# -*- coding: utf-8 -*-
"""
高蟾卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 33 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·长门怨二首 ----------
    {
        "id": "gao-chan-1",
        "title": "相和歌辞·长门怨二首",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "天上何劳万古春，君前谁是百年人。魂销尚愧金炉烬，",
            "思起犹惭玉辇尘。烟翠薄情攀不得，星芒浮艳采无因。",
            "可怜明镜来相向，何似恩光朝夕新。",
            "天上凤凰休寄梦，人间鹦鹉旧堪悲。",
            "平生心绪无人识，一只金梭万丈丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 途中除夜 ----------
    {
        "id": "gao-chan-2",
        "title": "途中除夜",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "南北浮萍迹，年华又暗催。残灯和腊尽，晓角带春来。",
            "鬓欲渐侵雪，心仍未肯灰。金门旧知己，谁为脱尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 长门怨 ----------
    {
        "id": "gao-chan-3",
        "title": "长门怨",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "天上何劳万古春，君前谁是百年人。魂销尚愧金炉烬，",
            "思起犹惭玉辇尘。烟翠薄情攀不得，星茫浮艳采无因。",
            "可怜明镜来相向，何似恩光朝夕新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 秋日寄华阳山人 ----------
    {
        "id": "gao-chan-4",
        "title": "秋日寄华阳山人",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "云木送秋何草草，风波凝冷太星星。银鞍公子魂俱断，",
            "玉弩将军涕自零。茅洞白龙和雨看，荆溪黄鹄带霜听。",
            "人间不见清凉事，犹向溪翁乞画屏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 感事 ----------
    {
        "id": "gao-chan-5",
        "title": "感事",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "浊河从北下，清洛向东流。清浊皆如此，何人不白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 楚思 ----------
    {
        "id": "gao-chan-6",
        "title": "楚思",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "叠浪与云急，翠兰和意香。风流化为雨，日暮下巫阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 雪中 ----------
    {
        "id": "gao-chan-7",
        "title": "雪中",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "金阁倚云开，朱轩犯雪来。三冬辛苦样，天意似难栽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 道中有感 ----------
    {
        "id": "gao-chan-8",
        "title": "道中有感",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "一醉六十日，一裘三十年。年华经几日，日日掉征鞭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 宋汴道中 ----------
    {
        "id": "gao-chan-9",
        "title": "宋汴道中",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "平野有千里，居人无一家。甲兵年正少，日久戍天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 秋思 ----------
    {
        "id": "gao-chan-10",
        "title": "秋思",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "天地太萧索，山川何渺茫。不堪星斗柄，犹把岁寒量。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 即事 ----------
    {
        "id": "gao-chan-11",
        "title": "即事",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "三年离水石，一旦隐樵渔。为问青云上，何人识卷舒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 渔家 ----------
    {
        "id": "gao-chan-12",
        "title": "渔家",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "野水千年在，闲花一夕空。近来浮世狭，何似钓船中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 关中 ----------
    {
        "id": "gao-chan-13",
        "title": "关中",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "风雨去愁晚，关河归思凉。西游无紫气，一夕九回肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 归思 ----------
    {
        "id": "gao-chan-14",
        "title": "归思",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "紫府归期断，芳洲别思迢。黄金作人世，只被岁寒消。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 下第出春明门 ----------
    {
        "id": "gao-chan-15",
        "title": "下第出春明门",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "曾和秋雨驱愁入，却向春风领恨回。",
            "深谢灞陵堤畔柳，与人头上拂尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 华清宫 ----------
    {
        "id": "gao-chan-16",
        "title": "华清宫",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "何事金舆不再游，翠鬟丹脸岂胜愁。",
            "重门深锁禁钟后，月满骊山宫树秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 秋日北固晚望二首 ----------
    {
        "id": "gao-chan-17",
        "title": "秋日北固晚望二首",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "风含远思翛翛晚，日照高情的的秋。",
            "何事满江惆怅水，年年无语向东流。",
            "泽国路岐当面苦，江城砧杵入心寒。",
            "不知白发谁医得，为问无情岁月看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送张道士 ----------
    {
        "id": "gao-chan-18",
        "title": "送张道士",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "因将岁月离三岛，闲贮风烟在一壶。",
            "为问金乌头白后，人间流水却回无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 吴门春雨 ----------
    {
        "id": "gao-chan-19",
        "title": "吴门春雨",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "吴甸落花春漫漫，吴宫芳树晚沈沈。",
            "王孙不耐如丝雨，罥断春风一寸心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 旅夕 ----------
    {
        "id": "gao-chan-20",
        "title": "旅夕",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "风散古陂惊宿雁，月临荒戍起啼鸦。",
            "不堪吟断无人见，时复寒灯落一花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 瓜洲夜泊 ----------
    {
        "id": "gao-chan-21",
        "title": "瓜洲夜泊",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "偶为芳草无情客，况是青山有事身。",
            "一夕瓜洲渡头宿，天风吹尽广陵尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 金陵晚望 ----------
    {
        "id": "gao-chan-22",
        "title": "金陵晚望",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "曾伴浮云归晚翠，犹陪落日泛秋声。",
            "世间无限丹青手，一片伤心画不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 晚思 ----------
    {
        "id": "gao-chan-23",
        "title": "晚思",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "虞泉冬恨由来短，杨叶春期分外长。",
            "惆怅浮生不知处，明朝依旧出沧浪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 长信宫二首（后首一作长门怨） ----------
    {
        "id": "gao-chan-24",
        "title": "长信宫二首（后首一作长门怨）",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "天上梦魂何杳杳，日宫消息太沈沈。",
            "君恩不似黄金井，一处团圆万丈深。",
            "天上凤凰休寄梦，人间鹦鹉旧堪悲。",
            "平生心绪无人识，一只金梭万丈丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 长安旅怀 ----------
    {
        "id": "gao-chan-25",
        "title": "长安旅怀",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "马嘶九陌年年苦，人语千门日日新。",
            "唯有终南寂无事，寒光不入帝乡尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 春 ----------
    {
        "id": "gao-chan-26",
        "title": "春",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "天柱几条支白日，天门几扇锁明时。",
            "阳春发处无根蒂，凭仗东风分外吹。",
            "明月断魂清霭霭，平芜归思绿迢迢。",
            "人生莫遣头如雪，纵得春风亦不消。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 秋 ----------
    {
        "id": "gao-chan-27",
        "title": "秋",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "阳羡溪声冷骇人，洞庭山翠晚凝神。",
            "天将金玉为风露，曾为高秋几度贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 灞陵亭 ----------
    {
        "id": "gao-chan-28",
        "title": "灞陵亭",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "一条归梦朱弦直，一片离心白羽轻。",
            "明日灞陵新霁后，马头烟树绿相迎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 偶作二首 ----------
    {
        "id": "gao-chan-29",
        "title": "偶作二首",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "丁当玉佩三更雨，平帖金闺一觉云。",
            "明日薄情何处去，风流春水不知君。",
            "霞衣重叠红蝉暖，云髻葱笼紫凤寒。",
            "天上少年分散后，一条烟水若为看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 永夕 ----------
    {
        "id": "gao-chan-30",
        "title": "永夕",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "云鸿宿处江村冷，独狖啼时海国阴。",
            "不会残灯无一事，觉来犹有向隅心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 落花 ----------
    {
        "id": "gao-chan-31",
        "title": "落花",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "一叶落时空下泪，三春归尽复何情。",
            "无人共得东风语，半日尊前计不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 下第后上永崇高侍郎 ----------
    {
        "id": "gao-chan-32",
        "title": "下第后上永崇高侍郎",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "天上碧桃和露种，日边红杏倚云栽。",
            "芙蓉生在秋江上，不向东风怨未开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 句 ----------
    {
        "id": "gao-chan-33",
        "title": "句",
        "author": "高蟾",
        "poet_id": "gao-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "君恩秋后叶，日日向人疏。（《宫词》）",
            "第六百六十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]