# -*- coding: utf-8 -*-
"""
贺知章卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 21 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·采莲曲 ----------
    {
        "id": "he-zhi-zhang-1",
        "title": "相和歌辞·采莲曲",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "稽山罢雾郁嵯峨，镜水无风也自波。",
            "莫言春度芳菲尽，别有中流采芰荷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 唐禅社首乐章·顺和 ----------
    {
        "id": "he-zhi-zhang-2",
        "title": "唐禅社首乐章·顺和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "至哉含柔德，万物资以生。常顺称厚载，流谦通变盈。",
            "圣心事能察，增广陈厥诚。黄祇僾如在，泰折俟咸亨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 唐禅社首乐章·太和 ----------
    {
        "id": "he-zhi-zhang-3",
        "title": "唐禅社首乐章·太和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "肃我成命，於昭黄祇。裘冕而祀，陟降在斯。",
            "五音克备，八变聿施。缉熙肆靖，厥心匪离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 唐禅社首乐章·肃和 ----------
    {
        "id": "he-zhi-zhang-4",
        "title": "唐禅社首乐章·肃和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "黄祇是祗，我其夙夜。夤畏诚絜，匪遑宁舍。",
            "礼以琮玉，荐厥茅藉。念兹降康，胡宁克暇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 唐禅社首乐章·雍和 ----------
    {
        "id": "he-zhi-zhang-5",
        "title": "唐禅社首乐章·雍和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "夙夜宥密，不敢宁宴。五齐既陈，八音在县。",
            "粢盛以絜，房俎斯荐。惟德惟馨，尚兹克遍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 唐禅社首乐章·寿和 ----------
    {
        "id": "he-zhi-zhang-6",
        "title": "唐禅社首乐章·寿和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "惟以明发，有怀载殷。乐盈而反，礼顺其禋。",
            "立清以献，荐欲是亲。於穆不已，裒对斯臻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 唐禅社首乐章·福和 ----------
    {
        "id": "he-zhi-zhang-7",
        "title": "唐禅社首乐章·福和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "穆穆天子，告成岱宗。大裘如濡，执珽有颙。",
            "乐以平志，礼以和容。上帝临我，云胡肃邕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 唐禅社首乐章·太和 ----------
    {
        "id": "he-zhi-zhang-8",
        "title": "唐禅社首乐章·太和",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "昭昭有唐，天俾万国。列祖应命，四宗顺则。",
            "申锡无疆，宗我同德。曾孙继绪，享神配极。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 晓发 ----------
    {
        "id": "he-zhi-zhang-9",
        "title": "晓发",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "江皋闻曙钟，轻枻理还舼。海潮夜约约，川露晨溶溶。",
            "始见沙上鸟，犹埋云外峰。故乡杳无际，明发怀朋从。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 奉和御制春台望 ----------
    {
        "id": "he-zhi-zhang-10",
        "title": "奉和御制春台望",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "青阳布王道，玄览陶真性。欣若天下春，高逾域中圣。",
            "神皋类观赏，帝里如悬镜。缭绕八川浮，岧峣双阙映。",
            "晓色遍昭阳，晴云卷建章。华滋的皪丹青树，",
            "颢气氤氲金玉堂。尚有灵蛇下鄜畤，还征瑞宝入陈仓。",
            "自昔秦奢汉穷武，后庭万馀宫百数。旗回五丈殿千门，",
            "连绵南隥出西垣。广画螓蛾夸窈窕，罗生玳瑁象昆仑。",
            "乃眷天晴兴隐恤，古来土木良非一。荆临章观赵丛台。",
            "何如尧阶将禹室。层栏窈窕下龙舆，清管逶迤半绮疏。",
            "一听南风引鸾舞，长谣北极仰鹑居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 望人家桃李花 ----------
    {
        "id": "he-zhi-zhang-11",
        "title": "望人家桃李花",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "山源夜雨度仙家，朝发东园桃李花。桃花红兮李花白，",
            "照灼城隅复南陌。南陌青楼十二重，春风桃李为谁容。",
            "弃置千金轻不顾，踟蹰五马谢相逢。徒言南国容华晚，",
            "遂叹西家飘落远。的皪长奉明光殿，氛氲半入披香苑。",
            "苑中珍木元自奇，黄金作叶白银枝。千年万岁不凋落，",
            "还将桃李更相宜。桃李从来露井傍，成蹊结影矜艳阳。",
            "莫道春花不可树，会持仙实荐君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送人之军 ----------
    {
        "id": "he-zhi-zhang-12",
        "title": "送人之军",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "常经绝脉塞，复见断肠流。送子成今别，令人起昔愁。",
            "陇云晴半雨，边草夏先秋。万里长城寄，无贻汉国忧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 奉和圣制送张说上集贤学士赐宴赋得谟字 ----------
    {
        "id": "he-zhi-zhang-13",
        "title": "奉和圣制送张说上集贤学士赐宴赋得谟字",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "西学垂玄览，东堂发圣谟。天光烛武殿，时宰集鸿都。",
            "枯朽沾皇泽，翾飞舞帝梧。迹同游汗漫，荣是出泥涂。",
            "三叹承汤鼎，千欢接舜壶。微躯不可答，空欲咏依蒲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 奉和圣制送张说巡边 ----------
    {
        "id": "he-zhi-zhang-14",
        "title": "奉和圣制送张说巡边",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "荒憬尽怀忠，梯航已自通。九攻虽不战，五月尚持戎。",
            "遣戍征周牒，恢边重汉功。选车命元宰，授律取文雄。",
            "胄出天弧上，谋成帝幄中。诏旂分夏物，专土锡唐弓。",
            "帐宿伊川右，钲传晋苑东。饔人藉蕡实，乐正理丝桐。",
            "岐陌涵馀雨，离川照晚虹。恭闻咏方叔，千载舞皇风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 题袁氏别业（一作偶游主人园） ----------
    {
        "id": "he-zhi-zhang-15",
        "title": "题袁氏别业（一作偶游主人园）",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "主人不相识，偶坐为林泉。莫谩愁沽酒，囊中自有钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 咏柳（一作柳枝词） ----------
    {
        "id": "he-zhi-zhang-16",
        "title": "咏柳（一作柳枝词）",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "碧玉妆成一树高，万条垂下绿丝绦。",
            "不知细叶谁裁出，二月春风似剪刀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 采莲曲 ----------
    {
        "id": "he-zhi-zhang-17",
        "title": "采莲曲",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "稽山罢雾郁嵯峨，镜水无风也自波。",
            "莫言春度芳菲尽，别有中流采芰荷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 回乡偶书二首 ----------
    {
        "id": "he-zhi-zhang-18",
        "title": "回乡偶书二首",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "少小离乡老大回，乡音难改鬓毛衰。",
            "儿童相见不相识，笑问客从何处来。",
            "离别家乡岁月多，近来人事半销磨。",
            "唯有门前镜湖水，春风不改旧时波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 答朝士 ----------
    {
        "id": "he-zhi-zhang-19",
        "title": "答朝士",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "fk镂银盘盛蛤蜊，镜湖莼菜乱如丝。",
            "乡曲近来佳此味，遮渠不道是吴儿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 句 ----------
    {
        "id": "he-zhi-zhang-20",
        "title": "句",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "落花真好些，一醉一回颠。（见《诗式》）",
            "第一百一十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 答朝士 ----------
    {
        "id": "he-zhi-zhang-21",
        "title": "答朝士",
        "author": "贺知章",
        "poet_id": "he-zhi-zhang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "fk镂银盘盛蛤蜊，镜湖莼菜乱如丝。",
            "乡曲近来佳此味，遮渠不道是吴儿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]