# -*- coding: utf-8 -*-
"""
处默卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 圣果寺 ----------
    {
        "id": "chu-mo-1",
        "title": "圣果寺",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "路自中峰上，盘回出薜萝。到江吴地尽，隔岸越山多。",
            "古木丛青霭，遥天浸白波。下方城郭近，钟磬杂笙歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送僧游西域 ----------
    {
        "id": "chu-mo-2",
        "title": "送僧游西域",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "一盂兼一锡，只此度流沙。野性虽为客，禅心即是家。",
            "寺披云峤雪，路入晓天霞。自说游诸国，回应岁月赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 远烟 ----------
    {
        "id": "chu-mo-3",
        "title": "远烟",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "霭霭前山上，凝光满薜萝。高风吹不尽，远树得偏多。",
            "翠与晴云合，轻将淑气和。正堪流野目，朱阁意如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 萤 ----------
    {
        "id": "chu-mo-4",
        "title": "萤",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "熠熠与娟娟，池塘竹树边。乱飞如拽火，成聚却无烟。",
            "微雨洒不灭，轻风吹欲燃。昔时书案上，频把作囊悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 忆庐山旧居 ----------
    {
        "id": "chu-mo-5",
        "title": "忆庐山旧居",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "粗衣粝食老烟霞，勉把衰颜惜岁华。独鹤只为山客伴，",
            "闲云常在野僧家。丛生嫩蕨粘松粉，自落干薪带藓花。",
            "明月清风旧相得，十年归恨可能赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 题栖霞寺僧房 ----------
    {
        "id": "chu-mo-6",
        "title": "题栖霞寺僧房",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "名山不取买山钱，任构花宫近碧巅。松桧老依云里寺，",
            "楼台深锁洞中天。风经绝嶂回疏雨，石倚危屏挂落泉。",
            "欲结茅庵共师住，肯饶多少薜萝烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 山中作 ----------
    {
        "id": "chu-mo-7",
        "title": "山中作",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "席帘高卷枕高欹，门掩垂萝蘸碧溪。",
            "闲把史书眠一觉，起来山日过松西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 织妇 ----------
    {
        "id": "chu-mo-8",
        "title": "织妇",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "蓬鬓蓬门积恨多，夜阑灯下不停梭。",
            "成缣犹自陪钱纳，未直青楼一曲歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 句 ----------
    {
        "id": "chu-mo-9",
        "title": "句",
        "author": "处默",
        "poet_id": "chu-mo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "太平时节无人看，雪刃闲封满匣尘。（《剑》，",
            "见王正字《诗格》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]