# -*- coding: utf-8 -*-
"""
周昙卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 195 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 吟叙 ----------
    {
        "id": "zhou-tan-1",
        "title": "吟叙",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "历代兴亡亿万心，圣人观古贵知今。",
            "古今成败无多事，月殿花台幸一吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 闲吟 ----------
    {
        "id": "zhou-tan-2",
        "title": "闲吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "考摭妍媸用破心，剪裁千古献当今。",
            "闲吟不是闲吟事，事有闲思闲要吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 唐虞门·唐尧 ----------
    {
        "id": "zhou-tan-3",
        "title": "唐虞门·唐尧",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "祅氛不起瑞烟轻，端拱垂衣日月明。",
            "传事四方无外役，茅茨深处土阶平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 唐虞门·虞舜 ----------
    {
        "id": "zhou-tan-4",
        "title": "唐虞门·虞舜",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "进善惩奸立帝功，功成揖让益温恭。",
            "满朝卿士多元凯，为黜兜苗与四凶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 唐虞门·舜妃 ----------
    {
        "id": "zhou-tan-5",
        "title": "唐虞门·舜妃",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "苍梧一望隔重云，帝子悲寻不记春。",
            "何事泪痕偏在竹，贞姿应念节高人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 唐虞门·再吟 ----------
    {
        "id": "zhou-tan-6",
        "title": "唐虞门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "潇湘何代泣幽魂，骨化重泉志尚存。",
            "若道地中休下泪，不应新竹有啼痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 三代门·夏禹 ----------
    {
        "id": "zhou-tan-7",
        "title": "三代门·夏禹",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "尧违天孽赖询谟，顿免洪波浸碧虚。",
            "海内生灵微伯禹，尽应随浪化为鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 三代门·再吟 ----------
    {
        "id": "zhou-tan-8",
        "title": "三代门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "万古龙门一旦开，无成甘死作黄能。",
            "司空定有匡尧术，九载之前何处来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 三代门·太康 ----------
    {
        "id": "zhou-tan-9",
        "title": "三代门·太康",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "师保何人为琢磨，安知父祖苦辛多。",
            "酒酣禽色方为乐，讵肯闲听五子歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 三代门·后稷 ----------
    {
        "id": "zhou-tan-10",
        "title": "三代门·后稷",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "人惟邦本本由农，旷古谁高后稷功。",
            "百谷且繁三曜在，牲牢郊祀信无穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 三代门·文王 ----------
    {
        "id": "zhou-tan-11",
        "title": "三代门·文王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "昭然明德报天休，礿祭惟馨胜杀牛。",
            "二老五侯何所诈，不归商受尽归周。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 三代门·武王 ----------
    {
        "id": "zhou-tan-12",
        "title": "三代门·武王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "文王寝膳武王随，内竖言安色始怡。",
            "七载岂堪囚羑里，一夫为报亦何疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 三代门·太公 ----------
    {
        "id": "zhou-tan-13",
        "title": "三代门·太公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "昌猎关西纣猎东，纣怜崇虎弃非熊。",
            "危邦自谓多麟凤，肯把王纲取钓翁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 三代门·再吟 ----------
    {
        "id": "zhou-tan-14",
        "title": "三代门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "东邻不事事西邻，御物卑和物自亲。",
            "天下言知天下者，兆人无主属贤人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 三代门·又吟 ----------
    {
        "id": "zhou-tan-15",
        "title": "三代门·又吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "千妖万态逞妍姿，破国亡家更是谁。",
            "匡政必能除苟媚，去邪当断勿狐疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 三代门·子牙妻 ----------
    {
        "id": "zhou-tan-16",
        "title": "三代门·子牙妻",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "陵柏无心竹变秋，不能同戚拟同休。",
            "岁寒焉在空垂涕，覆水如何欲再收。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 三代门·周公 ----------
    {
        "id": "zhou-tan-17",
        "title": "三代门·周公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "文武传芳百代基，几多贤哲守成规。",
            "仍闻吐握延儒素，犹恐民疵未尽知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 三代门·夷齐 ----------
    {
        "id": "zhou-tan-18",
        "title": "三代门·夷齐",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "让国由衷义亦乖，不知天命匹夫才。",
            "将除暴虐诚能阻，何异崎岖助纣来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 三代门·管蔡 ----------
    {
        "id": "zhou-tan-19",
        "title": "三代门·管蔡",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "伊商胡越尚同图，管蔡如何有异谟。",
            "不念祖宗危社稷，强于仁圣遣行诛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 三代门·成王 ----------
    {
        "id": "zhou-tan-20",
        "title": "三代门·成王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "成王有过伯禽笞，圣惠能新日自奇。",
            "王道既成何所感，越裳呈瑞凤来仪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 三代门·幽王 ----------
    {
        "id": "zhou-tan-21",
        "title": "三代门·幽王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "狼烟篝火为边尘，烽候那宜悦妇人。",
            "厚德未闻闻厚色，不亡家国幸亡身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 三代门·平王 ----------
    {
        "id": "zhou-tan-22",
        "title": "三代门·平王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "犬戎西集杀幽王，邦土何由不便亡。",
            "宜臼东来年更远，川流难绝信源长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 春秋战国门·祭足 ----------
    {
        "id": "zhou-tan-23",
        "title": "春秋战国门·祭足",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "吴鲁燕韩岂别宗，曾无外御但相攻。",
            "当时周郑谁为相，交质将何服远戎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-24",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "周室衰微不共匡，干戈终日互争强。",
            "诸侯若解尊天子，列国何因次第亡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 春秋战国门·隐公 ----------
    {
        "id": "zhou-tan-25",
        "title": "春秋战国门·隐公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "今古难堤是小人，苟希荣宠任相亲。",
            "陈谋不信怀忧惧，反间须防却害身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 春秋战国门·庄公 ----------
    {
        "id": "zhou-tan-26",
        "title": "春秋战国门·庄公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "齐甲强临力有馀，鲁庄为战念区区。",
            "鱼丽三鼓微曹刿，肉食安能暇远谟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 春秋战国门·哀公 ----------
    {
        "id": "zhou-tan-27",
        "title": "春秋战国门·哀公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "贤为邻用国忧危，庙算无非委艳奇。",
            "两叶翠娥春乍展，一毛须去不难吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-28",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "好龙天为降真龙，及见真龙瘁厥躬。",
            "接下不勤徒好士，叶公何异鲁哀公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 春秋战国门·平公 ----------
    {
        "id": "zhou-tan-29",
        "title": "春秋战国门·平公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "鸿鹄轻腾万里高，何殊朝野得贤豪。",
            "能知翼戴穹苍力，不是蒙茸腹背毛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 春秋战国门·文公 ----------
    {
        "id": "zhou-tan-30",
        "title": "春秋战国门·文公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "灭虢吞虞未息兵，柔秦败楚霸威成。",
            "文公徒欲三强服，分晋元来是六卿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 春秋战国门·景公 ----------
    {
        "id": "zhou-tan-31",
        "title": "春秋战国门·景公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "觉病当宜早问师，病深难疗恨难追。",
            "晋侯徒有秦医缓，疾在膏肓救已迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 春秋战国门·卫灵公 ----------
    {
        "id": "zhou-tan-32",
        "title": "春秋战国门·卫灵公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "子鱼无隐欲源清，死不忘忠感卫灵。",
            "伯玉既亲知德润，残桃休吃悟兰馨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 春秋战国门·陈灵公 ----------
    {
        "id": "zhou-tan-33",
        "title": "春秋战国门·陈灵公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "谁与陈君嫁祸来，孔宁行父夏姬媒。",
            "灵公徒认徵舒面，至死何曾识祸胎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 春秋战国门·陈蔡君 ----------
    {
        "id": "zhou-tan-34",
        "title": "春秋战国门·陈蔡君",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "楚聘宣尼欲道光，是时陈蔡畏邻强。",
            "庸谋但解遮贤路，不解迎贤谋自昌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 春秋战国门·楚惠王 ----------
    {
        "id": "zhou-tan-35",
        "title": "春秋战国门·楚惠王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "芹中遇蛭强为吞，不欲缘微有害人。",
            "何事免成心腹疾，皇天惟德是相亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 春秋战国门·楚怀王 ----------
    {
        "id": "zhou-tan-36",
        "title": "春秋战国门·楚怀王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "不听陈轸信张仪，六里商於果见欺。",
            "既舍黔中西换得，又令生去益堪悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-37",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "不得商於又失齐，楚怀方寸一何迷。",
            "明知秦是虎狼国，更忍车轮独向西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 春秋战国门·韩惠王 ----------
    {
        "id": "zhou-tan-38",
        "title": "春秋战国门·韩惠王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "韩惠开渠止暴秦，营田万顷饱秦人。",
            "何殊般肉供羸兽，兽壮安知不害身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 春秋战国门·顷襄王 ----------
    {
        "id": "zhou-tan-39",
        "title": "春秋战国门·顷襄王",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "秦陷荆王死不还，只缘偏听子兰言。",
            "顷襄还信子兰语，忍使江鱼葬屈原。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 春秋战国门·武公 ----------
    {
        "id": "zhou-tan-40",
        "title": "春秋战国门·武公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "猛兽来兵只为文，岂宜凉德拟图尊。",
            "君看豹彩蒙麋质，人取无难必不存。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 春秋战国门·华元 ----------
    {
        "id": "zhou-tan-41",
        "title": "春秋战国门·华元",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "未知军法忌偏颇，徒解于思腹漫皤。",
            "昔日羊斟曾不预，今朝为政事如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 春秋战国门·臧孙 ----------
    {
        "id": "zhou-tan-42",
        "title": "春秋战国门·臧孙",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "诸孟憎吾似犬狞，贤臧哭孟倍伤情。",
            "季孙爱我如甘疾，疾足亡身药故宁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 春秋战国门·公叔 ----------
    {
        "id": "zhou-tan-43",
        "title": "春秋战国门·公叔",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "吴起南奔魏国荒，必听公叔失贤良。",
            "无谋纵欲离安邑，可免河沟徙大梁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 春秋战国门·庄辛 ----------
    {
        "id": "zhou-tan-44",
        "title": "春秋战国门·庄辛",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "庄辛正谏谓妖词，兵及鄢陵始悔思。",
            "见兔必能知顾犬，亡羊补栈未为迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 春秋战国门·孙膑 ----------
    {
        "id": "zhou-tan-45",
        "title": "春秋战国门·孙膑",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "曾嫌胜己害贤人，钻火明知速自焚。",
            "断足尔能行不足，逢君谁肯不酬君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 春秋战国门·灵辄 ----------
    {
        "id": "zhou-tan-46",
        "title": "春秋战国门·灵辄",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "失水枯鳞得再生，翳桑无地谢深情。",
            "朱轮未染酬恩血，公子何由见赤诚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 春秋战国门·郭开 ----------
    {
        "id": "zhou-tan-47",
        "title": "春秋战国门·郭开",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "秦袭邯郸岁月深，何人沾赠郭开金。",
            "廉颇还国李牧在，安得赵王为尔擒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 春秋战国门·乐羊 ----------
    {
        "id": "zhou-tan-48",
        "title": "春秋战国门·乐羊",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "杯羹忍啜得非忠，巧佞胡为惑主聪。",
            "盈箧谤书能寝默，中山不是乐羊功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 春秋战国门·虞卿 ----------
    {
        "id": "zhou-tan-49",
        "title": "春秋战国门·虞卿",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "割地求和国必危，安知坚守绝来思。",
            "年年来伐年年割，割尽邯郸何所之。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 春秋战国门·豫让 ----------
    {
        "id": "zhou-tan-50",
        "title": "春秋战国门·豫让",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "门客家臣义莫俦，漆身吞炭不能休。",
            "中行智伯思何异，国士终期国士酬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 春秋战国门·毛遂 ----------
    {
        "id": "zhou-tan-51",
        "title": "春秋战国门·毛遂",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "不识囊中颖脱锥，功成方信有英奇。",
            "平原门下三千客，得力何曾是素知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-52",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "定获英奇不在多，然须设网遍山河。",
            "禽虽一目罗中得，岂可空张一目罗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 春秋战国门·田文 ----------
    {
        "id": "zhou-tan-53",
        "title": "春秋战国门·田文",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "下客常才不足珍，谁为狗盗脱强秦。",
            "秦关若待鸡鸣出，笑杀临淄土偶人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-54",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "门下三千各自矜，频弹剑客独无能。",
            "田文不厌无能客，三窟全身果有凭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 春秋战国门·冯讙 ----------
    {
        "id": "zhou-tan-55",
        "title": "春秋战国门·冯讙",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "兔窟穿成主再兴，辈流狐伏敢骄矜。",
            "冯讙不是无能者，要试君心欲展能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 春秋战国门·章子 ----------
    {
        "id": "zhou-tan-56",
        "title": "春秋战国门·章子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "在家能子必能臣，齐将功成以孝闻。",
            "改葬义无欺死父，临戎安肯背生君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 春秋战国门·卞和 ----------
    {
        "id": "zhou-tan-57",
        "title": "春秋战国门·卞和",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "磷磷谁为惑温温，至宝凡姿甚易分。",
            "自是时人多贵耳，目无明鉴使俱焚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 春秋战国门·季札 ----------
    {
        "id": "zhou-tan-58",
        "title": "春秋战国门·季札",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "吹毛霜刃过千金，生许徐君死挂林。",
            "宝剑徒称无价宝，行心更贵不欺心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 春秋战国门·孙武 ----------
    {
        "id": "zhou-tan-59",
        "title": "春秋战国门·孙武",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "理国无难似理兵，兵家法令贵遵行。",
            "行刑不避君王宠，一笑随刀八阵成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 春秋战国门·夫差 ----------
    {
        "id": "zhou-tan-60",
        "title": "春秋战国门·夫差",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "信听谗言疾不除，忠臣须杀竟何如。",
            "会稽既雪夫差死，泉下胡颜见子胥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 春秋战国门·少孺 ----------
    {
        "id": "zhou-tan-61",
        "title": "春秋战国门·少孺",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "宝贵亲仁与善邻，邻兵何要互相臻。",
            "螳螂定是遭黄雀，黄雀须防挟弹人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 春秋战国门·苏厉 ----------
    {
        "id": "zhou-tan-62",
        "title": "春秋战国门·苏厉",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "百步穿杨箭不移，养由堪教听弘规。",
            "身隆业著未知退，勿遣功名一旦隳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 春秋战国门·鬻拳 ----------
    {
        "id": "zhou-tan-63",
        "title": "春秋战国门·鬻拳",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "鬻拳强谏惧威刑，退省怀惭不顾生。",
            "双刖忍行留痛恨，惟君适足见忠诚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 春秋战国门·荆轲 ----------
    {
        "id": "zhou-tan-64",
        "title": "春秋战国门·荆轲",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "反刃相酬是匹夫，安知突骑驾群胡。",
            "有心为报怀权略，可在於期与地图。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-65",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "几尺如霜利不群，恩仇未报反亡身。",
            "诚哉利器全由用，可惜吹毛不得人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 春秋战国门·陈轸 ----------
    {
        "id": "zhou-tan-66",
        "title": "春秋战国门·陈轸",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "丹青徒有逞喧哗，有足由来不是蛇。",
            "杀将破军为柱国，君今官极更何加。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 春秋战国门·田饶 ----------
    {
        "id": "zhou-tan-67",
        "title": "春秋战国门·田饶",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "厨抛败肉士怀饥，仓烂馀粮客未炊。",
            "临难欲行求死士，将何恩信致扶危。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 春秋战国门·鲍叔 ----------
    {
        "id": "zhou-tan-68",
        "title": "春秋战国门·鲍叔",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "忠臣祝寿吐嘉词，鲍叔临轩酒一卮。",
            "安不忘危臣所愿，愿思危困必无危。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 春秋战国门·晏婴 ----------
    {
        "id": "zhou-tan-69",
        "title": "春秋战国门·晏婴",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "正人徒以刃相危，贪利忘忠死不为。",
            "麋鹿命悬当有处，驱车何必用奔驰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-70",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "下泽逢蛇盖是常，还如山上见豺狼。",
            "国中有怪非蛇兽，不用贤能是不祥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 春秋战国门·又吟 ----------
    {
        "id": "zhou-tan-71",
        "title": "春秋战国门·又吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "马毙厩人欲就刑，百年临尽一言生。",
            "赖逢贤相能匡救，仍免吾君播恶声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 春秋战国门·叔向 ----------
    {
        "id": "zhou-tan-72",
        "title": "春秋战国门·叔向",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "重禄存家不敢言，小臣忧祸亦如然。",
            "明开谏诤能无罪，只此宜为理国先。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 春秋战国门·师旷 ----------
    {
        "id": "zhou-tan-73",
        "title": "春秋战国门·师旷",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "老能劝学照馀生，似夜随灯到处明。",
            "往行前言如不见，暗中无烛若为行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 春秋战国门·智伯 ----------
    {
        "id": "zhou-tan-74",
        "title": "春秋战国门·智伯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "三国连兵敌就擒，晋阳城下碧波深。",
            "风涛撼处看沈赵，舟楫不从翻自沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-75",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "攻城来下惜先分，一旦家邦属四邻。",
            "徒逞威强称智伯，不知权变是愚人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 春秋战国门·襄子 ----------
    {
        "id": "zhou-tan-76",
        "title": "春秋战国门·襄子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "君子常闻不迫危，城崩何用急重围。",
            "叛亡能退修文德，果见中牟以义归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 春秋战国门·杨回 ----------
    {
        "id": "zhou-tan-77",
        "title": "春秋战国门·杨回",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "三逐乡闾五去君，莫知何地可容身。",
            "杨回不是逢英鉴，白首无成一旅人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 春秋战国门·颜回 ----------
    {
        "id": "zhou-tan-78",
        "title": "春秋战国门·颜回",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "陋巷箪瓢困有年，是时端木饫腥膻。",
            "宣尼行教何形迹，不肯分甘救子渊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 春秋战国门·子贡 ----------
    {
        "id": "zhou-tan-79",
        "title": "春秋战国门·子贡",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "救鲁亡吴事可伤，谁令利口说田常。",
            "吴亡必定由端木，鲁亦宜其运不长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-80",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "一言能使定安危，安己危人是所宜。",
            "仁义不思垂教化，背恩亡德岂儒为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 春秋战国门·郑相 ----------
    {
        "id": "zhou-tan-81",
        "title": "春秋战国门·郑相",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "郑相清贤慎有馀，好鱼鱼至竟何如。",
            "退鱼留得终身禄，禄在何忧不得鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 春秋战国门·子产 ----------
    {
        "id": "zhou-tan-82",
        "title": "春秋战国门·子产",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "为政何门是化源，宽仁高下保安全。",
            "如嫌水德人多狎，拯溺宜将猛济宽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 春秋战国门·管仲 ----------
    {
        "id": "zhou-tan-83",
        "title": "春秋战国门·管仲",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "美酒浓馨客要沽，门深谁敢强提壶。",
            "苟非贤主询贤士，肯信沽人畏子獹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-84",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "社鼠穿墙巧庇身，何由攻灌若为熏。",
            "能知窟穴依形势，不听谗邪是圣君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 春秋战国门·范蠡 ----------
    {
        "id": "zhou-tan-85",
        "title": "春秋战国门·范蠡",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "西子能令转嫁吴，会稽知尔啄姑苏。",
            "迹高尘外功成处，一叶翩翩在五湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 春秋战国门·屈原 ----------
    {
        "id": "zhou-tan-86",
        "title": "春秋战国门·屈原",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "满朝皆醉不容醒，众浊如何拟独清。",
            "江上流人真浪死，谁知浸润误深诚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 春秋战国门·黄歇 ----------
    {
        "id": "zhou-tan-87",
        "title": "春秋战国门·黄歇",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "春申随质若王图，为主轻生大丈夫。",
            "女子异心安足听，功成何更用阴谟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 春秋战国门·王后 ----------
    {
        "id": "zhou-tan-88",
        "title": "春秋战国门·王后",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "连环要解解非难，忽碎瑶阶一旦间。",
            "两国相持兵不解，会应俱碎似连环。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 春秋战国门·樊姬 ----------
    {
        "id": "zhou-tan-89",
        "title": "春秋战国门·樊姬",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "侧影频移未退朝，喜逢贤相日从高。",
            "当时不有樊姬问，令尹何由进叔敖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 春秋战国门·齐桓公 ----------
    {
        "id": "zhou-tan-90",
        "title": "春秋战国门·齐桓公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "三往何劳万乘君，五来方见一微臣。",
            "微臣傲爵能轻主，霸主如何敢傲人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 春秋战国门·中山君 ----------
    {
        "id": "zhou-tan-91",
        "title": "春秋战国门·中山君",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "敌临烹子一何庸，激怒来军速自攻。",
            "结怨岂思围不解，愚谋多以杀为雄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 春秋战国门·赵简子 ----------
    {
        "id": "zhou-tan-92",
        "title": "春秋战国门·赵简子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "简子雄心蓄霸机，贤愚聊欲试诸儿。",
            "假言藏宝非真宝，不是生知焉得知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-93",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷93》",
        "verse": [
            "谔谔能昌唯唯亡，亦由匡正得贤良。",
            "一从忠谠无周舍，吾过何人为短长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 春秋战国门·赵宣子 ----------
    {
        "id": "zhou-tan-94",
        "title": "春秋战国门·赵宣子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "门人曾不有提弥，连嗾呀呀孰敢支。",
            "临难若教无苟免，乱朝争那以獒为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 春秋战国门·韩昭侯 ----------
    {
        "id": "zhou-tan-95",
        "title": "春秋战国门·韩昭侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷95》",
        "verse": [
            "去年秦伐我宜阳，今岁天灾旱且荒。",
            "对此不思人力困，楼门何可更高张。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 春秋战国门·魏文侯 ----------
    {
        "id": "zhou-tan-96",
        "title": "春秋战国门·魏文侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷96》",
        "verse": [
            "冒雨如何固出畋，虑乖群约失乾乾。",
            "文侯不是贪禽者，示信将为教化先。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 春秋战国门·郤成子 ----------
    {
        "id": "zhou-tan-97",
        "title": "春秋战国门·郤成子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷97》",
        "verse": [
            "陈乐无欢璧在隅，宰臣怀智有微谟。",
            "苟非成子当明哲，谁是仁人可托孤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 春秋战国门·秦武阳 ----------
    {
        "id": "zhou-tan-98",
        "title": "春秋战国门·秦武阳",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷98》",
        "verse": [
            "丱岁徒闻有壮名，及令为副误荆卿。",
            "是时环柱能相副，谁谓燕囚事不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 春秋战国门·田子方 ----------
    {
        "id": "zhou-tan-99",
        "title": "春秋战国门·田子方",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷99》",
        "verse": [
            "太子无嫌礼乐亏，愿听贫富与安危。",
            "贱贫骄物贫终在，富贵骄人贵必隳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 春秋战国门·淳于髡 ----------
    {
        "id": "zhou-tan-100",
        "title": "春秋战国门·淳于髡",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷100》",
        "verse": [
            "穰穰何祷手何赍，一呷村浆与只鸡。",
            "以少求多诚可笑，还如轻币欲全齐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-101",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷101》",
        "verse": [
            "戏问将何对所耽，滑稽无骨是常谭。",
            "昔时王者皆通四，近见君王只好三。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-102",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷102》",
        "verse": [
            "曲突徙薪不谓贤，焦头烂额飨盘筵。",
            "时人多是轻先见，不独田家国亦然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 春秋战国门·田子奇 ----------
    {
        "id": "zhou-tan-103",
        "title": "春秋战国门·田子奇",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷103》",
        "verse": [
            "少年为吏虑非循，一骑奔追委使臣。",
            "使者不追何所对，车中缘见白头人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 春秋战国门·百里奚 ----------
    {
        "id": "zhou-tan-104",
        "title": "春秋战国门·百里奚",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷104》",
        "verse": [
            "船骥由来是股肱，在虞虞灭在秦兴。",
            "裁量何异刀将尺，只系用之能不能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 春秋战国门·孙叔敖 ----------
    {
        "id": "zhou-tan-105",
        "title": "春秋战国门·孙叔敖",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷105》",
        "verse": [
            "童稚逢蛇叹不祥，虑悲来者为埋藏。",
            "是知阳报由阴施，天爵昭然契日彰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 春秋战国门·鲁仲连 ----------
    {
        "id": "zhou-tan-106",
        "title": "春秋战国门·鲁仲连",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷106》",
        "verse": [
            "昔迸烧牛发战机，夜奔惊火走燕师。",
            "今来跃马怀骄惰，十万如无一撮时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 春秋战国门·宋子罕 ----------
    {
        "id": "zhou-tan-107",
        "title": "春秋战国门·宋子罕",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷107》",
        "verse": [
            "子怜温润欲归仁，吾贵坚廉是宝身。",
            "自有不贪身内宝，玉人徒献外来珍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 春秋战国门·宫之奇 ----------
    {
        "id": "zhou-tan-108",
        "title": "春秋战国门·宫之奇",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷108》",
        "verse": [
            "虞虢相依自保安，谋臣吞度不为难。",
            "贪怜璧马迷香饵，肯信之奇谕齿寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 春秋战国门·王孙满 ----------
    {
        "id": "zhou-tan-109",
        "title": "春秋战国门·王孙满",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷109》",
        "verse": [
            "九牧金熔物像成，辞昏去乱祚休明。",
            "兴亡在德不在鼎，楚子何劳问重轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 春秋战国门·颜叔子 ----------
    {
        "id": "zhou-tan-110",
        "title": "春秋战国门·颜叔子",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷110》",
        "verse": [
            "夜雨邻娃告屋倾，一宵从寄念悲惊。",
            "诚知独处从烧烛，君子行心要自明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 春秋战国门·张孟谭 ----------
    {
        "id": "zhou-tan-111",
        "title": "春秋战国门·张孟谭",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷111》",
        "verse": [
            "强兵四合国将危，赖有谋臣为发挥。",
            "城内蒿铜诚自有，无谋谁解见玄机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 春秋战国门·公子无忌 ----------
    {
        "id": "zhou-tan-112",
        "title": "春秋战国门·公子无忌",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷112》",
        "verse": [
            "按剑临笼震咄呼，鹞甘枭戮伏鸠辜。",
            "能怜钝拙诛豪俊，悯弱摧强真丈夫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-113",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷113》",
        "verse": [
            "赵解重围魏再昌，信陵贤德日馨芳。",
            "昏蒙愚主听谗说，公子云亡国亦亡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 春秋战国门·侯嬴朱亥 ----------
    {
        "id": "zhou-tan-114",
        "title": "春秋战国门·侯嬴朱亥",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷114》",
        "verse": [
            "屠肆监门一贱微，信陵交结国人非。",
            "当时不是二君计，匹马那能解赵围。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 春秋战国门·再吟 ----------
    {
        "id": "zhou-tan-115",
        "title": "春秋战国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷115》",
        "verse": [
            "走敌存亡义有馀，全由雄勇与英谟。",
            "但如公子能交结，朱亥侯嬴何代无。",
            "第七百二十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 秦门·胡亥 ----------
    {
        "id": "zhou-tan-116",
        "title": "秦门·胡亥",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "鹿马何难辨是非，宁劳卜筮问安危。",
            "权臣为乱多如此，亡国时君不自知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 秦门·再吟 ----------
    {
        "id": "zhou-tan-117",
        "title": "秦门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "盗贼纵横主恶闻，遂为流矢犯君轩。",
            "怪言何不早言者，若使早言还不存。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 秦门·赵高 ----------
    {
        "id": "zhou-tan-118",
        "title": "秦门·赵高",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "赵高胡亥速天诛，率土兴兵怨毒痡。",
            "丰沛见机群小吏，功成儿戏亦何殊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 秦门·陈涉 ----------
    {
        "id": "zhou-tan-119",
        "title": "秦门·陈涉",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "秦法烦苛霸业隳，一夫攘臂万夫随。",
            "王侯无种英雄志，燕雀喧喧安得知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 秦门·项籍 ----------
    {
        "id": "zhou-tan-120",
        "title": "秦门·项籍",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "九垓垂定弃谋臣，一阵无功便杀身。",
            "壮士诚知轻性命，不思辜负八千人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 秦门·范增 ----------
    {
        "id": "zhou-tan-121",
        "title": "秦门·范增",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "智士宁为暗主谟，范公曾不读兵书。",
            "平生心力为谁尽，一事无成空背疽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 前汉门·高祖 ----------
    {
        "id": "zhou-tan-122",
        "title": "前汉门·高祖",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "爱子从烹报主时，安知强啜不含悲。",
            "太公悬命临刀几，忍取杯羹欲为谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 前汉门·再吟 ----------
    {
        "id": "zhou-tan-123",
        "title": "前汉门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "北伐匈奴事可悲，当时将相是其谁。",
            "君臣束手平城里，三十万兵能忍饥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 前汉门·周苛纪信 ----------
    {
        "id": "zhou-tan-124",
        "title": "前汉门·周苛纪信",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "为主坚能不顾身，赴汤蹈火见忠臣。",
            "后来邦国论心义，谁是君王出热人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 前汉门·酂侯 ----------
    {
        "id": "zhou-tan-125",
        "title": "前汉门·酂侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "共怪酂侯第一功，咸称得地合先封。",
            "韩生不是萧君荐，猎犬何人为指踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 前汉门·曲逆侯 ----------
    {
        "id": "zhou-tan-126",
        "title": "前汉门·曲逆侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "社肉分平未足奇，须观大用展无私。",
            "一朝如得宰天下，必使还如宰社时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 前汉门·薛公 ----------
    {
        "id": "zhou-tan-127",
        "title": "前汉门·薛公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "黥布称兵孰敢当，薛公三计为斟量。",
            "上中良策知非用，南取长沙是死乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 前汉门·条侯 ----------
    {
        "id": "zhou-tan-128",
        "title": "前汉门·条侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "上将风戈赏罚明，矛鋋严闭亚夫营。",
            "人君却禀将军令，按辔垂鞭为缓行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 前汉门·平津侯 ----------
    {
        "id": "zhou-tan-129",
        "title": "前汉门·平津侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "儒素逢时得自媒，忽从徒步列公台。",
            "北辰如不延吾辈，东阁何由逐汝开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 前汉门·博陆侯 ----------
    {
        "id": "zhou-tan-130",
        "title": "前汉门·博陆侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "栋梁徒自保坚贞，毁穴难防雀鼠争。",
            "不是主人知诈伪，如何柱石免欹倾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 前汉门·夏贺良 ----------
    {
        "id": "zhou-tan-131",
        "title": "前汉门·夏贺良",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "汉代中微亦再昌，忠臣忧国冀修禳。",
            "赤精符谶诚非妄，枉杀无辜夏贺良。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 前汉门·王莽 ----------
    {
        "id": "zhou-tan-132",
        "title": "前汉门·王莽",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "权归诸吕牝鸡鸣，殷鉴昭然讵可轻。",
            "新室不因崇外戚，水中安敢寄生营。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 前汉门·再吟 ----------
    {
        "id": "zhou-tan-133",
        "title": "前汉门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "重赋严刑作祸胎，岂知由此乱离媒。",
            "家传揖让亦难济，况是身从倾篡来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 前汉门·又吟 ----------
    {
        "id": "zhou-tan-134",
        "title": "前汉门·又吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "铜马朱眉满四方，总缘居摄乱天常。",
            "因君多少布衣士，不是公卿即帝王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 前汉门·毛延寿 ----------
    {
        "id": "zhou-tan-135",
        "title": "前汉门·毛延寿",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "不拔金钗赂汉臣，徒嗟玉艳委胡尘。",
            "能知货贿移妍丑，岂独丹青画美人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 前汉门·刘圣公 ----------
    {
        "id": "zhou-tan-136",
        "title": "前汉门·刘圣公",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "不纳良谋刘縯言，胡为衔璧向崇宣。",
            "伤哉乱帝途穷处，何必当时谮福先。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 前汉门·樊崇徐宣 ----------
    {
        "id": "zhou-tan-137",
        "title": "前汉门·樊崇徐宣",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "庸中佼佼铁铮铮，百万长驱入帝京。",
            "首事纵隳三善在，归仁何虑不全生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 前汉门·僭号公孙述 ----------
    {
        "id": "zhou-tan-138",
        "title": "前汉门·僭号公孙述",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "剑蜀金汤孰敢争，子阳才业匪雄英。",
            "方知在德不在险，危栈何曾阻汉兵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 后汉门·光武 ----------
    {
        "id": "zhou-tan-139",
        "title": "后汉门·光武",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "成败非儒孰可量，儒生何指指萧王。",
            "萧王得众能宽裕，吴汉归来帝业昌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 140. 后汉门·明帝 ----------
    {
        "id": "zhou-tan-140",
        "title": "后汉门·明帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "朝臣咸佞孰知非，张佚公忠语独奇。",
            "博士一言除太傅，谥为明帝信其宜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 141. 后汉门·桓帝 ----------
    {
        "id": "zhou-tan-141",
        "title": "后汉门·桓帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "能嫌跋扈斩梁王，宁便荣枯信段张。",
            "襄楷忠言谁佞惑，忍教奸祸起萧墙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 142. 后汉门·灵帝 ----------
    {
        "id": "zhou-tan-142",
        "title": "后汉门·灵帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "榜悬金价鬻官荣，千万为公五百卿。",
            "公瑾孔明穷退者，安知高卧遇雄英。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 143. 后汉门·废帝 ----------
    {
        "id": "zhou-tan-143",
        "title": "后汉门·废帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "乱兵如猬走王师，社稷颠危孰为持。",
            "夜逐萤光寻道路，汉家天子步归时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 144. 后汉门·献帝 ----------
    {
        "id": "zhou-tan-144",
        "title": "后汉门·献帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "只为曹侯数贵人，普天黔首尽黄巾。",
            "汉灵早听侍中谏，安得献生称不辰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 145. 后汉门·再吟 ----------
    {
        "id": "zhou-tan-145",
        "title": "后汉门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "咸怨刑科有党偏，耕夫无不事戎旃。",
            "是时老幼饥号处，一斛黄禾五百千。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 146. 后汉门·子密 ----------
    {
        "id": "zhou-tan-146",
        "title": "后汉门·子密",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "子密封侯岂所宜，能高德义必无为。",
            "当时若缚还彭氏，率土何忧不自归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 147. 后汉门·羊续 ----------
    {
        "id": "zhou-tan-147",
        "title": "后汉门·羊续",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "鱼悬洁白振清风，禄散亲宾岁自穷。",
            "单席寒厅惭使者，葛衣何以至三公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 148. 后汉门·杨震 ----------
    {
        "id": "zhou-tan-148",
        "title": "后汉门·杨震",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "为国推贤匪惠私，十金为报遽相危。",
            "无言暗室何人见，咫尺斯须已四知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 149. 后汉门·赵孝 ----------
    {
        "id": "zhou-tan-149",
        "title": "后汉门·赵孝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "绿林清旦正朝饥，岂计行人瘦与肥。",
            "为感在原哀叫切，鶺鴒休报听双飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 150. 后汉门·马后 ----------
    {
        "id": "zhou-tan-150",
        "title": "后汉门·马后",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "粗衣闲寂阅群书，荐达嫔妃广帝居。",
            "再实伤根嫌贵宠，惠慈劳悴育皇储。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 151. 后汉门·魏博妻 ----------
    {
        "id": "zhou-tan-151",
        "title": "后汉门·魏博妻",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "萝挂青松是所依，松凋萝更改何枝。",
            "操刀必割腕可断，磐石徒坚心不移。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 152. 后汉门·曹娥 ----------
    {
        "id": "zhou-tan-152",
        "title": "后汉门·曹娥",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "心摧目断哭江濆，窥浪无踪日又昏。",
            "不入重泉寻水底，此生安得见沈魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 153. 后汉门·周都妻 ----------
    {
        "id": "zhou-tan-153",
        "title": "后汉门·周都妻",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "绿水双鸳一已沈，皇天更欲配何禽。",
            "不将血涕随霜刃，谁见朱殷未死心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 154. 后汉门·鲍宣妻 ----------
    {
        "id": "zhou-tan-154",
        "title": "后汉门·鲍宣妻",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "君恶奢华意不欢，一言从俭亦何难。",
            "但能和乐同琴瑟，未必恩情在绮纨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 155. 后汉门·吕母 ----------
    {
        "id": "zhou-tan-155",
        "title": "后汉门·吕母",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "狱无良吏雪无由，处处戈鋋自执仇。",
            "吕母衔冤穷老妇，亦能为帅复私雠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 156. 三国门·蜀先主 ----------
    {
        "id": "zhou-tan-156",
        "title": "三国门·蜀先主",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "豫州军败信途穷，徐庶推能荐卧龙。",
            "不是卑词三访谒，谁令玄德主巴邛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 157. 三国门·再吟 ----------
    {
        "id": "zhou-tan-157",
        "title": "三国门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "一家区宇忽三分，龌龊车书曷足论。",
            "定有伊姜为佐辅，忍教鸿雁各乾坤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 158. 三国门·后主 ----------
    {
        "id": "zhou-tan-158",
        "title": "三国门·后主",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "万峰如剑载前来，危阁横空信险哉。",
            "对此玄休长叹息，方知刘禅是庸才。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 159. 三国门·吴后主 ----------
    {
        "id": "zhou-tan-159",
        "title": "三国门·吴后主",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "吴宫季主恣骄奢，移尽江南百媚花。",
            "一旦狂风江上起，花随风散落谁家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 160. 三国门·王表 ----------
    {
        "id": "zhou-tan-160",
        "title": "三国门·王表",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "王表闻声莫见身，吴中敬事甚君亲。",
            "是知邦国将亡灭，不听人臣听鬼神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 161. 三国门·鲁肃 ----------
    {
        "id": "zhou-tan-161",
        "title": "三国门·鲁肃",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "轻财重义见英奇，圣主贤臣是所依。",
            "公瑾窘饥求子敬，一言才起数船归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 162. 晋门·晋武帝 ----------
    {
        "id": "zhou-tan-162",
        "title": "晋门·晋武帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "汉贪金帛鬻公卿，财赡羸军冀国宁。",
            "晋武鬻官私室富，是知犹不及桓灵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 163. 晋门·再吟 ----------
    {
        "id": "zhou-tan-163",
        "title": "晋门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "君人为理在安民，论道求贤德自新。",
            "经国远图无所问，何曾言指一何神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 164. 晋门·惠帝 ----------
    {
        "id": "zhou-tan-164",
        "title": "晋门·惠帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "蛙鸣堪笑问官私，更劝饥人食肉糜。",
            "蒙昧万机犹妇女，寇戎安得不纷披。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 165. 晋门·贾后 ----------
    {
        "id": "zhou-tan-165",
        "title": "晋门·贾后",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "贾后甘为废戮人，齐王还杀赵王伦。",
            "一从天下无真主，瓜割中原四百春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 166. 晋门·怀帝 ----------
    {
        "id": "zhou-tan-166",
        "title": "晋门·怀帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "蕃汉戈矛遍九垓，两京簪绂走黄埃。",
            "刘聪大会平阳日，遣帝行觞事可哀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 167. 晋门·愍帝 ----------
    {
        "id": "zhou-tan-167",
        "title": "晋门·愍帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "耕牛吃尽大田荒，二两黄金籴斗粮。",
            "御粥又闻无麴屑，不降胡虏奈饥肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 168. 晋门·郭钦 ----------
    {
        "id": "zhou-tan-168",
        "title": "晋门·郭钦",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "谁疑忠谏郭钦言，不逐戎夷出塞垣。",
            "晋室既无明圣主，果为胡虏乱中原。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 169. 晋门·王夷甫 ----------
    {
        "id": "zhou-tan-169",
        "title": "晋门·王夷甫",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "六合谁为辅弼臣，八风昏处尽胡尘。",
            "是知济弱扶倾术，不属高谈虚论人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 170. 晋门·王茂弘 ----------
    {
        "id": "zhou-tan-170",
        "title": "晋门·王茂弘",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "韩魏荆扬日岂堪，胡风看欲过江南。",
            "中原一片生灵血，谁秉王纲色不惭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 171. 晋门·吴隐之 ----------
    {
        "id": "zhou-tan-171",
        "title": "晋门·吴隐之",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "闻说贪泉近郁林，隐之今日得深斟。",
            "徒言滴水能穿石，其那坚贞匪石心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 172. 晋门·再吟 ----------
    {
        "id": "zhou-tan-172",
        "title": "晋门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "贪泉何处是泉源，只在灵台一点间。",
            "必也心源元自有，此泉何必在江山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 173. 六朝门·前赵刘聪 ----------
    {
        "id": "zhou-tan-173",
        "title": "六朝门·前赵刘聪",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "戎羯谁令识善言，刑将不舍遽能原。",
            "垂成却罢凤仪殿，仍改逍遥纳谏园。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 174. 六朝门·前凉张轨 ----------
    {
        "id": "zhou-tan-174",
        "title": "六朝门·前凉张轨",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "官从主簿至专征，谁遣凉王破赵名。",
            "益信用贤由拔擢，穰苴不是将家生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 175. 六朝门·后魏武帝 ----------
    {
        "id": "zhou-tan-175",
        "title": "六朝门·后魏武帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "太武南征似卷蓬，徐阳兖蔡杀皆空。",
            "从来吊伐宁如此，千里无烟血草红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 176. 六朝门·三废帝 ----------
    {
        "id": "zhou-tan-176",
        "title": "六朝门·三废帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "明庄节闵并罹殃，命在朱高二悖王。",
            "已叹一年三易换，更嗟殴辱下东廊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 177. 六朝门·苻坚 ----------
    {
        "id": "zhou-tan-177",
        "title": "六朝门·苻坚",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "百万南征几马归，叛亡如猬亦何悲。",
            "宾擒敌国诸戎主，更遣权兵过在谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 178. 六朝门·再呤 ----------
    {
        "id": "zhou-tan-178",
        "title": "六朝门·再呤",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "空知勇锐不知兵，困兽孤军未可轻。",
            "安有长驱百馀万，身驰几旅欲先征。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 179. 六朝门·又吟 ----------
    {
        "id": "zhou-tan-179",
        "title": "六朝门·又吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "水影星光怪异多，不思修德事干戈。",
            "无谋拒谏仍轻敌，国破身擒将奈何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 180. 六朝门·宋武帝 ----------
    {
        "id": "zhou-tan-180",
        "title": "六朝门·宋武帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "栖栖老楚未遭时，债主凭陵似迫危。",
            "人杰既为王谧识，刁逵诛斩独何悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 181. 六朝门·二废帝 ----------
    {
        "id": "zhou-tan-181",
        "title": "六朝门·二废帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "肆意荒狂杀不辜，方嗟废帝又苍梧。",
            "自言威震为英武，肯虑湘东与玉夫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 182. 六朝门·齐废帝东昏侯 ----------
    {
        "id": "zhou-tan-182",
        "title": "六朝门·齐废帝东昏侯",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "定策谁扶捕鼠儿，不忧萧衍畏潘妃。",
            "长围既合刀临项，犹惜金钱对落晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 183. 六朝门·梁武帝 ----------
    {
        "id": "zhou-tan-183",
        "title": "六朝门·梁武帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "梁武年高厌六龙，繁华声色尽归空。",
            "不求贤德追尧舜，翻作忧囚一病翁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 184. 六朝门·再吟 ----------
    {
        "id": "zhou-tan-184",
        "title": "六朝门·再吟",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "兴亡何故遽环回，汤纣身为事可哀。",
            "莫是自长嫌胜己，蔽贤犹执匹夫才。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 185. 六朝门·简文帝 ----------
    {
        "id": "zhou-tan-185",
        "title": "六朝门·简文帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "救兵方至强抽军，与贼开城是简文。",
            "曲项琵琶催酒处，不图为乐向谁云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 186. 六朝门·元帝 ----------
    {
        "id": "zhou-tan-186",
        "title": "六朝门·元帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "木栅江城困魏军，王褒横议遏谋臣。",
            "宾降未免俱为戮，一死安能谢益仁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 187. 六朝门·谢举 ----------
    {
        "id": "zhou-tan-187",
        "title": "六朝门·谢举",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "叛奴逃数岂堪留，忠节曾无肯到头。",
            "朱异早能同远见，青衫宁假帝登楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 188. 六朝门·朱异 ----------
    {
        "id": "zhou-tan-188",
        "title": "六朝门·朱异",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "徒览儒书不学兵，彦和虚得不廉名。",
            "四郊多垒犹相罪，国破将何谢太清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 189. 六朝门·傅昭 ----------
    {
        "id": "zhou-tan-189",
        "title": "六朝门·傅昭",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "为政残苛兽亦饥，除饥机在养疲羸。",
            "人能善政兽何暴，焉用劳人以槛为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 190. 六朝门·宣帝 ----------
    {
        "id": "zhou-tan-190",
        "title": "六朝门·宣帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "宣帝骄奢恣所为，后宫升降略无时。",
            "乘危自有妻公在，安许鸾凰是尉迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 191. 六朝门·李集 ----------
    {
        "id": "zhou-tan-191",
        "title": "六朝门·李集",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "忠谏能坚信正臣，三沈三屈竟何云。",
            "每沈良久方能语，及语还呼桀纣君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 192. 隋门·隋文帝 ----------
    {
        "id": "zhou-tan-192",
        "title": "隋门·隋文帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "孤儿寡妇忍同欺，辅政刚教篡夺为。",
            "矫诏必能疏昉译，直臣诚合重颜仪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 193. 隋门·独孤后 ----------
    {
        "id": "zhou-tan-193",
        "title": "隋门·独孤后",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "腹生奚强有亲疏，怜者为贤弃者愚。",
            "储贰不遭谗构死，隋亡宁便在江都。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 194. 隋门·炀帝 ----------
    {
        "id": "zhou-tan-194",
        "title": "隋门·炀帝",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "拒谏劳兵作祸基，穷奢极武向戎夷。",
            "兆人疲弊不堪命，天下嗷嗷新主资。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 195. 隋门·贺若弼 ----------
    {
        "id": "zhou-tan-195",
        "title": "隋门·贺若弼",
        "author": "周昙",
        "poet_id": "zhou-tan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "破敌将军意气豪，请除倾国斩妖娆。",
            "红绡忍染娇春雪，瞪目看行切玉刀。",
            "第七百三十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]