# -*- coding: utf-8 -*-
"""
皇甫松卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 19 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·杨柳枝 ----------
    {
        "id": "huang-fu-song-1",
        "title": "杂曲歌辞·杨柳枝",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "春入行宫映翠微，玄宗侍女舞烟丝。",
            "如今柳向空城绿，玉笛何人更把吹。",
            "烂熳春归水国时，吴王宫殿柳垂丝。",
            "黄莺长叫空闺畔，西子无因更得知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 杂曲歌辞·浪淘沙 ----------
    {
        "id": "huang-fu-song-2",
        "title": "杂曲歌辞·浪淘沙",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "滩头细草接疏林，浪恶罾船半欲沉。",
            "宿鹭眠洲非旧浦，去年沙觜是江心。",
            "蛮歌豆蔻北人愁，松雨蒲风夜艇秋。",
            "浪起䴔䴖眠不得，寒沙细细入江流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 古松感兴 ----------
    {
        "id": "huang-fu-song-3",
        "title": "古松感兴",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "皇天后土力，使我向此生。贵贱不我均，若为天地情。",
            "我家世道德，旨意匡文明。家集四百卷，独立天地经。",
            "寄言青松姿，岂羡朱槿荣。昭昭大化光，共此遗芳馨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 怨回纥歌 ----------
    {
        "id": "huang-fu-song-4",
        "title": "怨回纥歌",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "白首南朝女，愁听异域歌。收兵颉利国，饮马胡芦河。",
            "毳布腥膻久，穹庐岁月多。雕巢城上宿，吹笛泪滂沱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 江上送别 ----------
    {
        "id": "huang-fu-song-5",
        "title": "江上送别",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "祖席驻征棹，开帆候信潮。隔筵桃叶泣，吹管杏花飘。",
            "船去鸥飞阁，人归尘上桥。别离惆怅泪，江路湿红蕉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 采莲子二首 ----------
    {
        "id": "huang-fu-song-6",
        "title": "采莲子二首",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "菡萏香连十顷陂，小姑贪戏采莲迟。",
            "晚来弄水船头湿，更脱红裙裹鸭儿。",
            "船动湖光滟滟秋，贪看年少信船流。",
            "无端隔水抛莲子，遥被人知半日羞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 抛球乐 ----------
    {
        "id": "huang-fu-song-7",
        "title": "抛球乐",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "红拨一声飘，轻球坠越绡。带翻金孔雀，香满绣蜂腰。",
            "少少抛分数，花枝正索饶。",
            "金蹙花球小，真珠绣带垂。几回冲蜡烛，千度入春怀。",
            "上客终须醉，觥杯自乱排。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 劝僧酒 ----------
    {
        "id": "huang-fu-song-8",
        "title": "劝僧酒",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "劝僧一杯酒，共看青青山。酣然万象灭，不动心印闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 登郭隗台 ----------
    {
        "id": "huang-fu-song-9",
        "title": "登郭隗台",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "燕相谋在兹，积金黄巍巍。上者欲何颜，使我千载悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 杨柳枝词二首 ----------
    {
        "id": "huang-fu-song-10",
        "title": "杨柳枝词二首",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "烂漫春归水国时，吴王宫殿柳丝垂。",
            "黄莺长叫空闺畔，西子无因更得知。",
            "春入行宫映翠微，玄宗侍女舞烟丝。",
            "如今柳向空城绿，玉笛何人更把吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 浪淘沙二首 ----------
    {
        "id": "huang-fu-song-11",
        "title": "浪淘沙二首",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "滩头细草接疏林，浪恶罾船半欲沉。",
            "宿鹭眠洲非旧浦，去年沙觜是江心。",
            "蛮歌豆蔻北人愁，松雨蒲风野艇秋。",
            "浪起䴔䴖眠不得，寒沙细细入江流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 句 ----------
    {
        "id": "huang-fu-song-12",
        "title": "句",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "夜入真珠室，朝游玳瑁宫。（《纪事》载：松为牛僧孺表",
            "甥，不相荐举。因襄阳大水，极言诽谤。真珠乃牛爱姬也）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 竹枝（一名巴渝辞） ----------
    {
        "id": "huang-fu-song-13",
        "title": "竹枝（一名巴渝辞）",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "槟榔花发鹧鸪啼，雄飞烟瘴雌亦飞。",
            "木棉花尽荔支垂，千花万花待郎归。",
            "芙蓉并蒂一心连，花侵槅子眼应穿。",
            "筵中蜡烛泪珠红，合欢桃核两人同。",
            "斜江风起动横波，劈开莲子苦心多。",
            "山头桃花谷底杏，两花窈窕遥相映。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 摘得新 ----------
    {
        "id": "huang-fu-song-14",
        "title": "摘得新",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "酌一卮，须教玉笛吹。锦筵红蜡烛，莫来迟。",
            "繁红一夜经风雨，是空枝。",
            "摘得新，枝枝叶叶春。管弦兼美酒，最关人。",
            "平生都得几十度，展香茵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 采莲子 ----------
    {
        "id": "huang-fu-song-15",
        "title": "采莲子",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "菡萏香连十顷陂（举棹），小姑贪戏采莲迟（年少）。",
            "晚来弄水船头湿（举棹），更脱红裙裹鸭儿（年少）。",
            "船动湖光滟滟秋（举棹），贪看年少信船流（年少）。",
            "无端隔水抛莲子（举棹），遥被人知半日羞（年少）。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 抛球乐 ----------
    {
        "id": "huang-fu-song-16",
        "title": "抛球乐",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "红拨一声飘，轻裘坠越绡。带翻金孔雀，香满绣蜂腰。",
            "少少抛分数，花枝正索饶。",
            "金蹙花球小，真珠绣带垂。几回冲蜡烛，千度入香怀。",
            "上客终须醉，觥盂且乱排。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 忆江南 ----------
    {
        "id": "huang-fu-song-17",
        "title": "忆江南",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "兰烬落，屏上暗红蕉。闲梦江南梅熟日，",
            "夜船吹笛雨潇潇。人语驿边桥。",
            "楼上寝，残月下帘旌。梦见秣陵惆怅事，",
            "桃花柳絮满江城。双髻坐吹笙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 天仙子 ----------
    {
        "id": "huang-fu-song-18",
        "title": "天仙子",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "晴野鹭鸶飞一只，水葓花发秋江碧。刘郎此日别天仙，",
            "登绮席，泪珠滴，十二晚峰青历历。",
            "踯躅花开红照水，鹧鸪飞绕青山觜。行人经岁始归来，",
            "千万里，错相倚，懊恼天仙应有以。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 怨回纥 ----------
    {
        "id": "huang-fu-song-19",
        "title": "怨回纥",
        "author": "皇甫松",
        "poet_id": "huang-fu-song",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "白首南朝女，愁听异域歌。收兵颉利国，饮马胡卢河。",
            "毳布腥膻久，穹庐岁月多。雕窠城上宿，吹笛泪滂沱。",
            "祖席驻征棹，开帆候信潮。隔筵桃叶泣，吹管杏花飘。",
            "船去鸥飞阁，人归尘上桥。别离惆怅泪，江路湿红蕉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]