# -*- coding: utf-8 -*-
"""
李纾卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 唐德明兴圣庙乐章·迎神 ----------
    {
        "id": "li-shu-1",
        "title": "唐德明兴圣庙乐章·迎神",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "元尊九德，佐尧光宅。烈祖太宗，方周作伯。",
            "响怀霜露，乐变金石。白云清风，仿佛来格。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 唐德明兴圣庙乐章·登歌奠币 ----------
    {
        "id": "li-shu-2",
        "title": "唐德明兴圣庙乐章·登歌奠币",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "四时有典，百事来祭。尊祖奉宗，严禋大帝。",
            "礼先苍璧，奠备黝制。于万期年，熙成帝系。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 唐德明兴圣庙乐章·迎俎 ----------
    {
        "id": "li-shu-3",
        "title": "唐德明兴圣庙乐章·迎俎",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "盛牲实俎，涓选休成。鼎煁阳燧，玉盥阴精。",
            "有飶嘉豆，既和大羹。侑以清乐，细齐人情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 唐德明兴圣庙乐章·德明酌献 ----------
    {
        "id": "li-shu-4",
        "title": "唐德明兴圣庙乐章·德明酌献",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "清庙奕奕，和乐雍雍。器尊牺象，礼属宗公。",
            "白水方祼，黄流在中。谟明之德，万古清风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 唐德明兴圣庙乐章·兴圣酌献 ----------
    {
        "id": "li-shu-5",
        "title": "唐德明兴圣庙乐章·兴圣酌献",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "閟宫静谧，合乐周张。泰尊始献，百末重觞。",
            "震澹存诚，庶几迪尝。遥源之祚，天汉灵长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 唐德明兴圣庙乐章·亚献终献 ----------
    {
        "id": "li-shu-6",
        "title": "唐德明兴圣庙乐章·亚献终献",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "惟清惟肃，靡闻靡见。举备九成，俯终三献。",
            "庆彰曼寿，胙撤嘉荐。瘗玉埋牲，礼神斯遍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 唐德明兴圣庙乐章·送神 ----------
    {
        "id": "li-shu-7",
        "title": "唐德明兴圣庙乐章·送神",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "元精回复，灵贶繁滋。风洒兰路，云摇桂旗。",
            "高丘缅邈，凉部逶迟。瞻望靡及，缠绵永思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 让皇帝庙乐章·迎神 ----------
    {
        "id": "li-shu-8",
        "title": "让皇帝庙乐章·迎神",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "皇矣天宗，德先王季。因心则友，克让以位。",
            "爰命有司，式尊前志。神其降灵，昭飨祀事。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 让皇帝庙乐章·奠币 ----------
    {
        "id": "li-shu-9",
        "title": "让皇帝庙乐章·奠币",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "惟帝时若，去而上仙。祀用商武，乐备宫悬。",
            "白璧加荐，玄纁告虔。子孙拜后，承兹吉蠲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 让皇帝庙乐章·迎俎 ----------
    {
        "id": "li-shu-10",
        "title": "让皇帝庙乐章·迎俎",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "祀盛体荐，礼协粢盛。方周假庙，用鲁纯牲。",
            "捧撤祗敬，击拊和鸣。受釐归胙，既戒而平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 让皇帝庙乐章·酌献 ----------
    {
        "id": "li-shu-11",
        "title": "让皇帝庙乐章·酌献",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "八音具举，三寿既盥。洁兹宗彝，瑟彼圭瓒。",
            "兰肴重错，椒醑飘散。降祚维城，永为藩翰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 让皇帝庙乐章·亚献终献 ----------
    {
        "id": "li-shu-12",
        "title": "让皇帝庙乐章·亚献终献",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "秩礼有序，和音既同。九仪不忒，三揖将终。",
            "孝感藩后，相维辟公。四时之典，永永无穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 让皇帝庙乐章·送神 ----------
    {
        "id": "li-shu-13",
        "title": "让皇帝庙乐章·送神",
        "author": "李纾",
        "poet_id": "li-shu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "奠献已事，昏昕载分。风摇雨散，灵卫絪缊。",
            "龙驾帝服，已腾五云。泮宫复閟，寂寞无闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]