# -*- coding: utf-8 -*-
"""
徐安贞卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 书殿赐宴应制 ----------
    {
        "id": "xu-an-zhen-1",
        "title": "书殿赐宴应制",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "校文常近日，赐宴忽升天。酒正传杯至，饔人捧案前。",
            "玉阶鸣溜水，清阁引归烟。共惜芸香暮，春风几万年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 从驾温泉宫 ----------
    {
        "id": "xu-an-zhen-2",
        "title": "从驾温泉宫",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "神女调温液，年年待圣人。试开临水殿，来洗属车尘。",
            "暖气随明主，恩波浃近臣。灵威自无极，从此献千春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送吕向补阙西岳勒碑 ----------
    {
        "id": "xu-an-zhen-3",
        "title": "送吕向补阙西岳勒碑",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "圣作西山颂，君其出使年。勒碑悬日月，驱传接云烟。",
            "寒尽函关路，春归洛水边。别离能几许，朝暮玉墀前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送丹阳采访 ----------
    {
        "id": "xu-an-zhen-4",
        "title": "送丹阳采访",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "郡县分南国，皇华出圣朝。为怜乡棹近，不道使车遥。",
            "旧俗吴三让，遗风汉六条。愿言除疾苦，天子听歌谣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送王判官 ----------
    {
        "id": "xu-an-zhen-5",
        "title": "送王判官",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "明月开三峡，花源出五溪。城池青壁里，烟火绿林西。",
            "不畏王程促，惟愁仙路迷。巴东下归棹，莫待夜猿啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 题襄阳图 ----------
    {
        "id": "xu-an-zhen-6",
        "title": "题襄阳图",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "画得襄阳郡，依然见昔游。岘山思驻马，汉水忆回舟。",
            "丹壑常含霁，青林不换秋。图书空咫尺，千里意悠悠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 程将军夫人挽诗 ----------
    {
        "id": "xu-an-zhen-7",
        "title": "程将军夫人挽诗",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "琴瑟调双凤，和鸣不独飞。正歌春可乐，行泣露先晞。",
            "环珮声犹在，房栊梦不归。将军休沐日，谁劝著新衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 奉和喜雪应制 ----------
    {
        "id": "xu-an-zhen-8",
        "title": "奉和喜雪应制",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "两宫斋祭近登临，雨雪纷纷天昼阴。只为经寒无瑞色，",
            "顿教正月满春林。蓬莱北上旌门暗，花萼南归马迹深。",
            "自有三农歌帝力，还将万庾答尧心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 闻邻家理筝 ----------
    {
        "id": "xu-an-zhen-9",
        "title": "闻邻家理筝",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "北斗横天夜欲阑，愁人倚月思无端。忽闻画阁秦筝逸，",
            "知是邻家赵女弹。曲成虚忆青蛾敛，调急遥怜玉指寒。",
            "银锁重关听未辟，不如眠去梦中看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 奉和圣制早度蒲津关 ----------
    {
        "id": "xu-an-zhen-10",
        "title": "奉和圣制早度蒲津关",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "仙掌临秦甸，虹桥辟晋关。两都分地险，一曲度河湾。",
            "路得津门要，时称古戍闲。城花春正发，岸柳曙堪攀。",
            "后乘犹临水，前旌欲换山。长安回望日，宸御六龙还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 奉和圣制答二相出雀鼠谷 ----------
    {
        "id": "xu-an-zhen-11",
        "title": "奉和圣制答二相出雀鼠谷",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "两臣初入梦，二月扈巡边。涧北寒犹在，山南春半传。",
            "颂声先奉御，辰象复回天。云日明千里，旌旗照一川。",
            "柳阴低辇路，草色变新田。还望汾阳近，宸游自窅然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 句 ----------
    {
        "id": "xu-an-zhen-12",
        "title": "句",
        "author": "徐安贞",
        "poet_id": "xu-an-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "暮雨衣犹湿，春风帆正开。（《云溪友议》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]