# -*- coding: utf-8 -*-
"""
王贞白卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 67 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·妾薄命 ----------
    {
        "id": "wang-zhen-bai-1",
        "title": "杂曲歌辞·妾薄命",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "薄命头欲白，频年嫁不成。秦娥未十五，昨夜事公卿。",
            "岂有机杼力，空传歌舞名。妾专修妇德，媒氏却相轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 拟塞外征行 ----------
    {
        "id": "wang-zhen-bai-2",
        "title": "拟塞外征行",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "寇骑满鸡田，都护欲临边。青泥方绝漠，怀剑始辞燕。",
            "旌旗挂龙虎，壮士募鹰鹯。长城威十万，高岭奋三千。",
            "行行向马邑，去去指祁连。鼓声遥赤塞，兵气远冲天。",
            "对阵云初上，临城月始悬。风惊烽易灭，沙暗马难前。",
            "恩重恒思报，劳心屡损年。微功一可立，身轻不自怜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 芦苇 ----------
    {
        "id": "wang-zhen-bai-3",
        "title": "芦苇",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "高士想江湖，湖闲庭植芦。清风时有至，绿竹兴何殊。",
            "嫩喜日光薄，疏忧雨点粗。惊蛙跳得过，斗雀袅如无。",
            "未织巴篱护，几抬邛竹扶。惹烟轻弱柳，蘸水漱清蒲。",
            "溉灌情偏重，琴樽赏不孤。穿花思钓叟，吹叶少羌雏。",
            "寒色暮天映，秋声远籁俱。朗吟应有趣，潇洒十馀株。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 田舍曲 ----------
    {
        "id": "wang-zhen-bai-4",
        "title": "田舍曲",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "古今利名路，只在侬门前。至老不离家，一生常晏眠。",
            "牛羊晚自归，儿童戏野田。岂思封侯贵，唯只待丰年。",
            "征赋岂辞苦，但愿时官贤。时官苟贪浊，田舍生忧煎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 妾薄命 ----------
    {
        "id": "wang-zhen-bai-5",
        "title": "妾薄命",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "薄命头欲白，频年嫁不成。秦娥未十五，昨夜事公卿。",
            "岂有机杼力，空传歌舞名。妾专修妇德，媒氏却相轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 湘妃怨 ----------
    {
        "id": "wang-zhen-bai-6",
        "title": "湘妃怨",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "舜欲省蛮陬，南巡非逸游。九江沉白日，二女泣沧洲。",
            "目极楚云断，恨深湘水流。至今闻鼓瑟，咽绝不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 长门怨二首 ----------
    {
        "id": "wang-zhen-bai-7",
        "title": "长门怨二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "寂寞故宫春，残灯晓尚存。从来非妾过，偶尔失君恩。",
            "花落伤容鬓，莺啼惊梦魂。翠华如可待，应免老长门。",
            "叶落长门静，苔生永巷幽。相思对明月，独坐向空楼。",
            "銮驾迷终转，蛾眉老自愁。昭阳歌舞伴，此夕未知秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 有所思（一作长相思） ----------
    {
        "id": "wang-zhen-bai-8",
        "title": "有所思（一作长相思）",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "芙蓉出水时，偶尔便分离。自此无因见，长教挂所思。",
            "残春不入梦，芳信欲传谁。寂寞秋堂下，空吟小谢诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 短歌 ----------
    {
        "id": "wang-zhen-bai-9",
        "title": "短歌",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "物候来相续，新蝉送晚莺。百年休倚赖，一梦甚分明。",
            "金鼎神仙隐，铜壶昼夜倾。不如早立德，万古有其名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 御沟水 ----------
    {
        "id": "wang-zhen-bai-10",
        "title": "御沟水",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "一带御沟水，绿槐相荫清。此中涵帝泽，无处濯尘缨。",
            "鸟道来虽险，龙池到自平。朝宗本心切，愿向急流倾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 少年行二首 ----------
    {
        "id": "wang-zhen-bai-11",
        "title": "少年行二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "游宴不知厌，杜陵狂少年。花时轻暖酒，春服薄装绵。",
            "戏马上林苑，斗鸡寒食天。鲁儒甘被笑，对策鬓皤然。",
            "弱冠投边急，驱兵夜渡河。追奔铁马走，杀虏宝刀讹。",
            "威静黑山路，气含清海波。常闻为突骑，天子赐长戈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 塞上曲 ----------
    {
        "id": "wang-zhen-bai-12",
        "title": "塞上曲",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "岁岁但防虏，西征早晚休。匈奴不系颈，汉将但封侯。",
            "夕照低烽火，寒笳咽戍楼。燕然山上字，男子见须羞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 长安道 ----------
    {
        "id": "wang-zhen-bai-13",
        "title": "长安道",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "晓鼓人已行，暮鼓人未息。梯航万国来，争先贡金帛。",
            "不问贤与愚，但论官与职。如何贫书生，只献安边策。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 洛阳道 ----------
    {
        "id": "wang-zhen-bai-14",
        "title": "洛阳道",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "喧喧洛阳路，奔走争先步。唯恐著鞭迟，谁能更回顾。",
            "覆车虽在前，润屋何曾惧。贤哉只二疏，东门挂冠去。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 度关山 ----------
    {
        "id": "wang-zhen-bai-15",
        "title": "度关山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "只领千馀骑，长驱碛邑间。云州多警急，雪夜度关山。",
            "石响铃声远，天寒弓力悭。秦楼休怅望，不日凯歌还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 出自蓟北门行 ----------
    {
        "id": "wang-zhen-bai-16",
        "title": "出自蓟北门行",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "蓟北连极塞，塞色昼冥冥。战地骸骨满，长时风雨腥。",
            "沙河留不定，春草冻难青。万户封侯者，何谋静虏庭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 从军行 ----------
    {
        "id": "wang-zhen-bai-17",
        "title": "从军行",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "从军朔方久，未省用干戈。只以恩信及，自然戎虏和。",
            "边声动白草，烧色入枯河。每度因看猎，令人勇气多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 古悔从军行 ----------
    {
        "id": "wang-zhen-bai-18",
        "title": "古悔从军行",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "忆昔仗孤剑，十年从武威。论兵亲玉帐，逐虏过金微。",
            "陇水秋先冻，关云寒不飞。辛勤功业在，麟阁志犹违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 胡笳曲 ----------
    {
        "id": "wang-zhen-bai-19",
        "title": "胡笳曲",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "陇底悲笳引，陇头鸣北风。一轮霜月落，万里塞天空。",
            "戍卒泪应尽，胡儿哭未终。争教班定远，不念玉关中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 入塞 ----------
    {
        "id": "wang-zhen-bai-20",
        "title": "入塞",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "玉殿论兵事，君王诏出征。新除羽林将，曾破月支兵。",
            "惯历塞垣险，能分部落情。从今一战胜，不使虏尘生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 游仙 ----------
    {
        "id": "wang-zhen-bai-21",
        "title": "游仙",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "我家三岛上，洞户眺波涛。醉背云屏卧，谁知海日高。",
            "露香红玉树，风绽碧蟠桃。悔与仙子别，思归梦钓鳌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 歌（一作凉州行） ----------
    {
        "id": "wang-zhen-bai-22",
        "title": "歌（一作凉州行）",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "谁唱关西曲，寂寞夜景深。一声长在耳，万恨重经心。",
            "调古清风起，曲终凉月沉。却应筵上客，未必是知音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 经故洛城 ----------
    {
        "id": "wang-zhen-bai-23",
        "title": "经故洛城",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "卜世何久远，由来仰圣明。山河徒自壮，周召不长生。",
            "几主任奸谄，诸侯各战争。但馀崩垒在，今古共伤情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 金陵 ----------
    {
        "id": "wang-zhen-bai-24",
        "title": "金陵",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "六代江山在，繁华古帝都。乱来城不守，战后地多芜。",
            "寒日随潮落，归帆与鸟孤。兴亡多少事，回首一长吁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 金陵怀古 ----------
    {
        "id": "wang-zhen-bai-25",
        "title": "金陵怀古",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "恃险不种德，兴亡叹数穷。石城几换主，天堑谩连空。",
            "御路叠民冢，台基聚牧童。折碑犹有字，多记晋英雄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 商山 ----------
    {
        "id": "wang-zhen-bai-26",
        "title": "商山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "商山名利路，夜亦有人行。四皓卧云处，千秋叠藓生。",
            "昼烧笼涧黑，残雪隔林明。我待酬恩了，来听水石声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 庐山 ----------
    {
        "id": "wang-zhen-bai-27",
        "title": "庐山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "岳立镇南楚，雄名天下闻。五峰高阂日，九叠翠连云。",
            "夏谷雪犹在，阴岩昼不分。唯应嵩与华，清峻得为群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 终南山 ----------
    {
        "id": "wang-zhen-bai-28",
        "title": "终南山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "终朝异五岳，列翠满长安。地去搜扬近，人谋隐遁难。",
            "水穿诸苑过，雪照一城寒。为问红尘里，谁同驻马看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 寄郑谷 ----------
    {
        "id": "wang-zhen-bai-29",
        "title": "寄郑谷",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "五百首新诗，缄封寄去时。只凭夫子鉴，不要俗人知。",
            "火鼠重收布，冰蚕乍吐丝。直须天上手，裁作领巾披。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 题严陵钓台 ----------
    {
        "id": "wang-zhen-bai-30",
        "title": "题严陵钓台",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "山色四时碧，溪声七里清。严陵爱此景，下视汉公卿。",
            "垂钓月初上，放歌风正轻。应怜渭滨叟，匡国正论兵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 晓泊汉阳渡 ----------
    {
        "id": "wang-zhen-bai-31",
        "title": "晓泊汉阳渡",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "落月临古渡，武昌城未开。残灯明市井，晓色辨楼台。",
            "云自苍梧去，水从嶓冢来。芳洲号鹦鹉，用记祢生才。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 随计 ----------
    {
        "id": "wang-zhen-bai-32",
        "title": "随计",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "徒步随计吏，辛勤鬓易凋。归期无定日，乡思羡回潮。",
            "冒雨投前驿，侵星过断桥。何堪穆陵路，霜叶更潇潇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 白牡丹 ----------
    {
        "id": "wang-zhen-bai-33",
        "title": "白牡丹",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "谷雨洗纤素，裁为白牡丹。异香开玉合，轻粉泥银盘。",
            "晓贮露华湿，宵倾月魄寒。家人淡妆罢，无语倚朱栏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 述松 ----------
    {
        "id": "wang-zhen-bai-34",
        "title": "述松",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "远谷呈材干，何由入栋梁。岁寒虚胜竹，功绩不如桑。",
            "秋露落松子，春深裛嫩黄。虽蒙匠者顾，樵采日难防。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 宫池产瑞莲（帖经日试） ----------
    {
        "id": "wang-zhen-bai-35",
        "title": "宫池产瑞莲（帖经日试）",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "雨露及万物，嘉祥有瑞莲。香飘鸡树近，荣占凤池先。",
            "圣日临双丽，恩波照并妍。愿同指佞草，生向帝尧前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 送友人南归 ----------
    {
        "id": "wang-zhen-bai-36",
        "title": "送友人南归",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "南国菖蒲老，知君忆钓船。离京近残暑，归路有新蝉。",
            "岘首白云起，洞庭秋月悬。若教吟兴足，西笑是何年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 送马明府归山 ----------
    {
        "id": "wang-zhen-bai-37",
        "title": "送马明府归山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "辞秩入匡庐，重修靖节居。免遭黑绶束，不与白云疏。",
            "送吏各献酒，群儿自担书。到时看瀑布，为我谢清虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 送韩从事归本道 ----------
    {
        "id": "wang-zhen-bai-38",
        "title": "送韩从事归本道",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "献捷灵州倅，归时宠拜新。论边多称旨，许国誓亡身。",
            "马渴黄河冻，雁回青冢春。到蕃唯促战，应不肯和亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 秋日旅怀寄右省郑拾遗 ----------
    {
        "id": "wang-zhen-bai-39",
        "title": "秋日旅怀寄右省郑拾遗",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "永夕愁不寐，草虫喧客庭。半窗分晓月，当枕落残星。",
            "鬓发游梁白，家山近越青。知音在谏省，苦调有谁听。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 赠刘凝评事 ----------
    {
        "id": "wang-zhen-bai-40",
        "title": "赠刘凝评事",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "棘寺官初罢，梁园静掩扉。春深颜子巷，花映老莱衣。",
            "谈史曾无滞，攻书已造微。即膺新宠命，称庆向庭闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 忆张处士 ----------
    {
        "id": "wang-zhen-bai-41",
        "title": "忆张处士",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "天台张处士，诗句造玄微。古乐知音少，名言与俗违。",
            "山风入松径，海月上岩扉。毕世唯高卧，无人说是非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 云居长老 ----------
    {
        "id": "wang-zhen-bai-42",
        "title": "云居长老",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "巘路蹑云上，来参出世僧。松高半岩雪，竹覆一溪冰。",
            "不说有为法，非传无尽灯。了然方寸内，应只见南能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 洗竹 ----------
    {
        "id": "wang-zhen-bai-43",
        "title": "洗竹",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "道院竹繁教略洗，鸣琴酌酒看扶疏。不图结实来双凤，",
            "且要长竿钓巨鱼。锦箨裁冠添散逸，玉芽修馔称清虚。",
            "有时记得三天事，自向琅玕节下书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 庾楼晓望 ----------
    {
        "id": "wang-zhen-bai-44",
        "title": "庾楼晓望",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "独凭朱槛亦凌晨，山色初明水色新。竹雾晓笼衔岭月，",
            "蘋风暖送过江春。子城阴处犹残雪，衙鼓声前未有尘。",
            "三百年来庾楼上，曾经多少望乡人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 送芮尊师 ----------
    {
        "id": "wang-zhen-bai-45",
        "title": "送芮尊师",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "石上菖蒲节节灵，先生服食得长生。早知避世忧身老，",
            "近日登山觉步轻。黄鹤待传蓬岛信，丹书应换蕊宫名。",
            "他年控鲤升天去，庐岳逋民愿从行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 折杨柳三首（一作段成式诗） ----------
    {
        "id": "wang-zhen-bai-46",
        "title": "折杨柳三首（一作段成式诗）",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "枝枝交影锁长门，嫩色曾沾雨露恩。",
            "凤辇不来春欲尽，空留莺语到黄昏。",
            "水殿年年占早芳，柔条风里御炉香。",
            "如今万乘多巡狩，辇路无阴绿草长。",
            "嫩叶初齐不耐寒，风和时拂玉栏干。",
            "征人去日曾攀折，泣雨伤春翠黛残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 远闻本郡行春到旧山二首 ----------
    {
        "id": "wang-zhen-bai-47",
        "title": "远闻本郡行春到旧山二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "一身从宦留京邑，五马遥闻到旧山。",
            "已领烟霞光野径，深惭老幼候柴关。",
            "清风借响松筠外，画隼停晖水石间。",
            "定掩溪名在图传，共知轩盖此登攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 宿新安村步 ----------
    {
        "id": "wang-zhen-bai-48",
        "title": "宿新安村步",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "淅淅寒流涨浅沙，月明空渚遍芦花。",
            "离人偶宿孤村下，永夜闻砧一两家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 仙岩二首 ----------
    {
        "id": "wang-zhen-bai-49",
        "title": "仙岩二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "白烟昼起丹灶，红叶秋书篆文。",
            "二十四岩天上，一鸡啼破晴云。",
            "风呼山鬼服役，月照衡薇结花。",
            "江暖客寻瑶草，洞深人咽丹霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 雨后从陶郎中登庾楼 ----------
    {
        "id": "wang-zhen-bai-50",
        "title": "雨后从陶郎中登庾楼",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "庾楼逢霁色，夏日欲西曛。虹截半江雨，风驱大泽云。",
            "岛边渔艇聚，天畔鸟行分。此景堪谁画，文翁请缀文。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 九日长安作 ----------
    {
        "id": "wang-zhen-bai-51",
        "title": "九日长安作",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "无酒泛金菊，登高但忆秋。归心随旅雁，万里在沧洲。",
            "残照明天阙，孤砧隔御沟。谁能思落帽，两鬓已添愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 晓发萧关 ----------
    {
        "id": "wang-zhen-bai-52",
        "title": "晓发萧关",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "早发长风里，边城曙色间。数鸿寒背碛，片月落临关。",
            "陇上明星没，沙中夜探还。归程不可问，几日到家山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 钓台 ----------
    {
        "id": "wang-zhen-bai-53",
        "title": "钓台",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "异代有巢许，方知严子情。旧交虽建国，高卧不求荣。",
            "溪鸟寒来浴，汀兰暖重生。何颜吟过此，辛苦得浮名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 寄天台叶尊师 ----------
    {
        "id": "wang-zhen-bai-54",
        "title": "寄天台叶尊师",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "师住天台久，长闻过石桥。晴峰见沧海，深洞彻丹霄。",
            "采药霞衣湿，煎芝古鼎焦。念予无俗骨，频与鹤书招。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 御试后进诗 ----------
    {
        "id": "wang-zhen-bai-55",
        "title": "御试后进诗",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "三时赐食天厨近，再宿偷吟禁漏清。",
            "二十五家齐拔宅，人间已写上升名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 春日咏梅花 ----------
    {
        "id": "wang-zhen-bai-56",
        "title": "春日咏梅花",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "靓妆才罢粉痕新，迨晓风回散玉尘。",
            "若遣有情应怅望，已兼残雪又兼春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 句 ----------
    {
        "id": "wang-zhen-bai-57",
        "title": "句",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "太阳虽不照，梁栋每重阴。（廊下井，以下《吟窗杂录》）",
            "白发未逢媒，对景且裴回。（丑妇）",
            "别酒莫辞今夜醉，故人知我几时来。（合赋）",
            "改贯永留乡党额，减租重感郡侯恩。（洪景卢《野处集》",
            "载赴选别太守句，贞白自注：蒙本州改坊名为进贤，",
            "并减户税）",
            "第七百零二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 江上吟晓 ----------
    {
        "id": "wang-zhen-bai-58",
        "title": "江上吟晓",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "一叶野人舟，长将载酒游。夜来吟思苦，江上月华秋。",
            "晓露满红蓼，轻波飏白鸥。渔翁似有约，相伴钓中流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 过商山 ----------
    {
        "id": "wang-zhen-bai-59",
        "title": "过商山",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "一宿白云根，时经采麝村。数峰虽似蜀，当昼不闻猿。",
            "马立溪沙浅，人争阁道喧。明朝弃襦罢，步步入金门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 泛镜湖□□ ----------
    {
        "id": "wang-zhen-bai-60",
        "title": "泛镜湖□□",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "我泛镜湖日，未生千里莼。时无贺宾客，谁识谪仙人。",
            "吟对四时雪，忆游三岛春。恶闻亡越事，洗耳大江滨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 太湖石 ----------
    {
        "id": "wang-zhen-bai-61",
        "title": "太湖石",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "谁怜孤峭质，移在太湖心。出得风波外，任他池馆深。",
            "不同花逞艳，多愧竹垂阴。一片至坚操，那忧岁月侵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 依韵和幹公题庭中太湖石二首 ----------
    {
        "id": "wang-zhen-bai-62",
        "title": "依韵和幹公题庭中太湖石二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "山立只盈寻，高奇药圃阴。风涛打欲碎，岩穴蛰方深。",
            "藓点晴偏绿，蛩藏晓竞吟。岁寒终不变，堪比古人心。",
            "徒劳水府寻，宛在玉堂阴。兰圃安虽窄，盆池映转深。",
            "山僧来尽爱，诗客见先吟。若是买花者，年年不计心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 书陶潜醉石 ----------
    {
        "id": "wang-zhen-bai-63",
        "title": "书陶潜醉石",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "片石陶真性，非为麹糵昏。争如累月醉，不笑独醒人。",
            "积叠莓苔色，交加薜荔根。至今重九日，犹待白衣魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 看天王院牡丹 ----------
    {
        "id": "wang-zhen-bai-64",
        "title": "看天王院牡丹",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "前年帝里探春时，寺寺名花我尽知。",
            "今日长安已灰烬，忍随南国对芳枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 芍药 ----------
    {
        "id": "wang-zhen-bai-65",
        "title": "芍药",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "芍药承春宠，何曾羡牡丹。麦秋能几日，谷雨只微寒。",
            "妒态风频起，娇妆露欲残。芙蓉浣纱伴，长恨隔波澜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 独芙蓉 ----------
    {
        "id": "wang-zhen-bai-66",
        "title": "独芙蓉",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "方塘清晓镜，独照玉容秋。蠹芰不相采，敛蘋空自愁。",
            "日斜还顾影，风起强垂头。芳意羡何物，双双鸂鶒游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 冯氏书斋小松二首 ----------
    {
        "id": "wang-zhen-bai-67",
        "title": "冯氏书斋小松二首",
        "author": "王贞白",
        "poet_id": "wang-zhen-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "孤根生远岳，移植翠枝添。自秉雪霜操，任他蜂蝶嫌。",
            "微阴连迥竹，清韵入疏帘。耸势即空碧，时人看莫厌。",
            "得地已经岁，清音昼夜闻。根涵旧山土，叶间近溪云。",
            "野鹤望长远，庭花笑不群。须知摇落后，众木始能分。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]