# -*- coding: utf-8 -*-
"""
卢延让卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 14 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 苦吟 ----------
    {
        "id": "lu-yan-rang-1",
        "title": "苦吟",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "莫话诗中事，诗中难更无。吟安一个字，撚断数茎须。",
            "险觅天应闷，狂搜海亦枯。不同文赋易，为著者之乎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 雪 ----------
    {
        "id": "lu-yan-rang-2",
        "title": "雪",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "瑞雪落纷华，随风一向斜。地平铺作月，天迥撒成花。",
            "客满烧烟舍，牛牵卖炭车。吾皇忧挟纩，犹自问君家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 松寺 ----------
    {
        "id": "lu-yan-rang-3",
        "title": "松寺",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "山寺取凉当夏夜，共僧蹲坐石阶前。两三条电欲为雨，",
            "七八个星犹在天。衣汗稍停床上扇，茶香时拨涧中泉。",
            "通宵听论莲华义，不藉松窗一觉眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠僧 ----------
    {
        "id": "lu-yan-rang-4",
        "title": "赠僧",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "浮世浮华一断空，偶抛烦恼到莲宫。高僧解语牙无水，",
            "老鹤能飞骨有风。野色吟馀生竹外，山阴坐久入池中。",
            "禅师莫问求名苦，滋味过于食蓼虫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 逢友人赴阙 ----------
    {
        "id": "lu-yan-rang-5",
        "title": "逢友人赴阙",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "正当天下待雍熙，丹诏征来早为迟。倚马才高犹爱艺，",
            "问牛心在肯容私。吏开黄阁排班处，民拥青门看入时。",
            "却笑郡人留不得，感恩唯拟立生祠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 哭李郢端公 ----------
    {
        "id": "lu-yan-rang-6",
        "title": "哭李郢端公",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "军门半掩槐花宅，每过犹闻哭临声。北固暴亡兼在路，",
            "东都权葬未归茔。渐穷老仆慵看马，著惨佳人暗理筝。",
            "诗侣酒徒消散尽，一场春梦越王城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 谢杨尚书惠樱桃 ----------
    {
        "id": "lu-yan-rang-7",
        "title": "谢杨尚书惠樱桃",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "满合虚红怕动摇，尚书知重赐樱桃。揉蓝尚带新鲜叶，",
            "泼血犹残旧折条。万颗真珠轻触破，一团甘露软含消。",
            "春来老病尤珍荷，并食中肠似火烧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 寒食日戏赠李侍御 ----------
    {
        "id": "lu-yan-rang-8",
        "title": "寒食日戏赠李侍御",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "十二街如市，红尘咽不开。洒蹄骢马汗，没处看花来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 樊川寒食二首 ----------
    {
        "id": "lu-yan-rang-9",
        "title": "樊川寒食二首",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "寒食权豪尽出行，一川如画雨初晴。",
            "谁家络络游春盛，担入花间轧轧声。",
            "鞍马和花总是尘，歌声处处有佳人。",
            "五陵年少粗于事，栲栳量金买断春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 句 ----------
    {
        "id": "lu-yan-rang-10",
        "title": "句",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "只讹些子缘，应耗没多光。（《八月十六夜》）",
            "臂鹰健卒悬毡帽，骑马佳人卷画衫。（送周太保赴浙西）",
            "每过私第邀看鹤，长著公裳送上驴。（《寄友》）",
            "名纸毛生五门下，家僮骨立六街中。（《旅舍言怀》）云间闹铎骡驼至，雪里残骸虎拽来。（《蜀路》）",
            "树上咨诹批颊鸟，窗间壁驳叩头虫。（《冬夜》）",
            "莫欺零落残牙齿，曾吃红绫饼餤来。",
            "渡水蹇驴双耳直，避风羸仆一肩高。（《雪》）",
            "高据襄阳播盛名，问人人道是诗星。（《吊孟浩然》，",
            "以上并见《海录碎事》）",
            "凉雨打低残菡萏，急风吹散小蜻蜓。（见《锦绣万花谷》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 哭亡将诗 ----------
    {
        "id": "lu-yan-rang-11",
        "title": "哭亡将诗",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "自是硇砂发，非干骇石伤。牒高身上职，碗大背边创。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 八月十六夜月 ----------
    {
        "id": "lu-yan-rang-12",
        "title": "八月十六夜月",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "十六胜三五，中天照大荒。只讹些子缘，应号没多光。",
            "桂老犹全在，蟾深未煞忙。难期一年事，到晓泥诗章。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 冬除夜书情 ----------
    {
        "id": "lu-yan-rang-13",
        "title": "冬除夜书情",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "兀兀坐无味，思量谁与邻。数星深夜火，一个远乡人。",
            "雁翥天微雪，风号树欲春。愁章自难过，不觉苦吟频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 观新岁朝贺 ----------
    {
        "id": "lu-yan-rang-14",
        "title": "观新岁朝贺",
        "author": "卢延让",
        "poet_id": "lu-yan-rang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "龙墀初立仗，鸳鹭列班行。元日燕脂色，朝天桦烛香。",
            "表章堆玉案，缯帛满牙床。三百年如此，无因及我唐。",
            "第八百八十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]