# -*- coding: utf-8 -*-
"""
张继卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 49 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·长相思 ----------
    {
        "id": "zhang-ji-1",
        "title": "杂曲歌辞·长相思",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "辽阳望河县，白首无由见。海上珊瑚枝，年年寄春燕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 郢城西楼吟（一作郎士元诗） ----------
    {
        "id": "zhang-ji-2",
        "title": "郢城西楼吟（一作郎士元诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "连山尽塞水萦回，山上戍门临水开。珠帘直下一百丈，",
            "日暖游鳞自相向。昔人爱险闭层城，今人复爱闲江清。",
            "沙洲枫岸无来客，草绿花开山鸟鸣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 登丹阳楼（一作郎士元诗） ----------
    {
        "id": "zhang-ji-3",
        "title": "登丹阳楼（一作郎士元诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "寒皋那可望，旅客又初还。迢递高楼上，萧疏凉野间。",
            "暮晴依远水，秋兴属连山。浮客时相见，霜凋朱翠颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春夜皇甫冉宅欢宴（一作对酒） ----------
    {
        "id": "zhang-ji-4",
        "title": "春夜皇甫冉宅欢宴（一作对酒）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "流落时相见，悲欢共此情。兴因尊酒洽，愁为故人轻。",
            "暗滴花茎露，斜晖月过城。那知横吹笛，江外作边声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 会稽秋晚奉呈于太守 ----------
    {
        "id": "zhang-ji-5",
        "title": "会稽秋晚奉呈于太守",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "寂寂讼庭幽，森森戟户秋。山光隐危堞，湖色上高楼。",
            "禹穴探书罢，天台作赋游。云浮将越客，岁晚共淹留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 题严陵钓台 ----------
    {
        "id": "zhang-ji-6",
        "title": "题严陵钓台",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "旧隐人如在，清风亦似秋。客星沈夜壑，钓石俯春流。",
            "鸟向乔枝聚，鱼依浅濑游。古来芳饵下，谁是不吞钩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 清明日自西午桥至瓜岩村有怀 ----------
    {
        "id": "zhang-ji-7",
        "title": "清明日自西午桥至瓜岩村有怀",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "晚霁龙门雨，春生汝穴风。鸟啼官路静，花发毁垣空。",
            "鸣玉惭时辈，垂丝学老翁。旧游人不见，惆怅洛城东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 洛阳作（一作初出徽安门） ----------
    {
        "id": "zhang-ji-8",
        "title": "洛阳作（一作初出徽安门）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "洛阳天子县，金谷石崇乡。草色侵官道，花枝出苑墙。",
            "书成休逐客，赋罢遂为郎。贫贱非吾事，西游思自强。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 晚次淮阳 ----------
    {
        "id": "zhang-ji-9",
        "title": "晚次淮阳",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "微凉风叶下，楚俗转清闲。候馆临秋水，郊扉掩暮山。",
            "月明潮渐近，露湿雁初还。浮客了无定，萍流淮海间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送窦十九判官使江南 ----------
    {
        "id": "zhang-ji-10",
        "title": "送窦十九判官使江南",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "游客淹星纪，裁诗炼土风。今看乘传去，那与问津同。",
            "南郡迎徐子，临川谒谢公。思归一惆怅，於越古亭中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 江上送客游庐山 ----------
    {
        "id": "zhang-ji-11",
        "title": "江上送客游庐山",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "楚客自相送，沾裳春水边。晚来风信好，并发上江船。",
            "花映新林岸，云开瀑布泉。惬心应在此，佳句向谁传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 酬张二十员外前国子博士窦叔向 ----------
    {
        "id": "zhang-ji-12",
        "title": "酬张二十员外前国子博士窦叔向",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "故交日零落，心赏寄何人。幸与冯唐遇，心同迹复亲。",
            "语言未终夕，离别又伤春。结念湓城下，闻猿诗兴新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 会稽郡楼雪霁（一作望雪） ----------
    {
        "id": "zhang-ji-13",
        "title": "会稽郡楼雪霁（一作望雪）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "江城昨夜雪如花，郢客登楼齐望华。夏禹坛前仍聚玉，",
            "西施浦上更飞沙。帘栊向晚寒风度，睥睨初晴落景斜。",
            "数处微明销不尽，湖山清映越人家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 冯翊西楼（一作郎士元诗） ----------
    {
        "id": "zhang-ji-14",
        "title": "冯翊西楼（一作郎士元诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "城上西楼倚暮天，楼中归望正凄然。近郭乱山横古渡，",
            "野庄乔木带新烟。北风吹雁声能苦，远客辞家月再圆。",
            "陶令好文常对酒，相招那惜醉为眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送邹判官往陈留（一作洪州送郄绍充河南租庸判官） ----------
    {
        "id": "zhang-ji-15",
        "title": "送邹判官往陈留（一作洪州送郄绍充河南租庸判官）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "齐宋伤心地，频年此用兵。女停襄邑杼，农废汶阳耕。",
            "国使乘轺去，诸侯拥节迎。深仁荷君子，薄赋恤黎甿。",
            "火燎原犹热，波摇海未平。应将否泰理，一问鲁诸生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 酬李书记校书越城秋夜见赠 ----------
    {
        "id": "zhang-ji-16",
        "title": "酬李书记校书越城秋夜见赠",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "东越秋城夜，西人白发年。寒城警刁斗，孤愤抱龙泉。",
            "凤辇栖岐下，鲸波斗洛川。量空海陵粟，赐乏水衡钱。",
            "投阁嗤扬子，飞书代鲁连。苍苍不可问，余亦赋思玄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 感怀（一作陆沈诗，题作上礼部杨侍郎） ----------
    {
        "id": "zhang-ji-17",
        "title": "感怀（一作陆沈诗，题作上礼部杨侍郎）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "调与时人背，心将静者论。终年帝城里，不识五侯门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 长相思 ----------
    {
        "id": "zhang-ji-18",
        "title": "长相思",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "辽阳望河县，白首无由见。海上珊瑚枝，年年寄春燕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 奉寄皇甫补阙 ----------
    {
        "id": "zhang-ji-19",
        "title": "奉寄皇甫补阙",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "京口情人别久，扬州估客来疏。",
            "潮至浔阳回去，相思无处通书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 枫桥夜泊（一作夜泊枫江） ----------
    {
        "id": "zhang-ji-20",
        "title": "枫桥夜泊（一作夜泊枫江）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "月落乌啼霜满天，江枫渔父对愁眠。",
            "姑苏城外寒山寺，夜半钟声到客船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 阊门即事 ----------
    {
        "id": "zhang-ji-21",
        "title": "阊门即事",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "耕夫召募逐楼船，春草青青万顷田。",
            "试上吴门窥郡郭，清明几处有新烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 安公房问法 ----------
    {
        "id": "zhang-ji-22",
        "title": "安公房问法",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "流年一日复一日，世事何时是了时。",
            "试向东林问禅伯，遣将心地学琉璃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 上清词 ----------
    {
        "id": "zhang-ji-23",
        "title": "上清词",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "紫阳宫女捧丹砂，王母令过汉帝家。",
            "春风不肯停仙驭，却向蓬莱看杏花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 送顾况泗上觐叔父 ----------
    {
        "id": "zhang-ji-24",
        "title": "送顾况泗上觐叔父",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "吴乡岁贡足嘉宾，后进之中见此人。",
            "别业更临洙泗上，拟将书卷对残春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 留别（一作皇甫冉诗，题作又得云字） ----------
    {
        "id": "zhang-ji-25",
        "title": "留别（一作皇甫冉诗，题作又得云字）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "何事千年遇圣君，坐令双鬓老江云。",
            "南行更入山深浅，岐路悠悠水自分。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送张中丞归使幕（一作韩翃诗） ----------
    {
        "id": "zhang-ji-26",
        "title": "送张中丞归使幕（一作韩翃诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "独受主恩归，当朝似者稀。玉壶分御酒，金殿赐春衣。",
            "拂席流莺醉，鸣鞭骏马肥。满台簪白笔，捧手恋清辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 华州夜宴庾侍御宅（一作韩翃诗） ----------
    {
        "id": "zhang-ji-27",
        "title": "华州夜宴庾侍御宅（一作韩翃诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "世故他年别，心期此夜同。千峰孤烛外，片雨一更中。",
            "酒客逢山简，诗人得谢公。自怜驱匹马，拂曙向关东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 赠章八元 ----------
    {
        "id": "zhang-ji-28",
        "title": "赠章八元",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "相见谈经史，江楼坐夜阑。风声吹户响，灯影照人寒。",
            "俗薄交游尽，时危出处难。衰年逢二妙，亦得闷怀宽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 城西虎跑寺 ----------
    {
        "id": "zhang-ji-29",
        "title": "城西虎跑寺",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "石势虎蹲伏，山形龙屈盘。寺开梁殿阁，坟掩晋衣冠。",
            "出涧泉声细，斜阳塔影寒。近城多□□，栖息此中安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 褚主簿宅会毕庶子钱员外郎使君（一作韩翃诗） ----------
    {
        "id": "zhang-ji-30",
        "title": "褚主簿宅会毕庶子钱员外郎使君（一作韩翃诗）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "开瓮腊酒熟，主人心赏同。斜阳疏竹上，残雪乱山中。",
            "更喜宣城印，朝廷与谢公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 奉送王相公赴幽州（一作韩翃诗，题下有巡边二字） ----------
    {
        "id": "zhang-ji-31",
        "title": "奉送王相公赴幽州（一作韩翃诗，题下有巡边二字）",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "黄阁开帏幄，丹墀拜冕旒。位高汤左相，权总汉诸侯。",
            "不改周南化，仍分赵北忧。双旌过易水，千骑入幽州。",
            "塞草连天暮，边风动地愁。无因随远道，结束佩吴钩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 重经巴丘 ----------
    {
        "id": "zhang-ji-32",
        "title": "重经巴丘",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "昔年高接李膺欢，日泛仙舟醉碧澜。诗句乱随青草落，",
            "酒肠俱逐洞庭宽。浮生聚散云相似，往事冥微梦一般。",
            "今日片帆城下去，秋风回首泪阑干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 九日巴丘杨公台上宴集 ----------
    {
        "id": "zhang-ji-33",
        "title": "九日巴丘杨公台上宴集",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "凄凄霜日上高台，水国秋凉客思哀。万叠银山寒浪起，",
            "一行斜字早鸿来。谁家捣练孤城暮，何处题衣远信回。",
            "江汉路长身不定，菊花三笑旅怀开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 游灵岩 ----------
    {
        "id": "zhang-ji-34",
        "title": "游灵岩",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "灵岩有路入烟霞，台殿高低释子家。风满回廊飘坠叶，",
            "水流绝涧泛秋花。青松阅世风霜古，翠竹题诗岁月赊。",
            "谁谓无生真可学，山中亦自有年华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 河间献王墓 ----------
    {
        "id": "zhang-ji-35",
        "title": "河间献王墓",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "汉家宗室独称贤，遗事闲中见旧编。偶过河间寻往迹，",
            "却怜荒冢带寒烟。频求千古书连帙，独对三雍策几篇。",
            "雅乐未兴人已逝，雄歌依旧大风传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 秋日道中 ----------
    {
        "id": "zhang-ji-36",
        "title": "秋日道中",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "齐鲁西风草树秋，川原高下过东州。道边白鹤来华表，",
            "陌上苍麟卧古丘。九曲半应非禹迹，三山何处是仙洲。",
            "径行俯仰成今古，却忆当年赋远游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 华清宫 ----------
    {
        "id": "zhang-ji-37",
        "title": "华清宫",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "天宝承平奈乐何，华清宫殿郁嵯峨。朝元阁峻临秦岭，",
            "羯鼓楼高俯渭河。玉树长飘云外曲，霓裳闲舞月中歌。",
            "只今惟有温泉水，呜咽声中感慨多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 春申君祠 ----------
    {
        "id": "zhang-ji-38",
        "title": "春申君祠",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "春申祠宇空山里，古柏阴阴石泉水。日暮江南无主人，",
            "弥令过客思公子。萧条寒景傍山村，寂寞谁知楚相尊。",
            "当时珠履三千客，赵使怀惭不敢言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 人日代客子是日立春 ----------
    {
        "id": "zhang-ji-39",
        "title": "人日代客子是日立春",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "人日兼春日，长怀复短怀。遥知双彩胜，并在一金钗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 寄郑员外 ----------
    {
        "id": "zhang-ji-40",
        "title": "寄郑员外",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "经月愁闻雨，新年苦忆君。何时共登眺，整屐待晴云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 饮李十二宅 ----------
    {
        "id": "zhang-ji-41",
        "title": "饮李十二宅",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "重门敞春夕，灯烛霭馀辉。醉我百尊酒，留连夜未归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 山家 ----------
    {
        "id": "zhang-ji-42",
        "title": "山家",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "板桥人渡泉声，茅檐日午鸡鸣。",
            "莫嗔焙茶烟暗，却喜晒谷天晴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 归山 ----------
    {
        "id": "zhang-ji-43",
        "title": "归山",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "心事数茎白发，生涯一片青山。",
            "空林有雪相待，古道无人独还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 金谷园 ----------
    {
        "id": "zhang-ji-44",
        "title": "金谷园",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "彩楼歌馆正融融，一骑星飞锦帐空。",
            "老尽名花春不管，年年啼鸟怨东风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 邮亭 ----------
    {
        "id": "zhang-ji-45",
        "title": "邮亭",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "云淡山横日欲斜，邮亭下马对残花。",
            "自从身逐征西府，每到开时不在家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 宿白马寺 ----------
    {
        "id": "zhang-ji-46",
        "title": "宿白马寺",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "白马驮经事已空，断碑残刹见遗踪。",
            "萧萧茅屋秋风起，一夜雨声羁思浓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 明德宫 ----------
    {
        "id": "zhang-ji-47",
        "title": "明德宫",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "碧瓦朱楹白昼闲，金衣宝扇晓风寒。",
            "摩云观阁高如许，长对河流出断山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 读峄山碑 ----------
    {
        "id": "zhang-ji-48",
        "title": "读峄山碑",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "六国平来四海家，相君当代擅才华。",
            "谁知颂德山头石，却与他人戒后车。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 句 ----------
    {
        "id": "zhang-ji-49",
        "title": "句",
        "author": "张继",
        "poet_id": "zhang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "汉月经时掩，胡尘与岁深。（《咏镜》，见《诗式》）。",
            "第二百四十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]