# -*- coding: utf-8 -*-
"""
陆希声卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 21 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 山居即事二首 ----------
    {
        "id": "lu-xi-sheng-1",
        "title": "山居即事二首",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "君山苍翠接青冥，东走洮湖上洞庭。茅屋向阳梳白发，",
            "竹窗深夜诵丹经。涌泉回泬鱼龙气，怪石惊腾鸟兽形。",
            "为问前时金马客，此焉还作少微星。",
            "不是幽栖矫性灵，从来无意在膻腥。满川风物供高枕，",
            "四合云山借画屏。五鹿归来惊岳岳，孤鸿飞去入冥冥。",
            "君阳遁叟何为乐，一炷清香两卷经。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 阳羡杂咏十九首·苦行径 ----------
    {
        "id": "lu-xi-sheng-2",
        "title": "阳羡杂咏十九首·苦行径",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "山前无数碧琅玕，一径清森五月寒。",
            "世上何人怜苦节，应须细问子猷看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 阳羡杂咏十九首·梅花坞 ----------
    {
        "id": "lu-xi-sheng-3",
        "title": "阳羡杂咏十九首·梅花坞",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "冻蕊凝香色艳新，小山深坞伴幽人。",
            "知君有意凌寒色，羞共千花一样春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 阳羡杂咏十九首·石兕台 ----------
    {
        "id": "lu-xi-sheng-4",
        "title": "阳羡杂咏十九首·石兕台",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "大河波浪激潼关，青兕胡为伏此山。",
            "遥想楚王云梦泽，蜺旌羽盖定空还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 阳羡杂咏十九首·讲易台 ----------
    {
        "id": "lu-xi-sheng-5",
        "title": "阳羡杂咏十九首·讲易台",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "年逾知命志尤坚，独向青山更绝编。",
            "天下有山山有水，养蒙肥遁正翛然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 阳羡杂咏十九首·观鱼亭 ----------
    {
        "id": "lu-xi-sheng-6",
        "title": "阳羡杂咏十九首·观鱼亭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "惠施徒自学多方，谩说观鱼理未长。",
            "不得庄生濠上旨，江湖何以见相忘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 阳羡杂咏十九首·绿云亭 ----------
    {
        "id": "lu-xi-sheng-7",
        "title": "阳羡杂咏十九首·绿云亭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "六月清凉绿树阴，小亭高卧涤烦襟。",
            "羲皇向上何人到，永日时时弄素琴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 阳羡杂咏十九首·清辉堂 ----------
    {
        "id": "lu-xi-sheng-8",
        "title": "阳羡杂咏十九首·清辉堂",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "野人心地本无机，为爱茅檐倚翠微。",
            "尽日尊前谁是客，秋山含水有清辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 阳羡杂咏十九首·观妙庵 ----------
    {
        "id": "lu-xi-sheng-9",
        "title": "阳羡杂咏十九首·观妙庵",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "妙理难观旨甚深，欲知无欲是无心。",
            "茅庵不异人间世，河上真人自可寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 阳羡杂咏十九首·西阳亭 ----------
    {
        "id": "lu-xi-sheng-10",
        "title": "阳羡杂咏十九首·西阳亭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "隔林残日照孤亭，玄晏先生酒未醒。",
            "入夜莫愁迷下路，昔人犹在逐流萤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 阳羡杂咏十九首·弄云亭 ----------
    {
        "id": "lu-xi-sheng-11",
        "title": "阳羡杂咏十九首·弄云亭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "自知无业致吾君，只向春山弄白云。",
            "已共此山私断当，不须转辙重移文。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 阳羡杂咏十九首·伏龟堂 ----------
    {
        "id": "lu-xi-sheng-12",
        "title": "阳羡杂咏十九首·伏龟堂",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "盘崖蹙缩似灵龟，鬼谷先生隐遁时。",
            "不独卷怀经世志，白云流水是心期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 阳羡杂咏十九首·桃花谷 ----------
    {
        "id": "lu-xi-sheng-13",
        "title": "阳羡杂咏十九首·桃花谷",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "君阳山下足春风，满谷仙桃照水红。",
            "何必武陵源上去，涧边好过落花中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 阳羡杂咏十九首·含桃圃 ----------
    {
        "id": "lu-xi-sheng-14",
        "title": "阳羡杂咏十九首·含桃圃",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "小圃初晴风露光，含桃花发满山香。",
            "看花对酒心无事，倍觉春来白日长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 阳羡杂咏十九首·茗坡 ----------
    {
        "id": "lu-xi-sheng-15",
        "title": "阳羡杂咏十九首·茗坡",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "二月山家谷雨天，半坡芳茗露华鲜。",
            "春醒酒病兼消渴，惜取新芽旋摘煎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 阳羡杂咏十九首·松岭 ----------
    {
        "id": "lu-xi-sheng-16",
        "title": "阳羡杂咏十九首·松岭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "岭上青松手自栽，已能苍翠映莓苔。",
            "岁寒本是君家事，好送清风月下来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 阳羡杂咏十九首·桃溪 ----------
    {
        "id": "lu-xi-sheng-17",
        "title": "阳羡杂咏十九首·桃溪",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "芳草霏霏遍地齐，桃花脉脉自成溪。",
            "也知百舌多言语，任向春风尽意啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 阳羡杂咏十九首·李径 ----------
    {
        "id": "lu-xi-sheng-18",
        "title": "阳羡杂咏十九首·李径",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "一径秾芳万蕊攒，风吹雨打未摧残。",
            "怜君尽向高枝发，应为行人要整冠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 阳羡杂咏十九首·鸿盘 ----------
    {
        "id": "lu-xi-sheng-19",
        "title": "阳羡杂咏十九首·鸿盘",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "落落飞鸿渐始盘，青云起处剩须看。",
            "如今天路多矰缴，纵使衔芦去也难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 阳羡杂咏十九首·偃月岭 ----------
    {
        "id": "lu-xi-sheng-20",
        "title": "阳羡杂咏十九首·偃月岭",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "山岭依稀偃月形，数层倚石叠空青。",
            "几回雪夜寒光积，直似金光照户庭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 寄z6光上人 ----------
    {
        "id": "lu-xi-sheng-21",
        "title": "寄z6光上人",
        "author": "陆希声",
        "poet_id": "lu-xi-sheng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "笔下龙蛇似有神，天池雷雨变逡巡。",
            "寄言昔日不龟手，应念江头洴澼人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]