# -*- coding: utf-8 -*-
"""
周朴卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 46 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 题甘露寺 ----------
    {
        "id": "zhou-pu-1",
        "title": "题甘露寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "层阁叠危壁，瑞因千古名。几连扬子路，独倚润州城。",
            "云近衔江色，雕高背磬声。僧居上方久，端坐见营营。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 题玄公院 ----------
    {
        "id": "zhou-pu-2",
        "title": "题玄公院",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "院深尘自外，如佛值玄公。常迹或非次，志门因得中。",
            "衣巾离暑气，床榻向凉风。是事不逾分，只应明德同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 福州东禅寺 ----------
    {
        "id": "zhou-pu-3",
        "title": "福州东禅寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "瓯闽在郊外，师院号东禅。物得居来正，人经论后贤。",
            "瓟槽柳塞马，盖地月支綖。鹳鹊尚巢顶，谁堪举世传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠大沩和尚 ----------
    {
        "id": "zhou-pu-4",
        "title": "赠大沩和尚",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "大沩清复深，万象影沈沈。有客衣多毳，空门偈胜金。",
            "王侯皆作礼，陆子只来吟。我问师心处，师言无处心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 秋夜不寐寄崔温进士 ----------
    {
        "id": "zhou-pu-5",
        "title": "秋夜不寐寄崔温进士",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "愁多难得寐，展转读书床。不是旅人病，岂知秋夜长。",
            "归乡凭远梦，无梦更思乡。枕上移窗月，分明是泪光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 春中途中寄南巴崔使君 ----------
    {
        "id": "zhou-pu-6",
        "title": "春中途中寄南巴崔使君",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "旅人游汲汲，春气又融融。农事蛙声里，归程草色中。",
            "独惭出谷雨，未变暖天风。子玉和予去，应怜恨不穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 寄处士方干 ----------
    {
        "id": "zhou-pu-7",
        "title": "寄处士方干",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "桐庐江水闲，终日对柴关。因想别离处，不知多少山。",
            "钓舟春岸泊，庭树晓莺还。莫便求栖隐，桂枝堪恨颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 寄塞北张符 ----------
    {
        "id": "zhou-pu-8",
        "title": "寄塞北张符",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "陇树塞风吹，辽城角几枝。霜凝无暂歇，君貌莫应衰。",
            "万里平沙际，一行边雁移。那堪朔烟起，家信正相离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 次梧州却寄永州使君 ----------
    {
        "id": "zhou-pu-9",
        "title": "次梧州却寄永州使君",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "随风身不定，今夜在苍梧。客泪有时有，猿声无处无。",
            "潮添瘴海阔，烟拂粤山孤。却忆零陵住，吟诗半玉壶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 赠念经僧 ----------
    {
        "id": "zhou-pu-10",
        "title": "赠念经僧",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "庵前古折碑，夜静念经时。月皎海霞散，露浓山草垂。",
            "鬼闻抛故冢，禽听离寒枝。想得天花坠，馨香拂白眉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 董岭水 ----------
    {
        "id": "zhou-pu-11",
        "title": "董岭水",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "湖州安吉县，门与白云齐。禹力不到处，河声流向西。",
            "去衙山色远，近水月光低。中有高人在，沙中曳杖藜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 早春 ----------
    {
        "id": "zhou-pu-12",
        "title": "早春",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "良夜岁应足，严风为变春。遍回寒作暖，通改旧成新。",
            "秀树因馨雨，融冰雨泛蘋。韶光不偏党，积渐煦疲民。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 秋深（一作塞上行） ----------
    {
        "id": "zhou-pu-13",
        "title": "秋深（一作塞上行）",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "柳色尚沈沈，风吹秋更深。山河空远道，乡国自鸣砧。",
            "巷有千家月，人无万里心。长城哭崩后，寂绝至如今。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 赠双峰山和尚 ----------
    {
        "id": "zhou-pu-14",
        "title": "赠双峰山和尚",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "峨峨双髻山，瀑布泻云间。尘世自疑水，禅门长去关。",
            "茯神松不异，藏宝石俱闲。向此师清业，如何方可攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 赠无了禅师 ----------
    {
        "id": "zhou-pu-15",
        "title": "赠无了禅师",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "不学世所惜，是何无了公。灵匡虚院外，虎迹乱山中。",
            "昼夜必连去，古今争敢同。禅情岂堪问，问答更无穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 王霸坛 ----------
    {
        "id": "zhou-pu-16",
        "title": "王霸坛",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "王君上升处，信首古居前。皂树即须朽，白龟应亦全。",
            "云间犹一日，尘里已千年。碧色坛如黛，时人谁可仙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送梁道士 ----------
    {
        "id": "zhou-pu-17",
        "title": "送梁道士",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "旧居桐柏观，归去爱安闲。倒树造新屋，化人修古坛。",
            "晚花霜后落，山雨夜深寒。应有同溪客，相寻学炼丹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 边思 ----------
    {
        "id": "zhou-pu-18",
        "title": "边思",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "年高来远戍，白首罢干戎。夜色蓟门火，秋声边塞风。",
            "碛浮悲老马，月满引新弓。百战阴山去，唯添上将雄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 哭陈庾 ----------
    {
        "id": "zhou-pu-19",
        "title": "哭陈庾",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "系马向山立，一杯聊奠君。野烟孤客路，寒草故人坟。",
            "琴韵归流水，诗情寄白云。日斜休哭后，松韵不堪闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 宿玉泉寺 ----------
    {
        "id": "zhou-pu-20",
        "title": "宿玉泉寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "野寺度残夏，空房欲暮时。夜听猿不睡，秋思客先知。",
            "竹迥烟生薄，山高月上迟。又登尘路去，难与老僧期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 题赤城中岩寺 ----------
    {
        "id": "zhou-pu-21",
        "title": "题赤城中岩寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "浮世师休话，晋时灯照岩。禽飞穿静户，藤结入高杉。",
            "存没诗千首，废兴经数函。谁知将俗耳，来此避嚣谗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 塞上行 ----------
    {
        "id": "zhou-pu-22",
        "title": "塞上行",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "秦筑长城在，连云碛气侵。风吹边草急，角绝塞鸿沈。",
            "世世征人往，年年战骨深。辽天望乡者，回首尽沾襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 玉泉寺 ----------
    {
        "id": "zhou-pu-23",
        "title": "玉泉寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "寺还名玉泉，澄水亦遭贤。物尚犹如此，人争合偶然。",
            "溪流云断外，山峻鸟飞还。初日长廊下，高僧正坐禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 春宫怨（一作杜荀鹤诗） ----------
    {
        "id": "zhou-pu-24",
        "title": "春宫怨（一作杜荀鹤诗）",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "早被婵娟误，欲妆临镜慵。承恩不在貌，教妾若为容。",
            "风暖鸟声碎，日高花影重。年年越溪女，相忆采芙蓉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 宿刘温书斋 ----------
    {
        "id": "zhou-pu-25",
        "title": "宿刘温书斋",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "不掩盈窗日，天然格调高。凉风移蟋蟀，落叶在离骚。",
            "回笔挑灯烬，悬图见海潮。因论三国志，空载几英豪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 登福州南涧寺 ----------
    {
        "id": "zhou-pu-26",
        "title": "登福州南涧寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "万里重山绕福州，南横一道见溪流。天边飞鸟东西没，",
            "尘里行人早晚休。晓日青山当大海，连云古堑对高楼。",
            "那堪望断他乡目，只此萧条自白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 望中怀古 ----------
    {
        "id": "zhou-pu-27",
        "title": "望中怀古",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "齐心楼上望浮云，万古千秋空姓名。尧水永销天际去，",
            "姬风一变世间平。高踪尽共烟霞在，大道长将日月明。",
            "从此安然寰海内，后来无复谩相倾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 升山寺 ----------
    {
        "id": "zhou-pu-28",
        "title": "升山寺",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "升山自古道飞来，此是神功不可猜。气色虽然离禹穴，",
            "峰峦犹自接天台。岩边折树泉冲落，顶上浮云日照开。",
            "南望闽城尘世界，千秋万古卷尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 哭李端 ----------
    {
        "id": "zhou-pu-29",
        "title": "哭李端",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "三年剪拂感知音，哭向青山永夜心。竹在晓烟孤凤去，",
            "剑荒秋水一龙沈。新坟日落松声小，旧色春残草色深。",
            "不及此时亲执绋，石门遥想泪沾襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 福州神光寺塔 ----------
    {
        "id": "zhou-pu-30",
        "title": "福州神光寺塔",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "良匠用材为塔了，神光寺更得高名。风云会处千寻出，",
            "日月中时八面明。海水旋流倭国野，天文方戴福州城。",
            "相轮顶上望浮世，尘里人心应总平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 福州开元寺塔 ----------
    {
        "id": "zhou-pu-31",
        "title": "福州开元寺塔",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "开元寺里七重塔，遥对方山影拟齐。杂俗人看离世界，",
            "孤高僧上觉天低。唯堪片片紫霞映，不与濛濛白雾迷。",
            "心若无私罗汉在，参差免向日虹西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 春日秦国怀古 ----------
    {
        "id": "zhou-pu-32",
        "title": "春日秦国怀古",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "荒郊一望欲消魂，泾水萦纡傍远村。牛马放多春草尽，",
            "原田耕破古碑存。云和积雪苍山晚，烟伴残阳绿树昏。",
            "数里黄沙行客路，不堪回首思秦原。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 春日游北园寄韩侍郎 ----------
    {
        "id": "zhou-pu-33",
        "title": "春日游北园寄韩侍郎",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "灼灼春园晚色分，露珠千点映寒云。多情舞蝶穿花去，",
            "解语流莺隔水闻。冷酒杯中宜泛滟，暖风林下自氛氲。",
            "仙桃不肯全开拆，应借馀芳待使君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 喜贺拔先辈衡阳除正字 ----------
    {
        "id": "zhou-pu-34",
        "title": "喜贺拔先辈衡阳除正字",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "黄纸晴空坠一缄，圣朝恩泽洗冤谗。李膺门客为闲客，",
            "梅福官衔改旧衔。名自石渠书典籍，香从芸阁著衣衫。",
            "寰中不用忧天旱，霖雨看看属傅岩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 客州赁居寄萧郎中 ----------
    {
        "id": "zhou-pu-35",
        "title": "客州赁居寄萧郎中",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "松店茅轩向水开，东头舍赁一裴徊。窗吟苦为秋江静，",
            "枕梦惊因晓角催。邻舍见愁赊酒与，主人知去索钱来。",
            "眼看白笔为霖雨，肯使红鳞便曝腮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 赠李裕先辈 ----------
    {
        "id": "zhou-pu-36",
        "title": "赠李裕先辈",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "晓擎弓箭入初场，一发曾穿百步杨。仙籍旧题前进士，",
            "圣朝新奏校书郎。马疑金马门前马，香认芸香阁上香。",
            "闲伴李膺红烛下，慢吟丝竹浅飞觞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 桐柏观 ----------
    {
        "id": "zhou-pu-37",
        "title": "桐柏观",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "东南一境清心目，有此千峰插翠微。人在下方冲月上，",
            "鹤从高处破烟飞。岩深水落寒侵骨，门静花开色照衣。",
            "欲识蓬莱今便是，更于何处学忘机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 塞上 ----------
    {
        "id": "zhou-pu-38",
        "title": "塞上",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "受降城必破，回落陇头移。蕃道北海北，谋生今始知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 塞上曲 ----------
    {
        "id": "zhou-pu-39",
        "title": "塞上曲",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "一阵风来一阵砂，有人行处没人家。",
            "黄河九曲冰先合，紫塞三春不见花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 塞下曲 ----------
    {
        "id": "zhou-pu-40",
        "title": "塞下曲",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "石国胡儿向碛东，爱吹横笛引秋风。",
            "夜来云雨皆飞尽，月照平沙万里空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 咏猿 ----------
    {
        "id": "zhou-pu-41",
        "title": "咏猿",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "生在巫山更向西，不知何事到巴溪。",
            "中宵为忆秋云伴，遥隔朱门向月啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 桃花 ----------
    {
        "id": "zhou-pu-42",
        "title": "桃花",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "桃花春色暖先开，明媚谁人不看来。",
            "可惜狂风吹落后，殷红片片点莓苔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 薛老峰 ----------
    {
        "id": "zhou-pu-43",
        "title": "薛老峰",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "薛老峰头三个字，须知此与石齐生。",
            "直教截断苍苔色，浮世人侪眼始明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 吊李群玉 ----------
    {
        "id": "zhou-pu-44",
        "title": "吊李群玉",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "群玉诗名冠李唐，投诗换得校书郎。",
            "吟魂醉魄知何处，空有幽兰隔岸香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 无等岩 ----------
    {
        "id": "zhou-pu-45",
        "title": "无等岩",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "建造上方藤影里，高僧往往似天台。",
            "不知名树檐前长，曾问道人岩下来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 句 ----------
    {
        "id": "zhou-pu-46",
        "title": "句",
        "author": "周朴",
        "poet_id": "zhou-pu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "古陵寒雨集，高鸟夕阳明。",
            "高情千里外，长啸一声初。（以上见张为《主客图》）",
            "月离山一丈，风吹花数苞。（见《吟窗杂录》）",
            "晓来山鸟闹，雨过杏花稀。（见《优古堂诗话》）",
            "曲渚回湾锁钓舟。",
            "平潮晚影沈清底，远岳危栏等翠尖。（上见《海录碎事》）",
            "白日才离沧海底，清光先照户窗前。（灵岩广化寺，",
            "见《闽志》）",
            "连云天堑有山色，极目海门无雁行。",
            "可怜黄雀衔将去，从此庄周梦不成。（《咏蝶》。",
            "见《泉州志》）",
            "禅是大沩诗是朴，大唐天子只三人。（《赠大沩》）",
            "第六百七十四卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]