# -*- coding: utf-8 -*-
"""
崔日用卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 郊庙歌辞·享龙池乐章·第六章 ----------
    {
        "id": "cui-ri-yong-1",
        "title": "郊庙歌辞·享龙池乐章·第六章",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "龙兴白水汉兴符，圣主时乘运斗枢。岸上丰茸五花树，",
            "波中的皪千金珠。操环昔闻迎夏启，发匣先来瑞有虞。",
            "风色云光随隐见，赤云神化象江湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉和九月九日登慈恩寺浮图应制 ----------
    {
        "id": "cui-ri-yong-2",
        "title": "奉和九月九日登慈恩寺浮图应制",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "紫宸欢每洽，绀殿法初隆。菊泛延龄酒，兰吹解愠风。",
            "咸英调正乐，香梵遍秋空。临幸浮天瑞，重阳日再中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 奉和圣制送张说巡边 ----------
    {
        "id": "cui-ri-yong-3",
        "title": "奉和圣制送张说巡边",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "轩相推风后，周官重夏卿。庙谋能允迪，韬略又纵横。",
            "吉日四黄马，宣王六月兵。拟清鸡鹿塞，先指朔方城。",
            "列将怀威抚，匈奴畏盛名。去当推毂送，来伫出郊迎。",
            "绝漠蓬将断，华筵槿正荣。壮心看舞剑，别绪应悬旌。",
            "睿锡承优旨，乾文复宠行。暂劳期永逸，赫矣振天声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 奉和立春游苑迎春应制 ----------
    {
        "id": "cui-ri-yong-4",
        "title": "奉和立春游苑迎春应制",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "乘时迎气正璿衡，灞浐烟氛向晚清。剪绮裁红妙春色，",
            "宫梅殿柳识天情。瑶筐彩燕先呈瑞，金缕晨鸡未学鸣。",
            "圣泽阳和宜宴乐，年年捧日向东城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 奉和圣制春日幸望春宫应制 ----------
    {
        "id": "cui-ri-yong-5",
        "title": "奉和圣制春日幸望春宫应制",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "东郊风物正熏馨，素浐凫鹥戏绿汀。凤阁斜通平乐观，",
            "龙旂直逼望春亭。光风摇动兰英紫，淑气依迟柳色青。",
            "渭浦明晨修禊事，群公倾贺水心铭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 奉和人日重宴大明宫恩赐彩缕人胜应制 ----------
    {
        "id": "cui-ri-yong-6",
        "title": "奉和人日重宴大明宫恩赐彩缕人胜应制",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "新年宴乐坐东朝，钟鼓铿锽大乐调。金屋瑶筐开宝胜，",
            "花笺彩笔颂春椒。曲池苔色冰前液，上苑梅香雪里娇。",
            "宸极此时飞圣藻，微臣窃抃预闻韶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 奉和圣制龙池篇 ----------
    {
        "id": "cui-ri-yong-7",
        "title": "奉和圣制龙池篇",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "龙兴白水汉兴符，圣主时乘运斗枢。岸上zv茸五花树，",
            "波中的皪千金珠。操环昔闻迎夏启，发匣先来瑞有虞。",
            "风色云光随隐见，赤云神化象江湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 夜宴安乐公主宅 ----------
    {
        "id": "cui-ri-yong-8",
        "title": "夜宴安乐公主宅",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "银烛金屏坐碧堂，只言河汉动神光。",
            "主家盛时欢不极，才子能歌夜未央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 饯唐永昌 ----------
    {
        "id": "cui-ri-yong-9",
        "title": "饯唐永昌",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "洛阳桴鼓今不鸣，朝野咸推重太平。",
            "冬至冰霜俱怨别，春来花鸟若为情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 奉和送金城公主适西蕃 ----------
    {
        "id": "cui-ri-yong-10",
        "title": "奉和送金城公主适西蕃",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "圣后经纶远，谋臣计画多。受降追汉策，筑馆计戎和。",
            "俗化乌孙垒，春生积石河。六龙今出饯，双鹤愿为歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 句 ----------
    {
        "id": "cui-ri-yong-11",
        "title": "句",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "彼名流兮左氏癖，意玄远兮冠今夕。（《赠武平一》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 乞金鱼词 ----------
    {
        "id": "cui-ri-yong-12",
        "title": "乞金鱼词",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "台中鼠子直须谙，信足跳梁上壁龛。倚翻灯脂污张五，",
            "还来啮带报韩三。莫浪语，直王相。大家必若赐金龟，",
            "卖却猫儿相报赏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 又赐宴自歌 ----------
    {
        "id": "cui-ri-yong-13",
        "title": "又赐宴自歌",
        "author": "崔日用",
        "poet_id": "cui-ri-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "东馆总是鹓鸾，南台自多杞梓。日用读书万卷，",
            "何忍不蒙学士。墨制帘下出来，微臣眼看喜死。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]