# -*- coding: utf-8 -*-
"""
郑絪卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 郊庙歌辞·享太庙乐章·大顺舞 ----------
    {
        "id": "zheng-yin-1",
        "title": "郊庙歌辞·享太庙乐章·大顺舞",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "於穆时文，受天明命。允恭玄默，化成理定。",
            "出震嗣德，应乾传圣。猗欤缉熙，千亿流庆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉和武相公省中宿斋，酬李相公见寄 ----------
    {
        "id": "zheng-yin-2",
        "title": "奉和武相公省中宿斋，酬李相公见寄",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "高阁安仁省，名园广武庐。沐兰朝太一，种竹咏华胥。",
            "禁静疏钟彻，庭开爽韵虚。洪钧齐万物，缥帙整群书。",
            "寒露滋新菊，秋风落故蕖。同怀不同赏，幽意竟何如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寒夜闻霜钟 ----------
    {
        "id": "zheng-yin-3",
        "title": "寒夜闻霜钟",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "霜钟初应律，寂寂出重林。拂水宜清听，凌空散迥音。",
            "舂容时未歇，摇曳夜方深。月下和虚籁，风前间远砧。",
            "净兼寒漏彻，闲畏曙更侵。遥相千山外，泠泠何处寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 奉酬宣上人九月十五日东亭望月见赠因怀紫阁旧游 ----------
    {
        "id": "zheng-yin-4",
        "title": "奉酬宣上人九月十五日东亭望月见赠因怀紫阁旧游",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "中年偶逐鸳鸾侣，弱岁多从糜鹿群。紫阁道流今不见，",
            "红楼禅客早曾闻。松斋月朗星初散，苔砌霜繁夜欲分。",
            "一览彩笺佳句满，何人更咏惠休文。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 九日登高怀邵二 ----------
    {
        "id": "zheng-yin-5",
        "title": "九日登高怀邵二",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "簪茱泛菊俯平阡，饮过三杯却惘然。",
            "十岁此辰同醉友，登高各处已三年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 享太庙乐章 ----------
    {
        "id": "zheng-yin-6",
        "title": "享太庙乐章",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "於穆时文，受天明命。允恭玄默，化成理定。",
            "出震嗣德，应乾传圣。猗欤缉熙，千亿流庆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 句 ----------
    {
        "id": "zheng-yin-7",
        "title": "句",
        "author": "郑絪",
        "poet_id": "zheng-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "情人共惆怅，良友不同游。（《纪事》云：絪九日有怀邵",
            "二诗，又怀林十二云云，其重友如此）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]