# -*- coding: utf-8 -*-
"""
陆畅卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 37 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 云安公主下降奉诏作催妆诗 ----------
    {
        "id": "lu-chang-1",
        "title": "云安公主下降奉诏作催妆诗",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "云安公主贵，出嫁五侯家。天母亲调粉，日兄怜赐花。",
            "催铺百子帐，待障七香车。借问妆成未，东方欲晓霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 山出云 ----------
    {
        "id": "lu-chang-2",
        "title": "山出云",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "灵山蓄云彩，纷郁出清晨。望树繁花白，看峰小雪新。",
            "映松张盖影，依涧布鱼鳞。高似从龙处，低如触石频。",
            "浓光藏半岫，浅色类飘尘。玉叶开天际，遥怜占早春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 惊雪 ----------
    {
        "id": "lu-chang-3",
        "title": "惊雪",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "五言绝句",
        "year": "约中唐",
        "source": "《全唐诗·卷四七八》",
        "verse": [
            "怪得北风急，前庭如月辉。天人宁许巧，剪水作花飞。",
        ],
        "tijie": "此诗写雪，以「剪水作花」之奇想状雪之飞舞，构思精巧，为唐人咏雪小诗之巧作。",
        "notes": [
            ("怪得", "怪不得、难怪。"),
            ("月辉", "月光般光辉，喻雪反光。"),
            ("宁许巧", "怎如此巧。"),
            ("剪水作花", "喻雪如剪水成花。"),
        ],
        "appreciation": "首二句「怪得北风急，前庭如月辉」写北风急骤、前庭雪映如月，设疑而起；后二句「天人宁许巧，剪水作花飞」答疑：天公何其巧也，剪水成花漫天飞——以「剪水作花」喻雪，想象奇绝，将无形之雪化为可剪之花。陆畅此诗小巧玲珑，于咏雪常题中翻出新巧，与韩愈「白雪却嫌春色晚」同一机杼。",
        "famous": [
            ("天人宁许巧，剪水作花飞。", "咏雪巧喻，想象奇绝。"),
        ],
        "sources": [
            "《全唐诗》卷四七八",
            "《唐诗鉴赏辞典》陆畅条（上海辞书出版社，1983）",
        ],
    },
    # ---------- 4. 闻早蝉 ----------
    {
        "id": "lu-chang-4",
        "title": "闻早蝉",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "落日早蝉急，客心闻更愁。一声来枕上，梦里故园秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 别刘端公 ----------
    {
        "id": "lu-chang-5",
        "title": "别刘端公",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "连骑出都门，秋蝉噪高柳。落日辞故人，自醉不关酒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 新晴爱月（一作山斋玩月） ----------
    {
        "id": "lu-chang-6",
        "title": "新晴爱月（一作山斋玩月）",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "野性平生惟爱月，新晴半夜睹蝉娟。",
            "起来自擘纱窗破，恰漏清光落枕前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 云安公主出降杂咏催妆二首 ----------
    {
        "id": "lu-chang-7",
        "title": "云安公主出降杂咏催妆二首",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "天上琼花不避秋，今宵织女嫁牵牛。",
            "万人惟待乘鸾出，乞巧齐登明月楼。",
            "少妆银粉饰金钿，端正天花贵自然。",
            "闻道禁中时节异，九秋香满镜台前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 坐障 ----------
    {
        "id": "lu-chang-8",
        "title": "坐障",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "白玉为竿丁字成，黄金绣带短长轻。",
            "强遮天上花颜色，不隔云中语笑声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 帘 ----------
    {
        "id": "lu-chang-9",
        "title": "帘",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "劳将素手卷虾须，琼室流光更缀珠。",
            "玉漏报来过半夜，可怜潘岳立踟蹰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 阶 ----------
    {
        "id": "lu-chang-10",
        "title": "阶",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "甃玉编金次第平，花纹隐起踏无声。",
            "几重便上华堂里，得见天人吹凤笙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 扇 ----------
    {
        "id": "lu-chang-11",
        "title": "扇",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "宝扇持来入禁宫，本教花下动香风。",
            "姮娥须逐彩云降，不可通宵在月中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 解内人嘲（一作酬宫人） ----------
    {
        "id": "lu-chang-12",
        "title": "解内人嘲（一作酬宫人）",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "粉面仙郎选圣朝，偶逢秦女学吹箫。",
            "须教翡翠闻王母，不奈乌鸢噪鹊桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 成都赠别席夔 ----------
    {
        "id": "lu-chang-13",
        "title": "成都赠别席夔",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "不值分流二江水，定应犹得且同行。",
            "三千里外情人别，更被子规啼数声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 游城东王驸马亭 ----------
    {
        "id": "lu-chang-14",
        "title": "游城东王驸马亭",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "城外无尘水间松，秋天木落见山容。",
            "共寻萧史江亭去，一望终南紫阁峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 望毛女峰 ----------
    {
        "id": "lu-chang-15",
        "title": "望毛女峰",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "我种东峰千叶莲，此峰毛女始求仙。",
            "今朝暗算当时事，已是人间七万年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送李山人归山 ----------
    {
        "id": "lu-chang-16",
        "title": "送李山人归山",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "来从千山万山里，归向千山万山去。",
            "山中白云千万重，却望人间不知处。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 长安新晴 ----------
    {
        "id": "lu-chang-17",
        "title": "长安新晴",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "九重深浅人不知，金殿玉楼倚朝日。",
            "一夜城中新雨晴，御沟流得宫花出。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 出蓝田关寄董使君 ----------
    {
        "id": "lu-chang-18",
        "title": "出蓝田关寄董使君",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "万里烟萝锦帐间，云迎水送度蓝关。",
            "七盘九折难行处，尽是龚黄界外山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 题悟公禅堂 ----------
    {
        "id": "lu-chang-19",
        "title": "题悟公禅堂",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "临坛付法十三春，家本长城若下人。",
            "芸阁少年应不识，南山钞主是前身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 宿陕府北楼奉酬崔大夫二首 ----------
    {
        "id": "lu-chang-20",
        "title": "宿陕府北楼奉酬崔大夫二首",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "楼压黄河山满坐，风清水凉谁忍卧。",
            "人定军州禁漏传，不妨秋月城头过。",
            "一别朱门三四春，再来应笑尚风尘。",
            "昨宵唯有楼前月，识是谢公诗酒人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 陕州逢窦巩同宿，寄江陵韦协律 ----------
    {
        "id": "lu-chang-21",
        "title": "陕州逢窦巩同宿，寄江陵韦协律",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "共出丘门岁九霜，相逢凄怆对离觞。",
            "荆南为报韦从事，一宿同眠御史床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 夜到泗州酬崔使君 ----------
    {
        "id": "lu-chang-22",
        "title": "夜到泗州酬崔使君",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "徐城洪尽到淮头，月里山河见泗州。",
            "闻道泗滨清庙磬，雅声今在谢家楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送崔员外使回入京金钩驿逢因赠 ----------
    {
        "id": "lu-chang-23",
        "title": "送崔员外使回入京金钩驿逢因赠",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "六星宫里一星归，行到金钩近紫微。",
            "侍史别来经岁月，今宵应梦护香衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 成都送别费冠卿 ----------
    {
        "id": "lu-chang-24",
        "title": "成都送别费冠卿",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "红椒花落桂花开，万里同游俱未回。",
            "莫厌客中频送客，思乡独上望乡台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 题商山庙 ----------
    {
        "id": "lu-chang-25",
        "title": "题商山庙",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "商洛秦时四老翁，人传羽化此山空。",
            "若无仙眼何由见，总在庙前花洞中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 题独孤少府园林 ----------
    {
        "id": "lu-chang-26",
        "title": "题独孤少府园林",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "四面青山是四邻，烟霞成伴草成茵。",
            "年年洞口桃花发，不记曾经迷几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 送独孤秀才下第归太白山 ----------
    {
        "id": "lu-chang-27",
        "title": "送独孤秀才下第归太白山",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "逸翮暂时成落羽，将归太白赏灵踪。",
            "须寻最近碧霄处，拟倩和云买一峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 下第后病中 ----------
    {
        "id": "lu-chang-28",
        "title": "下第后病中",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "献玉频年命未通，穷秋成病悟真空。",
            "笑看朝市趋名者，不病那知在病中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 送深上人归江南 ----------
    {
        "id": "lu-chang-29",
        "title": "送深上人归江南",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "留得莲花偈付谁，独携金策欲归时。",
            "江南无限萧家寺，曾与白云何处期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 题自然观 ----------
    {
        "id": "lu-chang-30",
        "title": "题自然观",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "剑阁门西第一峰，道陵成道有高踪。",
            "行人若上升仙处，须拨白云三四重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 疾愈步庭花 ----------
    {
        "id": "lu-chang-31",
        "title": "疾愈步庭花",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "桃红李白觉春归，强步闲庭力尚微。",
            "从困不扶灵寿杖，恐惊花里早莺飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 筹笔店江亭 ----------
    {
        "id": "lu-chang-32",
        "title": "筹笔店江亭",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "九折岩边下马行，江亭暂歇听江声。",
            "白云绿树不关我，枉与樵人乐一生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 赠贺若少府 ----------
    {
        "id": "lu-chang-33",
        "title": "赠贺若少府",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "十日广陵城里住，听君花下抚金徽。",
            "新声指上怀中纸，莫怪潜偷数曲归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 太子刘舍人邀看花 ----------
    {
        "id": "lu-chang-34",
        "title": "太子刘舍人邀看花",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "年少风流七品官，朱衣白马冶游盘。",
            "负心不报春光主，几处偷看红牡丹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 蔷薇花 ----------
    {
        "id": "lu-chang-35",
        "title": "蔷薇花",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "锦窠花朵灯丛醉，翠叶眉稠裛露垂。",
            "莫引美人来架下，恐惊红片落燕支。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 句 ----------
    {
        "id": "lu-chang-36",
        "title": "句",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "蜀道易，易于履平地。（《蜀道易》）",
            "蝉噪入云树，风开无主花。（《崔谏议林亭》）",
            "第四百七十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 句 ----------
    {
        "id": "lu-chang-37",
        "title": "句",
        "author": "陆畅",
        "poet_id": "lu-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "满手香传金菊酒，漏声遥滴上阳宫。（《九日》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]