# -*- coding: utf-8 -*-
"""
雍裕之卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 31 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·自君之出矣 ----------
    {
        "id": "yong-yu-zhi-1",
        "title": "杂曲歌辞·自君之出矣",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "自君之出矣，宝镜为谁明。思君如陇水，长闻呜咽声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 五杂组 ----------
    {
        "id": "yong-yu-zhi-2",
        "title": "五杂组",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "五杂组，刺绣窠。往复还，织锦梭。不得已，戍交河。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 剪彩花 ----------
    {
        "id": "yong-yu-zhi-3",
        "title": "剪彩花",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "敢竞桃李色，自呈刀尺功。蝶犹迷剪翠，人岂辨裁红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春晦送客（一作三月晦日郊外送客） ----------
    {
        "id": "yong-yu-zhi-4",
        "title": "春晦送客（一作三月晦日郊外送客）",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "野酌乱无巡，送君兼送春。明年春色至，莫作未归人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 自君之出矣 ----------
    {
        "id": "yong-yu-zhi-5",
        "title": "自君之出矣",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "自君之出矣，宝镜为谁明。思君如陇水，长闻呜咽声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 四气 ----------
    {
        "id": "yong-yu-zhi-6",
        "title": "四气",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "春禽犹竞啭，夏木忽交阴。稍觉秋山远，俄惊冬霰深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 四色 ----------
    {
        "id": "yong-yu-zhi-7",
        "title": "四色",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "壶中冰始结，盘上露初圆。何意瑶池雪，欲夺鹤毛鲜。",
            "道士牛已至，仙家鸟亦来。骨为神不朽，眼向故人开。",
            "劳鲂莲渚内，汗马火旂间。平生血诚尽，不独左轮殷。",
            "已见池尽墨，谁言突不黔。漆身恩未报，貂裘弊岂嫌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 大言 ----------
    {
        "id": "yong-yu-zhi-8",
        "title": "大言",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "四溟杯渌醑，五岳髻青螺。挥汗曾成雨，画地亦成河。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 细言 ----------
    {
        "id": "yong-yu-zhi-9",
        "title": "细言",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "蚊眉自可托，蜗角岂劳争。欲效丝毫力，谁知蝼蚁诚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 山中桂 ----------
    {
        "id": "yong-yu-zhi-10",
        "title": "山中桂",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "八树拂丹霄，四时青不凋。秋风何处起，先袅最长条。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 芦花 ----------
    {
        "id": "yong-yu-zhi-11",
        "title": "芦花",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "夹岸复连沙，枝枝摇浪花。月明浑似雪，无处认渔家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 江边柳 ----------
    {
        "id": "yong-yu-zhi-12",
        "title": "江边柳",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "袅袅古堤边，青青一树烟。若为丝不断，留取系郎船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 江上山 ----------
    {
        "id": "yong-yu-zhi-13",
        "title": "江上山",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "绮霞明赤岸，锦缆绕丹枝。楚客正愁绝，西风且莫吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 游丝 ----------
    {
        "id": "yong-yu-zhi-14",
        "title": "游丝",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "游丝何所似，应最似春心。一向风前乱，千条不可寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 柳絮 ----------
    {
        "id": "yong-yu-zhi-15",
        "title": "柳絮",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "无风才到地，有风还满空。缘渠偏似雪，莫近鬓毛生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 残莺 ----------
    {
        "id": "yong-yu-zhi-16",
        "title": "残莺",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "花阑莺亦懒，不语似含情。何言百啭舌，唯馀一两声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 早蝉 ----------
    {
        "id": "yong-yu-zhi-17",
        "title": "早蝉",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "一声清溽暑，几处促流年。志士心偏苦，初闻独泫然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 秋蛩 ----------
    {
        "id": "yong-yu-zhi-18",
        "title": "秋蛩",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "雨绝苍苔地，月斜青草阶。蛩鸣谁不怨，况是正离怀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 江上闻猿 ----------
    {
        "id": "yong-yu-zhi-19",
        "title": "江上闻猿",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "枫岸月斜明，猿啼旅梦惊。愁多肠易断，不待第三声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 折柳赠行人 ----------
    {
        "id": "yong-yu-zhi-20",
        "title": "折柳赠行人",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "那言柳乱垂，尽日任风吹。欲识千条恨，和烟折一枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 题蒲葵扇 ----------
    {
        "id": "yong-yu-zhi-21",
        "title": "题蒲葵扇",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "倾心曾向日，在手幸摇风。羡尔逢提握，知名自谢公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 赠苦行僧 ----------
    {
        "id": "yong-yu-zhi-22",
        "title": "赠苦行僧",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "幽深红叶寺，清净白毫僧。古殿长鸣磬，低头礼昼灯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 两头纤纤 ----------
    {
        "id": "yong-yu-zhi-23",
        "title": "两头纤纤",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "两头纤纤八字眉，半白半黑灯影帷。",
            "腷腷膊膊晓禽飞，磊磊落落秋果垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 了语 ----------
    {
        "id": "yong-yu-zhi-24",
        "title": "了语",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "扫却烟尘寇初剿，深水高林放鱼鸟。",
            "鸡人唱绝残漏晓，仙乐拍终天悄悄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 不了语 ----------
    {
        "id": "yong-yu-zhi-25",
        "title": "不了语",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "浮名世利知多少，朝市喧喧尘扰扰。",
            "车马交驰往复来，钟鼓相催天又晓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 听弹沈湘 ----------
    {
        "id": "yong-yu-zhi-26",
        "title": "听弹沈湘",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "贾谊投文吊屈平，瑶琴能写此时情。",
            "秋风一奏沈湘曲，流水千年作恨声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 豪家夏冰咏 ----------
    {
        "id": "yong-yu-zhi-27",
        "title": "豪家夏冰咏",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "金错银盘贮赐冰，清光如耸玉山棱。",
            "无论尘客闲停扇，直到消时不见蝇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 宿棣华馆闻雁 ----------
    {
        "id": "yong-yu-zhi-28",
        "title": "宿棣华馆闻雁",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "不堪旅宿棣花馆，况有离群鸿雁声。",
            "一点秋灯残影下，不知寒梦几回惊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 农家望晴 ----------
    {
        "id": "yong-yu-zhi-29",
        "title": "农家望晴",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "尝闻秦地西风雨，为问西风早晚回。",
            "白发老农如鹤立，麦场高处望云开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 宫人斜 ----------
    {
        "id": "yong-yu-zhi-30",
        "title": "宫人斜",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "几多红粉委黄泥，野鸟如歌又似啼。",
            "应有春魂化为燕，年来飞入未央栖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 曲江池上 ----------
    {
        "id": "yong-yu-zhi-31",
        "title": "曲江池上",
        "author": "雍裕之",
        "poet_id": "yong-yu-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "殷勤春在曲江头，全藉群仙占胜游。",
            "何必三山待鸾鹤，年年此地是瀛洲。",
            "第四百七十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]