# -*- coding: utf-8 -*-
"""
唐求卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 36 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 酬友生早秋 ----------
    {
        "id": "tang-qiu-1",
        "title": "酬友生早秋",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "彤云将欲罢，蝉柳响如秋。雾散九霄近，日程三伏愁。",
            "残阳宿雨霁，高浪碎沙沤。袪足馀旬后，分襟任自由。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 晓发 ----------
    {
        "id": "tang-qiu-2",
        "title": "晓发",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "旅馆候天曙，整车趋远程。几处晓钟断，半桥残月明。",
            "沙上鸟犹在，渡头人未行。去去古时道，马嘶三两声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 客行 ----------
    {
        "id": "tang-qiu-3",
        "title": "客行",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "上山下山去，千里万里愁。树色野桥暝，雨声孤馆秋。",
            "南北眼前道，东西江畔舟。世人重金玉，无金徒远游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题郑处士隐居 ----------
    {
        "id": "tang-qiu-4",
        "title": "题郑处士隐居",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "不信最清旷，及来愁已空。数点石泉雨，一溪霜叶风。",
            "业在有山处，道成无事中。酌尽一尊酒，病夫颜亦红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 古寺 ----------
    {
        "id": "tang-qiu-5",
        "title": "古寺",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "路傍古时寺，寥落藏金容。破塔有寒草，坏楼无晓钟。",
            "乱纸失经偈，断碑分篆踪。日暮月光吐，绕门千树松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 赠著上人 ----------
    {
        "id": "tang-qiu-6",
        "title": "赠著上人",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "掩门江上住，尽日更无为。古木坐禅处，残星鸣磬时。",
            "水浇冰滴滴，珠数落累累。自有闲行伴，青藤杖一枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 马嵬感事 ----------
    {
        "id": "tang-qiu-7",
        "title": "马嵬感事",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "冷气生深殿，狼星渡远关。九城鼙鼓内，千骑道途间。",
            "凤髻随秋草，鸾舆入暮山。恨多留不得，悲泪满龙颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 赠行如上人 ----------
    {
        "id": "tang-qiu-8",
        "title": "赠行如上人",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "不知名利苦，念佛老岷峨。衲补云千片，香烧印一窠。",
            "恋山人事少，怜客道心多。日日斋钟后，高悬滤水罗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送友人归邛州 ----------
    {
        "id": "tang-qiu-9",
        "title": "送友人归邛州",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "鹤鸣山下去，满箧荷瑶琨。放马荒田草，看碑古寺门。",
            "渐寒沙上雨，欲暝水边村。莫忘分襟处，梅花扑酒尊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 和舒上人山居即事 ----------
    {
        "id": "tang-qiu-10",
        "title": "和舒上人山居即事",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "败叶填溪路，残阳过野亭。仍弹一滴水，更读两张经。",
            "暝鸟烟中见，寒钟竹里听。不多山下去，人世尽膻腥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 发邛州寄友人 ----------
    {
        "id": "tang-qiu-11",
        "title": "发邛州寄友人",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "茫茫驱一马，自叹又何之。出郭见山处，待船逢雨时。",
            "晓鸡鸣野店，寒叶堕秋枝。寂寞前程去，闲吟欲共谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 舟行夜泊夔州 ----------
    {
        "id": "tang-qiu-12",
        "title": "舟行夜泊夔州",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "维舟镜面中，迥对白盐峰。夜静沙堤月，天寒水寺钟。",
            "故园何日到，旧友几时逢。欲作还家梦，青山一万重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 山东兰若遇静公夜归 ----------
    {
        "id": "tang-qiu-13",
        "title": "山东兰若遇静公夜归",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "松门一径微，苔滑往来稀。半夜闻钟后，浑身带雪归。",
            "问寒僧接杖，辨语犬衔衣。又是安禅去，呼童闭竹扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 边将 ----------
    {
        "id": "tang-qiu-14",
        "title": "边将",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "三千护塞儿，独自滞边陲。老向二毛见，秋从一叶知。",
            "地寒乡思苦，天暮角声悲。却被交亲笑，封侯未有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 秋寄□江舒公 ----------
    {
        "id": "tang-qiu-15",
        "title": "秋寄□江舒公",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "故人何处望，秋色满江濆。入水溪虫乱，过桥山路分。",
            "鹤归松上月，僧入竹间云。莫惜中宵磬，从教梦里闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 题杨山人隐居 ----------
    {
        "id": "tang-qiu-16",
        "title": "题杨山人隐居",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "深山道者家，门户带烟霞。绿缀沿岩草，红飘落水花。",
            "半庭栽小树，一径扫平沙。往往溪边坐，持竿到日斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 夜上隐居寺 ----------
    {
        "id": "tang-qiu-17",
        "title": "夜上隐居寺",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "寻师拟学空，空住虎溪东。千里照山月，一枝惊鹤风。",
            "年如流去水，山似转来蓬。尽日都无事，安禅石窟中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 友人见访不值因寄 ----------
    {
        "id": "tang-qiu-18",
        "title": "友人见访不值因寄",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "门户寒江近，篱墙野树深。晚风摇竹影，斜日转山阴。",
            "砌觉披秋草，床惊倒古琴。更闻邻舍说，一只鹤来寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 涂次偶作 ----------
    {
        "id": "tang-qiu-19",
        "title": "涂次偶作",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "岁月客中销，崎岖力自招。问人寻野寺，牵马渡危桥。",
            "为雨疑天晚，因山觉路遥。前程何处是，一望又迢迢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送友人江行之庐山肄业 ----------
    {
        "id": "tang-qiu-20",
        "title": "送友人江行之庐山肄业",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "蜀国初开棹，庐峰拟拾萤。兽皮裁褥暖，莲叶制衣馨。",
            "楚水秋来碧，巫山雨后青。莫教衔凤诏，三度到中庭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 山居偶作 ----------
    {
        "id": "tang-qiu-21",
        "title": "山居偶作",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "趋名逐利身，终日走风尘。还到水边宅，却为山下人。",
            "僧教开竹户，客许戴纱巾。且喜琴书在，苏生未厌贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 赠道者 ----------
    {
        "id": "tang-qiu-22",
        "title": "赠道者",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "披霞戴鹿胎，岁月不能催。饭把琪花煮，衣将藕叶裁。",
            "鹤从归日养，松是小时栽。往往樵人见，溪边洗药来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 邛州水亭夜宴送顾非熊之官 ----------
    {
        "id": "tang-qiu-23",
        "title": "邛州水亭夜宴送顾非熊之官",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "寂寞邛城夜，寒塘对庾楼。蜀关蝉已噪，秦树叶应秋。",
            "道路连天远，笙歌到晓愁。不堪分袂后，残月正如钩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 题青城山范贤观 ----------
    {
        "id": "tang-qiu-24",
        "title": "题青城山范贤观",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "数里缘山不厌难，为寻真诀问黄冠。苔铺翠点仙桥滑，",
            "松织香梢古道寒。昼傍绿畦薅嫩玉，夜开红灶撚新丹。",
            "钟声已断泉声在，风动茅花月满坛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送僧讲罢归山 ----------
    {
        "id": "tang-qiu-25",
        "title": "送僧讲罢归山",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "休将如意辩真空，吹尽天花任晓风。共看玉蟾三皎洁，",
            "独悬金锡一玲珑。岩间松桂秋烟白，江上楼台晚日红。",
            "依旧曹溪念经处，野泉声在草堂东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 题友人寓居 ----------
    {
        "id": "tang-qiu-26",
        "title": "题友人寓居",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "寓居无不在天涯，莫恨秦关道路赊。缭绕城边山是蜀，",
            "弯环门外水名巴。黄头卷席宾初散，白鼻嘶风日欲斜。",
            "何处一声金磬发，古松南畔有僧家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 伤张玖秀才 ----------
    {
        "id": "tang-qiu-27",
        "title": "伤张玖秀才",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "铜梁剑阁几区区，十上探珠不见珠。卞玉影沈沙草暗，",
            "骅骝声断陇城孤。入关词客秋怀友，出户孀妻晓望夫。",
            "吴水楚山千万里，旅魂归到故乡无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 题李少府别业 ----------
    {
        "id": "tang-qiu-28",
        "title": "题李少府别业",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "寻得仙家不姓梅，马嘶人语出尘埃。竹和庭上春烟动，",
            "花带溪头晓露开。绕岸白云终日在，傍松黄鹤有时来。",
            "何年亦作围棋伴，一到松间醉一回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 赠楚公 ----------
    {
        "id": "tang-qiu-29",
        "title": "赠楚公",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "曾闻半偈雪山中，贝叶翻时理尽通。般若恒添持戒力，",
            "落叉谁算念经功。云间晓月应难染，海上虚舟自信风。",
            "长说满庭花色好，一枝红是一枝空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 赠王山人 ----------
    {
        "id": "tang-qiu-30",
        "title": "赠王山人",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "红藤一柱脚常轻，日日缘溪入谷行。山下有家身未老，",
            "灶前无火药初成。经秋少见闲人说，带雨多闻野鹤鸣。",
            "知到蓬莱难再访，问何方法得长生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 庭竹 ----------
    {
        "id": "tang-qiu-31",
        "title": "庭竹",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "月笼翠叶秋承露，风亚繁梢暝扫烟。",
            "知道雪霜终不变，永留寒色在庭前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 题常乐寺 ----------
    {
        "id": "tang-qiu-32",
        "title": "题常乐寺",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "桂冷香闻十里间，殿台浑不似人寰。",
            "日斜回首江头望，一片晴云落后山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 题刘炼师归山 ----------
    {
        "id": "tang-qiu-33",
        "title": "题刘炼师归山",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "风急云轻鹤背寒，洞天谁道却归难。",
            "千山万水瀛洲路，何处烟飞是醮坛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 酬舒公见寄 ----------
    {
        "id": "tang-qiu-34",
        "title": "酬舒公见寄",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "无客不言云外见，为文长遣世间知。",
            "一声松径寒吟后，正是前山雪下时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 巫山下作 ----------
    {
        "id": "tang-qiu-35",
        "title": "巫山下作",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "细腰宫尽旧城摧，神女归山更不来。",
            "唯有楚江斜日里，至今犹自绕阳台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 句 ----------
    {
        "id": "tang-qiu-36",
        "title": "句",
        "author": "唐求",
        "poet_id": "tang-qiu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "恰似有龙深处卧，被人惊起黑云生。（《临池洗砚》，",
            "见《纪事》）",
            "第七百二十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]