# -*- coding: utf-8 -*-
"""
伊用昌卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 8 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 望江南词咏鼓 ----------
    {
        "id": "yi-yong-chang-1",
        "title": "望江南词咏鼓",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "江南鼓，梭肚两头栾。钉著不知侵骨髓，",
            "打来只是没心肝，空腹被人谩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 题茶陵县门 ----------
    {
        "id": "yi-yong-chang-2",
        "title": "题茶陵县门",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "茶陵一道好长街，两畔栽柳不栽槐。",
            "夜后不闻更漏鼓，只听锤芒织草鞋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 题酒楼壁 ----------
    {
        "id": "yi-yong-chang-3",
        "title": "题酒楼壁",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "此生生在此生先，何事从玄不复玄。",
            "已在淮南鸡犬后，而今便到玉皇前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题游帷观真君殿后 ----------
    {
        "id": "yi-yong-chang-4",
        "title": "题游帷观真君殿后",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "日日祥云瑞气连，侬家应作大神仙。笔头洒起风雷力，",
            "剑下驱驰造化权。更无戎夷添礼乐，永教胡虏绝烽烟。",
            "列仙功业只如此，直上三清第一天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 留题阁皂观 ----------
    {
        "id": "yi-yong-chang-5",
        "title": "留题阁皂观",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "花洞门前吠似雷，险声流断俗尘埃。雨喷山脚毒龙起，",
            "月照松梢孤鹤回。萝幕秋高添碧翠，画帘时卷到楼台。",
            "两坛诗客何年去，去后门关更不开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 湖南闯斋吟 ----------
    {
        "id": "yi-yong-chang-6",
        "title": "湖南闯斋吟",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "谁人能识白元君，上士由来尽见闻。避世早空南火宅，",
            "植田高种北山云。鸡能抱卵心常听，蝉到成形壳自分。",
            "学取大罗些子术，免教松下作孤坟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 忆江南 ----------
    {
        "id": "yi-yong-chang-7",
        "title": "忆江南",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "江南鼓，梭肚两头栾。钉著不知侵骨髓，",
            "打来只是没心肝。空腹被人谩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 句 ----------
    {
        "id": "yi-yong-chang-8",
        "title": "句",
        "author": "伊用昌",
        "poet_id": "yi-yong-chang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "暂游大庾，白鹤飞来谁共语？岭畔人家，曾见寒梅几度花。",
            "春来春去，人在落花流水处。花满前蹊，藏尽神仙人不知。",
            "（吕岩《求斋不得》，失注调名。无考）",
            "第九百零一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]