# -*- coding: utf-8 -*-
"""
窦叔向卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 10 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 寒食日恩赐火 ----------
    {
        "id": "dou-shu-xiang-1",
        "title": "寒食日恩赐火",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "恩光及小臣，华烛忽惊春。电影随中使，星辉拂路人。",
            "幸因榆柳暖，一照草茅贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 端午日恩赐百索 ----------
    {
        "id": "dou-shu-xiang-2",
        "title": "端午日恩赐百索",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "仙宫长命缕，端午降殊私。事盛蛟龙见，恩深犬马知。",
            "馀生倘可续，终冀答明时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 贞懿皇后挽歌三首（今存二首） ----------
    {
        "id": "dou-shu-xiang-3",
        "title": "贞懿皇后挽歌三首（今存二首）",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "二陵恭妇道，六寝盛皇情。礼逊生前贵，恩追殁后荣。",
            "幼王亲捧土，爱女复边茔。东望长如在，谁云向玉京。",
            "后庭攀画柳，上陌咽清笳。命妇羞蘋叶，都人插柰花。",
            "寿宫星月异，仙路往来赊。纵有迎仙术，终悲隔绛纱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 秋砧送邑大夫 ----------
    {
        "id": "dou-shu-xiang-4",
        "title": "秋砧送邑大夫",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "断续长门下，清泠逆旅秋。征夫应待信，寒女不胜愁。",
            "带月飞城上，因风散陌头。离居偏入听，况复送归舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 过担石湖 ----------
    {
        "id": "dou-shu-xiang-5",
        "title": "过担石湖",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "晓发渔门戍，晴看担石湖。日衔高浪出，天入四空无。",
            "尺寸分洲岛，纤毫指舳舻。渺然从此去，谁念客帆孤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 春日早朝应制 ----------
    {
        "id": "dou-shu-xiang-6",
        "title": "春日早朝应制",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "紫殿俯千官，春松应合欢。御炉香焰暖，驰道玉声寒。",
            "乳燕翻珠缀，祥乌集露盘。宫花一万树，不敢举头看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 酬李袁州嘉祐 ----------
    {
        "id": "dou-shu-xiang-7",
        "title": "酬李袁州嘉祐",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "少年轻会复轻离，老大关心总是悲。强说前程聊自慰，",
            "未知携手定何时。公才屈指登黄阁，匪服胡颜上赤墀。",
            "想到长安诵佳句，满朝谁不念琼枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 夏夜宿表兄话旧 ----------
    {
        "id": "dou-shu-xiang-8",
        "title": "夏夜宿表兄话旧",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "夜合花开香满庭，夜深微雨醉初醒。远书珍重何曾达，",
            "旧事凄凉不可听。去日儿童皆长大，昔年亲友半凋零。",
            "明朝又是孤舟别，愁见河桥酒幔青。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 句 ----------
    {
        "id": "dou-shu-xiang-9",
        "title": "句",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "禁兵环素帟，宫女哭寒云。",
            "（《哀挽》第三首，止存二句。见《联珠集叙》）。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 青阳馆望九子山 ----------
    {
        "id": "dou-shu-xiang-10",
        "title": "青阳馆望九子山",
        "author": "窦叔向",
        "poet_id": "dou-shu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "苍翠岧峣上碧天，九峰遥落县门前。毫芒映日千重树，",
            "涓滴垂空万丈泉。武帝南游曾驻跸，始皇东幸亦祈年。",
            "云祠绝迹终难访，唯有猿声到客边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]