# -*- coding: utf-8 -*-
"""
裴迪卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 29 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 青龙寺昙壁上人院集 ----------
    {
        "id": "pei-di-1",
        "title": "青龙寺昙壁上人院集",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "灵境信为绝，法堂出尘氛。自然成高致，向下看浮云。",
            "迤逦峰岫列，参差闾井分。林端远堞见，风末疏钟闻。",
            "吾师久禅寂，在世超人群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 青雀歌 ----------
    {
        "id": "pei-di-2",
        "title": "青雀歌",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "动息自适性，不曾妄与燕雀群。幸忝鹓鸾早相识，",
            "何时提携致青云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 游感化寺昙兴上人山院 ----------
    {
        "id": "pei-di-3",
        "title": "游感化寺昙兴上人山院",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "不远灞陵边，安居向十年。入门穿竹径，留客听山泉。",
            "鸟啭深林里，心闲落照前。浮名竟何益，从此愿栖禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 夏日过青龙寺谒操禅师 ----------
    {
        "id": "pei-di-4",
        "title": "夏日过青龙寺谒操禅师",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "安禅一室内，左右竹亭幽。有法知不染，无言谁敢酬。",
            "鸟飞争向夕，蝉噪已先秋。烦暑自兹适，清凉何所求。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 春日与王右丞过新昌里访吕逸人不遇 ----------
    {
        "id": "pei-di-5",
        "title": "春日与王右丞过新昌里访吕逸人不遇",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "恨不逢君出荷蓑，青松白屋更无他。陶令五男曾不有，",
            "蒋生三径枉相过。芙蓉曲沼春流满，薜荔成帷晚霭多。",
            "闻说桃源好迷客，不如高卧眄庭柯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 辋川集二十首·孟城坳 ----------
    {
        "id": "pei-di-6",
        "title": "辋川集二十首·孟城坳",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "结庐古城下，时登古城上。古城非畴昔，今人自来往。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 辋川集二十首·华子冈 ----------
    {
        "id": "pei-di-7",
        "title": "辋川集二十首·华子冈",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "落日松风起，还家草露晞。云光侵履迹，山翠拂人衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 辋川集二十首·文杏馆 ----------
    {
        "id": "pei-di-8",
        "title": "辋川集二十首·文杏馆",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "迢迢文杏馆，跻攀日已屡。南岭与北湖，前看复回顾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 辋川集二十首·斤竹岭 ----------
    {
        "id": "pei-di-9",
        "title": "辋川集二十首·斤竹岭",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "明流纡且直，绿筱密复深。一径通山路，行歌望旧岑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 辋川集二十首·鹿柴 ----------
    {
        "id": "pei-di-10",
        "title": "辋川集二十首·鹿柴",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "日夕见寒山，便为独往客。不知深林事，但有麏麚迹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 辋川集二十首·木兰柴 ----------
    {
        "id": "pei-di-11",
        "title": "辋川集二十首·木兰柴",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "苍苍落日时，鸟声乱溪水。缘溪路转深，幽兴何时已。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 辋川集二十首·茱萸沜 ----------
    {
        "id": "pei-di-12",
        "title": "辋川集二十首·茱萸沜",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "飘香乱椒桂，布叶间檀栾。云日虽回照，森沉犹自寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 辋川集二十首·宫槐陌 ----------
    {
        "id": "pei-di-13",
        "title": "辋川集二十首·宫槐陌",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "门前宫槐陌，是向欹湖道。秋来山雨多，落叶无人扫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 辋川集二十首·临湖亭 ----------
    {
        "id": "pei-di-14",
        "title": "辋川集二十首·临湖亭",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "当轩弥滉漾，孤月正裴回。谷口猿声发，风传入户来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 辋川集二十首·南垞 ----------
    {
        "id": "pei-di-15",
        "title": "辋川集二十首·南垞",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "孤舟信一泊，南垞湖水岸。落日下崦嵫，清波殊淼漫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 辋川集二十首·欹湖 ----------
    {
        "id": "pei-di-16",
        "title": "辋川集二十首·欹湖",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "空阔湖水广，青荧天色同。舣舟一长啸，四面来清风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 辋川集二十首·柳浪 ----------
    {
        "id": "pei-di-17",
        "title": "辋川集二十首·柳浪",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "映池同一色，逐吹散如丝。结阴既得地，何谢陶家时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 辋川集二十首·栾家濑 ----------
    {
        "id": "pei-di-18",
        "title": "辋川集二十首·栾家濑",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "濑声喧极浦，沿涉向南津。泛泛鸥凫渡，时时欲近人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 辋川集二十首·金屑泉 ----------
    {
        "id": "pei-di-19",
        "title": "辋川集二十首·金屑泉",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "萦渟澹不流，金碧如可拾。迎晨含素华，独往事朝汲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 辋川集二十首·白石滩 ----------
    {
        "id": "pei-di-20",
        "title": "辋川集二十首·白石滩",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "跂石复临水，弄波情未极。日下川上寒，浮云澹无色。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 辋川集二十首·北垞 ----------
    {
        "id": "pei-di-21",
        "title": "辋川集二十首·北垞",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "南山北垞下，结宇临欹湖。每欲采樵去，扁舟出菰蒲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 辋川集二十首·竹里馆 ----------
    {
        "id": "pei-di-22",
        "title": "辋川集二十首·竹里馆",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "来过竹里馆，日与道相亲。出入唯山鸟，幽深无世人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 辋川集二十首·辛夷坞 ----------
    {
        "id": "pei-di-23",
        "title": "辋川集二十首·辛夷坞",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "绿堤春草合，王孙自留玩。况有辛夷花，色与芙蓉乱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 辋川集二十首·漆园 ----------
    {
        "id": "pei-di-24",
        "title": "辋川集二十首·漆园",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "好闲早成性，果此谐宿诺。今日漆园游，还同庄叟乐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 辋川集二十首·椒园 ----------
    {
        "id": "pei-di-25",
        "title": "辋川集二十首·椒园",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "丹刺罥人衣，芳香留过客。幸堪调鼎用，愿君垂采摘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 辋口遇雨忆终南山因献王维 ----------
    {
        "id": "pei-di-26",
        "title": "辋口遇雨忆终南山因献王维",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "积雨晦空曲，平沙灭浮彩。辋水去悠悠，南山复何在。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 崔九欲往南山马上口号与别（一作留别王维） ----------
    {
        "id": "pei-di-27",
        "title": "崔九欲往南山马上口号与别（一作留别王维）",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "归山深浅去，须尽丘壑美。莫学武陵人，暂游桃源里。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 与卢员外象过崔处士兴宗林亭 ----------
    {
        "id": "pei-di-28",
        "title": "与卢员外象过崔处士兴宗林亭",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "乔柯门里自成阴，散发窗中曾不簪。",
            "逍遥且喜从吾事，荣宠从来非我心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 西塔寺陆羽茶泉 ----------
    {
        "id": "pei-di-29",
        "title": "西塔寺陆羽茶泉",
        "author": "裴迪",
        "poet_id": "pei-di",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "竟陵西塔寺，踪迹尚空虚。不独支公住，曾经陆羽居。",
            "草堂荒产蛤，茶井冷生鱼。一汲清泠水，高风味有馀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]