# -*- coding: utf-8 -*-
"""
薛莹卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 秋晚同友人闲步 ----------
    {
        "id": "xue-ying-1",
        "title": "秋晚同友人闲步",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "藉草与行莎，相看日未斜。断崖分鸟道，疏树见人家。",
            "望远临孤石，吟馀落片霞。野情看不足，归路思犹赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 宿仙都观阴王二君修道处 ----------
    {
        "id": "xue-ying-2",
        "title": "宿仙都观阴王二君修道处",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "十载别仙峰，峰前千古踪。阴王修道处，云雪满高松。",
            "洞口风雷异，池心星汉重。明朝下山去，片月落残钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 宿东岩寺晓起 ----------
    {
        "id": "xue-ying-3",
        "title": "宿东岩寺晓起",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "野寺寒塘晓，游人一梦分。钟残数树月，僧起半岩云。",
            "宿鸟惊初见，幽泉落不闻。吟馀凭前槛，红叶下纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 秋日湖上 ----------
    {
        "id": "xue-ying-4",
        "title": "秋日湖上",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "落日五湖游，烟波处处愁。沈浮千古事，谁与问东流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 江山闲望 ----------
    {
        "id": "xue-ying-5",
        "title": "江山闲望",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "渺渺无穷尽，风涛几日平。年光与人事，东去一声声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 访武陵道者不遇 ----------
    {
        "id": "xue-ying-6",
        "title": "访武陵道者不遇",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "花发鸟仍啼，行行路欲迷。二真无问处，虚度武陵溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 寄旧山隐侣 ----------
    {
        "id": "xue-ying-7",
        "title": "寄旧山隐侣",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "旧山诸隐沦，身在苦无身。莫锁白云路，白云多误人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 羡僧 ----------
    {
        "id": "xue-ying-8",
        "title": "羡僧",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "处世曾无著，生前事尽非。一瓶兼一衲，南北去如归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 锦 ----------
    {
        "id": "xue-ying-9",
        "title": "锦",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "轧轧弄寒机，功多力渐微。惟忧机上锦，不称舞人衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 中秋月 ----------
    {
        "id": "xue-ying-10",
        "title": "中秋月",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "三十六旬盈复缺，百年堪喜又堪伤。",
            "劝君莫惜登楼望，云放婵娟不久长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 句 ----------
    {
        "id": "xue-ying-11",
        "title": "句",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "单棹横疏雨，江滩秋泊时。",
            "花留身住越，月递梦还秦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 十日菊 ----------
    {
        "id": "xue-ying-12",
        "title": "十日菊",
        "author": "薛莹",
        "poet_id": "xue-ying",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "昨日尊前折，万人酣晓香。今朝篱下见，满地委残阳。",
            "得失片时痛，荣枯一岁伤。未将同腐草，犹更有重霜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]