# -*- coding: utf-8 -*-
"""
柳中庸卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 秋怨 ----------
    {
        "id": "liu-zhong-yong-1",
        "title": "秋怨",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "玉树起凉烟，凝情一叶前。别离伤晓镜，摇落思秋弦。",
            "汉垒关山月，胡笳塞北天。不知肠断梦，空绕几山川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 春思赠人 ----------
    {
        "id": "liu-zhong-yong-2",
        "title": "春思赠人",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "红粉当三五，青娥艳一双。绮罗回锦陌，弦管入花江。",
            "落雁惊金弹，抛杯泻玉缸。谁知褐衣客，憔悴在书窗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 幽院早春 ----------
    {
        "id": "liu-zhong-yong-3",
        "title": "幽院早春",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "草短花初拆，苔青柳半黄。隔帘春雨细，高枕晓莺长。",
            "无事含闲梦，多情识异香。欲寻苏小小，何处觅钱塘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 寒食戏赠 ----------
    {
        "id": "liu-zhong-yong-4",
        "title": "寒食戏赠",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "春暮越江边，春阴寒食天。杏花香麦粥，柳絮伴秋千。",
            "酒是芳菲节，人当桃李年。不知何处恨，已解入筝弦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 听筝 ----------
    {
        "id": "liu-zhong-yong-5",
        "title": "听筝",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "抽弦促柱听秦筝，无限秦人悲怨声。似逐春风知柳态，",
            "如随啼鸟识花情。谁家独夜愁灯影，何处空楼思月明。",
            "更入几重离别恨，江南岐路洛阳城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 河阳桥送别 ----------
    {
        "id": "liu-zhong-yong-6",
        "title": "河阳桥送别",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "黄河流出有浮桥，晋国归人此路遥。",
            "若傍阑干千里望，北风驱马雨萧萧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 征怨 ----------
    {
        "id": "liu-zhong-yong-7",
        "title": "征怨",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "岁岁金河复玉关，朝朝马策与刀环。",
            "三春白雪归青冢，万里黄河绕黑山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 凉州曲二首 ----------
    {
        "id": "liu-zhong-yong-8",
        "title": "凉州曲二首",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "关山万里远征人，一望关山泪满巾。",
            "青海戍头空有月，黄沙碛里本无春。",
            "高槛连天望武威，穷阴拂地戍金微。",
            "九城弦管声遥发，一夜关山雪满飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 江行 ----------
    {
        "id": "liu-zhong-yong-9",
        "title": "江行",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "繁阴乍隐洲，落叶初飞浦。萧萧楚客帆，暮入寒江雨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 丁评事宅秋夜宴集 ----------
    {
        "id": "liu-zhong-yong-10",
        "title": "丁评事宅秋夜宴集",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "翠幕卷回廊，银灯开后堂。风惊拥砌叶，月冷满庭霜。",
            "绮席人将醉，繁弦夜未央。共怜今促席，谁道客愁长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 夜渡江（一作姚崇诗） ----------
    {
        "id": "liu-zhong-yong-11",
        "title": "夜渡江（一作姚崇诗）",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "夜渚带浮烟，苍茫晦远天。舟轻不觉动，缆急始知牵。",
            "听笛遥寻岸，闻香暗识莲。唯看去帆影，常恐客心悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 扬子途中 ----------
    {
        "id": "liu-zhong-yong-12",
        "title": "扬子途中",
        "author": "柳中庸",
        "poet_id": "liu-zhong-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "楚塞望苍然，寒林古戍边。秋风人渡水，落日雁飞天。",
            "第二百五十八卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]