# -*- coding: utf-8 -*-
"""
李嘉祐卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 135 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·江上曲 ----------
    {
        "id": "li-jia-you-1",
        "title": "杂曲歌辞·江上曲",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "江上澹澹芙蓉花，江口蛾眉独浣纱。可怜应是阳台女，",
            "坐对鸬鹚娇不语。掩面羞看北地人，回首忽作空山雨。",
            "苍梧秋色不堪论，千载依依帝子魂。",
            "君看峰上斑斑竹，尽是湘妃泣泪痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 江上曲 ----------
    {
        "id": "li-jia-you-2",
        "title": "江上曲",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "江心澹澹芙蓉花，江口蛾眉独浣纱。可怜应是阳台女，",
            "对坐鹭鸶娇不语。掩面羞看北地人，回身忽作空山语。",
            "苍梧秋色不堪论，千载依依帝子魂。君看峰上斑斑竹，",
            "尽是湘妃泣泪痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 伤吴中 ----------
    {
        "id": "li-jia-you-3",
        "title": "伤吴中",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "馆娃宫中春已归，阖闾城头莺已飞。复见花开人又老，",
            "横塘寂寂柳依依。忆昔吴王在宫阙，馆娃满眼看花发。",
            "舞袖朝欺陌上春，歌声夜怨江边月。古来人事亦犹今，",
            "莫厌清觞与绿琴。独向西山聊一笑，白云芳草自知心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 夜闻江南人家赛神，因题即事 ----------
    {
        "id": "li-jia-you-4",
        "title": "夜闻江南人家赛神，因题即事",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "南方淫祀古风俗，楚妪解唱迎神曲。锵锵铜鼓芦叶深，",
            "寂寂琼筵江水绿。雨过风清洲渚闲，椒浆醉尽迎神还。",
            "帝女凌空下湘岸，番君隔浦向尧山。月隐回塘犹自舞，",
            "一门依倚神之祜。韩康灵药不复求，扁鹊医方曾莫睹。",
            "逐客临江空自悲，月明流水无已时。听此迎神送神曲，",
            "携觞欲吊屈原祠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 古兴 ----------
    {
        "id": "li-jia-you-5",
        "title": "古兴",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "十五小家女，双鬟人不如。蛾眉暂一见，可直千金馀。",
            "自从得向蓬莱里，出入金舆乘玉趾。梧桐树上春鸦鸣，",
            "晓伴君王犹未起。莫道君恩长不休，婕妤团扇苦悲秋。",
            "君看魏帝邺都里，惟有铜台漳水流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 杂兴 ----------
    {
        "id": "li-jia-you-6",
        "title": "杂兴",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "花间昔日黄鹂啭，妾向青楼已生怨。花落黄鹂不复来，",
            "妾老君心亦应变。君心比妾心，妾意旧来深。",
            "一别十年无尺素，归时莫赠路傍金。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送韦邕少府归钟山 ----------
    {
        "id": "li-jia-you-7",
        "title": "送韦邕少府归钟山",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "祈门官罢后，负笈向桃源。万卷长开帙，千峰不闭门。",
            "绿杨垂野渡，黄鸟傍山村。念尔能高枕，丹墀会一论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送卢员外往饶州 ----------
    {
        "id": "li-jia-you-8",
        "title": "送卢员外往饶州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "为郎复典郡，锦帐映朱轮。露冕随龙节，停桡得水人。",
            "早霜芦叶变，寒雨石榴新。莫怪谙风土，三年作逐臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送裴五归京口 ----------
    {
        "id": "li-jia-you-9",
        "title": "送裴五归京口",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "君罢江西日，家贫为一官。还归五陵去，只向远峰看。",
            "暮色催人别，秋风待雨寒。遥知到三径，唯有菊花残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送严维归越州 ----------
    {
        "id": "li-jia-you-10",
        "title": "送严维归越州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "艰难只用武，归向浙河东。松雪千山暮，林泉一水通。",
            "乡心缘绿草，野思看青枫。春日偏相忆，裁书寄剡中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送杜士瞻楚州觐省 ----------
    {
        "id": "li-jia-you-11",
        "title": "送杜士瞻楚州觐省",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "风流与才思，俱似晋时人。淮月归心促，江花入兴新。",
            "云深沧海暮，柳暗白田春。共道官犹小，怜君孝养亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送裴宣城上元所居 ----------
    {
        "id": "li-jia-you-12",
        "title": "送裴宣城上元所居",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "水流过海稀，尔去换春衣。泪向槟榔尽，身随鸿雁归。",
            "草思晴后发，花怨雨中飞。想到金陵渚，酣歌对落晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 留别毗陵诸公 ----------
    {
        "id": "li-jia-you-13",
        "title": "留别毗陵诸公",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "久作涔阳令，丹墀忽再还。凄凉辞泽国，离乱到乡山。",
            "北固滩声满，南徐草色闲。知心从此别，相忆鬓毛斑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 送独孤拾遗先辈先赴上都 ----------
    {
        "id": "li-jia-you-14",
        "title": "送独孤拾遗先辈先赴上都",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "行春日已晓，桂楫逐寒烟。转曲遥峰出，看涛极浦连。",
            "入京当献赋，封事更闻天。日日趋黄阁，应忘云海边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 常州韦郎中泛舟见饯 ----------
    {
        "id": "li-jia-you-15",
        "title": "常州韦郎中泛舟见饯",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "主人冯轼贵，送客泛舟稀。逼岸随芳草，回桡背落晖。",
            "映花双节驻，临水伯劳飞。醉与群公狎，春塘露冕归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送崔侍御入朝 ----------
    {
        "id": "li-jia-you-16",
        "title": "送崔侍御入朝",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "十年犹执宪，万里独归春。旧国逢芳草，青云见故人。",
            "潘郎今发白，陶令本家贫。相送临京口，停桡泪满巾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送岳州司马弟之任 ----------
    {
        "id": "li-jia-you-17",
        "title": "送岳州司马弟之任",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "岳阳天水外，念尔一帆过。野墅人烟迥，山城雁影多。",
            "有时巫峡色，终日洞庭波。丞相今为郡，应无劳者歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 裴侍御见赠斑竹杖 ----------
    {
        "id": "li-jia-you-18",
        "title": "裴侍御见赠斑竹杖",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "骚人夸竹杖，赠我意何深。万点湘妃泪，三年贾谊心。",
            "愿持终白首，谁道贵黄金。他日归愚谷，偏宜绿绮琴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送张观归袁州 ----------
    {
        "id": "li-jia-you-19",
        "title": "送张观归袁州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "羡尔湘东去，烟花尚可亲。绿芳深映鸟，远岫递迎人。",
            "饥狖啼初日，残莺惜暮春。遥怜谢客兴，佳句又应新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 冬夜饶州使堂饯相公五叔赴歙州 ----------
    {
        "id": "li-jia-you-20",
        "title": "冬夜饶州使堂饯相公五叔赴歙州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "丞相过邦牧，清弦送羽觞。高情同客醉，子夜为人长。",
            "斜汉初过斗，寒云正护霜。新安江自绿，明主待惟良。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 蒋山开善寺（一作崔峒诗） ----------
    {
        "id": "li-jia-you-21",
        "title": "蒋山开善寺（一作崔峒诗）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "山殿秋云里，香烟出翠微。客寻朝磬至，僧背夕阳归。",
            "下界千门在，前朝万事非。看心兼送目，葭菼自依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 晚发江宁道中呈严维 ----------
    {
        "id": "li-jia-you-22",
        "title": "晚发江宁道中呈严维",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "惆怅遥江路，萧条落日过。蝉鸣独树急，鸦向古城多。",
            "转曲随青嶂，因高见白波。潘生秋径草，严子意如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 句容县东青阳馆作 ----------
    {
        "id": "li-jia-you-23",
        "title": "句容县东青阳馆作",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "句曲千峰暮，归人向远烟。风摇近水叶，云护欲晴天。",
            "夕照留山馆，秋光落草田。征途傍斜日，一骑独翩翩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 晚春宴无锡蔡明府西亭 ----------
    {
        "id": "li-jia-you-24",
        "title": "晚春宴无锡蔡明府西亭",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "茅檐闲寂寂，无事觉人和。井近时浇圃，城低下见河。",
            "兴缘芳草积，情向远峰多。别日归吴地，停桡更一过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送王端赴朝 ----------
    {
        "id": "li-jia-you-25",
        "title": "送王端赴朝",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "君承明主意，日日上丹墀。东阁论兵后，南宫草奏期。",
            "人稀傍河处，槐暗入关时。独遣吴州客，平陵结梦思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送王正字山寺读书 ----------
    {
        "id": "li-jia-you-26",
        "title": "送王正字山寺读书",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "欲究先儒教，还过支遁居。山阶闲听法，竹径独看书。",
            "向日荷新卷，迎秋柳半疏。风流有佳句，不似带经锄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 送房明府罢长宁令湖州客舍 ----------
    {
        "id": "li-jia-you-27",
        "title": "送房明府罢长宁令湖州客舍",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "君为万里宰，恩及五湖人。未满先求退，归闲不厌贫。",
            "远峰晴更近，残柳雨还新。要自趋丹陛，明年鸡树亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 咏萤 ----------
    {
        "id": "li-jia-you-28",
        "title": "咏萤",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "映水光难定，凌虚体自轻。夜风吹不灭，秋露洗还明。",
            "向烛仍分焰，投书更有情。犹将流乱影，来此傍檐楹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 送李中丞、杨判官 ----------
    {
        "id": "li-jia-you-29",
        "title": "送李中丞、杨判官",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "射策名先著，论兵气自雄。能全季布诺，不道鲁连功。",
            "流水蒹葭外，诸山睥睨中。别君秋日晚，回首夕阳空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 至七里滩作 ----------
    {
        "id": "li-jia-you-30",
        "title": "至七里滩作",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "迁客投於越，临江泪满衣。独随流水远，转觉故人稀。",
            "万木迎秋序，千峰驻晚晖。行舟犹未已，惆怅暮潮归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 南浦渡口 ----------
    {
        "id": "li-jia-you-31",
        "title": "南浦渡口",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "寂寞横塘路，新篁覆水低。东风潮信满，时雨稻粳齐。",
            "寡妇共租税，渔人逐鼓鼙。惭无卓鲁术，解印谢黔黎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 暮秋迁客增思寄京华 ----------
    {
        "id": "li-jia-you-32",
        "title": "暮秋迁客增思寄京华",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "宋玉怨三秋，张衡复四愁。思乡雁北至，欲别水东流。",
            "倚树看黄叶，逢人诉白头。佳期不可失，落日自登楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 送苏修往上饶 ----------
    {
        "id": "li-jia-you-33",
        "title": "送苏修往上饶",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "爱尔无羁束，云山恣意过。一身随远岫，孤棹任轻波。",
            "世事关心少，渔家寄宿多。芦花泊舟处，江月奈人何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 题王十九茆堂 ----------
    {
        "id": "li-jia-you-34",
        "title": "题王十九茆堂",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "满庭多种药，入里作山家。终日能留客，凌寒亦对花。",
            "海鸥过竹屿，门柳拂江沙。知尔卑栖意，题诗美白华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 送弘志上人归湖州 ----------
    {
        "id": "li-jia-you-35",
        "title": "送弘志上人归湖州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "山林唯幽静，行住不妨禅。高月穿松径，残阳过水田。",
            "诗从宿世悟，法为本师传。能使南人敬，修持香火缘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 送陆士伦宰义兴 ----------
    {
        "id": "li-jia-you-36",
        "title": "送陆士伦宰义兴",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "阳羡兰陵近，高城带水闲。浅流通野寺，绿茗盖春山。",
            "长吏多愁罢，游人讵肯还。知君日清净，无事掩重关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 和张舍人中书宿直 ----------
    {
        "id": "li-jia-you-37",
        "title": "和张舍人中书宿直",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "汉主留才子，春城直紫微。对花阊阖静，过竹吏人稀。",
            "裁诏催添烛，将朝欲更衣。玉堂宜岁久，且莫厌彤闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 司勋王郎中宅送韦九郎中往濠州 ----------
    {
        "id": "li-jia-you-38",
        "title": "司勋王郎中宅送韦九郎中往濠州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "怜尔因同舍，看书似外家。出关逢落叶，傍水见寒花。",
            "送远添秋思，将衰恋岁华。清淮倍相忆，回首莫令赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 晚春送吉校书归楚州（吉中孚曾为道士） ----------
    {
        "id": "li-jia-you-39",
        "title": "晚春送吉校书归楚州（吉中孚曾为道士）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "诗人饶楚思，淮上及春归。旧浦菱花发，闲门柳絮飞。",
            "高名乡曲重，少事道流稀。定向渔家醉，残阳卧钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 送严二擢第东归 ----------
    {
        "id": "li-jia-you-40",
        "title": "送严二擢第东归",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "隳官就宾荐，时辈讵争先。盛业推儒行，高科独少年。",
            "迎秋见衰叶，馀照逐鸣蝉。旧里三峰下，开门古县前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 送冷朝阳及第东归江宁 ----------
    {
        "id": "li-jia-you-41",
        "title": "送冷朝阳及第东归江宁",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "高第由佳句，诸生似者稀。长安带酒别，建业候潮归。",
            "稚子欢迎棹，邻人为扫扉。含情过旧浦，鸥鸟亦依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送越州辛法曹之任 ----------
    {
        "id": "li-jia-you-42",
        "title": "送越州辛法曹之任",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "但能一官适，莫羡五侯尊。山色垂趋府，潮声自到门。",
            "缘塘剡溪路，映竹五湖村。王谢登临处，依依今尚存。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送樊兵曹潭州谒韦大夫 ----------
    {
        "id": "li-jia-you-43",
        "title": "送樊兵曹潭州谒韦大夫",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "塞鸿归欲尽，北客始辞春。零桂虽逢竹，湘川少见人。",
            "江花铺浅水，山木暗残春。修刺辕门里，多怜尔为亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送杜御史还广陵 ----------
    {
        "id": "li-jia-you-44",
        "title": "送杜御史还广陵",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "惭君从弱岁，顾我比诸昆。同事元戎久，俱承国士恩。",
            "随莺过淮水，看柳向辕门。草色金陵岸，思心那可论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 送兖州杜别驾之任 ----------
    {
        "id": "li-jia-you-45",
        "title": "送兖州杜别驾之任",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "停车邀别乘，促轸奏胡笳。若见楚山暮，因愁浙水赊。",
            "河堤经浅草，村径历繁花。更有堪悲处，梁城春日斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 题裴十六少卿东亭 ----------
    {
        "id": "li-jia-you-46",
        "title": "题裴十六少卿东亭",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "平津旧东阁，深巷见南山。卷箔岚烟润，遮窗竹影闲。",
            "倾茶兼落帽，恋客不开关。斜照窥帘外，川禽时往还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 同皇甫侍御题荐福寺一公房 ----------
    {
        "id": "li-jia-you-47",
        "title": "同皇甫侍御题荐福寺一公房",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "虚室独焚香，林空静磬长。闲窥数竿竹，老在一绳床。",
            "啜茗翻真偈，然灯继夕阳。人归远相送，步履出回廊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 送从侄端之东都 ----------
    {
        "id": "li-jia-you-48",
        "title": "送从侄端之东都",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "虏近人行少，怜君独出城。故关逢落叶，寒日逐徂征。",
            "闻笛添归思，看山惬野情。皇华今绝少，龙额也相迎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 送王谏议充东都留守判官 ----------
    {
        "id": "li-jia-you-49",
        "title": "送王谏议充东都留守判官",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "时称谢康乐，别事汉平津。衰柳寒关道，高车左掖臣。",
            "背河见北雁，到洛问东人。忆昔游金谷，相看华发新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 和都官苗员外秋夜省直对雨简诸知己 ----------
    {
        "id": "li-jia-you-50",
        "title": "和都官苗员外秋夜省直对雨简诸知己",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "多雨南宫夜，仙郎寓直时。漏长丹凤阙，秋冷白云司。",
            "萤影侵阶乱，鸿声出苑迟。萧条人吏散，小谢有新诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 送从弟归河朔 ----------
    {
        "id": "li-jia-you-51",
        "title": "送从弟归河朔",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "故乡那可到，令弟独能归。诸将矜旄节，何人重布衣。",
            "空城流水在，荒泽旧村稀。秋日平原路，虫鸣桑叶飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 送崔夷甫员外和蕃 ----------
    {
        "id": "li-jia-you-52",
        "title": "送崔夷甫员外和蕃",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "君过湟中去，寻源未是赊。经春逢白草，尽日度黄沙。",
            "双节行为伴，孤烽到似家。和戎非用武，不学李轻车。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 春日长安送从弟尉吴县 ----------
    {
        "id": "li-jia-you-53",
        "title": "春日长安送从弟尉吴县",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "春愁能浩荡，送别又如何。人向吴台远，莺飞汉苑多。",
            "见花羞白发，因尔忆沧波。好是神仙尉，前贤亦未过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 元日无衣冠入朝，寄皇甫拾遗冉、从弟补阙纾 ----------
    {
        "id": "li-jia-you-54",
        "title": "元日无衣冠入朝，寄皇甫拾遗冉、从弟补阙纾",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "伏奏随廉使，周行外冗员。白髭空受岁，丹陛不朝天。",
            "秉烛千官去，垂帘一室眠。羡君青琐里，并冕入炉烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 和韩郎中扬子津玩雪寄严维 ----------
    {
        "id": "li-jia-you-55",
        "title": "和韩郎中扬子津玩雪寄严维",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "雪深扬子岸，看柳尽成梅。山色潜知近，潮声只听来。",
            "夜禽惊晓散，春物受寒催。粉署生新兴，瑶华寄上才。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 送王牧往吉州谒王使君叔 ----------
    {
        "id": "li-jia-you-56",
        "title": "送王牧往吉州谒王使君叔",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "细草绿汀洲，王孙耐薄游。年华初冠带，文体旧弓裘。",
            "野渡花争发，春塘水乱流。使君怜小阮，应念倚门愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 广陵送林宰 ----------
    {
        "id": "li-jia-you-57",
        "title": "广陵送林宰",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "清政过前哲，香名达至尊。明通汉家籍，重识府公恩。",
            "春景生云物，风潮敛雪痕。长吟策羸马，青楚入关门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 赠卫南长官赴任 ----------
    {
        "id": "li-jia-you-58",
        "title": "赠卫南长官赴任",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "吏曹难茂宰，主意念疲人。更事文犀节，还过白马津。",
            "云间辞北阙，树里出西秦。为报陶明府，裁书莫厌贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 自常州还江阴途中作 ----------
    {
        "id": "li-jia-you-59",
        "title": "自常州还江阴途中作",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "处处空篱落，江村不忍看。无人花色惨，多雨鸟声寒。",
            "黄霸初临郡，陶潜未罢官。乘春务征伐，谁肯问凋残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 润州杨别驾宅送蒋九侍御收兵归扬州 ----------
    {
        "id": "li-jia-you-60",
        "title": "润州杨别驾宅送蒋九侍御收兵归扬州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "沴气清金虎，兵威壮铁冠。扬旌川色暗，吹角水风寒。",
            "人对辎輧醉，花垂睥睨残。羡归丞相阁，空望旧门栏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 仲夏江阴官舍寄裴明府 ----------
    {
        "id": "li-jia-you-61",
        "title": "仲夏江阴官舍寄裴明府",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "万室边江次，孤城对海安。朝霞晴作雨，湿气晚生寒。",
            "苔色侵衣桁，潮痕上井栏。题诗招茂宰，思尔欲辞官。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 送夏侯审参军游江东 ----------
    {
        "id": "li-jia-you-62",
        "title": "送夏侯审参军游江东",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "袖中多丽句，未遣世人闻。醉夜眠江月，闲时逐海云。",
            "荻花寒漫漫，鸥鸟暮群群。若到长沙苑，渔家更待君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 送袁员外宣慰劝农毕赴洪州使院 ----------
    {
        "id": "li-jia-you-63",
        "title": "送袁员外宣慰劝农毕赴洪州使院",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "圣主临前殿，殷忧遣使臣。气迎天诏喜，恩发土膏春。",
            "草色催归棹，莺声为送人。龙沙多道里，流水自相亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 送侍御史四叔归朝 ----------
    {
        "id": "li-jia-you-64",
        "title": "送侍御史四叔归朝",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "淮南频送别，临水惜残春。攀折隋宫柳，淹留秦地人。",
            "含情归上国，论旧见平津。更接天津近，馀花映绶新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 登楚州城望驿路，十馀里山村竹林相次交映 ----------
    {
        "id": "li-jia-you-65",
        "title": "登楚州城望驿路，十馀里山村竹林相次交映",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "十里山村道，千峰栎树林。霜浓竹枝亚，岁晚荻花深。",
            "草市多樵客，渔家足水禽。幽居虽可羡，无那子牟心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 奉陪韦润州游鹤林寺 ----------
    {
        "id": "li-jia-you-66",
        "title": "奉陪韦润州游鹤林寺",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "野寺江城近，双旌五马过。禅心超忍辱，梵语问多罗。",
            "松竹闲僧老，云烟晚日和。寒塘归路转，清磬隔微波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 奉酬路五郎中院长新除工部员外见简 ----------
    {
        "id": "li-jia-you-67",
        "title": "奉酬路五郎中院长新除工部员外见简",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "一门同秘省，万里作长城。问绢莲花府，扬旗细柳营。",
            "词锋偏却敌，草奏直论兵。何幸新诗赠，真输小谢名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 送韦司直西行（此公深入道门） ----------
    {
        "id": "li-jia-you-68",
        "title": "送韦司直西行（此公深入道门）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "不耻青袍故，尤宜白发新。心朝玉皇帝，貌似紫阳人。",
            "湘浦眠销日，桃源醉度春。能文兼证道，庄叟是前身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 送上官侍御赴黔中 ----------
    {
        "id": "li-jia-you-69",
        "title": "送上官侍御赴黔中",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "莫向黔中路，令人到欲迷。水声巫峡里，山色夜郎西。",
            "树隔朝云合，猿窥晓月啼。南方饶翠羽，知尔饮清溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 送元侍御还荆南幕府 ----------
    {
        "id": "li-jia-you-70",
        "title": "送元侍御还荆南幕府",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "迢递荆州路，山多水又分。霜林澹寒日，朔雁蔽南云。",
            "八座由持节，三湘亦置军。自当行直指，应不为功勋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 登湓城浦望庐山初晴，直省赍敕催赴江阴 ----------
    {
        "id": "li-jia-you-71",
        "title": "登湓城浦望庐山初晴，直省赍敕催赴江阴",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "西望香炉雪，千峰晚色新。白头悲作吏，黄纸苦催人。",
            "多负登山屐，深藏漉酒巾。伤心公府内，手板日相亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 九日 ----------
    {
        "id": "li-jia-you-72",
        "title": "九日",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "惆怅重阳日，空山野菊新。蒹葭百战地，江海十年人。",
            "叹老堪衰柳，伤秋对白蘋。孤楼闻夕磬，塘路向城闉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 九日送人 ----------
    {
        "id": "li-jia-you-73",
        "title": "九日送人",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "晴景应重阳，高台怆远乡。水澄千室倒，雾四卷山长。",
            "受节人逾老，惊寒菊半黄。席前愁此别，未别已沾裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 春日淇上作（一作汉口春） ----------
    {
        "id": "li-jia-you-74",
        "title": "春日淇上作（一作汉口春）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "淇上春风涨，鸳鸯逐浪飞。清明桑叶小，度雨杏花稀。",
            "卫女红妆薄，王孙白马肥。相将踏青去，不解惜罗衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 送从叔阳冰祇召赴都 ----------
    {
        "id": "li-jia-you-75",
        "title": "送从叔阳冰祇召赴都",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "自小从游惯，多由戏笑偏。常时矜礼数，渐老荷优怜。",
            "见主承休命，为郎贵晚年。伯喈文与篆，虚作汉家贤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 送友人入湘 ----------
    {
        "id": "li-jia-you-76",
        "title": "送友人入湘",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "闻说湘川路，年年苦雨多。猿啼巫峡雨，月照洞庭波。",
            "穷海人还去，孤城雁共过。青山不可极，来往自蹉跎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 送裴员外往江南 ----------
    {
        "id": "li-jia-you-77",
        "title": "送裴员外往江南",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "公务江南远，留驩幕下荣。枫林缘楚塞，水驿到湓城。",
            "岸草知春晚，沙禽好夜惊。风帆几度泊，处处暮潮声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 登秦岭 ----------
    {
        "id": "li-jia-you-78",
        "title": "登秦岭",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "南登秦岭头，回望始堪愁。汉阙青门远，高山蓝水流。",
            "三湘迁客去，九陌故人游。从此辞乡泪，双垂不复收。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 送张惟俭秀才入举 ----------
    {
        "id": "li-jia-you-79",
        "title": "送张惟俭秀才入举",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "清秀过终童，携书访老翁。以吾为世旧，怜尔继家风。",
            "淮岸经霜柳，关城带月鸿。春归定得意，花送到东中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 送韦侍御湖南幕府 ----------
    {
        "id": "li-jia-you-80",
        "title": "送韦侍御湖南幕府",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "执宪随征虏，逢秋出故关。雨多愁郢路，叶下识衡山。",
            "地远从军乐，兵强分野闲。皇家不易将，此去未应还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 同皇甫冉赴官，留别灵一上人 ----------
    {
        "id": "li-jia-you-81",
        "title": "同皇甫冉赴官，留别灵一上人",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "法许庐山远，诗传休上人。独归双树宿，静与百花亲。",
            "对物虽留兴，观空已悟身。能令折腰客，遥赏竹房春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 送客游荆州 ----------
    {
        "id": "li-jia-you-82",
        "title": "送客游荆州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "草色随骢马，悠悠共出秦。水传云梦晓，山接洞庭春。",
            "帆影连三峡，猿声在四邻。青门一分首，难见杜陵人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 与郑锡游春 ----------
    {
        "id": "li-jia-you-83",
        "title": "与郑锡游春",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "东门垂柳长，回首独心伤。日暖临芳草，天晴忆故乡。",
            "映花莺上下，过水蝶悠飏。借问同行客，今朝泪几行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 故燕国相公挽歌二首 ----------
    {
        "id": "li-jia-you-84",
        "title": "故燕国相公挽歌二首",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "文若为全德，留侯是重名。论公长不宰，因病得无生。",
            "大梦依禅定，高坟共化城。自应怜寂灭，人世但伤情。",
            "共美持衡日，皆言折槛时。蜀侯供庙略，汉主缺台司。",
            "车马行仍止，笳箫咽又悲。今年杜陵陌，殄瘁百花迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 故吏部郎中赠给事中韦公挽歌二首 ----------
    {
        "id": "li-jia-you-85",
        "title": "故吏部郎中赠给事中韦公挽歌二首",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "神理今何在，斯人竟若斯。颜渊徒有德，伯道且无儿。",
            "白发今非老，青云数有奇。谁言夕郎拜，翻向夜台悲。",
            "社里东城接，松阡北地开。闻笳春色惨，执绋故人哀。",
            "终日南山对，何时渭水回。仁兄与恩旧，相望泣泉台。",
            "第二百零七卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 和袁郎中破贼后经剡县山水上太尉 ----------
    {
        "id": "li-jia-you-86",
        "title": "和袁郎中破贼后经剡县山水上太尉",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "受律仙郎贵，长驱下会稽。鸣笳山月晓，摇旆野云低。",
            "翦寇人皆贺，回军马自嘶。地闲春草绿，城静夜乌啼。",
            "破竹清闽岭，看花入剡溪。元戎催献捷，莫道事攀跻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 送评事十九叔入秦 ----------
    {
        "id": "li-jia-you-87",
        "title": "送评事十九叔入秦",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "白露沾蕙草，王孙转忆归。蔡州新战罢，郢路去人稀。",
            "谒帝不辞远，怀亲空有违。孤舟看落叶，平楚逐斜晖。",
            "北阙见端冕，南台当绣衣。唯余播迁客，只伴鹧鸪飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 赠王八衢 ----------
    {
        "id": "li-jia-you-88",
        "title": "赠王八衢",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "丹地偏相逐，清江若有期。腰金才子贵，剖竹老人迟。",
            "桂楫闲迎客，茶瓯对说诗。渚田分邑里，山桂树罘罳。",
            "心静无华发，人和似古时。别君远山去，幽独更应悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 入睦州分水路忆刘长卿 ----------
    {
        "id": "li-jia-you-89",
        "title": "入睦州分水路忆刘长卿",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "北阙忤明主，南方随白云。沿洄滩草色，应接海鸥群。",
            "建德潮已尽，新安江又分。回看严子濑，朗咏谢安文。",
            "雨过暮山碧，猿吟秋日曛。吴洲不可到，刷鬓为思君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 奉和杜相公长兴新宅即事呈元相公 ----------
    {
        "id": "li-jia-you-90",
        "title": "奉和杜相公长兴新宅即事呈元相公",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "意有空门乐，居无甲第奢。经过容法侣，雕饰让侯家。",
            "隐树重檐肃，开园一径斜。据梧听好鸟，行药寄名花。",
            "梦蝶留清簟，垂貂坐绛纱。当山不掩户，映日自倾茶。",
            "雅望归安石，深知在叔牙。还成吉甫颂，赠答比瑶华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 江湖秋思 ----------
    {
        "id": "li-jia-you-91",
        "title": "江湖秋思",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "趋陪禁掖雁行随，迁向江潭鹤发垂。素浪遥疑八溪水，",
            "清枫忽似万年枝。嵩南春遍伤魂梦，壶口云深隔路歧。",
            "共望汉朝多霈泽，苍蝇早晚得先知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 送朱中舍游江东 ----------
    {
        "id": "li-jia-you-92",
        "title": "送朱中舍游江东",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "孤城郭外送王孙，越水吴洲共尔论。野寺山边斜有径，",
            "渔家竹里半开门。青枫独映摇前浦，白鹭闲飞过远村。",
            "若到西陵征战处，不堪秋草自伤魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 送窦拾遗赴朝因寄中书十七弟（窦拾遗叔向其弟窦舒也） ----------
    {
        "id": "li-jia-you-93",
        "title": "送窦拾遗赴朝因寄中书十七弟（窦拾遗叔向其弟窦舒也）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "自叹未沾黄纸诏，那堪远送赤墀人。老为侨客偏相恋，",
            "素是诗家倍益亲。妻儿共载无羁思，鸳鹭同行不负身。",
            "凭尔将书通令弟，唯论华发愧头巾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 自苏台至望亭驿人家尽空春物增思怅然有作因寄从弟纾 ----------
    {
        "id": "li-jia-you-94",
        "title": "自苏台至望亭驿人家尽空春物增思怅然有作因寄从弟纾",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "南浦菰蒋覆白蘋，东吴黎庶逐黄巾。野棠自发空临水，",
            "江燕初归不见人。远岫依依如送客，平田渺渺独伤春。",
            "那堪回首长洲苑，烽火年年报虏尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 承恩量移宰江邑，临鄱江怅然之作 ----------
    {
        "id": "li-jia-you-95",
        "title": "承恩量移宰江邑，临鄱江怅然之作",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "四年谪宦滞江城，未厌门前鄱水清。谁言宰邑化黎庶，",
            "欲别云山如弟兄。双鸥为底无心狎，白发从他绕鬓生。",
            "惆怅闲眠临极浦，夕阳秋草不胜情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 题灵台县东山村主人 ----------
    {
        "id": "li-jia-you-96",
        "title": "题灵台县东山村主人",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "处处征胡人渐稀，山村寥落暮烟微。门临莽苍经年闭，",
            "身逐嫖姚几日归。贫妻白发输残税，馀寇黄河未解围。",
            "天子如今能用武，只应岁晚息兵机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 同皇甫冉登重玄阁 ----------
    {
        "id": "li-jia-you-97",
        "title": "同皇甫冉登重玄阁",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "高阁朱栏不厌游，蒹葭白水绕长洲。孤云独鸟川光暮，",
            "万井千山海色秋。清梵林中人转静，夕阳城上角偏愁。",
            "谁怜远作秦吴别，离恨归心双泪流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 宋州东登望题武陵驿 ----------
    {
        "id": "li-jia-you-98",
        "title": "宋州东登望题武陵驿",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "梁宋人稀鸟自啼，登舻一望倍含凄。白骨半随河水去，",
            "黄云犹傍郡城低。平陂战地花空落，旧苑春田草未齐。",
            "明主频移虎符守，几时行县向黔黎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 晚登江楼有怀 ----------
    {
        "id": "li-jia-you-99",
        "title": "晚登江楼有怀",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "独坐南楼佳兴新，青山绿水共为邻。爽气遥分隔浦岫，",
            "斜光偏照渡江人。心闲鸥鸟时相近，事简鱼竿私自亲。",
            "只忆帝京不可到，秋琴一弄欲沾巾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 游徐城河忽见清淮，因寄赵八 ----------
    {
        "id": "li-jia-you-100",
        "title": "游徐城河忽见清淮，因寄赵八",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "自缘迟暮忆沧洲，翻爱南河浊水流。初过重阳惜残菊，",
            "行看旧浦识群鸥。朝霞映日同归处，暝柳摇风欲别秋。",
            "长恨相逢即分首，含情掩泪独回头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 题游仙阁白公庙 ----------
    {
        "id": "li-jia-you-101",
        "title": "题游仙阁白公庙",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "仙冠轻举竟何之，薜荔缘阶竹映祠。甲子不知风驭日，",
            "朝昏唯见雨来时。霓旌翠盖终难遇，流水青山空所思。",
            "逐客自怜双鬓改，焚香多负白云期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 送郑正则汉阳迎妇 ----------
    {
        "id": "li-jia-you-102",
        "title": "送郑正则汉阳迎妇",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "锦字相催鸟急飞，郎君暂脱老莱衣。遥想双眉待人画，",
            "行看五马送潮归。望夫山上花犹发，新妇江边莺未稀。",
            "令秩和鸣真可羡，此行谁道负春辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 送皇甫冉往安宜 ----------
    {
        "id": "li-jia-you-103",
        "title": "送皇甫冉往安宜",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "江皋尽日唯烟水，君向白田何日归。楚地蒹葭连海迥，",
            "隋朝杨柳映堤稀。津楼故市无行客，山馆荒城闭落晖。",
            "若问行人与征战，使君双泪定沾衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 晚发咸阳，寄同院遗补 ----------
    {
        "id": "li-jia-you-104",
        "title": "晚发咸阳，寄同院遗补",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "征战初休草又衰，咸阳晚眺泪堪垂。去路全无千里客，",
            "秋田不见五陵儿。秦家故事随流水，汉代高坟对石碑。",
            "回首青山独不语，羡君谈笑万年枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 早秋京口旅泊，章侍御寄书相问，因以赠之，时七夕 ----------
    {
        "id": "li-jia-you-105",
        "title": "早秋京口旅泊，章侍御寄书相问，因以赠之，时七夕",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "移家避寇逐行舟，厌见南徐江水流。吴越征徭非旧日，",
            "秣陵凋弊不宜秋。千家闭户无砧杵，七夕何人望斗牛。",
            "只有同时骢马客，偏宜尺牍问穷愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 秋晓招隐寺东峰茶宴，送内弟阎伯均归江州 ----------
    {
        "id": "li-jia-you-106",
        "title": "秋晓招隐寺东峰茶宴，送内弟阎伯均归江州",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "万畦新稻傍山村，数里深松到寺门。幸有香茶留稚子，",
            "不堪秋草送王孙。烟尘怨别唯愁隔，井邑萧条谁忍论。",
            "莫怪临歧独垂泪，魏舒偏念外家恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 送严员外（一作刘长卿诗） ----------
    {
        "id": "li-jia-you-107",
        "title": "送严员外（一作刘长卿诗）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "春风倚棹阖闾城，水国春寒阴复晴。细雨湿衣看不见，",
            "闲花落地听无声。日斜江上孤帆影，草绿湖南万里情。",
            "君去若逢相识问，青袍今已误儒生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 赴南中留别褚七少府湖上林亭（一作刘长卿诗） ----------
    {
        "id": "li-jia-you-108",
        "title": "赴南中留别褚七少府湖上林亭（一作刘长卿诗）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "种田东郭傍春陂，万事无情把钓丝。绿竹放侵行径里，",
            "青山常对卷帘时。纷纷花发门空闭，寂寂莺啼日更迟。",
            "从此别君千万里，白云流水忆佳期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 与从弟正字、从兄兵曹宴集林园 ----------
    {
        "id": "li-jia-you-109",
        "title": "与从弟正字、从兄兵曹宴集林园",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "竹窗松户有佳期，美酒香茶慰所思。辅嗣外生还解易，",
            "惠连群从总能诗。檐前花落春深后，谷里莺啼日暮时。",
            "去路归程仍待月，垂缰不控马行迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 酬皇甫十六侍御曾见寄（此公时贬舒州司马） ----------
    {
        "id": "li-jia-you-110",
        "title": "酬皇甫十六侍御曾见寄（此公时贬舒州司马）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "自顾衰容累玉除，忽承优诏赴铜鱼。江头鸟避青旄节，",
            "城里人迎露网车。长沙地近悲才子，古郡山多忆旧庐。",
            "更枉新诗思何苦，离骚愁处亦无如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 暮春宜阳郡斋愁坐，忽枉刘七侍御新诗，因以酬答 ----------
    {
        "id": "li-jia-you-111",
        "title": "暮春宜阳郡斋愁坐，忽枉刘七侍御新诗，因以酬答",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "子规夜夜啼槠叶，远道逢春半是愁。芳草伴人还易老，",
            "落花随水亦东流。山临睥睨恒多雨，地接潇湘畏及秋。",
            "唯羡君为周柱史，手持黄纸到沧洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 送舍弟 ----------
    {
        "id": "li-jia-you-112",
        "title": "送舍弟",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "诸谢偏推永嘉守，三何独许水曹郎。老兄鄙思难俦匹，",
            "令弟清词堪比量。叠嶂入云藏古寺，高秋背月转南湘。",
            "定知马上多新句，早寄袁溪当八行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 送从弟永任饶州录事参军 ----------
    {
        "id": "li-jia-you-113",
        "title": "送从弟永任饶州录事参军",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "一官万里向千溪，水宿山行鱼浦西。日晚长烟高岸近，",
            "天寒积雪远峰低。芦花渚里鸿相叫，苦竹丛边猿暗啼。",
            "闻道慈亲倚门待，到时兰叶正萋萋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 送马将军奏事毕归滑州使幕 ----------
    {
        "id": "li-jia-you-114",
        "title": "送马将军奏事毕归滑州使幕",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "吴门别后蹈沧州，帝里相逢俱白头。自叹马卿常带病，",
            "还嗟李广未封侯。棠梨宫里瞻龙衮，细柳营前著豹裘。",
            "想到滑台桑叶落，黄河东注荻花秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 闻逝者自惊 ----------
    {
        "id": "li-jia-you-115",
        "title": "闻逝者自惊",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "亦知死是人间事，年老闻之心自疑。黄卷清琴总为累，",
            "落花流水共添悲。愿将从药看真诀，又欲休官就本师。",
            "儿女眼前难喜舍，弥怜双鬓渐如丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 伤歙州陈二使君 ----------
    {
        "id": "li-jia-you-116",
        "title": "伤歙州陈二使君",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "怜君辞满卧沧洲，一旦云亡万事休。慈母断肠妻独泣，",
            "寒云惨色水空流。江村故老长怀惠，山路孤猿亦共愁。",
            "寂寞荒坟近渔浦，野松孤月即千秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 白田西忆楚州使君弟 ----------
    {
        "id": "li-jia-you-117",
        "title": "白田西忆楚州使君弟",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "山阳郭里无潮，野水自向新桥。鱼网平铺荷叶，",
            "鹭鸶闲步稻苗。秣陵归人惆怅，楚地连山寂寥。",
            "却忆士龙宾阁，清琴绿竹萧萧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 送陆澧还吴中（一作刘长卿诗） ----------
    {
        "id": "li-jia-you-118",
        "title": "送陆澧还吴中（一作刘长卿诗）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "瓜步寒潮送客，杨花暮雨沾衣。",
            "故乡南望何处，春水连天独归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 春日忆家（一作春日归山） ----------
    {
        "id": "li-jia-you-119",
        "title": "春日忆家（一作春日归山）",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "自觉劳乡梦，无人见客心。空馀庭草色，日日伴愁襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 远寺钟 ----------
    {
        "id": "li-jia-you-120",
        "title": "远寺钟",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "疏钟何处来，度竹兼拂水。渐逐微风声，依依犹在耳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 白鹭 ----------
    {
        "id": "li-jia-you-121",
        "title": "白鹭",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "江南渌水多，顾影逗轻波。落日秦云里，山高奈若何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 夜宴南陵留别 ----------
    {
        "id": "li-jia-you-122",
        "title": "夜宴南陵留别",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "雪满前庭月色闲，主人留客未能还。",
            "预愁明日相思处，匹马千山与万山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 题前溪馆 ----------
    {
        "id": "li-jia-you-123",
        "title": "题前溪馆",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "两年谪宦在江西，举目云山要自迷。",
            "今日始知风土异，浔阳南去鹧鸪啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 过乌公山寄钱起员外 ----------
    {
        "id": "li-jia-you-124",
        "title": "过乌公山寄钱起员外",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "雨过青山猿叫时，愁人泪点石榴枝。",
            "无端王事还相系，肠断蒹葭君不知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 寄王舍人竹楼 ----------
    {
        "id": "li-jia-you-125",
        "title": "寄王舍人竹楼",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "傲吏身闲笑五侯，西江取竹起高楼。",
            "南风不用蒲葵扇，纱帽闲眠对水鸥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 韦润州后亭海榴 ----------
    {
        "id": "li-jia-you-126",
        "title": "韦润州后亭海榴",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "江上年年小雪迟，年光独报海榴知。",
            "寂寂山城风日暖，谢公含笑向南枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 送崔十一弟归北京 ----------
    {
        "id": "li-jia-you-127",
        "title": "送崔十一弟归北京",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "潘郎美貌谢公诗，银印花骢年少时。",
            "楚地江皋一为别，晋山沙水独相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 访韩司空不遇 ----------
    {
        "id": "li-jia-you-128",
        "title": "访韩司空不遇",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "图画风流似长康，文词体格效陈王。",
            "蓬莱对去归常晚，丛竹闲飞满夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 题道虔上人竹房 ----------
    {
        "id": "li-jia-you-129",
        "title": "题道虔上人竹房",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "诗思禅心共竹闲，任他流水向人间。",
            "手持如意高窗里，斜日沿江千万山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 秋朝木芙蓉 ----------
    {
        "id": "li-jia-you-130",
        "title": "秋朝木芙蓉",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "水面芙蓉秋已衰，繁条到是著花时。",
            "平明露滴垂红脸，似有朝愁暮落悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 袁江口忆王司勋、王吏部二郎中、起居十七弟 ----------
    {
        "id": "li-jia-you-131",
        "title": "袁江口忆王司勋、王吏部二郎中、起居十七弟",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "京华不啻三千里，客泪如今一万双。",
            "若个最为相忆处，青枫黄竹入袁江。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 答泉州薛播使君重阳日赠酒 ----------
    {
        "id": "li-jia-you-132",
        "title": "答泉州薛播使君重阳日赠酒",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "欲强登高无力去，篱边黄菊为谁开。",
            "共知不是浔阳郡，那得王弘送酒来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 题张公洞 ----------
    {
        "id": "li-jia-you-133",
        "title": "题张公洞",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "空山杳杳鸾凤飞，神仙门户开翠微。",
            "主人白发雪霞衣，松间留我谈玄机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 句 ----------
    {
        "id": "li-jia-you-134",
        "title": "句",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "水田飞白鹭，夏木啭黄鹂。（李肇称嘉祐有此句，",
            "王右丞取以为七言，今集中无之）",
            "白马撼金珂，纷纷侍从多。身居骠骑幕，家住滹沱河。",
            "（《少年行》，《诗式》）",
            "溪北映初星。（《海录碎事》）",
            "第二百零八卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 句 ----------
    {
        "id": "li-jia-you-135",
        "title": "句",
        "author": "李嘉祐",
        "poet_id": "li-jia-you",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "巴峡猿声催客泪，铜梁山翠入江楼。（江晚望陪杨园）",
            "千峰鸟路含梅雨，五岁蝉声送麦秋。（《发青泥店至",
            "长余县西涯山口》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]