# -*- coding: utf-8 -*-
"""
王缙卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杂曲歌辞·古别离 ----------
    {
        "id": "wang-jin-1",
        "title": "杂曲歌辞·古别离",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "下阶欲离别，相对映兰丛。含辞未及吐，泪落兰丛中。",
            "高堂静秋日，罗衣飘暮风。谁能待明月，回首见床空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 古离别 ----------
    {
        "id": "wang-jin-2",
        "title": "古离别",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "下阶欲离别，相对映兰丛。含辞未及吐，泪落兰丛中。",
            "高堂静秋日，罗衣飘暮风。谁能待明月，回首见床空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 青雀歌 ----------
    {
        "id": "wang-jin-3",
        "title": "青雀歌",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "林间青雀儿，来往翩翩绕一枝。",
            "莫言不解衔环报，但问君恩今若为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 同王昌龄裴迪游青龙寺昙壁上人兄院集和兄维 ----------
    {
        "id": "wang-jin-4",
        "title": "同王昌龄裴迪游青龙寺昙壁上人兄院集和兄维",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "林中空寂舍，阶下终南山。高卧一床上，回看六合间。",
            "浮云几处灭，飞鸟何时还。问义天人接，无心世界闲。",
            "谁知大隐者，兄弟自追攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 别辋川别业 ----------
    {
        "id": "wang-jin-5",
        "title": "别辋川别业",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "山月晓仍在，林风凉不绝。殷勤如有情，惆怅令人别。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 与卢员外象过崔处士兴宗林亭 ----------
    {
        "id": "wang-jin-6",
        "title": "与卢员外象过崔处士兴宗林亭",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "身名不问十年馀，老大谁能更读书。",
            "林中独酌邻家酒，门外时闻长者车。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 九日作 ----------
    {
        "id": "wang-jin-7",
        "title": "九日作",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "莫将边地比京都，八月严霜草已枯。",
            "今日登高樽酒里，不知能有菊花无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送孙秀才（以下二首一作王维诗） ----------
    {
        "id": "wang-jin-8",
        "title": "送孙秀才（以下二首一作王维诗）",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "帝城风日好，况复建平家。玉枕双纹簟，金盘五色瓜。",
            "山中无鲁酒，松下饭胡麻。莫厌田家苦，归期远复赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 游悟真寺 ----------
    {
        "id": "wang-jin-9",
        "title": "游悟真寺",
        "author": "王缙",
        "poet_id": "wang-jin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "闻道黄金地，仍开白玉田。掷山移巨石，咒岭出飞泉。",
            "猛虎同三径，愁猿学四禅。买香然绿桂，乞火蹈红莲。",
            "草色摇霞上，松声泛月边。山河穷百二，世界接三千。",
            "梵宇聊凭视，王城遂渺然。灞陵才出树，渭水欲连天。",
            "远县分朱郭，孤村起白烟。望云思圣主，披雾忆群贤。",
            "薄宦惭尸素，终身拟尚玄。谁知草庵客，曾和柏梁篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]