# -*- coding: utf-8 -*-
"""
张文琮卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 8 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·昭君词 ----------
    {
        "id": "zhang-wen-cong-1",
        "title": "相和歌辞·昭君词",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "戒途飞万里，回首望三秦。忽见天山雪，还疑上苑春。",
            "玉痕垂泪粉，罗袂拂胡尘。为得胡中曲，还悲远嫁人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·蜀道难 ----------
    {
        "id": "zhang-wen-cong-2",
        "title": "相和歌辞·蜀道难",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "梁山镇地险，积石阻云端。深谷下寥廓，层岩上郁盘。",
            "飞梁架绝岭，栈道接危峦。揽辔独长息，方知斯路难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 同潘屯田冬日早朝 ----------
    {
        "id": "zhang-wen-cong-3",
        "title": "同潘屯田冬日早朝",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "假寐怀古人，夙兴瞻晓月。通晨禁门启，冠盖趋朝谒。",
            "霜霭清九衢，霞光照双阙。纷纶文物纪，焕烂声明发。",
            "腰剑动陆离，鸣玉和清越。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 蜀道难 ----------
    {
        "id": "zhang-wen-cong-4",
        "title": "蜀道难",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "梁山镇地险，积石阻云端。深谷下寥廓，层岩上郁盘。",
            "飞梁架绝岭，栈道接危峦。揽辔独长息，方知斯路难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 昭君怨 ----------
    {
        "id": "zhang-wen-cong-5",
        "title": "昭君怨",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "戒途飞万里，回首望三秦。忽见天山雪，还疑上苑春。",
            "玉痕垂粉泪，罗袂拂胡尘。为得胡中曲，还悲远嫁人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 咏水 ----------
    {
        "id": "zhang-wen-cong-6",
        "title": "咏水",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "标名资上善，流派表灵长。地图罗四渎，天文载五潢。",
            "方流涵玉润，圆折动珠光。独有蒙园吏，栖偃玩濠梁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 赋桥 ----------
    {
        "id": "zhang-wen-cong-7",
        "title": "赋桥",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "造舟浮谓日，鞭石表秦初。星文遥写汉，虹势尚凌虚。",
            "已授文成履，空题武骑书。别有临濠上，栖偃独观鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 和杨舍人咏中书省花树 ----------
    {
        "id": "zhang-wen-cong-8",
        "title": "和杨舍人咏中书省花树",
        "author": "张文琮",
        "poet_id": "zhang-wen-cong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "花萼映芳丛，参差间早红。因风时落砌，杂雨乍浮空。",
            "影照凤池水，香飘鸡树风。岂不爱攀折，希君怀袖中。",
            "第四十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]