# -*- coding: utf-8 -*-
"""
翁绶卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 15 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 横吹曲辞·陇头吟 ----------
    {
        "id": "weng-shou-1",
        "title": "横吹曲辞·陇头吟",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "陇水潺湲陇树黄，征人陇上尽思乡。马嘶斜日朔风急，",
            "雁过寒云边思长。残月出林明剑戟，平沙隔水见牛羊。",
            "横行俱足封侯者，谁斩楼兰献未央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 横吹曲辞·折杨柳 ----------
    {
        "id": "weng-shou-2",
        "title": "横吹曲辞·折杨柳",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "紫陌金堤映绮罗，游人处处动离歌。阴移古戍迷荒草，",
            "花带残阳落远波。台上少年吹白雪，楼中思妇敛青蛾。",
            "殷勤攀折赠行客，此去关山雨雪多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 横吹曲辞·关山月 ----------
    {
        "id": "weng-shou-3",
        "title": "横吹曲辞·关山月",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "裴回汉月满边州，照尽天涯到陇头。影转银河寰海静，",
            "光分玉塞古今愁。笳吹远戍孤烽灭，雁下平沙万里秋。",
            "况是故园摇落夜，那堪少妇独登楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 横吹曲辞·雨雪曲 ----------
    {
        "id": "weng-shou-4",
        "title": "横吹曲辞·雨雪曲",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "边声四合殷河流，雨雪飞来遍陇头。铁岭探人迷鸟道，",
            "阴山飞将湿貂裘。斜飘旌旆过戎帐，半杂风沙入戍楼。",
            "一自塞垣无李蔡，何人为解北门忧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 相和歌辞·婕妤怨 ----------
    {
        "id": "weng-shou-5",
        "title": "相和歌辞·婕妤怨",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "谗谤潜来起百忧，朝承恩宠暮仇雠。火烧白玉非因玷，",
            "霜翦红兰不待秋。花落昭阳谁共辇，月明长信独登楼。",
            "繁华事逐东流水，团扇悲歌万古愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 杂曲歌辞·行路难 ----------
    {
        "id": "weng-shou-6",
        "title": "杂曲歌辞·行路难",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "行路艰难不复歌，故人荣达我蹉跎。双轮晚上铜梁雪，",
            "一叶春浮瘴海波。自古要津皆若此，方今失路欲如何。",
            "君看西汉翟丞相，凤沼朝辞暮雀罗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 婕妤怨 ----------
    {
        "id": "weng-shou-7",
        "title": "婕妤怨",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "谗谤潜来起百忧，朝承恩宠暮仇雠。火烧白玉非因玷，",
            "霜翦红兰不待秋。花落昭阳谁共辇，月明长信独登楼。",
            "繁华事逐东流水，团扇悲歌万古愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 陇头吟 ----------
    {
        "id": "weng-shou-8",
        "title": "陇头吟",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "陇水潺湲陇树黄，征人陇上尽思乡。马嘶斜日朔风急，",
            "雁过寒云边思长。残月出林明剑戟，平沙隔水见牛羊。",
            "横行俱是封侯者，谁斩楼兰献未央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 关山月 ----------
    {
        "id": "weng-shou-9",
        "title": "关山月",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "裴回汉月满边州，照尽天涯到陇头。影转银河寰海静，",
            "光分玉塞古今愁。笳吹远戍孤烽灭，雁下平沙万里秋。",
            "况是故园摇落夜，那堪少妇独登楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 雨雪曲 ----------
    {
        "id": "weng-shou-10",
        "title": "雨雪曲",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "边声四合殷河流，雨雪飞来遍陇头。铁岭探人迷鸟道，",
            "阴山飞将湿貂裘。斜飘旌旆过戎帐，半杂风沙入戍楼。",
            "一自塞垣无李蔡，何人为解北门忧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 行路难 ----------
    {
        "id": "weng-shou-11",
        "title": "行路难",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "行路艰难不复歌，故人荣达我蹉跎。双轮晚上铜台雪，",
            "一叶春浮瘴海波。自古要津皆若此，方今失路欲如何。",
            "君看西汉翟丞相，凤沼朝辞暮雀罗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 折杨柳 ----------
    {
        "id": "weng-shou-12",
        "title": "折杨柳",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "紫陌金堤映绮罗，游人处处动离歌。阴移古戍迷芳草，",
            "花带残阳落远波。台上少年吹白雪，楼中思妇敛青蛾。",
            "殷勤攀折赠行客，此去关山雨雪多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 咏酒 ----------
    {
        "id": "weng-shou-13",
        "title": "咏酒",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "逃暑迎春复送秋，无非绿蚁满杯浮。百年莫惜千回醉，",
            "一盏能消万古愁。几为芳菲眠细草，曾因雨雪上高楼。",
            "平生名利关身者，不识狂歌到白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 白马 ----------
    {
        "id": "weng-shou-14",
        "title": "白马",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "渥洼龙种雪霜同，毛骨天生胆气雄。金埒乍调光照地，",
            "玉关初别远嘶风。花明锦襜垂杨下，露湿朱缨细草中。",
            "一夜羽书催转战，紫髯骑出佩騂弓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 句 ----------
    {
        "id": "weng-shou-15",
        "title": "句",
        "author": "翁绶",
        "poet_id": "weng-shou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "海国欧乡浙水东，暂烦良守此凭熊。（见《事文类聚》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]