# -*- coding: utf-8 -*-
"""
李昌符卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 35 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 书边事（一作边行书事，一作塞上行） ----------
    {
        "id": "li-chang-fu-1",
        "title": "书边事（一作边行书事，一作塞上行）",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "朔野烟尘起，天军又举戈。阴风向晚急，杀气入秋多。",
            "树尽禽栖草，冰坚路在河。汾阳无继者，羌虏肯先和。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 远归别墅（一作秋晚归故居） ----------
    {
        "id": "li-chang-fu-2",
        "title": "远归别墅（一作秋晚归故居）",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "马省曾行处，连嘶渡晚河。忽惊乡树出，渐识路人多。",
            "细径穿禾黍，颓垣压薜萝。乍归犹似客，邻叟亦相过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 题友人屋 ----------
    {
        "id": "li-chang-fu-3",
        "title": "题友人屋",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "松底诗人宅，闲门远岫孤。数家分小径，一水截平芜。",
            "竹节偶相对，鸟名多自呼。爱君真静者，欲去又踟蹰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠同游 ----------
    {
        "id": "li-chang-fu-4",
        "title": "赠同游",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "此来风雨后，已觉减年华。若待皆无事，应难更有花。",
            "管弦临夜急，榆柳向江斜。且莫看归路，同须醉酒家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送人出塞 ----------
    {
        "id": "li-chang-fu-5",
        "title": "送人出塞",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "北风吹雨雪，举目已凄凄。战鬼秋频哭，征鸿夜不栖。",
            "沙平关路直，碛广郡楼低。此去非东鲁，人多事鼓鼙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 寻僧元皎因赠 ----------
    {
        "id": "li-chang-fu-6",
        "title": "寻僧元皎因赠",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "此生迷有著，因病得寻师。话尽山中事，归当月上时。",
            "高松连寺影，亚竹入窗枝。闲忆草堂路，相逢非素期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 下第后蒙侍郎示意指于新先辈宣恩感谢 ----------
    {
        "id": "li-chang-fu-7",
        "title": "下第后蒙侍郎示意指于新先辈宣恩感谢",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "才薄命如此，自嗟兼自疑。遭逢好文日，黜落至公时。",
            "倚玉甘无路，穿杨却未期。更惭君侍坐，问许可言诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 夜泊渭津 ----------
    {
        "id": "li-chang-fu-8",
        "title": "夜泊渭津",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "漂漂东去客，一宿渭城边。远处星垂岸，中流月满船。",
            "凉归夜深簟，秋入雨馀天。渐觉家山小，残程尚几年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 晚夏逢友人 ----------
    {
        "id": "li-chang-fu-9",
        "title": "晚夏逢友人",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "一别同袍友，相思已十年。长安多在客，久病忽闻蝉。",
            "骤雨才沾地，阴云不遍天。微凉堪话旧，移榻晚风前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 秋中夜坐 ----------
    {
        "id": "li-chang-fu-10",
        "title": "秋中夜坐",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "空庭吟坐久，爽气入荷衣。病叶先秋落，惊禽背月飞。",
            "瘴云晴未散，戍客老将依。为应金门策，多应说战机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 旅游伤春 ----------
    {
        "id": "li-chang-fu-11",
        "title": "旅游伤春",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "酒醒乡关远，迢迢听漏终。曙分林影外，春尽雨声中。",
            "鸟思江村路，花残野岸风。十年成底事，羸马倦西东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 得远书 ----------
    {
        "id": "li-chang-fu-12",
        "title": "得远书",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "故人居谪宦，今日一书来。良久惊兼喜，殷勤卷更开。",
            "瘴云沉去雁，江雨促新梅。满纸殊乡泪，非冤不可哀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 赠同席 ----------
    {
        "id": "li-chang-fu-13",
        "title": "赠同席",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "四座列吾友，满园花照衣。一生知几度，后到拟先归。",
            "急管侵诸乐，严城送落晖。当欢莫离席，离席却欢稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 赠供奉僧玄观 ----------
    {
        "id": "li-chang-fu-14",
        "title": "赠供奉僧玄观",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "自得曹溪法，诸经更不看。已降禅侣久，兼作帝师难。",
            "夜木侵檐黑，秋灯照雨寒。如何嫌有著，一念在林峦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送琴客 ----------
    {
        "id": "li-chang-fu-15",
        "title": "送琴客",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "楚客抱离思，蜀琴留恨声。坐来新月上，听久觉秋生。",
            "夜静骚人语，天高别鹤鸣。因君兴一叹，竟夕意难平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 别谪者 ----------
    {
        "id": "li-chang-fu-16",
        "title": "别谪者",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "此地闻犹恶，人言是所之。一家书绝久，孤驿梦成迟。",
            "八月三湘道，闻猿冒雨时。不须祠楚相，臣节转堪疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 行思 ----------
    {
        "id": "li-chang-fu-17",
        "title": "行思",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "千里岂云去，欲归如路穷。人间无暇日，马上又秋风。",
            "破月衔高岳，流星拂晓空。此时皆在梦，行色独匆匆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 感怀题从舅宅 ----------
    {
        "id": "li-chang-fu-18",
        "title": "感怀题从舅宅",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "郗家庭树下，几度醉春风。今日花还发，当时事不同。",
            "流言应未息，直道竟难通。徒遣相思者，悲歌向暮空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 与友人会 ----------
    {
        "id": "li-chang-fu-19",
        "title": "与友人会",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "蝉吟槐蕊落，的的是愁端。病觉离家远，贫知处事难。",
            "真交无所隐，深语有馀欢。未必闻歌吹，羁心得暂宽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 赠春游侣 ----------
    {
        "id": "li-chang-fu-20",
        "title": "赠春游侣",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "密林多暗香，轻吹送馀芳。啼鸟愁春尽，游人喜日长。",
            "浮云横暮色，新雨洗韶光。欲散垂□恨，应须入醉乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送人游边 ----------
    {
        "id": "li-chang-fu-21",
        "title": "送人游边",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "愁指萧关外，风沙入远程。马行初有迹，雨落竟无声。",
            "地理全归汉，天威不在兵。西京逢故老，暗喜复时平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 寄栖白上人 ----------
    {
        "id": "li-chang-fu-22",
        "title": "寄栖白上人",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "剪发兼成隐，将心更属文。无憀对豪客，不拜谒吾君。",
            "画壁惟泉石，经窗半典坟。归林幽鸟狎，乞食病僧分。",
            "默坐终清夜，凝思念碧云。相逢应未卜，余正走嚣氛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送人入新罗使 ----------
    {
        "id": "li-chang-fu-23",
        "title": "送人入新罗使",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "鸡林君欲去，立册付星轺。越海程难计，征帆影自飘。",
            "望乡当落日，怀阙羡回潮。宿雾蒙青嶂，惊波荡碧霄。",
            "春生阳气早，天接祖州遥。愁约三年外，相迎上石桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 咏铁马鞭 ----------
    {
        "id": "li-chang-fu-24",
        "title": "咏铁马鞭",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "汉将临流得铁鞭，鄂侯名字旧雕镌。须为圣代无双物，",
            "肯逐将军卧九泉。汗马不侵诛虏血，神功今见补亡篇。",
            "时来终荐明君用，莫叹沉埋二百年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送友人 ----------
    {
        "id": "li-chang-fu-25",
        "title": "送友人",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "举世谁能与事期，解携多是正欢时。人间不遣有名利，",
            "陌上始应无别离。晚渡待船愁立久，乱山投店独行迟。",
            "我今漂泊还如此，江剑相逢亦未知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 南潭 ----------
    {
        "id": "li-chang-fu-26",
        "title": "南潭",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "匝岸青芜掩古苔，面山亭树枕潭开。有时弦管收筵促，",
            "无数凫鹥逆浪来。路入龙祠群木老，风惊渔艇一声回。",
            "人传郭恽多游此，谁见当初泛玉杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 秋夜作 ----------
    {
        "id": "li-chang-fu-27",
        "title": "秋夜作",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "数亩池塘近杜陵，秋天寂寞夜云凝。芙蓉叶上三更雨，",
            "蟋蟀声中一点灯。迹避险巇翻失路，心归闲淡不因僧。",
            "既逢上国陈诗日，长守林泉亦未能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 客恨 ----------
    {
        "id": "li-chang-fu-28",
        "title": "客恨",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "古原南北旧萧疏，高木风多小雪馀。半夜病吟人寝后，",
            "百年闲事酒醒初。频招兄弟同佳节，已有兵戈隔远书。",
            "肥马王孙定相笑，不知岐路厌樵渔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 三月尽日 ----------
    {
        "id": "li-chang-fu-29",
        "title": "三月尽日",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "江头从此管弦稀，散尽游人独未归。",
            "落日已将春色去，残花应逐夜风飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 绿珠咏 ----------
    {
        "id": "li-chang-fu-30",
        "title": "绿珠咏",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "洛阳佳丽与芳华，金谷园中见百花。",
            "谁遣当年坠楼死，无人巧笑破孙家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 赠别 ----------
    {
        "id": "li-chang-fu-31",
        "title": "赠别",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "又将书剑出孤舟，尽日停桡结远愁。",
            "莫道江波话离别，江波一去不回流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 闷书 ----------
    {
        "id": "li-chang-fu-32",
        "title": "闷书",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "病来难处早秋天，一径无人树有蝉。",
            "归计未成书半卷，中宵多梦昼多眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 伤春 ----------
    {
        "id": "li-chang-fu-33",
        "title": "伤春",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "即是春风尽，仍沾夜雨归。明朝更来此，兼恐落花稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 登临洮望萧关 ----------
    {
        "id": "li-chang-fu-34",
        "title": "登临洮望萧关",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "渐觉风沙暗，萧关欲到时。儿童能探火，妇女解缝旗。",
            "川少衔鱼鹭，林多带箭麋。暂来戎马地，不敢苦吟诗。",
            "第六百零二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 婢仆诗 ----------
    {
        "id": "li-chang-fu-35",
        "title": "婢仆诗",
        "author": "李昌符",
        "poet_id": "li-chang-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "春娘爱上酒家楼，不怕归迟总不忧。",
            "推道那家娘子卧，且留教住待梳头。",
            "不论秋菊与春花，个个能噇空腹茶。",
            "无事莫教频入库，一名闲物要些些。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]