# -*- coding: utf-8 -*-
"""
孟贯卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 31 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 宿山寺 ----------
    {
        "id": "meng-guan-1",
        "title": "宿山寺",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "溪山尽日行，方听远钟声。入院逢僧定，登楼见月生。",
            "露垂群木润，泉落一岩清。此景关吾事，通宵寐不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠栖隐洞谭先生 ----------
    {
        "id": "meng-guan-2",
        "title": "赠栖隐洞谭先生",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "先生双鬓华，深谷卧云霞。不伐有巢树，多移无主花。",
            "石泉春酿酒，松火夜煎茶。因问山中事，如君有几家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 归雁 ----------
    {
        "id": "meng-guan-3",
        "title": "归雁",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "春至衡阳雁，思归塞路长。汀洲齐奋翼，霄汉共成行。",
            "雪尽翻风暖，寒收度月凉。直应到秋日，依旧返潇湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春江送人 ----------
    {
        "id": "meng-guan-4",
        "title": "春江送人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "春江多去情，相去枕长汀。数雁别湓浦，片帆离洞庭。",
            "雨馀沙草绿，云散岸峰青。谁共观明月，渔歌夜好听。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 过秦岭 ----------
    {
        "id": "meng-guan-5",
        "title": "过秦岭",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "古今传此岭，高下势峥嵘。安得青山路，化为平地行。",
            "苍苔留虎迹，碧树障溪声。欲过一回首，踟蹰无限情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送吴梦誾归闽 ----------
    {
        "id": "meng-guan-6",
        "title": "送吴梦誾归闽",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "瓯闽在天末，此去整行衣。久客逢春尽，思家冒暑归。",
            "海云添晚景，山瘴灭晴晖。相忆吟偏苦，不堪书信稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 山中夏日 ----------
    {
        "id": "meng-guan-7",
        "title": "山中夏日",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "深山宜避暑，门户映岚光。夏木荫溪路，昼云埋石床。",
            "心源澄道静，衣葛蘸泉凉。算得红尘里，谁知此兴长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 宿故人江居 ----------
    {
        "id": "meng-guan-8",
        "title": "宿故人江居",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "渡口树冥冥，南山渐隐青。渔舟归旧浦，鸥鸟宿前汀。",
            "静榻悬灯坐，闲门对浪扃。相思频到此，几番醉还醒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 寄伍乔 ----------
    {
        "id": "meng-guan-9",
        "title": "寄伍乔",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "蹉跎春又晚，天末信来迟。长忆分携日，正当摇落时。",
            "独游饶旅恨，多事失归期。君看前溪树，山禽巢几枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 山中访人不遇 ----------
    {
        "id": "meng-guan-10",
        "title": "山中访人不遇",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "负琴兼杖藜，特地过岩西。已见竹轩闭，又闻山鸟啼。",
            "长松寒倚谷，细草暗连溪。久立无人事，烟霞归路迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 赠隐者 ----------
    {
        "id": "meng-guan-11",
        "title": "赠隐者",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "世路争名利，深山独结茅。安情自得所，非道岂相交。",
            "百尺松当户，千年鹤在巢。知君于此景，未欲等闲抛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 寄暹上人 ----------
    {
        "id": "meng-guan-12",
        "title": "寄暹上人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "闻罢城中讲，来安顶上禅。夜灯明石室，清磬出岩泉。",
            "欲访惭多事，相思恨隔年。终期息尘虑，接话虎溪边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 江边闲步 ----------
    {
        "id": "meng-guan-13",
        "title": "江边闲步",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "闲来南渡口，迤逦看江枫。一路波涛畔，数家芦苇中。",
            "远汀排晚树，深浦漾寒鸿。吟罢慵回首，此情谁与同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 过王逸人园林 ----------
    {
        "id": "meng-guan-14",
        "title": "过王逸人园林",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "谷口何时住，烟霞一径深。水声离远洞，山色出疏林。",
            "雪彩从沾鬓，年光不计心。自言人少到，犹喜我来寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 寄李处士 ----------
    {
        "id": "meng-guan-15",
        "title": "寄李处士",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "僧话磻溪叟，平生重赤松。夜堂悲蟋蟀，秋水老芙蓉。",
            "吟坐倦垂钓，闲行多倚筇。闻名来已久，未得一相逢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 夏日寄史处士 ----------
    {
        "id": "meng-guan-16",
        "title": "夏日寄史处士",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "掩关苔满地，终日坐腾腾。暑气冷衣葛，暮云催烛灯。",
            "寂寥知得趣，疏懒似无能。还忆旧游否，何年别杜陵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 夏日登瀑顶寺，因寄诸知己 ----------
    {
        "id": "meng-guan-17",
        "title": "夏日登瀑顶寺，因寄诸知己",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "曾于尘里望，此景在烟霄。岩静水声近，山深暑气遥。",
            "杖藜青石路，煮茗白云樵。寄语为郎者，谁能访寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 怀果上人 ----------
    {
        "id": "meng-guan-18",
        "title": "怀果上人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "拥锡南游去，名香几处焚。别来无远信，多恐在深云。",
            "好月曾同步，幽香省共闻。相思不相见，林下叶纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 寄故园兄弟 ----------
    {
        "id": "meng-guan-19",
        "title": "寄故园兄弟",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "久与乡关阻，风尘损旧衣。水思和月泛，山忆共僧归。",
            "林想添邻舍，溪应改钓矶。弟兄无苦事，不用别庭闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 早秋吟眺 ----------
    {
        "id": "meng-guan-20",
        "title": "早秋吟眺",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "新秋初雨后，独立对遥山。去鸟望中没，好云吟里还。",
            "长年惭道薄，明代取身闲。从有西征思，园林懒闭关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送江为归岭南 ----------
    {
        "id": "meng-guan-21",
        "title": "送江为归岭南",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "旧山临海色，归路到天涯。此别各多事，重逢是几时。",
            "江行晴望远，岭宿夜吟迟。珍重南方客，清风失所思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 山中答友人 ----------
    {
        "id": "meng-guan-22",
        "title": "山中答友人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "偶爱春山住，因循值暑时。风尘非所愿，泉石本相宜。",
            "坐久松阴转，吟馀蝉韵移。自惭疏野甚，多失故人期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 山斋早秋雨中 ----------
    {
        "id": "meng-guan-23",
        "title": "山斋早秋雨中",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "深居少往还，卷箔早秋间。雨洒吟蝉树，云藏啸狖山。",
            "炎蒸如便退，衣葛亦堪闲。静坐得无事，酒卮聊畅颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 送人游南越 ----------
    {
        "id": "meng-guan-24",
        "title": "送人游南越",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "孑然南越去，替尔畏前程。见说路岐嶮，不通车马行。",
            "瘴烟迷海色，岭树带猿声。独向山家宿，多应乡思生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 酬东溪史处士 ----------
    {
        "id": "meng-guan-25",
        "title": "酬东溪史处士",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "咫尺东溪路，年来偶访迟。泉声迷夜雨，花片落空枝。",
            "石径逢僧出，山床见鹤移。贫斋有琴酒，曾许月圆期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 秋江送客 ----------
    {
        "id": "meng-guan-26",
        "title": "秋江送客",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "秋风楚江上，送子话游遨。远水宿何处，孤舟春夜涛。",
            "浦云沈雁影，山月照猿嗥。莫为饥寒苦，便成名利劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 寄山中高逸人 ----------
    {
        "id": "meng-guan-27",
        "title": "寄山中高逸人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "烟霞多放旷，吟啸是寻常。猿共摘山果，僧邻住石房。",
            "蹑云双屐冷，采药一身香。我忆相逢夜，松潭月色凉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 怀友人 ----------
    {
        "id": "meng-guan-28",
        "title": "怀友人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "浮世况多事，飘流每叹君。路岐何处去，消息几时闻。",
            "吟里落秋叶，望中生暮云。孤怀谁慰我，夕鸟自成群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 送人归别业 ----------
    {
        "id": "meng-guan-29",
        "title": "送人归别业",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "别业五湖上，春残去路赊。还寻旧山水，重到故人家。",
            "门径掩芳草，园林落异花。君知钓矶在，犹喜有生涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 冬日登江楼 ----------
    {
        "id": "meng-guan-30",
        "title": "冬日登江楼",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "高楼临古岸，野步晚来登。江水因寒落，山云为雪凝。",
            "远村虽入望，危槛不堪凭。亲老未归去，乡愁徒自兴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 寄张山人 ----------
    {
        "id": "meng-guan-31",
        "title": "寄张山人",
        "author": "孟贯",
        "poet_id": "meng-guan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "草堂南涧边，有客啸云烟。扫叶林风后，拾薪山雨前。",
            "野桥通竹径，流水入芝田。琴月相亲夜，更深恋不眠。",
            "第七百五十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]