# -*- coding: utf-8 -*-
"""
栖蟾卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 短歌行 ----------
    {
        "id": "qi-chan-1",
        "title": "短歌行",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "蟾光堪自笑，浮世懒思量。身得几时活，眼开终日忙。",
            "千门无寿药，一镜有愁霜。早向尘埃外，光阴任短长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 除夜（一作尚颜诗） ----------
    {
        "id": "qi-chan-2",
        "title": "除夜（一作尚颜诗）",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "九冬三十夜，寒与暖分开。坐到四更后，身添一岁来。",
            "鱼灯延腊火，兽炭化春灰。青帝今应老，迎新见几回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 宿巴江 ----------
    {
        "id": "qi-chan-3",
        "title": "宿巴江",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "江声五十里，泻碧急于弦。不觉日又夜，争教人少年。",
            "一汀巫峡月，两岸子规天。山影似相伴，浓遮到晓船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 游边 ----------
    {
        "id": "qi-chan-4",
        "title": "游边",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "边云四顾浓，饥马嗅枯丛。万里八九月，一身西北风。",
            "偷营天正黑，战地雪多红。昨夜东归梦，桃花暖色中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 居南岳怀沈彬 ----------
    {
        "id": "qi-chan-5",
        "title": "居南岳怀沈彬",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "石房开竹扉，茗外独支颐。万木还无叶，百年能几时。",
            "隔云闻狖过，截雨见虹垂。因忆岳南客，晏眠吟好诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 南中怀友生 ----------
    {
        "id": "qi-chan-6",
        "title": "南中怀友生",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "荔枝江上立，望北几思量。隔海无书札，前年在汉阳。",
            "瘴村人起早，铜柱象揩光。居此成何事，寻君过碧湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 赠南岳玄泰布衲 ----------
    {
        "id": "qi-chan-7",
        "title": "赠南岳玄泰布衲",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "曹溪入室人，终老甚难群。四十馀年内，青山与白云。",
            "松和巢鹤看，果共野猿分。海外僧来说，名高自小闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 寄问政山聂威仪 ----------
    {
        "id": "qi-chan-8",
        "title": "寄问政山聂威仪",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "先生卧碧岑，诸祖是知音。得道无一法，孤云同寸心。",
            "岚光薰鹤诏，茶味敌人参。苦向壶中去，他年许我寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送迁客 ----------
    {
        "id": "qi-chan-9",
        "title": "送迁客",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "谏频甘得罪，一骑入南深。若顺吾皇意，即无臣子心。",
            "织花蛮市布，捣月象州砧。蒙雪知何日，凭楼望北吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 读齐己上人集（一作尚颜诗） ----------
    {
        "id": "qi-chan-10",
        "title": "读齐己上人集（一作尚颜诗）",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "诗为儒者禅，此格的惟仙。古雅如周颂，清和甚舜弦。",
            "冰生听瀑句，香发早梅篇。想得吟成夜，文星照楚天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 牧童 ----------
    {
        "id": "qi-chan-11",
        "title": "牧童",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "牛得自由骑，春风细雨飞。青山青草里，一笛一蓑衣。",
            "日出唱歌去，月明抚掌归。何人得似尔，无是亦无非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 再宿京口禅院 ----------
    {
        "id": "qi-chan-12",
        "title": "再宿京口禅院",
        "author": "栖蟾",
        "poet_id": "qi-chan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "滩声依旧水溶溶，岸影参差对梵宫。楚树七回凋旧叶，",
            "江人两至宿秋风。蟾蜍竹老摇疏白，菡萏池干落碎红。",
            "多病支郎念行止，晚年生计转如蓬。",
            "第八百四十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]