# -*- coding: utf-8 -*-
"""
章孝标卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 73 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 上浙东元相 ----------
    {
        "id": "zhang-xiao-biao-1",
        "title": "上浙东元相",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "婺女星边喜气频，越王台上坐诗人。雪晴山水勾留客，",
            "风暖旌旗计会春。黎庶已同猗顿富，烟花却为相公贫。",
            "何言禹迹无人继，万顷湖田又斩新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠茅山高拾遗蔓 ----------
    {
        "id": "zhang-xiao-biao-2",
        "title": "赠茅山高拾遗蔓",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "人皆贪禄利，白首更营营。若见无为理，兼忘不朽名。",
            "幽禽窥饭下，好药入篱生。梦觉幽泉滴，应疑禁漏声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 次韵和光禄钱卿二首 ----------
    {
        "id": "zhang-xiao-biao-3",
        "title": "次韵和光禄钱卿二首",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "大隐严城内，闲门向水开。扇风知暑退，树影觉秋来。",
            "望远云生海，行稀砌长苔。废兴今古事，何必叹池灰。",
            "闲论忧王室，愁眉仗酒开。方嗟三覆役，又喜四愁来。",
            "晨起萤穿竹，晡餐鸟下苔。同期阳月至，灵室祝葭灰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠庐山钱卿 ----------
    {
        "id": "zhang-xiao-biao-4",
        "title": "赠庐山钱卿",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "象魏抽簪早，匡庐筑室牢。宦情归去薄，天爵隐来高。",
            "箧有新征诏，囊馀旧缊袍。何如舍麋鹿，明主仰风骚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 山中送进士刘蟾赴举 ----------
    {
        "id": "zhang-xiao-biao-5",
        "title": "山中送进士刘蟾赴举",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "去住迹虽异，爱憎情不同。因君向帝里，使我厌山中。",
            "故友多朝客，新文尽国风。艺精心更苦，何患不成功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送进士陈峣往睦州谒冯郎中 ----------
    {
        "id": "zhang-xiao-biao-6",
        "title": "送进士陈峣往睦州谒冯郎中",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "孤帆几日程，投刺水边城。倚棹逢春老，登筵见月生。",
            "饮酣杯有浪，棋散漏无声。太守怜才者，从容礼不轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 丰城剑池即事 ----------
    {
        "id": "zhang-xiao-biao-7",
        "title": "丰城剑池即事",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "神物不复见，小池空在兹。因嫌冲斗夜，未是偃戈时。",
            "岸古鱼藏穴，蒲凋翠立危。吾皇别有剑，何必铸金为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 咏弓 ----------
    {
        "id": "zhang-xiao-biao-8",
        "title": "咏弓",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "较量武艺论勋庸，曾发将军箭落鸿。握内从夸弯似月，",
            "眼前还怕撇来风。只知击起穿雕镞，不解容和射鹄功。",
            "得病自从杯里后，至今形状怕相逢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送无相禅师入关 ----------
    {
        "id": "zhang-xiao-biao-9",
        "title": "送无相禅师入关",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "九衢车马尘，不染了空人。暂舍中峰雪，应看内殿春。",
            "斋心无外事，定力见前身。圣主方崇教，深宜谒紫宸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 赠匡山道者 ----------
    {
        "id": "zhang-xiao-biao-10",
        "title": "赠匡山道者",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "尝闻一粒功，足以反衰容。方寸如不达，此生安可逢。",
            "寄书时态尽，忆语道情浓。争得携巾屦，同归鸟外峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 道者与金丹开合已失，因为二首，再有投掷 ----------
    {
        "id": "zhang-xiao-biao-11",
        "title": "道者与金丹开合已失，因为二首，再有投掷",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "木钻钻盘石，辛勤四十年。一朝才见物，五色互呈妍。",
            "七魄憎阳盛，三彭恶命延。被他迷失却，叹息只潸然。",
            "阴阳曾作炭，造化亦分功。减自青囊里，收安玉合中。",
            "凡材难度世，神物自归空。惆怅流年速，看成白首翁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 思越州山水寄朱庆馀 ----------
    {
        "id": "zhang-xiao-biao-12",
        "title": "思越州山水寄朱庆馀",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "窗户潮头雪，云霞镜里天。岛桐秋送雨，江艇暮摇烟。",
            "藕折莲芽脆，茶挑茗眼鲜。还将欧冶剑，更淬若耶泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 蜀中上王尚书 ----------
    {
        "id": "zhang-xiao-biao-13",
        "title": "蜀中上王尚书",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "梓桐花幕碧云浮，天许文星寄上头。武略剑峰环相府，",
            "诗情锦浪浴仙洲。丁香风里飞笺草，邛竹烟中动酒钩。",
            "自古名高闲不得，肯容王粲赋登楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 赠陆鬯浙西进诗除官 ----------
    {
        "id": "zhang-xiao-biao-14",
        "title": "赠陆鬯浙西进诗除官",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "帝城云物得阳春，水国烟花失主人。",
            "昨日天风吹乐府，六宫丝管一时新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 古行宫 ----------
    {
        "id": "zhang-xiao-biao-15",
        "title": "古行宫",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "瓦烟疏冷古行宫，寂寞朱门反锁空。残粉水银流砌下，",
            "堕环秋月落泥中。莺传旧语娇春日，花学严妆妒晓风。",
            "天子时清不巡幸，只应鸾凤集梧桐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 题上皇观 ----------
    {
        "id": "zhang-xiao-biao-16",
        "title": "题上皇观",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "烟霞星盖七星坛，想像先朝驻禁銮。辇路已平栽药地，",
            "皇风犹在步虚寒。楼台瑞气晴萧索，杉桧龙身老屈蟠。",
            "翻感惠休并李郭，剑门空处望长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 鹰 ----------
    {
        "id": "zhang-xiao-biao-17",
        "title": "鹰",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "星眸未放瞥秋毫，频掣金铃试雪毛。会使老拳供口腹，",
            "莫辞亲手啖腥臊。穿云自怪身如电，煞兔谁知吻胜刀。",
            "可惜忍饥寒日暮，向人鵮断碧丝绦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 方山寺松下泉 ----------
    {
        "id": "zhang-xiao-biao-18",
        "title": "方山寺松下泉",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "石脉绽寒光，松根喷晓霜。注瓶云母滑，漱齿茯苓香。",
            "野客偷煎茗，山僧惜净床。三禅不要问，孤月在中央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 瀑布 ----------
    {
        "id": "zhang-xiao-biao-19",
        "title": "瀑布",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "秋河溢长空，天洒万丈布。深雷隐云壑，孤电挂岩树。",
            "沧溟晓喷寒，碧落晴荡素。非趋下流急，热使不得住。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送张使君赴饶州（一作送饶州张蒙使君赴任） ----------
    {
        "id": "zhang-xiao-biao-20",
        "title": "送张使君赴饶州（一作送饶州张蒙使君赴任）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "饶阳因富得州名，不独农桑别有营。日暖提筐依茗树，",
            "天阴把酒入银坑。江寒鱼动枪旗影，山晚云和鼓角声。",
            "太守能诗兼爱静，西楼见月几篇成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 和滕迈先辈伤马 ----------
    {
        "id": "zhang-xiao-biao-21",
        "title": "和滕迈先辈伤马",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "浮云变化失龙儿，始忆嘶风喷沫时。蹄想尘中翻碧玉，",
            "尾休烟里掉青丝。曾同客舍吞饥渴，久共名场踏嶮巇。",
            "今日枥前兴一叹，不关行李乏金羁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 省试骐骥长鸣 ----------
    {
        "id": "zhang-xiao-biao-22",
        "title": "省试骐骥长鸣",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "有马骨堪惊，无人眼暂明。力穷吴坂峻，嘶苦朔风生。",
            "逐逐怀良御，萧萧顾乐鸣。瑶池期弄影，天路拟飞声。",
            "皎月谁知种，浮云莫问程。盐车今愿脱，千里为君行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 鲤鱼 ----------
    {
        "id": "zhang-xiao-biao-23",
        "title": "鲤鱼",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "眼似真珠鳞似金，时时动浪出还沈。",
            "河中得上龙门去，不叹江湖岁月深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 饥鹰词 ----------
    {
        "id": "zhang-xiao-biao-24",
        "title": "饥鹰词",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "遥想平原兔正肥，千回砺吻振毛衣。",
            "纵令啄解丝绦结，未得人呼不敢飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 归燕词辞工部侍郎（一作下第后献主司） ----------
    {
        "id": "zhang-xiao-biao-25",
        "title": "归燕词辞工部侍郎（一作下第后献主司）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "旧垒危巢泥已落，今年故向社前归。",
            "连云大厦无栖处，更望谁家门户飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 归海上旧居 ----------
    {
        "id": "zhang-xiao-biao-26",
        "title": "归海上旧居",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "乡路绕蒹葭，萦纡出海涯。人衣披蜃气，马迹印盐花。",
            "草没题诗石，潮摧坐钓槎。还归旧窗里，凝思向馀霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 答友人惠牙簪 ----------
    {
        "id": "zhang-xiao-biao-27",
        "title": "答友人惠牙簪",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "牙簪不可忘，来处隔炎荒。截得半环月，磨成四寸霜。",
            "晓辞梳齿腻，秋入发根凉。好是纱巾下，纤纤锥出囊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 日者 ----------
    {
        "id": "zhang-xiao-biao-28",
        "title": "日者",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "十指中央了五行，说人休咎见前生。",
            "我来本乞真消息，却怕呵钱卦欲成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 送金可纪归新罗 ----------
    {
        "id": "zhang-xiao-biao-29",
        "title": "送金可纪归新罗",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "登唐科第语唐音，望日初生忆故林。鲛室夜眠阴火冷，",
            "蜃楼朝泊晓霞深。风高一叶飞鱼背，潮净三山出海心。",
            "想把文章合夷乐，蟠桃花里醉人参。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 闻角 ----------
    {
        "id": "zhang-xiao-biao-30",
        "title": "闻角",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "边秋画角怨金微，半夜对吹惊贼围。塞雁绕空秋不下，",
            "胡云著草冻还飞。关头老马嘶看月，碛里疲兵泪湿衣。",
            "馀韵袅空何处尽，戍天寥落晓星稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 梦乡 ----------
    {
        "id": "zhang-xiao-biao-31",
        "title": "梦乡",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "家住吴王旧苑东，屋头山水胜屏风。",
            "寻常梦在秋江上，钓艇游扬藕叶中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 织绫词 ----------
    {
        "id": "zhang-xiao-biao-32",
        "title": "织绫词",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "去年蚕恶绫帛贵，官急无丝织红泪。残经脆纬不通梭，",
            "鹊凤阑珊失头尾。今年蚕好缲白丝，鸟鲜花活人不知。",
            "瑶台雪里鹤张翅，禁苑风前梅折枝。不学邻家妇慵懒，",
            "蜡揩粉拭谩官眼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 诸葛武侯庙 ----------
    {
        "id": "zhang-xiao-biao-33",
        "title": "诸葛武侯庙",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "木牛零落阵图残，山姥烧钱古柏寒。",
            "七纵七擒何处在，茅花枥叶盖神坛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 长安秋夜 ----------
    {
        "id": "zhang-xiao-biao-34",
        "title": "长安秋夜",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "田家无五行，水旱卜蛙声。牛犊乘春放，儿童候暖耕。",
            "池塘烟未起，桑柘雨初晴。步晚香醪熟，村村自送迎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 钱塘赠武翊黄 ----------
    {
        "id": "zhang-xiao-biao-35",
        "title": "钱塘赠武翊黄",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "曾将心剑作戈矛，一战名场造化愁。花锦文章开四面，",
            "天人科第上三头。鸳鸿待侣飞清禁，山水缘情住外州。",
            "时伴庾公看海月，好吟诗断望潮楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 风不鸣条（一作左牢诗） ----------
    {
        "id": "zhang-xiao-biao-36",
        "title": "风不鸣条（一作左牢诗）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "旭日悬清景，微风在绿条。入松声不发，过柳影空摇。",
            "长养应潜变，扶疏每暗飘。有林时杳杳，无树暂萧萧。",
            "慢逐清烟散，轻和瑞气饶。丰年知有待，歌咏美唐尧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 贻美人 ----------
    {
        "id": "zhang-xiao-biao-37",
        "title": "贻美人",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "诸侯帐下惯新妆，皆怯刘家薄媚娘。宝髻巧梳金翡翠，",
            "罗裙宜著绣鸳鸯。轻轻舞汗初沾袖，细细歌声欲绕梁。",
            "何事不归巫峡去，故来人世断人肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 闻云中唳鹤 ----------
    {
        "id": "zhang-xiao-biao-38",
        "title": "闻云中唳鹤",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "久在青田唳，天高忽暂闻。翩翩萦碧落，嘹唳入重云。",
            "出谷莺何待，鸣岐凤欲群。九皋宁足道，此去透絪缊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 柘枝 ----------
    {
        "id": "zhang-xiao-biao-39",
        "title": "柘枝",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "柘枝初出鼓声招，花钿罗衫耸细腰。移步锦靴空绰约，",
            "迎风绣帽动飘飖。亚身踏节鸾形转，背面羞人凤影娇。",
            "只恐相公看未足，便随风雨上青霄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 上太皇先生 ----------
    {
        "id": "zhang-xiao-biao-40",
        "title": "上太皇先生",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "颢气贯精神，苍崖老姓名。烟霞空送景，水木苦无情。",
            "劚药云根断，眠花石面平。折松开月色，决水放秋声。",
            "颜为忘忧嫩，身缘绝粒轻。围棋看局势，对镜戮妖精。",
            "过海量鲸力，归天算鹤程。露凝钟乳冷，风定玉箫清。",
            "坐觉衣裳古，行疑羽翼生。应怜市朝客，开眼锁浮荣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 破山水屏风（一作姚合诗） ----------
    {
        "id": "zhang-xiao-biao-41",
        "title": "破山水屏风（一作姚合诗）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "时人嫌古画，倚壁不曾收。雨滴胶山断，风吹绢海秋。",
            "残云飞屋里，片水落床头。尚胜凡花鸟，君能补缀休。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 览杨校书文卷 ----------
    {
        "id": "zhang-xiao-biao-42",
        "title": "览杨校书文卷",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "跪伸霜素剖琅玕，身堕瑶池魄暗寒。红锦晚开云母殿，",
            "白珠秋写水精盘。情高鹤立昆仑峭，思壮鲸跳渤澥宽。",
            "谁有轩辕古铜片，为持相并照妖看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送陈校书赴蔡州幕 ----------
    {
        "id": "zhang-xiao-biao-43",
        "title": "送陈校书赴蔡州幕",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "天假纵横入幕筹，东南顿减一方忧。行赍健笔辞天阁，",
            "坐见妖星落蔡州。青草袍襟翻日脚，黄金马镫照旄头。",
            "此行领取从军乐，莫虑功名不拜侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 少年行 ----------
    {
        "id": "zhang-xiao-biao-44",
        "title": "少年行",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "平明小猎出中军，异国名香满袖薰。画榼倒悬鹦鹉嘴，",
            "花衫对舞凤凰文。手抬白马嘶春雪，臂竦青骹入暮云。",
            "落日胡姬楼上饮，风吹箫管满楼闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 蜀中赠广上人 ----------
    {
        "id": "zhang-xiao-biao-45",
        "title": "蜀中赠广上人",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "曾持麈尾引金根，万乘前头草五言。疏讲青龙归禁苑，",
            "歌抄白雪乞梨园。朝惊云气遮天阁，暮踏猿声入剑门。",
            "今日西川无子美，诗风又起浣花村。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 和顾校书新开井 ----------
    {
        "id": "zhang-xiao-biao-46",
        "title": "和顾校书新开井",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "霜锸破桐阴，青丝试浅深。月轮开地脉，镜面写天心。",
            "碧甃花千片，香泉乳百寻。欲知争汲引，听取辘轳音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 游云际寺 ----------
    {
        "id": "zhang-xiao-biao-47",
        "title": "游云际寺",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "衫袖拂青冥，推鞍上翠屏。尘埃辞马尾，城阙入窗棂。",
            "云领浮名去，钟撞大梦醒。茫茫山下事，满眼送流萍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 赠刘宽夫昆季（一作赠刘侍郎兄弟三人同时及第） ----------
    {
        "id": "zhang-xiao-biao-48",
        "title": "赠刘宽夫昆季（一作赠刘侍郎兄弟三人同时及第）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "文聚星辰衣彩霞，问谁兄弟是刘家。雁行云掺参差翼，",
            "琼树风开次第花。天假声名悬日月，国凭骚雅变浮华。",
            "曾穷晋汉儒林传，龙虎虽多未足夸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 赠杭州严史君 ----------
    {
        "id": "zhang-xiao-biao-49",
        "title": "赠杭州严史君",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "州青县白浙河濆，饱向苍龙阙下闻。鼓角自严寒海月，",
            "旌旗不动湿江云。风骚处处文章主，井邑家家父母君。",
            "长恐抱辕留不住，九天鸳鹭待成群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 题朱秀城南亭子 ----------
    {
        "id": "zhang-xiao-biao-50",
        "title": "题朱秀城南亭子",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "朱家亭子象悬匏，阶莹青莎栋剪茆。瘿挂眼开欺鸲鹆，",
            "花缘网结妒螵蛸。有时风月输三虎，无壁琴书属四郊。",
            "土木欲知精洁处，社天归燕怯安巢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 上西川王尚书 ----------
    {
        "id": "zhang-xiao-biao-51",
        "title": "上西川王尚书",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "人人入蜀谒文翁，妍丑终须露镜中。诗景荒凉难道合，",
            "客情疏密分当同。城南歌吹琴台月，江上旌旗锦水风。",
            "下客低头来又去，暗堆冰炭在深衷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 骆谷行 ----------
    {
        "id": "zhang-xiao-biao-52",
        "title": "骆谷行",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "扪云袅栈入青冥，鞿马铃骡傍日星。仰踏剑棱梯万仞，",
            "下缘冰岫杳千寻。山花织锦时聊看，涧水弹琴不暇听。",
            "若比争名求利处，寻思此路却安宁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 初及第归酬孟元翊见赠 ----------
    {
        "id": "zhang-xiao-biao-53",
        "title": "初及第归酬孟元翊见赠",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "六年衣破帝城尘，一日天池水脱鳞。未有片言惊后辈，",
            "不无惭色见同人。每登公宴思来日，渐听乡音认本身。",
            "何幸致诗相慰贺，东归花发杏桃春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 淮南李相公绅席上赋春雪 ----------
    {
        "id": "zhang-xiao-biao-54",
        "title": "淮南李相公绅席上赋春雪",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "六出花飞处处飘，粘窗著砌上寒条。",
            "朱门到晓难盈尺，尽是三军喜气消。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 及第后寄广陵故人（一作寄淮南李相公绅） ----------
    {
        "id": "zhang-xiao-biao-55",
        "title": "及第后寄广陵故人（一作寄淮南李相公绅）",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "及第全胜十政官，金鞍镀了出长安。",
            "马头渐入扬州郭，为报时人洗眼看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 小松 ----------
    {
        "id": "zhang-xiao-biao-56",
        "title": "小松",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "爪叶鳞条龙不盘，梳风幕翠一庭寒。",
            "莫言只是人长短，须作浮云向上看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 宫词 ----------
    {
        "id": "zhang-xiao-biao-57",
        "title": "宫词",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "明日銮舆欲向东，守宫金翠带愁红。",
            "九门佳气已西去，千里花开一夜风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 题杭州樟亭驿 ----------
    {
        "id": "zhang-xiao-biao-58",
        "title": "题杭州樟亭驿",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "樟亭驿上题诗客，一半寻为山下尘。",
            "世事日随流水去，红花还似白头人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 刘侍中宅盘花紫蔷薇 ----------
    {
        "id": "zhang-xiao-biao-59",
        "title": "刘侍中宅盘花紫蔷薇",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "真宰偏饶丽景家，当春盘出带根霞。",
            "从开一朵朝衣色，免踏尘埃看杂花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 题东林寺寄江州李员外 ----------
    {
        "id": "zhang-xiao-biao-60",
        "title": "题东林寺寄江州李员外",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "山势棱层入杳冥，寺形高下趁山行。象牙床坐莲花佛，",
            "玛瑙函盛贝叶经。日映砌阴移宝阁，风吹天乐动金铃。",
            "门前更有清江水，便是浔阳太守厅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 玄都观栽桃十韵 ----------
    {
        "id": "zhang-xiao-biao-61",
        "title": "玄都观栽桃十韵",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "驱使鬼神功，攒栽万树红。薰香丹凤阙，妆点紫琼宫。",
            "宝帐重庶日，妖金遍累空。色然烧药火，影舞步虚风。",
            "粉扑青牛过，枝惊白鹤冲。拜星春锦上，服食晚霞中。",
            "棋局阴长合，箫声秘不通。艳阳迷俗客，幽邃失壶公。",
            "根柢终盘石，桑麻自转蓬。求师饱灵药，他日访辽东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 僧院小松 ----------
    {
        "id": "zhang-xiao-biao-62",
        "title": "僧院小松",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "抛杉背柏冷僧帘，锁月梳风出殿檐。",
            "还似天台新雨后，小峰云外碧尖尖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 春原早望 ----------
    {
        "id": "zhang-xiao-biao-63",
        "title": "春原早望",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "一忝乡书荐，长安未得回。年光逐渭水，春色上秦台。",
            "燕掠平芜去，人冲细雨来。东风生故里，又过几花开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 西山广福院 ----------
    {
        "id": "zhang-xiao-biao-64",
        "title": "西山广福院",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "野寺孤峰上，危楼耸翠微。卷帘沧海近，洗钵白云飞。",
            "竹影临经案，松花点衲衣。日斜登望处，湖畔一僧归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 游地肺 ----------
    {
        "id": "zhang-xiao-biao-65",
        "title": "游地肺",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "市朝扰扰千古，林壑冥冥四贤。黄鹤不归丹灶，",
            "白云自养芝田。溪滩永夜流月，羽翼清秋在天。",
            "高迹无人更蹑，碧峰寥落孤烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 八月 ----------
    {
        "id": "zhang-xiao-biao-66",
        "title": "八月",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "徙倚仙居绕翠楼，分明宫漏静兼秋。",
            "长安夜夜家家月，几处笙歌几处愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 题紫微山上方 ----------
    {
        "id": "zhang-xiao-biao-67",
        "title": "题紫微山上方",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "地势连沧海，山名号紫微。景闲僧坐久，路僻客来稀。",
            "峡影云相照，河流石自围。尘喧都不到，安得此忘归。",
            "第五百零七卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 及第后寄李绅 ----------
    {
        "id": "zhang-xiao-biao-68",
        "title": "及第后寄李绅",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "及第全胜十政官，金鞍镀了出长安。",
            "马头渐入扬州郭，为报时人洗眼看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 送张孝廉归吴 ----------
    {
        "id": "zhang-xiao-biao-69",
        "title": "送张孝廉归吴",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "吴将勤苦见高科，艺至春官不奈何。",
            "想得江南诸父老，因君鞭鞑子孙多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 夜笛词 ----------
    {
        "id": "zhang-xiao-biao-70",
        "title": "夜笛词",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "皎洁西楼月未斜，笛声寥亮入东家。",
            "顿令灯下裁衣妇，误剪同心一片依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 题碧山寺塔 ----------
    {
        "id": "zhang-xiao-biao-71",
        "title": "题碧山寺塔",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "六时佛火明珠缀，午后茶烟出翠微。",
            "萦砌乳泉梳石发，滴松银露洗墙衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 玩月遇云 ----------
    {
        "id": "zhang-xiao-biao-72",
        "title": "玩月遇云",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "无端玉叶连天起，不放金波到晓流。",
            "暗惜蚌胎沉海面，仰思鹏翼破风头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 句 ----------
    {
        "id": "zhang-xiao-biao-73",
        "title": "句",
        "author": "章孝标",
        "poet_id": "zhang-xiao-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "钱塘去国三千里，一道风光任意看。（《及第》）",
            "珠呈夜浦萤无影，鹘坐秋林鸟失行。（奉酬朱二十四见寄诗",
            "昨日见君亲下笔，五花笺上黑龙飞。（《观草书》）",
            "何人枉折教狼藉，孤负春风长养情。（《杨柳枝》）",
            "梅花带雪飞琴上，柳色和烟入酒中。（早春初晴野宴）",
            "阮籍啸场人步月，子猷看处鸟栖烟。（《竹词》）",
            "白练鸟迷山芍药，红妆妓妒水林檎。（《宴渔州》）",
            "今日华山秋顶上，闻天长叫在长空。（《独鹤谣》）",
            "天风更送新声出，不放行云过凤楼。（《梨园调》）",
            "昨日天宫吹乐府，六官弦管一时新。（《赠盩厔陆少府》）",
            "通传胜事因风月，打破愁肠是酒杯。（《游檀溪》）",
            "姑苏台上烟花月，宁负春风箫管声。（送陆二十一及第归）",
            "玉轮低月中天晓，金铎纵风上界秋。（《登总持寺塔》）",
            "萧洒竹房尘境外，满天云月共清虚。（《题灵初禅师院》）",
            "言若浚川流巨海，戒如秋月挂长空。（《赠言枢法师》）",
            "金殿月中看捣药，玉楼风里听吹笙。（《宿天柱观》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]