# -*- coding: utf-8 -*-
"""
窦群卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 23 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 雪中遇直 ----------
    {
        "id": "dou-qun-1",
        "title": "雪中遇直",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "寒光凝雪彩，限直居粉闱。恍疑白云上，乍觉金印非。",
            "树色霭虚空，琴声谐素徽。明晨阻通籍，独卧挂朝衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 东山月下怀友人 ----------
    {
        "id": "dou-qun-2",
        "title": "东山月下怀友人",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "东山多乔木，月午始苍苍。虽殊碧海状，爱此青苔光。",
            "高下灭华烛，参差启洞房。佳人梦馀思，宝瑟愁应商。",
            "皎洁殊未已，沈吟限一方。宦情哂鸡口，世路倦羊肠。",
            "彼美金石分，眷言兰桂芳。清晖讵同夕，耿耿但相望。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 时兴 ----------
    {
        "id": "dou-qun-3",
        "title": "时兴",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "夙心旷何许，日暮依林薄。流水不待人，孤云时映鹤。",
            "濛濛千万花，曷为神仙药。不遇烂柯叟，报非旧城郭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题剑 ----------
    {
        "id": "dou-qun-4",
        "title": "题剑",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "丈夫得宝剑，束发曾书绅。嗟吁一朝遇，愿言千载邻。",
            "心许留家树，辞直断佞臣。焉能为绕指，拂拭试时人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 黔中书事 ----------
    {
        "id": "dou-qun-5",
        "title": "黔中书事",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "万事非京国，千山拥丽谯。佩刀看日晒，赐马傍江调。",
            "言语多重译，壶觞每独谣。沿流如著翅，不敢问归桡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 冬日晓思寄杨二十七炼师 ----------
    {
        "id": "dou-qun-6",
        "title": "冬日晓思寄杨二十七炼师",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "雨霜地如雪，松桂青参差。鹤警晨光上，步出南轩时。",
            "所遇各有适，我怀亦自怡。愿言缄素封，昨夜梦琼枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 贞元末东院尝接事今西川武相公于兹…夏日即事因寄四韵 ----------
    {
        "id": "dou-qun-7",
        "title": "贞元末东院尝接事今西川武相公于兹…夏日即事因寄四韵",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "重轩深似谷，列柏镇含烟。境绝苍蝇到，风生白雪前。",
            "弹冠惊迹近，专席感恩偏。霄汉朝来下，油幢路几千。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 北地（一作容州） ----------
    {
        "id": "dou-qun-8",
        "title": "北地（一作容州）",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "何事到容州，临池照白头。兴随年已往，愁与水长流。",
            "黾勉思逋客，辛勤悔饭牛。诗人亦何意，树草欲忘忧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 雨后月下寄怀羊二十七资州 ----------
    {
        "id": "dou-qun-9",
        "title": "雨后月下寄怀羊二十七资州",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "夕霁凉飙至，翛然心赏谐。清光松上月，虚白郡中斋。",
            "置酒平生在，开衿愿见乖。殷勤寄双鲤，梦想入君怀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 奉酬西川武相公晨兴赠友见示之作 ----------
    {
        "id": "dou-qun-10",
        "title": "奉酬西川武相公晨兴赠友见示之作",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "碧树分晓色，宿雨弄清光。犹闻子规啼，独念一声长。",
            "眷眷轸芳思，依依寄远方。情同如兰臭，惠比返魂香。",
            "新什惊变雅，古瑟代沈湘。殷勤见知己，掩抑绕中肠。",
            "隙驷不我待，路人易相忘。孤老空许国，幽报期苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 晨游昌师院 ----------
    {
        "id": "dou-qun-11",
        "title": "晨游昌师院",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "深庭芳草浓，晓井山泉溢。林馥乱沈烟，石润侵经室。",
            "幽岩鸟飞静，晴岭云归密。壁藓凝苍华，竹阴满晴日。",
            "生期半宵梦，忧绪仍非一。若无高世心，安能此终毕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 同王晦伯朱遐景宿慧山寺 ----------
    {
        "id": "dou-qun-12",
        "title": "同王晦伯朱遐景宿慧山寺",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "共访青山寺，曾隐南朝人。问古松桂老，开襟言笑新。",
            "步移月亦出，水映石磷磷。予洗肠中酒，君濯缨上尘。",
            "皓彩入幽抱，清气逼苍旻。信此澹忘归，淹留冰玉邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 草堂夜坐 ----------
    {
        "id": "dou-qun-13",
        "title": "草堂夜坐",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "匣中三尺剑，天上少微星。勿谓相去远，壮心曾不停。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 经潼关赠宇文十 ----------
    {
        "id": "dou-qun-14",
        "title": "经潼关赠宇文十",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "古有弓旌礼，今征草泽臣。方同白衣见，不是弃繻人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 观画鹤 ----------
    {
        "id": "dou-qun-15",
        "title": "观画鹤",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "华亭不相识，卫国复谁知。怅望冲天羽，甘心任画师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 晚自台中归永宁里南望山色怅然有怀呈上右司十一兄 ----------
    {
        "id": "dou-qun-16",
        "title": "晚自台中归永宁里南望山色怅然有怀呈上右司十一兄",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "白发侵侵生有涯，青襟曾爱紫河车。",
            "自怜悟主难归去，马上看山恐到家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 中牟县经鲁公庙（尝修名臣略，系司徒公） ----------
    {
        "id": "dou-qun-17",
        "title": "中牟县经鲁公庙（尝修名臣略，系司徒公）",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "青史编名在箧中，故林遗庙揖仁风。",
            "还将文字如颜色，暂下蒲车为鲁公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 初入谏司喜家室至 ----------
    {
        "id": "dou-qun-18",
        "title": "初入谏司喜家室至",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "一旦悲欢见孟光，十年辛苦伴沧浪。",
            "不知笔砚缘封事，犹问佣书日几行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 春雨 ----------
    {
        "id": "dou-qun-19",
        "title": "春雨",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "昨日偷闲看花了，今朝多雨奈人何。",
            "人间尽似逢花雨，莫爱芳菲湿绮罗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送内弟袁德师 ----------
    {
        "id": "dou-qun-20",
        "title": "送内弟袁德师",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "南渡登舟即水仙，西垣有客思悠然。",
            "因君相问为官意，不卖毗陵负郭田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 赠刘大兄院长 ----------
    {
        "id": "dou-qun-21",
        "title": "赠刘大兄院长",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "万年枝下昔同趋，三事行中半已无。",
            "路自长沙忽相见，共惊双鬓别来殊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 假日寻花 ----------
    {
        "id": "dou-qun-22",
        "title": "假日寻花",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "武陵缘源不可到，河阳带县讵堪夸。",
            "枝枝如雪南关外，一日休闲尽属花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 自京将赴黔南 ----------
    {
        "id": "dou-qun-23",
        "title": "自京将赴黔南",
        "author": "窦群",
        "poet_id": "dou-qun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "风雨荆州二月天，问人初雇峡中船。",
            "西南一望云和水，犹道黔南有四千。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]