# -*- coding: utf-8 -*-
"""
杨师道卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 22 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 横吹曲辞·陇头水 ----------
    {
        "id": "yang-shi-dao-1",
        "title": "横吹曲辞·陇头水",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "陇头秋月明，陇水带关城。笳添离别曲，风送断肠声。",
            "映雪峰犹暗，乘冰马屡惊。雾中寒雁至，沙上转蓬轻。",
            "天山传羽檄，汉地急征兵。阵开都护道，剑聚伏波营。",
            "于兹觉无度，方共濯胡缨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 陇头水 ----------
    {
        "id": "yang-shi-dao-2",
        "title": "陇头水",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "陇头秋月明，陇水带关城。笳添离别曲，风送断肠声。",
            "映雪峰犹暗，乘冰马屡惊。雾中寒雁至，沙上转蓬轻。",
            "天山传羽檄，汉地急征兵。阵开都护道，剑聚伏波营。",
            "于兹觉无渡，方共濯胡缨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 中书寓直咏雨简褚起居上官学士 ----------
    {
        "id": "yang-shi-dao-3",
        "title": "中书寓直咏雨简褚起居上官学士",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "云暗苍龙阙，沉沉殊未开。窗临凤凰沼，飒飒雨声来。",
            "电影入飞阁，风威凌吹台。长檐响奔溜，清簟肃浮埃。",
            "早荷叶稍没，新篁枝半摧。兹晨怅多绪，怀友自难裁。",
            "况复重城内，日暮独裴回。玉阶良史笔，金马掞天才。",
            "高甍通散骑，复道驾蓬莱。思君赠桃李，于此冀琼瑰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 阙题 ----------
    {
        "id": "yang-shi-dao-4",
        "title": "阙题",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "汉家伊洛九重城，御路浮桥万里平。桂户雕梁连绮翼，",
            "虹梁绣柱映丹楹。朝光欲动千门曙，丽日初照百花明。",
            "燕赵蛾眉旧倾国，楚宫腰细本传名。二月桑津期结伴，",
            "三春淇水逐关情。兰丛有意飞双蝶，柳叶无趣隐啼莺。",
            "扇里细妆将夜并，风前独舞共花荣。两鬟百万谁论价，",
            "一笑千金判是轻。不为披图来侍寝，非因主第奉身迎。",
            "羊车讵畏青门闭，兔月今宵照后庭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 初秋夜坐应诏 ----------
    {
        "id": "yang-shi-dao-5",
        "title": "初秋夜坐应诏",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "玉琯凉初应，金壶夜渐阑。沧池流稍洁，仙掌露方漙。",
            "雁声风处断，树影月中寒。爽气长空净，高吟觉思宽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 赋终南山用风字韵应诏 ----------
    {
        "id": "yang-shi-dao-6",
        "title": "赋终南山用风字韵应诏",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "眷言怀隐逸，辍驾践幽丛。白云飞夏雨，碧岭横春虹。",
            "草绿长杨路，花疏五柞宫。登临日将晚，兰桂起香风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 咏饮马应诏 ----------
    {
        "id": "yang-shi-dao-7",
        "title": "咏饮马应诏",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "清晨控龙马，弄影出花林。躞蹀依春涧，联翩度碧浔。",
            "苔流染丝络，水洁写雕簪。一御瑶池驾，讵忆长城阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 初宵看婚 ----------
    {
        "id": "yang-shi-dao-8",
        "title": "初宵看婚",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "洛城花烛动，戚里画新蛾。隐扇羞应惯，含情愁已多。",
            "轻啼湿红粉，微睇转横波。更笑巫山曲，空传暮雨过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 侍宴赋得起坐弹鸣琴二首（一作杨希道诗） ----------
    {
        "id": "yang-shi-dao-9",
        "title": "侍宴赋得起坐弹鸣琴二首（一作杨希道诗）",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "北林鹊夜飞，南轩月初进。调弦发清徵，荡心祛褊吝。",
            "变作离鸿声，还入思归引。长叹未终极，秋风飘素鬓。",
            "丝传园客意，曲奏楚妃情。罕有知音者，空劳流水声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 咏琴（一作杨希道诗） ----------
    {
        "id": "yang-shi-dao-10",
        "title": "咏琴（一作杨希道诗）",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "久擅龙门质，孤竦峄阳名。齐娥初发弄，赵女正调声。",
            "嘉客勿遽反，繁弦曲未成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 咏笙（一作杨希道诗） ----------
    {
        "id": "yang-shi-dao-11",
        "title": "咏笙（一作杨希道诗）",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "短长插凤翼，洪细摹鸾音。能令楚妃叹，复使荆王吟。",
            "切切孤竹管，来应云和琴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 应诏咏巢乌 ----------
    {
        "id": "yang-shi-dao-12",
        "title": "应诏咏巢乌",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "桂树春晖满，巢乌刷羽仪。朝飞丽城上，夜宿碧林陲。",
            "背风藏密叶，向日逐疏枝。仰德还能哺，依仁遂可窥。",
            "惊鸣雕辇侧，王吉自相知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 奉和夏日晚景应诏 ----------
    {
        "id": "yang-shi-dao-13",
        "title": "奉和夏日晚景应诏",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "辇路夹垂杨，离宫通建章。日落横峰影，云归起夕凉。",
            "雕轩动流吹，羽盖息回塘。薙草生还绿，残花落尚香。",
            "青岩类姑射，碧涧似汾阳。幸属无为日，欢娱尚未央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 奉和圣制春日望海 ----------
    {
        "id": "yang-shi-dao-14",
        "title": "奉和圣制春日望海",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "春山临渤海，征旅辍晨装。回瞰卢龙塞，斜瞻肃慎乡。",
            "洪波回地轴，孤屿映云光。落日惊涛上，浮天骇浪长。",
            "仙台隐螭驾，水府泛鼋梁。碣石朝烟灭，之罘归雁翔。",
            "北巡非汉后，东幸异秦皇。搴旗羽林客，跋距少年场。",
            "龙击驱辽水，鹏飞出带方。将举青丘缴，安访白霓裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 春朝闲步 ----------
    {
        "id": "yang-shi-dao-15",
        "title": "春朝闲步",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "休沐乘闲豫，清晨步北林。池塘藉芳草，兰芷袭幽衿。",
            "雾中分晓日，花里弄春禽。野径香恒满，山阶笋屡侵。",
            "何须命轻盖，桃李自成阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 还山宅 ----------
    {
        "id": "yang-shi-dao-16",
        "title": "还山宅",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "暮春还旧岭，徙倚玩年华。芳草无行径，空山正落花。",
            "垂藤扫幽石，卧柳碍浮槎。鸟散茅檐静，云披涧户斜。",
            "依然此泉路，犹是昔烟霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 咏马 ----------
    {
        "id": "yang-shi-dao-17",
        "title": "咏马",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "宝马权奇出未央，雕鞍照曜紫金装。春草初生驰上苑，",
            "秋风欲动戏长杨。鸣珂屡度章台侧，细蹀经向濯龙傍。",
            "徒令汉将连年去，宛城今已献名王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 奉和咏弓 ----------
    {
        "id": "yang-shi-dao-18",
        "title": "奉和咏弓",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "霜重麟胶劲，风高月影圆。乌飞随帝辇，雁落逐鸣弦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 咏砚 ----------
    {
        "id": "yang-shi-dao-19",
        "title": "咏砚",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "圆池类璧水，轻翰染烟华。将军欲定远，见弃不应赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 奉和正日临朝应诏 ----------
    {
        "id": "yang-shi-dao-20",
        "title": "奉和正日临朝应诏",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "皇猷被寰宇，端扆属元辰。九重丽天邑，千门临上春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 咏舞（一作杨希道诗） ----------
    {
        "id": "yang-shi-dao-21",
        "title": "咏舞（一作杨希道诗）",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "二八如回雪，三春类早花。分行向烛转，一种逐风斜。",
            "第三十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 采莲 ----------
    {
        "id": "yang-shi-dao-22",
        "title": "采莲",
        "author": "杨师道",
        "poet_id": "yang-shi-dao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "采莲江浦觅同心，日暮风生江水深。",
            "莫言花重船应没，自解凌波不畏沉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]