# -*- coding: utf-8 -*-
"""
萧至忠卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 奉和九日幸临渭亭登高应制得馀字 ----------
    {
        "id": "xiao-zhi-zhong-1",
        "title": "奉和九日幸临渭亭登高应制得馀字",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "望幸三秋暮，登高九日初。朱旗巡汉苑，翠帟俯秦墟。",
            "宠极萸房遍，恩深菊酎馀。承欢何以答，万亿奉宸居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉和九月九日登慈恩寺浮图应制 ----------
    {
        "id": "xiao-zhi-zhong-2",
        "title": "奉和九月九日登慈恩寺浮图应制",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "天跸三乘启，星舆六辔行。登高凌宝塔，极目遍王城。",
            "神卫空中绕，仙歌云外清。重阳千万寿，率舞颂升平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 奉和幸安乐公主山庄应制 ----------
    {
        "id": "xiao-zhi-zhong-3",
        "title": "奉和幸安乐公主山庄应制",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "西郊窈窕凤凰台，北渚平明法驾来。匝地金声初度曲，",
            "周堂玉溜好传杯。湾路分游画舟转，岸门相向碧亭开。",
            "微臣此时承宴乐，仿佛疑从星汉回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送张亶赴朔方应制（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-4",
        "title": "送张亶赴朔方应制（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "命将择耆年，图功胜必全。光辉万乘饯，威武二庭宣。",
            "中衢横鼓角，旷野蔽旌旃。推食天厨至，投醪御酒传。",
            "凉风过雁苑，杀气下鸡田。分阃恩何极，临岐动睿篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 陪幸长宁公主林亭（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-5",
        "title": "陪幸长宁公主林亭（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "公主林亭地，清晨降玉舆。画桥飞渡水，仙阁迥临虚。",
            "新晴看蛱蝶，早夏摘芙蕖。文酒娱游盛，忻叨侍从馀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 陪幸五王宅（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-6",
        "title": "陪幸五王宅（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "北斗枢机任，西京肺腑亲。畴昔王门下，今兹制幸晨。",
            "恩来山水被，圣作管弦新。绕座薰红药，当轩暗绿筠。",
            "摘荷才早夏，听鸟尚馀春。行漏金徒晓，风烟是观津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 三会寺应制（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-7",
        "title": "三会寺应制（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "岧峣仓史台，敞朗绀园开。戒旦壶人警，翻霜羽骑来。",
            "下辇登三袭，褰旒望九垓。林披馆陶榜，水浸昆明灰。",
            "网户飞花缀，幡竿度鸟回。豫游仙唱动，潇洒出尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 荐福寺应制（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-8",
        "title": "荐福寺应制（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "地灵传景福，天驾俨钩陈。佳哉藩邸旧，赫矣梵宫新。",
            "香塔鱼山下，禅堂雁水滨。珠幡映白日，镜殿写青春。",
            "甚欢延故吏，大觉拯生人。幸承歌颂末，长奉属车尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 陪游上苑遇雪（一作刘宪诗） ----------
    {
        "id": "xiao-zhi-zhong-9",
        "title": "陪游上苑遇雪（一作刘宪诗）",
        "author": "萧至忠",
        "poet_id": "xiao-zhi-zhong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "龙骖晓入望春宫，正逢春雪舞春风。",
            "花光并在天文上，寒气行销御酒中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]