# -*- coding: utf-8 -*-
"""
王初卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 17 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 延平天庆观 ----------
    {
        "id": "wang-chu-1",
        "title": "延平天庆观",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "剑化江边绿构新，层台不染玉梯尘。千章隐篆标龙简，",
            "一曲空歌降凤钧。岚气湿衣云叶晚，天香飘户月枝春。",
            "盟经早晚闻仙语，学种三芝伴羽人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送叶秀才 ----------
    {
        "id": "wang-chu-2",
        "title": "送叶秀才",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "快骑璁珑刻玉羁，河梁返照上征衣。层冰春近蟠龙起，",
            "九泽云闲独鹤飞。行想北山清梦断，重游西洛故人稀。",
            "汉庭狗监深知己，有日前驱负弩归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送王秀才谒池州吴都督 ----------
    {
        "id": "wang-chu-3",
        "title": "送王秀才谒池州吴都督",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "池阳去去跃雕鞍，十里长亭百草干。衣袂障风金镂细，",
            "剑光横雪玉龙寒。晴郊别岸乡魂断，晓树啼乌客梦残。",
            "南馆星郎东道主，摇鞭休问路行难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 青帝 ----------
    {
        "id": "wang-chu-4",
        "title": "青帝",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "青帝邀春隔岁还，月娥孀独夜漫漫。韩凭舞羽身犹在，",
            "素女商弦调未残。终古兰岩栖偶鹤，从来玉谷有离鸾。",
            "几时幽恨飘然断，共待天池一水干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 银河 ----------
    {
        "id": "wang-chu-5",
        "title": "银河",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "阊阖疏云漏绛津，桥头秋夜鹊飞频。犹残仙媛湔裙水，",
            "几见星妃度袜尘。历历素榆飘玉叶，涓涓清月湿冰轮。",
            "年来若有乘槎客，为吊波灵是楚臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 书秋 ----------
    {
        "id": "wang-chu-6",
        "title": "书秋",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "千里南云度塞鸿，秋容无迹淡平空。人间玉岭清宵月，",
            "天上银河白昼风。潘赋登山魂易断，楚歌遗佩怨何穷。",
            "往来未若奇张翰，欲鲙霜鲸碧海东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 自和书秋 ----------
    {
        "id": "wang-chu-7",
        "title": "自和书秋",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "陇首斜飞避弋鸿，颓云萧索见层空。汉宫夜结双茎露，",
            "阊阖凉生六幕风。湘女怨弦愁不禁，鄂君香被梦难穷。",
            "江边两桨连歌渡，惊散游鱼莲叶东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 立春后作 ----------
    {
        "id": "wang-chu-8",
        "title": "立春后作",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "东君珂佩响珊珊，青驭多时下九关。",
            "方信玉霄千万里，春风犹未到人间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 梅花二首 ----------
    {
        "id": "wang-chu-9",
        "title": "梅花二首",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "应为阳春信未传，固将青艳属残年。",
            "东君欲待寻佳约，剩寄衣香与粉绵。",
            "迎春雪艳飘零极，度夕蟾华掩映多。",
            "欲托清香传远信，一枝无计奈愁何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 春日咏梅花二首 ----------
    {
        "id": "wang-chu-10",
        "title": "春日咏梅花二首",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "靓妆才罢粉痕新，递晓风回散玉尘。",
            "若遣有情应怅望，已兼残雪又兼春。",
            "青帝来时值远芳，残花残雪尚交光。",
            "隔年拟待春消息，得见春风已断肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 即夕 ----------
    {
        "id": "wang-chu-11",
        "title": "即夕",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "榆叶飘零碧汉流，玉蟾珠露两清秋。",
            "仙家若有单栖恨，莫向银台半夜游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送陈校勘入宿 ----------
    {
        "id": "wang-chu-12",
        "title": "送陈校勘入宿",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "日落风回卷碧霓，芳蓬一夜拆龙泥。",
            "银台级级连清汉，桂子香浓月杵低。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 即夕 ----------
    {
        "id": "wang-chu-13",
        "title": "即夕",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "风幌凉生白袷衣，星榆才乱绛河低。",
            "月明休近相思树，恐有韩凭一处栖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 早春咏雪 ----------
    {
        "id": "wang-chu-14",
        "title": "早春咏雪",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "句芒宫树已先开，珠蕊琼花斗剪裁。",
            "散作上林今夜雪，送教春色一时来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 望雪 ----------
    {
        "id": "wang-chu-15",
        "title": "望雪",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "银花珠树晓来看，宿醉初醒一倍寒。",
            "已似王恭披鹤氅，凭栏仍是玉栏干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 雪霁 ----------
    {
        "id": "wang-chu-16",
        "title": "雪霁",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "星榆叶叶昼离披，云粉千重凝不飞。",
            "昆玉楼台珠树密，夜来谁向月中归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 舟次汴堤 ----------
    {
        "id": "wang-chu-17",
        "title": "舟次汴堤",
        "author": "王初",
        "poet_id": "wang-chu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "曲岸兰丛雁飞起，野客维舟碧烟里。",
            "竿头五两转天风，白日杨花满流水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]