# -*- coding: utf-8 -*-
"""
陈去疾卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 送林刺史简言之漳州 ----------
    {
        "id": "chen-qu-ji-1",
        "title": "送林刺史简言之漳州",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "江树欲含曛，清歌一送君。征骖辞荔浦，别袂暗松云。",
            "路狭横柯度，山深坠叶闻。明朝宿何处，未忍醉中分。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 忆山中 ----------
    {
        "id": "chen-qu-ji-2",
        "title": "忆山中",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "长吟重悒然，为忆山中年。清瑟泛遥夜，乱花随暮烟。",
            "珠林馀露气，乳窦滴香泉。迹远尘埃外，花开绮藻前。",
            "岩罗云貌逸，竹抱水容妍。蕙磴飞英绕，萍潭片影悬。",
            "林藏诸曲胜，台擅一峰偏。会可标真寄，焚香对石筵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 元夕京城和欧阳衮 ----------
    {
        "id": "chen-qu-ji-3",
        "title": "元夕京城和欧阳衮",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "兰焰芳芬彻晓开，珠光新霭映人来。歌迎甲夜催银管，",
            "影动繁星缀玉台。别有朱门春澹荡，不妨芝火翠崔嵬。",
            "此时月色同沾醉，何处游轮陌上回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送韩将军之雁门 ----------
    {
        "id": "chen-qu-ji-4",
        "title": "送韩将军之雁门",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "荒塞峰烟百道驰，雁门风色暗旌旗。破围铁骑长驱疾，",
            "饮血将军转战危。画角吹开边月静，缦缨不信虏尘窥。",
            "归来长揖功成后，黄石当年故有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 赋得骐骥长鸣 ----------
    {
        "id": "chen-qu-ji-5",
        "title": "赋得骐骥长鸣",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "骐骥忻知己，嘶鸣忽异常。积悲摅怨抑，一举彻穹苍。",
            "迹类三年鸟，心驰五达庄。何言从蹇踬，今日逐腾骧。",
            "牛皂休维絷，天衢恣陆梁。向非逢伯乐，谁足见其长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 偶题 ----------
    {
        "id": "chen-qu-ji-6",
        "title": "偶题",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "魂梦天南垂，宿昔万里道。池台花气深，到处生春草。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 春宫曲 ----------
    {
        "id": "chen-qu-ji-7",
        "title": "春宫曲",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "流莺春晓唤樱桃，花外传呼殿影高。",
            "抱里琵琶最承宠，君王敕赐玉檀槽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 采莲曲 ----------
    {
        "id": "chen-qu-ji-8",
        "title": "采莲曲",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "粉光花色叶中开，荷气衣香水上来。",
            "棹响清潭见斜领，双鸳何事亦相猜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 踏歌行 ----------
    {
        "id": "chen-qu-ji-9",
        "title": "踏歌行",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "鸳鸯楼下万花新，翡翠宫前百戏陈。",
            "夭矫翔龙衔火树，飞来瑞凤散芳春。",
            "仙跸初传紫禁香，瑞云开处夜花芳。",
            "繁弦促管升平调，绮缀丹莲借月光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 塞下曲 ----------
    {
        "id": "chen-qu-ji-10",
        "title": "塞下曲",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "春至金河雪似花，萧条玉塞但胡沙。",
            "晓来重上关城望，惟见惊尘不见家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送人谪幽州 ----------
    {
        "id": "chen-qu-ji-11",
        "title": "送人谪幽州",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "临路深怀放废惭，梦中犹自忆江南。",
            "莫言塞北春风少，还胜炎荒入瘴岚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 西上辞母坟 ----------
    {
        "id": "chen-qu-ji-12",
        "title": "西上辞母坟",
        "author": "陈去疾",
        "poet_id": "chen-qu-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "高盖山头日影微，黄昏独立宿禽稀。",
            "林间滴酒空垂泪，不见丁宁嘱早归。",
            "第四百九十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]