# -*- coding: utf-8 -*-
"""
薛涛卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 78 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 酬人雨后玩竹 ----------
    {
        "id": "xue-tao-1",
        "title": "酬人雨后玩竹",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "南天春雨时，那鉴雪霜姿。众类亦云茂，虚心能自持。",
            "多留晋贤醉，早伴舜妃悲。晚岁君能赏，苍苍劲节奇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 春望词四首 ----------
    {
        "id": "xue-tao-2",
        "title": "春望词四首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "花开不同赏，花落不同悲。欲问相思处，花开花落时。",
            "揽草结同心，将以遗知音。春愁正断绝，春鸟复哀吟。",
            "风花日将老，佳期犹渺渺。不结同心人，空结同心草。",
            "那堪花满枝，翻作两相思。玉箸垂朝镜，春风知不知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 宣上人见示与诸公唱和 ----------
    {
        "id": "xue-tao-3",
        "title": "宣上人见示与诸公唱和",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "许厕高斋唱，涓泉定不如。可怜谯记室，流水满禅居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 风 ----------
    {
        "id": "xue-tao-4",
        "title": "风",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "猎蕙微风远，飘弦唳一声。林梢鸣淅沥，松径夜凄清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 月 ----------
    {
        "id": "xue-tao-5",
        "title": "月",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "魄依钩样小，扇逐汉机团。细影将圆质，人间几处看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 蝉 ----------
    {
        "id": "xue-tao-6",
        "title": "蝉",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "露涤清音远，风吹数叶齐。声声似相接，各在一枝栖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 池上双鸟 ----------
    {
        "id": "xue-tao-7",
        "title": "池上双鸟",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "双栖绿池上，朝暮共飞还。更忆将雏日，同心莲叶间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 鸳鸯草 ----------
    {
        "id": "xue-tao-8",
        "title": "鸳鸯草",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "绿英满香砌，两两鸳鸯小。但娱春日长，不管秋风早。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 罚赴边有怀上韦令公二首（一作陈情上韦令公） ----------
    {
        "id": "xue-tao-9",
        "title": "罚赴边有怀上韦令公二首（一作陈情上韦令公）",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "闻道边城苦，今来到始知。羞将门下曲，唱与陇头儿。",
            "黠虏犹违命，烽烟直北愁。却教严谴妾，不敢向松州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 咏八十一颗 ----------
    {
        "id": "xue-tao-10",
        "title": "咏八十一颗",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "色比丹霞朝日，形如合浦筼筜。",
            "开时九九如数，见处双双颉颃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 谒巫山庙 ----------
    {
        "id": "xue-tao-11",
        "title": "谒巫山庙",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "乱猿啼处访高唐，路入烟霞草木香。山色未能忘宋玉，",
            "水声犹是哭襄王。朝朝夜夜阳台下，为雨为云楚国亡。",
            "惆怅庙前多少柳，春来空斗画眉长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 牡丹 ----------
    {
        "id": "xue-tao-12",
        "title": "牡丹",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "去春零落暮春时，泪湿红笺怨别离。常恐便同巫峡散，",
            "因何重有武陵期。传情每向馨香得，不语还应彼此知。",
            "只欲栏边安枕席，夜深闲共说相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 贼平后上高相公 ----------
    {
        "id": "xue-tao-13",
        "title": "贼平后上高相公",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "惊看天地白荒荒，瞥见青山旧夕阳。",
            "始信大威能照映，由来日月借生光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 送友人 ----------
    {
        "id": "xue-tao-14",
        "title": "送友人",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "七言绝句",
        "year": "约元和中",
        "source": "《全唐诗·卷八〇三》",
        "verse": [
            "水国蒹葭夜有霜，月寒山色共苍苍。",
            "谁言千里自今夕，离梦杳如关塞长。",
        ],
        "tijie": "此诗为薛涛送友之作，以蒹葭、月寒写离梦之远，清婉含蓄，为唐代女诗人七绝之名篇。",
        "notes": [
            ("水国", "水乡。"),
            ("蒹葭", "芦苇，用《秦风·蒹葭》意。"),
            ("苍苍", "深青色。"),
            ("离梦杳", "离梦遥远。"),
        ],
        "appreciation": "前二句「水国蒹葭夜有霜，月寒山色共苍苍」写水乡秋夜、蒹葭含霜、月寒山苍，以《蒹葭》意境起离思，清冷如画。后二句「谁言千里自今夕，离梦杳如关塞长」以反问写离梦之远胜千里、杳如关塞，将空间之远与梦之远叠合，情致深婉。薛涛为唐代女诗人冠冕，此诗与其《十离诗》之悲切异趣，转见清婉含蓄，七绝风调不让须眉。",
        "famous": [
            ("离梦杳如关塞长", "离梦名句，清婉深致。"),
        ],
        "sources": [
            "《全唐诗》卷八〇三",
            "《唐诗鉴赏辞典》薛涛条（上海辞书出版社，1983）",
        ],
    },
    # ---------- 15. 听僧吹芦管 ----------
    {
        "id": "xue-tao-15",
        "title": "听僧吹芦管",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "晓蝉呜咽暮莺愁，言语殷勤十指头。",
            "罢阅梵书聊一弄，散随金磬泥清秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 酬郭简州寄柑子 ----------
    {
        "id": "xue-tao-16",
        "title": "酬郭简州寄柑子",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "霜规不让黄金色，圆质仍含御史香。",
            "何处同声情最异，临川太守谢家郎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 上川主武元衡相国二首 ----------
    {
        "id": "xue-tao-17",
        "title": "上川主武元衡相国二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "落日重城夕雾收，玳筵雕俎荐诸侯。",
            "因令朗月当庭燎，不使珠帘下玉钩。",
            "东阁移尊绮席陈，貂簪龙节更宜春。",
            "军城画角三声歇，云幕初垂红烛新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 忆荔枝 ----------
    {
        "id": "xue-tao-18",
        "title": "忆荔枝",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "传闻象郡隔南荒，绛实丰肌不可忘。",
            "近有青衣连楚水，素浆还得类琼浆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 斛石山晓望寄吕侍御 ----------
    {
        "id": "xue-tao-19",
        "title": "斛石山晓望寄吕侍御",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "曦轮初转照仙扃，旋擘烟岚上窅冥。",
            "不得玄晖同指点，天涯苍翠漫青青。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 寄词 ----------
    {
        "id": "xue-tao-20",
        "title": "寄词",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "菌阁芝楼杳霭中，霞开深见玉皇宫。",
            "紫阳天上神仙客，称在人间立世功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 斛石山书事 ----------
    {
        "id": "xue-tao-21",
        "title": "斛石山书事",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "王家山水画图中，意思都卢粉墨容。",
            "今日忽登虚境望，步摇冠翠一千峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送姚员外 ----------
    {
        "id": "xue-tao-22",
        "title": "送姚员外",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "万条江柳早秋枝，袅地翻风色未衰。",
            "欲折尔来将赠别，莫教烟月两乡悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 酬祝十三秀才 ----------
    {
        "id": "xue-tao-23",
        "title": "酬祝十三秀才",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "浩思蓝山玉彩寒，冰囊敲碎楚金盘。",
            "诗家利器驰声久，何用春闱榜下看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 别李郎中 ----------
    {
        "id": "xue-tao-24",
        "title": "别李郎中",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "花落梧桐凤别凰，想登秦岭更凄凉。",
            "安仁纵有诗将赋，一半音词杂悼亡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送扶炼师 ----------
    {
        "id": "xue-tao-25",
        "title": "送扶炼师",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "锦浦归舟巫峡云，绿波迢递雨纷纷。",
            "山阴妙术人传久，也说将鹅与右军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 摩诃池赠萧中丞 ----------
    {
        "id": "xue-tao-26",
        "title": "摩诃池赠萧中丞",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "昔以多能佐碧油，今朝同泛旧仙舟。",
            "凄凉逝水颓波远，惟有碑泉咽不流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 乡思（用前韵） ----------
    {
        "id": "xue-tao-27",
        "title": "乡思（用前韵）",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "峨嵋山下水如油，怜我心同不系舟。",
            "何日片帆离锦浦，棹声齐唱发中流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 和李书记席上见赠 ----------
    {
        "id": "xue-tao-28",
        "title": "和李书记席上见赠",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "翩翩射策东堂秀，岂复相逢豁寸心。",
            "借问风光为谁丽，万条丝柳翠烟深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 棠梨花和李太尉 ----------
    {
        "id": "xue-tao-29",
        "title": "棠梨花和李太尉",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "吴均蕙圃移嘉木，正及东溪春雨时。",
            "日晚莺啼何所为，浅深红腻压繁枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 酬文使君 ----------
    {
        "id": "xue-tao-30",
        "title": "酬文使君",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "延英晓拜汉恩新，五马腾骧九陌尘。",
            "今日谢庭飞白雪，巴歌不复旧阳春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 酬吴随君 ----------
    {
        "id": "xue-tao-31",
        "title": "酬吴随君",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "支公别墅接花扃，买得前山总未经。",
            "入户剡溪云水满，高斋咫尺蹑青冥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 酬李校书 ----------
    {
        "id": "xue-tao-32",
        "title": "酬李校书",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "才游象外身虽远，学茂区中事易闻。",
            "自顾漳滨多病后，空瞻逸翮舞青云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 赋凌云寺二首 ----------
    {
        "id": "xue-tao-33",
        "title": "赋凌云寺二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "闻说凌云寺里苔，风高日近绝纤埃。",
            "横云点染芙蓉壁，似待诗人宝月来。",
            "闻说凌云寺里花，飞空绕磴逐江斜。",
            "有时锁得嫦娥镜，镂出瑶台五色霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 九日遇雨二首 ----------
    {
        "id": "xue-tao-34",
        "title": "九日遇雨二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "万里惊飙朔气深，江城萧索昼阴阴。",
            "谁怜不得登山去，可惜寒芳色似金。",
            "茱萸秋节佳期阻，金菊寒花满院香。",
            "神女欲来知有意，先令云雨暗池塘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 酬雍秀才贻巴峡图 ----------
    {
        "id": "xue-tao-35",
        "title": "酬雍秀才贻巴峡图",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "千叠云峰万顷湖，白波分去绕荆吴。",
            "感君识我枕流意，重示瞿塘峡口图。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 上王尚书 ----------
    {
        "id": "xue-tao-36",
        "title": "上王尚书",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "碧玉双幢白玉郎，初辞天帝下扶桑。",
            "手持云篆题新榜，十万人家春日长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 和刘宾客玉蕣 ----------
    {
        "id": "xue-tao-37",
        "title": "和刘宾客玉蕣",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "琼枝的皪露珊珊，欲折如披玉彩寒。",
            "闲拂朱房何所似，缘山偏映月轮残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 江边 ----------
    {
        "id": "xue-tao-38",
        "title": "江边",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "西风忽报雁双双，人世心形两自降。",
            "不为鱼肠有真诀，谁能梦梦立清江。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 送卢员外 ----------
    {
        "id": "xue-tao-39",
        "title": "送卢员外",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "玉垒山前风雪夜，锦官城外别离魂。",
            "信陵公子如相问，长向夷门感旧恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 题竹郎庙 ----------
    {
        "id": "xue-tao-40",
        "title": "题竹郎庙",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "竹郎庙前多古木，夕阳沈沈山更绿。",
            "何处江村有笛声，声声尽是迎郎曲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 赠苏十三中丞 ----------
    {
        "id": "xue-tao-41",
        "title": "赠苏十三中丞",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "洛阳陌上埋轮气，欲逐秋空击隼飞。",
            "今日芝泥检征诏，别须台外振霜威。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 和郭员外题万里桥 ----------
    {
        "id": "xue-tao-42",
        "title": "和郭员外题万里桥",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "万里桥头独越吟，知凭文字写愁心。",
            "细侯风韵兼前事，不止为舟也作霖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送郑眉州 ----------
    {
        "id": "xue-tao-43",
        "title": "送郑眉州",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "雨暗眉山江水流，离人掩袂立高楼。",
            "双旌千骑骈东陌，独有罗敷望上头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 江亭饯别（一作宴饯，一作江亭宴） ----------
    {
        "id": "xue-tao-44",
        "title": "江亭饯别（一作宴饯，一作江亭宴）",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "绿沼红泥物象幽，范汪兼倅李并州。",
            "离亭急管四更后，不见公车心独愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 海棠溪 ----------
    {
        "id": "xue-tao-45",
        "title": "海棠溪",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "春教风景驻仙霞，水面鱼身总带花。",
            "人世不思灵卉异，竞将红缬染轻沙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 采莲舟 ----------
    {
        "id": "xue-tao-46",
        "title": "采莲舟",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "风前一叶压荷蕖，解报新秋又得鱼。",
            "兔走乌驰人语静，满溪红袂棹歌初。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 菱荇沼 ----------
    {
        "id": "xue-tao-47",
        "title": "菱荇沼",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "水荇斜牵绿藻浮，柳丝和叶卧清流。",
            "何时得向溪头赏，旋摘菱花旋泛舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 金灯花 ----------
    {
        "id": "xue-tao-48",
        "title": "金灯花",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "阑边不见蘘蘘叶，砌下惟翻艳艳丛。",
            "细视欲将何物比，晓霞初叠赤城宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 春郊游眺寄孙处士二首 ----------
    {
        "id": "xue-tao-49",
        "title": "春郊游眺寄孙处士二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "低头久立向蔷薇，爱似零陵香惹衣。",
            "何事碧溪孙处士，百劳东去燕西飞。",
            "今朝纵目玩芳菲，夹缬笼裙绣地衣。",
            "满袖满头兼手把，教人识是看花归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 酬杨供奉法师见招 ----------
    {
        "id": "xue-tao-50",
        "title": "酬杨供奉法师见招",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "远水长流洁复清，雪窗高卧与云平。",
            "不嫌袁室无烟火，惟笑商山有姓名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 试新服裁制初成三首 ----------
    {
        "id": "xue-tao-51",
        "title": "试新服裁制初成三首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "紫阳宫里赐红绡，仙雾朦胧隔海遥。",
            "霜兔毳寒冰茧净，嫦娥笑指织星桥。",
            "九气分为九色霞，五灵仙驭五云车。",
            "春风因过东君舍，偷样人间染百花。",
            "长裾本是上清仪，曾逐群仙把玉芝。",
            "每到宫中歌舞会，折腰齐唱步虚词。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 寄张元夫 ----------
    {
        "id": "xue-tao-52",
        "title": "寄张元夫",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "前溪独立后溪行，鹭识朱衣自不惊。",
            "借问人间愁寂意，伯牙弦绝已无声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 酬辛员外折花见遗 ----------
    {
        "id": "xue-tao-53",
        "title": "酬辛员外折花见遗",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "青鸟东飞正落梅，衔花满口下瑶台。",
            "一枝为授殷勤意，把向风前旋旋开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 赠远二首 ----------
    {
        "id": "xue-tao-54",
        "title": "赠远二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "芙蓉新落蜀山秋，锦字开缄到是愁。",
            "闺阁不知戎马事，月高还上望夫楼。",
            "扰弱新蒲叶又齐，春深花落塞前溪。",
            "知君未转秦关骑，月照千门掩袖啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 秋泉 ----------
    {
        "id": "xue-tao-55",
        "title": "秋泉",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "冷色初澄一带烟，幽声遥泻十丝弦。",
            "长来枕上牵情思，不使愁人半夜眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 柳絮 ----------
    {
        "id": "xue-tao-56",
        "title": "柳絮",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "二月杨花轻复微，春风摇荡惹人衣。",
            "他家本是无情物，一任南飞又北飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 续嘉陵驿诗献武相国 ----------
    {
        "id": "xue-tao-57",
        "title": "续嘉陵驿诗献武相国",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "蜀门西更上青天，强为公歌蜀国弦。",
            "卓氏长卿称士女，锦江玉垒献山川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 段相国游武担寺，病不能从题寄 ----------
    {
        "id": "xue-tao-58",
        "title": "段相国游武担寺，病不能从题寄",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "消瘦翻堪见令公，落花无那恨东风。",
            "侬心犹道青春在，羞看飞蓬石镜中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 赠段校书 ----------
    {
        "id": "xue-tao-59",
        "title": "赠段校书",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "公子翩翩说校书，玉弓金勒紫绡裾。",
            "玄成莫便骄名誉，文采风流定不如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 十离诗·犬离主 ----------
    {
        "id": "xue-tao-60",
        "title": "十离诗·犬离主",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "驯扰朱门四五年，毛香足净主人怜。",
            "无端咬著亲情客，不得红丝毯上眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 十离诗·笔离手 ----------
    {
        "id": "xue-tao-61",
        "title": "十离诗·笔离手",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "越管宣毫始称情，红笺纸上撒花琼。",
            "都缘用久锋头尽，不得羲之手里擎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 十离诗·马离厩 ----------
    {
        "id": "xue-tao-62",
        "title": "十离诗·马离厩",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "雪耳红毛浅碧蹄，追风曾到日东西。",
            "为惊玉貌郎君坠，不得华轩更一嘶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 十离诗·鹦鹉离笼 ----------
    {
        "id": "xue-tao-63",
        "title": "十离诗·鹦鹉离笼",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "陇西独自一孤身，飞去飞来上锦茵。",
            "都缘出语无方便，不得笼中再唤人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 十离诗·燕离巢 ----------
    {
        "id": "xue-tao-64",
        "title": "十离诗·燕离巢",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "出入朱门未忍抛，主人常爱语交交。",
            "衔泥秽污珊瑚枕，不得梁间更垒巢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 十离诗·珠离掌 ----------
    {
        "id": "xue-tao-65",
        "title": "十离诗·珠离掌",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "皎洁圆明内外通，清光似照水晶宫。",
            "只缘一点玷相秽，不得终宵在掌中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 十离诗·鱼离池 ----------
    {
        "id": "xue-tao-66",
        "title": "十离诗·鱼离池",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "跳跃深池四五秋，常摇朱尾弄纶钩。",
            "无端摆断芙蓉朵，不得清波更一游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 十离诗·鹰离鞲 ----------
    {
        "id": "xue-tao-67",
        "title": "十离诗·鹰离鞲",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "爪利如锋眼似铃，平原捉兔称高情。",
            "无端窜向青云外，不得君王臂上擎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 十离诗·竹离亭 ----------
    {
        "id": "xue-tao-68",
        "title": "十离诗·竹离亭",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "蓊郁新栽四五行，常将劲节负秋霜。",
            "为缘春笋钻墙破，不得垂阴覆玉堂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 十离诗·镜离台 ----------
    {
        "id": "xue-tao-69",
        "title": "十离诗·镜离台",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "铸泻黄金镜始开，初生三五月裴回。",
            "为遭无限尘蒙蔽，不得华堂上玉台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 酬杜舍人 ----------
    {
        "id": "xue-tao-70",
        "title": "酬杜舍人",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "双鱼底事到侬家，扑手新诗片片霞。",
            "唱到白蘋洲畔曲，芙蓉空老蜀江花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 筹边楼 ----------
    {
        "id": "xue-tao-71",
        "title": "筹边楼",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "平临云鸟八窗秋，壮压西川四十州。",
            "诸将莫贪羌族马，最高层处见边头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 赠韦校书 ----------
    {
        "id": "xue-tao-72",
        "title": "赠韦校书",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "芸香误比荆山玉，那似登科甲乙年。",
            "澹地鲜风将绮思，飘花散蕊媚青天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 江月楼 ----------
    {
        "id": "xue-tao-73",
        "title": "江月楼",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "秋风仿佛吴江冷，鸥路参差夕阳影。垂虹纳纳卧谯门，",
            "雉堞眈眈俯渔艇。阳安小儿拍手笑，使君幻出江南景。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 西岩 ----------
    {
        "id": "xue-tao-74",
        "title": "西岩",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "凭阑却忆骑鲸客，把酒临风手自招。",
            "细雨声中停去马，夕阳影里乱鸣蜩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 罚赴边上武相公二首 ----------
    {
        "id": "xue-tao-75",
        "title": "罚赴边上武相公二首",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "萤在荒芜月在天，萤飞岂到月轮边。",
            "重光万里应相照，目断云霄信不传。",
            "按辔岭头寒复寒，微风细雨彻心肝。",
            "但得放儿归舍去，山水屏风永不看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 寄旧诗与元微之 ----------
    {
        "id": "xue-tao-76",
        "title": "寄旧诗与元微之",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "诗篇调态人皆有，细腻风光我独知。月下咏花怜暗澹，",
            "雨朝题柳为欹垂。长教碧玉藏深处，总向红笺写自随。",
            "老大不能收拾得，与君开似教男儿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 句 ----------
    {
        "id": "xue-tao-77",
        "title": "句",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "枝迎南北鸟，叶送往来风。（涛八九岁知声律。一日，",
            "其父郧指井梧曰：“庭除一古桐，耸干入云中。”涛应",
            "声云云，父愀然久之。后果入乐籍。别本载田洙遇薛涛，",
            "有落花联句、夜月联句、四时回文折齿曲，皆后人附会，",
            "兹概不录）",
            "第八百零四卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 赠杨蕴中 ----------
    {
        "id": "xue-tao-78",
        "title": "赠杨蕴中",
        "author": "薛涛",
        "poet_id": "xue-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "玉漏声长灯耿耿，东墙西墙时见影。",
            "月明窗外子规啼，忍使孤魂愁夜永。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]