# -*- coding: utf-8 -*-
"""
李忱卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 百丈山 ----------
    {
        "id": "li-chen-1",
        "title": "百丈山",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "大雄真迹枕危峦，梵宇层楼耸万般。日月每从肩上过，",
            "山河长在掌中看。仙峰不间三春秀，灵境何时六月寒。",
            "更有上方人罕到，暮钟朝磬碧云端。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 吊白居易 ----------
    {
        "id": "li-chen-2",
        "title": "吊白居易",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "缀玉联珠六十年，谁教冥路作诗仙。浮云不系名居易，",
            "造化无为字乐天。童子解吟长恨曲，胡儿能唱琵琶篇。",
            "文章已满行人耳，一度思卿一怆然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 幸华严寺 ----------
    {
        "id": "li-chen-3",
        "title": "幸华严寺",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "云散晴山几万重，烟收春色更冲融。帐殿出空登碧汉，",
            "遐川俯望色蓝笼。林光入户低韶景，岭气通宵展霁风。",
            "今日追游何所似，莫惭汉武赏汾中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 重阳锡宴群臣 ----------
    {
        "id": "li-chen-4",
        "title": "重阳锡宴群臣",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "款塞旋征骑，和戎委庙贤。倾心方倚注，叶力共安边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题泾县水西寺 ----------
    {
        "id": "li-chen-5",
        "title": "题泾县水西寺",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "大殿连云接爽溪，钟声还与鼓声齐。",
            "长安若问江南事，说道风光在水西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 瀑布联句 ----------
    {
        "id": "li-chen-6",
        "title": "瀑布联句",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "千岩万壑不辞劳，远看方知出处高。--黄檗",
            "溪涧岂能留得住，终归大海作波涛。--李忱",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 句 ----------
    {
        "id": "li-chen-7",
        "title": "句",
        "author": "李忱",
        "poet_id": "li-chen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "海岳宴咸通。",
            "七载秉钧调四序，一方狱市获来苏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]