# -*- coding: utf-8 -*-
"""
崔涂卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 101 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 琴曲歌辞·幽兰 ----------
    {
        "id": "cui-tu-1",
        "title": "琴曲歌辞·幽兰",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "幽植众能知，贞芳只暗持。自无君子佩，未是国香衰。",
            "白露沾长早，青春每到迟。不知当路草，芳馥欲何为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 秋夕送友人归吴 ----------
    {
        "id": "cui-tu-2",
        "title": "秋夕送友人归吴",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "离心醉岂欢，把酒强相宽。世路须求达，还家亦未安。",
            "旅程愁算远，江月坐吟残。莫羡扁舟兴，功成去不难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 长安逢江南僧 ----------
    {
        "id": "cui-tu-3",
        "title": "长安逢江南僧",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "孤云无定踪，忽到又相逢。说尽天涯事，听残上国钟。",
            "问人寻寺僻，乞食过街慵。忆到曾栖处，开门对数峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 晚次修路僧 ----------
    {
        "id": "cui-tu-4",
        "title": "晚次修路僧",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "平尽不平处，尚嫌功未深。应难将世路，便得称师心。",
            "高鸟下残照，白烟生远林。更闻清磬发，聊喜缓尘襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 湖外送友人游边 ----------
    {
        "id": "cui-tu-5",
        "title": "湖外送友人游边",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "我泛潇湘浦，君行指塞云。两乡天外隔，一径渡头分。",
            "雨暗江花老，笳愁陇月曛。不堪来去雁，迢递思离群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 读段太尉碑 ----------
    {
        "id": "cui-tu-6",
        "title": "读段太尉碑",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "愤激计潜成，临危岂顾生。只空持一笏，便欲碎长鲸。",
            "国已酬徽烈，家犹耸义声。不知青史上，谁可计功名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 夕次洛阳道中 ----------
    {
        "id": "cui-tu-7",
        "title": "夕次洛阳道中",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "秋风吹故城，城下独吟行。高树鸟已息，古原人尚耕。",
            "流年川暗度，往事月空明。不复叹岐路，马前尘夜生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 读方干诗因怀别业 ----------
    {
        "id": "cui-tu-8",
        "title": "读方干诗因怀别业",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "把君诗一吟，万里见君心。华发新知少，沧洲旧隐深。",
            "潮冲虚阁上，山入暮窗沈。忆宿高斋夜，庭枝识海禽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 题嵩阳隐者 ----------
    {
        "id": "cui-tu-9",
        "title": "题嵩阳隐者",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "四十年高梦，生涯指一丘。无人同久住，有鹤对冥修。",
            "草杂芝田出，泉和石髓流。更嫌庭树老，疑是世间秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 友人问卜见招 ----------
    {
        "id": "cui-tu-10",
        "title": "友人问卜见招",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "何必问蓍龟，行藏自可期。但逢公道日，即是命通时。",
            "乐善知无厌，操心幸不欺。岂能花下泪，长似去年垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 江行晚望 ----------
    {
        "id": "cui-tu-11",
        "title": "江行晚望",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "木落曙江晴，寒郊极望平。孤舟三楚去，万里独吟行。",
            "鸟占横查立，人当故里耕。十年来复去，不觉二毛生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 巫山庙 ----------
    {
        "id": "cui-tu-12",
        "title": "巫山庙",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "双黛俨如嚬，应伤故国春。江山非旧主，云雨是前身。",
            "梦觉传词客，灵犹福楚人。不知千载后，何处又为神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 秋夕与友人话别 ----------
    {
        "id": "cui-tu-13",
        "title": "秋夕与友人话别",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "怀君非一夕，此夕倍堪悲。华发犹漂泊，沧洲又别离。",
            "冷禽栖不定，衰叶堕无时。况值干戈隔，相逢未可期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 与友人同怀江南别业 ----------
    {
        "id": "cui-tu-14",
        "title": "与友人同怀江南别业",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "因君话故国，此夕倍依依。旧业临秋水，何人在钓矶。",
            "浮名如纵得，沧海亦终归。却是风尘里，如何便息机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 苦吟 ----------
    {
        "id": "cui-tu-15",
        "title": "苦吟",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "朝吟复暮吟，只此望知音。举世轻孤立，何人念苦心。",
            "他乡无旧识，落日羡归禽。况住寒江上，渔家似故林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 春日郊居酬友人见贻 ----------
    {
        "id": "cui-tu-16",
        "title": "春日郊居酬友人见贻",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "荒斋原上掩，不出动经旬。忽觉草木变，始知天地春。",
            "方期五字达，未厌一箪贫。丽句劳相勉，余非乐钓纶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 问卜 ----------
    {
        "id": "cui-tu-17",
        "title": "问卜",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "承家望一名，几欲问君平。自小非无志，何年即有成。",
            "岂能长失路，争忍学归耕。不拟逢昭代，悠悠过此生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 蜀城春 ----------
    {
        "id": "cui-tu-18",
        "title": "蜀城春",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "天涯憔悴身，一望一沾巾。在处有芳草，满城无故人。",
            "怀才皆得路，失计自伤春。清镜不能照，鬓毛愁更新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送道士于千龄游南岳 ----------
    {
        "id": "cui-tu-19",
        "title": "送道士于千龄游南岳",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "物外与谁期，人间又别离。四方多事日，高岳独游时。",
            "猿狖潇湘树，烟波屈宋祠。无因陪此去，空惜鬓将衰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 入蜀赴举秋夜与先生话别 ----------
    {
        "id": "cui-tu-20",
        "title": "入蜀赴举秋夜与先生话别",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "欲怆峨嵋别，中宵寝不能。听残池上雨，吟尽枕前灯。",
            "失计方期隐，修心未到僧。云门一万里，应笑又担簦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 春晚怀进士韦澹 ----------
    {
        "id": "cui-tu-21",
        "title": "春晚怀进士韦澹",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "故里花应尽，江楼梦尚残。半生吟欲过，一命达何难。",
            "特立珪无玷，相思草有兰。二年春怅望，不似在长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 言怀 ----------
    {
        "id": "cui-tu-22",
        "title": "言怀",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "干时虽苦节，趋世且无机。及觉知音少，翻疑所业非。",
            "青云如不到，白首亦难归。所以沧江上，年年别钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 秋夜兴上人别 ----------
    {
        "id": "cui-tu-23",
        "title": "秋夜兴上人别",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "常时岂不别，此别异常情。南国初闻雁，中原未息兵。",
            "暗蛩侵语歇，疏磬入吟清。曾听无生说，辞师话此行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 感花 ----------
    {
        "id": "cui-tu-24",
        "title": "感花",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "绣轭香鞯夜不归，少年争惜最红枝。",
            "东风一阵黄昏雨，又到繁华梦觉时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 秋宿天彭僧舍 ----------
    {
        "id": "cui-tu-25",
        "title": "秋宿天彭僧舍",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "身世两相惜，秋云每独兴。难将尘界事，话向雪山僧。",
            "力善知谁许，归耕又未能。此怀平不得，挑尽草堂灯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 秋夜僧舍闻猿 ----------
    {
        "id": "cui-tu-26",
        "title": "秋夜僧舍闻猿",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "哀猿听未休，禅景夜方幽。暂得同僧静，那能免客愁。",
            "影摇云外树，声褭月中秋。曾向巴江宿，当时泪亦流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 过昭君故宅 ----------
    {
        "id": "cui-tu-27",
        "title": "过昭君故宅",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "以色静胡尘，名还异众嫔。免劳征战力，无愧绮罗身。",
            "骨竟埋青冢，魂应怨画人。不堪逢旧宅，寥落对江滨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 过洛阳故城 ----------
    {
        "id": "cui-tu-28",
        "title": "过洛阳故城",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "三十世皇都，萧条是霸图。片墙看破尽，遗迹渐应无。",
            "野径通荒苑，高槐映远衢。独吟人不问，清冷自呜呜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 秋夕与友人同会 ----------
    {
        "id": "cui-tu-29",
        "title": "秋夕与友人同会",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "章句积微功，星霜二十空。僻应如我少，吟喜得君同。",
            "月上僧归后，诗成客梦中。更闻栖鹤警，清露滴青松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 春日登吴门 ----------
    {
        "id": "cui-tu-30",
        "title": "春日登吴门",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "故国望不见，愁襟难暂开。春潮映杨柳，细雨入楼台。",
            "静少人同到，晴逢雁正来。长安远于日，搔首独徘徊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 湘中秋怀迁客 ----------
    {
        "id": "cui-tu-31",
        "title": "湘中秋怀迁客",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "兰杜晓香薄，汀洲夕露繁。并闻燕塞雁，独立楚人村。",
            "雾散孤城上，滩回曙枕喧。不堪逢贾傅，还欲吊湘沅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 南山旅舍与故人别（一作商山道中） ----------
    {
        "id": "cui-tu-32",
        "title": "南山旅舍与故人别（一作商山道中）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "一日又将暮，一年看即残。病知新事少，老别旧交难。",
            "山尽路犹险，雨馀春却寒。那堪试回首，烽火是长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 东林愿禅师院 ----------
    {
        "id": "cui-tu-33",
        "title": "东林愿禅师院",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "与世渐无缘，身心独了然。讲销林下日，腊长定中年。",
            "磬绝朝斋后，香焚古寺前。非因送小朗，不到虎谿边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 孤雁 ----------
    {
        "id": "cui-tu-34",
        "title": "孤雁",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "湘浦离应晚，边城去已孤。如何万里计，只在一枝芦。",
            "迥起波摇楚，寒栖月映蒲。不知天畔侣，何处下平芜。",
            "几行归去尽，片影独何之。暮雨相呼失，寒塘独下迟。",
            "渚云低暗度，关月冷遥随。未必逢矰缴，孤飞自可疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 寄青城山颢禅师 ----------
    {
        "id": "cui-tu-35",
        "title": "寄青城山颢禅师",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "怀师不可攀，师往杳冥间。林下谁闻法，尘中只见山。",
            "终年人不到，尽日鸟空还。曾听无生说，应怜独未还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 秋夕与王处士话别 ----------
    {
        "id": "cui-tu-36",
        "title": "秋夕与王处士话别",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "微灯照寂寥，此夕正迢迢。丹桂得已晚，故山归尚遥。",
            "虫声移暗壁，月色动寒条。此去如真隐，期君试一瓢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 秋日犍为道中（一作途中感怀） ----------
    {
        "id": "cui-tu-37",
        "title": "秋日犍为道中（一作途中感怀）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "久客厌岐路，出门吟且悲。平生未到处，落日独行时。",
            "芳草不长绿，故人无重期。那堪更南渡，乡国已天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 送僧归江东（一作岐下送蒙上人归天台） ----------
    {
        "id": "cui-tu-38",
        "title": "送僧归江东（一作岐下送蒙上人归天台）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "坐彻秦城夏，行登越客船。去留那有著，语默不离禅。",
            "叶拥临关路，霞明近海天。更寻同社侣，应得虎溪边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 喜友人及第 ----------
    {
        "id": "cui-tu-39",
        "title": "喜友人及第",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "孤吟望至公，已老半生中。不有同人达，兼疑此道穷。",
            "只应才自薄，岂是命难通。尚激抟溟势，期君借北风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 上巳日永崇里言怀 ----------
    {
        "id": "cui-tu-40",
        "title": "上巳日永崇里言怀",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "未敢分明赏物华，十年如见梦中花。",
            "游人过尽衡门掩，独自凭栏到日斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 送僧归天竺 ----------
    {
        "id": "cui-tu-41",
        "title": "送僧归天竺",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "忽忆曾栖处，千峰近沃州。别来秦树老，归去海门秋。",
            "汲带寒汀月，禅邻贾客舟。遥思清兴惬，不厌石林幽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 牛渚夜泊 ----------
    {
        "id": "cui-tu-42",
        "title": "牛渚夜泊",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "烟老石矶平，袁郎夜泛情。数吟人不遇，千古月空明。",
            "人事年年别，春潮日日生。无因逢谢尚，风物自凄清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送友人归江南 ----------
    {
        "id": "cui-tu-43",
        "title": "送友人归江南",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "渚田芳草遍，共忆故山春。独往沧洲暮，相看白发新。",
            "定过林下寺，应见社中人。只恐东归后，难将鸥鸟亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 过陶征君隐居 ----------
    {
        "id": "cui-tu-44",
        "title": "过陶征君隐居",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "陶令昔居此，弄琴遗世荣。田园三亩绿，轩冕一铢轻。",
            "衰柳自无主，白云犹可耕。不随陵谷变，应只有高名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 江上旅泊 ----------
    {
        "id": "cui-tu-45",
        "title": "江上旅泊",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "汀洲一夜泊，久客半连樯。尽说逢秋色，多同忆故乡。",
            "孤冈生晚烧，独树隐回塘。欲问东归路，遥知隔渺茫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 灞上 ----------
    {
        "id": "cui-tu-46",
        "title": "灞上",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "长安名利路，役役古由今。征骑少闲日，绿杨无旧阴。",
            "水侵秦甸阔，草接汉陵深。紫阁曾过处，依稀白鸟沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 寄舅 ----------
    {
        "id": "cui-tu-47",
        "title": "寄舅",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "中朝轩冕内，久绝甯家亲。白社同孤立，青云独并伸。",
            "致君期折槛，举职在埋轮。须信尧庭草，犹能指佞人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 赠休粮僧 ----------
    {
        "id": "cui-tu-48",
        "title": "赠休粮僧",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "闻钟独不斋，何事更关怀。静少人过院，闲从草上阶。",
            "生台无鸟下，石路有云埋。为忆禅中旧，时犹梦百崖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 题绝岛山寺 ----------
    {
        "id": "cui-tu-49",
        "title": "题绝岛山寺",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "绝岛跨危栏，登临到此难。夕阳高鸟过，疏雨一钟残。",
            "骇浪摇空阔，灵山厌渺漫。那堪更回首，乡树隔云端。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 读侯道华真人传 ----------
    {
        "id": "cui-tu-50",
        "title": "读侯道华真人传",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "汉皇轻万乘，方士说三丹。不得修心要，翻知出世难。",
            "茂陵春竟绿，金掌曙空寒。何似先生去，翩翩逐彩鸾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 残花 ----------
    {
        "id": "cui-tu-51",
        "title": "残花",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "迟迟傍晓阴，昨夜色犹深。毕竟终须落，堪悲古与今。",
            "明年何处见，尽日此时心。蜂蝶无情极，残香更不寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 题兴善寺隋松院与人期不至 ----------
    {
        "id": "cui-tu-52",
        "title": "题兴善寺隋松院与人期不至",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "青青伊涧松，移植在莲宫。藓色前朝雨，秋声半夜风。",
            "长闲应未得，暂赏亦难同。不及禅栖者，相看老此中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 樵者 ----------
    {
        "id": "cui-tu-53",
        "title": "樵者",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "行山行采薇，闲翦蕙为衣。避世嫌山浅，逢人说姓稀。",
            "有时还独醉，何处掩衡扉。莫看棋终局，溪风晚待归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 南涧耕叟 ----------
    {
        "id": "cui-tu-54",
        "title": "南涧耕叟",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "年年南涧滨，力尽志犹存。雨雪朝耕苦，桑麻岁计贫。",
            "战添丁壮役，老忆太平春。见说经荒后，田园半属人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 春日闲居忆江南旧业 ----------
    {
        "id": "cui-tu-55",
        "title": "春日闲居忆江南旧业",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "杜门朝复夕，岂是解谋身。梦不离泉石，林唯称隐沦。",
            "渐谙浮世事，转忆故山春。南国水风暖，又应生白蘋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 屈原庙 ----------
    {
        "id": "cui-tu-56",
        "title": "屈原庙",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "谗胜祸难防，沈冤信可伤。本图安楚国，不是怨怀王。",
            "庙古碑无字，洲晴蕙有香。独醒人尚笑，谁与奠椒浆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 宿庐山绝顶山舍 ----------
    {
        "id": "cui-tu-57",
        "title": "宿庐山绝顶山舍",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "一磴出林端，千峰次第看。长闲如未遂，暂到亦应难。",
            "谷树云埋老，僧窗瀑影寒。自嫌心不达，向此梦长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 王逸人隐居 ----------
    {
        "id": "cui-tu-58",
        "title": "王逸人隐居",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "一径入千岑，幽人许重寻。不逢秦世乱，未觉武陵深。",
            "石转生寒色，云归带夕阴。却愁危坐久，看尽暝栖禽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 申州道中 ----------
    {
        "id": "cui-tu-59",
        "title": "申州道中",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "风紧日凄凄，乡心向此迷。水分平楚阔，山接故关低。",
            "客路缘烽火，人家厌鼓鼙。那堪独驰马，江树穆陵西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 江上怀翠微寺空上人 ----------
    {
        "id": "cui-tu-60",
        "title": "江上怀翠微寺空上人",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "旅泛本无定，相逢那可期。空怀白阁夜，未答碧云诗。",
            "暮雨潮生早，春寒雁到迟。所思今不见，乡国正天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 秋宿鹤林寺 ----------
    {
        "id": "cui-tu-61",
        "title": "秋宿鹤林寺",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "步步入林中，山穷意未穷。偏逢僧话久，转与鹤栖同。",
            "烛焰风销尽，兰条露湿空。又须从此别，江上正秋鸿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 远望 ----------
    {
        "id": "cui-tu-62",
        "title": "远望",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "长为乡思侵，望极即沾襟。不是前山色，能伤愁客心。",
            "平芜连海尽，独树隐云深。况复斜阳外，分明有去禽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 秋晚书怀 ----------
    {
        "id": "cui-tu-63",
        "title": "秋晚书怀",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "看看秋色晚，又是出门时。白发生非早，青云去自迟。",
            "梦唯怀上国，迹不到他岐。以此坚吾道，还无愧已知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 途中秋晚送友人归江南 ----------
    {
        "id": "cui-tu-64",
        "title": "途中秋晚送友人归江南",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "又指烟波算路岐，此生多是厌羁离。正逢摇落仍须别，",
            "不待登临已合悲。里巷半空兵过后，水云初冷雁来时。",
            "扁舟未得如君去，空向沧江梦所思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 己亥岁感事 ----------
    {
        "id": "cui-tu-65",
        "title": "己亥岁感事",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "正闻青犊起葭萌，又报黄巾犯汉营。岂是将皆无上略，",
            "直疑天自弃苍生。瓜沙旧戍犹传檄，吴楚新春已废耕。",
            "见说圣君能仄席，不知谁是请长缨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 金陵晚眺（一作怀古） ----------
    {
        "id": "cui-tu-66",
        "title": "金陵晚眺（一作怀古）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "苇声骚屑水天秋，吟对金陵古渡头。千古是非输蝶梦，",
            "一轮风雨属渔舟。若无仙分应须老，幸有归山即合休。",
            "何必登临更惆怅，比来身世只如浮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 过长江贾岛主簿旧厅 ----------
    {
        "id": "cui-tu-67",
        "title": "过长江贾岛主簿旧厅",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "雕琢文章字字精，我经此处倍伤情。身从谪宦方沾禄，",
            "才被槌埋更有声。过县已无曾识吏，到厅空见旧题名。",
            "长江一曲年年水，应为先生万古清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 途中感怀寄青城李明府 ----------
    {
        "id": "cui-tu-68",
        "title": "途中感怀寄青城李明府",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "鳞鬣催残志未休，壮心翻是此身雠。并闻寒雨多因夜，",
            "不得乡书又到秋。耕钓旧交吟好忆，雪霜危栈去堪愁。",
            "如何只是三年别，君著朱衣我白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 夏日书怀寄道友 ----------
    {
        "id": "cui-tu-69",
        "title": "夏日书怀寄道友",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "达即匡邦退即耕，是非何足挠平生。终期道向希夷得，",
            "未省心因宠辱惊。峰转暂无当户影，雉飞时有隔林声。",
            "十年惟悟吟诗句，待得中原欲铸兵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 和进士张曙闻雁见寄 ----------
    {
        "id": "cui-tu-70",
        "title": "和进士张曙闻雁见寄",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "断行哀响递相催，争趁高秋作恨媒。云外关山闻独去，",
            "渡头风雨见初来。也知榆塞寒须别，莫恋蘋汀暖不回。",
            "试向富春江畔过，故园犹合有池台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 鹦鹉洲即事（一作眺望） ----------
    {
        "id": "cui-tu-71",
        "title": "鹦鹉洲即事（一作眺望）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "怅望春襟郁未开，重吟鹦鹉益堪哀。曹瞒尚不能容物，",
            "黄祖何曾解爱才。幽岛暖闻燕雁去，晓江晴觉蜀波来。",
            "何人正得风涛便，一点轻帆万里回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 读留侯传 ----------
    {
        "id": "cui-tu-72",
        "title": "读留侯传",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "覆楚雠韩势有馀，男儿遭遇更难如。偶成汉室千年业，",
            "只读圯桥一卷书。翻把壮心轻尺组，却烦商皓正皇储。",
            "若能终始匡天子，何必□□□□□。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 赤壁怀古 ----------
    {
        "id": "cui-tu-73",
        "title": "赤壁怀古",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "汉室河山鼎势分，勤王谁肯顾元勋。不知征伐由天子，",
            "唯许英雄共使君。江上战馀陵是谷，渡头春在草连云。",
            "分明胜败无寻处，空听渔歌到夕曛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 东晋 ----------
    {
        "id": "cui-tu-74",
        "title": "东晋",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "五陵豪侠笑为儒，将为儒生只读书。",
            "看取不成投笔后，谢安功业复何如。",
            "秦国金陵王气全，一龙正道始东迁。",
            "兴亡竟不关人事，虚倚长淮五百年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 春夕 ----------
    {
        "id": "cui-tu-75",
        "title": "春夕",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "水流花谢两无情，送尽东风过楚城。胡蝶梦中家万里，",
            "子规枝上月三更。故园书动经年绝，华发春唯满镜生。",
            "自是不归归便得，五湖烟景有谁争。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 涧松 ----------
    {
        "id": "cui-tu-76",
        "title": "涧松",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "寸寸凌霜长劲条，路人犹笑未干霄。",
            "南园桃李虽堪羡，争奈春残又寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 湘中弦 ----------
    {
        "id": "cui-tu-77",
        "title": "湘中弦",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "苍山遥遥江潾潾，路傍老尽没闲人。",
            "王孙不见草空绿，惆怅渡头春复春。",
            "烟愁雨细云冥冥，杜兰香老三湘清。",
            "故山望断不知处，鶗鴂隔花时一声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 续纪汉武（一作读汉武内传） ----------
    {
        "id": "cui-tu-78",
        "title": "续纪汉武（一作读汉武内传）",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "分明三鸟下储胥，一觉钧天梦不如。",
            "争那白头方士到，茂陵红叶已萧疏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 陇上逢江南故人 ----------
    {
        "id": "cui-tu-79",
        "title": "陇上逢江南故人",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "三声戍角边城暮，万里乡心塞草春。",
            "莫学少年轻远别，陇关西少向东人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 夷陵夜泊 ----------
    {
        "id": "cui-tu-80",
        "title": "夷陵夜泊",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "家依楚塞穷秋别，身逐孤舟万里行。",
            "一曲巴歌半江月，便应消得二毛生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 橹声 ----------
    {
        "id": "cui-tu-81",
        "title": "橹声",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "烟外桡声远，天涯幽梦回。争知江上客，不是故乡来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 海棠图 ----------
    {
        "id": "cui-tu-82",
        "title": "海棠图",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "海棠花底三年客，不见海棠花盛开。",
            "却向江南看图画，始惭虚到蜀城来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 云 ----------
    {
        "id": "cui-tu-83",
        "title": "云",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "得路直为霖济物，不然闲共鹤忘机。",
            "无端却向阳台畔，长送襄王暮雨归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 过二妃庙 ----------
    {
        "id": "cui-tu-84",
        "title": "过二妃庙",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "残阳楚水畔，独吊舜时人。不及庙前草，至今江上春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 送友人 ----------
    {
        "id": "cui-tu-85",
        "title": "送友人",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "登高迎送远，春恨并依依。不得沧洲信，空看白鹤归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 声 ----------
    {
        "id": "cui-tu-86",
        "title": "声",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "欢戚犹来恨不平，此中高下本无情。",
            "韩娥绝唱唐衢哭，尽是人间第一声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 放鹧鸪 ----------
    {
        "id": "cui-tu-87",
        "title": "放鹧鸪",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "秋入池塘风露微，晓开笼槛看初飞。",
            "满身金翠画不得，无限烟波何处归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 泉 ----------
    {
        "id": "cui-tu-88",
        "title": "泉",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "远辞岩窦泻潺潺，静拂云根别故山。",
            "可惜寒声留不得，旋添波浪向人间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 巫山旅别 ----------
    {
        "id": "cui-tu-89",
        "title": "巫山旅别",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "五千里外三年客，十二峰前一望秋。",
            "无限别魂招不得，夕阳西下水东流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 幽兰 ----------
    {
        "id": "cui-tu-90",
        "title": "幽兰",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "幽植众宁知，芬芳只暗持。自无君子佩，未是国香衰。",
            "白露沾长早，春风到每迟。不如当路草，芬馥欲何为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 读庾信集 ----------
    {
        "id": "cui-tu-91",
        "title": "读庾信集",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "四朝十帝尽风流，建业长安两醉游。",
            "唯有一篇杨柳曲，江南江北为君愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 过绣岭宫 ----------
    {
        "id": "cui-tu-92",
        "title": "过绣岭宫",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "古殿春残绿野阴，上皇曾此驻泥金。三城帐属升平梦，",
            "一曲铃关怅望心。苑路暗迷香辇绝，缭垣秋断草烟深。",
            "前朝旧物东流在，犹为年年下翠岑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 巴山道中除夜书怀 ----------
    {
        "id": "cui-tu-93",
        "title": "巴山道中除夜书怀",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "迢递三巴路，羁危万里身。乱山残雪夜，孤烛异乡春。",
            "渐与骨肉远，转于僮仆亲。那堪正漂泊，明日岁华新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 题净众寺古松 ----------
    {
        "id": "cui-tu-94",
        "title": "题净众寺古松",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷93》",
        "verse": [
            "百尺森疏倚梵台，昔人谁见此初栽。故园未有偏堪恋，",
            "浮世如闲即合来。天暝岂分苍翠色，岁寒应识栋梁材。",
            "清阴可惜不驻得，归去暮城空首回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 折杨柳 ----------
    {
        "id": "cui-tu-95",
        "title": "折杨柳",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "朝朝车马如蓬转，处处江山待客归。",
            "若使人间少离别，杨花应合过春飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 七夕 ----------
    {
        "id": "cui-tu-96",
        "title": "七夕",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷95》",
        "verse": [
            "年年七夕渡瑶轩，谁道秋期有泪痕。",
            "自是人间一周岁，何妨天上只黄昏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 泛楚江 ----------
    {
        "id": "cui-tu-97",
        "title": "泛楚江",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷96》",
        "verse": [
            "九重城外家书远，百里洲前客棹还。",
            "金印碧幢如见问，一生安稳是长闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 初过汉江 ----------
    {
        "id": "cui-tu-98",
        "title": "初过汉江",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷97》",
        "verse": [
            "襄阳好向岘亭看，人物萧条值岁阑。",
            "为报习家多置酒，夜来风雪过江寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 题授阳镇路 ----------
    {
        "id": "cui-tu-99",
        "title": "题授阳镇路",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷98》",
        "verse": [
            "越鸟巢边溪路断，秦人耕处洞门开。",
            "小桃花发春风起，千里江山一梦回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 初识梅花 ----------
    {
        "id": "cui-tu-100",
        "title": "初识梅花",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷99》",
        "verse": [
            "江北不如南地暖，江南好断北人肠。",
            "燕脂桃颊梨花粉，共作寒梅一面妆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 江雨望花 ----------
    {
        "id": "cui-tu-101",
        "title": "江雨望花",
        "author": "崔涂",
        "poet_id": "cui-tu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷100》",
        "verse": [
            "细雨满江春水涨，好风留客野梅香。",
            "避秦不是无归意，一度逢花一断肠。",
            "第六百八十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]