# -*- coding: utf-8 -*-
"""
张谔卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 百子池 ----------
    {
        "id": "zhang-e-1",
        "title": "百子池",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "旧闻百子汉家池，汉家渌水今逶迤。宫女厌镜笑窥池，",
            "身前影后不相见，无数容华空自知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 东封山下宴群臣 ----------
    {
        "id": "zhang-e-2",
        "title": "东封山下宴群臣",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "万里扈封峦，群公遇此欢。幔城连夜静，霜仗满空寒。",
            "辇路宵烟合，旌门晓月残。明朝陪圣主，山下礼圆坛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 三日岐王宅 ----------
    {
        "id": "zhang-e-3",
        "title": "三日岐王宅",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "玉女贵妃生，嫛婗始发声。金盆浴未了，绷子绣初成。",
            "翡翠雕芳缛，真珠帖小缨。何时学健步，斗取落花轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 满月 ----------
    {
        "id": "zhang-e-4",
        "title": "满月",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "社金流茂祉，庭玉表奇才。竹似因谈植，兰疑入梦栽。",
            "乌将八子去，凤逐九雏来。今夜明珠色，当随满月开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 岐王山亭 ----------
    {
        "id": "zhang-e-5",
        "title": "岐王山亭",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "王家傍绿池，春色正相宜。岂有楼台好，兼看草树奇。",
            "石榴天上叶，椰子日南枝。出入千门里，年年乐未移。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 岐王席上咏美人 ----------
    {
        "id": "zhang-e-6",
        "title": "岐王席上咏美人",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "半额画双蛾，盈盈烛下歌。玉杯寒意少，金屋夜情多。",
            "香艳王分帖，裙娇敕赐罗。平阳莫相妒，唤出不如他。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 还京（一作广陵送别宋员外佐越郑舍人还京一作韦述诗） ----------
    {
        "id": "zhang-e-7",
        "title": "还京（一作广陵送别宋员外佐越郑舍人还京一作韦述诗）",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "朱绂临秦望，皇华赴洛桥。文章南渡越，书奏北归朝。",
            "树入江云尽，城衔海月遥。秋风将客思，川上晚萧萧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 赠吏部孙员外济 ----------
    {
        "id": "zhang-e-8",
        "title": "赠吏部孙员外济",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "天子爱贤才，星郎入拜来。明光朝半下，建礼直初回。",
            "名带含香发，文随绮幕开。披云自有镜，从此照仙台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送李著作倅杭州 ----------
    {
        "id": "zhang-e-9",
        "title": "送李著作倅杭州",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "辍史空三署，题舆佐一方。祖筵开霁景，征陌直朝光。",
            "水陆风烟隔，秦吴道路长。伫闻敷善政，邦国咏惟康。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 九日 ----------
    {
        "id": "zhang-e-10",
        "title": "九日",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "秋来林下不知春，一种佳游事也均。绛叶从朝飞著夜，",
            "黄花开日未成旬。将曛陌树频惊鸟，半醉归途数问人。",
            "城远登高并九日，茱萸凡作几年新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 延平门高斋亭子应岐王教 ----------
    {
        "id": "zhang-e-11",
        "title": "延平门高斋亭子应岐王教",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "花源药屿凤城西，翠幕纱窗莺乱啼。昨夜蒲萄初上架，",
            "今朝杨柳半垂堤。片片仙云来渡水，双双燕子共衔泥。",
            "请语东风催后骑，并将歌舞向前谿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 九日宴 ----------
    {
        "id": "zhang-e-12",
        "title": "九日宴",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "秋叶风吹黄飒飒，晴云日照白鳞鳞。",
            "归来得问茱萸女，今日登高醉几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 句 ----------
    {
        "id": "zhang-e-13",
        "title": "句",
        "author": "张谔",
        "poet_id": "zhang-e",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "天上姮娥遥解意，偏教月向踏歌明。（月夜看美人踏歌）",
            "共待山头明月上，照君行棹出长川。（玩山月送百九）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]