# -*- coding: utf-8 -*-
"""
韦承庆卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 8 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 横吹曲辞·折杨柳 ----------
    {
        "id": "wei-cheng-qing-1",
        "title": "横吹曲辞·折杨柳",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "万里边城地，三春杨柳节。叶似镜中眉，花如关外雪。",
            "征人远乡思，倡妇高楼别。不忍掷年华，含情寄攀折。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 折杨柳 ----------
    {
        "id": "wei-cheng-qing-2",
        "title": "折杨柳",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "万里边城地，三春杨柳节。叶似镜中眉，花如关外雪。",
            "征人远乡思，倡妇高楼别。不忍掷年华，含情寄攀折。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寒食应制 ----------
    {
        "id": "wei-cheng-qing-3",
        "title": "寒食应制",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "凤城春色晚，龙禁早晖通。旧火收槐燧，馀寒入桂宫。",
            "莺啼正隐叶，鸡斗始开笼。蔼蔼瑶山满，仙歌始乐风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 凌朝浮江旅思（一作马周诗） ----------
    {
        "id": "wei-cheng-qing-4",
        "title": "凌朝浮江旅思（一作马周诗）",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "天晴上初日，春水送孤舟。山远疑无树，潮平似不流。",
            "岸花开且落，江鸟没还浮。羁望伤千里，长歌遣四愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 直中书省 ----------
    {
        "id": "wei-cheng-qing-5",
        "title": "直中书省",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "清切凤凰池，扶疏鸡树枝。唯应集鸾鹭，何为宿羁雌。",
            "大造乾坤辟，深恩雨露垂。昆蚑皆含养，驽骀亦驱驰。",
            "木偶翻为用，芝泥忽滥窥。九思空自勉，五字本无施。",
            "徒喜逢千载，何阶答二仪。萤光向日尽，蚊力负山疲。",
            "禁宇庭除阔，闲宵钟箭移。暗花临户发，残月下帘欹。",
            "白发随年改，丹心为主披。命将时共泰，言与行俱危。",
            "寄谢巢由客，尧年正在斯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 南行别弟 ----------
    {
        "id": "wei-cheng-qing-6",
        "title": "南行别弟",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "澹澹长江水，悠悠远客情。落花相与恨，到地一无声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 南中咏雁诗（一作于季子诗，题作南行别弟） ----------
    {
        "id": "wei-cheng-qing-7",
        "title": "南中咏雁诗（一作于季子诗，题作南行别弟）",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "万里人南去，三春雁北飞。不知何岁月，得与尔同归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 江楼 ----------
    {
        "id": "wei-cheng-qing-8",
        "title": "江楼",
        "author": "韦承庆",
        "poet_id": "wei-cheng-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "独酌芳春酒，登楼已半曛。谁惊一行雁，冲断过江云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]