# -*- coding: utf-8 -*-
"""
刘象卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 早春池亭独游三首 ----------
    {
        "id": "liu-xiang-1",
        "title": "早春池亭独游三首",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "春意送残腊，春晴融小洲。蒲茸才簇岸，柳颊已遮楼。",
            "便有杯觞兴，可据羁旅愁。凫鹥亦相狎，尽日戏清流。",
            "清流环绿筱，清景媚虹桥。莺刷初迁羽，莎拳拟拆苗。",
            "细沙擢暖岸，淑景动和飙。倍忆同袍侣，相欢倒一瓢。",
            "一瓢欢自足，一日兴偏多。幽意人先赏，疏丛蝶未过。",
            "知音新句苦，窥沼醉颜酡。万虑从相拟，今朝欲奈何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 鹭鸶 ----------
    {
        "id": "liu-xiang-2",
        "title": "鹭鸶",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "洁白孤高生不同，顶丝清软冷摇风。窥鱼翘立荷香里，",
            "慕侣低翻柳影中。几日下巢辞紫阁，多时凝目向晴空。",
            "摩霄志在潜修羽，会接鸾凰别苇丛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 春夜二首 ----------
    {
        "id": "liu-xiang-3",
        "title": "春夜二首",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "几处兵戈阻路岐，忆山心切与山违。",
            "时难何处披怀抱，日日日斜空醉归。",
            "一别杜陵归未期，只凭魂梦接亲知。",
            "近来欲睡兼难睡，夜夜夜深闻子规。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 晓登迎春阁 ----------
    {
        "id": "liu-xiang-4",
        "title": "晓登迎春阁",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "未栉凭栏眺锦城，烟笼万井二江明。",
            "香风满阁花盈户，树树树梢啼晓莺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 咏仙掌 ----------
    {
        "id": "liu-xiang-5",
        "title": "咏仙掌",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "万古亭亭倚碧霄，不成擎亦不成招。",
            "何如掬取天池水，洒向人间救旱苗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 郪中感旧 ----------
    {
        "id": "liu-xiang-6",
        "title": "郪中感旧",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "顷年曾住此中来，今日重游事可哀。",
            "忆得几家欢宴处，家家家业尽成灰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 白髭 ----------
    {
        "id": "liu-xiang-7",
        "title": "白髭",
        "author": "刘象",
        "poet_id": "liu-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "到处逢人求至药，几回染了又成丝。",
            "素丝易染髭难染，墨翟当时合泣髭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]