# -*- coding: utf-8 -*-
"""
郎士元卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 72 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 琴曲歌辞·湘夫人 ----------
    {
        "id": "lang-shi-yuan-1",
        "title": "琴曲歌辞·湘夫人",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "娥眉对湘水，遥哭苍梧间。万乘既已殁，孤舟谁忍还。",
            "至今楚山上，犹有泪痕斑。南有涔阳路，渺渺多新愁。",
            "昔神降回时，风波江上秋。彩云忽无处，碧水空安流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 题刘相公三湘图 ----------
    {
        "id": "lang-shi-yuan-2",
        "title": "题刘相公三湘图",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "昔别醉衡霍，迩来忆南州。今朝平津邸，兼得潇湘游。",
            "稍辨郢门树，依然芳杜洲。微明三巴峡，咫尺万里流。",
            "飞鸟不知倦，远帆生暮愁。涔阳指天末，北渚空悠悠。",
            "枕上见渔父，坐中常狎鸥。谁言魏阙下，自有东山幽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 长安逢故人 ----------
    {
        "id": "lang-shi-yuan-3",
        "title": "长安逢故人",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "数年音信断，不意在长安。马上相逢久，人中欲认难。",
            "一官今懒道，双鬓竟羞看。莫问生涯事，只应持钓竿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送韦湛判官 ----------
    {
        "id": "lang-shi-yuan-4",
        "title": "送韦湛判官",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "高阁晴江上，重阳古戍间。聊因送归客，更此望乡山。",
            "惜别心能醉，经秋鬓自斑。临流兴不尽，惆怅水云间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送长沙韦明府 ----------
    {
        "id": "lang-shi-yuan-5",
        "title": "送长沙韦明府",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "秋入长沙县，萧条旅宦心。烟波连桂水，官舍映枫林。",
            "云日楚天暮，沙汀白露深。遥知讼堂里，佳政在鸣琴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送孙愿 ----------
    {
        "id": "lang-shi-yuan-6",
        "title": "送孙愿",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "悠然富春客，忆与暮潮归。擢第人多羡，如君独步稀。",
            "乱流江渡浅，远色海山微。若访新安路，严陵有钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送林宗配雷州（一作送王棼流雷州） ----------
    {
        "id": "lang-shi-yuan-7",
        "title": "送林宗配雷州（一作送王棼流雷州）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "昨日三峰尉，今朝万里人。平生任孤直，岂是不防身。",
            "海雾多为瘴，山雷乍作邻。遥怜北户月，与子独相亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送洪州李别驾之任 ----------
    {
        "id": "lang-shi-yuan-8",
        "title": "送洪州李别驾之任",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "南去秋江远，孤舟兴自多。能将流水引，更入洞庭波。",
            "夏口帆初上，浔阳雁正过。知音在霄汉，佐郡岂蹉跎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送杨中丞和蕃 ----------
    {
        "id": "lang-shi-yuan-9",
        "title": "送杨中丞和蕃",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "锦车登陇日，边草正萋萋。旧好寻君长，新愁听鼓鼙。",
            "河源飞鸟外，雪岭大荒西。汉垒今犹在，遥知路不迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送李将军赴定州（一作送彭将军） ----------
    {
        "id": "lang-shi-yuan-10",
        "title": "送李将军赴定州（一作送彭将军）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "双旌汉飞将，万里授横戈。春色临边尽，黄云出塞多。",
            "鼓鼙悲绝漠，烽戍隔长河。莫断阴山路，天骄已请和。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 关羽祠送高员外还荆州 ----------
    {
        "id": "lang-shi-yuan-11",
        "title": "关羽祠送高员外还荆州",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "将军禀天姿，义勇冠今昔。走马百战场，一剑万人敌。",
            "虽为感恩者，竟是思归客。流落荆巫间，裴回故乡隔。",
            "离筵对祠宇，洒酒暮天碧。去去勿复言，衔悲向陈迹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送张南史（一作寄李纾） ----------
    {
        "id": "lang-shi-yuan-12",
        "title": "送张南史（一作寄李纾）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "雨馀深巷静，独酌送残春。车马虽嫌僻，莺花不弃贫。",
            "虫丝粘户网，鼠迹印床尘。借问山阳会，如今有几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送奚贾归吴 ----------
    {
        "id": "lang-shi-yuan-13",
        "title": "送奚贾归吴",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "东南富春渚，曾是谢公游。今日奚生去，新安江正秋。",
            "水清迎过客，霜叶落行舟。遥想赤亭下，闻猿应夜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 送陆员外赴潮州 ----------
    {
        "id": "lang-shi-yuan-14",
        "title": "送陆员外赴潮州",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "含香台上客，剖竹海边州。楚地多归信，闽溪足乱流。",
            "今朝永嘉兴，重见谢公游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送裴补阙入河南幕 ----------
    {
        "id": "lang-shi-yuan-15",
        "title": "送裴补阙入河南幕",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "皎然青琐客，何事动行轩。苦节酬知己，清吟去掖垣。",
            "秋城临海树，寒月上营门。邹鲁诗书国，应无鼙鼓喧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送韩司直路出延陵（一作刘长卿诗） ----------
    {
        "id": "lang-shi-yuan-16",
        "title": "送韩司直路出延陵（一作刘长卿诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "游吴还适越，来往任风波。复送王孙去，其如春草何。",
            "岸明残雪在，潮满夕阳多。季子留遗庙，停舟试一过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 盩厔县郑礒宅送钱大（一作送别钱起，又作送友人别） ----------
    {
        "id": "lang-shi-yuan-17",
        "title": "盩厔县郑礒宅送钱大（一作送别钱起，又作送友人别）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "暮蝉不可听，落叶岂堪闻。共是悲秋客，那知此路分。",
            "荒城背流水，远雁入寒云。陶令门前菊，馀花可赠君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送元诜还丹阳别业 ----------
    {
        "id": "lang-shi-yuan-18",
        "title": "送元诜还丹阳别业",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "已知成傲吏，复见解朝衣。应向丹阳郭，秋山独掩扉。",
            "草堂连古寺，江日动晴晖。一别沧洲远，兰桡几岁归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送崔侍御往容州宣慰 ----------
    {
        "id": "lang-shi-yuan-19",
        "title": "送崔侍御往容州宣慰",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "秦原独立望湘川，击隼南飞向楚天。奉诏不言空问俗，",
            "清时因得访遗贤。荆门晓色兼梅雨，桂水春风过客船。",
            "畴昔常闻陆贾说，故人今日岂徒然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 朱方南郭留别皇甫冉（一作皇甫冉诗：润州南郭留别） ----------
    {
        "id": "lang-shi-yuan-20",
        "title": "朱方南郭留别皇甫冉（一作皇甫冉诗：润州南郭留别）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "萦回枫叶岸，留滞木兰桡。吴岫新经雨，江天正落潮。",
            "故人劳见爱，行客自无憀。若问前程事，孤云入剡遥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 赠张五諲归濠州别业 ----------
    {
        "id": "lang-shi-yuan-21",
        "title": "赠张五諲归濠州别业",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "常知罢官意，果与世人疏。复此凉风起，仍闻濠上居。",
            "故山期采菊，秋水忆观鱼。一去蓬蒿径，羡君闲有馀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送王司马赴润州 ----------
    {
        "id": "lang-shi-yuan-22",
        "title": "送王司马赴润州",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "暂屈文为吏，聊将禄代耕。金陵且不远，山水复多名。",
            "楚塞因高出，寒潮入夜生。离心逐春草，直到建康城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 留卢秦卿（一作司空曙诗） ----------
    {
        "id": "lang-shi-yuan-23",
        "title": "留卢秦卿（一作司空曙诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "知有前期在，欢如此夜中。无将故人酒，不及古淳风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 赠强山人 ----------
    {
        "id": "lang-shi-yuan-24",
        "title": "赠强山人",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "或掉轻舟或杖藜，寻常适意钓前溪。",
            "草堂竹径在何处，落日孤烟寒渚西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 赠韦司直 ----------
    {
        "id": "lang-shi-yuan-25",
        "title": "赠韦司直",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "闻君感叹二毛初，旧友相依万里馀。烽火有时惊暂定，",
            "甲兵无处可安居。客来吴地星霜久，家在平陵音信疏。",
            "昨日风光还入户，登山临水意何如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 石城馆酬王将军 ----------
    {
        "id": "lang-shi-yuan-26",
        "title": "石城馆酬王将军",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "谁能绣衣客，肯驻木兰舟。连雁沙边至，孤城江上秋。",
            "归帆背南浦，楚塞入西楼。何处看离思，沧波日夜流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 酬王季友题半日村别业兼呈李明府 ----------
    {
        "id": "lang-shi-yuan-27",
        "title": "酬王季友题半日村别业兼呈李明府",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "村映寒原日已斜，烟生密竹早归鸦。长溪南路当群岫，",
            "半景东邻照数家。门通小径连芳草，马饮春泉踏浅沙。",
            "欲待主人林上月，还思潘岳县中花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 酬二十八秀才见寄 ----------
    {
        "id": "lang-shi-yuan-28",
        "title": "酬二十八秀才见寄",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "昨夜山月好，故人果相思。清光到枕上，袅袅凉风时。",
            "永意能在我，惜无携手期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 冬夕寄青龙寺源公 ----------
    {
        "id": "lang-shi-yuan-29",
        "title": "冬夕寄青龙寺源公",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "敛屦入寒竹，安禅过漏声。高松残子落，深井冻痕生。",
            "罢磬风枝动，悬灯雪屋明。何当招我宿，乘月上方行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 塞下曲 ----------
    {
        "id": "lang-shi-yuan-30",
        "title": "塞下曲",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "宝刀塞下儿，身经百战曾百胜，壮心竟未嫖姚知。",
            "白草山头日初没，黄沙戍下悲歌发。萧条夜静边风吹，",
            "独倚营门望秋月。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 柏林寺南望 ----------
    {
        "id": "lang-shi-yuan-31",
        "title": "柏林寺南望",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "溪上遥闻精舍钟，泊舟微径度深松。",
            "青山霁后云犹在，画出东南四五峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 宿杜判官江楼 ----------
    {
        "id": "lang-shi-yuan-32",
        "title": "宿杜判官江楼",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "适楚岂吾愿，思归秋向深。故人江楼月，永夜千里心。",
            "叶落觉乡梦，鸟啼惊越吟。寥寥更何有，断续空城砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 春宴王补阙城东别业 ----------
    {
        "id": "lang-shi-yuan-33",
        "title": "春宴王补阙城东别业",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "柳陌乍随州势转，花源忽傍竹阴开。能将瀑水清人境，",
            "直取流莺送酒杯。山下古松当绮席，檐前片雨滴春苔。",
            "地主同声复同舍，留欢不畏夕阳催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 郢城西楼吟（一作张继诗） ----------
    {
        "id": "lang-shi-yuan-34",
        "title": "郢城西楼吟（一作张继诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "连山尽处水萦回，山上戍门临水开。朱栏直下一百丈，",
            "日暖游鳞自相向。昔人爱险闭层城，今日爱闲江复清。",
            "沙洲枫岸无来客，草绿花红山鸟鸣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 听邻家吹笙 ----------
    {
        "id": "lang-shi-yuan-35",
        "title": "听邻家吹笙",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "凤吹声如隔彩霞，不知墙外是谁家。",
            "重门深锁无寻处，疑有碧桃千树花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 登丹阳北楼（一作张继诗） ----------
    {
        "id": "lang-shi-yuan-36",
        "title": "登丹阳北楼（一作张继诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "寒皋那可望，旅望又初还。迢递高楼上，萧条旷野闲。",
            "暮晴依远水，秋兴属连山。浮客时相见，霜凋动翠颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 题精舍寺（一作酬王季友秋夜宿露台寺见寄） ----------
    {
        "id": "lang-shi-yuan-37",
        "title": "题精舍寺（一作酬王季友秋夜宿露台寺见寄）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "石林精舍武溪东，夜扣禅关谒远公。月在上方诸品静，",
            "僧持半偈万缘空。秋山竟日闻猿啸，落木寒泉听不穷。",
            "惟有双峰最高顶，此心期与故人同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 双林寺谒傅大士 ----------
    {
        "id": "lang-shi-yuan-38",
        "title": "双林寺谒傅大士",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "草露经前代，津梁及后人。此方今示灭，何国更分身。",
            "月色空知夜，松阴不记春。犹怜下生日，应在一微尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 题尹真人祠 ----------
    {
        "id": "lang-shi-yuan-39",
        "title": "题尹真人祠",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "窅窅云旗去不还，阴阴祠宇闭空山。",
            "我来始悟丹青妙，稽首如逢冰雪颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 山中即事 ----------
    {
        "id": "lang-shi-yuan-40",
        "title": "山中即事",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "入谷多春兴，乘舟棹碧浔。山云昨夜雨，溪水晓来深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 湘夫人二首（乐府诗作一首） ----------
    {
        "id": "lang-shi-yuan-41",
        "title": "湘夫人二首（乐府诗作一首）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "蛾眉对湘水，遥哭苍梧山。万乘既已殁，孤舟谁忍还。",
            "至今楚竹上，犹有泪痕斑。",
            "南有涔阳路，渺渺多新愁。桂酒神降时，回风江上秋。",
            "彩云忽无处，碧水空安流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 盖少府新除江南尉问风俗 ----------
    {
        "id": "lang-shi-yuan-42",
        "title": "盖少府新除江南尉问风俗",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "闻君作尉向江潭，吴越风烟到自谙。客路寻常随竹影，",
            "人家大底傍山岚。缘溪花木偏宜远，避地衣冠尽向南。",
            "惟有夜猿啼海树，思乡望国意难堪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 春宴张舍人宅 ----------
    {
        "id": "lang-shi-yuan-43",
        "title": "春宴张舍人宅",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "懒寻芳草径，来接侍臣筵。山色知残雨，墙阴觉暮天。",
            "莺啼汉宫柳，花隔杜陵烟。地与东城接，春光醉目前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 寄李袁州桑落酒 ----------
    {
        "id": "lang-shi-yuan-44",
        "title": "寄李袁州桑落酒",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "色比琼浆犹嫩，香同甘露仍春。",
            "十千提携一斗，远送潇湘故人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 赠万生下第还吴） ----------
    {
        "id": "lang-shi-yuan-45",
        "title": "赠万生下第还吴）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "直道多不偶，美才应息机。灞陵春欲暮，云海独言归。",
            "为客成白首，入门嗟布衣。莼羹若可忆，惭出掩柴扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送大德讲时河东徐明府招 ----------
    {
        "id": "lang-shi-yuan-46",
        "title": "送大德讲时河东徐明府招",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "远近作人天，王城指日边。宰君迎说法，童子伴随缘。",
            "到处花为雨，行时杖出泉。今宵松月下，开阁想安禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 赴无锡别灵一上人（一作刘长卿诗，一作皇甫冉诗） ----------
    {
        "id": "lang-shi-yuan-47",
        "title": "赴无锡别灵一上人（一作刘长卿诗，一作皇甫冉诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "高僧本姓竺，开士旧名林。一入春山里，千峰不可寻。",
            "新年芳草遍，度日白云深。欲问微官去，悬知讶此心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 送粲上人兼寄梁镇员外 ----------
    {
        "id": "lang-shi-yuan-48",
        "title": "送粲上人兼寄梁镇员外",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "季月还乡独未能，林行溪宿厌层冰。尺素欲传三署客，",
            "雪山愁送五天僧。连空朔气横秦苑。满目寒云隔灞陵。",
            "借问从来香积寺，何时携手更同登。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 送韦逸人归钟山（一作皇甫冉诗） ----------
    {
        "id": "lang-shi-yuan-49",
        "title": "送韦逸人归钟山（一作皇甫冉诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "逸人归路远，弟子出山迎。服药颜犹驻，耽书癖已成。",
            "柴扉多岁月，藜杖见公卿。更作儒林传，应须载姓名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 登无锡北楼（一作皇甫冉诗） ----------
    {
        "id": "lang-shi-yuan-50",
        "title": "登无锡北楼（一作皇甫冉诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "秋兴因危堞，归心过远山。风霜征雁早，江海旅人还。",
            "驿树寒仍密，渔舟晚更闲。仲宣何所赋，只欲滞柴关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 和王相公题中书丛竹寄上元相公 ----------
    {
        "id": "lang-shi-yuan-51",
        "title": "和王相公题中书丛竹寄上元相公",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "多时仙掖里，色并翠琅玕。幽意含烟月，清阴庇蕙兰。",
            "枝繁宜露重，叶老爱天寒。竟日双鸾止，孤吟为一看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 酬萧二十七侍御初秋言怀 ----------
    {
        "id": "lang-shi-yuan-52",
        "title": "酬萧二十七侍御初秋言怀",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "楚客秋多兴，江林月渐生。细枝凉叶动，极浦早鸿声。",
            "胜赏睽前夕，新诗报远情。曲高惭和者，惆怅闭寒城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 奉和杜相公益昌路作 ----------
    {
        "id": "lang-shi-yuan-53",
        "title": "奉和杜相公益昌路作",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "春半梁山正落花，台衡受律向天涯。南去猿声傍双节，",
            "西来江色绕千家。风吹画角孤城晓，林映蛾眉片月斜。",
            "已见庙谟能喻蜀，新文更喜报金华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 赋得长洲苑送李惠 ----------
    {
        "id": "lang-shi-yuan-54",
        "title": "赋得长洲苑送李惠",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "草深那可访，地久阻相传。散漫三秋雨，疏芜万里烟。",
            "都迷采兰处，强记馆娃年。客有游吴者，临风思眇然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 别房士清 ----------
    {
        "id": "lang-shi-yuan-55",
        "title": "别房士清",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "世路还相见，偏堪泪满衣。那能郢门别，独向邺城归。",
            "平楚看蓬转，连山望鸟飞。苍苍岁阴暮，况复惜驰晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 送彭偃房由赴朝因寄钱大郎中李十七舍人 ----------
    {
        "id": "lang-shi-yuan-56",
        "title": "送彭偃房由赴朝因寄钱大郎中李十七舍人",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "衰病已经年，西峰望楚天。风光欺鬓发，秋色换山川。",
            "寂寞浮云外，支离汉水边。平生故人远，君去话潸然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 送李遂之越 ----------
    {
        "id": "lang-shi-yuan-57",
        "title": "送李遂之越",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "未习风波事，初为东越游。露沾湖草晚，月照海山秋。",
            "梅市门何处，兰亭水向流。西兴待潮信，落日满孤舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 送郑正则徐州行营（一作皇甫冉诗） ----------
    {
        "id": "lang-shi-yuan-58",
        "title": "送郑正则徐州行营（一作皇甫冉诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "从军非陇头，师在古徐州。气劲三河卒，功全万户侯。",
            "元戎阃外略，才子握中筹。莫听关山曲，还生塞上愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 送钱拾遗归兼寄刘校书 ----------
    {
        "id": "lang-shi-yuan-59",
        "title": "送钱拾遗归兼寄刘校书",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "墟落岁阴暮，桑榆烟景昏。蝉声静空馆，雨色隔秋原。",
            "归客不可望，悠然林外村。终当报芸阁，携手醉柴门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 送郴县裴明府之任兼充宣慰 ----------
    {
        "id": "lang-shi-yuan-60",
        "title": "送郴县裴明府之任兼充宣慰",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "白蘋楚水三湘远，芳草秦城二月初。连雁北飞看欲尽，",
            "孤舟南去意何如。渡江野老思求瘼，候馆郴人忆下车。",
            "别后天涯何所寄，故交惟有袖中书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 送李敖湖南书记 ----------
    {
        "id": "lang-shi-yuan-61",
        "title": "送李敖湖南书记",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "怜君才与阮家同，掌记能资亚相雄。入楚岂忘看泪竹，",
            "泊舟应自爱江枫。诚知客梦烟波里，肯厌猿鸣夜雨中。",
            "莫信衡湘书不到，年年秋雁过巴东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 送麹司直 ----------
    {
        "id": "lang-shi-yuan-62",
        "title": "送麹司直",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "曙雪苍苍兼曙云，朔风烟雁不堪闻。",
            "贫交此别无他赠，唯有青山远送君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 送别 ----------
    {
        "id": "lang-shi-yuan-63",
        "title": "送别",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "穆陵关上秋云起，安陆城边远行子。",
            "薄暮寒蝉三两声，回头故乡千万里。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 咸阳西楼别窦审 ----------
    {
        "id": "lang-shi-yuan-64",
        "title": "咸阳西楼别窦审",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "西楼迥起寒原上，霁日遥分万井间。小苑城隅连渭水，",
            "离宫曙色近京关。亭皋寂寞伤孤客，云雪萧条满众山。",
            "时命如今犹未偶，辞君拟欲拂衣还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 闻蝉寄友人（一作李端诗） ----------
    {
        "id": "lang-shi-yuan-65",
        "title": "闻蝉寄友人（一作李端诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "昨日始闻莺，今朝蝉又鸣。朱颜向华发，定是几年程。",
            "故国白云远，闲居青草生。因垂数行泪，书寄十年兄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 送李骑曹之灵武宁侍 ----------
    {
        "id": "lang-shi-yuan-66",
        "title": "送李骑曹之灵武宁侍",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "一岁一归宁，凉天数骑行。河来当塞曲，山远与沙平。",
            "纵猎旗风卷，听笳帐月生。新鸿引寒色，回日满京城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 冯翊西楼（一作张继诗） ----------
    {
        "id": "lang-shi-yuan-67",
        "title": "冯翊西楼（一作张继诗）",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "城上西楼倚暮天，楼中归望正凄然。近郭乱山横古渡，",
            "野庄乔木带新烟。北风吹雁声能苦，远客辞家月再圆。",
            "陶令好文常对酒，相招一和白云篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 郢城秋望 ----------
    {
        "id": "lang-shi-yuan-68",
        "title": "郢城秋望",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "白首思归归不得，空山闻雁雁声哀。",
            "高城落日望西北，又见秋风逐水来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 夜泊湘江 ----------
    {
        "id": "lang-shi-yuan-69",
        "title": "夜泊湘江",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "湘山木落洞庭波，湘水连云秋雁多。",
            "寂寞舟中谁借问，月明只自听渔歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 留别常著 ----------
    {
        "id": "lang-shi-yuan-70",
        "title": "留别常著",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "岁晏苍郊蓬转时，游人相见说归期。",
            "宓君堂上能留客，明日还家应未迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 送张光归吴 ----------
    {
        "id": "lang-shi-yuan-71",
        "title": "送张光归吴",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "看取庭芜白露新，劝君不用久风尘。",
            "秋来多见长安客，解爱鲈鱼能几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 闻吹杨叶者二首 ----------
    {
        "id": "lang-shi-yuan-72",
        "title": "闻吹杨叶者二首",
        "author": "郎士元",
        "poet_id": "lang-shi-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "妙吹杨叶动悲笳，胡马迎风起恨赊。",
            "若是雁门寒月夜，此时应卷尽惊沙。",
            "天生一艺更无伦，寥亮幽音妙入神。",
            "吹向别离攀折处，当应合有断肠人。",
            "第二百四十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]