# -*- coding: utf-8 -*-
"""
白行简卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 春从何处来 ----------
    {
        "id": "bai-xing-jian-1",
        "title": "春从何处来",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "欲识春生处，先从木德来。入门潜报柳，度岭暗惊梅。",
            "透雪寒光散，消冰水镜开。晓迎郊骑发，夜逐斗杓回。",
            "淑气空中变，新声雨后催。偏宜资律吕，应是候阳台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 贡院楼北新栽小松 ----------
    {
        "id": "bai-xing-jian-2",
        "title": "贡院楼北新栽小松",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "华省春霜曙，楼阴植小松。移根依厚地，委质别危峰。",
            "北户知犹远，东堂幸见容。心坚终待鹤，枝嫩未成龙。",
            "夜影看仍薄，朝岚色渐浓。山苗不可荫，孤直俟秦封。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 金在熔 ----------
    {
        "id": "bai-xing-jian-3",
        "title": "金在熔",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "巨橐方熔物，洪炉欲范金。紫光看渐发，赤气望逾深。",
            "焰热晴云变，烟浮昼景阴。坚刚由我性，鼓铸任君心。",
            "踊跃徒标异，沈潜自可钦。何当得成器，待叩向知音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 归马华山 ----------
    {
        "id": "bai-xing-jian-4",
        "title": "归马华山",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "牧野功成后，周王战马闲。驱驰休伏皂，饮龁任依山。",
            "逐日朝仍去，随风暮自还。冰生疑陇坂，叶落似榆关。",
            "躞蹀仙峰下，腾骧渭水湾。幸逢时偃武，不复鼓鼙间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 夫子鼓琴得其人 ----------
    {
        "id": "bai-xing-jian-5",
        "title": "夫子鼓琴得其人",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "宣父穷玄奥，师襄授素琴。稍殊流水引，全辨圣人心。",
            "慕德声逾感，怀人意自深。泠泠传妙手，摵摵振空林。",
            "促调清风至，操弦白日沈。曲终情不尽，千古仰知音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 李都尉重阳日得苏属国书 ----------
    {
        "id": "bai-xing-jian-6",
        "title": "李都尉重阳日得苏属国书",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "降虏意何如，穷荒九月初。三秋异乡节，一纸故人书。",
            "对酒情无极，开缄思有馀。感时空寂寞，怀旧几踌躇。",
            "雁尽平沙迥，烟销大漠虚。登台南望处，掩泪对双鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 在巴南望郡南山呈乐天（时从乐天忠州） ----------
    {
        "id": "bai-xing-jian-7",
        "title": "在巴南望郡南山呈乐天（时从乐天忠州）",
        "author": "白行简",
        "poet_id": "bai-xing-jian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "临江一嶂白云间，红绿层层锦绣班。",
            "不作巴南天外意，何殊昭应望骊山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]