# -*- coding: utf-8 -*-
"""
刘方平卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 29 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 乐府杂曲·鼓吹曲辞·巫山高 ----------
    {
        "id": "liu-fang-ping-1",
        "title": "乐府杂曲·鼓吹曲辞·巫山高",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "楚国巫山秀，清猿日夜啼。万重春树合，十二碧峰齐。",
            "峡出朝云下，江来暮雨西。阳台归路直，不畏向家迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 横吹曲辞·梅花落 ----------
    {
        "id": "liu-fang-ping-2",
        "title": "横吹曲辞·梅花落",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "新岁芳梅树，繁苞四面同。春风吹渐落，一夜几枝空。",
            "小妇今如此，长城恨不穷。莫将辽海雪，来比后庭中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 相和歌辞·婕妤怨 ----------
    {
        "id": "liu-fang-ping-3",
        "title": "相和歌辞·婕妤怨",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "夕殿别君王，宫深月似霜。人愁在长信，萤出向昭阳。",
            "露裛红兰死，秋凋碧树伤。惟当合欢扇，从此箧中藏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 相和歌辞·栖乌曲二首 ----------
    {
        "id": "liu-fang-ping-4",
        "title": "相和歌辞·栖乌曲二首",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "蛾眉曼脸倾城国，鸣环动佩新相识。",
            "银汉斜临白玉堂，芙蓉行障掩灯光。",
            "画舸双艚锦为缆，芙蓉花发莲叶暗。",
            "门前月色映横塘，感郎中夜渡潇湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 琴曲歌辞·宛转歌二首 ----------
    {
        "id": "liu-fang-ping-5",
        "title": "琴曲歌辞·宛转歌二首",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "星参差，月二八，灯五枝。黄鹤瑶琴将别去，",
            "芙蓉羽帐惜空垂。歌宛转，宛转恨无穷。愿为波与浪，",
            "俱起碧流中。",
            "晓将近，黄姑织女银河尽。九华锦衾无复情，",
            "千金宝镜谁能引。歌宛转，宛转伤别离。愿作杨与柳，",
            "同向玉窗垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 代宛转歌二首 ----------
    {
        "id": "liu-fang-ping-6",
        "title": "代宛转歌二首",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "星参差，明月二八灯五枝。黄鹤瑶琴将别去，",
            "芙蓉羽帐惜空垂。歌宛转，宛转恨无穷。愿为潮与浪，",
            "俱起碧流中。",
            "晓将近，黄姑织女银河尽。九华锦衾无复情，",
            "千金宝镜谁能引。歌宛转，宛转伤别离。愿作杨与柳，",
            "同向玉窗垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 乌栖曲二首 ----------
    {
        "id": "liu-fang-ping-7",
        "title": "乌栖曲二首",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "蛾眉曼脸倾城国，鸣环动佩新相识。",
            "银汉斜临白玉堂，芙蓉行障掩灯光。",
            "画舸双艚锦为缆，芙蓉花发莲叶暗。",
            "门前月色映横塘，感郎中夜度潇湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 巫山高 ----------
    {
        "id": "liu-fang-ping-8",
        "title": "巫山高",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "楚国巫山秀，清猿日夜啼。万重春树合，十二碧峰齐。",
            "峡出朝云下，江来暮雨西。阳台归路直，不畏向家迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 巫山神女 ----------
    {
        "id": "liu-fang-ping-9",
        "title": "巫山神女",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "神女藏难识，巫山秀莫群。今宵为大雨，昨日作孤云。",
            "散漫愁巴峡，徘徊恋楚君。先王为立庙，春树几氛氲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 梅花落 ----------
    {
        "id": "liu-fang-ping-10",
        "title": "梅花落",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "新岁芳梅树，繁花四面同。春风吹渐落，一夜几枝空。",
            "少妇今如此，长城恨不穷。莫将辽海雪，来比后庭中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 铜雀妓 ----------
    {
        "id": "liu-fang-ping-11",
        "title": "铜雀妓",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "遗令奉君王，嚬蛾强一妆。岁移陵树色，恩在舞衣香。",
            "玉座生秋气，铜台下夕阳。泪痕沾井干，舞袖为谁长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 秋夜思（一作淮上秋夜） ----------
    {
        "id": "liu-fang-ping-12",
        "title": "秋夜思（一作淮上秋夜）",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "旅梦何时尽，征途望每赊。晚秋淮上水，新月楚人家。",
            "猿啸空山近，鸿飞极浦斜。明朝南岸去，言折桂枝花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 秋夜泛舟 ----------
    {
        "id": "liu-fang-ping-13",
        "title": "秋夜泛舟",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "林塘夜发舟，虫响荻飕飕。万影皆因月，千声各为秋。",
            "岁华空复晚，乡思不堪愁。西北浮云外，伊川何处流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 折杨枝 ----------
    {
        "id": "liu-fang-ping-14",
        "title": "折杨枝",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "官渡初杨柳，风来亦动摇。武昌行路好，应为最长条。",
            "叶映黄鹂夕，花繁白雪朝。年年攀折意，流恨入纤腰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 班婕妤（一作婕妤怨） ----------
    {
        "id": "liu-fang-ping-15",
        "title": "班婕妤（一作婕妤怨）",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "夕殿别君王，宫深月似霜。人幽在长信，萤出向昭阳。",
            "露浥红兰湿，秋凋碧树伤。惟当合欢扇，从此箧中藏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 新春 ----------
    {
        "id": "liu-fang-ping-16",
        "title": "新春",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "南陌春风早，东邻曙色斜。一花开楚国，双燕入卢家。",
            "眠罢梳云髻，妆成上锦车。谁知如昔日，更浣越溪纱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 寄严八判官 ----------
    {
        "id": "liu-fang-ping-17",
        "title": "寄严八判官",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "洛阳新月动秋砧，瀚海沙场天半阴。出塞能全仲叔策，",
            "安亲更切老莱心。汉家宫里风云晓，羌笛声中雨雪深。",
            "怀袖未传三岁字，相思空作陇头吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 秋夜寄皇甫冉郑丰 ----------
    {
        "id": "liu-fang-ping-18",
        "title": "秋夜寄皇甫冉郑丰",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "洛阳清夜白云归，城里长河列宿稀。秋后见飞千里雁，",
            "月中闻捣万家衣。长怜西雍青门道，久别东吴黄鹄矶。",
            "借问客书何所寄，用心不啻两乡违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 寄陇右严判官 ----------
    {
        "id": "liu-fang-ping-19",
        "title": "寄陇右严判官",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "副相西征重，苍生属望晨。还同周薄伐，不取汉和亲。",
            "虏阵摧枯易，王师决胜频。高旗临鼓角，太白静风尘。",
            "赤狄争归化，青羌已请臣。遥传阃外美，盛选幕中宾。",
            "玉剑光初发，冰壶色自真。忠贞期报主，章服岂荣身。",
            "边草含风绿，征鸿过月新。胡笳长出塞，陇水半归秦。",
            "绝漠多来往，连年厌苦辛。路经西汉雪，家掷后园春。",
            "谁念烟云里，深居汝颍滨。一丛黄菊地，九日白衣人。",
            "松叶疏开岭，桃花密映津。缣书若有寄，为访许由邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 拟娼楼节怨 ----------
    {
        "id": "liu-fang-ping-20",
        "title": "拟娼楼节怨",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "上苑离离莺度，昆明幂幂蒲生。",
            "时光春华可惜，何须对镜含情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 采莲曲 ----------
    {
        "id": "liu-fang-ping-21",
        "title": "采莲曲",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "落日晴江里，荆歌艳楚腰。采莲从小惯，十五即乘潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 长信宫 ----------
    {
        "id": "liu-fang-ping-22",
        "title": "长信宫",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "梦里君王近，宫中河汉高。秋风能再热，团扇不辞劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 京兆眉 ----------
    {
        "id": "liu-fang-ping-23",
        "title": "京兆眉",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "新作蛾眉样，谁将月里同。有来凡几日，相效满城中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 春雪 ----------
    {
        "id": "liu-fang-ping-24",
        "title": "春雪",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "飞雪带春风，裴回乱绕空。君看似花处，偏在洛阳东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 望夫石 ----------
    {
        "id": "liu-fang-ping-25",
        "title": "望夫石",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "佳人成古石，藓驳覆花黄。犹有春山杏，枝枝似薄妆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送别 ----------
    {
        "id": "liu-fang-ping-26",
        "title": "送别",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "华亭霁色满今朝，云里樯竿去转遥。",
            "莫怪山前深复浅，清淮一日两回潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 夜月 ----------
    {
        "id": "liu-fang-ping-27",
        "title": "夜月",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "更深月色半人家，北斗阑干南斗斜。",
            "今夜偏知春气暖，虫声新透绿窗纱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 春怨 ----------
    {
        "id": "liu-fang-ping-28",
        "title": "春怨",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "七言绝句",
        "year": "约开元中",
        "source": "《全唐诗·卷二五一》",
        "verse": [
            "纱窗日落渐黄昏，金屋无人见泪痕。",
            "寂寞空庭春欲晚，梨花满地不开门。",
        ],
        "tijie": "此诗写宫怨，以落日、空庭、梨花写深宫寂寞，含蓄哀婉，为刘方平七绝中之宫怨名篇。",
        "notes": [
            ("金屋", "华美宫室，用金屋藏娇典。"),
            ("春欲晚", "春将尽。"),
            ("不开门", "深闭宫门，写孤寂。"),
        ],
        "appreciation": "首句「纱窗日落渐黄昏」写日暮窗前，时光暗转；次句「金屋无人见泪痕」写华屋泪痕无人见，寂寞之深。后二句「寂寞空庭春欲晚，梨花满地不开门」以空庭春晚、梨花满地、门深闭收束，以落花喻青春空逝，以闭门写永巷之孤。刘方平宫怨诗擅长以景写哀，此篇无一「怨」字而怨意弥漫，与王昌龄宫怨并美而更趋含蓄。",
        "famous": [
            ("寂寞空庭春欲晚，梨花满地不开门。", "宫怨名句，含蓄哀婉。"),
        ],
        "sources": [
            "《全唐诗》卷二五一",
            "《唐诗鉴赏辞典》刘方平条（上海辞书出版社，1983）",
        ],
    },
    # ---------- 29. 代春怨 ----------
    {
        "id": "liu-fang-ping-29",
        "title": "代春怨",
        "author": "刘方平",
        "poet_id": "liu-fang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "朝日残莺伴妾啼，开帘只见草萋萋。",
            "庭前时有东风入，杨柳千条尽向西。",
            "第二百五十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]