# -*- coding: utf-8 -*-
"""
修睦卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 27 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 秋日闲居 ----------
    {
        "id": "xiu-mu-1",
        "title": "秋日闲居",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "是事不相关，谁人似此闲。卷帘当白昼，移榻对青山。",
            "野鹤眠松上，秋苔长雨间。岳僧频有信，昨日得书还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 宿岳阳开元寺 ----------
    {
        "id": "xiu-mu-2",
        "title": "宿岳阳开元寺",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "竟夕凭虚槛，何当兴叹频。往来人自老，今古月常新。",
            "风逆沈鱼唱，松疏露鹤身。无眠钟又动，几客在迷津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送边将 ----------
    {
        "id": "xiu-mu-3",
        "title": "送边将",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "人尽有离别，而君独可嗟。言将身报国，敢望禄荣家。",
            "战思风吹野，乡心月照沙。归期定何日，塞北树无花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 雪中送人北游 ----------
    {
        "id": "xiu-mu-4",
        "title": "雪中送人北游",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "然知心去速，其奈雪飞频。莫喜无危道，虽平更陷人。",
            "远郊光接汉，旷野色通秦。此去迢遥极，却回应过春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 落叶 ----------
    {
        "id": "xiu-mu-5",
        "title": "落叶",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "雨过闲田地，重重落叶红。翻思向春日，肯信有秋风。",
            "几处随流水，河边乱暮空。只应松自立，而不与君同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 落花 ----------
    {
        "id": "xiu-mu-6",
        "title": "落花",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "一片又一片，等闲苔面红。不能延数日，开亦是春风。",
            "公子歌声歇，诗人眼界空。遥思故山下，经雨两三丛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 题田道者院 ----------
    {
        "id": "xiu-mu-7",
        "title": "题田道者院",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "入门空寂寂，真个出家儿。有行鬼不见，无心人谓痴。",
            "古岩寒柏对，流水落花随。欲别一何懒，相从所恨迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 东林寺 ----------
    {
        "id": "xiu-mu-8",
        "title": "东林寺",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "欲去不忍去，徘徊吟绕廊。水光秋澹荡，僧好语寻常。",
            "碑古苔文叠，山晴钟韵长。翻思南岳上，欠此白莲香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 寄贯休上人 ----------
    {
        "id": "xiu-mu-9",
        "title": "寄贯休上人",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "常语亦关诗，常流安得知。楚郊来未久，吴地住多时。",
            "立月无人近，归林有鹤随。所居浑不远，相识偶然迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 喜僧友到 ----------
    {
        "id": "xiu-mu-10",
        "title": "喜僧友到",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "十年消息断，空使梦烟萝。嵩岳几时下，洞庭何日过。",
            "瓶干离涧久，衲坏卧云多。意欲相留住，游方肯舍么。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 怀虚中上人 ----------
    {
        "id": "xiu-mu-11",
        "title": "怀虚中上人",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "檐雨滴更残，思君安未安。湘川闻不远，道路去寻难。",
            "吟鬓霜应蚀，禅衣雪渐寒。倚松因独立，一鸟下江干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 简寂观 ----------
    {
        "id": "xiu-mu-12",
        "title": "简寂观",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "正同高士坐烟霞，思著闲忙又是嗟。碧岫观中人似鹤，",
            "红尘路上事如麻。石肥滞雨添苍藓，松老涵风落翠花。",
            "莫道此间无我分，遗民长在惠持家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 睡起作 ----------
    {
        "id": "xiu-mu-13",
        "title": "睡起作",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "长空秋雨歇，睡起觉精神。看水看山坐，无名无利身。",
            "偈吟诸祖意，茶碾去年春。此外谁相识，孤云到砌频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 卖松者 ----------
    {
        "id": "xiu-mu-14",
        "title": "卖松者",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "求利有何限，将松入市来。直饶人买去，也向柳边栽。",
            "细叶犹粘雪，孤根尚惹苔。知君用心错，举世重花开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 思齐己上人 ----------
    {
        "id": "xiu-mu-15",
        "title": "思齐己上人",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "同人与流俗，相谓好襟灵。有口不他说，长年自诵经。",
            "水声秋后石，山色晚来庭。客问修何法，指松千岁青。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送玄泰禅师 ----------
    {
        "id": "xiu-mu-16",
        "title": "送玄泰禅师",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "去去去何住，一盂兼一瓶。水边寒草白，岛外晚峰青。",
            "宿处林闻虎，行时天有星。回期谁可定，浮世重看经。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 三生石 ----------
    {
        "id": "xiu-mu-17",
        "title": "三生石",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "圣迹谁会得，每到亦徘徊。一尚不可得，三从何处来。",
            "清宵寒露滴，白昼野云隈。应是表灵异，凡情安可猜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 题僧梦微房 ----------
    {
        "id": "xiu-mu-18",
        "title": "题僧梦微房",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "东海日未出，九衢人已行。吾师无事坐，苔藓入门生。",
            "雨过闲花落，风来古木声。天台频说法，石壁欠题名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 秋台作 ----------
    {
        "id": "xiu-mu-19",
        "title": "秋台作",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "独上高楼上，客情何物同。孤云无定处，长日信秋风。",
            "兄弟多年别，关河此夕中。到头归去是，免使叹洪濛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 怀故园 ----------
    {
        "id": "xiu-mu-20",
        "title": "怀故园",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "故园归未得，此日意何伤。独坐水边草，水流春日长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 僧院泉 ----------
    {
        "id": "xiu-mu-21",
        "title": "僧院泉",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "澄澈照人胆，深山只一般。来难穷处所，心去助波澜。",
            "砌曲夜声苦，窗虚客梦阑。无心谁肯爱，时有老僧看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 题僧院泉 ----------
    {
        "id": "xiu-mu-22",
        "title": "题僧院泉",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "何处云根新布得，归仍半日在烟萝。莫轻竹引经窗小，",
            "须信更深入耳多。绕砌虽然清自别，出门长恐浊相和。",
            "从此无心恋沧海，沧海无风亦起波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 岳上作 ----------
    {
        "id": "xiu-mu-23",
        "title": "岳上作",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "始好步青苔，蝉声且莫催。辛勤来到此，容易便言回。",
            "远水月未上，四方云正开。更堪逢道侣，特地话天台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 望西山 ----------
    {
        "id": "xiu-mu-24",
        "title": "望西山",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "积翠异诸岳，令人看莫休。有时经暮雨，独得倚高楼。",
            "云外僧应老，林间水正秋。到头归隐处，岂在问嵩丘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 题虎掊泉 ----------
    {
        "id": "xiu-mu-25",
        "title": "题虎掊泉",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "一自虎掊得，清声四远流。众人怜尔处，长夜洗心头。",
            "出谷花随去，背岩猿下偷。林边落江徼，风起雨翛翛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 松 ----------
    {
        "id": "xiu-mu-26",
        "title": "松",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "细韵飕飕入骨凉，影兼巢鹤过高墙。",
            "盘根一种依平地，自是梧桐不久长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 岳阳对柳 ----------
    {
        "id": "xiu-mu-27",
        "title": "岳阳对柳",
        "author": "修睦",
        "poet_id": "xiu-mu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "谁此种秋色，令人看莫穷。正垂云梦雨，不奈洞庭风。",
            "昔出长安道，独游隋苑东。当时今日思，须信苦相同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]