# -*- coding: utf-8 -*-
"""
宗楚客卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 奉和人日清晖阁宴群臣遇雪应制 ----------
    {
        "id": "zong-chu-ke-1",
        "title": "奉和人日清晖阁宴群臣遇雪应制",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "窈窕神仙阁，参差云汉间。九重中叶启，七日早春还。",
            "太液天为水，蓬莱雪作山。今朝上林树，无处不堪攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 安乐公主移入新宅侍宴应制 ----------
    {
        "id": "zong-chu-ke-2",
        "title": "安乐公主移入新宅侍宴应制",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "星桥他日创，仙榜此时开。马向铺钱埒，箫闻弄玉台。",
            "人同卫叔美，客似长卿才。借问游天汉，谁能取石回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 正月晦日侍宴浐水应制赋得长字 ----------
    {
        "id": "zong-chu-ke-3",
        "title": "正月晦日侍宴浐水应制赋得长字",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "御辇出明光，乘流泛羽觞。珠胎随月减，玉漏与年长。",
            "寒尽梅犹白，风迟柳未黄。日斜旌骑转，休气满林塘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 奉和幸上阳宫侍宴应制 ----------
    {
        "id": "zong-chu-ke-4",
        "title": "奉和幸上阳宫侍宴应制",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "紫庭金凤阙，丹禁玉鸡川。似立蓬瀛上，疑游昆阆前。",
            "鸟将歌合转，花共锦争鲜。湛露飞尧酒，熏风入舜弦。",
            "水光摇落日，树色带晴烟。向夕回雕辇，佳气满岩泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 奉和幸安乐公主山庄应制 ----------
    {
        "id": "zong-chu-ke-5",
        "title": "奉和幸安乐公主山庄应制",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "玉楼银榜枕严城，翠盖红旂列禁营。日映层岩图画色，",
            "风摇杂树管弦声。水边重阁含飞动，云里孤峰类削成。",
            "幸睹八龙游阆苑，无劳万里访蓬瀛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 奉和圣制喜雪应制 ----------
    {
        "id": "zong-chu-ke-6",
        "title": "奉和圣制喜雪应制",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "飘飘瑞雪下山川，散漫轻飞集九埏。似絮还飞垂柳陌，",
            "如花更绕落梅前。影随明月团纨扇，声将流水杂鸣弦。",
            "共荷神功万庾积，终朝圣寿百千年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 句 ----------
    {
        "id": "zong-chu-ke-7",
        "title": "句",
        "author": "宗楚客",
        "poet_id": "zong-chu-ke",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "竹町罗千卫，兰莛降两宫。（《海录碎事》）",
            "七萃銮舆动，千年瑞检开。彩旗临凤阙，翠幕绕龟津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]