# -*- coding: utf-8 -*-
"""
喻凫卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 66 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 赠李商隐 ----------
    {
        "id": "yu-fu-1",
        "title": "赠李商隐",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "羽翼恣抟扶，山河使笔驱。月疏吟夜桂，龙失咏春珠。",
            "草细盘金勒，花繁倒玉壶。徒嗟好章句，无力致前途。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 元日即事 ----------
    {
        "id": "yu-fu-2",
        "title": "元日即事",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "敛板贺交亲，称觞讵有巡。年光悲掷旧，景色喜呈新。",
            "水柳烟中重，山梅雪后真。不知将白发，何以度青春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送贾岛往金州谒姚员外 ----------
    {
        "id": "yu-fu-3",
        "title": "送贾岛往金州谒姚员外",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "山光与水色，独往此中深。溪沥椒花气，岩盘漆叶阴。",
            "潇湘终共去，巫峡羡先寻。几夕江楼月，玄晖伴静吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送友人罢举归蜀 ----------
    {
        "id": "yu-fu-4",
        "title": "送友人罢举归蜀",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "憔悴满衣尘，风光岂属身。卖琴红粟贵，看镜白髭新。",
            "栈畔谁高步，巴边自问津。凄然莫滴血，杜宇正哀春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送卫尉之延陵 ----------
    {
        "id": "yu-fu-5",
        "title": "送卫尉之延陵",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "草木正花时，交亲触雨辞。一官之任远，尽室出城迟。",
            "乳滴茅君洞，鸦鸣季子祠。想知佐理暇，日有咏怀诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送越州高录事 ----------
    {
        "id": "yu-fu-6",
        "title": "送越州高录事",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "官曹权纪纲，行李半舟航。浦溆潮来广，川源鸟去长。",
            "笋成稽岭岸，莲发镜湖香。泽国还之任，鲈鱼浪得尝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送潘咸 ----------
    {
        "id": "yu-fu-7",
        "title": "送潘咸",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "时时赍破囊，访我息闲坊。煮雪问茶味，当风看雁行。",
            "心齐山鹿逸，句敌柳花狂。坚苦今如此，前程岂渺茫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送友人下第归宁 ----------
    {
        "id": "yu-fu-8",
        "title": "送友人下第归宁",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "紫阁雪未尽，杏园花亦寒。灞西辞旧友，楚外忆新安。",
            "细雨猿啼枿，微阳鹭起滩。旋应赴秋贡，讵得久承欢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 游北山寺 ----------
    {
        "id": "yu-fu-9",
        "title": "游北山寺",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "烟冈影畔寺，游步此时孤。庭静众药在，鹤闲双桧枯。",
            "蓝峰露秋院，灞水入春厨。便可栖心迹，如何返旧途。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 冬日题无可上人院 ----------
    {
        "id": "yu-fu-10",
        "title": "冬日题无可上人院",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "入户道心生，茶间踏叶行。泻风瓶水涩，承露鹤巢轻。",
            "阁北长河气，窗东一桧声。诗言与禅味，语默此皆清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 游云际寺 ----------
    {
        "id": "yu-fu-11",
        "title": "游云际寺",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "涧壑吼风雷，香门绝顶开。阁寒僧不下，钟定虎常来。",
            "鸟啄林稍果，鼯跳竹里苔。心源无一事，尘界拟休回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 题翠微寺 ----------
    {
        "id": "yu-fu-12",
        "title": "题翠微寺",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "沿溪又涉巅，始喜入前轩。钟度鸟沈壑，殿扃云湿幡。",
            "凉泉堕众石，古木彻疏猿。月上僧阶近，斯游岂易言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 广德官舍二松 ----------
    {
        "id": "yu-fu-13",
        "title": "广德官舍二松",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "杨公休簿领，二木日坚牢。直甚彰吾节，清终庇尔曹。",
            "幽阴月里细，冷树雪中高。谁见干霄后，枝飘白鹤毛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 浴马 ----------
    {
        "id": "yu-fu-14",
        "title": "浴马",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "解控复收鞭，长津动细涟。空蹄沈绿玉，阔臆没连钱。",
            "沫漩桥声下，嘶盘柳影边。常闻禀龙性，固与白波便。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 和段学士南亭春日对雨 ----------
    {
        "id": "yu-fu-15",
        "title": "和段学士南亭春日对雨",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "晨飞晚未休，兰阁客吟愁。萧飒柳边挂，萦纡花底流。",
            "声繁乍离籁，洒急不成沤。经夕江湖思，烟波一钓舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 书怀 ----------
    {
        "id": "yu-fu-16",
        "title": "书怀",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "只是守琴书，僧中独寓居。心唯务鹤静，分合与名疏。",
            "暮雨啼螀次，凉风落木初。家山太湖渌，归去复何如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 一公房 ----------
    {
        "id": "yu-fu-17",
        "title": "一公房",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "幽深谁掩关，清净自多闲。一雨收众木，孤云生远山。",
            "花萎绿苔上，鸽乳翠楼间。岚霭燃香夕，容听半偈还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 晚次临泾 ----------
    {
        "id": "yu-fu-18",
        "title": "晚次临泾",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "路入犬羊群，城寒雉堞曛。居人只尚武，过客谩投文。",
            "马怯奔浑水，雕沈莽苍云。沙田积蒿艾，竟夕见烧焚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 王母祠前写望 ----------
    {
        "id": "yu-fu-19",
        "title": "王母祠前写望",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "云霞千古事，桃李旧花颜。芳信沈青鸟，空祠掩暮山。",
            "香传一座暗，柳匝万家闲。那复伤神所，河昏落日间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 游暖泉精舍 ----------
    {
        "id": "yu-fu-20",
        "title": "游暖泉精舍",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "坞木殿前空，山河泽国同。鸟闲沙影上，泉落树阴中。",
            "缆舸蒲花水，萦幡柳絮风。翛然方寸地，何事更悲蓬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 怀乡 ----------
    {
        "id": "yu-fu-21",
        "title": "怀乡",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "秋风江上家，钓艇泊芦花。断岸绿杨荫，疏篱红槿遮。",
            "鼍鸣积雨窟，鹤步夕阳沙。抱疾僧窗夜，归心过月斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 岫禅师南溪兰若 ----------
    {
        "id": "yu-fu-22",
        "title": "岫禅师南溪兰若",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "锡影配瓶光，孤溪照草堂。水悬青石磴，钟动白云床。",
            "树色含残雨，河流带夕阳。唯应无月夜，瞑目见他方。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 龙翔寺寄李频 ----------
    {
        "id": "yu-fu-23",
        "title": "龙翔寺寄李频",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "钟声南北寺，不道往来遥。人事因循过，时光荏苒销。",
            "悬灯洒砌雨，上阁绕云雕。即是洲中柳，嘶蝉急暮条。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 送武瑴之邠宁 ----------
    {
        "id": "yu-fu-24",
        "title": "送武瑴之邠宁",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "戍路少人踪，边烟淡复浓。诗宁写别恨，酒不上离容。",
            "燕拂沙河柳，鸦高石窟钟。悠然一暌阻，山叠虏云重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 夏日题岫禅师房 ----------
    {
        "id": "yu-fu-25",
        "title": "夏日题岫禅师房",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "朝朝声磬罢，章子扫藤阴。花过少游客，日长无事心。",
            "回山闭院直，落水下桥深。安得开方便，容身老此林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 夏日因怀阳羡旧游寄裴书记 ----------
    {
        "id": "yu-fu-26",
        "title": "夏日因怀阳羡旧游寄裴书记",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "落日太湖西，波涵万象低。藕花熏浦溆，菱蔓匿凫鹥。",
            "树及长桥尽，滩回七里迷。还应坐筹暇，时一梦荆溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 呈薛博士 ----------
    {
        "id": "yu-fu-27",
        "title": "呈薛博士",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "辛勤长在学，一室少曾开。时忆暮山寺，独登衰草台。",
            "名期五字立，迹愧九年来。此意今聊写，还希君子哀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 即事 ----------
    {
        "id": "yu-fu-28",
        "title": "即事",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "抱杖立溪口，迎秋看塞门。连山互苍翠，二水各清浑。",
            "笛发孤烟戍，鸦归夕照村。萋萋芳草色，终是忆王孙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 龙翔寺阁夜怀渭南张少府 ----------
    {
        "id": "yu-fu-29",
        "title": "龙翔寺阁夜怀渭南张少府",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "春城带病别，秋塞见除书。况是神仙吏，仍非尘土居。",
            "河风吹鸟迥，岳雨滴桐疏。坐阁驰思夕，沙东凉月虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 夏日龙翔寺居即事寄崔侍御 ----------
    {
        "id": "yu-fu-30",
        "title": "夏日龙翔寺居即事寄崔侍御",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "古刹一幡斜，吹门水过沙。数声钟里饭，双影树间茶。",
            "落日穷荒雨，微风古堑花。何当戴豸客，复此问生涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 龙翔寺居喜胡权见访因宿 ----------
    {
        "id": "yu-fu-31",
        "title": "龙翔寺居喜胡权见访因宿",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "林栖无异欢，煮茗就花栏。雀啅北冈晓，僧开西阁寒。",
            "冲桥二水急，扣月一钟残。明发还分手，徒悲行路难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 宿石窟寺 ----------
    {
        "id": "yu-fu-32",
        "title": "宿石窟寺",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "一刹古冈南，孤钟撼夕岚。客闲明月阁，僧闭白云庵。",
            "野鹤立枯枿，天龙吟净潭。因知不生理，合自此中探。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 夏日龙翔寺寄张侍御 ----------
    {
        "id": "yu-fu-33",
        "title": "夏日龙翔寺寄张侍御",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "沙西林杪寺，殿倚石棱开。晓月僧汲井，残阳钟殷台。",
            "河冲绿野去，鸟背白云来。日夕唯增思，京关未想回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 秋日将归长安留别王尚书 ----------
    {
        "id": "yu-fu-34",
        "title": "秋日将归长安留别王尚书",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "朔漠正秋霖，西风传夕砧。沧洲未归迹，华发受恩心。",
            "露色冈莎冷，蝉声坞木深。清晨鈇钺内，只献白云吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 龙翔寺言怀 ----------
    {
        "id": "yu-fu-35",
        "title": "龙翔寺言怀",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "眠云喜道存，读易过朝昏。乔木青连郭，长河白泻门。",
            "钟沈残月坞，鸟去夕阳村。搜此成闲句，期逢作者论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 龙翔寺居夏日寄献王尚书 ----------
    {
        "id": "yu-fu-36",
        "title": "龙翔寺居夏日寄献王尚书",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "那期高旆下，得遇重臣知。泉石容居止，风沙免路岐。",
            "河兼落下望，句入大荒思。无复愁烦暑，回山翠阁危。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 题弘济寺不出院僧 ----------
    {
        "id": "yu-fu-37",
        "title": "题弘济寺不出院僧",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "楚鞋应此世，只绕砌苔休。色相栽花视，身心坐石修。",
            "声寒通节院，城黑见烽楼。欲取闲云并，闲云有去留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 寄刘录事 ----------
    {
        "id": "yu-fu-38",
        "title": "寄刘录事",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "城西青岛寺，累夏漱寒泉。今在提纲所，应难扫石眠。",
            "风沙榆塞迥，波浪橘洲偏。重整潇湘棹，心期更几年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 酬王檀见寄 ----------
    {
        "id": "yu-fu-39",
        "title": "酬王檀见寄",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "驰心栖杳冥，何物比清泠。夜月照巫峡，秋风吹洞庭。",
            "酬难尘鬓皓，坐久壁灯青。竟晚苍山咏，乔枝有鹤听。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 寺居秋日对雨有怀 ----------
    {
        "id": "yu-fu-40",
        "title": "寺居秋日对雨有怀",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "修修复雭雭，黄叶此时飞。隐几客吟断，邻房僧话稀。",
            "鸽寒栖树定，萤湿在窗微。即事潇湘渚，渔翁披草衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 答刘录事夜月怀湘西友人见寄 ----------
    {
        "id": "yu-fu-41",
        "title": "答刘录事夜月怀湘西友人见寄",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "相逢仍朔漠，相问即波涛。江思苇花折，笛声关月高。",
            "簿书君阅倦，章句我吟劳。竟夕空凭阁，长河漴石壕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 上高侍御 ----------
    {
        "id": "yu-fu-42",
        "title": "上高侍御",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "旧隐白云峰，生涯落叶同。关河一栖旅，杨柳十东风。",
            "迹处龙钟内，声居汩没中。酬恩若有地，宁止杀微躬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 冬日寄友人 ----------
    {
        "id": "yu-fu-43",
        "title": "冬日寄友人",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "空为梁甫吟，谁竟是知音。风雪坐闲夜，乡园来旧心。",
            "沧江孤棹迥，落日一钟深。君子久忘我，此诚甘自沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 冬夜宿余正字静恭里闲居 ----------
    {
        "id": "yu-fu-44",
        "title": "冬夜宿余正字静恭里闲居",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "每来多便宿，不负白云言。古木朔风动，寒城疏雪翻。",
            "微灯悬刻漏，旧梦返湘沅。先是琴边起，知为阁务繁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 得子侄书 ----------
    {
        "id": "yu-fu-45",
        "title": "得子侄书",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "远书来阮巷，阙下见江东。不得经史力，枉抛耕稼功。",
            "雁天霞脚雨，渔夜苇条风。无复琴杯兴，开怀向尔同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 献知己 ----------
    {
        "id": "yu-fu-46",
        "title": "献知己",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "亦忝受恩身，当殊投刺新。竟蒙分玉石，终不离埃尘。",
            "大谷非无暖，幽枝自未春。昏昏过朝夕，应念苦吟人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 赠张濆处士 ----------
    {
        "id": "yu-fu-47",
        "title": "赠张濆处士",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "露白覆棋宵，林青读易朝。道高天子问，名重四方招。",
            "许鹤归华顶，期僧过石桥。虽然在京国，心迹自逍遥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 早秋寺居酬张侍御六韵见寄 ----------
    {
        "id": "yu-fu-48",
        "title": "早秋寺居酬张侍御六韵见寄",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "六十上清冥，晓缄东越藤。山光紫衣陟，寺影白云凝。",
            "湿叶起寒鸟，深林惊古僧。微风窗静展，细雨阁吟登。",
            "清韵岳磬远，佳音湖水澄。却思前所献，何以豸冠称。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 和段学士对雪 ----------
    {
        "id": "yu-fu-49",
        "title": "和段学士对雪",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "盈尺知丰稔，开窗对酒壶。飘当大野匝，洒到急流无。",
            "密际西风尽，凝间朔气扶。干摧鸟栖枿，冷射夜残垆。",
            "赞月登斜汉，兼沙搅北湖。惭于郢客坐，一此调巴歈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 监试夜雨滴空阶 ----------
    {
        "id": "yu-fu-50",
        "title": "监试夜雨滴空阶",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "霎霎复凄凄，飘松又洒槐。气濛蛛网槛，声叠藓花阶。",
            "古壁青灯动，深庭湿叶埋。徐垂旧鸳瓦，竞历小茅斋。",
            "冷与阴虫间，清将玉漏谐。病身唯展转，谁见此时怀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 春雨如膏 ----------
    {
        "id": "yu-fu-51",
        "title": "春雨如膏",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "幂幂敛轻尘，濛濛湿野春。细光添柳重，幽点溅花匀。",
            "惨淡游丝景，阴沈落絮辰。回低飞蝶翅，寒滴语禽身。",
            "洒岳摧馀雪，吹江叠远蘋。东城与西陌，晴后趣何新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 送友人南中访旧知 ----------
    {
        "id": "yu-fu-52",
        "title": "送友人南中访旧知",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "春尽大方游，思君便白头。地蒸川有毒，天暖树无秋。",
            "水急三巴险，猿分五岭愁。为缘知己分，南国必淹留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 玄都观李尊师 ----------
    {
        "id": "yu-fu-53",
        "title": "玄都观李尊师",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "藓帻翠髯公，存思古观空。晓坛柽叶露，晴圃柳花风。",
            "寿已将椿并，棋难见局终。何当与高鹤，飞去海光中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 送石贲归吴兴 ----------
    {
        "id": "yu-fu-54",
        "title": "送石贲归吴兴",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "同志幸同年，高堂君独还。齐荣恩未报，共隐事皆闲。",
            "访寺临河岸，开楼见海山。洛中推二陆，莫久恋乡关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 感遇 ----------
    {
        "id": "yu-fu-55",
        "title": "感遇",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "江乡十年别，京国累日同。在客几多事，俱付酒杯中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 晚思 ----------
    {
        "id": "yu-fu-56",
        "title": "晚思",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "鹤下紫阁云，沈沈翠微雨。独坐正无言，孤庄一声杵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 赠空禅师 ----------
    {
        "id": "yu-fu-57",
        "title": "赠空禅师",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "虎见修行久，松知夏腊高。寒堂坐风雨，瞑目尚波涛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 西山寒日逢韦侍御 ----------
    {
        "id": "yu-fu-58",
        "title": "西山寒日逢韦侍御",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "獬豸霜中貌，龙钟病后颜。惨伤此身事，风雪动江山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 题禅院 ----------
    {
        "id": "yu-fu-59",
        "title": "题禅院",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "无花地亦香，有鹤松多直。向此奚必孤，山僧尽相识。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 惊秋 ----------
    {
        "id": "yu-fu-60",
        "title": "惊秋",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "莺啭才间关，蝉鸣旋萧屑。如何两鬓毛，不作千枝雪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 经刘校书墓 ----------
    {
        "id": "yu-fu-61",
        "title": "经刘校书墓",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "远冢松回曲渚风，一官闻是校书终。",
            "霜情月思今何在，零落人间策子中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 蒋处士宅喜闲公至 ----------
    {
        "id": "yu-fu-62",
        "title": "蒋处士宅喜闲公至",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "绝杯夏别螺江渡，单钵春过处士斋。",
            "尝茗议空经不夜，照花明月影侵阶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 绝句（一作忆友人） ----------
    {
        "id": "yu-fu-63",
        "title": "绝句（一作忆友人）",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "银地无尘金菊开，紫梨红枣堕莓苔。",
            "一泓秋水一轮月，今夜故人来不来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 句 ----------
    {
        "id": "yu-fu-64",
        "title": "句",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "颜凋明镜觉，思苦白云知。",
            "沧洲迷钓隐，紫阁负僧期。（见张为《主客图》）。",
            "第五百四十四卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 樊川寒食 ----------
    {
        "id": "yu-fu-65",
        "title": "樊川寒食",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "新松□绿草，古柏翳黄沙。珮珂客惊鸟，绮罗人间花。",
            "蹙尘南北马，碾石去来车。川晚悲风动，坟前碎纸斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 句 ----------
    {
        "id": "yu-fu-66",
        "title": "句",
        "author": "喻凫",
        "poet_id": "yu-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "虹横布水台南雨，雁返炉峰顶北霞。（《送欧阳孝廉",
            "及第归彭泽》）",
            "闲卧东风灯渐晓，溪南花气雨中来。（《溪居雨夜》）",
            "一别山阴诗酒客，水风花片梦兰亭。（《寄山阴李处士》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]