# -*- coding: utf-8 -*-
"""
江为卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 旅怀 ----------
    {
        "id": "jiang-wei-1",
        "title": "旅怀",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "迢迢江汉路，秋色又堪惊。半夜闻鸿雁，多年别弟兄。",
            "高风云影断，微雨菊花明。欲寄东归信，裴回无限情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 江行 ----------
    {
        "id": "jiang-wei-2",
        "title": "江行",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "越信隔年稀，孤舟几梦归。月寒花露重，江晚水烟微。",
            "峰直帆相望，沙空鸟自飞。何时洞庭上，春雨满蓑衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 登润州城 ----------
    {
        "id": "jiang-wei-3",
        "title": "登润州城",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "天末江城晚，登临客望迷。春潮平岛屿，残雨隔虹霓。",
            "鸟与孤帆远，烟和独树低。乡山何处是，目断广陵西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 岳阳楼 ----------
    {
        "id": "jiang-wei-4",
        "title": "岳阳楼",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "倚楼高望极，展转念前途。晚叶红残楚，秋江碧入吴。",
            "云中来雁急，天末去帆孤。明月谁同我，悠悠上帝都。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送客 ----------
    {
        "id": "jiang-wei-5",
        "title": "送客",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "明月孤舟远，吟髭镊更华。天形围泽国，秋色露人家。",
            "水馆萤交影，霜洲橘委花。何当寻旧隐，泉石好生涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 临刑诗 ----------
    {
        "id": "jiang-wei-6",
        "title": "临刑诗",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "街鼓侵人急，西倾日欲斜。黄泉无旅店，今夜宿谁家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 塞下曲 ----------
    {
        "id": "jiang-wei-7",
        "title": "塞下曲",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "万里黄云冻不飞，碛烟烽火夜深微。",
            "胡儿移帐寒笳绝，雪路时闻探马归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 隋堤柳 ----------
    {
        "id": "jiang-wei-8",
        "title": "隋堤柳",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "锦缆龙舟万里来，醉乡繁盛忽尘埃。",
            "空馀两岸千株柳，雨叶风花作恨媒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 句 ----------
    {
        "id": "jiang-wei-9",
        "title": "句",
        "author": "江为",
        "poet_id": "jiang-wei",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "吟登萧寺旃檀阁，醉倚王家玳瑁筵。（《题白鹿寺》）",
            "远远朝宗出白云，方圆随处性长存。（《水》，",
            "见《吟窗杂录》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]