# -*- coding: utf-8 -*-
"""
皇甫曾卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 50 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 奉陪韦中丞使君游鹤林寺 ----------
    {
        "id": "huang-fu-ceng-1",
        "title": "奉陪韦中丞使君游鹤林寺",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "古寺传灯久，层城闭阁闲。香花同法侣，旌旆入深山。",
            "寒磬虚空里，孤云起灭间。谢公忆高卧，徒御欲东还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉送杜侍御还京（一作杜中丞，一作林中丞） ----------
    {
        "id": "huang-fu-ceng-2",
        "title": "奉送杜侍御还京（一作杜中丞，一作林中丞）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "罢战回龙节，朝天上凤池。寒生五湖道，春入万年枝。",
            "召化多遗爱，胡清已畏知。怀恩偏感别，堕泪向旌麾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 酬郑侍御秋夜见寄 ----------
    {
        "id": "huang-fu-ceng-3",
        "title": "酬郑侍御秋夜见寄",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "摇落空林夜，河阳兴已生。未辞公府步，知结远山情。",
            "高柳风难定，寒泉月助明。袁公方卧雪，尺素及柴荆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 酬窦拾遗秋日见呈（时此公自江阴令除谏官） ----------
    {
        "id": "huang-fu-ceng-4",
        "title": "酬窦拾遗秋日见呈（时此公自江阴令除谏官）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "孤城永巷时相见，衰柳闲门日半斜。",
            "欲送近臣朝魏阙，犹怜残菊在陶家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 韦使君宅海榴咏 ----------
    {
        "id": "huang-fu-ceng-5",
        "title": "韦使君宅海榴咏",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "淮阳卧理有清风，腊月榴花带雪红。",
            "闭阁寂寥常对此，江湖心在数枝中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送普上人还阳羡（一作皇甫冉诗） ----------
    {
        "id": "huang-fu-ceng-6",
        "title": "送普上人还阳羡（一作皇甫冉诗）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "花宫难久别，道者忆千灯。残雪入林路，暮山归寺僧。",
            "日光依嫩草，泉响滴春冰。何用求方便，看心是一乘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送李中丞归本道（一作送人作使归） ----------
    {
        "id": "huang-fu-ceng-7",
        "title": "送李中丞归本道（一作送人作使归）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "上将还专席，双旌复出秦。关河三晋路，宾从五原人。",
            "孤戍云连海，平沙雪度春。酬恩看玉剑，何处有烟尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 和谢舍人雪夜寓直 ----------
    {
        "id": "huang-fu-ceng-8",
        "title": "和谢舍人雪夜寓直",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "禁省夜沉沉，春风雪满林。沧洲归客梦，青琐近臣心。",
            "挥翰宣鸣玉，承恩在赐金。建章寒漏起，更助掖垣深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 寻刘处士 ----------
    {
        "id": "huang-fu-ceng-9",
        "title": "寻刘处士",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "几年人不见，林下掩柴关。留客当清夜，逢君话旧山。",
            "隔城寒杵急，带月早鸿还。南陌虽相近，其如隐者闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 哭陆处士 ----------
    {
        "id": "huang-fu-ceng-10",
        "title": "哭陆处士",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "从此无期见，柴门对雪开。二毛逢世难，万恨掩泉台。",
            "返照空堂夕，孤城吊客回。汉家偏访道，犹畏鹤书来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 乌程水楼留别 ----------
    {
        "id": "huang-fu-ceng-11",
        "title": "乌程水楼留别",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "悠悠千里去，惜此一尊同。客散高楼上，帆飞细雨中。",
            "山程随远水，楚思在青枫。共说前期易，沧波处处同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 题赠吴门邕上人 ----------
    {
        "id": "huang-fu-ceng-12",
        "title": "题赠吴门邕上人",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "春山唯一室，独坐草萋萋。身寂心成道，花闲鸟自啼。",
            "细泉松径里，返景竹林西。晚与门人别，依依出虎溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送陆鸿渐山人采茶回 ----------
    {
        "id": "huang-fu-ceng-13",
        "title": "送陆鸿渐山人采茶回",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "千峰待逋客，香茗复丛生。采摘知深处，烟霞羡独行。",
            "幽期山寺远，野饭石泉清。寂寂燃灯夜，相思一磬声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 寄刘员外长卿 ----------
    {
        "id": "huang-fu-ceng-14",
        "title": "寄刘员外长卿",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "南忆新安郡，千山带夕阳。断猿知夜久，秋草助江长。",
            "疏发应成素，青松独耐霜。爱才称汉主，题柱待回乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 寄张仲甫 ----------
    {
        "id": "huang-fu-ceng-15",
        "title": "寄张仲甫",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "悲风生旧浦，云岭隔东田。伏腊同鸡黍，柴门闭雪天。",
            "孤村明夜火，稚子候归船。静者心相忆，离居畏度年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送元侍御充使湖南 ----------
    {
        "id": "huang-fu-ceng-16",
        "title": "送元侍御充使湖南",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "云梦南行尽，三湘万里流。山川重分手，徒御亦悲秋。",
            "白简劳王事，清猿助客愁。离群复多病，岁晚忆沧洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 晚至华阴 ----------
    {
        "id": "huang-fu-ceng-17",
        "title": "晚至华阴",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "腊尽促归心，行人及华阴。云霞仙掌出，松柏古祠深。",
            "野渡冰生岸，寒川烧隔林。温泉看渐近，宫树晚沈沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送孔征士 ----------
    {
        "id": "huang-fu-ceng-18",
        "title": "送孔征士",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "谷口山多处，君归不可寻。家贫青史在，身老白云深。",
            "扫雪开松径，疏泉过竹林。馀生负丘壑，相送亦何心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 秋兴 ----------
    {
        "id": "huang-fu-ceng-19",
        "title": "秋兴",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "流萤与落叶，秋晚共纷纷。返照城中尽，寒砧雨外闻。",
            "离人见衰鬓，独鹤暮何群。楚客在千里，相思看碧云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送归中丞使新罗 ----------
    {
        "id": "huang-fu-ceng-20",
        "title": "送归中丞使新罗",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "南幰衔恩去，东夷泛海行。天遥辞上国，水尽到孤城。",
            "已变炎凉气，仍愁浩淼程。云涛不可极，来往见双旌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送少微上人东南游 ----------
    {
        "id": "huang-fu-ceng-21",
        "title": "送少微上人东南游",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "石梁人不到，独往更迢迢。乞食山家少，寻钟野寺遥。",
            "松门风自扫，瀑布雪难消。秋夜闻清梵，馀音逐海潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送韦判官赴闽中 ----------
    {
        "id": "huang-fu-ceng-22",
        "title": "送韦判官赴闽中",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "孤棹闽中客，双旌海上军。路人从北少，海水向南分。",
            "野鹤伤秋别，林猿忌夜闻。汉家崇亚相，知子远邀勋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送人还荆州（一作李嘉祐诗） ----------
    {
        "id": "huang-fu-ceng-23",
        "title": "送人还荆州（一作李嘉祐诗）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "草色随骢马，悠悠同出秦。水传云梦晓，山接洞庭春。",
            "帆影连三峡，猿声近四邻。青门一分手，难见杜陵人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 寄净虚上人初至云门（一作刘长聊诗） ----------
    {
        "id": "huang-fu-ceng-24",
        "title": "寄净虚上人初至云门（一作刘长聊诗）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "寒踪白云里，法侣自提携。竹径通城下，松门隔水西。",
            "方同沃洲去，不似武陵迷。仿佛方知处，高峰是会稽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 春和杜相公移入长兴宅，奉呈诸宰执 ----------
    {
        "id": "huang-fu-ceng-25",
        "title": "春和杜相公移入长兴宅，奉呈诸宰执",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "欲向幽偏适，还从绝地移。秦官鼎食贵，尧世土阶卑。",
            "戟户槐阴满，书窗竹叶垂。才分午夜漏，遥隔万年枝。",
            "北阙深恩在，东林远梦知。日斜门掩映，山远树参差。",
            "论道齐鸳翼，题诗忆凤池。从公亦何幸，长与珮声随。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 路中口号 ----------
    {
        "id": "huang-fu-ceng-26",
        "title": "路中口号",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "还乡不见家，年老眼多泪。车马上河桥，城中好天气。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 山下泉 ----------
    {
        "id": "huang-fu-ceng-27",
        "title": "山下泉",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "漾漾带山光，澄澄倒林影。那知石上喧，却忆山中静。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 早朝日寄所知 ----------
    {
        "id": "huang-fu-ceng-28",
        "title": "早朝日寄所知",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "长安雪夜见归鸿，紫禁朝天拜舞同。曙色渐分双阙下，",
            "漏声遥在百花中。炉烟乍起开仙仗，玉佩才成引上公。",
            "共荷发生同雨露，不应黄叶久随风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 秋夕寄怀契上人 ----------
    {
        "id": "huang-fu-ceng-29",
        "title": "秋夕寄怀契上人",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "已见槿花朝委露，独悲孤鹤在人群。真僧出世心无事，",
            "静夜名香手自焚。窗临绝涧闻流水，客至孤峰扫白云。",
            "更想清晨诵经处，独看松上雪纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 张芬见访郊居作 ----------
    {
        "id": "huang-fu-ceng-30",
        "title": "张芬见访郊居作",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "林中雨散早凉生，已有迎秋促织声。三径荒芜羞对客，",
            "十年衰老愧称兄。愁心自惜江蓠晚，世事方看木槿荣。",
            "君若罢官携手日，寻山莫算白云程。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 赠鉴上人（一作赠别筌公） ----------
    {
        "id": "huang-fu-ceng-31",
        "title": "赠鉴上人（一作赠别筌公）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "律仪传教诱，僧腊老烟霄。树色依禅诵，泉声入寂寥。",
            "宝龛经末劫，画壁见南朝。深竹风开合，寒潭月动摇。",
            "息心归静理，爱道坐中宵。更欲寻真去，乘船过海潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 奉寄中书王舍人 ----------
    {
        "id": "huang-fu-ceng-32",
        "title": "奉寄中书王舍人",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "腰金载笔谒承明，至道安禅得此生，西掖几年纶綍贵，",
            "东山遥夜薜萝情。风传刻漏星河曙，月上梧桐雨露清。",
            "圣主好文谁为荐，闭门空赋子虚成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 送汤中丞和蕃 ----------
    {
        "id": "huang-fu-ceng-33",
        "title": "送汤中丞和蕃",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "继好中司出，天心外国知。已传尧雨露，更说汉威仪。",
            "陇上应回首，河源复载驰。孤峰问徒御，空碛见旌麾。",
            "春草乡愁起，边城旅梦移。莫嗟行远地，此去答恩私。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 送和西蕃使 ----------
    {
        "id": "huang-fu-ceng-34",
        "title": "送和西蕃使",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "白简初分命，黄金已在腰。恩华通外国，徒御发中朝。",
            "雨雪从边起，旌旗上陇遥。暮天沙漠漠，空碛马萧萧。",
            "寒路随河水，关城见柳条。和戎先罢战，知胜霍嫖姚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 送王相公赴幽州 ----------
    {
        "id": "huang-fu-ceng-35",
        "title": "送王相公赴幽州",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "台衮兼戎律，勤忧秉化元。凤池东掖宠，龙节北方尊。",
            "长路山河转，前驱鼓角喧。人安布时令，地远答君恩。",
            "暮日平沙迥，秋风大旆翻。渔阳在天末，恋别信陵门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 送徐大夫赴南海 ----------
    {
        "id": "huang-fu-ceng-36",
        "title": "送徐大夫赴南海",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "旧国当分阃，天涯答圣私。大军传羽檄，老将拜旌旗。",
            "位重登坛后，恩深弄印时。何年谏猎赋，今日饮泉诗。",
            "海内求民瘼，城隅见岛夷。由来黄霸去，自有上台期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 赠沛禅师 ----------
    {
        "id": "huang-fu-ceng-37",
        "title": "赠沛禅师",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "南岳满湘沅，吾师经利涉。身归沃洲老，名与支公接。",
            "净教传荆吴，道缘止渔猎。观空色不染，对境心自惬。",
            "室中人寂寞，门外山重叠。天台积幽梦，早晚当负笈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 萼岭四望 ----------
    {
        "id": "huang-fu-ceng-38",
        "title": "萼岭四望",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "汉家仙仗在咸阳，洛水东流出建章。",
            "野老至今犹望幸，离宫秋树独苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 过刘员外长卿别墅（一作碧涧别业） ----------
    {
        "id": "huang-fu-ceng-39",
        "title": "过刘员外长卿别墅（一作碧涧别业）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "谢客开山后，郊扉积水通。江湖千里别，衰老一尊同。",
            "返照寒川满，平田暮雪空。沧洲自有趣，不便哭途穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 遇风雨作（一作权德舆诗） ----------
    {
        "id": "huang-fu-ceng-40",
        "title": "遇风雨作（一作权德舆诗）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "草草理夜装，涉江又登陆。望路殊未穷，指期今已促。",
            "传呼戒徒驭，振辔转林麓。阴云拥岩端，沾雨当山腹。",
            "震雷如在耳，飞电来照目。兽迹不敢窥，马蹄惟务速。",
            "虔心若斋祷，濡体如沐浴。万窍相怒号，百泉暗奔瀑。",
            "危梁虑足跌，峻坂忧车覆。问我何以然，前日爱微禄。",
            "转知人代事，缨组乃徽束。向若家居时，安枕春梦熟。",
            "遵途稍已近，候吏来相续。晓霁心始安，林端见初旭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 送商州杜中丞赴任 ----------
    {
        "id": "huang-fu-ceng-41",
        "title": "送商州杜中丞赴任",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "安康地理接商於，帝命专城总赋舆。夕拜忽辞青琐闼，",
            "晨装独捧紫泥书。深山古驿分驺骑，芳草闲云逐隼旟。",
            "绮皓清风千古在，因君一为谢岩居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送著公归越 ----------
    {
        "id": "huang-fu-ceng-42",
        "title": "送著公归越",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "谁能愁此别，到越会相逢。长忆云门寺，门前千万峰。",
            "石床埋积雪，山路倒枯松。莫学白居士，无人知去踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送郑秀才贡举 ----------
    {
        "id": "huang-fu-ceng-43",
        "title": "送郑秀才贡举",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "西去意如何，知随贡士科。吟诗向月路，驱马出烟萝。",
            "晚色寒芜远，秋声候雁多。自怜归未得，相送一劳歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 锡杖歌，送明楚上人归佛川（一作权德舆诗） ----------
    {
        "id": "huang-fu-ceng-44",
        "title": "锡杖歌，送明楚上人归佛川（一作权德舆诗）",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "上人远自西天至，头陀行遍南朝寺。口翻贝叶古字经，",
            "手持金策声泠泠。护法护身惟振锡，石濑云溪深寂寂。",
            "乍来松径风露寒，遥映霜天月成魄。后夜空山禅诵时，",
            "寥寥挂在枯树枝。真法尝传心不住，东西南北随缘路。",
            "佛川此去何时回，应真莫便游天台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 玉山岭上作 ----------
    {
        "id": "huang-fu-ceng-45",
        "title": "玉山岭上作",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "悠悠驱匹马，征路上连冈。晚翠深云窦，寒台净石梁。",
            "秋花偏似雪，枫叶不禁霜。愁见前程远，空郊下夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 国子柳博士兼领太常博士，辄申贺赠 ----------
    {
        "id": "huang-fu-ceng-46",
        "title": "国子柳博士兼领太常博士，辄申贺赠",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "博士本秦官，求才帖职难。临风曲台净，对月碧池寒。",
            "讲学分阴重，斋祠晓漏残。朝衣辨色处，双绶更宜看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 送裴秀才贡举 ----------
    {
        "id": "huang-fu-ceng-47",
        "title": "送裴秀才贡举",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "儒衣羞此别，去抵汉公卿。宾贡年犹少，篇章艺已成。",
            "临流惜暮景，话别起乡情。离酌不辞醉，西江春草生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 赠老将 ----------
    {
        "id": "huang-fu-ceng-48",
        "title": "赠老将",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "白草黄云塞上秋，曾随骠骑出并州。",
            "辘轳剑折虬髯白，转战功多独不侯。",
            "第二百一十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 建元寺昼公与崔秀才见过联句，与郑奉礼说同作 ----------
    {
        "id": "huang-fu-ceng-49",
        "title": "建元寺昼公与崔秀才见过联句，与郑奉礼说同作",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "人闲宜岁晚，道者访幽期。独与寒山别，行当暮雪时。--皇甫曾",
            "柏台辞汉主，竹寺寄潜师。荷策知君待，开门笑我迟。--皎然",
            "暮阶县雨足，寒吹绕松枝，理辩尘心妄，经分梵字疑。--郑说",
            "久承黄纸诏，曾赋碧云诗。然诺惊相许，风流话所思。--崔子向",
            "筌忘心己默，磬发夜何其。愿结求羊侣，名山从所之。--皇甫曾",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 建元寺西院寄李员外纵联句 ----------
    {
        "id": "huang-fu-ceng-50",
        "title": "建元寺西院寄李员外纵联句",
        "author": "皇甫曾",
        "poet_id": "huang-fu-ceng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "寄隐霜台客，相思粉署人。--崔子向",
            "诚知阡陌近，无奈别离频。--皇甫曾",
            "夜色迷双树，钟声警四邻。--郑说",
            "散才徒仰鲍，归梦远知秦。--台上",
            "雨带清笳发，花惊夕漏春。--皎然",
            "招摇随步锡，仿佛听行轮。--崔子向",
            "要路推高足，空林寄一身。--皇甫曾",
            "盛名知独擅，良会忆相亲。--郑说",
            "稍涤心中垢，都遗陌上尘。--崔子向",
            "今宵此堂集，何事少遗民。--皎然",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]