# -*- coding: utf-8 -*-
"""
褚亮卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 35 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 乐府杂曲·鼓吹曲辞·临高台 ----------
    {
        "id": "chu-liang-1",
        "title": "乐府杂曲·鼓吹曲辞·临高台",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "高台暂俯临，飞翼耸轻音。浮光随日度，漾影逐波深。",
            "迥瞰周平野，开怀畅远襟。独此三休上，还伤千岁心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 祈谷乐章·肃和 ----------
    {
        "id": "chu-liang-2",
        "title": "祈谷乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "履艮斯绳，居中体正。龙运垂祉，昭符启圣。",
            "式事严禋，聿怀嘉庆。惟帝永锡，时皇休命。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 祈谷乐章·雍和 ----------
    {
        "id": "chu-liang-3",
        "title": "祈谷乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "殷荐乘春，太坛临曙。八簋盈和，六瑚登御。",
            "嘉稷匪歆，德馨斯饫。祝嘏无易，灵心有豫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 祈谷乐章·舒和 ----------
    {
        "id": "chu-liang-4",
        "title": "祈谷乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "玉帛牺牲申敬享，金丝戚羽盛音容。",
            "庶俾亿龄禔景福，长欣万宇洽时邕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 明堂乐章·肃和 ----------
    {
        "id": "chu-liang-5",
        "title": "明堂乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "象天御宇，乘时布政。严配申虔，宗禋展敬。",
            "樽罍盈列，树羽交映。玉币通诚，祚隆皇圣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 明堂乐章·雍和 ----------
    {
        "id": "chu-liang-6",
        "title": "明堂乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "八牖晨披，五精朝奠。雾凝璇篚，风清金悬。",
            "神涤备全，明粢丰衍。载絜彝俎，陈诚以荐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 明堂乐章·舒和 ----------
    {
        "id": "chu-liang-7",
        "title": "明堂乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "御扆合宫承宝历，席图重馆奉明灵。",
            "偃武修文九围泰，沉烽静柝八荒宁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 雩祀乐章·肃和 ----------
    {
        "id": "chu-liang-8",
        "title": "雩祀乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "朱鸟开辰，苍龙启映。大帝昭飨，群生展敬。",
            "礼备怀柔，功宣舞咏。旬液应序，年祥叶庆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 雩祀乐章·雍和 ----------
    {
        "id": "chu-liang-9",
        "title": "雩祀乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "绀筵分彩，宝图吐绚。凤管晨凝，云歌晓啭。",
            "肃事蘋藻，虔申桂奠。百谷斯登，万箱攸荐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 雩祀乐章·舒和 ----------
    {
        "id": "chu-liang-10",
        "title": "雩祀乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "凤曲登歌调令序，龙雩集舞泛祥风。",
            "彩旞云回昭睿德，朱干电发表神功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 享先农乐章·诚和 ----------
    {
        "id": "chu-liang-11",
        "title": "享先农乐章·诚和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "粒食伊始，农之所先。古今攸赖，是曰人天。",
            "耕斯帝籍，播厥公田。式崇明祀，神其福焉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 享先农乐章·肃和 ----------
    {
        "id": "chu-liang-12",
        "title": "享先农乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "樽彝既列，瑚簋方荐。歌工载登，币礼斯奠。",
            "肃肃享祀，颙颙缨弁。神之听之，福流寰县。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 享先农乐章·雍和 ----------
    {
        "id": "chu-liang-13",
        "title": "享先农乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "前夕视牲，质明奉俎。沐芳整弁，其仪式序。",
            "盛礼毕陈，嘉乐备举。歆我懿德，非馨稷黍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 享先农乐章·舒和 ----------
    {
        "id": "chu-liang-14",
        "title": "享先农乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "羽籥低昂文缀已，干戚蹈厉武行初。",
            "望岁祈农神所听，延祥介福岂云虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 祭神州乐章·肃和 ----------
    {
        "id": "chu-liang-15",
        "title": "祭神州乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "大矣坤仪，至哉神县。包含日域，牢笼月竁。",
            "露絜三清，风调六变。皇祇届止，式歆恭荐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 祭神州乐章·雍和 ----------
    {
        "id": "chu-liang-16",
        "title": "祭神州乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "泰圻严享，阴郊展敬。礼以导神，乐以和性。",
            "黝牲在列，黄琮俯映。九土既平，万邦贻庆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 祭神州乐章·舒和 ----------
    {
        "id": "chu-liang-17",
        "title": "祭神州乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "坤道降祥和庶品，灵心载德厚群生。",
            "水土既调三极泰，文武毕备九区平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 祭方丘乐章·顺和 ----------
    {
        "id": "chu-liang-18",
        "title": "祭方丘乐章·顺和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "万物资以化，交泰属升平。易从业惟简，得一道斯宁。",
            "具仪光玉帛，送舞变咸英。黍稷良非贵，明德信惟馨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 祭方丘乐章·肃和 ----------
    {
        "id": "chu-liang-19",
        "title": "祭方丘乐章·肃和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "至矣坤德，皇哉地祇。开元统纽，合大承规。",
            "九宫肃列，六典相仪。永言配命，长保无亏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 祭方丘乐章·雍和 ----------
    {
        "id": "chu-liang-20",
        "title": "祭方丘乐章·雍和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "柔而能方，直而能敬。厚载以德，大亨以正。",
            "有涤斯牷，有馨斯盛。介兹景福，祚我休庆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 祭方丘乐章·舒和 ----------
    {
        "id": "chu-liang-21",
        "title": "祭方丘乐章·舒和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "玉币牲牷分荐享，羽旄干戚递成容。",
            "一德惟宁两仪泰，三材保合四时邕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 祭方丘乐章·顺和 ----------
    {
        "id": "chu-liang-22",
        "title": "祭方丘乐章·顺和",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "阴祇协赞，厚载方贞。牲币具举，箫管备成。",
            "其礼惟肃，其德惟明。神之听矣，式鉴虔诚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 临高台 ----------
    {
        "id": "chu-liang-23",
        "title": "临高台",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "高台暂俯临，飞翼耸轻音。浮光随日度，漾影逐波深。",
            "回瞰周平野，开怀畅远襟。独此三休上，还伤千岁心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 赋得蜀都 ----------
    {
        "id": "chu-liang-24",
        "title": "赋得蜀都",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "列宿光参井，分芒跨梁岷。沉犀对江浦，驷马入城闉。",
            "英图多霸迹，历选有名臣。连骑簪缨满，含章词赋新。",
            "得上仙槎路，无待访严遵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 奉和咏日午 ----------
    {
        "id": "chu-liang-25",
        "title": "奉和咏日午",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "曦车日亭午，浮箭未移晖。日光无落照，树影正中围。",
            "草萎看稍靡，叶燥望疑稀。昼寝惭经笥，暂解入朝衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 奉和望月应魏王教 ----------
    {
        "id": "chu-liang-26",
        "title": "奉和望月应魏王教",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "层轩登皎月，流照满中天。色共梁珠远，光随赵璧圆。",
            "落影临秋扇，虚轮入夜弦。所欣东馆里，预奉西园篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 咏花烛（烛花） ----------
    {
        "id": "chu-liang-27",
        "title": "咏花烛（烛花）",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "兰径香风满，梅梁暖日斜。言是东方骑，来寻南陌车。",
            "靥星临夜烛，眉月隐轻纱。莫言春稍晚，自有镇开花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 在陇头哭潘学士 ----------
    {
        "id": "chu-liang-28",
        "title": "在陇头哭潘学士",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "陇底嗟长别，流襟一恸君。何言幽咽所，更作死生分。",
            "转蓬飞不息，悲松断更闻。谁能驻征马，回首望孤坟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 奉和禁苑饯别应令 ----------
    {
        "id": "chu-liang-29",
        "title": "奉和禁苑饯别应令",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "大藩初锡瑞，出牧迩皇京。暂以绿车重，言承朱传荣。",
            "舒桃临远骑，垂柳映京营。惠化宣千里，威风动百城。",
            "禁籞芳嘉节，神襟饯送情。金笳催别景，玉琯切离声。",
            "野花开更落，山鸟哢还惊。微臣夙多幸，薄宦奉储明。",
            "钓台惭作赋，伊水滥闻笙。怀德良知久，酬恩识命轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 和御史韦大夫喜霁之作 ----------
    {
        "id": "chu-liang-30",
        "title": "和御史韦大夫喜霁之作",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "晴天度旅雁，斜影照残虹。野净馀烟尽，山明远色同。",
            "沙平寒水落，叶脆晚枝空。白简光朝幰，彤驺出禁中。",
            "息驾游兰坂，雕文折桂丛。无因轻羽扇，徒自仰仁风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 晚别乐记室彦 ----------
    {
        "id": "chu-liang-31",
        "title": "晚别乐记室彦",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "穷途属岁晚，临水忽分悲。抱影同为客，伤情共此时。",
            "雾色侵虚牖，霜氛冷薄帷。举袂惨将别，停怀怅不怡。",
            "风严征雁远，雪暗去篷迟。他乡有岐路，游子欲何之。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 伤始平李少府正己 ----------
    {
        "id": "chu-liang-32",
        "title": "伤始平李少府正己",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "劳息本相循，悲欢理自均。谁能免玄夜，惜尔正青春。",
            "迈德惟家宝，生才谅国珍。高文缀翡翠，茂学掩麒麟。",
            "述作纷无已，言谈妙入神。断肠虽累月，分手未盈旬。",
            "辅嗣俄长往，颜生即短辰。声华满昭代，形影委穷尘。",
            "禅草回中使，生刍引吊宾。同游秘府日，方驾直城闉。",
            "并拜黄图右，分曹清渭滨。风期嵇吕好，存殁范张亲。",
            "虚座怜王述，遗篇恸景纯。精灵与毫翰，千祀寿何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 秋雁（一作虞世南诗） ----------
    {
        "id": "chu-liang-33",
        "title": "秋雁（一作虞世南诗）",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "日暮霜风急，羽翮转难任。为有传书意，翩翩入上林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 句（赠杜侍御） ----------
    {
        "id": "chu-liang-34",
        "title": "句（赠杜侍御）",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "神羊既不触，夕鸟欲依人。",
            "第三十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 宗庙九德之歌辞 ----------
    {
        "id": "chu-liang-35",
        "title": "宗庙九德之歌辞",
        "author": "褚亮",
        "poet_id": "chu-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "皇祖诞庆，于昭于天。积德斯远，茂攸绪先。",
            "维文应历，神武弘宣。肇迹□水，成功坂泉。",
            "道光覆载，声穆吉先。式备牺象，用□牲牷。",
            "礼终九献，乐展四悬。神贶景福，遐哉永年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]