# -*- coding: utf-8 -*-
"""
窦巩卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 40 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 老将行（一作吟） ----------
    {
        "id": "dou-gong-1",
        "title": "老将行（一作吟）",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷100》",
        "verse": [
            "烽烟犹未尽，年鬓暗相催。轻敌心空在，弯弓手不开。",
            "马依秋草病，柳傍故营摧。唯有酬恩客，时听说剑来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠萧都官 ----------
    {
        "id": "dou-gong-2",
        "title": "赠萧都官",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷101》",
        "verse": [
            "萧郎自小贤，爱客不言钱。有酒轻寒夜，无愁倚少年。",
            "闲寻织锦字，醉上看花船。好是关身事，从人道性偏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 忝职武昌，初至夏口，书事献府主相公 ----------
    {
        "id": "dou-gong-3",
        "title": "忝职武昌，初至夏口，书事献府主相公",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷102》",
        "verse": [
            "白发放櫜鞬，梁王爱旧全。竹篱江畔宅，梅雨病中天。",
            "时奉登楼宴，闲修上水船。邑人兴谤易，莫遣鹤支钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 早秋江行 ----------
    {
        "id": "dou-gong-4",
        "title": "早秋江行",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷103》",
        "verse": [
            "回望湓城远，西风吹荻花。暮潮江势阔，秋雨雁行斜。",
            "多醉浑无梦，频愁欲到家。渐惊云树转，数点是晨鸦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题任处士幽居 ----------
    {
        "id": "dou-gong-5",
        "title": "题任处士幽居",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷104》",
        "verse": [
            "红叶江村夕，孤烟草舍贫。水清鱼识钓，林静犬随人。",
            "采掇山无主，扶持药有神。客来唯劝酒，蝴蝶是前身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 汉阴驿与宇文十相遇，旋归西川，因以赠别 ----------
    {
        "id": "dou-gong-6",
        "title": "汉阴驿与宇文十相遇，旋归西川，因以赠别",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷105》",
        "verse": [
            "吴蜀何年别，相逢汉水头。望乡心共醉，握手泪先流。",
            "宿雾千山晓，春霖一夜愁。离情方浩荡，莫说去刀州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 早春松江野望 ----------
    {
        "id": "dou-gong-7",
        "title": "早春松江野望",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷106》",
        "verse": [
            "江村风雪霁，晓望忽惊春。耕地人来早，营巢鹊语频。",
            "带花移树小，插槿作篱新。何事胜无事，穷通任此身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 少妇词 ----------
    {
        "id": "dou-gong-8",
        "title": "少妇词",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷107》",
        "verse": [
            "坐惜年光变，辽阳信未通。燕迷新画屋，春识旧花丛。",
            "梦绕天山外，愁翻锦字中。昨来谁是伴，鹦鹉在帘栊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 岁晚喜远兄弟至书情 ----------
    {
        "id": "dou-gong-9",
        "title": "岁晚喜远兄弟至书情",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷108》",
        "verse": [
            "几年沧海别，相见竟多违。鬓发缘愁白，音书为懒稀。",
            "新诗徒有赠，故国未同归。人事那堪问，无言是与非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 登玉钩亭奉献淮南李相公 ----------
    {
        "id": "dou-gong-10",
        "title": "登玉钩亭奉献淮南李相公",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷109》",
        "verse": [
            "西南城上高高处，望月分明似玉钩。朱槛入云看鸟灭，",
            "绿杨如荠绕江流。定知有客嫌陈榻，从此无人上庾楼。",
            "今日卷帘天气好，不劳骑马看扬州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 南阳道中作 ----------
    {
        "id": "dou-gong-11",
        "title": "南阳道中作",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷110》",
        "verse": [
            "东风雨洗顺阳川，蜀锦花开绿草田。彩雉斗时频驻马，",
            "酒旗翻处亦留钱。新晴日照山头雪，薄暮人争渡口船。",
            "早晚到家春欲尽，今年寒食月初圆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 哭吕衡州八郎中 ----------
    {
        "id": "dou-gong-12",
        "title": "哭吕衡州八郎中",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷111》",
        "verse": [
            "今朝血泪问苍苍，不分先悲旅馆丧。人送剑来归陇上，",
            "雁飞书去叫衡阳。还家路远儿童小，埋玉泉深昼夜长。",
            "望尽素车秋草外，欲将身赎返魂香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 江陵遇元九李六二侍御纪事书情呈十二韵 ----------
    {
        "id": "dou-gong-13",
        "title": "江陵遇元九李六二侍御纪事书情呈十二韵",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷112》",
        "verse": [
            "自见人相爱，如君爱我稀。好闲容问道，攻短每言非。",
            "梦想何曾间，追欢未省违。看花怜后到，避酒许先归。",
            "柳寺春堤远，津桥曙月微。渔翁随去处，禅客共因依。",
            "蓬阁初疑义，霜台晚畏威。学深通古字，心直触危机。",
            "肯滞荆州掾，犹香柏署衣。山连巫峡秀，田傍渚宫肥。",
            "美玉方齐价，迁莺尚怯飞。伫看霄汉上，连步侍彤闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 游仙词 ----------
    {
        "id": "dou-gong-14",
        "title": "游仙词",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷113》",
        "verse": [
            "海上神山绿，溪边杏树红。不知何处去，月照玉楼空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 赠阿史那都尉 ----------
    {
        "id": "dou-gong-15",
        "title": "赠阿史那都尉",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷114》",
        "verse": [
            "较猎燕山经几春，雕弓白羽不离身。",
            "年来马上浑无力，望见飞鸿指似人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 陕府宾堂览房杜二公仁寿年中题纪手迹 ----------
    {
        "id": "dou-gong-16",
        "title": "陕府宾堂览房杜二公仁寿年中题纪手迹",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷115》",
        "verse": [
            "仁寿元和二百年，濛笼水墨淡如烟。",
            "当时憔悴题名日，汉祖龙潜未上天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 早春送宇文十归吴 ----------
    {
        "id": "dou-gong-17",
        "title": "早春送宇文十归吴",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷116》",
        "verse": [
            "春迟不省似今年，二月无花雪满天。",
            "村店闭门何处宿，夜深遥唤渡江船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 经窦车骑故城 ----------
    {
        "id": "dou-gong-18",
        "title": "经窦车骑故城",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷117》",
        "verse": [
            "荒陂古堞欲千年，名振图书剑在泉。",
            "今日诸孙拜坟树，愧无文字续燕然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 赠王氏小儿 ----------
    {
        "id": "dou-gong-19",
        "title": "赠王氏小儿",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷118》",
        "verse": [
            "竹林会里偏怜小，淮水清时最觉贤。",
            "莫倚儿童轻岁月，丈人曾共尔同年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 唐州东途作 ----------
    {
        "id": "dou-gong-20",
        "title": "唐州东途作",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷119》",
        "verse": [
            "绿林兵起结愁云，白羽飞书未解纷。",
            "天子欲开三面网，莫将弓箭射官军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 新罗进白鹰 ----------
    {
        "id": "dou-gong-21",
        "title": "新罗进白鹰",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷120》",
        "verse": [
            "御马新骑禁苑秋，白鹰来自海东头。",
            "汉皇无事须游猎，雪乱争飞锦臂鞲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 秋夕 ----------
    {
        "id": "dou-gong-22",
        "title": "秋夕",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷121》",
        "verse": [
            "护霜云映月朦胧，乌鹊争飞井上桐。",
            "夜半酒醒人不觉，满池荷叶动秋风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 襄阳寒食寄宇文籍 ----------
    {
        "id": "dou-gong-23",
        "title": "襄阳寒食寄宇文籍",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷122》",
        "verse": [
            "烟水初销见万家，东风吹柳万条斜。",
            "大堤欲上谁相伴，马踏春泥半是花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 奉使蓟门 ----------
    {
        "id": "dou-gong-24",
        "title": "奉使蓟门",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷123》",
        "verse": [
            "自从身属富人侯，蝉噪槐花已四秋。",
            "今日一茎新白发，懒骑官马到幽州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送刘禹锡 ----------
    {
        "id": "dou-gong-25",
        "title": "送刘禹锡",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷124》",
        "verse": [
            "十年憔悴武陵溪，鹤病深林玉在泥。",
            "今日太行平似砥，九霄初倚入云梯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送元稹西归 ----------
    {
        "id": "dou-gong-26",
        "title": "送元稹西归",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷125》",
        "verse": [
            "南州风土滞龙媒，黄纸初飞敕字来。",
            "二月曲江连旧宅，阿婆情熟牡丹开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 过骊山 ----------
    {
        "id": "dou-gong-27",
        "title": "过骊山",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷126》",
        "verse": [
            "翠辇红旌去不回，苍苍宫树锁青苔。",
            "有人说得当时事，曾见长生玉殿开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 洛中即事 ----------
    {
        "id": "dou-gong-28",
        "title": "洛中即事",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷127》",
        "verse": [
            "高梧叶尽鸟巢空，洛水潺湲夕照中。",
            "寂寂天桥车马绝，寒鸦飞入上阳宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 寻道者所隐不遇（一作于鹄诗，题作访隐者不遇） ----------
    {
        "id": "dou-gong-29",
        "title": "寻道者所隐不遇（一作于鹄诗，题作访隐者不遇）",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷128》",
        "verse": [
            "篱外涓涓涧水流，槿花半点夕阳收。",
            "欲题名字知相访，又恐芭蕉不奈秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 寄南游兄弟 ----------
    {
        "id": "dou-gong-30",
        "title": "寄南游兄弟",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷129》",
        "verse": [
            "书来未报几时还，知在三湘五岭间。",
            "独立衡门秋水阔，寒鸦飞去日衔山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 宫人斜 ----------
    {
        "id": "dou-gong-31",
        "title": "宫人斜",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷130》",
        "verse": [
            "离宫路远北原斜，生死恩深不到家。",
            "云雨今归何处去，黄鹂飞上野棠花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 代邻叟 ----------
    {
        "id": "dou-gong-32",
        "title": "代邻叟",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷131》",
        "verse": [
            "年来七十罢耕桑，就暖支羸强下床。",
            "满眼儿孙身外事，闲梳白发对残阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 新营别墅寄家兄 ----------
    {
        "id": "dou-gong-33",
        "title": "新营别墅寄家兄",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷132》",
        "verse": [
            "懒性如今成野人，行藏由兴不由身。",
            "莫惊此度归来晚，买得西山正值春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 南游感兴 ----------
    {
        "id": "dou-gong-34",
        "title": "南游感兴",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷133》",
        "verse": [
            "伤心欲问前朝事，惟见江流去不回。",
            "日暮东风春草绿，鹧鸪飞上越王台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 题剑津 ----------
    {
        "id": "dou-gong-35",
        "title": "题剑津",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷134》",
        "verse": [
            "风前推折千年剑，岩下澄空万古潭。",
            "双剑变成龙化去，两溪相并水归南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 放鱼（武昌作） ----------
    {
        "id": "dou-gong-36",
        "title": "放鱼（武昌作）",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷135》",
        "verse": [
            "金钱赎得免刀痕，闻道禽鱼亦感恩。",
            "好去长江千万里，不须辛苦上龙门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 永宁小园寄接近校书（一作羊士谔诗） ----------
    {
        "id": "dou-gong-37",
        "title": "永宁小园寄接近校书（一作羊士谔诗）",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷136》",
        "verse": [
            "故里心期奈别何，手栽芳树忆庭柯。",
            "东皋黍熟君应醉，梨叶初红白露多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 从军别家 ----------
    {
        "id": "dou-gong-38",
        "title": "从军别家",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷137》",
        "verse": [
            "自笑儒生著战袍，书斋壁上挂弓刀。",
            "如今便是征人妇，好织回文寄窦滔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 悼妓东东 ----------
    {
        "id": "dou-gong-39",
        "title": "悼妓东东",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷138》",
        "verse": [
            "芳菲美艳不禁风，未到春残已坠红。",
            "惟有侧轮车上铎，耳边长似叫东东。",
            "第二百七十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 自京师将赴黔南 ----------
    {
        "id": "dou-gong-40",
        "title": "自京师将赴黔南",
        "author": "窦巩",
        "poet_id": "dou-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "风雨荆州二月天，问人须雇峡中船。",
            "西南一望云和水，犹道黔南有四千。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]