# -*- coding: utf-8 -*-
"""
孔德绍卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 南隐游泉山 ----------
    {
        "id": "kong-de-shao-1",
        "title": "南隐游泉山",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "名山狎招隐，俗外远相求。还如倒景望，忽似阆风游。",
            "临崖俯大壑，披雾仰飞流。岁积松方偃，年深椿欲秋。",
            "野花开石镜，云叶掩山楼。何须问方士，此处即瀛洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 行经太华 ----------
    {
        "id": "kong-de-shao-2",
        "title": "行经太华",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "纷吾世网暇，灵岳展幽寻。寥廓风尘远，杳冥川谷深。",
            "山昏五里雾，日落二华阴。疏峰起莲叶，危塞隐桃林。",
            "何必东都外，此处可抽簪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 夜宿荒村 ----------
    {
        "id": "kong-de-shao-3",
        "title": "夜宿荒村",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "绵绵夕漏深，客恨转伤心。抚弦无人听，对酒时独斟。",
            "故乡万里绝，穷愁百虑侵。秋草思边马，绕枝惊夜禽。",
            "风度谷馀响，月斜山半阴。劳歌欲叙意，终是白头吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 王泽岭遭洪水 ----------
    {
        "id": "kong-de-shao-4",
        "title": "王泽岭遭洪水",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "地籁风声急，天津云色愁。悠然万顷满，俄尔百川浮。",
            "还似金堤溢，翻如碧海流。惊涛遥起鹭，回岸不分牛。",
            "徒知怀赵景，终是倦阳侯。木梗诚无托，芦灰岂暇求。",
            "思得乘槎便，萧然河汉游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 登白马山护明寺 ----------
    {
        "id": "kong-de-shao-5",
        "title": "登白马山护明寺",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "名岳标形胜，危峰远郁纡。成象建环极，大壮阐规模。",
            "层台耸灵鹫，高殿迩阳乌。暂同游阆苑，还类入仙都。",
            "三休开碧岭，万户洞金铺。摄心罄前礼，访道挹中虚。",
            "遥瞻尽地轴，长望极天隅。白云起梁栋，丹霞映栱栌。",
            "露花疑濯锦，泉月似沉珠。今日桃源客，相雇失归涂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送舍利宿定普岩 ----------
    {
        "id": "kong-de-shao-6",
        "title": "送舍利宿定普岩",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "仁祠表虚旷，祇园展肃恭。栖息翠微岭，登顿白云峰。",
            "映流看夜月，临峰听晓钟。涧芳十步草，崖阴百丈松。",
            "萧然遥路绝，无复市朝踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 观太常奏新乐 ----------
    {
        "id": "kong-de-shao-7",
        "title": "观太常奏新乐",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "大君膺宝历，出豫表功成。钧天金石响，洞庭弦管清。",
            "八音动繁会，九变叶希声。和云留睿赏，熏风悦圣情。",
            "盛烈光韶濩，易俗迈咸英。窃吹良无取，率舞抃群生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 赋得涉江采芙蓉 ----------
    {
        "id": "kong-de-shao-8",
        "title": "赋得涉江采芙蓉",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "莲舟泛锦碛，极目眺江干。沿流渡楫易，逆浪取花难。",
            "有雾疑川广，无风见水宽。朝来采摘倦，讵得久盘桓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 赋得华亭鹤 ----------
    {
        "id": "kong-de-shao-9",
        "title": "赋得华亭鹤",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "华亭失侣鹤，乘轩宠遂终。三山凌苦雾，千里激悲风。",
            "心危白露下，声断彩弦中。何言斯物变，翻覆似辽东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送蔡君知入蜀二首 ----------
    {
        "id": "kong-de-shao-10",
        "title": "送蔡君知入蜀二首",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "金陵已去国，铜梁忽背飞。失路远相送，他乡何日归。",
            "灵关九折险，蜀道二星遥。乘槎若有便，希泛广陵潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 落叶（一作孔绍安诗） ----------
    {
        "id": "kong-de-shao-11",
        "title": "落叶（一作孔绍安诗）",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "早秋惊叶落，飘零似客心。翻飞未肯下，犹言惜故林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 句 ----------
    {
        "id": "kong-de-shao-12",
        "title": "句",
        "author": "孔德绍",
        "poet_id": "kong-de-shao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "谁分菱花影，还看蓬鬓秋。（照镜见白发，《诗式》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]