# -*- coding: utf-8 -*-
"""
杨凝卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 39 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 送别 ----------
    {
        "id": "yang-ning-1",
        "title": "送别",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "樽酒邮亭暮，云帆驿使归。野鸥寒不起，川雨冻难飞。",
            "吴会家移遍，轩辕梦去稀。姓杨皆足泪，非是强沾衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送客东归 ----------
    {
        "id": "yang-ning-2",
        "title": "送客东归",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "君向古营州，边风战地愁。草青缦别路，柳亚拂孤楼。",
            "人意伤难醉，莺啼咽不流。芳菲只合乐，离思返如秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送客归湖南 ----------
    {
        "id": "yang-ning-3",
        "title": "送客归湖南",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "湖南树色尽，了了辨潭州。雨散今为别，云飞何处游。",
            "情来偏似醉，泪迸不成流。那向萧条路，缘湘篁竹愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送客归淮南 ----------
    {
        "id": "yang-ning-4",
        "title": "送客归淮南",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "画舫照河堤，暄风百草齐。行丝直网蝶，去燕旋遗泥。",
            "郡向高天近，人从别路迷。非关御沟上，今日各东西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 春情 ----------
    {
        "id": "yang-ning-5",
        "title": "春情",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "旧宅洛川阳，曾游游侠场。水添杨柳色，花绊绮罗香。",
            "赵瑟多愁曲，秦家足艳妆。江潭远相忆，春梦不胜长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 秋夜听捣衣 ----------
    {
        "id": "yang-ning-6",
        "title": "秋夜听捣衣",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "砧杵闻秋夜，裁缝寄远方。声微渐湿露，响细未经霜。",
            "兰牖唯遮树，风帘不碍凉。云中望何处，听此断人肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 从军行 ----------
    {
        "id": "yang-ning-7",
        "title": "从军行",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "都尉出居延，强兵集五千。还将张博望，直救范祁连。",
            "汉卒悲箫鼓，胡姬湿采旃。如今意气尽，流泪挹流泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 和直禁省 ----------
    {
        "id": "yang-ning-8",
        "title": "和直禁省",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "宵直丹宫近，风传碧树凉。漏稀银箭滴，月度网轩光。",
            "凤诏裁多暇，兰灯梦更长。此时颜范贵，十步旧连行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 留别 ----------
    {
        "id": "yang-ning-9",
        "title": "留别",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "玉节随东阁，金闺别旧僚。若为花满寺，跃马上河桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送客往洞庭 ----------
    {
        "id": "yang-ning-10",
        "title": "送客往洞庭",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "九江归路远，万里客舟还。若过巴江水，湘东满碧烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 别友人 ----------
    {
        "id": "yang-ning-11",
        "title": "别友人",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "倦客惊危路，伤禽绕树枝。非逢暴公子，不敢涕流离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 初渡淮北岸 ----------
    {
        "id": "yang-ning-12",
        "title": "初渡淮北岸",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "别梦虽难觉，悲魂最易销。殷勤淮北岸，乡近去家遥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 咏雨 ----------
    {
        "id": "yang-ning-13",
        "title": "咏雨",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "尘浥多人路，泥归足燕家。可怜缭乱点，湿尽满宫花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 柳絮 ----------
    {
        "id": "yang-ning-14",
        "title": "柳絮",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "河畔多杨柳，追游尽狭斜。春风一回送，乱入莫愁家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 花枕 ----------
    {
        "id": "yang-ning-15",
        "title": "花枕",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "席上沈香枕，楼中荡子妻。那堪一夜里，长湿两行啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送客往鄜州 ----------
    {
        "id": "yang-ning-16",
        "title": "送客往鄜州",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "新参将相事营平，锦带騂弓结束轻。晓上关城吟画角，",
            "暗驰羌马发支兵。回中地近风常急，鄜畤年多草自生。",
            "近喜扶阳系戎相，从来卫霍笑长缨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送客往夏州 ----------
    {
        "id": "yang-ning-17",
        "title": "送客往夏州",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "怜君此去过居延，古塞黄云共渺然。沙阔独行寻马迹，",
            "路迷遥指戍楼烟。夜投孤店愁吹笛，朝望行尘避控弦。",
            "闻有故交今从骑，何须著论更言钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 春霁晚望 ----------
    {
        "id": "yang-ning-18",
        "title": "春霁晚望",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "细雨晴深小苑东，春云开气逐光风。雄儿走马神光上，",
            "静女看花佛寺中。书剑学多心欲懒，田园荒废望频空。",
            "南归路极天连海，惟有相思明月同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 唐昌观玉蕊花 ----------
    {
        "id": "yang-ning-19",
        "title": "唐昌观玉蕊花",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "瑶华琼蕊种何年，萧史秦嬴向紫烟。",
            "时控彩鸾过旧邸，摘花持献玉皇前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 别李协 ----------
    {
        "id": "yang-ning-20",
        "title": "别李协",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "江边日暮不胜愁，送客沾衣江上楼。",
            "明月峡添明月照，蛾眉峰似两眉愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 初次巴陵 ----------
    {
        "id": "yang-ning-21",
        "title": "初次巴陵",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "西江浪接洞庭波，积水遥连天上河。",
            "乡信为凭谁寄去，汀洲燕雁渐来多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 上巳 ----------
    {
        "id": "yang-ning-22",
        "title": "上巳",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "帝京元巳足繁华，细管清弦七贵家。",
            "此日风光谁不共，纷纷皆是掖垣花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 春怨 ----------
    {
        "id": "yang-ning-23",
        "title": "春怨",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "花满帘栊欲度春，此时夫婿在咸秦。",
            "绿窗孤寝难成寐，紫燕双飞似弄人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 送客归常州 ----------
    {
        "id": "yang-ning-24",
        "title": "送客归常州",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "行到河边从此辞，寒天日远暮帆迟。",
            "可怜芳草成衰草，公子归时过绿时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送别 ----------
    {
        "id": "yang-ning-25",
        "title": "送别",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "春愁不尽别愁来，旧泪犹长新泪催。",
            "相思倘寄相思字，君到扬州扬子回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送客入蜀 ----------
    {
        "id": "yang-ning-26",
        "title": "送客入蜀",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "剑阁迢迢梦想间，行人归路绕梁山。",
            "明朝骑马摇鞭去，秋雨槐花子午关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 送别 ----------
    {
        "id": "yang-ning-27",
        "title": "送别",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "仙花笑尽石门中，石室重重掩绿空。",
            "暂下云峰能几日，却回烟驾驭春风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 残花 ----------
    {
        "id": "yang-ning-28",
        "title": "残花",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "五马踟蹰在路岐，南来只为看花枝。",
            "莺衔蝶弄红芳尽，此日深闺那得知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 戏赠友人 ----------
    {
        "id": "yang-ning-29",
        "title": "戏赠友人",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "湘阴直与地阴连，此日相逢忆醉年。",
            "美酒非如平乐贵，十升不用一千钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 赠同游 ----------
    {
        "id": "yang-ning-30",
        "title": "赠同游",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "此□风雨后，已觉减年华。若待皆无事，应难更有花。",
            "管弦临夜急，榆柳向江斜。且莫看归路，同须醉酒家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 送人出塞 ----------
    {
        "id": "yang-ning-31",
        "title": "送人出塞",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "北风吹雨雪，举目已凄凄。战鬼秋频哭，征鸿夜不栖。",
            "沙平关路直，碛广郡楼低。此去非东鲁，人多事鼓鼙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 寻僧元皎因病 ----------
    {
        "id": "yang-ning-32",
        "title": "寻僧元皎因病",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "此僧迷有著，因病得寻师。话尽山中事，归当月上时。",
            "高松连寺影，亚竹入窗枝。闲忆草堂路，相逢非素期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 夜泊渭津 ----------
    {
        "id": "yang-ning-33",
        "title": "夜泊渭津",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "飘飘东去客，一宿渭城边。远处星垂岸，中流月满船。",
            "凉归夜深簟，秋入雨馀天。渐觉家山小，残程尚几年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 晚夏逢友人 ----------
    {
        "id": "yang-ning-34",
        "title": "晚夏逢友人",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "一别同袍友，相思已十年。长安多在客，久病忽闻蝉。",
            "骤雨才沾地，阴云不遍天。微凉堪话旧，移榻晚风前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 别谪者 ----------
    {
        "id": "yang-ning-35",
        "title": "别谪者",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "此地闻犹恶，人言是所之。一家书绝久，孤驿梦成迟。",
            "八月三湘道，闻猿冒雨时。不须祠楚相，臣节转堪疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 行思 ----------
    {
        "id": "yang-ning-36",
        "title": "行思",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "千里岂云去，欲归如路穷。人间无暇日，马上又秋风。",
            "破月衔高岳，流星拂晓空。此时皆在梦，行色独匆匆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 感怀题从舅宅 ----------
    {
        "id": "yang-ning-37",
        "title": "感怀题从舅宅",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "郄家庭树下，几度醉春风。今日花还发，当时事不同。",
            "流言应未息，直道竟难通。徒遣相思者，悲歌向暮空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 与友人会 ----------
    {
        "id": "yang-ning-38",
        "title": "与友人会",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "蝉吟槐蕊落，的的是愁端。病觉离家远，贫知处事难。",
            "真交无所隐，深语有馀欢。未必闻歌吹，羁心得暂宽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 下第后蒙侍郎示意指于新先辈宣恩感谢 ----------
    {
        "id": "yang-ning-39",
        "title": "下第后蒙侍郎示意指于新先辈宣恩感谢",
        "author": "杨凝",
        "poet_id": "yang-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "才薄命如此，自嗟兼自疑。遭逢好交日，黜落至公时。",
            "倚玉甘无路，穿杨却未期。更惭君侍坐，问许可言诗。",
            "第二百九十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]