# -*- coding: utf-8 -*-
"""
袁晖卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 10 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·铜雀妓 ----------
    {
        "id": "yuan-hui-1",
        "title": "相和歌辞·铜雀妓",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "君爱本相饶，从来事舞腰。那堪攀玉座，肠断望陵朝。",
            "怨著情无主，哀凝曲不调。况临松日暮，悲吹坐萧萧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·长门怨 ----------
    {
        "id": "yuan-hui-2",
        "title": "相和歌辞·长门怨",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "早知君爱歇，本自无萦妒。谁使恩情深，今来反相误。",
            "愁眠罗帐晓，泣坐金闺暮。独有梦中魂，犹言意如故。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 长门怨 ----------
    {
        "id": "yuan-hui-3",
        "title": "长门怨",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "早知君爱歇，本自无萦妒。谁使恩情深，今来反相误。",
            "愁眠罗帐晓，泣坐金闺暮。独有梦中魂，犹言意如故。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 铜雀妓 ----------
    {
        "id": "yuan-hui-4",
        "title": "铜雀妓",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "君爱本相饶，从来似舞腰。那堪攀玉座，肠断望陵朝。",
            "怨著情无主，哀凝曲不调。况临松日暮，悲吹坐萧萧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 正月闺情 ----------
    {
        "id": "yuan-hui-5",
        "title": "正月闺情",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "正月金闺里，微风绣户间。晓魂怜别梦，春思逼啼颜。",
            "绕砌梅堪折，当轩树未攀。岁华庭北上，何日度阳关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 二月闺情 ----------
    {
        "id": "yuan-hui-6",
        "title": "二月闺情",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "二月韶光好，春风香气多。园中花巧笑，林里鸟能歌。",
            "有恨离琴瑟，无情著绮罗。更听春燕语，妾亦不如他。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 三月闺情 ----------
    {
        "id": "yuan-hui-7",
        "title": "三月闺情",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "三月春将尽，空房妾独居。蛾眉愁自结，鬓发没情梳。",
            "□□□□□，□□□□□。□□□□□，□□□□□。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 七月闺情 ----------
    {
        "id": "yuan-hui-8",
        "title": "七月闺情",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "七月坐凉宵，金波满丽谯。容华芳意改，枕席怨情饶。",
            "锦字沾愁泪，罗裙缓细腰。不如银汉女，岁岁鹊成桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 奉和圣制答张说扈从南出雀鼠谷之作 ----------
    {
        "id": "yuan-hui-9",
        "title": "奉和圣制答张说扈从南出雀鼠谷之作",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "魏国山河险，周王警跸回。九旗云际出，万骑谷中来。",
            "石路行将尽，烟郊望忽开。赏矜垂柳报，春畏落花催。",
            "兴逸横汾什，恩褒作颂才。小臣瞻日月，延首咏康哉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 奉和圣制送张尚书巡边 ----------
    {
        "id": "yuan-hui-10",
        "title": "奉和圣制送张尚书巡边",
        "author": "袁晖",
        "poet_id": "yuan-hui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "出师宣九命，分阃用三台。始应幕中画，言从天上来。",
            "丹青不独任，韬略遂双该。坐见威棱洽，弥彰事业恢。",
            "旌旗晓云送，鞞鼓朔风催。虏气消残月，边声韵落梅。",
            "羽书雄北地，龙漠寝南垓。宠战黄金尽，输诚白日回。",
            "离章宸翰发，祖宴国门开。欲识恩华盛，平生文武材。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]