# -*- coding: utf-8 -*-
"""
梁锽卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 16 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 天长节 ----------
    {
        "id": "liang-huang-1",
        "title": "天长节",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "日月生天久，年年庆一回。时平祥不去，寿远节长来。",
            "连吹千家笛，同朝百郡杯。愿持金殿镜，处处照遗才。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 长门怨 ----------
    {
        "id": "liang-huang-2",
        "title": "长门怨",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "妾命何偏薄，君王去不归。欲令遥见悔，楼上试春衣。",
            "空殿看人入，深宫羡鸟飞。翻悲因买赋，索镜照空辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 美人春卧 ----------
    {
        "id": "liang-huang-3",
        "title": "美人春卧",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "妾家巫峡阳，罗幌寝兰堂。晓日临窗久，春风引梦长。",
            "落钗仍挂鬓，微汗欲消黄。纵使朦胧觉，魂犹逐楚王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 名姝咏 ----------
    {
        "id": "liang-huang-4",
        "title": "名姝咏",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "阿娇年未多，弱体性能和。怕重愁拈镜，怜轻喜曳罗。",
            "临津双洛浦，对月两嫦娥。独有荆王殿，时时暮雨过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 艳女词 ----------
    {
        "id": "liang-huang-5",
        "title": "艳女词",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "露井桃花发，双双燕并飞。美人姿态里，春色上罗衣。",
            "自爱频开镜，时羞欲掩扉。不知行路客，遥惹五香归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 狷氏子 ----------
    {
        "id": "liang-huang-6",
        "title": "狷氏子",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "杏梁初照日，碧玉后堂开。忆事临妆笑，春娇满镜台。",
            "含声歌扇举，顾影舞腰回。别有佳期处，青楼客夜来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 戏赠歌者 ----------
    {
        "id": "liang-huang-7",
        "title": "戏赠歌者",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "白皙歌童子，哀音绝又连。楚妃临扇学，卢女隔帘传。",
            "晓燕喧喉里，春莺啭舌边。若逢汉武帝，还是李延年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 七夕泛舟 ----------
    {
        "id": "liang-huang-8",
        "title": "七夕泛舟",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "云端有灵匹，掩映拂妆台。夜久应摇珮，天高响不来。",
            "片欢秋始展，残梦晓翻催。却怨填河鹊，留桥又不回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 崔驸马宅咏画山水扇 ----------
    {
        "id": "liang-huang-9",
        "title": "崔驸马宅咏画山水扇",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "画扇出秦楼，谁家赠列侯。小含吴剡县，轻带楚扬州。",
            "掩作山云暮，摇成陇树秋。坐来传与客，汉水又回流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 观王美人海图障子 ----------
    {
        "id": "liang-huang-10",
        "title": "观王美人海图障子",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "宋玉东家女，常怀物外多。自从图渤海，谁为觅湘娥。",
            "白鹭栖脂粉，赪鲂跃绮罗。仍怜转娇眼，别恨一横波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 闻百舌鸟 ----------
    {
        "id": "liang-huang-11",
        "title": "闻百舌鸟",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "百舌闻他郡，间关媚物华。敛形藏一叶，分响出千花。",
            "坐爱时褰幌，行藏或驻车。不须应独感，三载已辞家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 省试方士进恒春草 ----------
    {
        "id": "liang-huang-12",
        "title": "省试方士进恒春草",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "东吴有灵草，生彼剡溪傍。既乱莓苔色，仍连菡萏香。",
            "掇之称远士，持以奉明王。北阙颜弥驻，南山寿更长。",
            "金膏徒骋妙，石髓莫矜良。倘使沾涓滴，还游不死方。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 代征人妻喜夫还 ----------
    {
        "id": "liang-huang-13",
        "title": "代征人妻喜夫还",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "征夫走马发渔阳，少妇含娇开洞房。千日废台还挂镜，",
            "数年尘面再新妆。春风喜出今朝户，明月虚眠昨夜床。",
            "莫道幽闺书信隔，还衣总是旧时香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 赠李中华 ----------
    {
        "id": "liang-huang-14",
        "title": "赠李中华",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "莫向嵩山去，神仙多误人。不如朝魏阙，天子重贤臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 咏木老人（一作傀儡吟，一作咏窟磊子人） ----------
    {
        "id": "liang-huang-15",
        "title": "咏木老人（一作傀儡吟，一作咏窟磊子人）",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "刻木牵丝作老翁，鸡皮鹤发与真同。",
            "须臾弄罢寂无事，还似人生一梦中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 句 ----------
    {
        "id": "liang-huang-16",
        "title": "句",
        "author": "梁锽",
        "poet_id": "liang-huang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "堂高凭上望，宅广乘车行。（《咏郭令公宅》。",
            "见《封氏闻见记》）",
            "第二百零三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]