# -*- coding: utf-8 -*-
"""
陈标卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 公无渡河 ----------
    {
        "id": "chen-biao-1",
        "title": "公无渡河",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "阴云飒飒浪花愁，半度惊湍半挂舟。声尽云天君不住，",
            "命悬鱼鳖妾同休。黛娥芳脸垂珠泪，罗袜香裾赴碧流。",
            "馀魄岂能衔木石，独将遗恨付箜篌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 秦王卷衣 ----------
    {
        "id": "chen-biao-2",
        "title": "秦王卷衣",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "秦王宫阙霭春烟，珠树琼枝近碧天。御气馨香苏合启，",
            "帘光浮动水精悬。霏微罗縠随芳袖，宛转鲛鮹逐宝筵。",
            "从此咸阳一回首，暮云愁色已千年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 婕妤怨 ----------
    {
        "id": "chen-biao-3",
        "title": "婕妤怨",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "掌上恩移玉帐空，香珠满眼泣春风。飘零怨柳凋眉翠，",
            "狼藉愁桃坠脸红。凤辇只应三殿北，鸾声不向五湖中。",
            "笙歌处处回天眷，独自无情长信宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 饮马长城窟 ----------
    {
        "id": "chen-biao-4",
        "title": "饮马长城窟",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "日日风吹虏骑尘，年年饮马汉营人。千堆战骨那知主，",
            "万里枯沙不辨春。浴谷气寒愁坠指，断崖冰滑恐伤神。",
            "金鞍玉勒无颜色，泪满征衣怨暴秦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 江南行 ----------
    {
        "id": "chen-biao-5",
        "title": "江南行",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "水光春色满江天，蘋叶风吹荷叶钱。香蚁翠旗临岸市，",
            "艳娥红袖渡江船。晓惊白鹭联翩雪，浪蹙青茭潋滟烟。",
            "不怕江洲芳草暮，待将秋兴折湖莲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 长安秋思（一作白纻歌） ----------
    {
        "id": "chen-biao-6",
        "title": "长安秋思（一作白纻歌）",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "吴女秋机织曙霜，冰蚕吐丝月盈筐。金刀玉指裁缝促，",
            "水殿花楼弦管长。舞袖慢移凝瑞雪，歌尘微动避雕梁。",
            "唯愁陌上芳菲度，狼藉风池荷叶黄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 赠元和十三年登第进士 ----------
    {
        "id": "chen-biao-7",
        "title": "赠元和十三年登第进士",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "春官南院粉墙东，地色初分月色红。文字一千重马拥，",
            "喜欢三十二人同。眼看鱼变辞凡水，心逐鹦飞出瑞风。",
            "莫怪云泥从此别，总曾惆怅去年中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 焦桐树 ----------
    {
        "id": "chen-biao-8",
        "title": "焦桐树",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "江上烹鱼采野樵，鸾枝摧折半曾烧。未经良匠材虽散，",
            "待得知音尾已焦。若使琢磨徽白玉，便来风律轸青瑶。",
            "还能万里传山水，三峡泉声岂寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 寄友人 ----------
    {
        "id": "chen-biao-9",
        "title": "寄友人",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "杜甫在时贪入蜀，孟郊生处却归秦。",
            "如今始会麻姑意，借问山川与后人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 啄木谣 ----------
    {
        "id": "chen-biao-10",
        "title": "啄木谣",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "丁丁向晚急还稀，啄遍庭槐未肯归。",
            "终日与君除蠹害，莫嫌无事不频飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 僧院牡丹 ----------
    {
        "id": "chen-biao-11",
        "title": "僧院牡丹",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "琉璃地上开红艳，碧落天头散晓霞。",
            "应是向西无地种，不然争肯重莲花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 蜀葵 ----------
    {
        "id": "chen-biao-12",
        "title": "蜀葵",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "眼前无奈蜀葵何，浅紫深红数百窠。",
            "能共牡丹争几许，得人嫌处只缘多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 句 ----------
    {
        "id": "chen-biao-13",
        "title": "句",
        "author": "陈标",
        "poet_id": "chen-biao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "长把酒杯凭夜月，每将诗思泥春风。（《赠祝元膺》）",
            "襄阳乐事经过尽，岘首烟花倒泻空。（《叙旧》）",
            "犹疑波底鲛人泪，滴在衣裳半欲零。（《露荷》）",
            "春明门外襄阳路，落日秋风送客归。（《送人归襄阳》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]