# -*- coding: utf-8 -*-
"""
吴商浩卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 巫峡听猿 ----------
    {
        "id": "wu-shang-hao-1",
        "title": "巫峡听猿",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "巴江猿啸苦，响入客舟中。孤枕破残梦，三声随晓风。",
            "连云波澹澹，和雾雨濛濛。巫峡去家远，不堪魂断空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 长安春赠友人 ----------
    {
        "id": "wu-shang-hao-2",
        "title": "长安春赠友人",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "繁华堪泣帝城春，粉堞青楼势碍云。花对玉钩帘外发，",
            "歌飘尘土路边闻。几多远客魂空断，何处王孙酒自醺。",
            "各有归程千万里，东风时节恨离群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 塞上即事 ----------
    {
        "id": "wu-shang-hao-3",
        "title": "塞上即事",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "身似星流迹似蓬，玉关孤望杳溟濛。寒沙万里平铺月，",
            "晓角一声高卷风。战士殁边魂尚哭，单于猎处火犹红。",
            "分明更想残宵梦，故国依然在甬东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 宿山驿 ----------
    {
        "id": "wu-shang-hao-4",
        "title": "宿山驿",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "文战何堪功未图，又驱羸马指天衢。露华凝夜渚莲尽，",
            "月彩满轮山驿孤。岐路辛勤终日有，乡关音信隔年无。",
            "好同范蠡扁舟兴，高挂一帆归五湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 北邙山 ----------
    {
        "id": "wu-shang-hao-5",
        "title": "北邙山",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "北邙山草又青青，今日销魂事可明。绿酒醉来春未歇，",
            "白杨风起柳初晴。冈原旋葬松新长，年代无人阙半平。",
            "堪取金炉九还药，不能随梦向浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 秋塘晓望 ----------
    {
        "id": "wu-shang-hao-6",
        "title": "秋塘晓望",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "钟尽疏桐散曙鸦，故山烟树隔天涯。",
            "西风一夜秋塘晓，零落几多红藕花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 水楼感事 ----------
    {
        "id": "wu-shang-hao-7",
        "title": "水楼感事",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "高柳螀啼雨后秋，年光空感泪如流。",
            "满湖菱荇东归晚，闲倚南轩尽日愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 泊舟 ----------
    {
        "id": "wu-shang-hao-8",
        "title": "泊舟",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "身逐烟波魂自惊，木兰舟上一帆轻。",
            "云中有寺在何处，山底宿时闻磬声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 湘云 ----------
    {
        "id": "wu-shang-hao-9",
        "title": "湘云",
        "author": "吴商浩",
        "poet_id": "wu-shang-hao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "□满湘江云莹空，纷纷长对水溶溶。",
            "日西遥望自归处，尽挂九疑千万峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]