# -*- coding: utf-8 -*-
"""
李九龄卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 19 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 上清辞五首 ----------
    {
        "id": "li-jiu-ling-1",
        "title": "上清辞五首",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "入海浮生汗漫秋，紫皇高宴五云楼。",
            "霓裳曲罢天风起，吹散仙香满十洲。",
            "楼锁彤霞地绝尘，碧桃花发九天春。",
            "东皇近日慵游宴，闲煞瑶池五色麟。",
            "上清仙路有丹梯，影响行人到即迷。",
            "不会无端个渔父，阿谁教入武陵溪。",
            "本来方朔是真仙，偶别丹台未得还。",
            "何事玉皇消息晚，忍教憔悴向人间。",
            "新拜天官上玉都，紫皇亲授五灵符。",
            "群仙个个来相问，人世风光似此无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 读三国志 ----------
    {
        "id": "li-jiu-ling-2",
        "title": "读三国志",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "有国由来在得贤，莫言兴废是循环。",
            "武侯星落周瑜死，平蜀降吴似等闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 山舍南溪小桃花 ----------
    {
        "id": "li-jiu-ling-3",
        "title": "山舍南溪小桃花",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "一树繁英夺眼红，开时先合占东风。",
            "可怜地僻无人赏，抛掷深山乱木中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春行遇雨 ----------
    {
        "id": "li-jiu-ling-4",
        "title": "春行遇雨",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "夹路轻风撼柳条，雨侵春态动无憀。",
            "采香陌上谁家女，湿损钗头翡翠翘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 登楼寄远 ----------
    {
        "id": "li-jiu-ling-5",
        "title": "登楼寄远",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "满城春色花如雪，极目烟光月似钩。",
            "总是动人乡思处，更堪容易上高楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 望思台 ----------
    {
        "id": "li-jiu-ling-6",
        "title": "望思台",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "汉武年高慢帝图，任人曾不问贤愚。",
            "直饶四老依前出，消得江充宠佞无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 山舍偶题 ----------
    {
        "id": "li-jiu-ling-7",
        "title": "山舍偶题",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "门掩松萝一径深，偶携藜杖出前林。",
            "谁知尽日看山坐，万古兴亡总在心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 荆溪夜泊 ----------
    {
        "id": "li-jiu-ling-8",
        "title": "荆溪夜泊",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "点点渔灯照浪清，水烟疏碧月胧明。",
            "小滩惊起鸳鸯处，一双采莲船过声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 旅舍卧病 ----------
    {
        "id": "li-jiu-ling-9",
        "title": "旅舍卧病",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "家隔西秦无远信，身随东洛度流年。",
            "病来旅馆谁相问，牢落闲庭一树蝉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 登昭福寺楼 ----------
    {
        "id": "li-jiu-ling-10",
        "title": "登昭福寺楼",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "旅怀秋兴正无涯，独倚危楼四望赊。",
            "谷变陵迁何处问，满川空有旧烟霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 代边将 ----------
    {
        "id": "li-jiu-ling-11",
        "title": "代边将",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "雪冻阴河半夜风，战回狂虏血漂红。",
            "据鞍遥指长安路，须刻麟台第一功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 夜与张舒话别 ----------
    {
        "id": "li-jiu-ling-12",
        "title": "夜与张舒话别",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "愁听南楼角又吹，晓鸡啼后更分离。",
            "如何销得凄凉思，更劝灯前酒一卮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 寒梅词 ----------
    {
        "id": "li-jiu-ling-13",
        "title": "寒梅词",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "霜梅先拆岭头枝，万卉千花冻不知。",
            "留得和羹滋味在，任他风雪苦相欺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 题灵泉寺 ----------
    {
        "id": "li-jiu-ling-14",
        "title": "题灵泉寺",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "入谷先生一阵香，异花奇木簇禅堂。",
            "可怜门外高低路，万毂千蹄日日忙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 宿张正字别业 ----------
    {
        "id": "li-jiu-ling-15",
        "title": "宿张正字别业",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "茅屋萧寥烟暗后，松窗寂历月明初。",
            "此时谁念孤吟客，唯有黄公一帙书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 鹤 ----------
    {
        "id": "li-jiu-ling-16",
        "title": "鹤",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "天上瑶池覆五云，玉麟金凤好为群。",
            "不须更饮人间水，直是清流也汗君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 过相思谷 ----------
    {
        "id": "li-jiu-ling-17",
        "title": "过相思谷",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "悠悠信马春山曲，芳草和烟铺嫩绿。",
            "正被离愁著莫人，那堪更过相思谷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 写庄子 ----------
    {
        "id": "li-jiu-ling-18",
        "title": "写庄子",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "圣泽安排当散地，贤侯优贷借新居。",
            "闲中亦有闲生计，写得南华一部书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 山中寄友人 ----------
    {
        "id": "li-jiu-ling-19",
        "title": "山中寄友人",
        "author": "李九龄",
        "poet_id": "li-jiu-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "乱云堆里结茅庐，已共红尘迹渐疏。",
            "莫问野人生计事，窗前流水枕前书。",
            "第七百三十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]