# -*- coding: utf-8 -*-
"""
陈润卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 宿北乐馆 ----------
    {
        "id": "chen-run-1",
        "title": "宿北乐馆",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "欲眠不眠夜深浅，越鸟一声空山远。庭木萧萧落叶时，",
            "溪声雨声听不辨。溪流潺潺雨习习，灯影山光满窗入。",
            "栋里不知浑是云，晓来但觉衣裳湿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 东都所居寒食下作 ----------
    {
        "id": "chen-run-2",
        "title": "东都所居寒食下作",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "江南寒食早，二月杜鹃鸣。日暖山初绿，春寒雨欲晴。",
            "浴蚕当社日，改火待清明。更喜瓜田好，令人忆邵平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 登西灵塔 ----------
    {
        "id": "chen-run-3",
        "title": "登西灵塔",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "塔庙出招提，登临碧海西。不知人意远，渐觉鸟飞低。",
            "稍与云霞近，如将日月齐。迁乔未得意，徒欲蹑云梯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送骆征君 ----------
    {
        "id": "chen-run-4",
        "title": "送骆征君",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "野人膺辟命，溪上掩柴扉。黄卷犹将去，青山岂更归。",
            "马留苔藓迹，人脱薜萝衣。他日相思处，天边望少微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 赋得浦外虹送人 ----------
    {
        "id": "chen-run-5",
        "title": "赋得浦外虹送人",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "日影化为虹，弯弯出浦东。一条微雨后，五色片云中。",
            "轮势随天度，桥形跨海通。还将饮水处，持送使车雄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 赋得秋河曙耿耿 ----------
    {
        "id": "chen-run-6",
        "title": "赋得秋河曙耿耿",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "晚望秋高夜，微明欲曙河。桥成鹊已去，机罢女应过。",
            "月上殊开练，云行类动波。寻源不可到，耿耿复如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 赋得池塘生春草（一作陈陶诗） ----------
    {
        "id": "chen-run-7",
        "title": "赋得池塘生春草（一作陈陶诗）",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "谢公遗咏处，池水夹通津。古往人何在，年来草自春。",
            "色宜波际绿，香爱雨中新。今日青青意，空悲行路人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 阙题 ----------
    {
        "id": "chen-run-8",
        "title": "阙题",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "丈夫不感恩，感恩宁有泪。心头感恩血，一滴染天地。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 句 ----------
    {
        "id": "chen-run-9",
        "title": "句",
        "author": "陈润",
        "poet_id": "chen-run",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "两岸杨花风作雪，一池荷叶雨成珠。（题山阴朱征君隐居）",
            "暮猿啼处三声绝，寒雁归时一叶秋。（客舍石己山渡行）",
            "一双泪滴黄河水，愿得东流入汉宫。（《王昭君》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]