# -*- coding: utf-8 -*-
"""
霍总卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 郡楼望九华歌 ----------
    {
        "id": "huo-zong-1",
        "title": "郡楼望九华歌",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "楼上坐见九子峰，翠云赤日光溶溶。有时朝昏变疏密，",
            "八峰和烟一峰出。有时风卷天雨晴，聚立连连如弟兄。",
            "阳乌生子偶成数，丹凤养雏同此名。日日遥看机已静，",
            "未离尘躅思真境。子明龙驾腾九垓，陵阳相对空崔嵬。",
            "玉浆瑶草不可见，自有神仙风马来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 塞下曲 ----------
    {
        "id": "huo-zong-2",
        "title": "塞下曲",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "曾当一面战，频出九重围。但见争锋处，长须得胜归。",
            "雪沾旗尾落，风断节毛稀。岂要铭燕石，平生重武威。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 关山月 ----------
    {
        "id": "huo-zong-3",
        "title": "关山月",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "珠珑翡翠床，白皙侍中郎。五日来花下，双童问道傍。",
            "到门车马狭，连夜管弦长。每笑东家子，窥他宋玉墙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 骢马 ----------
    {
        "id": "huo-zong-4",
        "title": "骢马",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "青骊八尺高，侠客倚雄豪。踏雪生珠汗，障泥护锦袍。",
            "路傍看骤影，鞍底卷旋毛。岂独连钱贵，酬恩更代劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 雉朝飞 ----------
    {
        "id": "huo-zong-5",
        "title": "雉朝飞",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "五色有名翚，清晨挟两雌。群群飞自乐，步步饮相随。",
            "觇叶逢人处，惊媒妒宠时。绿毛春斗尽，强敌愿君知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 木芙蓉 ----------
    {
        "id": "huo-zong-6",
        "title": "木芙蓉",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "本自江湖远，常开霜露馀。争春候秾李，得水异红蕖。",
            "孤秀曾无偶，当门幸不锄。谁能政摇落，繁彩照阶除。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 采莲女 ----------
    {
        "id": "huo-zong-7",
        "title": "采莲女",
        "author": "霍总",
        "poet_id": "huo-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "舟中采莲女，两两催妆梳。闻早渡江去，日高来起居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]