# -*- coding: utf-8 -*-
"""
董思恭卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 19 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·王昭君 ----------
    {
        "id": "dong-si-gong-1",
        "title": "相和歌辞·王昭君",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "琵琶马上弹，行路曲中难。汉月正南远，燕山直北寒。",
            "髻鬟风拂散，眉黛雪沾残。斟酌红颜尽，何劳镜里看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·三妇艳诗 ----------
    {
        "id": "dong-si-gong-2",
        "title": "相和歌辞·三妇艳诗",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "大妇裁纨素，中妇弄明珰。小妇多姿态，登楼红粉妆。",
            "丈人且安坐，初日渐流光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 三妇艳 ----------
    {
        "id": "dong-si-gong-3",
        "title": "三妇艳",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "大妇裁纨素，中妇弄明珰。小妇多姿态，登楼红粉妆。",
            "丈人且安坐，初日渐流光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 感怀 ----------
    {
        "id": "dong-si-gong-4",
        "title": "感怀",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "野郊怆新别，河桥非旧饯。惨日映峰沉，愁云随盖转。",
            "哀笳时断续，悲旌乍舒卷。望望情何极，浪浪泪空泫。",
            "无复昔时人，芳春共谁遣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 守岁二首（此二首一作太宗诗，后题作《除夜》。） ----------
    {
        "id": "dong-si-gong-5",
        "title": "守岁二首（此二首一作太宗诗，后题作《除夜》。）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "暮景斜芳殿，年华丽绮宫。寒辞去冬雪，暖带入春风。",
            "阶馥舒梅素，盘花卷烛红。共欢新故岁，迎送一宵中。",
            "岁阴穷暮纪，献节启新芳。冬尽今宵促，年开明日长。",
            "冰销出镜水，梅散入风香。对此欢终宴，倾壶待曙光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 昭君怨二首（前首一作董初诗） ----------
    {
        "id": "dong-si-gong-6",
        "title": "昭君怨二首（前首一作董初诗）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "新年犹尚小，那堪远聘秦。裾衫沾马汗，眉黛染胡尘。",
            "举眼无相识，路逢皆异人。唯有梅将李，犹带故乡春。",
            "琵琶马上弹，行路曲中难。汉月正南远，燕山直北寒。",
            "髻鬟风拂乱，眉黛雪沾残。斟酌红颜改，徒劳握镜看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 咏日 ----------
    {
        "id": "dong-si-gong-7",
        "title": "咏日",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "沧海十枝晖，悬圃重轮庆。蕣华发晨楹，菱彩翻朝镜。",
            "忽遇惊风飘，自有浮云映。更也人皆仰，无待挥戈正。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 咏月 ----------
    {
        "id": "dong-si-gong-8",
        "title": "咏月",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "北堂未安寝，西园聊骋望。玉户照罗帏，珠轩明绮障。",
            "别客长安道，思妇高楼上。所愿君莫违，清风时可访。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 咏星 ----------
    {
        "id": "dong-si-gong-9",
        "title": "咏星",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "历历东井舍，昭昭右掖垣。云际龙文出，池中鸟色翻。",
            "流辉下月路，坠影入河源。方知颍川集，别有太丘门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 咏风 ----------
    {
        "id": "dong-si-gong-10",
        "title": "咏风",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "萧萧度阊阖，习习下庭闱。花蝶自飘舞，兰蕙生光辉。",
            "相乌正举翼，退鹢已惊飞。方从列子御，更逐浮云归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 咏云 ----------
    {
        "id": "dong-si-gong-11",
        "title": "咏云",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "帝乡白云起，飞盖上天衢。带月绮罗映，从风枝叶敷。",
            "参差过层阁，倏忽下苍梧。因风望既远，安得久踟蹰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 咏雪 ----------
    {
        "id": "dong-si-gong-12",
        "title": "咏雪",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "天山飞雪度，言是落花朝。惜哉不我与，萧索从风飘。",
            "鲜洁凌纨素，纷糅下枝条。良时竟何在，坐见容华销。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 咏露 ----------
    {
        "id": "dong-si-gong-13",
        "title": "咏露",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "夜色凝仙掌，晨甘下帝庭。不觉九秋至，远向三危零。",
            "芦渚花初白，葵园叶尚青。晞阳一洒惠，方愿益沧溟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 咏雾 ----------
    {
        "id": "dong-si-gong-14",
        "title": "咏雾",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "苍山寂已暮，翠观黯将沉。终南晨豹隐，巫峡夜猿吟。",
            "天寒气不歇，景晦色方深。待访公超市，将予赴华阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 咏虹（一作虹蜺） ----------
    {
        "id": "dong-si-gong-15",
        "title": "咏虹（一作虹蜺）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "春暮萍生早，日落雨飞馀。横彩分长汉，倒色媚清渠。",
            "梁前朝影出，桥上晚光舒。愿逐旌旗转，飘飘侍直庐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 咏桃（一作太宗诗） ----------
    {
        "id": "dong-si-gong-16",
        "title": "咏桃（一作太宗诗）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "禁苑春光丽，花蹊几树装。缀条深浅色，点露参差光。",
            "向日分千笑，迎风共一香。如何仙岭侧，独秀隐遥芳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 咏李（一作太宗诗） ----------
    {
        "id": "dong-si-gong-17",
        "title": "咏李（一作太宗诗）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "盘根植瀛渚，交干横倚天。舒华光四海，卷叶荫山川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 咏弓（一作太宗诗） ----------
    {
        "id": "dong-si-gong-18",
        "title": "咏弓（一作太宗诗）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "上弦明月半，激箭流星远。落雁带书惊，啼猿映枝转。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 咏琵琶（一作太宗诗） ----------
    {
        "id": "dong-si-gong-19",
        "title": "咏琵琶（一作太宗诗）",
        "author": "董思恭",
        "poet_id": "dong-si-gong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "半月无双影，金花有四时。摧藏千里态，掩抑几重悲。",
            "促节萦红袖，清音满翠帷。驶弹风响急，缓曲钏声迟。",
            "空馀关陇恨，因此代相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]