# -*- coding: utf-8 -*-
"""
杨凭卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 19 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 长安春夜宿开元观 ----------
    {
        "id": "yang-ping-1",
        "title": "长安春夜宿开元观",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "霓裳下晚烟，留客杏花前。遍问人寰事，新从洞府天。",
            "长松皆扫月，老鹤不知年。为说蓬瀛路，云涛几处连。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 晚泊江戍 ----------
    {
        "id": "yang-ping-2",
        "title": "晚泊江戍",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "旅棹依遥戍，清湘急晚流。若为南浦宿，逢此北风秋。",
            "云月孤鸿晚，关山几路愁。年年不得意，零落对沧洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 巴江雨夜 ----------
    {
        "id": "yang-ping-3",
        "title": "巴江雨夜",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "五岭天无雁，三巴客问津。纷纷轻汉暮，漠漠暗江春。",
            "青草连湖岸，繁花忆楚人。芳菲无限路，几夜月明新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 边塞行 ----------
    {
        "id": "yang-ping-4",
        "title": "边塞行",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "九原临得水，双足是重城。独许为儒老，相怜从骑行。",
            "细丛榆塞迥，高点雁山晴。圣主嗤炎汉，无心自勒兵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 乐游园望月 ----------
    {
        "id": "yang-ping-5",
        "title": "乐游园望月",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "炎灵全盛地，明月半秋时。今古人同望，盈亏节暗移。",
            "彩凝双月迥，轮度八川迟。共惜鸣珂去，金波送酒卮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 千叶桃花 ----------
    {
        "id": "yang-ping-6",
        "title": "千叶桃花",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "千叶桃花胜百花，孤荣春晚驻年华。",
            "若教避俗秦人见，知向河源旧侣夸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 春中泛舟 ----------
    {
        "id": "yang-ping-7",
        "title": "春中泛舟",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "仙郎归奏过湘东，正值三湘二月中。",
            "惆怅满川桃杏醉，醉看还与曲江同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 雨中怨秋 ----------
    {
        "id": "yang-ping-8",
        "title": "雨中怨秋",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "辞家远客怆秋风，千里寒云与断蓬。",
            "日暮隔山投古寺，钟声何处雨濛濛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 秋日独游曲江 ----------
    {
        "id": "yang-ping-9",
        "title": "秋日独游曲江",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "信马闲过忆所亲，秋山行尽路无尘。",
            "主人莫惜松阴醉，还有千钱沽酒人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 寄别 ----------
    {
        "id": "yang-ping-10",
        "title": "寄别",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "晚烟洲雾并苍苍，河雁惊飞不作行。",
            "回旆转舟行数里，歌声犹自逐清湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 边情 ----------
    {
        "id": "yang-ping-11",
        "title": "边情",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "新种如今屡请和，玉关边上幸无他。",
            "欲知北海苦辛处，看取节毛馀几多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 早发湘中 ----------
    {
        "id": "yang-ping-12",
        "title": "早发湘中",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "按节鸣笳中贵催，红旌白旆满船开。",
            "迎愁湓浦登城望，西见荆门积水来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 海榴 ----------
    {
        "id": "yang-ping-13",
        "title": "海榴",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "海榴殷色透帘栊，看盛看衰意欲同。",
            "若许三英随五马，便将浓艳斗繁红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 春情 ----------
    {
        "id": "yang-ping-14",
        "title": "春情",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "暮雨朝云几日归，如丝如雾湿人衣。",
            "三湘二月春光早，莫逐狂风缭乱飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送客往荆州 ----------
    {
        "id": "yang-ping-15",
        "title": "送客往荆州",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "巴丘过日又登城，云水湘东一日平。",
            "若爱春秋繁露学，正逢元凯镇南荆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 赠马炼师 ----------
    {
        "id": "yang-ping-16",
        "title": "赠马炼师",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "心嫌碧落更何从，月帔花冠冰雪容。",
            "行雨若迷归处路，近南惟见祝融峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 湘江泛舟 ----------
    {
        "id": "yang-ping-17",
        "title": "湘江泛舟",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "湘川洛浦三千里，地角天涯南北遥。",
            "除却同倾百壶外，不愁谁奈两魂销。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送别 ----------
    {
        "id": "yang-ping-18",
        "title": "送别",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "江岸梅花雪不如，看君驿驭向南徐。",
            "相闻不必因来雁，云里飞輧落素书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 赠窦牟（一作窦洛阳牟见简篇章，偶赠绝句） ----------
    {
        "id": "yang-ping-19",
        "title": "赠窦牟（一作窦洛阳牟见简篇章，偶赠绝句）",
        "author": "杨凭",
        "poet_id": "yang-ping",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "直用天才众却瞋，应欺李杜久为尘。",
            "南荒不死中华老，别玉翻同西国人。",
            "第二百九十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]