# -*- coding: utf-8 -*-
"""
杨发卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 南溪书院 ----------
    {
        "id": "yang-fa-1",
        "title": "南溪书院",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "茅屋住来久，山深不置门。草生垂井口，花发接篱根。",
            "入院将雏鸟，攀萝抱子猿。曾逢异人说，风景似桃源。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 春园醉醒闲卧小斋 ----------
    {
        "id": "yang-fa-2",
        "title": "春园醉醒闲卧小斋",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "酣醉送馀春，醒来恨更频。花残蜂蠹物，叶暗鸟欺人。",
            "帘闭高眠贵，斋空浩气新。从今北窗蝶，长是梦中身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 小园秋兴 ----------
    {
        "id": "yang-fa-3",
        "title": "小园秋兴",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "谁言帝城里，独作野人居。石磴晴看叠，山苗晚自锄。",
            "相惭五秉粟，尚癖一车书。昔日扬雄宅，还无卿相舆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 与诸公池上待月 ----------
    {
        "id": "yang-fa-4",
        "title": "与诸公池上待月",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "树密云萦岸，池遥水际空。芰开方吐镜，蘋动欲含风。",
            "渐映沙汀白，微分渚叶红。金波宜共赏，仙棹一宵同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 檐雀 ----------
    {
        "id": "yang-fa-5",
        "title": "檐雀",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "弱羽怯孤飞，投檐幸所依。衔环唯报德，贺厦本知归。",
            "红觜休争顾，丹心自识机。从来攀凤足，生死恋光辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 残花（一作罗隐诗） ----------
    {
        "id": "yang-fa-6",
        "title": "残花（一作罗隐诗）",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "已笑良时晚，仍悲别酒催。暖芳随日薄，残片逐风回。",
            "黛敛愁歌扇，妆残泣镜台。繁阴莫矜衒，终是共尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 山泉（一作李才江诗） ----------
    {
        "id": "yang-fa-7",
        "title": "山泉（一作李才江诗）",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "半空飞下水，势去响如雷。静彻啼猿寺，高陵坐客台。",
            "耳同经剑阁，身若到天台。溅树吹成冻，邻祠触作灰。",
            "深中试榔栗，浅处落莓苔。半夜重城闭，潺湲枕底来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 秋晚日少陵原游山泉之什 ----------
    {
        "id": "yang-fa-8",
        "title": "秋晚日少陵原游山泉之什",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "喧浊侵肌性未沈，每来云外恣幽寻。尘衣更喜秋泉洁，",
            "倦迹方依竹洞深。暂过偶然应系分，有期终去但劳心。",
            "唯怜一夜空山月，似许他年伴独吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 秋晴独立南亭 ----------
    {
        "id": "yang-fa-9",
        "title": "秋晴独立南亭",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "昼对南风独闭关，暗期幽鸟去仍还。如今有待终身贵，",
            "未若忘机尽日闲。心似蒙庄游物外，官惭许掾在人间。",
            "开襟自向清风笑，无限秋光为解颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 宿黄花馆 ----------
    {
        "id": "yang-fa-10",
        "title": "宿黄花馆",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "孤馆萧条槐叶稀，暮蝉声隔水声微。年年为客路无尽，",
            "日日送人身未归。何处迷鸿离浦月，谁家愁妇捣霜衣。",
            "夜深不卧帘犹卷，数点残萤入户飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 南野逢田客 ----------
    {
        "id": "yang-fa-11",
        "title": "南野逢田客",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "桑柘悠悠水蘸堤，晚风晴景不妨犁。高机犹织卧蚕子，",
            "下坂未饥逢饲妻。杏色满林羊酪熟，麦凉浮垄雉媒低。",
            "生时自乐死由命，万事在天管不迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 东斋夜宴酬绍之起居见赠 ----------
    {
        "id": "yang-fa-12",
        "title": "东斋夜宴酬绍之起居见赠",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "龙门八上不知津，唯有君心困益亲。白社追游名自远，",
            "青袍相映道逾新。十年江海鱼缄尽，一夜笙歌凤吹频。",
            "渐老旧交情更重，莫将美酒负良辰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 玩残花 ----------
    {
        "id": "yang-fa-13",
        "title": "玩残花",
        "author": "杨发",
        "poet_id": "yang-fa",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "十日浓芳一岁程，东风初急眼偏明。",
            "低枝似泥幽人醉，莫道无情似有情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]