# -*- coding: utf-8 -*-
"""
卢殷卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 妾换马 ----------
    {
        "id": "lu-yin-1",
        "title": "妾换马",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "伴凤楼中妾，如龙枥上宛。同年辞旧宠，异地受新恩。",
            "香阁更衣处，尘蒙喷草痕。连嘶将忍泪，俱恋主人门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 七夕 ----------
    {
        "id": "lu-yin-2",
        "title": "七夕",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "河耿月凉时，牵牛织女期。欢娱方在此，漏刻竟由谁。",
            "定不嫌秋驶，唯当乞夜迟。全胜客子妇，十载泣生离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 月夜 ----------
    {
        "id": "lu-yin-3",
        "title": "月夜",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "露下凉生簟，无人月满庭。难闻逆河浪，徒望白榆星。",
            "树绕孤栖鹊，窗飞就暗萤。移时宿兰影，思共习芳馨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 仲夏寄江南 ----------
    {
        "id": "lu-yin-4",
        "title": "仲夏寄江南",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "五月行将近，三年客未回。梦成千里去，酒醒百忧来。",
            "晚暮时看槿，悲酸不食梅。空将白团扇，从寄复裴回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 欲销云 ----------
    {
        "id": "lu-yin-5",
        "title": "欲销云",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "欲隐从龙质，仍馀触石文。霏微依碧落，仿佛误非云。",
            "度月光无隔，倾河影不分。如逢作霖处，当为起氤氲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 遇边使 ----------
    {
        "id": "lu-yin-6",
        "title": "遇边使",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "累年无的信，每夜梦边城。袖掩千行泪，书封一尺情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 移住别居 ----------
    {
        "id": "lu-yin-7",
        "title": "移住别居",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "自到西川住，唯君别有情。常逢对门远，又隔一重城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 堋口逢友人 ----------
    {
        "id": "lu-yin-8",
        "title": "堋口逢友人",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "艰难别离久，中外往还深。已改当时法，空馀旧日心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 雨霁登北岸寄友人 ----------
    {
        "id": "lu-yin-9",
        "title": "雨霁登北岸寄友人",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "稻黄扑扑黍油油，野树连山涧自流。",
            "忆得年时冯翊部，谢郎相引上楼头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 长安亲故 ----------
    {
        "id": "lu-yin-10",
        "title": "长安亲故",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "楚兰不佩佩吴钩，带酒城头别旧游。",
            "年事已多筋力在，试将弓箭到并州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 悲秋 ----------
    {
        "id": "lu-yin-11",
        "title": "悲秋",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "秋空雁度青天远，疏树蝉嘶白露寒。",
            "阶下败兰犹有气，手中团扇渐无端。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 晚蝉 ----------
    {
        "id": "lu-yin-12",
        "title": "晚蝉",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "深藏高柳背斜晖，能轸孤愁减昔围。",
            "犹畏旅人头不白，再三移树带声飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 维扬郡西亭赠友人 ----------
    {
        "id": "lu-yin-13",
        "title": "维扬郡西亭赠友人",
        "author": "卢殷",
        "poet_id": "lu-yin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "萍飒风池香满船，杨花漠漠暮春天。",
            "玉人此日心中事，何似乘羊入市年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]