# -*- coding: utf-8 -*-
"""
丁仙芝卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·江南曲 ----------
    {
        "id": "ding-xian-zhi-1",
        "title": "相和歌辞·江南曲",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "长干斜路北，近浦是儿家。有意来相访，明朝出浣纱。",
            "发向横塘口，船开值急流。知郎旧时意，且请拢船头。",
            "昨暝逗南陵，风声波浪阻。入浦不逢人，归家谁信汝。",
            "未晓已成妆，乘潮去茫茫。因从京口渡，使报邵陵王。",
            "始下芙蓉楼，言发琅邪岸。急为打船开，恶许傍人见。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 和荐福寺英公新构禅堂 ----------
    {
        "id": "ding-xian-zhi-2",
        "title": "和荐福寺英公新构禅堂",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "上人久弃世，中道自忘筌。寂照出群有，了心清众缘。",
            "所以于此地，筑馆开青莲。果药罗砌下，烟虹垂户前。",
            "咒中洒甘露，指处流香泉。禅远目无事，体清宵不眠。",
            "枳闻庐山法，松入汉阳禅。一枕西山外，虚舟常浩然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 赠朱中书 ----------
    {
        "id": "ding-xian-zhi-3",
        "title": "赠朱中书",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "十年种田滨五湖，十年遭涝尽为芜。频年井税常不足，",
            "今年缗钱谁为输。东邻转谷五之利，西邻贩缯日已贵。",
            "而我守道不迁业，谁能肯敢效此事。紫微侍郎白虎殿，",
            "出入通籍回天眷。晨趋彩笔柏梁篇，昼出雕盘大官膳。",
            "会应怜尔居素约，可即长年守贫贱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 戏赠姚侍御 ----------
    {
        "id": "ding-xian-zhi-4",
        "title": "戏赠姚侍御",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "繁霜晓幕鸣柏乌，待子兽炭然金炉。重门启锁紫髯胡。",
            "新披骢马陇西驹，头戴獬豸急晨趋。明光殿前见天子，",
            "今日应弹佞幸夫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 馀杭醉歌赠吴山人 ----------
    {
        "id": "ding-xian-zhi-5",
        "title": "馀杭醉歌赠吴山人",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "晓幕红襟燕，春城白项乌。只来梁上语，不向府中趋。",
            "城头坎坎鼓声曙，满庭新种樱桃树。桃花昨夜撩乱开，",
            "当轩发色映楼台。十千兑得馀杭酒，二月春城长命杯。",
            "酒后留君待明月，还将明月送君回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 京中守岁 ----------
    {
        "id": "ding-xian-zhi-6",
        "title": "京中守岁",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "守岁多然烛，通宵莫掩扉。客愁当暗满，春色向明归。",
            "玉斗巡初匝，银河落渐微。开正献岁酒，千里间庭闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 渡扬子江 ----------
    {
        "id": "ding-xian-zhi-7",
        "title": "渡扬子江",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "桂楫中流望，空波两畔明。林开扬子驿，山出润州城。",
            "海尽边阴静，江寒朔吹生。更闻风叶下，淅沥度秋声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 长宁公主旧山池 ----------
    {
        "id": "ding-xian-zhi-8",
        "title": "长宁公主旧山池",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "平阳旧池馆，寂寞使人愁。座卷流黄簟，帘垂白玉钩。",
            "庭闲花自落，门闭水空流。追想吹箫处，应随仙鹤游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 剡谿馆闻笛 ----------
    {
        "id": "ding-xian-zhi-9",
        "title": "剡谿馆闻笛",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "夜久闻羌笛，寥寥虚客堂。山空响不散，谿静曲宜长。",
            "草木生边气，城池泛夕凉。虚然异风出，仿佛宿平阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 越裳贡白雉（一作孙昌胤诗） ----------
    {
        "id": "ding-xian-zhi-10",
        "title": "越裳贡白雉（一作孙昌胤诗）",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "圣哲承休运，伊夔列上台。覃恩丹徼远，入贡素翚来。",
            "北阙欣初见，南枝顾未回。敛容残雪净，矫翼片云开。",
            "驯扰将无惧，翻飞幸不猜。甘从上林里，饮啄自徘徊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 江南曲五首 ----------
    {
        "id": "ding-xian-zhi-11",
        "title": "江南曲五首",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "长干斜路北，近浦是儿家。有意来相访，明朝出浣纱。",
            "发向横塘口，船开值急流。知郎旧时意，且请拢船头。",
            "昨暝逗南陵，风声波浪阻。入浦不逢人，归家谁信汝。",
            "未晓已成妆，乘潮去茫茫。因从京口渡，使报邵陵王。",
            "始下芙蓉楼，言发琅琊岸。急为打船开，恶许傍人见。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 句 ----------
    {
        "id": "ding-xian-zhi-12",
        "title": "句",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "穷花常闭户，秋城闻捣衣。",
            "树回早秋色，川长迟落晖。（见《吟窗杂录》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 句 ----------
    {
        "id": "ding-xian-zhi-13",
        "title": "句",
        "author": "丁仙芝",
        "poet_id": "ding-xian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "雨鸣鸳瓦收炎气，风卷珠帘送晓凉。（《陪岐王宅宴》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]