# -*- coding: utf-8 -*-
"""
殷尧藩卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 79 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 吴宫 ----------
    {
        "id": "yin-yao-fan-1",
        "title": "吴宫",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "吴王爱歌舞，夜夜醉婵娟。见日吹红烛，和尘扫翠钿。",
            "徒令勾践霸，不信子胥贤。莫问长洲草，荒凉无限年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 久雨 ----------
    {
        "id": "yin-yao-fan-2",
        "title": "久雨",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "云影蔽遥空，无端淡复浓。两旬绵密雨，二月似深冬。",
            "诗酒从教数，帘帏一任重。孰知春有地，微露小桃红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 郊行逢社日 ----------
    {
        "id": "yin-yao-fan-3",
        "title": "郊行逢社日",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "酒熟送迎便，村村庆有年。妻孥亲稼穑，老稚效渔畋。",
            "红树青林外，黄芦白鸟边。稔看风景美，宁不羡归田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 过友人幽居 ----------
    {
        "id": "yin-yao-fan-4",
        "title": "过友人幽居",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "身坐众香国，蒲团诗思新。一贫曾累我，此兴未输人。",
            "陋巷谁为俗，寒窗不染尘。石斋盟四友，年下顿生春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 过雍陶博士邸中饮（一作赠陈十四） ----------
    {
        "id": "yin-yao-fan-5",
        "title": "过雍陶博士邸中饮（一作赠陈十四）",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "落叶下萧萧，幽居远市朝。偶成投辖饮，不待致书招。",
            "塞雁冲寒过，山云傍槛飘。此身何所似，天地一渔樵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 游王羽士山房 ----------
    {
        "id": "yin-yao-fan-6",
        "title": "游王羽士山房",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "落日半楼明，琳宫事事清。山横万古色，鹤带九皋声。",
            "易作神仙侣，难忘父子情。道人应识我，未肯说长生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 署中答武功姚合 ----------
    {
        "id": "yin-yao-fan-7",
        "title": "署中答武功姚合",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "原中多阴雨，惟留一室明。自宜居静者，谁得问先生。",
            "深井泉香出，危沙药更荣。全家笑无辱，曾不见戈兵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 赠龙阳尉马戴 ----------
    {
        "id": "yin-yao-fan-8",
        "title": "赠龙阳尉马戴",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "早学全身术，惟令耕近田。自输官税后，常卧晚云边。",
            "细草沿阶长，高萝出石悬。向来名姓茂，空被外情牵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 上巳日赠都上人 ----------
    {
        "id": "yin-yao-fan-9",
        "title": "上巳日赠都上人",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "三月初三日，千家与万家。蝶飞秦地草，莺入汉宫花。",
            "鞍马皆争丽，笙歌尽斗奢。吾师无所愿，惟愿老烟霞。",
            "曲水公卿宴，香尘尽满街。无心修禊事，独步到禅斋。",
            "细草萦愁目，繁花逆旅怀。绮罗人走马，遗落凤凰钗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送沈亚之尉南康 ----------
    {
        "id": "yin-yao-fan-10",
        "title": "送沈亚之尉南康",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "行迈南康路，客心离怨多。暮烟葵叶屋，秋月竹枝歌。",
            "孤鹤唳残梦，惊猿啸薜萝。对江翘首望，愁泪叠如波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 奉送刘使君王屋山隐居 ----------
    {
        "id": "yin-yao-fan-11",
        "title": "奉送刘使君王屋山隐居",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "散发风檐下，沈沈日渐曛。鹰拳擒野雀，蛛网猎飞蚊。",
            "群动能归计，吾生亦谩勤。尘缘难著眼，晚兴寄青云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 寄许浑秀才 ----------
    {
        "id": "yin-yao-fan-12",
        "title": "寄许浑秀才",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "文字饥难煮，为农策最良。兴来鉏晓月，倦后卧斜阳。",
            "秋稼连千顷，春花醉几场。任他名利客，车马闹康庄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送客游吴 ----------
    {
        "id": "yin-yao-fan-13",
        "title": "送客游吴",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "吴国水中央，波涛白渺茫。衣逢梅雨渍，船入稻花香。",
            "海戍通盐灶，山村带蜜房。欲知苏小小，君试到钱塘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 陆丞相故宅 ----------
    {
        "id": "yin-yao-fan-14",
        "title": "陆丞相故宅",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "衣冠零落久，今日事堪伤。厨起青烟薄，门开白日长。",
            "残梅欹古道，名石卧颓墙。山色依然好，兴衰未可量。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 中元日观诸道士步虚 ----------
    {
        "id": "yin-yao-fan-15",
        "title": "中元日观诸道士步虚",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "玄都开秘箓，白石礼先生。上界秋光净，中元夜气清。",
            "星辰朝帝处，鸾鹤步虚声。玉洞花长发，珠宫月最明。",
            "扫坛天地肃，投简鬼神惊。倘赐刀圭药，还留不死名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 醉赠刘十二（一作寄岭南张明府） ----------
    {
        "id": "yin-yao-fan-16",
        "title": "醉赠刘十二（一作寄岭南张明府）",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "春草正凄凄，知君过恶溪。莺将吉了语，猿共猓然啼。",
            "别路魂先断，还家梦几迷。定寻雷令剑，应识越王笄。",
            "树色多于北，潮声少向西。椰花好为酒，谁伴醉如泥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 早朝 ----------
    {
        "id": "yin-yao-fan-17",
        "title": "早朝",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "曙钟催入紫宸朝，列炬流虹映绛绡。天近鳌头花簇仗，",
            "风低豹尾乐鸣韶。衣冠一变无夷俗，律令重颁有正条。",
            "昨日钟山甘露降，玻璃满赐出宫瓢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 帝京二首 ----------
    {
        "id": "yin-yao-fan-18",
        "title": "帝京二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "列郡征才起俊髦，万机独使圣躬劳。开藩上相颁龙节，",
            "破虏将军展豹韬。地入黄图三辅壮，天垂华盖七星高。",
            "迎春别赐瑶池宴，捧进金盘五色桃。",
            "龙虎山河御气通，遥瞻帝阙五云红。英雄尽入江东籍，",
            "将相多收蓟北功。礼乐日稽三代盛，梯航岁贡万方同。",
            "都将俭德熙文治，淳俗应还太古风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 宫词 ----------
    {
        "id": "yin-yao-fan-19",
        "title": "宫词",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "悄悄深宫不见人，倚阑惟见石麒麟。芙蓉帐冷愁长夜，",
            "翡翠帘垂隔小春。天远难通青鸟信，风寒欲动锦花茵。",
            "夜深怕有羊车过，自起笼灯看雪纹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 郊居作 ----------
    {
        "id": "yin-yao-fan-20",
        "title": "郊居作",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "碧树浓阴护短垣，苍江春暖渚凫喧。买鱼试唤鸣榔艇，",
            "寻鹤因行隔垄村。生理何凭文是业，世情纵遣酒盈樽。",
            "相逢谓我迂疏甚，欲辨还憎恐失言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 闲居 ----------
    {
        "id": "yin-yao-fan-21",
        "title": "闲居",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "茂苑闲居木石同，旋开小径翦蒿蓬。虚游心在鸿濛外，",
            "穴处身疑培塿中。花影一阑吟夜月，松声半榻卧秋风。",
            "百年寄傲聊容膝，何必高车驷马通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 暮春述怀 ----------
    {
        "id": "yin-yao-fan-22",
        "title": "暮春述怀",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "为客山南二十年，愁来怳近落花天。阴云带雨连山脊，",
            "湿气成岚滴树巅。邻屋有声敲石火，野禽无语避茶烟。",
            "此时若遇孙阳顾，肯服盐车不受鞭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 端午日 ----------
    {
        "id": "yin-yao-fan-23",
        "title": "端午日",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "少年佳节倍多情，老去谁知感慨生。不效艾符趋习俗，",
            "但祈蒲酒话升平。鬓丝日日添头白，榴锦年年照眼明。",
            "千载贤愚同瞬息，几人湮没几垂名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 九日 ----------
    {
        "id": "yin-yao-fan-24",
        "title": "九日",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "万里飘零十二秋，不堪今倚夕阳楼。壮怀空掷班超笔，",
            "久客谁怜季子裘。瘴雨蛮烟朝暮景，平芜野草古今愁。",
            "酣歌欲尽登高兴，强把黄花插满头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 九日病起 ----------
    {
        "id": "yin-yao-fan-25",
        "title": "九日病起",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "重阳开满菊花金，病起支床惜赏心。紫蟹霜肥秋纵好，",
            "绿醅蚁滑晚慵斟。眼窥薄雾行殊倦，身怯寒风坐未禁。",
            "沈醉又成来岁约，遣怀聊作记时吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 寒夜 ----------
    {
        "id": "yin-yao-fan-26",
        "title": "寒夜",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "云冷江空岁暮时，竹阴梅影月参差。鸡催梦枕司晨早，",
            "更咽寒城报点迟。人事纷华潜动息，天心静默运推移。",
            "凭谁荡涤穷残候，入眼东风喜在期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 喜雨 ----------
    {
        "id": "yin-yao-fan-27",
        "title": "喜雨",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "临岐终日自裴回，干我茅斋半亩苔。山上乱云随手变，",
            "浙东飞雨过江来。一元和气归中正，百怪苍渊起蛰雷。",
            "千里稻花应秀色，酒樽风月醉亭台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 春游 ----------
    {
        "id": "yin-yao-fan-28",
        "title": "春游",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "明日城东看杏花，叮咛童子蚤将车。路从丹凤楼前过，",
            "酒向金鱼馆里赊。绿水满沟生杜若，暖云将雨湿泥沙。",
            "绝胜羊傅襄阳道，车骑西风拥鼓笳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 夜酌溪楼 ----------
    {
        "id": "yin-yao-fan-29",
        "title": "夜酌溪楼",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "楼居溪上凉生早，坐对城头起暮笳。打鼓泊船何处客，",
            "捣衣隔竹是谁家。玉绳低转宵初迥，银烛高烧月近斜。",
            "得意引杯须痛饮，好怀那许负年华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 旅行（一作金陵道中） ----------
    {
        "id": "yin-yao-fan-30",
        "title": "旅行（一作金陵道中）",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "烟树寒林半有无，野人行李更萧疏。堠长堠短逢官马，",
            "山北山南闻鹧鸪。万里关河成传舍，五更风雨忆呼卢。",
            "寂寥一点寒灯在，酒熟邻家许夜沽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 下第东归作 ----------
    {
        "id": "yin-yao-fan-31",
        "title": "下第东归作",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "十载驱驰倦荷锄，三年生计鬓萧疏。辛勤几逐英雄后，",
            "乙榜犹然姓氏虚。欲射狼星把弓箭，休将萤火读诗书。",
            "身贱自惭贫骨相，朗啸东归学钓鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 还京口 ----------
    {
        "id": "yin-yao-fan-32",
        "title": "还京口",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "黄鹤山头雪未消，行人归计在今朝。城高铁瓮江山壮，",
            "地接金陵草木凋。北府市楼闻旧酒，南桥官柳识归桡。",
            "吏民莫见参军面，水宿风餐鬓发焦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 襄口阻风 ----------
    {
        "id": "yin-yao-fan-33",
        "title": "襄口阻风",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "雪浪排空接海门，孤舟三日阻龙津。曹瞒曾堕周郎计，",
            "王导难遮庾亮尘。鸥散白云沈远浦，花飞红雨送残春。",
            "篙师整缆候明发，仍谒荒祠问鬼神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 潭州独步 ----------
    {
        "id": "yin-yao-fan-34",
        "title": "潭州独步",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "鹤发垂肩懒著巾，晚凉独步楚江滨。一帆暝色鸥边雨，",
            "数尺筇枝物外身。习巧未逢医拙手，闻歌先识采莲人。",
            "笑看斥鷃飞翔去，乐处蓬莱便有春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 金陵怀古 ----------
    {
        "id": "yin-yao-fan-35",
        "title": "金陵怀古",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "黄道天清拥珮珂，东南王气秣陵多。江吞彭蠡来三蜀，",
            "地接昆仑带九河。凤阙晓霞红散绮，龙池春水绿生波。",
            "华夷混一归真主，端拱无为乐太和。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 登凤凰台二首 ----------
    {
        "id": "yin-yao-fan-36",
        "title": "登凤凰台二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "凤凰台上望长安，五色宫袍照水寒。彩笔十年留翰墨，",
            "银河一夜卧阑干。三山飞鸟江天暮，六代离宫草树残。",
            "始信人生如一梦，壮怀莫使酒杯干。",
            "梧桐叶落秋风老，人去台空凤不来。梁武台城芳草合，",
            "吴王宫殿野花开。石头城下春生水，燕子堂前雨长苔。",
            "莫问人间兴废事，百年相遇且衔杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 韩信庙 ----------
    {
        "id": "yin-yao-fan-37",
        "title": "韩信庙",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "长空鸟尽将军死，无复中原入马蹄。身向九泉还属汉，",
            "功超诸将合封齐。荒凉古庙惟松柏，咫尺长陵又鹿麋。",
            "此日深怜萧相国，竟无一语到金闺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 访许浑 ----------
    {
        "id": "yin-yao-fan-38",
        "title": "访许浑",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "去郭来寻隐者居，柳阴假步小篮舆。每期会面初偿约，",
            "却计论心旧得书。浅绿垣墙绵薜荔，淡红池沼映芙渠。",
            "为言肯共留连饮，涧有青芹罟有鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 李舍人席上感遇 ----------
    {
        "id": "yin-yao-fan-39",
        "title": "李舍人席上感遇",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "微云敛雨天气清，松声出树秋泠泠。窗户长含碧萝色，",
            "溪流时带蛟龙腥。一官到手不可避，万事役我徒劳形。",
            "飘然曳杖出门去，无数好山江上横。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 和赵相公登鹳雀楼（楼在河中府，前瞻中条，下瞰大河） ----------
    {
        "id": "yin-yao-fan-40",
        "title": "和赵相公登鹳雀楼（楼在河中府，前瞻中条，下瞰大河）",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "危楼高架泬寥天，上相闲登立彩旃。树色到京三百里，",
            "河流归汉几千年。晴峰耸日当周道，秋谷垂花满舜田。",
            "云路何人见高志，最看西面赤阑前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 冬至酬刘使君 ----------
    {
        "id": "yin-yao-fan-41",
        "title": "冬至酬刘使君",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "异乡冬至又今朝，回首家山入梦遥。渐喜一阳从地复，",
            "却怜群沴逐冰消。梅含露蕊知迎腊，柳拂宫袍忆候朝。",
            "多少故人承宴赏，五云堆里听箫韶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 李节度平虏诗 ----------
    {
        "id": "yin-yao-fan-42",
        "title": "李节度平虏诗",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "百万王师下日边，将军雄略可图全。元勋未论封茅异，",
            "捷势应知破竹然。燕警无烽清朔漠，秦文有宝进蓝田。",
            "太平从此销兵甲，记取红羊换劫年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 金陵上李公垂侍郎 ----------
    {
        "id": "yin-yao-fan-43",
        "title": "金陵上李公垂侍郎",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "海国微茫散晓暾，郁葱佳气满乾坤。六朝空据长江险，",
            "一统今归圣代尊。西北诸峰连朔漠，东南众水合昆仑。",
            "愿从吾道禧文运，再使河清俗化淳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 赠惟俨师 ----------
    {
        "id": "yin-yao-fan-44",
        "title": "赠惟俨师",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "焕然文采照青春，一策江湖自在身。云锁木龛聊息影，",
            "雪香纸袄不生尘。谈禅早续灯无尽，护法重编论有神。",
            "拟扫绿阴浮佛寺，桫椤高树结为邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 寄许浑秀才 ----------
    {
        "id": "yin-yao-fan-45",
        "title": "寄许浑秀才",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "万木惊秋叶渐稀，静探造化见玄机。眼前谁悟先天理，",
            "去后还知今日非。树拥秣陵千嶂合，云开萧寺一僧归。",
            "汉廷累下征贤诏，未许严陵老钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送白舍人渡江 ----------
    {
        "id": "yin-yao-fan-46",
        "title": "送白舍人渡江",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "晓发龙江第一程，诸公同济似登瀛。海门日上千峰出，",
            "桃叶波平一棹轻。横锁已沈王濬筏，投鞭难阻谢玄兵。",
            "片时喜得东风便，回首钟声隔凤城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 送刘禹锡侍御出刺连州 ----------
    {
        "id": "yin-yao-fan-47",
        "title": "送刘禹锡侍御出刺连州",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "遐荒迢递五羊城，归兴浓消客里情。家近似忘山路险，",
            "土甘殊觉瘴烟轻。梅花清入罗浮梦，荔子红分广海程。",
            "此去定知偿隐趣，石田春雨读书耕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 送韦侍御报使西蕃 ----------
    {
        "id": "yin-yao-fan-48",
        "title": "送韦侍御报使西蕃",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "归奏圣朝行万里，却衔天诏报蕃臣。本是诸生守文墨，",
            "今将匹马静烟尘。旅宿关河逢暮雨，春耕亭障识遗民。",
            "此去多应收故地，宁辞沙塞往来频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 寒食城南即事因访蓝田韦明府 ----------
    {
        "id": "yin-yao-fan-49",
        "title": "寒食城南即事因访蓝田韦明府",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "闲出城南禁火天，路傍骑马独摇鞭。青松古墓伤碑碣，",
            "红杏春园羡管弦。徒说鸊鹈膏玉剑，漫夸蚨血点铜钱。",
            "世间尽是悠悠事，且饮韦家冷酒眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 送源中丞使新罗（一作姚合诗） ----------
    {
        "id": "yin-yao-fan-50",
        "title": "送源中丞使新罗（一作姚合诗）",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "赤墀奉命使殊方，官重霜台紫绶光。玉节在船清海怪，",
            "金函开诏抚夷王。云晴渐觉山川异，风便宁知道路长。",
            "谁得似君将雨露，海东万里洒扶桑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 送景玄上人还山 ----------
    {
        "id": "yin-yao-fan-51",
        "title": "送景玄上人还山",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "嵩阳听罢讲经钟，远访庭闱锡度空。蒲履谩从归后织，",
            "衲衣犹记别时缝。地横龙朔连沙暝，山入乌桓碧树重。",
            "梵宇传来金贝叶，花前拜捧慰亲容。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 宫人入道 ----------
    {
        "id": "yin-yao-fan-52",
        "title": "宫人入道",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "卸却宫妆锦绣衣，黄冠素服制相宜。锡名近奉君王旨，",
            "佩箓新参老氏师。白昼无情趋玉陛，清宵有梦步瑶池。",
            "绿鬟女伴含愁别，释尽当年妒宠私。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 友人山中梅花 ----------
    {
        "id": "yin-yao-fan-53",
        "title": "友人山中梅花",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "南国看花动远情，沈郎诗苦瘦容生。铁心自儗山中赋，",
            "玉笛谁将月下横。临水一枝春占早，照人千树雪同清。",
            "好风吹醒罗浮梦，莫听空林翠羽声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 客中有感 ----------
    {
        "id": "yin-yao-fan-54",
        "title": "客中有感",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "天地一身在，头颅五十过。流年消壮志，空使泪成河。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 忆家二首 ----------
    {
        "id": "yin-yao-fan-55",
        "title": "忆家二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "新霁飏林初，蘋花贴岸舒。故乡今夜月，犹得照孤庐。",
            "树拥溪边阁，山浮雨后岚。白头归未得，梦里望江南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 江行二首 ----------
    {
        "id": "yin-yao-fan-56",
        "title": "江行二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "暝色沧州迥，秋声玉峡长。只因江上月，不觉过浔阳。",
            "晚泊长江口，寒沙白似霜。年光流不尽，东去水声长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 偶题 ----------
    {
        "id": "yin-yao-fan-57",
        "title": "偶题",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "越女收龙眼，蛮儿拾象牙。长安千万里，走马送谁家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 关中伤乱后 ----------
    {
        "id": "yin-yao-fan-58",
        "title": "关中伤乱后",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "去岁干戈险，今年蝗旱忧。关西归战马，海内卖耕牛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 楚江怀古 ----------
    {
        "id": "yin-yao-fan-59",
        "title": "楚江怀古",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "骚灵不可见，楚些竟谁闻。欲采蘋花去，沧州隔暮云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 张飞庙 ----------
    {
        "id": "yin-yao-fan-60",
        "title": "张飞庙",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "威名垂万古，勇力冠当时。回首三分国，何人赋黍离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 生公讲台 ----------
    {
        "id": "yin-yao-fan-61",
        "title": "生公讲台",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "暝色护楼台，阴云昼未开。一尘无处著，花雨遍苍苔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 席上听琴 ----------
    {
        "id": "yin-yao-fan-62",
        "title": "席上听琴",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "高堂流月明，万籁不到耳。一听清心魂，飞絮春纷起。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 酬雍秀才二首 ----------
    {
        "id": "yin-yao-fan-63",
        "title": "酬雍秀才二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "晚市人烟合，归帆带夕阳。栖迟未归客，犹著锦衣裳。",
            "卧病茅窗下，惊闻两月过。兴来聊赋咏，清婉逼阴何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 竹 ----------
    {
        "id": "yin-yao-fan-64",
        "title": "竹",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "窗户尽萧森，空阶凝碧阴。不缘冰雪里，为识岁寒心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 春怨 ----------
    {
        "id": "yin-yao-fan-65",
        "title": "春怨",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "柳花扑帘春欲尽，绿阴障林莺乱啼。",
            "只愁明日送春去，落日满园啼竹鸡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 馆娃宫 ----------
    {
        "id": "yin-yao-fan-66",
        "title": "馆娃宫",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "宫女三千去不回，真珠翠羽是尘埃。",
            "夫差旧国久破碎，红燕自归花自开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 汉宫词三首 ----------
    {
        "id": "yin-yao-fan-67",
        "title": "汉宫词三首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "成帝夫人泪满怀，璧宫相趁落空阶。",
            "可怜玉貌花前死，惟有君恩白燕钗。",
            "霍家有女字成君，年少教人著绣裙。",
            "枉杀宫中许皇后，椒房恩泽是浮云。",
            "骏马金鞍白玉鞭，宫中来取李延年。",
            "承恩直日鸳鸯殿，一曲清歌在九天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 同州端午 ----------
    {
        "id": "yin-yao-fan-68",
        "title": "同州端午",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "鹤发垂肩尺许长，离家三十五端阳。",
            "儿童见说深惊讶，却问何方是故乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 夜过洞庭 ----------
    {
        "id": "yin-yao-fan-69",
        "title": "夜过洞庭",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "笙歌只解闹花天，谁是敲冰掉小船。",
            "为觅潇湘幽隐处，夜深载月听鸣泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 游山南寺二首 ----------
    {
        "id": "yin-yao-fan-70",
        "title": "游山南寺二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "山中尽日无人到，竹外交加百鸟鸣。",
            "昨日小楼微雨过，樱桃花落晚风晴。",
            "踏碎羊山黄叶堆，天飞细雨隐轻雷。",
            "朗陵莫讶来何晚，不忍听君话别杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 寄太仆田卿二首 ----------
    {
        "id": "yin-yao-fan-71",
        "title": "寄太仆田卿二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "客窗强饮太匆匆，急雨寒风意万重。",
            "蓦上心来消未得，梦回又听五更钟。",
            "一阳才动伏群阴，万物于今寓太音。",
            "若喜长生添线日，微微消息识天心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 新昌井 ----------
    {
        "id": "yin-yao-fan-72",
        "title": "新昌井",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "辘轳千转劳筋力，待得甘泉渴杀人。",
            "且共山麋同饮涧，玉沙铺底浅磷磷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 经靖安里 ----------
    {
        "id": "yin-yao-fan-73",
        "title": "经靖安里",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "巷底萧萧绝市尘，供愁疏雨打黄昏。",
            "悠然一曲泉明调，浅立闲愁轻闭门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 闻筝歌 ----------
    {
        "id": "yin-yao-fan-74",
        "title": "闻筝歌",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "凄凄切切断肠声，指滑音柔万种情。",
            "花影深沈遮不住，度帏穿幕又残更。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 吹笙歌 ----------
    {
        "id": "yin-yao-fan-75",
        "title": "吹笙歌",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "伶儿竹声愁绕空，秦女泪湿燕支红。",
            "玉桃花片落不住，三十六簧能唤风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 赠歌人郭婉二首 ----------
    {
        "id": "yin-yao-fan-76",
        "title": "赠歌人郭婉二首",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "石家金谷旧歌人，起唱花筵泪满巾。",
            "红粉少年诸弟子，一时惆怅望梁尘。",
            "云满衣裳月满身，轻盈归步过流尘。",
            "五更无限留连意，常恐风花又一春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 潭州席上赠舞柘枝妓 ----------
    {
        "id": "yin-yao-fan-77",
        "title": "潭州席上赠舞柘枝妓",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "姑苏太守青娥女，流落长沙舞柘枝。",
            "坐满绣衣皆不识，可怜红脸泪双垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 句 ----------
    {
        "id": "yin-yao-fan-78",
        "title": "句",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "瘴雨出虹蝀，蛮烟渡江急。尝闻岛夷俗，犀象满城邑。",
            "（《寄岭南张明甫》，见《方舆胜览》）。",
            "第四百九十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 句 ----------
    {
        "id": "yin-yao-fan-79",
        "title": "句",
        "author": "殷尧藩",
        "poet_id": "yin-yao-fan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "云收碧海连天水，风动红蕉滴露光。（送韩协律胜起容府幕",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]