# -*- coding: utf-8 -*-
"""
朱景玄卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 16 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 题吕食新水阁兼寄南商州郎中 ----------
    {
        "id": "zhu-jing-xuan-1",
        "title": "题吕食新水阁兼寄南商州郎中",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "丹槛初结构，孤高冠清川。庭临谷中树，檐落山上泉。",
            "晓色挂残月，夜声杂繁弦。青春去如水，康乐归何年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 华山南望春 ----------
    {
        "id": "zhu-jing-xuan-2",
        "title": "华山南望春",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "灵岳多异状，巉巉出虚空。闲云恋岩壑，起灭苍翠中。",
            "皓气澄野水，神光秘琼宫。鹤巢前林雪，瀑落满涧风。",
            "春尽花未发，川回路难穷。何因著山屐，鹿迹寻羊公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 水阁 ----------
    {
        "id": "zhu-jing-xuan-3",
        "title": "水阁",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "楼居半池上，澄影共相空。谢守题诗处，莲开净碧中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 迎风亭 ----------
    {
        "id": "zhu-jing-xuan-4",
        "title": "迎风亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "山雨留清气，溪飙送早凉。时回石门步，阶下碧云光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 双槠亭 ----------
    {
        "id": "zhu-jing-xuan-5",
        "title": "双槠亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "连檐对双树，冬翠夏无尘。未肯惭桃李，成阴不待春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 莲亭 ----------
    {
        "id": "zhu-jing-xuan-6",
        "title": "莲亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "回塘最幽处，拍水小亭开。莫怪阑干湿，䴔䴖夜宿来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 中峰亭 ----------
    {
        "id": "zhu-jing-xuan-7",
        "title": "中峰亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "中峰上翠微，窗晓早霞飞。几引登山屐，春风踏雪归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 飞云亭 ----------
    {
        "id": "zhu-jing-xuan-8",
        "title": "飞云亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "上结孤圆顶，飞轩出泰清。有时迷处所，梁栋晓云生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 四望亭 ----------
    {
        "id": "zhu-jing-xuan-9",
        "title": "四望亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "高亭群峰首，四面俯晴川。每见晨光晓，阶前万井烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 望莲台 ----------
    {
        "id": "zhu-jing-xuan-10",
        "title": "望莲台",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "秋台好登望，菡萏发清池。半似红颜醉，凌波欲暮时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 茶亭 ----------
    {
        "id": "zhu-jing-xuan-11",
        "title": "茶亭",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "静得尘埃外，茶芳小华山。此亭真寂寞，世路少人闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 宿新安村步 ----------
    {
        "id": "zhu-jing-xuan-12",
        "title": "宿新安村步",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "淅淅寒流涨浅沙，月明空渚遍芦花。",
            "离人偶宿孤村下，永夜闻砧一两家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 远闻本郡行春到旧山二首 ----------
    {
        "id": "zhu-jing-xuan-13",
        "title": "远闻本郡行春到旧山二首",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "一身从宦留京邑，五马遥闻到旧山。",
            "已领烟霞光野径，深惭老幼候柴关。",
            "清风借响松筠外，画隼停晖水石间。",
            "定掩溪名在图传，共知轩盖此登攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 和崔使君临发不得观积雪 ----------
    {
        "id": "zhu-jing-xuan-14",
        "title": "和崔使君临发不得观积雪",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "贫居稍与池塘近，旬日轩车不降来。",
            "一树琼花空有待，晓风看落满青苔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 句 ----------
    {
        "id": "zhu-jing-xuan-15",
        "title": "句",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "塞鸿先秋去，边草入夏生。（见《酉阳杂俎》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 溪东岑望天都山 ----------
    {
        "id": "zhu-jing-xuan-16",
        "title": "溪东岑望天都山",
        "author": "朱景玄",
        "poet_id": "zhu-jing-xuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "目望浮山丘，梯云上东岑。群峰争入冥，巉巉生太阴。",
            "昔贤此升仙，结构穷耸深。未晓日先照，当昼色半沉。",
            "风泉雪霜飞，云树琼玉林。大道非闭隔，无路不可寻。",
            "窥镜澄夙虑，望坛起敬心。一从呼子安，永绝金玉音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]