# -*- coding: utf-8 -*-
"""
崔峒卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 48 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 扬州选蒙相公赏判雪后呈上 ----------
    {
        "id": "cui-dong-1",
        "title": "扬州选蒙相公赏判雪后呈上",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "自得山公许，休耕海上田。惭看长史传，欲弃钓鱼船。",
            "穷巷殷忧日，芜城雨雪天。此时瞻相府，心事比旌悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 客舍书情寄赵中丞 ----------
    {
        "id": "cui-dong-2",
        "title": "客舍书情寄赵中丞",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "东楚复西秦，浮云类此身。关山劳策蹇，僮仆惯投人。",
            "孤客来千里，全家托四邻。生涯难自料，中夜问情亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 客舍有怀因呈诸在事 ----------
    {
        "id": "cui-dong-3",
        "title": "客舍有怀因呈诸在事",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "读书常苦节，待诏岂辞贫。暮雪犹驱马，晡餐又寄人。",
            "愁来占吉梦，老去惜良辰。延首平津阁，家山日已春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 书怀寄杨郭李王判官 ----------
    {
        "id": "cui-dong-4",
        "title": "书怀寄杨郭李王判官",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "惯作云林客，因成懒漫人。吏欺从政拙，妻笑理家贫。",
            "李郭应时望，王杨入幕频。从容丞相阁，知忆故园春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 奉和给事寓直 ----------
    {
        "id": "cui-dong-5",
        "title": "奉和给事寓直",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "桂枝家共折，鸡树代相传。忝向鸾台下，仍看雁影连。",
            "夜闲方步月，漏尽欲朝天。知去丹墀近，明王许荐贤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 初入集贤院赠李献仁（曾于常山联官） ----------
    {
        "id": "cui-dong-6",
        "title": "初入集贤院赠李献仁（曾于常山联官）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "燕代官初罢，江湖路便分。九迁从命薄，四十幸人闻。",
            "迹愧趋丹禁，身曾系白云。何由返沧海，昨日谒明君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 酬李补阙雨中寄赠 ----------
    {
        "id": "cui-dong-7",
        "title": "酬李补阙雨中寄赠",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "十年随马宿，几度受人恩。白发还乡井，微官有子孙。",
            "竹窗寒雨滴，苦砌夜虫喧。独愧东垣友，新诗慰旅魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 初除拾遗酬丘二十二见寄（一作初拜命酬丘丹见赠） ----------
    {
        "id": "cui-dong-8",
        "title": "初除拾遗酬丘二十二见寄（一作初拜命酬丘丹见赠）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "江海久垂纶，朝衣忽挂身。丹墀初谒帝，白发免羞人。",
            "才愧文章士，名当谏诤臣。空馀荐贤分，不敢负交亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 刘展下判官相招以诗答之 ----------
    {
        "id": "cui-dong-9",
        "title": "刘展下判官相招以诗答之",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "国有非常宠，家承异姓勋。背恩惭皎日，不义若浮云。",
            "但使忠贞在，甘从玉石焚。窜身如有地，梦寐见明君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送侯山人赴会稽 ----------
    {
        "id": "cui-dong-10",
        "title": "送侯山人赴会稽",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "仙客辞萝月，东来就一官。且归沧海住，犹向白云看。",
            "猿叫江天暮，虫声野浦寒。时游镜湖里，为我把鱼竿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 宿禅智寺上方演大师院 ----------
    {
        "id": "cui-dong-11",
        "title": "宿禅智寺上方演大师院",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "石林高几许，金刹在中峰。白日空山梵，清霜后夜钟。",
            "竹窗回翠壁，苔径入寒松。幸接无生法，疑心怯所从。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 题空山人石室 ----------
    {
        "id": "cui-dong-12",
        "title": "题空山人石室",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "早晚悟无生，头陀不到城。云山知夏腊，猿鸟见修行。",
            "地僻无溪路，人寻逐水声。年年深谷里，谁识远公名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 登蒋山开善寺（一作李嘉祐诗） ----------
    {
        "id": "cui-dong-13",
        "title": "登蒋山开善寺（一作李嘉祐诗）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "山殿秋云里，香烟出翠微。客寻朝磬至，僧背夕阳归。",
            "下界千门见，前朝万事非。看心兼送目，葭菼暮依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 题崇福寺禅院 ----------
    {
        "id": "cui-dong-14",
        "title": "题崇福寺禅院",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "僧家竟何事，扫地与焚香。清磬度山翠，闲云来竹房。",
            "身心尘外远，岁月坐中长。向晚禅堂掩，无人空夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 秋晚送丹徒许明府赴上国，因寄江南故人 ----------
    {
        "id": "cui-dong-15",
        "title": "秋晚送丹徒许明府赴上国，因寄江南故人",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "秋暮之彭泽，篱花远近逢。君书前日至，别后此时重。",
            "寒夜江边月，晴天海上峰。还知南地客，招引住新丰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送薛仲方归扬州 ----------
    {
        "id": "cui-dong-16",
        "title": "送薛仲方归扬州",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "佳句应无敌，贞心不有猜。惭为丈人行，怯见后生才。",
            "泛舸贪斜月，浮桡值早梅。绿杨新过雨，芳草待君来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送韦员外还京 ----------
    {
        "id": "cui-dong-17",
        "title": "送韦员外还京",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "十年离乱后，此去若为情。春晚香山绿，人稀豫水清。",
            "野陂看独树，关路逐残莺。前殿朝明主，应怜白发生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 润州送友人 ----------
    {
        "id": "cui-dong-18",
        "title": "润州送友人",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "见君还此地，洒泪向江边。国士劳相问，家书无处传。",
            "荒城胡马迹，塞木戍人烟。一路堪愁思，孤舟何渺然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送张芬东归 ----------
    {
        "id": "cui-dong-19",
        "title": "送张芬东归",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "喧喧五衢上，鞍马自驱驰。落日临阡陌，贫交欲别离。",
            "早知时事异，堪与世人随。握手将何赠，君心我独知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送苏修游上饶 ----------
    {
        "id": "cui-dong-20",
        "title": "送苏修游上饶",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "爱尔无羁束，云山恣意过。一身随远岫，孤棹任轻波。",
            "世事关情少，渔家寄宿多。芦花浅淡处，江月奈人何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送陆明府之盱眙 ----------
    {
        "id": "cui-dong-21",
        "title": "送陆明府之盱眙",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "陶令之官去，穷愁惨别魂。白烟横海戍，红叶下淮村。",
            "澹浪摇山郭，平芜到县门。政成堪吏隐，免负府公恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 江南回逢赵曜，因送任十一赴交城主簿 ----------
    {
        "id": "cui-dong-22",
        "title": "江南回逢赵曜，因送任十一赴交城主簿",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "江上长相忆，因高北望看。不知携老幼，何处度艰难。",
            "屈指同人尽，伤心故里残。遥怜驱匹马，白首到微官。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送薛良史往越州谒从叔 ----------
    {
        "id": "cui-dong-23",
        "title": "送薛良史往越州谒从叔",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "辞家年已久，与子分偏深。易得相思泪，难为欲别心。",
            "孤云随浦口，几日到山阴。遥想兰亭下，清风满竹林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 送丘二十二之苏州 ----------
    {
        "id": "cui-dong-24",
        "title": "送丘二十二之苏州",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "积水与寒烟，嘉禾路几千。孤猿啼海岛，群雁起湖田。",
            "曾见长洲苑，尝闻大雅篇。却将封事去，知尔爱闲眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 登润州芙蓉楼 ----------
    {
        "id": "cui-dong-25",
        "title": "登润州芙蓉楼",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "上古人何在，东流水不归。往来潮有信，朝暮事成非。",
            "烟树临沙静，云帆入海稀。郡楼多逸兴，良牧谢玄晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 江上书怀 ----------
    {
        "id": "cui-dong-26",
        "title": "江上书怀",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "骨肉天涯别，江山日落时。泪流襟上血，发变镜中丝。",
            "胡越书难到，存亡梦岂知。登高回首罢，形影自相随。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 春日忆姚氏外甥 ----------
    {
        "id": "cui-dong-27",
        "title": "春日忆姚氏外甥",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "离乱人相失，春秋雁自飞。只缘行路远，未必寄书稀。",
            "二月花无数，频年意有违。落晖看过后，独坐泪沾衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 送真上人还兰若 ----------
    {
        "id": "cui-dong-28",
        "title": "送真上人还兰若",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "得道云林久，年深暂一归。出山逢世乱，乞食觉人稀。",
            "半偈初传法，中峰又掩扉。爱憎应不染，尘俗自依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 润州送师弟自江夏往台州 ----------
    {
        "id": "cui-dong-29",
        "title": "润州送师弟自江夏往台州",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "远客乘流去，孤帆向夜开。春风江上使，前日汉阳来。",
            "别路犹千里，离心重一杯。剡溪木未落，羡尔过天台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 送李道士归山 ----------
    {
        "id": "cui-dong-30",
        "title": "送李道士归山",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "秋城临古路，城上望君还。旷野入寒草，独行随远山。",
            "授人鸿宝内，将犬白云间。早晚烧丹罢，遥知冰雪寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 宿江西窦主簿厅（与此公亡兄联官） ----------
    {
        "id": "cui-dong-31",
        "title": "宿江西窦主簿厅（与此公亡兄联官）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "广庭方缓步，星汉话中移。月满关山道，乌啼霜树枝。",
            "时艰难会合，年长重亲知。前事成金石，凄然泪欲垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 喜逢妻弟郑损因送入京 ----------
    {
        "id": "cui-dong-32",
        "title": "喜逢妻弟郑损因送入京",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "乱后自江城，相逢喜复惊。为经多载别，欲问小时名。",
            "对酒悲前事，论文畏后生。遥知盈卷轴，纸贵在江城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 咏门下画小松上元王杜三相公（一作钱起诗） ----------
    {
        "id": "cui-dong-33",
        "title": "咏门下画小松上元王杜三相公（一作钱起诗）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "昔闻生涧底，今见起毫端。众草此时没，何人知岁寒。",
            "岂能裨栋宇，且贵出门阑。只在丹青意，凌云也不难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 寄上礼部李侍郎 ----------
    {
        "id": "cui-dong-34",
        "title": "寄上礼部李侍郎",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "吴楚相逢处，江湖共泛时。任风舟去远，待月酒行迟。",
            "白发常同叹，青云本要期。贵来君却少，秋至老偏悲。",
            "玉佩明朝盛，苍苔陋巷滋。追寻恨无路，唯有梦相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 书情寄上苏州韦使君兼呈吴县李明府 ----------
    {
        "id": "cui-dong-35",
        "title": "书情寄上苏州韦使君兼呈吴县李明府",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "数年湖上谢浮名，竹杖纱巾遂性情。云外有时逢寺宿，",
            "日西无事傍江行。陶潜县里看花发，庾亮楼中对月明。",
            "谁念献书来万里，君王深在九重城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 题桐庐李明府官舍（一作赠同官李明府） ----------
    {
        "id": "cui-dong-36",
        "title": "题桐庐李明府官舍（一作赠同官李明府）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "讼堂寂寂对烟霞，五柳门前聚晓鸦。流水声中视公事，",
            "寒山影里见人家。观风竞美新为政，计日还知旧触邪。",
            "可惜陶潜无限酒，不逢篱菊正开花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 赠窦十九（时公车待诏长安） ----------
    {
        "id": "cui-dong-37",
        "title": "赠窦十九（时公车待诏长安）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "灵台暮宿意多违，木落花开羡客归。江海几时传锦字，",
            "风尘不觉化缁衣。山阳会里同人少，灞曲农时故老稀。",
            "幸得汉皇容直谏，怜君未遇觉人非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 虔州见郑表新诗因以寄赠 ----------
    {
        "id": "cui-dong-38",
        "title": "虔州见郑表新诗因以寄赠",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "梅花岭里见新诗，感激情深过楚词。平子四愁今莫比，",
            "休文八咏自同时。萍乡露冕真堪惜，凤沼鸣珂已讶迟。",
            "才子风流定难见，湖南春草但相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 赠元秘书 ----------
    {
        "id": "cui-dong-39",
        "title": "赠元秘书",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "旧书稍稍出风尘，孤客逢秋感此身。秦地谬为门下客，",
            "淮阴徒笑市中人。也闻阮籍寻常醉，见说陈平不久贫。",
            "幸有故人茅屋在，更将心事问情亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 送韦八少府判官归东京 ----------
    {
        "id": "cui-dong-40",
        "title": "送韦八少府判官归东京",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "玄成世业紫真官，文似相如貌胜潘。鸿雁南飞人独去，",
            "云山一别岁将阑。清淮水急桑林晚，古驿霜多柿叶寒。",
            "琼树相思何日见，银钩数字莫为难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 送冯八将军奏事毕归滑台幕府 ----------
    {
        "id": "cui-dong-41",
        "title": "送冯八将军奏事毕归滑台幕府",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "王门别后到沧洲，帝里相逢俱白头。自叹马卿常带疾，",
            "还嗟李广不封侯。棠梨宫里瞻龙衮，细柳营中著虎裘。",
            "想到滑台桑叶落，黄河东注杏园秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送王侍御佐婺州（作郎士元：盖少府新除江南尉问风俗） ----------
    {
        "id": "cui-dong-42",
        "title": "送王侍御佐婺州（作郎士元：盖少府新除江南尉问风俗）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "闻君作尉向江潭。吴越风烟到自谙。客路寻常经竹径，",
            "人家大底傍山岚。缘溪花木偏宜远，避地衣冠尽向南。",
            "惟有夜猿啼海树，思乡望北意难堪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 越中送王使君赴江华 ----------
    {
        "id": "cui-dong-43",
        "title": "越中送王使君赴江华",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "皂盖春风自越溪，独寻芳树桂阳西。远水浮云随马去，",
            "空山弱筱向云低。遥知异政荆门北，旧许新诗康乐齐。",
            "万里相思在何处，九疑残雪白猿啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送皇甫冉往白田 ----------
    {
        "id": "cui-dong-44",
        "title": "送皇甫冉往白田",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "江边尽日雉鸣飞，君向白田何日归。楚地蒹葭连海迥，",
            "隋朝杨柳映堤稀。津楼故市无行客，山馆空庭闭落晖。",
            "试问疲人与征战，使君双泪定沾衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 题兰若 ----------
    {
        "id": "cui-dong-45",
        "title": "题兰若",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "绝顶茅庵老此生，寒云孤木独经行。",
            "世人那得知幽径，遥向青峰礼磬声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送贺兰广赴选 ----------
    {
        "id": "cui-dong-46",
        "title": "送贺兰广赴选",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "而今用武尔攻文，流辈干时独卧云。",
            "白发青袍趋会府，定应衡镜却惭君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 清江曲内一绝（折腰体） ----------
    {
        "id": "cui-dong-47",
        "title": "清江曲内一绝（折腰体）",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "八月长江去浪平，片帆一道带风轻。",
            "极目不分天水色，南山南是岳阳城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 武康郭外望许纬先生山居 ----------
    {
        "id": "cui-dong-48",
        "title": "武康郭外望许纬先生山居",
        "author": "崔峒",
        "poet_id": "cui-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "湖上千峰带落晖，白云开处见柴扉。",
            "松门一径仍生草，应是仙人向郭稀。",
            "第二百九十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]