# -*- coding: utf-8 -*-
"""
崔道融卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 68 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 梅花 ----------
    {
        "id": "cui-dao-rong-1",
        "title": "梅花",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "数萼初含雪，孤标画本难。香中别有韵，清极不知寒。",
            "横笛和愁听，斜枝倚病看。朔风如解意，容易莫摧残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 铜雀妓二首 ----------
    {
        "id": "cui-dao-rong-2",
        "title": "铜雀妓二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "严妆垂玉箸，妙舞对清风。无复君王顾，春来起渐慵。",
            "歌咽新翻曲，香销旧赐衣。陵园春雨暗，不见六龙归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 春闺二首 ----------
    {
        "id": "cui-dao-rong-3",
        "title": "春闺二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "寒食月明雨，落花香满泥。佳人持锦字，无雁寄辽西。",
            "欲剪宜春字，春寒入剪刀。辽阳在何处，莫望寄征袍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 访僧不遇 ----------
    {
        "id": "cui-dao-rong-4",
        "title": "访僧不遇",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "寻僧已寂寞，林下锁山房。松竹虽无语，牵衣借晚凉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 田上 ----------
    {
        "id": "cui-dao-rong-5",
        "title": "田上",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "雨足高田白，披蓑半夜耕。人牛力俱尽，东方殊未明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 月夕 ----------
    {
        "id": "cui-dao-rong-6",
        "title": "月夕",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "月上随人意，人闲月更清。朱楼高百尺，不见到天明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 槿花 ----------
    {
        "id": "cui-dao-rong-7",
        "title": "槿花",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "槿花不见夕，一日一回新。东风吹桃李，须到明年春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 西施滩 ----------
    {
        "id": "cui-dao-rong-8",
        "title": "西施滩",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "宰嚭亡吴国，西施陷恶名。浣纱春水急，似有不平声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 江上逢故人 ----------
    {
        "id": "cui-dao-rong-9",
        "title": "江上逢故人",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "故里琴樽侣，相逢近腊梅。江村买一醉，破泪却成咍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 牧竖 ----------
    {
        "id": "cui-dao-rong-10",
        "title": "牧竖",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "牧竖持蓑笠，逢人气傲然。卧牛吹短笛，耕却傍溪田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 过农家 ----------
    {
        "id": "cui-dao-rong-11",
        "title": "过农家",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "欲羡农家子，秋新看刈禾。苏秦无负郭，六印又如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 江夕 ----------
    {
        "id": "cui-dao-rong-12",
        "title": "江夕",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "江心秋月白，起柁信潮行。蛟龙化为人，半夜吹笛声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 春墅 ----------
    {
        "id": "cui-dao-rong-13",
        "title": "春墅",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "蛙声近过社，农事忽已忙。邻妇饷田归，不见百花芳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 江村 ----------
    {
        "id": "cui-dao-rong-14",
        "title": "江村",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "日暮片帆落，江村如有情。独对沙上月，满船人睡声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 拟乐府子夜四时歌四首 ----------
    {
        "id": "cui-dao-rong-15",
        "title": "拟乐府子夜四时歌四首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "吴子爱桃李，月色不到地。明朝欲看花，六宫人不睡。",
            "凉轩待月生，暗里萤飞出。低回不称意，蛙鸣乱清瑟。",
            "月色明如昼，虫声入户多。狂夫自不归，满地无天河。",
            "银缸照残梦，零泪沾粉臆。洞房犹自寒，何况关山北。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 寄人二首 ----------
    {
        "id": "cui-dao-rong-16",
        "title": "寄人二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "花上断续雨，江头来去风。相思春欲尽，未遣酒尊空。",
            "澹澹长江水，悠悠远客情。落花相与恨，到地一无声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 江鸥 ----------
    {
        "id": "cui-dao-rong-17",
        "title": "江鸥",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "白鸟波上栖，见人懒飞起。为有求鱼心，不是恋江水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 春晚 ----------
    {
        "id": "cui-dao-rong-18",
        "title": "春晚",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "三月寒食时，日色浓于酒。落尽墙头花，莺声隔原柳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 汉宫词 ----------
    {
        "id": "cui-dao-rong-19",
        "title": "汉宫词",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "独诏胡衣出，天花落殿堂。他人不敢妒，垂泪向君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 旅行 ----------
    {
        "id": "cui-dao-rong-20",
        "title": "旅行",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "少壮经勤苦，衰年始浪游。谁怜不龟手，他处却封侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 班婕妤 ----------
    {
        "id": "cui-dao-rong-21",
        "title": "班婕妤",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "宠极辞同辇，恩深弃后宫。自题秋扇后，不敢怨春风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 元日有题 ----------
    {
        "id": "cui-dao-rong-22",
        "title": "元日有题",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "十载元正酒，相欢意转深。自量麋鹿分，只合在山林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 古树 ----------
    {
        "id": "cui-dao-rong-23",
        "title": "古树",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "古树春风入，阳和力太迟。莫言生意尽，更引万年枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 春题二首 ----------
    {
        "id": "cui-dao-rong-24",
        "title": "春题二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "青春未得意，见花却如雠。路逢白面郎，醉插花满头。",
            "满眼桃李花，愁人如不见。别有惜花人，东风莫吹散。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 长安春 ----------
    {
        "id": "cui-dao-rong-25",
        "title": "长安春",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "长安牡丹开，绣毂辗晴雷。若使花长在，人应看不回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 病起二首 ----------
    {
        "id": "cui-dao-rong-26",
        "title": "病起二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "病起春已晚，曳筇伤绿苔。强攀庭树枝，唤作花未开。",
            "病起绕庭除，春泥粘屐齿。如从万里来，骨肉满面喜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 峡路 ----------
    {
        "id": "cui-dao-rong-27",
        "title": "峡路",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "清猿啼不住，白水下来新。八月莫为客，夜长愁杀人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 长门怨 ----------
    {
        "id": "cui-dao-rong-28",
        "title": "长门怨",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "长门春欲尽，明月照花枝。买得相如赋，君恩不可移。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 月夕有怀 ----------
    {
        "id": "cui-dao-rong-29",
        "title": "月夕有怀",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "圆光照一海，远客在孤舟。相忆无期见，中宵独上楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 夜泊九江 ----------
    {
        "id": "cui-dao-rong-30",
        "title": "夜泊九江",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "夜泊江门外，欢声月里楼。明朝归去路，犹隔洞庭秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 寒食夜 ----------
    {
        "id": "cui-dao-rong-31",
        "title": "寒食夜",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "满地梨花白，风吹碎月明。大家寒食夜，独贮望乡情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 归燕 ----------
    {
        "id": "cui-dao-rong-32",
        "title": "归燕",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "海燕频来去，西人独滞留。天边又相送，肠断故园秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 长安春 ----------
    {
        "id": "cui-dao-rong-33",
        "title": "长安春",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "珠箔映高柳，美人红袖垂。忽闻半天语，不见上楼时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 銮驾东回 ----------
    {
        "id": "cui-dao-rong-34",
        "title": "銮驾东回",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "两川花捧御衣香，万岁山呼辇路长。",
            "天子还从马嵬过，别无惆怅似明皇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 钓鱼 ----------
    {
        "id": "cui-dao-rong-35",
        "title": "钓鱼",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "闲钓江鱼不钓名，瓦瓯斟酒暮山青。",
            "醉头倒向芦花里，却笑无端犯客星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 西施 ----------
    {
        "id": "cui-dao-rong-36",
        "title": "西施",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "苎萝山下如花女，占得姑苏台上春。",
            "一笑不能忘敌国，五湖何处有功臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 马嵬 ----------
    {
        "id": "cui-dao-rong-37",
        "title": "马嵬",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "万乘凄凉蜀路归，眼前朱翠与心违。",
            "重华不是风流主，湘水犹传泣二妃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 羯鼓 ----------
    {
        "id": "cui-dao-rong-38",
        "title": "羯鼓",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "华清宫里打撩声，供奉丝簧束手听。",
            "寂寞銮舆斜谷里，是谁翻得雨淋铃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 寄李左司 ----------
    {
        "id": "cui-dao-rong-39",
        "title": "寄李左司",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "柏台兰省共清风，鸣玉朝联夜被同。",
            "肯信人间有兄弟，一生长在别离中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 梅 ----------
    {
        "id": "cui-dao-rong-40",
        "title": "梅",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "溪上寒梅初满枝，夜来霜月透芳菲。",
            "清光寂寞思无尽，应待琴尊与解围。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 天台陈逸人 ----------
    {
        "id": "cui-dao-rong-41",
        "title": "天台陈逸人",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "绝粒空山秋复春，欲看沧海化成尘。",
            "近抛三井更深去，不怕虎狼唯怕人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 雪窦禅师 ----------
    {
        "id": "cui-dao-rong-42",
        "title": "雪窦禅师",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "雪窦峰前一派悬，雪窦五月无炎天。",
            "客尘半日洗欲尽，师到白头林下禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 溪上遇雨二首 ----------
    {
        "id": "cui-dao-rong-43",
        "title": "溪上遇雨二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "回塘雨脚如缫丝，野禽不起沈鱼飞。",
            "耕蓑钓笠取未暇，秋田有望从淋漓。",
            "坐看黑云衔猛雨，喷洒前山此独晴。",
            "忽惊云雨在头上，却是山前晚照明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 长门怨 ----------
    {
        "id": "cui-dao-rong-44",
        "title": "长门怨",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "长门花泣一枝春，争奈君恩别处新。",
            "错把黄金买词赋，相如自是薄情人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 秋夕 ----------
    {
        "id": "cui-dao-rong-45",
        "title": "秋夕",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "自怜三十未西游，傍水寻山过却秋。",
            "一夜雨声多少事，不思量尽到心头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 过隆中 ----------
    {
        "id": "cui-dao-rong-46",
        "title": "过隆中",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "玄德苍黄起卧龙，鼎分天下一言中。",
            "可怜蜀国关张后，不见商量徐庶功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 关下 ----------
    {
        "id": "cui-dao-rong-47",
        "title": "关下",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "百二山河壮帝畿，关门何事更开迟。",
            "应从漏却田文后，每度闻鸡不免疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 寒食客中有怀 ----------
    {
        "id": "cui-dao-rong-48",
        "title": "寒食客中有怀",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "江上闻莺禁火时，百花开尽柳依依。",
            "故园兄弟别来久，应到清明犹望归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 溪夜 ----------
    {
        "id": "cui-dao-rong-49",
        "title": "溪夜",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "积雪消来溪水宽，满楼明月碎琅玕。",
            "渔人抛得钓筒尽，却放轻舟下急滩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 山居卧疾，广利大师见访 ----------
    {
        "id": "cui-dao-rong-50",
        "title": "山居卧疾，广利大师见访",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "桐谷孙枝已上弦，野人犹卧白云边。",
            "九天飞锡应相诮，三到行朝二十年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 村墅 ----------
    {
        "id": "cui-dao-rong-51",
        "title": "村墅",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "正月二月村墅闲，馀粮未乏人心宽。",
            "南邻雨中揭屋笑，酒熟数家来相看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 悲李拾遗二首 ----------
    {
        "id": "cui-dao-rong-52",
        "title": "悲李拾遗二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "故友从来匪石心，谏多难得主恩深。",
            "行朝半夜烟尘起，晓殿吁嗟一镜沈。",
            "天涯时有北来尘，因话它人及故人。",
            "也是先皇能罪己，殿前频得触龙鳞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 题《李将军传》 ----------
    {
        "id": "cui-dao-rong-53",
        "title": "题《李将军传》",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "猿臂将军去似飞，弯弓百步虏无遗。",
            "汉文自与封侯得，何必伤嗟不遇时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 酒醒 ----------
    {
        "id": "cui-dao-rong-54",
        "title": "酒醒",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "酒醒拨剔残灰火，多少凄凉在此中。",
            "炉畔自斟还自醉，打窗深夜雪兼风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 郊居友人相访 ----------
    {
        "id": "cui-dao-rong-55",
        "title": "郊居友人相访",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "柴门深掩古城秋，背郭缘溪一径幽。",
            "不有小园新竹色，君来那肯暂淹留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 镜湖雪霁贻方干 ----------
    {
        "id": "cui-dao-rong-56",
        "title": "镜湖雪霁贻方干",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "天外晓岚和雪望，月中归棹带冰行。",
            "相逢半醉吟诗苦，应抵寒猿袅树声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 秋霁 ----------
    {
        "id": "cui-dao-rong-57",
        "title": "秋霁",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "雨霁长空荡涤清，远山初出未知名。",
            "夜来江上如钩月，时有惊鱼掷浪声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 谢朱常侍寄贶蜀茶、剡纸二首 ----------
    {
        "id": "cui-dao-rong-58",
        "title": "谢朱常侍寄贶蜀茶、剡纸二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "瑟瑟香尘瑟瑟泉，惊风骤雨起炉烟。",
            "一瓯解却山中醉，便觉身轻欲上天。",
            "百幅轻明雪未融，薛家凡纸漫深红。",
            "不应点染闲言语，留记将军盖世功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 读杜紫微集 ----------
    {
        "id": "cui-dao-rong-59",
        "title": "读杜紫微集",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "紫微才调复知兵，长觉风雷笔下生。",
            "还有枉抛心力处，多于五柳赋闲情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 寓题 ----------
    {
        "id": "cui-dao-rong-60",
        "title": "寓题",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "海上乘查便合仙，若无仙骨未如船。",
            "人间亦有支机石，虚被声名到洞天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 寓吟集 ----------
    {
        "id": "cui-dao-rong-61",
        "title": "寓吟集",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "陶集篇篇皆有酒，崔诗句句不无杯。",
            "醉来已共身安约，让却诗人作酒魁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 溪居即事 ----------
    {
        "id": "cui-dao-rong-62",
        "title": "溪居即事",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "篱外谁家不系船，春风吹入钓鱼湾。",
            "小童疑是有村客，急向柴门去却关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 鸡 ----------
    {
        "id": "cui-dao-rong-63",
        "title": "鸡",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "买得晨鸡共鸡语，常时不用等闲鸣。",
            "深山月黑风雨夜，欲近晓天啼一声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 献浙东柳大夫 ----------
    {
        "id": "cui-dao-rong-64",
        "title": "献浙东柳大夫",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "属城甘雨几经春，圣主全分付越人。",
            "俗眼不知青琐贵，江头争看碧油新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 杨柳枝词 ----------
    {
        "id": "cui-dao-rong-65",
        "title": "杨柳枝词",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "雾撚烟搓一索春，年年长似染来新。",
            "应须唤作风流线，系得东西南北人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 楚怀王 ----------
    {
        "id": "cui-dao-rong-66",
        "title": "楚怀王",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "宫花一朵掌中开，缓急翻为敌国媒。",
            "六里江山天下笑，张仪容易去还来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 对早梅寄友人二首 ----------
    {
        "id": "cui-dao-rong-67",
        "title": "对早梅寄友人二首",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "忆得前年君寄诗，海边三见早梅词。",
            "与君犹是海边客，又见早梅花发时。",
            "忆得去年有遗恨，花前未醉到无花。",
            "清芳一夜月通白，先脱寒衣送酒家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 句 ----------
    {
        "id": "cui-dao-rong-68",
        "title": "句",
        "author": "崔道融",
        "poet_id": "cui-dao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "万里一点白，长空鸟不飞。（《边庭雪》，见《诗格》）",
            "如今却羡相如富，犹有人间四壁居。（见杨万里《诗话》）",
            "第七百一十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]