# -*- coding: utf-8 -*-
"""
刘昭禹卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 15 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 括苍山 ----------
    {
        "id": "liu-zhao-yu-1",
        "title": "括苍山",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "尽日行方半，诸山直下看。白云随步起，危径极天盘。",
            "瀑顶桥形小，溪边店影寒。往来空太息，玄鬓改非难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 忆天台山 ----------
    {
        "id": "liu-zhao-yu-2",
        "title": "忆天台山",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "常记游灵境，道人情不低。岩房容偃息，天路许相携。",
            "霞散曙峰外，虹生凉瀑西。何当尘役了，重去听猿啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 冬日暮国清寺留题 ----------
    {
        "id": "liu-zhao-yu-3",
        "title": "冬日暮国清寺留题",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "天台山下寺，冬暮景如屏。树密风长在，年深像有灵。",
            "高钟疑到月，远烧欲连星。因共真僧话，心中万虑宁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 灵溪观 ----------
    {
        "id": "liu-zhao-yu-4",
        "title": "灵溪观",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "鳌海西边地，宵吟景象宽。云开孤月上，瀑喷一山寒。",
            "人异发常绿，草灵秋不干。无由此栖息，魂梦在长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 怀华山隐者 ----------
    {
        "id": "liu-zhao-yu-5",
        "title": "怀华山隐者",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "先生入太华，杳杳绝良音。秋梦有时见，孤云无处寻。",
            "神清峰顶立，衣冷瀑边吟。应笑干名者，六街尘土深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 赠惠律大师 ----------
    {
        "id": "liu-zhao-yu-6",
        "title": "赠惠律大师",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "秋是忆山日，禅窗露洒馀。几悬华顶梦，应寄沃洲书。",
            "风月资吟笔，杉篁笼静居。满城谁不重，见著紫衣初。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 经费冠卿旧隐 ----------
    {
        "id": "liu-zhao-yu-7",
        "title": "经费冠卿旧隐",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "节高终不起，死恋九华山。圣主情何切，孤云性本闲。",
            "名传中国外，坟在乱松间。依约曾栖处，斜阳鸟自还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 闻蝉 ----------
    {
        "id": "liu-zhao-yu-8",
        "title": "闻蝉",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "一雨一番晴，山林冷落青。莫侵残日噪，正在异乡听。",
            "孤馆宿漳浦，扁舟离洞庭。年年当此际，那免鬓凋零。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送休公归衡 ----------
    {
        "id": "liu-zhao-yu-9",
        "title": "送休公归衡",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "草履初登南岳船，铜瓶犹贮北山泉。",
            "衡阳旧寺春归晚，门锁寒潭几树蝉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 句 ----------
    {
        "id": "liu-zhao-yu-10",
        "title": "句",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "句向夜深得，心从天外归。（见《纪事》）",
            "危楼聊侧耳，高柳又鸣蝉。（《秋日登楼》，",
            "见《吟窗杂录》）",
            "藓色围波井，花阴上竹楼。（以下见《海录碎事》）",
            "对面雷瞋树，当街雨趁人。（《夏雨》）",
            "春光怀玉阙，万里起初程。（《送人》）",
            "江上呼风去，天边挂席飞。（《送人舟行》）",
            "漆灯寻黑洞，之字上危峰。（《送人游九疑》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 仙都山留题 ----------
    {
        "id": "liu-zhao-yu-11",
        "title": "仙都山留题",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "林下事无非，尘中竟不知。白云深拥我，青石合眠谁。",
            "山静捣灵药，夜闲论古诗。此来亲羽客，何日变枯髭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 晚霁望岳麓 ----------
    {
        "id": "liu-zhao-yu-12",
        "title": "晚霁望岳麓",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "湘西斜日边，峭入几寻天。翠落重城内，屏开万户前。",
            "崖崚危溅瀑，林罅静通仙。谁肯功成后，相携扫石眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 石笋 ----------
    {
        "id": "liu-zhao-yu-13",
        "title": "石笋",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "千古海门石，移归吟叟居。窍腥蛟出后，形瘦浪冲馀。",
            "工语宁无玉，僧知忽有书。好期仙者叱，变化向庭隅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 伤雨后牡丹 ----------
    {
        "id": "liu-zhao-yu-14",
        "title": "伤雨后牡丹",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "废功看不已，醉起又持杯。数日帘常卷，中宵雨忽来。",
            "凄凉无戏蝶，零落在苍苔。造化根难问，令人首可回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送人红花栽 ----------
    {
        "id": "liu-zhao-yu-15",
        "title": "送人红花栽",
        "author": "刘昭禹",
        "poet_id": "liu-zhao-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "世上红蕉异，因移万里根。艰难离瘴土，潇洒入朱门。",
            "叶战青云韵，花零宿露痕。长安多未识，谁想动吟魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]