# -*- coding: utf-8 -*-
"""
张柬之卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 6 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·大堤曲 ----------
    {
        "id": "zhang-jian-zhi-1",
        "title": "相和歌辞·大堤曲",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "南国多佳人，莫若大堤女。玉床翠羽帐，宝袜莲花炬。",
            "魂处自目成，色授开心许。迢迢不可见，日暮空愁予。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 杂曲歌辞·东飞伯劳歌 ----------
    {
        "id": "zhang-jian-zhi-2",
        "title": "杂曲歌辞·东飞伯劳歌",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "青田白鹤丹山凤，婺女姮娥两相送。谁家绝世绮帐前，",
            "艳粉芳脂映宝钿。窈窕玉堂褰翠幕，参差绣户悬珠箔。",
            "绝世三五爱红妆，冶袖长裾兰麝香。春去花枝俄易改，",
            "可叹年光不相待。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 大堤曲 ----------
    {
        "id": "zhang-jian-zhi-3",
        "title": "大堤曲",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "南国多佳人，莫若大堤女。玉床翠羽帐，宝袜莲花距。",
            "魂处自目成，色授开心许。迢迢不可见，日暮空愁予。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 东飞伯劳歌 ----------
    {
        "id": "zhang-jian-zhi-4",
        "title": "东飞伯劳歌",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "青田白鹤丹山凤，婺女姮娥两相送。谁家绝世绮帐前，",
            "艳粉红脂映宝钿。窈窕玉堂褰翠幕，参差绣户悬珠箔。",
            "绝世三五爱红妆，冶袖长裙兰麝香。春去花枝俄易改，",
            "可叹年光不相待。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 出塞 ----------
    {
        "id": "zhang-jian-zhi-5",
        "title": "出塞",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "侠客重恩光，骢马饰金装。瞥闻传羽檄，驰突救边荒。",
            "歙野山川动，嚣天旌旆扬。吴钩明似月，楚剑利如霜。",
            "电断冲胡塞，风飞出洛阳。转战磨笄俗，横行戴斗乡。",
            "手擒郅支长，面缚谷蠡王。将军占太白，小妇怨流黄。",
            "騕褭青丝骑，娉婷红粉妆。三春莺度曲，八月雁成行。",
            "谁堪坐愁思，罗袖拂空床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 与国贤良夜歌二首 ----------
    {
        "id": "zhang-jian-zhi-6",
        "title": "与国贤良夜歌二首",
        "author": "张柬之",
        "poet_id": "zhang-jian-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "柳台临新堰，楼堞相重复。窈窕凤凰姝，倾城复倾国。",
            "杏间花照灼，楼上月裴回。带娇移玉柱，含笑捧金杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]