# -*- coding: utf-8 -*-
"""
唐彦谦卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 167 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 逢韩喜 ----------
    {
        "id": "tang-yan-qian-1",
        "title": "逢韩喜",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "相逢浑不觉，只似茂陵贫。袅袅花骄客，潇潇雨净春。",
            "借书消茗困，索句写梅真。此去青云上，知君有几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 夜坐示友 ----------
    {
        "id": "tang-yan-qian-2",
        "title": "夜坐示友",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "夜久烛花落，凄声生远林。有怀嫌会浅，无事又秋深。",
            "黄叶归田梦，白头行路吟。山中亦可乐，不似此同襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 梅亭 ----------
    {
        "id": "tang-yan-qian-3",
        "title": "梅亭",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "东海穷诗客，西风古驿亭。发从残岁白，山入故乡青。",
            "世事徒三窟，儿曹且一经。丁宁速赊酒，煮栗试砂瓶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 岁除 ----------
    {
        "id": "tang-yan-qian-4",
        "title": "岁除",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "索索风搜客，沈沈雨洗年。残林生猎迹，归鸟避窑烟。",
            "节物杯浆外，溪山鬓影前。行藏都未定，笔砚或能捐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 咏月 ----------
    {
        "id": "tang-yan-qian-5",
        "title": "咏月",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "阴盛此宵中，多为雨与风。坐无风雨至，看与雪霜同。",
            "抱湿离遥海，倾寒向远空。年年不相值，还似道难通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 闻应德茂先离棠溪 ----------
    {
        "id": "tang-yan-qian-6",
        "title": "闻应德茂先离棠溪",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "落日芦花雨，行人谷树村。青山时问路，红叶自知门。",
            "苜蓿穷诗味，芭蕉醉墨痕。端知弃城市，经席许频温。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 松 ----------
    {
        "id": "tang-yan-qian-7",
        "title": "松",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "托根蟠泰华，倚干蚀莓苔。谁云山泽间，而无梁栋材。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 梅 ----------
    {
        "id": "tang-yan-qian-8",
        "title": "梅",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "玉人下瑶台，香风动轻素。画角弄江城，鸣珰月中堕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 兰二首 ----------
    {
        "id": "tang-yan-qian-9",
        "title": "兰二首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "清风摇翠环，凉露滴苍玉。美人胡不纫，幽香蔼空谷。",
            "谢庭漫芳草，楚畹多绿莎。于焉忽相见，岁晏将如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 葡萄 ----------
    {
        "id": "tang-yan-qian-10",
        "title": "葡萄",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "金谷风露凉，绿珠醉初醒。珠帐夜不收，月明堕清影。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 春草 ----------
    {
        "id": "tang-yan-qian-11",
        "title": "春草",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "随梦入池塘，无心在金谷。青风自年年，吹遍天涯绿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 渔 ----------
    {
        "id": "tang-yan-qian-12",
        "title": "渔",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "相聚即为邻，烟火自成簇。约伴过前溪，撑破蘼芜绿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 留别四首 ----------
    {
        "id": "tang-yan-qian-13",
        "title": "留别四首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "鹏程三万里，别酒一千钟。好景当三月，春光上国浓。",
            "野花红滴滴，江燕语喃喃。鼓吹翻新调，都亭酒正酣。",
            "登庸趋俊乂，厕用野无遗。起喜赓歌日，明良际会时。",
            "盐车淹素志，长坂入青云。老骥春风里，奔腾独异群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 秋葵 ----------
    {
        "id": "tang-yan-qian-14",
        "title": "秋葵",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "月瓣团栾剪赭罗，长条排蕊缀鸣珂。",
            "倾阳一点丹心在，承得中天雨露多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 春草 ----------
    {
        "id": "tang-yan-qian-15",
        "title": "春草",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "天北天南绕路边，托根无处不延绵。",
            "萋萋总是无情物，吹绿东风又一年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 春日偶成 ----------
    {
        "id": "tang-yan-qian-16",
        "title": "春日偶成",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "dG筝箫管和琵琶，兴满金尊酒量赊。",
            "歌舞留春春似海，美人颜色正如花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 秋日感怀 ----------
    {
        "id": "tang-yan-qian-17",
        "title": "秋日感怀",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "溪上芙蓉映醉颜，悲秋宋玉鬓毛斑。",
            "无情最恨东流水，暗逐芳年去不还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 七夕 ----------
    {
        "id": "tang-yan-qian-18",
        "title": "七夕",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "会合无由叹久违，一年一度是缘非。",
            "而予愿乞天孙巧，五色纫针补衮衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 怀友 ----------
    {
        "id": "tang-yan-qian-19",
        "title": "怀友",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "金井凉生梧叶秋，闲看新月上帘钩。",
            "冰壶总忆人如玉，目断重云十二楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 翡翠 ----------
    {
        "id": "tang-yan-qian-20",
        "title": "翡翠",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "莎草江汀漫晚潮，翠华香扑水光遥。",
            "玉楼春暖笙歌夜，妆点花钿上舞翘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 咏马二首 ----------
    {
        "id": "tang-yan-qian-21",
        "title": "咏马二首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "紫云团影电飞瞳，骏骨龙媒自不同。",
            "骑过玉楼金辔响，一声嘶断落花风。",
            "崚嶒高耸骨如山，远放春郊苜蓿间。",
            "百战沙场汗流血，梦魂犹在玉门关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 留别 ----------
    {
        "id": "tang-yan-qian-22",
        "title": "留别",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "丹湖湖上送行舟，白雁啼残芦叶秋。",
            "采石江头旧时路，题诗还忆水边楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 咏竹 ----------
    {
        "id": "tang-yan-qian-23",
        "title": "咏竹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "醉卧凉阴沁骨清，石床冰簟梦难成。",
            "月明午夜生虚籁，误听风声是雨声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 忆孟浩然 ----------
    {
        "id": "tang-yan-qian-24",
        "title": "忆孟浩然",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "郊外凌兢西复东，雪晴驴背兴无穷。",
            "句搜明月梨花内，趣入春风柳絮中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 寄友三首 ----------
    {
        "id": "tang-yan-qian-25",
        "title": "寄友三首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "新酒秦淮缩项鳊，凌霄花下共流连。",
            "别来客邸空翘首，细雨春风忆往年。",
            "寒灯孤对拥青毡，牢落何如似客边。",
            "却忆花前酣后饮，醉呼明月上遥天。",
            "客里逢春一惘然，梅花落尽柳如烟。",
            "无情最恨东来雁，底事音书不肯传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 无题十首 ----------
    {
        "id": "tang-yan-qian-26",
        "title": "无题十首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "细草铺茵绿满堤，燕飞晴日正迟迟。",
            "寻芳陌上花如锦，折得东风第一枝。",
            "锦筝银甲响鹍弦，勾引春声上绮筵。",
            "醉倚阑干花下月，犀梳斜亸鬓云边。",
            "楚云湘雨会阳台，锦帐芙蓉向夜开。",
            "吹罢玉箫春似海，一双彩凤忽飞来。",
            "春江新水促归航，惜别花前酒漫觞。",
            "倒尽银瓶浑不醉，却怜和泪入愁肠。",
            "谁知别易会应难，目断青鸾信渺漫。",
            "情似蓝桥桥下水，年来流恨几时干。",
            "漏滴铜龙夜已深，柳梢斜月弄疏阴。",
            "满园芳草年年恨，剔尽灯花夜夜心。",
            "夜合庭前花正开，轻罗小扇为谁裁。",
            "多情惊起双蝴蝶，飞入巫山梦里来。",
            "忆别悠悠岁月长，酒兵无计敌愁肠。",
            "柔丝漫折长亭柳，绾得同心欲寄将。",
            "杨柳青青映画楼，翠眉终日锁离愁。",
            "杜鹃啼落枝头月，多为伤春恨不休。",
            "云色鲛绡拭泪颜，一帘春雨杏花寒。",
            "几时重会鸳鸯侣，月下吹笙和彩鸾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 寄同上人 ----------
    {
        "id": "tang-yan-qian-27",
        "title": "寄同上人",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "高高山顶寺，更有最高人。定起松鸣屋，吟圆月上身。",
            "云藏三伏热，水散百溪津。曾乞兰花供，无书又过春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 夜坐 ----------
    {
        "id": "tang-yan-qian-28",
        "title": "夜坐",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "愁鬓丁年白，寒灯丙夜青。不眠惊戍鼓，久客厌邮铃。",
            "汹汹城喷海，疏疏屋漏星。十年穷父子，相守慰飘零。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 吊方干处士二首 ----------
    {
        "id": "tang-yan-qian-29",
        "title": "吊方干处士二首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "不谓高名下，终全玉雪身。交犹及前辈，语不似今人。",
            "别号行鸣雁，遗编感获麟。敛衣应自定，只著古衣巾。",
            "不比他人死，何诗可挽君。渊明元懒仕，东野别攻文。",
            "沧海诸公泪，青山处士坟。相看莫浪哭，私谥有前闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 题证道寺 ----------
    {
        "id": "tang-yan-qian-30",
        "title": "题证道寺",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "弯环青径斜，自是野僧家。满涧洗岩液，插天排石牙。",
            "炉寒馀柏子，架静落藤花。记得逃兵日，门多贵客车。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 宿赵gj别业 ----------
    {
        "id": "tang-yan-qian-31",
        "title": "宿赵gj别业",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "溪山兵后县，风雪旅中人。迫夜愁严鼓，冲寒托软巾。",
            "摧藏名字在，疏率馔殽真。今代徐元直，高风自可亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 原上 ----------
    {
        "id": "tang-yan-qian-32",
        "title": "原上",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "危桥横古渡，村野带平林。野鹜寒塘静，山禽晓树深。",
            "雨微风矗□，云暗雪侵寻。安道门前水，清游岂独吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 寄台省知己 ----------
    {
        "id": "tang-yan-qian-33",
        "title": "寄台省知己",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "久怀声籍甚，千里致双鱼。宦路终推毂，亲帏且著书。",
            "才名贾太傅，文学马相如。辙迹东巡海，何时适我闾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 自咏 ----------
    {
        "id": "tang-yan-qian-34",
        "title": "自咏",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "白发三千丈，青春四十年。两牙摇欲落，双膝痺如挛。",
            "强仕非时彦，无闻惜昔贤。自期终见恶，未忍舍遗编。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 游阳明洞呈王理得诸君 ----------
    {
        "id": "tang-yan-qian-35",
        "title": "游阳明洞呈王理得诸君",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "禹穴苍茫不可探，人传灵笈锁烟岚。初晴鹤点青边嶂，",
            "欲雨龙移黑处潭。北半斋坛天寂寂，东风仙洞草毵毵。",
            "堪怜尹叟非关吏，犹向江南逐老聃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 新丰 ----------
    {
        "id": "tang-yan-qian-36",
        "title": "新丰",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "沛中歌舞百馀人，帝业功成里巷新。半夜素灵先哭楚，",
            "一星遗火下烧秦。貔貅扫尽无三户，鸡犬归来识四邻。",
            "惆怅故园前事远，晓风长路起埃尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 拜越公墓因游定水寺有怀源老 ----------
    {
        "id": "tang-yan-qian-37",
        "title": "拜越公墓因游定水寺有怀源老",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "越公已作飞仙去，犹得潭潭好墓田。老树背风深拓地，",
            "野云依海细分天。青峰晓接鸣钟寺，玉井秋澄试茗泉。",
            "我与源公旧相识，遗言潇洒有人传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 任潜谋隐之作 ----------
    {
        "id": "tang-yan-qian-38",
        "title": "任潜谋隐之作",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "江边秋日逢任子，大理索诗吾欲忘。为问山资何次第，",
            "只馀丹诀转凄凉，黄金范蠡曾辞禄，白首虞翻未信方。",
            "千古浮云共归思，晓风城郭水花香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 晚秋游中溪 ----------
    {
        "id": "tang-yan-qian-39",
        "title": "晚秋游中溪",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "淡竹冈前沙雁飞，小花尖下柘丸肥。山云不卷雨自薄，",
            "天气欲寒人正归。招伴只须新稻酒，临风犹有旧苔矶。",
            "故人旧业依稀在，怪石老松今是非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 寄陈少府兼简叔高 ----------
    {
        "id": "tang-yan-qian-40",
        "title": "寄陈少府兼简叔高",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "怀人路绝云归海，避俗门深草蔽丘。万事渐消闲客梦，",
            "一年虚白少年头。山螀啼缓从除架，淮雁来多莫上楼。",
            "近日邻家有新酿，每逢诗伴得淹留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 过清凉寺王导墓下 ----------
    {
        "id": "tang-yan-qian-41",
        "title": "过清凉寺王导墓下",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "江左风流廊庙人，荒坟抛与梵宫邻。多年羊虎犹眠石，",
            "败壁貂蝉只贮尘。万古云山同白骨，一庭花木自青春。",
            "永思陵下犹凄切，废屋寒风吹野薪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 第三溪 ----------
    {
        "id": "tang-yan-qian-42",
        "title": "第三溪",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "日晏霜浓十二月，林疏石瘦第三溪。云沙有径萦寒烧，",
            "松屋无人闻昼鸡。几聚衣冠埋作土，当年歌舞醉如泥。",
            "早知涉世真成梦，不弃山田春雨犁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 蒲津河亭 ----------
    {
        "id": "tang-yan-qian-43",
        "title": "蒲津河亭",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "宿雨清秋霁景澄，广亭高树向晨兴。烟横博望乘槎水，",
            "日上文王避雨陵。孤棹夷犹期独往，曲阑愁绝每长凭。",
            "思乡怀古多伤别，况此哀吟意不胜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 毗陵道中 ----------
    {
        "id": "tang-yan-qian-44",
        "title": "毗陵道中",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "百年只有百清明，狼狈今年又避兵。烟火谁开寒食禁，",
            "簪裾那复丽人行。禾麻地废生边气，草木春寒起战声。",
            "渺渺飞鸿天断处，古来还是阖闾城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 越城待旦 ----------
    {
        "id": "tang-yan-qian-45",
        "title": "越城待旦",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "策策虚楼竹隔明，悲来展转向谁倾。天寒胡雁出万里，",
            "月落越鸡啼四更。为底朱颜成老色，看人青史上新名。",
            "清溪白石村村有，五尺乌犍托此生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 过浩然先生墓 ----------
    {
        "id": "tang-yan-qian-46",
        "title": "过浩然先生墓",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "人间万卷庞眉老，眼见堂堂入草莱。行客须当下马过，",
            "故交谁复裹鸡来。山花不语如听讲，溪水无情自荐哀。",
            "犹胜黄金买碑碣，百年名字已烟埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 赠孟德茂（浩然子） ----------
    {
        "id": "tang-yan-qian-47",
        "title": "赠孟德茂（浩然子）",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "江海悠悠雪欲飞，抱书空出又空归。沙头人满鸥应笑，",
            "船上酒香鱼正肥。尘土竟成谁计是，山林又悔一年非。",
            "平生万卷应夫子，两世功名穷布衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 秋霁丰德寺与玄贞师咏月 ----------
    {
        "id": "tang-yan-qian-48",
        "title": "秋霁丰德寺与玄贞师咏月",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "露冷风轻霁魄圆，高楼更在碧山巅。四溟水合疑无地，",
            "八月槎通好上天。黯黯星辰环紫极，喧喧朝市匝青烟。",
            "夜深独与岩僧语，群动消声举世眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 长陵 ----------
    {
        "id": "tang-yan-qian-49",
        "title": "长陵",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "长安高阙此安刘，祔葬累累尽列侯。丰上旧居无故里，",
            "沛中原庙对荒丘。耳闻明主提三尺，眼见愚民盗一坏。",
            "千载腐儒骑瘦马，渭城斜月重回头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 留别 ----------
    {
        "id": "tang-yan-qian-50",
        "title": "留别",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "西入潼关路，何时更盍簪。年来人事改，老去鬓毛侵。",
            "花染离筵泪，葵倾报国心。龙潭千尺水，不似别情深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 宿独留 ----------
    {
        "id": "tang-yan-qian-51",
        "title": "宿独留",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "日晚宿留城，人家半掩门。群鸦栖老树，一犬吠荒村。",
            "争买鱼添价，新篘酒带浑。船头对新月，谁与共清论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 客中感怀 ----------
    {
        "id": "tang-yan-qian-52",
        "title": "客中感怀",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "客路三千里，西风两鬓尘。贪名笑吴起，说国叹苏秦。",
            "托兴非耽酒，思家岂为莼。可怜今夜月，独照异乡人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 过三山寺 ----------
    {
        "id": "tang-yan-qian-53",
        "title": "过三山寺",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "三山江上寺，宫殿望岧峣。石径侵高树，沙滩半种苗。",
            "一僧归晚日，群鹭宿寒潮。遥听风铃语，兴亡话六朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 望夫石 ----------
    {
        "id": "tang-yan-qian-54",
        "title": "望夫石",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "江上见危矶，人形立翠微。妾来终日望，夫去几时归。",
            "明月空悬镜，苍苔漫补衣。可怜双泪眼，千古断斜晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 过湖口 ----------
    {
        "id": "tang-yan-qian-55",
        "title": "过湖口",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "江湖分两路，此地是通津。云净山浮翠，风高浪泼银。",
            "人行俱是客，舟住即为邻。俯仰烟波内，蜉蝣寄此身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 夜泊东溪有怀 ----------
    {
        "id": "tang-yan-qian-56",
        "title": "夜泊东溪有怀",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "水昏天色晚，崖下泊行舟。独客伤归雁，孤眠叹野鸥。",
            "溪声牵别恨，乡梦惹离愁。酒醒推篷坐，凄凉望女牛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 登庐山 ----------
    {
        "id": "tang-yan-qian-57",
        "title": "登庐山",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "五老峰巅望，天涯在目前。湘潭浮夜雨，巴蜀暝寒烟。",
            "泰华根同峙，嵩衡脉共联。凭虚有仙骨，日月看推迁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 金陵九日 ----------
    {
        "id": "tang-yan-qian-58",
        "title": "金陵九日",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "野菊西风满路香，雨花台上集壶觞。九重天近瞻钟阜，",
            "五色云中望建章。绿酒莫辞今日醉，黄金难买少年狂。",
            "清歌惊起南飞雁，散作秋声送夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 游清凉寺 ----------
    {
        "id": "tang-yan-qian-59",
        "title": "游清凉寺",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "白云红树路纡萦，古殿长廊次第行。南望水连桃叶渡，",
            "北来山枕石头城。一尘不到心源净，万有俱空眼界清。",
            "竹院逢僧旧曾识，旋披禅衲为相迎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 高平九日 ----------
    {
        "id": "tang-yan-qian-60",
        "title": "高平九日",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "云净南山紫翠浮，凭陵绝顶望悠悠。偶逢佳节牵诗兴，",
            "漫把芳尊遣客愁。霜染鸦枫迎日醉，寒冲泾水带冰流。",
            "乌纱频岸西风里，笑插黄花满鬓秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 金陵怀古 ----------
    {
        "id": "tang-yan-qian-61",
        "title": "金陵怀古",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "碧树凉生宿雨收，荷花荷叶满汀洲。登高有酒浑忘醉，",
            "慨古无言独倚楼。宫殿六朝遗古迹，衣冠千古漫荒丘。",
            "太平时节殊风景，山自青青水自流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 道中逢故人 ----------
    {
        "id": "tang-yan-qian-62",
        "title": "道中逢故人",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "兰陵市上忽相逢，叙别殷勤兴倍浓。良会若同鸡黍约，",
            "暂时不放酒杯空。愁牵白发三千丈，路入青山几万重。",
            "行色一鞭催去马，画桥嘶断落花风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 早行遇雪 ----------
    {
        "id": "tang-yan-qian-63",
        "title": "早行遇雪",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "下马天未明，风高雪何急。须臾路欲迷，顷刻山尽白。",
            "鸡犬寂无声，曙光射寒色。荒村绝烟火，髯冻布袍湿。",
            "王事不可缓，行行动凄恻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 樊登见寄四首 ----------
    {
        "id": "tang-yan-qian-64",
        "title": "樊登见寄四首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "新辞翦秋水，洗我胸中尘。无由惬良会，极目空怀人。",
            "醉来拔剑歌，字字皆阳春。",
            "轻黄著柳条，新春喜更始。感时重搔首，怅望不能已。",
            "无由托深情，倾泻芳尊里。",
            "明月入我室，天风吹我袍。良夜最岑寂，旅况何萧条。",
            "驰情望海波，一鹤鸣九皋。",
            "悠悠括城北，眄眄岩泉西。宿草暝烟绿，苦竹含云低。",
            "幽怀不可托，鹧鸪空自啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 春风四首 ----------
    {
        "id": "tang-yan-qian-65",
        "title": "春风四首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "春风吹愁端，散漫不可收。不如古溪水，只望乡江流。",
            "新花红烁烁，旧花满山白。昔日金张门，狼藉馀废宅。",
            "回头语春风，莫向新花丛。我见朱颜人，多金亦成翁。",
            "多金不足惜，丹砂亦何益。更种明年花，春风自相识。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 感物二首 ----------
    {
        "id": "tang-yan-qian-66",
        "title": "感物二首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "騄骥初失群，亦自矜趫腾。俯仰岁时久，帖然困蚊蝇。",
            "豪鲸逸其穴，尺水成沧溟。岂无鱼鳖交，望望为所憎。",
            "物理有翕张，达人同废兴。幸无怵迫忧，聊复曲吾肱。",
            "鱼目出泥沙，空村百金珍。豫章值拥辏，细细供蒸薪。",
            "论材何必多，适用即能神。托交何必深，寡求永相亲。",
            "鲍叔拙羁鲁，张生穷厄陈。茫然扳援际，岂意出风尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 和陶渊明贫士诗七首 ----------
    {
        "id": "tang-yan-qian-67",
        "title": "和陶渊明贫士诗七首",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "贫贱如故旧，少壮即相依。中心不敢厌，但觉少光辉。",
            "向来乘时士，亦有能奋飞。一朝权势歇，欲退无所归。",
            "不如行其素，辛苦奈寒饥。人生系天运，何用发深悲。",
            "我居在穷巷，来往无华轩。辛勤衣食物，出此二亩园。",
            "薤菘郁朝露，桑柘浮春烟。以兹乱心曲，智计无他奸。",
            "择胜不在奢，兴至发清言。相逢樵牧徒，混混谁愚贤。",
            "松风四山来，清宵响瑶琴。听之不能寐，中有怨叹音。",
            "旦起绕其树，磈砢不计寻。清阴可敷席，有酒谁与斟。",
            "由来大度士，不受流俗侵。浩歌相倡答，慰此霜雪心。",
            "中年涉事熟，欲学唾面娄。逡巡避少年，赴秽不敢酬。",
            "旁人吁已甚，自喜计虑周。微劳消厚疚，残辱胜深忧。",
            "从知为下安，处上反无俦。人生各有志，勇懦从所求。",
            "古人重畎亩，有禄不待干。德成禄自至，释耒列王官。",
            "不仕亦不贫，本自足饔餐。后世耻躬耕，号呼脱饥寒。",
            "我生千祀后，念此愧在颜。为农倘可饱，何用出柴关。",
            "村郊多父老，面垢头如蓬。我尝使之年，言语不待工。",
            "古来名节士，敢望彭城龚。有叟诮其后，更恨道不通。",
            "鄙哉譊譊者，为隘不为通。低头拜野老，负米吾愿从。",
            "去年秋事荒，贩籴仰邻州。健者道路间，什百成朋俦。",
            "今年渐向熟，庶几民不流。书生自无田，与众同喜忧。",
            "作诗劳邻曲，有倡谁与酬。亦无采诗者，此修何可修。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 舟中望紫岩 ----------
    {
        "id": "tang-yan-qian-68",
        "title": "舟中望紫岩",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "近山如画墙，远山如帚长。我从云中来，回头白茫茫。",
            "惜去乃尔觉，常时自相忘。相忘岂不佳，遣此怀春伤。",
            "飘洒从何来，衣巾湿微凉。初疑风雨集，冉冉游尘黄。",
            "无归亦自可，信美非吾乡。登舟望东云，犹向帆端翔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 九日游中溪 ----------
    {
        "id": "tang-yan-qian-69",
        "title": "九日游中溪",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "悠悠循涧行，磊磊据石坐。林垂短长云，山缀丹碧颗。",
            "蓼花最无数，照水娇婀娜。何知是节序，风日自清妥。",
            "群童竞时新，万果间蔬蓏。欣然为之醉，乌帽危不堕。",
            "此日山中怀，孟公不如我。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 六月十三日上陈微博士 ----------
    {
        "id": "tang-yan-qian-70",
        "title": "六月十三日上陈微博士",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "骄云飞散雨，随风为有无。老农终岁心，望施在须臾。",
            "平生官田粟，长此礼义躯。置之且勿戚，一饱任妻孥。",
            "青青泽中蒲，九夏气凄寒。翾翾翠碧羽，照影苍溪间。",
            "巢由薄天下，俗士荣一官。小大各有适，自全良独难。",
            "穷居无公忧，私此长夏日。蚊蝇如俗子，正尔相妒嫉。",
            "麾驱非吾任，遁避亦无术。惟当俟其定，静坐万虑一。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 宿田家 ----------
    {
        "id": "tang-yan-qian-71",
        "title": "宿田家",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "落日下遥峰，荒村倦行履。停车息茅店，安寝正鼾睡。",
            "忽闻扣门急，云是下乡隶。公文捧花柙，鹰隼驾声势。",
            "良民惧官府，听之肝胆碎。阿母出搪塞，老脚走颠踬。",
            "小心事延款，□馀粮复匮。东邻借种鸡，西舍觅芳醑。",
            "再饭不厌饱，一饮直呼醉。明朝怯见官，苦苦灯前跪。",
            "使我不成眠，为渠滴清泪。民膏日已瘠，民力日愈弊。",
            "空怀伊尹心，何补尧舜治。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 夏日访友 ----------
    {
        "id": "tang-yan-qian-72",
        "title": "夏日访友",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "堤树生昼凉，浓阴扑空翠。孤舟唤野渡，村疃入幽邃。",
            "高轩俯清流，一犬隔花吠。童子立门墙，问我向何处。",
            "主人闻故旧，出迎时倒屣。惊迓叙间阔，屈指越寒暑。",
            "殷勤为延款，偶尔得良会。春盘擘紫虾，冰鲤斫银鲙。",
            "荷梗白玉香，荇菜青丝脆。腊酒击泥封，罗列总新味。",
            "移席临湖滨，对此有佳趣。流连送深杯，宾主共忘醉。",
            "清风岸乌纱，长揖谢君去。世事如浮云，东西渺烟水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 游南明山 ----------
    {
        "id": "tang-yan-qian-73",
        "title": "游南明山",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "久闻南明山，共慕南明寺。几度欲登临，日逐扰人事。",
            "于焉偶闲暇，鸣辔忽相聚。乘兴乐遨游，聊此托佳趣。",
            "涉水渡溪南，迢遥翠微里。石磴千叠斜，峭壁半空起。",
            "白云锁峰腰，红叶暗溪嘴。长藤络虚岩，疏花映寒水。",
            "金银拱梵刹，丹青照廊宇。石梁卧秋溟，风铃作檐语。",
            "深洞结苔阴，岚气滴晴雨。羊肠转咫尺，鸟道转千里。",
            "屈曲到禅房，上人喜延伫。香分宿火薰，茶汲清泉煮。",
            "投闲息万机，三生有宿契。行厨出盘飧，担瓮倒芳醑。",
            "脱冠挂长松，白石藉凭倚。宦途劳营营，暂此涤尘虑。",
            "阄令促传觞，投壶更联句。兴来较胜负，醉后忘尔汝。",
            "忽闻吼蒲牢，落日下云屿。长啸出烟萝，扬鞭赋归去。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 索虾 ----------
    {
        "id": "tang-yan-qian-74",
        "title": "索虾",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "姑孰多紫虾，独有湖阳优。出产在四时，极美宜于秋。",
            "双箝鼓繁须，当顶抽长矛。鞠躬见汤王，封作朱衣侯。",
            "所以供盘餐，罗列同珍羞。蒜友日相亲，瓜朋时与俦。",
            "既名钓诗钓，又作钩诗钩。于时同相访，数日承款留。",
            "厌饮多美味，独此心相投。别来岁云久，驰想空悠悠。",
            "衔杯动遐思，uT口涎空流。封缄托双鲤，于焉来远求。",
            "慷慨胡隐君，果肯分惠否。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 采桑女 ----------
    {
        "id": "tang-yan-qian-75",
        "title": "采桑女",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "春风吹蚕细如蚁，桑芽才努青鸦嘴。侵晨探采谁家女，",
            "手挽长条泪如雨。去岁初眠当此时，今岁春寒叶放迟。",
            "愁听门外催里胥，官家二月收新丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 送许户曹 ----------
    {
        "id": "tang-yan-qian-76",
        "title": "送许户曹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "沙头小燕鸣春和，杨柳垂丝烟倒拖。将军楼船发浩歌，",
            "云樯高插天嵯峨。白虹走香倾翠壶，劝饮花前金叵罗。",
            "神鳌驾粟升天河，新承雨泽浮恩波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 咏葡萄 ----------
    {
        "id": "tang-yan-qian-77",
        "title": "咏葡萄",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "西园晚霁浮嫩凉，开尊漫摘葡萄尝。满架高撑紫络索，",
            "一枝斜亸金琅珰。天风飕飕叶栩栩，蝴蝶声干作晴雨。",
            "神蛟清夜蛰寒潭，万片湿云飞不起。石家美人金谷游，",
            "罗帏翠幕珊瑚钩。玉盘新荐入华屋，珠帐高悬夜不收。",
            "胜游记得当年景，清气逼人毛骨冷。笑呼明镜上遥天，",
            "醉倚银床弄秋影。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 蟹 ----------
    {
        "id": "tang-yan-qian-78",
        "title": "蟹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "湖田十月清霜堕，晚稻初香蟹如虎。扳罾拖网取赛多，",
            "篾篓挑将水边货。纵横连爪一尺长，秀凝铁色含湖光。",
            "蟛蜞石蟹已曾食，使我一见惊非常。买之最厌黄髯老，",
            "偿价十钱尚嫌少。漫夸丰味过蝤蛑，尖脐犹胜团脐好。",
            "充盘煮熟堆琳琅，橙膏酱渫调堪尝。一斗擘开红玉满，",
            "双螯uT出琼酥香。岸头沽得泥封酒，细嚼频斟弗停手。",
            "西风张翰苦思鲈，如斯丰味能知否？物之可爱尤可憎，",
            "尝闻取刺于青蝇。无肠公子固称美，弗使当道禁横行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 叙别 ----------
    {
        "id": "tang-yan-qian-79",
        "title": "叙别",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "谯楼夜促莲花漏，树阴摇月蛟螭走。蟠拏对月吸深杯，",
            "月府清虚玉兔吼。翠盘擘脯胭脂香，碧碗敲冰分蔗浆。",
            "十载番思旧时事，好怀不似当年狂。夜合花香开小院，",
            "坐爱凉风吹醉面。酒中弹剑发清歌，白发年来为愁变。",
            "第六百七十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 绯桃 ----------
    {
        "id": "tang-yan-qian-80",
        "title": "绯桃",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "短墙荒圃四无邻，烈火绯桃照地春。坐久好风休掩袂，",
            "夜来微雨已沾巾。敢同俗态期青眼，似有微词动绛唇。",
            "尽日更无乡井念，此时何必见秦人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 小院 ----------
    {
        "id": "tang-yan-qian-81",
        "title": "小院",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "小院无人夜，烟斜月转明。清宵易惆怅，不必有离情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 春雪初霁杏花正芳月上夜吟 ----------
    {
        "id": "tang-yan-qian-82",
        "title": "春雪初霁杏花正芳月上夜吟",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "霁景明如练，繁英杏正芳。姮娥应有语，悔共雪争光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 文惠宫人 ----------
    {
        "id": "tang-yan-qian-83",
        "title": "文惠宫人",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "认得前家令，宫人泪满裾。不知梁佐命，全是沈尚书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 赠窦尊师 ----------
    {
        "id": "tang-yan-qian-84",
        "title": "赠窦尊师",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "我爱窦高士，弃官仍在家。为嫌句漏令，兼不要丹砂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 穆天子传 ----------
    {
        "id": "tang-yan-qian-85",
        "title": "穆天子传",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "王母清歌玉琯悲，瑶台应有再来期。",
            "穆王不得重相见，恐为无端哭盛姬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 楚天 ----------
    {
        "id": "tang-yan-qian-86",
        "title": "楚天",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "楚天遥望每长嚬，宋玉襄王尽作尘。",
            "不会瑶姬朝与暮，更为云雨待何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 寄徐山人 ----------
    {
        "id": "tang-yan-qian-87",
        "title": "寄徐山人",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "一室清羸鹤体孤，气和神莹爽冰壶。",
            "吴中高士虽求死，不那稽山有谢敷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 题宗人故帖 ----------
    {
        "id": "tang-yan-qian-88",
        "title": "题宗人故帖",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "所忠无处访相如，风笈尘编迹尚馀。",
            "惟有孝标情最厚，一编遗在茂陵书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 垂柳 ----------
    {
        "id": "tang-yan-qian-89",
        "title": "垂柳",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "绊惹春风别有情，世间谁敢斗轻盈。",
            "楚王江畔无端种，饿损纤腰学不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 登兴元城观烽火 ----------
    {
        "id": "tang-yan-qian-90",
        "title": "登兴元城观烽火",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "汉川城上角三呼，扈跸防边列万夫。",
            "褒姒冢前烽火起，不知泉下破颜无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 邓艾庙 ----------
    {
        "id": "tang-yan-qian-91",
        "title": "邓艾庙",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "昭烈遗黎死尚羞，挥刀斫石恨谯周。",
            "如何千载留遗庙，血食巴山伴武侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 曲江春望 ----------
    {
        "id": "tang-yan-qian-92",
        "title": "曲江春望",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "杏艳桃光夺晚霞，乐游无庙有年华。",
            "汉朝冠盖皆陵墓，十里宜春汉苑花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 汉殿 ----------
    {
        "id": "tang-yan-qian-93",
        "title": "汉殿",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "鸟去云飞意不通，夜坛斜月转松风。",
            "君王寂虑无消息，却就闲人觅巨公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 贺李昌时禁苑新命 ----------
    {
        "id": "tang-yan-qian-94",
        "title": "贺李昌时禁苑新命",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "振鹭翔鸾集禁闱，玉堂珠树莹风仪。",
            "不知新到灵和殿，张绪何如柳一枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 牡丹 ----------
    {
        "id": "tang-yan-qian-95",
        "title": "牡丹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "颜色无因饶锦绣，馨香惟解掩兰荪。",
            "那堪更被烟蒙蔽，南国西施泣断魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 罗江驿 ----------
    {
        "id": "tang-yan-qian-96",
        "title": "罗江驿",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "数枝高柳带鸣鸦，一树山榴自落花。",
            "已是向来多泪眼，短亭回首在天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 奏捷西蜀题沱江驿 ----------
    {
        "id": "tang-yan-qian-97",
        "title": "奏捷西蜀题沱江驿",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "野客乘轺非所宜，况将儒懦报戎机。",
            "锦江不识临邛酒，且免相如渴病归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 春早落英 ----------
    {
        "id": "tang-yan-qian-98",
        "title": "春早落英",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "纷纷从此见花残，转觉长绳系日难。",
            "楼上有愁春不浅，小桃风雪凭阑干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 仲山（高祖兄仲隐居之所） ----------
    {
        "id": "tang-yan-qian-99",
        "title": "仲山（高祖兄仲隐居之所）",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "千载遗踪寄薜萝，沛中乡里旧山河。",
            "长陵亦是闲丘陇，异日谁知与仲多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 汉嗣 ----------
    {
        "id": "tang-yan-qian-100",
        "title": "汉嗣",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "汉嗣安危系数君，高皇决意势难分。",
            "张良口辨周昌吃，同建储宫第一勋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 四老庙 ----------
    {
        "id": "tang-yan-qian-101",
        "title": "四老庙",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "西汉储宫定不倾，可能园绮胜良平。",
            "举朝公将无全策，借请闲人羽翼成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 南梁戏题汉高庙 ----------
    {
        "id": "tang-yan-qian-102",
        "title": "南梁戏题汉高庙",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "数载从军似武夫，今随戎捷气偏粗。",
            "汉皇若问何为者，免道高阳旧酒徒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 洛神 ----------
    {
        "id": "tang-yan-qian-103",
        "title": "洛神",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "人世仙家本自殊，何须相见向中途。",
            "惊鸿瞥过游龙去，漫恼陈王一事无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 初秋到慈州冬首换绛牧 ----------
    {
        "id": "tang-yan-qian-104",
        "title": "初秋到慈州冬首换绛牧",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "秋杪方攀玉树枝，隔年无计待春晖。",
            "自嫌暂作仙城守，不逐莺来共燕飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 重经冯家旧里 ----------
    {
        "id": "tang-yan-qian-105",
        "title": "重经冯家旧里",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "冯家旧宅闭柴关，修竹犹存潏水湾。",
            "应系星辰天上去，不留英骨葬人间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 克复后登安国寺阁 ----------
    {
        "id": "tang-yan-qian-106",
        "title": "克复后登安国寺阁",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "千门万户鞠蒿藜，断烬遗垣一望迷。",
            "惆怅建章鸳瓦尽，夜来空见玉绳低。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 题虔僧室 ----------
    {
        "id": "tang-yan-qian-107",
        "title": "题虔僧室",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "何缘春恨贮离忧，欲入空门万事休。",
            "水月定中何所谓，也嚬眉黛托腮愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 见炀帝宝帐 ----------
    {
        "id": "tang-yan-qian-108",
        "title": "见炀帝宝帐",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "汉文穷相作前王，悭惜明珠不斗量。",
            "翡翠鲛鮹何所直，千裨万接上书囊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 楼上偶题 ----------
    {
        "id": "tang-yan-qian-109",
        "title": "楼上偶题",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "尘土无因狎隐沦，青山一望每伤神。",
            "可能前岭空乔木，应有怀才抱器人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 亲仁里闻猿 ----------
    {
        "id": "tang-yan-qian-110",
        "title": "亲仁里闻猿",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "朱雀街东半夜惊，楚魂湘梦两徒清。",
            "五更撩乱趋朝火，满口尘埃亦数声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 闻李渎司勋下世 ----------
    {
        "id": "tang-yan-qian-111",
        "title": "闻李渎司勋下世",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "异乡丹旐已飘扬，一顾深知实未亡。",
            "任被褚裒泉下笑，重将北面哭真长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 试夜题省廊桂 ----------
    {
        "id": "tang-yan-qian-112",
        "title": "试夜题省廊桂",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "麻衣穿穴两京尘，十见东堂绿桂春。",
            "今日竞飞杨叶箭，魏舒休作画筹人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 竹风 ----------
    {
        "id": "tang-yan-qian-113",
        "title": "竹风",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "竹映风窗数阵斜，旅人愁坐思无涯。",
            "夜来留得江湖梦，全为乾声似荻花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 长溪秋望 ----------
    {
        "id": "tang-yan-qian-114",
        "title": "长溪秋望",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "柳短莎长溪水流，雨微烟暝立溪头。",
            "寒鸦闪闪前山去，杜曲黄昏独自愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 严子陵 ----------
    {
        "id": "tang-yan-qian-115",
        "title": "严子陵",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "严陵情性是真狂，抵触三公傲帝王。",
            "不怕旧交嗔僭越，唤他侯霸作君房。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 北齐 ----------
    {
        "id": "tang-yan-qian-116",
        "title": "北齐",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "草草招提强据鞍，周师乘胜莫回看。",
            "背城肯战知虚实，争奈人前忍笑难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 楚世家 ----------
    {
        "id": "tang-yan-qian-117",
        "title": "楚世家",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "偏信由来惑是非，一言邪佞脱危机。",
            "张仪重入怀王手，驷马安车却放归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 骊山道中 ----------
    {
        "id": "tang-yan-qian-118",
        "title": "骊山道中",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "月殿真妃下彩烟，渔阳追虏及汤泉。",
            "君王指点新丰树，几不亲留七宝鞭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 韦曲 ----------
    {
        "id": "tang-yan-qian-119",
        "title": "韦曲",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "欲写愁肠愧不才，多情练漉已低摧。",
            "穷郊二月初离别，独傍寒村嗅野梅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 黄子陂荷花 ----------
    {
        "id": "tang-yan-qian-120",
        "title": "黄子陂荷花",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "十顷狂风撼曲尘，缘堤照水露红新。",
            "世间花气皆愁绝，恰是莲香更恼人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 野行 ----------
    {
        "id": "tang-yan-qian-121",
        "title": "野行",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "蝶恋晚花终不去，鸥逢春水固难飞。",
            "野人心地都无著，伴蝶随鸥亦不归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 兴元沈氏庄 ----------
    {
        "id": "tang-yan-qian-122",
        "title": "兴元沈氏庄",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "清浅萦纡一水间，竹冈藤树小跻攀。露沾荒草行人过，",
            "月上高林宿鸟还。江绕武侯筹笔地，雨昏张载勒铭山。",
            "异乡一笑因酣醉，忘却愁来鬓发斑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 乱后经表兄琼华观旧居 ----------
    {
        "id": "tang-yan-qian-123",
        "title": "乱后经表兄琼华观旧居",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "一去仙居似转蓬，再经花谢倚春丛。醉中篇什金声在，",
            "别后音书锦字空。长忆映碑逢若士，未曾携杖逐壶公。",
            "东风狼藉苔侵径，蕙草香销杏带红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 秋霁夜吟寄友人 ----------
    {
        "id": "tang-yan-qian-124",
        "title": "秋霁夜吟寄友人",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "槐柳萧疏溽暑收，金商频伏火西流。尘衣岁晚缘身贱，",
            "雨簟更深满背秋。前事悲凉何足道，远书慵懒未能修。",
            "惟思待月高梧下，更就东床访惠休。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 贺李昌时禁苑新命 ----------
    {
        "id": "tang-yan-qian-125",
        "title": "贺李昌时禁苑新命",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "玉简金文直上清，禁垣丹地闭严扃。黄扉议政参元化，",
            "紫殿称觞拂寿星。万户千门迷步武，非烟非雾隔仪形。",
            "尘中旧侣无音信，知道辽东鹤姓丁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 寄蒋二十四 ----------
    {
        "id": "tang-yan-qian-126",
        "title": "寄蒋二十四",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "鸟啭蜂飞日渐长，旅人情味悔思量。禅门澹薄无心地，",
            "世事生疏欲面墙。二月云烟迷柳色，九衢风土带花香。",
            "大知高士禁愁寂，试倚阑干莫断肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 寄怀 ----------
    {
        "id": "tang-yan-qian-127",
        "title": "寄怀",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "有客伤春复怨离，夕阳亭畔草青时。泪从红蜡无由制，",
            "肠比朱弦恐更危。梅向好风惟是笑，柳因微雨不胜垂。",
            "双溪未去饶归梦，夜夜孤眠枕独欹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 送樊琯司业归朝 ----------
    {
        "id": "tang-yan-qian-128",
        "title": "送樊琯司业归朝",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "近者苏司业，文雄道最光。夫君居太学，妙誉继中行。",
            "汲郡陵初发，汾阴箧久亡。寂寥方倚席，容易忽升堂。",
            "去日应悬榻，来时定裂裳。惬心频拾芥，应手屡穿杨。",
            "辩急如无敌，飞腾固自强。论心期舌在，问事畏头长。",
            "驷马终题柱，诸生悉面墙。啖螯讥尔雅，卖饼诉公羊。",
            "未见泥函谷，俄惊火建章。烟尘昏象魏，行在隔巴梁。",
            "红粟填郿坞，青袍过寿阳。翦茅行殿湿，伐柏旧陵香。",
            "黉室青衿尽，渠门火旆扬。云飞同去国，星散各殊方。",
            "贱子悲穷辙，当年亦擅场。齑辛寻幼妇，醴酒忆先王。",
            "圣域探姬孔，皇风乐禹汤。畏诛轻李喜，言命小臧仓。",
            "折树休盘槊，沈钩且钓璜。鸿都问词客，他日莫相忘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 奉使岐下闻唐弘夫行军为贼所擒，伤而有作 ----------
    {
        "id": "tang-yan-qian-129",
        "title": "奉使岐下闻唐弘夫行军为贼所擒，伤而有作",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "报国捐躯实壮夫，楚囚垂欲复神都。云台画像皆何者，",
            "青史书名或不孤。散卒半随袁校尉，寡妻休问辟司徒。",
            "闻君败绩无归计，气激星辰坐向隅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 咸通中始闻褚河南归葬阳翟是岁上平徐方…成二十韵 ----------
    {
        "id": "tang-yan-qian-130",
        "title": "咸通中始闻褚河南归葬阳翟是岁上平徐方…成二十韵",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "册府藏馀烈，皇纲正本朝。不听还笏谏，几覆缀旒祧。",
            "咫尺言终直，怆惶道已消。泪心传位日，挥涕授遗朝。",
            "飞燕潜来赵，黄龙岂见谯。既迷秦帝鹿，难问贾生雕。",
            "穆卜缄縢秘，金根辙迹遥。北军那夺印，东海漫难桥。",
            "罗织黄门讼，笙簧白骨销。炎方无信息，丹旐竟沦漂。",
            "邂逅江鱼食，凄凉楚客招。文忠徒谥议，子卯但箫韶。",
            "未见公侯复，寻伤嗣续凋。流年随水逝，高谊薄层霄。",
            "柱石林公远，缣缃故国饶。奇踪天骥活，遗轴锦鸾翘。",
            "近者淮夷戮，前年归马调。始闻移北葬，兼议荫山苗。",
            "圣泽覃将溥，贞魂喜定飘。异时穷巷客，怀古漫成谣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 岐王宅 ----------
    {
        "id": "tang-yan-qian-131",
        "title": "岐王宅",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "朱邸平台隔禁闱，贵游陈迹尚依稀。云低雍畤祈年去，",
            "雨细长杨纵猎归。申白宾朋传道义，应刘文彩寄音徽。",
            "承平旧物惟君尽，犹写雕鞍伴六飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 东韦曲野思 ----------
    {
        "id": "tang-yan-qian-132",
        "title": "东韦曲野思",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "淡雾轻云匝四垂，绿塘秋望独颦眉。野莲随水无人见，",
            "寒鹭窥鱼共影知。九陌要津劳目击，五湖闲梦诱心期。",
            "孤灯夜夜愁欹枕，一觉沧洲似昔时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 上巳（一作上巳日寄韩公） ----------
    {
        "id": "tang-yan-qian-133",
        "title": "上巳（一作上巳日寄韩公）",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "上巳接寒食，莺花寥落晨。微微泼火雨，草草踏青人。",
            "凉似三秋景，清无九陌尘。与余同病者，对此合伤神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 移莎 ----------
    {
        "id": "tang-yan-qian-134",
        "title": "移莎",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "移从杜城曲，置在小斋东。正是高秋里，仍兼细雨中。",
            "结根方迸竹，疏荫托高桐。苒苒齐芳草，飘飘笑断蓬。",
            "片时留静者，一夜响鸣蛩。野露通宵滴，溪烟尽日蒙。",
            "试才卑庾薤，求味笑周菘。只此霜栽好，他时赠伯翁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 西明寺威公盆池新稻 ----------
    {
        "id": "tang-yan-qian-135",
        "title": "西明寺威公盆池新稻",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "为笑江南种稻时，露蝉鸣后雨霏霏。莲盆积润分畦小，",
            "藻井垂阴擢秀稀。得地又生金象界，结根仍对水田衣。",
            "支公尚有三吴思，更使幽人忆钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 红叶 ----------
    {
        "id": "tang-yan-qian-136",
        "title": "红叶",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "无处不飘扬，高楼临道旁。素娥前夕月，青女夜来霜。",
            "宿雨随时润，秋晴著物光。幽怀长若此，病眼更相妨。",
            "蜀纸裁深色，燕脂落靓妆。低丛侵小阁，倒影入回塘。",
            "谢脁留霞绮，甘宁弃锦张。何人休远道，是处有斜阳。",
            "薜荔垂书幌，梧桐坠井床。晚风生旅馆，寒籁近僧房。",
            "桂绿明淮甸，枫丹照楚乡。雁疏临鄠杜，蝉急傍潇湘。",
            "树异桓宣武，园非顾辟疆。茂陵愁卧客，不自保危肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 鸂鶒 ----------
    {
        "id": "tang-yan-qian-137",
        "title": "鸂鶒",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "一宿南塘烟雨时，好风摇动绿波微。惊离晓岸冲花去，",
            "暖下春汀照影飞。华屋撚弦弹鼓舞，绮窗含笔澹毛衣。",
            "画屏见后长回首，争得雕笼莫放归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 萤 ----------
    {
        "id": "tang-yan-qian-138",
        "title": "萤",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "日下芜城莽苍中，湿萤撩乱起衰丛。寒烟陈后长门闭，",
            "夜雨隋家旧苑空。星散欲陵前槛月，影低如试北窗风。",
            "羁人此夕方愁绪，心似寒灰首似蓬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 夜蝉 ----------
    {
        "id": "tang-yan-qian-139",
        "title": "夜蝉",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "翠竹高梧夹后溪，劲风危露雨凄凄。那知北牖残灯暗，",
            "又送西楼片月低。清夜更长应未已，远烟寻断莫频嘶。",
            "羁人此夕如三岁，不整寒衾待曙鸡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 140. 七夕 ----------
    {
        "id": "tang-yan-qian-140",
        "title": "七夕",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "露白风清夜向晨，小星垂佩月埋轮。绛河浪浅休相隔，",
            "沧海波深尚作尘。天外凤凰何寂寞，世间乌鹊漫辛勤。",
            "倚阑殿北斜楼上，多少通宵不寐人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 141. 中秋夜玩月 ----------
    {
        "id": "tang-yan-qian-141",
        "title": "中秋夜玩月",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "一夜高楼万景奇，碧天无际水无涯。只留皎月当层汉，",
            "并送浮云出四维。雾静不容玄豹隐，冰生惟恐夏虫疑。",
            "坐来离思忧将晓，争得嫦娥仔细知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 142. 八月十六日夜月 ----------
    {
        "id": "tang-yan-qian-142",
        "title": "八月十六日夜月",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "断肠佳赏固难期，昨夜销魂更不疑。丹桂影空蟾有露，",
            "绿槐阴在鹊无枝。赖将吟咏聊惆怅，早是疏顽耐别离。",
            "堪恨贾生曾恸哭，不缘清景为忧时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 143. 送韦向之睦州谒使君 ----------
    {
        "id": "tang-yan-qian-143",
        "title": "送韦向之睦州谒使君",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "才子南游多远情，闲舟荡漾任春行。",
            "新安江上长如此，何似新安太守清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 144. 春残 ----------
    {
        "id": "tang-yan-qian-144",
        "title": "春残",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "景为春时短，愁随别夜长。暂棋宁号隐，轻醉不成乡。",
            "风雨曾通夕，莓苔有众芳。落花如便去，楼上即河梁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 145. 玫瑰 ----------
    {
        "id": "tang-yan-qian-145",
        "title": "玫瑰",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "麝炷腾清燎，鲛纱覆绿蒙。宫妆临晓日，锦段落东风。",
            "无力春烟里，多愁暮雨中。不知何事意，深浅两般红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 146. 牡丹 ----------
    {
        "id": "tang-yan-qian-146",
        "title": "牡丹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "真宰多情巧思新，固将能事送残春。为云为雨徒虚语，",
            "倾国倾城不在人。开日绮霞应失色，落时青帝合伤神。",
            "嫦娥婺女曾相送，留下鸦黄作蕊尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 147. 秋晚高楼 ----------
    {
        "id": "tang-yan-qian-147",
        "title": "秋晚高楼",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "松拂疏窗竹映阑，素琴幽怨不成弹。清宵霁极云离岫，",
            "紫禁风高露满盘。晚蝶飘零惊宿雨，暮鸦凌乱报秋寒。",
            "高楼瞪目归鸿远，如信嵇康欲画难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 148. 离鸾 ----------
    {
        "id": "tang-yan-qian-148",
        "title": "离鸾",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "闻道离鸾思故乡，也知情愿嫁王昌。尘埃一别杨朱路，",
            "风月三年宋玉墙。下疾不成双点泪，断多难到九回肠。",
            "庭前佳树名栀子，试结同心寄谢娘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 149. 柳 ----------
    {
        "id": "tang-yan-qian-149",
        "title": "柳",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "春思春愁一万枝，远村遥岸寄相思。西园有雨和苔长，",
            "南内无人拂槛垂。游客寂寥缄远恨，暮莺啼叫惜芳时。",
            "晚来飞絮如霜鬓，恐为多情管别离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 150. 春阴 ----------
    {
        "id": "tang-yan-qian-150",
        "title": "春阴",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "一寸回肠百虑侵，旅愁危涕两争禁。天涯已有销魂别，",
            "楼上宁无拥鼻吟。感事不关河里笛，伤心应倍雍门琴。",
            "春云更觉愁于我，闲盖低村作暝阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 151. 春深独行马上有作 ----------
    {
        "id": "tang-yan-qian-151",
        "title": "春深独行马上有作",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "日烈风高野草香，百花狼藉柳披猖。连天瑞霭千门远，",
            "夹道新阴九陌长。众饮不欢逃席酒，独行无味放游缰。",
            "年来与问闲游者，若个伤春向路旁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 152. 春雨 ----------
    {
        "id": "tang-yan-qian-152",
        "title": "春雨",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "绮陌夜来雨，春楼寒望迷。远容迎燕戏，乱响隔莺啼。",
            "有恨开兰室，无言对李蹊。花欹浑拂槛，柳重欲垂堤。",
            "灯檠昏鱼目，薰炉咽麝脐。别轻天北鹤，梦怯汝南鸡。",
            "入户侵罗幌，捎檐润绣题。新丰树已失，长信草初齐。",
            "乱蝶寒犹舞，惊乌暝不栖。庾郎盘马地，却怕有春泥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 153. 汉代 ----------
    {
        "id": "tang-yan-qian-153",
        "title": "汉代",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "汉代金为屋，吴宫绮作寮。艳词传静婉，新曲定妖娆。",
            "箭响犹残梦，签声报早朝。鲜明临晓日，回转度春宵。",
            "半袖笼清镜，前丝压翠翘。静多如有待，闲极似无憀。",
            "梓泽花犹满，灵和柳未凋。障昏巫峡雨，屏掩浙江潮。",
            "未信潘名岳，应疑史姓萧。漏因歌暂断，灯为雨频挑。",
            "饮酒阑三雅，投壶赛百娇。钿蝉新翅重，金鸭旧香焦。",
            "水净疑澄练，霞孤欲建标。别随秦柱促，愁为蜀弦么。",
            "玄晏难瘳痹，临邛但发痟。联诗徵弱絮，思友咏甘蕉。",
            "王氏怜诸谢，周郎定小乔。黼帏翘彩雉，波扇画文鳐。",
            "荇密妨垂钓，荷欹欲度桥。不因衣带水，谁觉路迢迢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 154. 牡丹 ----------
    {
        "id": "tang-yan-qian-154",
        "title": "牡丹",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "青帝于君事分偏，秾堆浮艳倚朱门。",
            "虽然占得笙歌地，将甚酬他雨露恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 155. 湘妃庙 ----------
    {
        "id": "tang-yan-qian-155",
        "title": "湘妃庙",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "刘表荒碑断水滨，庙前幽草闭残春。已将愁泪留斑竹，",
            "又感悲风入白蘋。八族未来谁北拱，四凶犹在莫南巡。",
            "九峰相似堪疑处，望见苍梧不见人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 156. 句 ----------
    {
        "id": "tang-yan-qian-156",
        "title": "句",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "独来成怅望，不去泥栏干。（惜花。见《诗人玉屑》）",
            "第六百七十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 157. 木兰 ----------
    {
        "id": "tang-yan-qian-157",
        "title": "木兰",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "众花摇落正无憀，脉脉芳丛契后凋。舒卷绿苞临小槛，",
            "剪裁檀的缀长条。独当春尽情何限，尚有秋期别未遥。",
            "桃叶近来消息绝，见君长忆渡江桡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 158. 玉蕊 ----------
    {
        "id": "tang-yan-qian-158",
        "title": "玉蕊",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "玉蕊两高树，相辉松桂旁。向来尘不杂，此夜月仍光。",
            "秀掩丛兰色，艳吞秾李芳。世人嫌具美，何必更清香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 159. 莲 ----------
    {
        "id": "tang-yan-qian-159",
        "title": "莲",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "新莲映多浦，迢递绿塘东。静影摇波日，寒香映水风。",
            "金尘飘落蕊，玉露洗残红。看著馀芳少，无人问的中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 160. 望岳时贼据华夏 ----------
    {
        "id": "tang-yan-qian-160",
        "title": "望岳时贼据华夏",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "长路风埃隔楚氛，忽惊神岳映朝曛。削成绝壁五千仞，",
            "高揖泥金七十君。祝史秘辞今莫睹，从臣嘉颂久无闻。",
            "幽人闲望封中地，好为吾皇起白云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 161. 片石 ----------
    {
        "id": "tang-yan-qian-161",
        "title": "片石",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "小斋庐阜石，寄自沃洲僧。山客劳携笈，幽人自得朋。",
            "瘦云低作段，野浪冻成云。便可同清话，何须有物凭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 162. 柳 ----------
    {
        "id": "tang-yan-qian-162",
        "title": "柳",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "春风向杨柳，能事尽风流。有意疑张绪，无情见莫愁。",
            "依然金谷在，宁免武昌偷。前路难回首，何须苦映楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 163. 垂柳 ----------
    {
        "id": "tang-yan-qian-163",
        "title": "垂柳",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "垂柳碧髯茸，楼昏带雨容。思量成昼梦，来去发春慵。",
            "梳洗凭张敞，乘骑笑稚恭。碧虚从转笠，红烛近高舂。",
            "怨脸明秋水，愁眉淡远峰。小园花尽蝶，静院酒醒蛩。",
            "旧作琴台凤，今为药店龙。宝奁抛掷久，一任景阳钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 164. 紫薇花 ----------
    {
        "id": "tang-yan-qian-164",
        "title": "紫薇花",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "素秋寒露重，芳事固应稀。小槛临清昭，高丛见紫薇。",
            "温r3终有思，暗淡岂无辉。见欲迷交甫，谁能状宓妃。",
            "妆新犹倚镜，步缓不胜衣。恍似新相得，伥如久未归。",
            "又疑神女过，犹佩七香帏。还似星娥织，初临五彩机。",
            "庆云今已集，威凤莫惊飞。绮笔题难尽，烦君白玉徽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 165. 望中条 ----------
    {
        "id": "tang-yan-qian-165",
        "title": "望中条",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "虞乡县西郭，改观揖中条。第蓄终南小，交□□□遥。",
            "崦深应有寺，峰近恐通桥。为语前村叟，他时寄采樵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 166. 蒙穀山 ----------
    {
        "id": "tang-yan-qian-166",
        "title": "蒙穀山",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "蒙穀山低碧海枯，仲君闲坐说麻姑。遥天鹤语知虚实，",
            "长夜神光竟有无。秘祝斋心开九转，侍臣回首听三呼。",
            "交朋漫信文成术，短烛瑶坛漏满壶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 167. 菊 ----------
    {
        "id": "tang-yan-qian-167",
        "title": "菊",
        "author": "唐彦谦",
        "poet_id": "tang-yan-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "雪菊金英两断肠，蝶翎蜂鼻带清香。寒村宿雾临幽径，",
            "废苑斜晖傍短墙。近取松筠为伴侣，远将桃李作参商。",
            "年来病肺疏杯酒，每忆龙山似故乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]