# -*- coding: utf-8 -*-
"""
张鷟卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 21 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 咏燕 ----------
    {
        "id": "zhang-zhuo-1",
        "title": "咏燕",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "变石身犹重，衔泥力尚微。从来赴甲第，两起一双飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 答或人 ----------
    {
        "id": "zhang-zhuo-2",
        "title": "答或人",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "宁可且将朱唇饮酒，谁能逐你黑齿常之。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 游仙窟诗·赠崔十娘（张文成） ----------
    {
        "id": "zhang-zhuo-3",
        "title": "游仙窟诗·赠崔十娘（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "今朝忽见渠姿首，不觉殷勤著心口。令人频作许叮咛，",
            "渠家太剧难求守。端坐剩心惊，愁来益不平。",
            "看时未必相看死，难时那许太难生。沉吟处幽室，",
            "相思转成疾。自恨往还疏，谁肯交游密。夜夜空知心失眼，",
            "朝朝无便投胶漆。园里花开不避人，闺中面子翻羞出。",
            "如今寸步阻天津，伊处留心更觅新。莫言长有千金面，",
            "终归变作一抄尘。生前有日但为乐，死后无春更著人。",
            "只可徜徉一生意，何须负持百年身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 又赠十娘 ----------
    {
        "id": "zhang-zhuo-4",
        "title": "又赠十娘",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "薰香四面全，光色两边披。锦障划然卷，罗帷垂半欹。",
            "红颜杂绿黛。无处不相宜。艳色浮妆粉，含香乱口脂。",
            "鬓欺蝉鬓非成鬓，眉笑蛾眉不是眉。见许实娉婷，",
            "何处不轻盈。可怜娇里面，可爱语中声。婀娜腰支细细许，",
            "fyfW眼子长长馨。巧儿旧来携未得，",
            "画匠迎生模不成。相看未相识，倾城复倾国。",
            "迎风帔子郁金香，照日裙裾石榴色。口上珊瑚耐拾取，",
            "颊里芙蓉堪摘得。闻名腹肚已猖狂，见面精神更迷惑。",
            "心肝恰欲摧，踊跃不能裁。徐行步步香风散，",
            "欲语时时梅子开。靥疑织女留星去，眉似姮娥送月来。",
            "含娇窈窕迎前出，忍笑嫈嫇返却回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 咏崔五嫂 ----------
    {
        "id": "zhang-zhuo-5",
        "title": "咏崔五嫂",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "奇异妍雅，貌特惊新。眉间月出疑争夜，颊上花开似斗春。",
            "细腰偏爱转，笑脸特宜嚬。真成物外奇稀物，",
            "实是人间断绝人。自然能举止，可念无方比。",
            "能令公子百重生，巧使王孙千回死。黑云裁两鬓，",
            "白雪分双齿。织成锦绣骐驎儿，判绣裙腰鹦鹉子。",
            "触处尽开怀，何曾有不佳。机关大雅妙，行步绝fi娃。",
            "傍人一一丹罗袜，侍婢三三绿线鞋。黄龙透入黄金钏，",
            "白燕飞来白玉钗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 咏双树 ----------
    {
        "id": "zhang-zhuo-6",
        "title": "咏双树",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "新华发两树，分香遍一林。迎风转细影，向日动轻阴。",
            "戏蜂时隐见，飞蝶远追寻。承闻欲采摘，若个动君心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 同前答文成（崔十娘） ----------
    {
        "id": "zhang-zhuo-7",
        "title": "同前答文成（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "暂游双树下，遥见两枝芳。向日俱翻影，迎风并散香。",
            "戏蝶扶丹萼，游蜂入紫房。人今总摘取，各著一边箱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 咏花（张文成） ----------
    {
        "id": "zhang-zhuo-8",
        "title": "咏花（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "风吹遍树紫，日照满地丹。若为交暂折，擎就掌中看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 同前（崔十娘） ----------
    {
        "id": "zhang-zhuo-9",
        "title": "同前（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "映水俱知笑，成蹊竟不言。即今无自在，高下任渠攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 游后园（张文成） ----------
    {
        "id": "zhang-zhuo-10",
        "title": "游后园（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "昔时过小苑，今朝戏后园。两岁梅花匝，三春柳色繁。",
            "水明鱼影静，林翠鸟歌喧。何须杏树岭，即是桃花源。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 同前（崔十娘） ----------
    {
        "id": "zhang-zhuo-11",
        "title": "同前（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "梅蹊命道士，桃涧伫神仙。旧鱼成大剑，新龟类小钱。",
            "水湄唯见柳，池曲且生莲。欲知赏心处，桃花落眼前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 同前（崔五嫂） ----------
    {
        "id": "zhang-zhuo-12",
        "title": "同前（崔五嫂）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "极目游芳苑，相将对花林。露净山光出，池鲜树影沉。",
            "落花时泛酒，歌鸟或鸣琴。是时日将夕，携樽就树阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 代蜂子答十娘（张文成） ----------
    {
        "id": "zhang-zhuo-13",
        "title": "代蜂子答十娘（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "触处寻芳树，都虑少物华。试从香处觅，正值可怜花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 别文成（崔十娘） ----------
    {
        "id": "zhang-zhuo-14",
        "title": "别文成（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "别时终是别，春心不值春。羞见孤鸾影，悲看一骑尘。",
            "翠柳开眉色，红桃乱脸新。此时君不在，娇莺弄杀人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 同前（崔五嫂） ----------
    {
        "id": "zhang-zhuo-15",
        "title": "同前（崔五嫂）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "此时经一去，谁知隔几年。双凫伤别绪，独鹤惨离弦。",
            "怨起移酲后，愁生落醉前。若使人心密，莫惜马蹄穿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 别十娘（张文成） ----------
    {
        "id": "zhang-zhuo-16",
        "title": "别十娘（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "忽然闻道别，愁来不自禁。眼下千行泪，肠悬一寸心。",
            "两剑俄分匣，双凫忽异林。殷勤惜玉体，勿使外人侵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 扬州青铜镜留与十娘 ----------
    {
        "id": "zhang-zhuo-17",
        "title": "扬州青铜镜留与十娘",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "仙人好负局，隐士屡潜观。映水菱花散，临风竹影寒。",
            "月下时惊鹊，池边独舞鸾。若道人心变，从渠照胆看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 手中扇赠文成（崔十娘） ----------
    {
        "id": "zhang-zhuo-18",
        "title": "手中扇赠文成（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "合欢游璧水，同心侍华阙。飒飒似朝风，团团如夜月。",
            "鸾姿侵雾起，鹤影排空发。希君掌中握，勿使恩情歇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送张郎（香儿） ----------
    {
        "id": "zhang-zhuo-19",
        "title": "送张郎（香儿）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "丈夫存行迹，殷勤为数来。莫作浮萍草，逐浪不知回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 赠十娘（张文成） ----------
    {
        "id": "zhang-zhuo-20",
        "title": "赠十娘（张文成）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "人去悠悠隔两天，未审迢迢度几年。",
            "纵使身游万里外，终归意在十娘边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 答文成（崔十娘） ----------
    {
        "id": "zhang-zhuo-21",
        "title": "答文成（崔十娘）",
        "author": "张鷟",
        "poet_id": "zhang-zhuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "天涯地角知何处，玉体红颜难再遇。",
            "但令翅羽为人生，会些高飞共君去。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]