# -*- coding: utf-8 -*-
"""
张乔卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 168 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 宴边将 ----------
    {
        "id": "zhang-qiao-1",
        "title": "宴边将",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "一曲梁州金石清，边风萧飒动江城。",
            "座中有老沙场客，横笛休吹塞上声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 郢州即事 ----------
    {
        "id": "zhang-qiao-2",
        "title": "郢州即事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "孤城临远水，千里见寒山。白雪无人唱，沧洲尽日闲。",
            "鸟归残烧外，帆出断云间。此地秋风起，应随计吏还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送宾贡金夷吾奉使归本国 ----------
    {
        "id": "zhang-qiao-3",
        "title": "送宾贡金夷吾奉使归本国",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "渡海登仙籍，还家备汉仪。孤舟无岸泊，万里有星随。",
            "积水浮魂梦，流年半别离。东风未回日，音信杳难期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 华山 ----------
    {
        "id": "zhang-qiao-4",
        "title": "华山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "谁将倚天剑，削出倚天峰。众水背流急，他山相向重。",
            "树黏青霭合，崖夹白云浓。一夜盆倾雨，前湫起毒龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 滕王阁 ----------
    {
        "id": "zhang-qiao-5",
        "title": "滕王阁",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "昔人登览处，遗阁大江隅。叠浪有时有，闲云无日无。",
            "早凉先燕去，返照后帆孤。未得营归计，菱歌满旧湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 寄处士梁烛 ----------
    {
        "id": "zhang-qiao-6",
        "title": "寄处士梁烛",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "贤哉君子风，讽与古人同。采药楚云里，移家湘水东。",
            "星霜秋野阔，雨雹夜山空。早晚相招隐，深耕老此中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送许棠下第游蜀 ----------
    {
        "id": "zhang-qiao-7",
        "title": "送许棠下第游蜀",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "天下猿多处，西南是蜀关。马登青壁瘦，人宿翠微闲。",
            "带雨逢残日，因江见断山。行歌风月好，莫老锦城间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 题终南山白鹤观 ----------
    {
        "id": "zhang-qiao-8",
        "title": "题终南山白鹤观",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "上彻炼丹峰，求玄意未穷。古坛青草合，往事白云空。",
            "仙境日月外，帝乡烟雾中。人间足烦暑，欲去恋松风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 赠边将 ----------
    {
        "id": "zhang-qiao-9",
        "title": "赠边将",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "将军夸胆气，功在杀人多。对酒擎钟饮，临风拔剑歌。",
            "翻师平碎叶，掠地取交河。应笑孔门客，年年羡四科。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 吊建州李员外 ----------
    {
        "id": "zhang-qiao-10",
        "title": "吊建州李员外",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "铭旌归故里，猿鸟亦凄然。已葬桐江月，空回建水船。",
            "客传为郡日，僧说读书年。恐有吟魂在，深山古木边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送许棠及第归宣州 ----------
    {
        "id": "zhang-qiao-11",
        "title": "送许棠及第归宣州",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "雅调一生吟，谁为晚达心。傍人贺及第，独自却沾襟。",
            "宴别喧天乐，家归碍日岑。青门许攀送，故里接云林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送庞百篇之任青阳县尉 ----------
    {
        "id": "zhang-qiao-12",
        "title": "送庞百篇之任青阳县尉",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "都堂公试日，词翰独超群。品秩台庭与，篇章圣主闻。",
            "乡连三楚树，县封九华云。多少青门客，临岐共羡君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 曲江春 ----------
    {
        "id": "zhang-qiao-13",
        "title": "曲江春",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "寻春与送春，多绕曲江滨。一片凫鹥水，千秋辇毂尘。",
            "岸凉随众木，波影逐游人。自是游人老，年年管吹新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 秦原春望 ----------
    {
        "id": "zhang-qiao-14",
        "title": "秦原春望",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "无穷名利尘，轩盖逐年新。北阙东堂路，千山万水人。",
            "云离僧榻曙，燕远凤楼春。荏苒文明代，难归钓艇身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 游华山云际寺（一作游少华山甘露寺） ----------
    {
        "id": "zhang-qiao-15",
        "title": "游华山云际寺（一作游少华山甘露寺）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "少华中峰寺，高秋众景归。地连秦塞起，河隔晋山微。",
            "晚木蝉相应，凉天雁并飞。殷勤记岩石，只恐再来稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送棋待诏朴球归新罗 ----------
    {
        "id": "zhang-qiao-16",
        "title": "送棋待诏朴球归新罗",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "海东谁敌手，归去道应孤。阙下传新势，船中覆旧图。",
            "穷荒回日月，积水载寰区。故国多年别，桑田复在无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送郑谷先辈赴妆州辟命 ----------
    {
        "id": "zhang-qiao-17",
        "title": "送郑谷先辈赴妆州辟命",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "看花兴未休，已散曲江游。载笔离秦甸，从军过洛州。",
            "嵩云将雨去，汝水背城流。应念依门客，蒿莱满径秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 赠敬亭清越上人 ----------
    {
        "id": "zhang-qiao-18",
        "title": "赠敬亭清越上人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "海上独随缘，归来二十年。久闲时得句，渐老不离禅。",
            "砌木欹临水，窗峰直倚天。犹期向云里，别扫石床眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 题灵山寺 ----------
    {
        "id": "zhang-qiao-19",
        "title": "题灵山寺",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "树凉清岛寺，虚阁敞禅扉。四面闲云入，中流独鸟归。",
            "湖平幽径近，船泊夜灯微。一宿秋风里，烟波隔捣衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 吊栖白上人 ----------
    {
        "id": "zhang-qiao-20",
        "title": "吊栖白上人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "今古递相送，几时无逝波。篇章名不朽，寂灭理如何。",
            "内殿留真影，闲房落贝多。从兹高塔寺，惆怅懒经过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 北山书事 ----------
    {
        "id": "zhang-qiao-21",
        "title": "北山书事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "黄河一曲山，天半锁重关。圣日雄藩静，秋风老将闲。",
            "车舆穿谷口，市井响云间。大野无飞鸟，元戎校猎还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 长安书事 ----------
    {
        "id": "zhang-qiao-22",
        "title": "长安书事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "出送乡人尽，沧洲未得还。秋风五陵树，晴日六街山。",
            "有景终年住，无机是处闲。何当向云外，免老别离间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送郑侍御赴汴州辟命 ----------
    {
        "id": "zhang-qiao-23",
        "title": "送郑侍御赴汴州辟命",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "官从谏署清，暂去佐戎旌。朝客多相恋，吟僧欲伴行。",
            "河冰天际白，岳雪眼前明。即见东风起，梁园听早莺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 吊造微上人 ----------
    {
        "id": "zhang-qiao-24",
        "title": "吊造微上人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "至人随化往，遗路自堪伤。白塔收真骨，青山闭影堂。",
            "钟残含细韵，烟灭有馀香。松上斋乌在，迟迟立夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 经隐岩旧居（一作怀旧游） ----------
    {
        "id": "zhang-qiao-25",
        "title": "经隐岩旧居（一作怀旧游）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "夜久村落静，徘徊杨柳津。青山犹有路，明月已无人。",
            "梦寐空前事，星霜倦此身。尝期结茅处，来往蹑遗尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 再题敬亭清越上人山房 ----------
    {
        "id": "zhang-qiao-26",
        "title": "再题敬亭清越上人山房",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "重来访惠休，已是十年游。向水千松老，空山一磬秋。",
            "石窗清吹入，河汉夜光流。久别多新作，长吟洗俗愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 浮汴东归 ----------
    {
        "id": "zhang-qiao-27",
        "title": "浮汴东归",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "日暖泗滨西，无穷岸草齐。薄烟衰草树，微月迥城鸡。",
            "水近沧浪急，山随绿野低。羞将旧名姓，还向旧游题。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 雨中宿僧院 ----------
    {
        "id": "zhang-qiao-28",
        "title": "雨中宿僧院",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "千灯有宿因，长老许相亲。夜永楼台雨，更深江海人。",
            "劳生无了日，妄念起微尘。不是真如理，何门静此身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 江行至沙浦 ----------
    {
        "id": "zhang-qiao-29",
        "title": "江行至沙浦",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "烟霞接杳冥，旅泊寄回汀。夜雨雷电歇，春江蛟蜃腥。",
            "城侵潮影白，峤截鸟行青。遍欲探泉石，南须过洞庭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 送友人归江南 ----------
    {
        "id": "zhang-qiao-30",
        "title": "送友人归江南",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "辛勤同失意，迢递独还家。落日江边笛，残春岛上花。",
            "亲安诚可喜，道在亦何嗟。谁伴高吟处，晴天望九华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 刘补阙自九华山拜官因以寄献 ----------
    {
        "id": "zhang-qiao-31",
        "title": "刘补阙自九华山拜官因以寄献",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "冥鸿久不群，征拜动天文。地主迎过郡，山僧送出云。",
            "登车残月在，宿馆乱流分。若更思林下，还须共致君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 岳阳即事 ----------
    {
        "id": "zhang-qiao-32",
        "title": "岳阳即事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "远色岳阳楼，湘帆数片愁。竹风山上路，沙月水中洲。",
            "力学桑田废，思归鬓发秋。功名如不立，岂易狎汀鸥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 题兴善寺僧道深院 ----------
    {
        "id": "zhang-qiao-33",
        "title": "题兴善寺僧道深院",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "江峰峰顶人，受法老西秦。法本无前业，禅非为后身。",
            "院栽他国树，堂展祖师真。甚愿依宗旨，求闲未有因。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 送龙门令刘沧 ----------
    {
        "id": "zhang-qiao-34",
        "title": "送龙门令刘沧",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "去宰龙门县，应思变化年。还将鲁儒政，又与晋人传。",
            "峭壁开中古，长河落半天。几乡因劝勉，耕稼满云烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 送友人往宜春（一作江南） ----------
    {
        "id": "zhang-qiao-35",
        "title": "送友人往宜春（一作江南）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "落花兼柳絮，无处不纷纷。远道空归去，流莺独自闻。",
            "野桥喧磑水，山郭入楼云。故里南陵曲，秋期更送君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 书边事 ----------
    {
        "id": "zhang-qiao-36",
        "title": "书边事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "调角断清秋，征人倚戍楼。春风对青冢，白日落梁州。",
            "大汉无兵阻，穷边有客游。蕃情似此水，长愿向南流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 送僧雅觉归东海 ----------
    {
        "id": "zhang-qiao-37",
        "title": "送僧雅觉归东海",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "山川心地内，一念即千重。老别关中寺，禅归海外峰。",
            "鸟行来有路，帆影去无踪。几夜波涛息，先闻本国钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 和薛监察题兴善寺古松（薛一作崔） ----------
    {
        "id": "zhang-qiao-38",
        "title": "和薛监察题兴善寺古松（薛一作崔）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "种在法王城，前朝古寺名。瘦根盘地远，香吹入云清。",
            "鹤动池台影，僧禅雨雪声。看来人旋老，因此叹浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 听琴 ----------
    {
        "id": "zhang-qiao-39",
        "title": "听琴",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "清月转瑶轸，弄中湘水寒。能令坐来客，不语自相看。",
            "静恐鬼神出，急疑风雨残。几时归岭峤，更过洞庭弹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 送友人游蜀 ----------
    {
        "id": "zhang-qiao-40",
        "title": "送友人游蜀",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "此心知者稀，欲别倍相依。无食拟同去，有家还未归。",
            "巴山开国远，剑道入天微。必恐临邛客，疑君学赋非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 闻仰山禅师往曹溪因赠 ----------
    {
        "id": "zhang-qiao-41",
        "title": "闻仰山禅师往曹溪因赠",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "曹溪松下路，猿鸟重相亲。四海求玄理，千峰绕定身。",
            "异花天上堕，灵草雪中春。自惜经行处，焚香礼旧真。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 蓝溪夜坐 ----------
    {
        "id": "zhang-qiao-42",
        "title": "蓝溪夜坐",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "蓝水警尘梦，夜吟开草堂。月临山霭薄，松滴露花香。",
            "诗外真风远，人间静兴长。明朝访禅侣，更上翠微房。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 题郑侍御蓝田别业 ----------
    {
        "id": "zhang-qiao-43",
        "title": "题郑侍御蓝田别业",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "秋山清若水，吟客静于僧。小径通商岭，高窗见杜陵。",
            "云霞朝入镜，猿鸟夜窥灯。许作前峰侣，终来寄上层。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送友人进士许棠 ----------
    {
        "id": "zhang-qiao-44",
        "title": "送友人进士许棠",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "离乡积岁年，归路远依然。夜火山头市，春江树杪船。",
            "干戈愁鬓改，瘴疠喜家全。何处营甘旨，潮涛浸薄田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 秘省伴直 ----------
    {
        "id": "zhang-qiao-45",
        "title": "秘省伴直",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "乔枝聚暝禽，叠阁锁遥岑。待月当秋直，看书废夜吟。",
            "残薪留火细，古井下瓶深。纵欲抄前史，贫难遂此心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 宿昭应 ----------
    {
        "id": "zhang-qiao-46",
        "title": "宿昭应",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "夜忆开元寺，凄凉里巷间。薄烟通魏阙，明月照骊山。",
            "半壁空宫闭，连天白道闲。清晨更回首，独向灞陵还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 送陆处士 ----------
    {
        "id": "zhang-qiao-47",
        "title": "送陆处士",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "樽前放浩歌，便起泛烟波。舟楫故人少，江湖明月多。",
            "孤峰经宿上，僻寺共云过。若向仙岩住，还应著薜萝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 送韩处士归少室山 ----------
    {
        "id": "zhang-qiao-48",
        "title": "送韩处士归少室山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "江外历千岑，还归少室吟。地闲缑岭月，窗迥洛城砧。",
            "石窦垂寒乳，松枝长别琴。他年瀑泉下，亦拟置家林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 赠初上人 ----------
    {
        "id": "zhang-qiao-49",
        "title": "赠初上人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "竹色覆禅栖，幽禽绕院啼。空门无去住，行客自东西。",
            "井气春来歇，庭枝雪后低。相看念山水，尽日话曹溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 送新罗僧 ----------
    {
        "id": "zhang-qiao-50",
        "title": "送新罗僧",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "东来此学禅，多病念佛缘。把锡离岩寺，收经上海船。",
            "落帆敲石火，宿岛汲瓶泉。永向扶桑老，知无再少年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 题山僧院 ----------
    {
        "id": "zhang-qiao-51",
        "title": "题山僧院",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "谿路曾来日，年多与旧同。地寒松影里，僧老磬声中。",
            "远水清风落，闲云别院通。心源若无碍，何必更论空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 书梅福殿壁二首 ----------
    {
        "id": "zhang-qiao-52",
        "title": "书梅福殿壁二首",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "梅真从羽化，万古是须臾。此地名空在，西山云亦孤。",
            "井痕平野水，坛级上春芜。纵有双飞鹤，年多松已枯。",
            "一自白云去，千秋坛月明。我来思往事，谁更得长生。",
            "雅韵磬钟远，真风楼殿清。今来为尉者，天下有仙名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 荆楚道中 ----------
    {
        "id": "zhang-qiao-53",
        "title": "荆楚道中",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "前程曾未到，岐路拟何为。返照行人急，荒郊去鸟迟。",
            "春宵多旅梦，夏闰远秋期。处处牵愁绪，无穷是柳丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 送南陵尉李频 ----------
    {
        "id": "zhang-qiao-54",
        "title": "送南陵尉李频",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "重作东南尉，生涯尚似僧。客程淮馆月，乡思海船灯。",
            "晚雾看春毂，晴天见朗陵。不应三考足，先授诏书征。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 将归江淮书（一作冬归有感） ----------
    {
        "id": "zhang-qiao-55",
        "title": "将归江淮书（一作冬归有感）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "东风摇众木，即有看花期。紫陌频来日，沧洲独去时。",
            "郡因兵役苦，家为海翻移。未老多如此，那堪鬓不衰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 沿汉东归 ----------
    {
        "id": "zhang-qiao-56",
        "title": "沿汉东归",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "北去穷秦塞，南归绕汉川。深山逢古迹，远道见新年。",
            "绝壁云衔寺，空江雪洒船。萦回还此景，多坐夜灯前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 送蜀客 ----------
    {
        "id": "zhang-qiao-57",
        "title": "送蜀客",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "剑阁缘空去，西南转几州。丹霄行客语，明月杜鹃愁。",
            "露带山花落，云随野水流。相如曾醉地，莫滞少年游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 塞上（一作塞下曲） ----------
    {
        "id": "zhang-qiao-58",
        "title": "塞上（一作塞下曲）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "勒兵辽水边，风急卷旌旃。绝塞寒无树，平沙势尽天。",
            "雪晴回探骑，月落控鸣弦。永定山河誓，南归改汉年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 送友人归袁州 ----------
    {
        "id": "zhang-qiao-59",
        "title": "送友人归袁州",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "袁江猿鸟清，曾向此中行。才子登科去，诸侯扫榻迎。",
            "山藏明月浦，树绕白云城。远想安亲后，秋风梦不惊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 赠别李山人 ----------
    {
        "id": "zhang-qiao-60",
        "title": "赠别李山人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "分合老西秦，年年梦白蘋。曾为洞庭客，还送洞庭人。",
            "语别惜残夜，思归愁见春。遥知泊舟处，沙月自相亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 思宜春寄友人 ----------
    {
        "id": "zhang-qiao-61",
        "title": "思宜春寄友人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "胜游虽隔年，魂梦亦依然。瀑水喧秋思，孤灯动夜船。",
            "断虹全岭雨，斜月半溪烟。旧日吟诗侣，何人更不眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 江行夜雨 ----------
    {
        "id": "zhang-qiao-62",
        "title": "江行夜雨",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "江风木落天，游子感流年。万里波连蜀，三更雨到船。",
            "梦残灯影外，愁积苇丛边。不及樵渔客，全家住岛田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 赠仰大师 ----------
    {
        "id": "zhang-qiao-63",
        "title": "赠仰大师",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "仰山因久住，天下仰山名。井邑身虽到，林泉性本清。",
            "野云居处尽，江月定中明。仿佛曾相识，今来隔几生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 江南逢洛下友人 ----------
    {
        "id": "zhang-qiao-64",
        "title": "江南逢洛下友人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "洛下吟诗侣，南游只有君。波涛归路见，蟋蟀在船闻。",
            "晓月江城出，晴霞岛树分。无穷怀古意，岂独绕湘云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 东湖赠僧子兰（一作题兰上人） ----------
    {
        "id": "zhang-qiao-65",
        "title": "东湖赠僧子兰（一作题兰上人）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "名利了无时，何人暂访师。道情闲外见，心地语来知。",
            "竹落穿窗叶，松寒荫井枝。匡山许同社，愿卜挂帆期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 隐岩陪郑少师夜坐 ----------
    {
        "id": "zhang-qiao-66",
        "title": "隐岩陪郑少师夜坐",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "幸喜陪驺驭，频来向此宵。砚磨清涧石，厨爨白云樵。",
            "竹外村烟细，灯中禁漏遥。衣冠与文理，静语对前朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 送三传赴长城尉（一作送前辈读三传任长城尉） ----------
    {
        "id": "zhang-qiao-67",
        "title": "送三传赴长城尉（一作送前辈读三传任长城尉）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "登科精鲁史，为尉及良时。高论穷诸国，长才并几司。",
            "地倾流水疾，山叠过云迟。暇日琴书畔，何人对手棋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 送李道士归南岳 ----------
    {
        "id": "zhang-qiao-68",
        "title": "送李道士归南岳",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "千峰隔湘水，迢递挂帆归。扫月眠苍壁，和云著褐衣。",
            "洞虚悬溜滴，径狭长松围。只恐相寻日，人间旧识稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 延福里秋怀 ----------
    {
        "id": "zhang-qiao-69",
        "title": "延福里秋怀",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "终年九陌行，要路迹皆生。苦学犹难至，甘贫岂有成。",
            "病携秋卷重，闲著暑衣轻。一别林泉久，中宵御水声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 题玄哲禅师影堂 ----------
    {
        "id": "zhang-qiao-70",
        "title": "题玄哲禅师影堂",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "吾师视化身，一念即遗尘。岩谷藏虚塔，江湖散学人。",
            "云迷禅处石，院掩写来真。寂寞焚香后，闲阶细草生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 登慈恩寺塔 ----------
    {
        "id": "zhang-qiao-71",
        "title": "登慈恩寺塔",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "窗户几层风，清凉碧落中。世人来往别，烟景古今同。",
            "列岫横秦断，长河极塞空。斜阳越乡思，天末见归鸿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 送友人东归 ----------
    {
        "id": "zhang-qiao-72",
        "title": "送友人东归",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "远涉期秋卷，将行不废吟。故乡芳草路，来往别离心。",
            "挂席春风尽，开斋夏景深。子规谁共听，江月上清岑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 送僧鸾归蜀宁亲 ----------
    {
        "id": "zhang-qiao-73",
        "title": "送僧鸾归蜀宁亲",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "歌诗精外学，天子是知音。坐夏宫钟近，宁亲剑阁深。",
            "高名彻西国，旧迹寄东林。自此栖禅者，因师满蜀吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 送人归江南 ----------
    {
        "id": "zhang-qiao-74",
        "title": "送人归江南",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "贫归无定程，水宿与山行。未有安亲计，难为去国情。",
            "岛烟孤寺磬，江月远船筝。思苦秋回日，多应吟更清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 将离江上作 ----------
    {
        "id": "zhang-qiao-75",
        "title": "将离江上作",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "白衣归树下，青草恋江边。三楚足深隐，五陵多少年。",
            "寂寥闻蜀魄，清绝怨湘弦。岐路在何处，西行心渺然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 别李参军 ----------
    {
        "id": "zhang-qiao-76",
        "title": "别李参军",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "王孙游不遇，况我五湖人。野店难投宿，渔家独问津。",
            "岭分中夜月，江隔两乡春。静想青云路，还应寄此身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 送睦州张参军 ----------
    {
        "id": "zhang-qiao-77",
        "title": "送睦州张参军",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "重禄轻身日，清资近故乡。因知送君后，转自惜年芳。",
            "远水分林影，层峰起鸟行。扁舟此中去，溪月有余光。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 赠棋僧侣 ----------
    {
        "id": "zhang-qiao-78",
        "title": "赠棋僧侣",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "机谋时未有，多向弈棋销。已与山僧敌，无令海客饶。",
            "静驱云阵起，疏点雁行遥。夜雨如相忆，松窗更见招。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 题湖上友人居 ----------
    {
        "id": "zhang-qiao-79",
        "title": "题湖上友人居",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "岂得恋樵渔，全家湖畔居。远无潮客信，闲寄岳僧书。",
            "野白梅繁后，山明雨散初。逍遥向云水，莫与宦情疏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 送友人归宣州 ----------
    {
        "id": "zhang-qiao-80",
        "title": "送友人归宣州",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "失计复离愁，君归我独游。乱花藏道发，春水绕乡流。",
            "暝火丛桥市，晴山叠郡楼。无为谢公恋，吟过晓蝉秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 题古观 ----------
    {
        "id": "zhang-qiao-81",
        "title": "题古观",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "急景递衰老，此经谁养真。松留千载鹤，碑隔六朝人。",
            "洞水流花早，壶天闭雪春。其如为名利，归踏五陵尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 送友人及第归江南 ----------
    {
        "id": "zhang-qiao-82",
        "title": "送友人及第归江南",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "岂易及归荣，辛勤致此名。登车思往事，回首勉诸生。",
            "路绕山光晓，帆通海气清。秋期却闲坐，林下听江声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 送朴充侍御归海东 ----------
    {
        "id": "zhang-qiao-83",
        "title": "送朴充侍御归海东",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "天涯离二纪，阙下历三朝。涨海虽然阔，归帆不觉遥。",
            "惊波时失侣，举火夜相招。来往寻遗事，秦皇有断桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 吊前水部贾员外 ----------
    {
        "id": "zhang-qiao-84",
        "title": "吊前水部贾员外",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "笼中江海禽，日夕有归心。魏阙长谣久，吴山独往深。",
            "别时群木落，终处乱猿吟。李白坟前路，溪僧送入林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 题小松 ----------
    {
        "id": "zhang-qiao-85",
        "title": "题小松",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "松子落何年，纤枝长水边。斫开深涧雪，移出远林烟。",
            "带月栖幽鸟，兼花灌冷泉。微风动清韵，闲听罢琴眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 寄中岳颛顼先生 ----------
    {
        "id": "zhang-qiao-86",
        "title": "寄中岳颛顼先生",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "先生颛顼后，得道自何人。松柏卑于寿，儿孙老却身。",
            "夜窗峰顶曙，寒涧洞中春。恋此逍遥境，云间不可亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 送沈先辈尉昭应 ----------
    {
        "id": "zhang-qiao-87",
        "title": "送沈先辈尉昭应",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "馀才不废诗，佐邑喜闲司。丹陛终须去，青山未可期。",
            "叶凋温谷晚，云出古宫迟。若草东封疏，君王到有时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 送友人游湖南 ----------
    {
        "id": "zhang-qiao-88",
        "title": "送友人游湖南",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "所投非旧知，亦似有前期。路向长江上，帆扬细雨时。",
            "春生南岳早，日转大荒迟。尽采潇湘句，重来会近期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 江上送友人南游 ----------
    {
        "id": "zhang-qiao-89",
        "title": "江上送友人南游",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "何处积乡愁，天涯聚乱流。岸长群岫晚，湖阔片帆秋。",
            "买酒过渔舍，分灯与钓舟。潇湘见来雁，应念独边游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 江南别友人 ----------
    {
        "id": "zhang-qiao-90",
        "title": "江南别友人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "劳生故白头，头白未应休。阙下难孤立，天涯尚旅游。",
            "听猿吟岛寺，待月上江楼。醉别醒惆怅，云帆满乱流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 商山道中 ----------
    {
        "id": "zhang-qiao-91",
        "title": "商山道中",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "春去计秋期，长安在梦思。多逢山好处，少值客行时。",
            "云起争峰势，花交隐涧枝。停骖一惆怅，应只岭猿知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 吴江旅次 ----------
    {
        "id": "zhang-qiao-92",
        "title": "吴江旅次",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "行人愁落日，去鸟倦遥林。旷野鸣流水，空山响暮砧。",
            "旅途归计晚，乡树别年深。寂寞逢村酒，渔家一醉吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 寄南中友人 ----------
    {
        "id": "zhang-qiao-93",
        "title": "寄南中友人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷93》",
        "verse": [
            "相梦如相见，相思去后频。旧时行处断，华发别来新。",
            "浪动三湘月，烟藏五岭春。又无归北客，书札寄何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 寄绩溪陈明府 ----------
    {
        "id": "zhang-qiao-94",
        "title": "寄绩溪陈明府",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "古邑猿声里，空城只半存。岸移无旧路，沙涨别成村。",
            "鼓角喧京口，江山尽汝濆。六朝兴废地，行子一销魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 试月中桂 ----------
    {
        "id": "zhang-qiao-95",
        "title": "试月中桂",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷95》",
        "verse": [
            "与月转洪濛，扶疏万古同。根非生下土，叶不坠秋风。",
            "每以圆时足，还随缺处空。影高群木外，香满一轮中。",
            "未种丹霄日，应虚玉兔宫。何当因羽化，细得问玄功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 游歙州兴唐寺 ----------
    {
        "id": "zhang-qiao-96",
        "title": "游歙州兴唐寺",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷96》",
        "verse": [
            "山桥通绝境，到此忆天台。竹里寻幽径，云边上古台。",
            "鸟归残照出，钟断细泉来。为爱澄溪月，因成隔宿回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 题诠律师院 ----------
    {
        "id": "zhang-qiao-97",
        "title": "题诠律师院",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷97》",
        "verse": [
            "院凉松雨声，相对有山情。未许谿边老，犹思岳顶行。",
            "纱灯留火细，石井灌瓶清。欲问吾师外，何人得此生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 金山寺空上人院 ----------
    {
        "id": "zhang-qiao-98",
        "title": "金山寺空上人院",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷98》",
        "verse": [
            "已老金山顶，无心上石桥。讲移三楚遍，梵译五天遥。",
            "板阁禅秋月，铜瓶汲夜潮。自惭昏醉客，来坐亦通宵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 题广信寺 ----------
    {
        "id": "zhang-qiao-99",
        "title": "题广信寺",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷99》",
        "verse": [
            "亭北敞灵溪，林梢与槛齐。野云来影远，沙鸟去行低。",
            "晚渡明村火，晴山响郡鼙。思乡值摇落，赖不有猿啼。",
            "第六百三十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 兴善寺贝多树 ----------
    {
        "id": "zhang-qiao-100",
        "title": "兴善寺贝多树",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "还应毫末长，始见拂丹霄。得子从西国，成阴见昔朝。",
            "势随双刹直，寒出四墙遥。带月啼春鸟，连空噪暝蜩。",
            "远根穿古井，高顶起凉飙。影动悬灯夜，声繁过雨朝。",
            "静迟松桂老，坚任雪霜凋。永共终南在，应随劫火烧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 华山 ----------
    {
        "id": "zhang-qiao-101",
        "title": "华山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "青苍河一隅，气状杳难图。卓杰三峰出，高奇四岳无。",
            "力疑擎上界，势独压中区。众水东西走，群山远近趋。",
            "天回诸宿照，地耸百灵扶。石壁烟霞丽，龙潭雨雹粗。",
            "澄凝临甸服，险固束神都。浅觉川原异，深应日月殊。",
            "鹤归青霭合，仙去白云孤。瀑漏斜飞冻，松长倒挂枯。",
            "每来寻洞穴，不拟返江湖。傥有芝田种，岩间老一夫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 送何道士归山 ----------
    {
        "id": "zhang-qiao-102",
        "title": "送何道士归山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "身非绝粒本清羸，束挂仙经杖一枝。落叶独寻流水去，",
            "深山长与白云期。树临丹灶寒花疾，坛近清岚夜月迟。",
            "樵客若能随洞里，回归人世始应悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 城东寓居寄知己 ----------
    {
        "id": "zhang-qiao-103",
        "title": "城东寓居寄知己",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "花木闲门苔藓生，浐川特去得吟情。病来久绝洞庭信，",
            "年长却思庐岳耕。落日独归林下宿，暮云多绕水边行。",
            "干时退出长如此，频愧相忧道姓名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 再书边事 ----------
    {
        "id": "zhang-qiao-104",
        "title": "再书边事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "万里沙西寇已平，犬羊群外筑空城。分营夜火烧云远，",
            "校猎秋雕掠草轻。秦将力随胡马竭，蕃河流入汉家清。",
            "羌戎不识干戈老，须贺当时圣主明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 游边感怀二首 ----------
    {
        "id": "zhang-qiao-105",
        "title": "游边感怀二首",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "贫游缭绕困边沙，却被辽阳战士嗟。",
            "不是无家归不得，有家归去似无家。",
            "兄弟江南身塞北，雁飞犹自半年馀。",
            "夜来因得思乡梦，重读前秋转海书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 无题（一作赠友人） ----------
    {
        "id": "zhang-qiao-106",
        "title": "无题（一作赠友人）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "九霄无诏下，何事触清尘。宅带松萝僻，身惟猿鸟亲。",
            "吟看仙掌月，期有洞庭人。莫问烟霞句，悬知见岳神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 蝉 ----------
    {
        "id": "zhang-qiao-107",
        "title": "蝉",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "先秋蝉一悲，长是客行时。曾感去年者，又鸣何处枝。",
            "细听残韵在，回望旧声迟。断续谁家树，凉风送别离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 江上逢进士许棠 ----------
    {
        "id": "zhang-qiao-108",
        "title": "江上逢进士许棠",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "诗人推上第，新榜又无君。鹤发他乡老，渔歌故国闻。",
            "平江流晓月，独鸟伴馀云。且了髫年志，沙鸥未可群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 送河西从事 ----------
    {
        "id": "zhang-qiao-109",
        "title": "送河西从事",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "结束佐戎旃，河西住几年。陇头随日去，碛里寄星眠。",
            "水近沙连帐，程遥马入天。圣朝思上策，重待奏安边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 河湟旧卒 ----------
    {
        "id": "zhang-qiao-110",
        "title": "河湟旧卒",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "少年随将讨河湟，头白时清返故乡。",
            "十万汉军零落尽，独吹边曲向残阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 促织 ----------
    {
        "id": "zhang-qiao-111",
        "title": "促织",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "念尔无机自有情，迎寒辛苦弄梭声。",
            "椒房金屋何曾识，偏向贫家壁下鸣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 猿（一作长安赠猿） ----------
    {
        "id": "zhang-qiao-112",
        "title": "猿（一作长安赠猿）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "挂月栖云向楚林，取来全是为清音。",
            "谁知系在黄金索，翻畏侯家不敢吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 寄荐福寺栖白大师 ----------
    {
        "id": "zhang-qiao-113",
        "title": "寄荐福寺栖白大师",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "高塔六街无不见，塔边名出只吾师。",
            "尝闻朝客多相□，记得□□数句诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 越中赠别 ----------
    {
        "id": "zhang-qiao-114",
        "title": "越中赠别",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "东越相逢几醉眠，满楼明月镜湖边。",
            "别离吟断西陵渡，杨柳秋风两岸蝉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 寄清越上人（一作寄山僧） ----------
    {
        "id": "zhang-qiao-115",
        "title": "寄清越上人（一作寄山僧）",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "大道本来无所染，白云那得有心期。",
            "远公独刻莲花漏，犹向空山礼六时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 宿齐山僧舍 ----------
    {
        "id": "zhang-qiao-116",
        "title": "宿齐山僧舍",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "一宿经窗卧白波，万重归梦隔烟萝。",
            "若言不得南宗要，长在禅床事更多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 春日游曲江 ----------
    {
        "id": "zhang-qiao-117",
        "title": "春日游曲江",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "日暖鸳鸯拍浪春，蒹葭浦际聚青蘋。",
            "若论来往乡心切，须是烟波岛上人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 渔家 ----------
    {
        "id": "zhang-qiao-118",
        "title": "渔家",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "拥棹思悠悠，更深泛积流。唯将一星火，何处宿芦洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 送人及第归海东 ----------
    {
        "id": "zhang-qiao-119",
        "title": "送人及第归海东",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "东风日边起，草木一时春。自笑中华路，年年送远人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 题河中鹳雀楼 ----------
    {
        "id": "zhang-qiao-120",
        "title": "题河中鹳雀楼",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "高楼怀古动悲歌，鹳雀今无野燕过。树隔五陵秋色早，",
            "水连三晋夕阳多。渔人遗火成寒烧，牧笛吹风起夜波。",
            "十载重来值摇落，天涯归计欲如何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 宿洛都门 ----------
    {
        "id": "zhang-qiao-121",
        "title": "宿洛都门",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "山川马上度边禽，一宿都门永夜吟。",
            "客路不归秋又晚，西风吹动洛阳砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 对月二首 ----------
    {
        "id": "zhang-qiao-122",
        "title": "对月二首",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "圆魄上寒空，皆言四海同。安知千里外，不有雨兼风。",
            "盈缺青冥外，东风万古吹。何人种丹桂，不长出轮枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 赠友人 ----------
    {
        "id": "zhang-qiao-123",
        "title": "赠友人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "自说安贫归未得，竹边门掩小池冰。典琴赊酒吟过寺，",
            "送客思乡上灞陵。待月夜留烟岛客，忆云闲访翠微僧。",
            "几时献了相如赋，共向嵩山采茯苓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 笛 ----------
    {
        "id": "zhang-qiao-124",
        "title": "笛",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "剪雨裁烟一节秋，落梅杨柳曲中愁。",
            "尊前暂借殷勤看，明日曾闻向陇头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 渔者 ----------
    {
        "id": "zhang-qiao-125",
        "title": "渔者",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "首戴圆荷发不梳，叶舟为宅水为居。",
            "沙头聚看人如市，钓得澄江一丈鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 宿潺湲亭 ----------
    {
        "id": "zhang-qiao-126",
        "title": "宿潺湲亭",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "走月流烟叠树西，听来愁甚听猿啼。",
            "几时御水声边住，却梦潺湲宿此溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 台城 ----------
    {
        "id": "zhang-qiao-127",
        "title": "台城",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "宫殿馀基长草花，景阳宫树噪村鸦。",
            "云屯雉堞依然在，空绕渔樵四五家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 寄山僧 ----------
    {
        "id": "zhang-qiao-128",
        "title": "寄山僧",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "闲倚蒲团向日眠，不能归老岳云边。",
            "旧时僧侣无人在，惟有长松见少年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 题上元许棠所任王昌龄厅 ----------
    {
        "id": "zhang-qiao-129",
        "title": "题上元许棠所任王昌龄厅",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "琉璃堂里当时客，久绝吟声继后尘。",
            "百四十年庭树老，如今重得见诗人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 自诮 ----------
    {
        "id": "zhang-qiao-130",
        "title": "自诮",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "每到花时恨道穷，一生光景半成空。",
            "只应抱璞非良玉，岂得年年不至公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 赠河南诗友 ----------
    {
        "id": "zhang-qiao-131",
        "title": "赠河南诗友",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "山东令族玉无尘，裁剪烟花笔下春。",
            "不把瑶华借风月，洛阳才子更何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 寄维扬故人 ----------
    {
        "id": "zhang-qiao-132",
        "title": "寄维扬故人",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "离别河边绾柳条，千山万水玉人遥。",
            "月明记得相寻处，城锁东风十五桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 孤云 ----------
    {
        "id": "zhang-qiao-133",
        "title": "孤云",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "舒卷因风何所之，碧天孤影势迟迟。",
            "莫言长是无心物，还有随龙作雨时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 咏棋子赠弈僧 ----------
    {
        "id": "zhang-qiao-134",
        "title": "咏棋子赠弈僧",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "黑白谁能用入玄，千回生死体方圆。",
            "空门说得恒沙劫，应笑终年为一先。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 谷口作 ----------
    {
        "id": "zhang-qiao-135",
        "title": "谷口作",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "巴客青冥过岭尘，雪崖交映一川春。",
            "晴朝采药寻源去，必恐云深见异人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 寄弟 ----------
    {
        "id": "zhang-qiao-136",
        "title": "寄弟",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "故里行人战后疏，青崖萍寄白云居。",
            "那堪又是伤春日，把得长安落第书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 春日有怀 ----------
    {
        "id": "zhang-qiao-137",
        "title": "春日有怀",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "高下寻花春景迟，汾阳台榭白云诗。",
            "看山怀古翻惆怅，未胜遥传不到时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 鹭鸶障子 ----------
    {
        "id": "zhang-qiao-138",
        "title": "鹭鸶障子",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "剪得机中如雪素，画为江上带丝禽。",
            "闲来相对茅堂下，引出烟波万里心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 甘露寺僧房 ----------
    {
        "id": "zhang-qiao-139",
        "title": "甘露寺僧房",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "临水登山路，重寻旅思劳。竹阴行处密，僧腊别来高。",
            "远岫明寒火，危楼响夜涛。悲秋不成寐，明月上千舠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 140. 宿江叟岛居 ----------
    {
        "id": "zhang-qiao-140",
        "title": "宿江叟岛居",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "一家烟岛隈，竹里夜窗开。数派分潮去，千樯聚月来。",
            "石楼云断续，涧渚雁徘徊。了得平生志，还归筑钓台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 141. 江村 ----------
    {
        "id": "zhang-qiao-141",
        "title": "江村",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "贫游无定踪，乡信转难逢。寒渚暮烟阔，去帆归思重。",
            "潮平低戌火，木落远山钟。况是渔家宿，疏篱响夜舂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 142. 赠进士顾云 ----------
    {
        "id": "zhang-qiao-142",
        "title": "赠进士顾云",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "潮槛烟波别钓津，西京同□荻□贫。不知守道归何日，",
            "相对无言尽几春。晴景远山花外暮，云边高盖水边□。",
            "与君愁寂无消处，赊酒青门送楚人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 143. 赠头陀僧 ----------
    {
        "id": "zhang-qiao-143",
        "title": "赠头陀僧",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "自说年深别石桥，遍游灵迹熟南朝。已知世路皆虚幻，",
            "不觉空门是寂寥。沧海附船浮浪久，碧山寻塔上云遥。",
            "如今竹院藏衰老，一点寒灯弟子烧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 144. 寻阳村舍 ----------
    {
        "id": "zhang-qiao-144",
        "title": "寻阳村舍",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "荒林寄远居，坐卧见樵渔。夜火随船远，寒更出郡疏。",
            "雪迷登岳路，风阻转江书。寂寞高窗下，思乡岁欲除。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 145. 江楼作 ----------
    {
        "id": "zhang-qiao-145",
        "title": "江楼作",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "凭槛见天涯，非秋亦可悲。晚天帆去疾，春雪燕来迟。",
            "山水分乡县，干戈足别离。南人废耕织，早晚罢王师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 146. 回鸾阁写望 ----------
    {
        "id": "zhang-qiao-146",
        "title": "回鸾阁写望",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "古阁上空半，寥寥千里心。多年为客路，尽日倚栏吟。",
            "山压秦川重，河来虏塞深。回銮今不见，烟雾杳沉沉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 147. 题宣州开元寺 ----------
    {
        "id": "zhang-qiao-147",
        "title": "题宣州开元寺",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "谁家烟径长莓苔，金碧虚栏竹上开。流水远分山色断，",
            "清猿时带角声来。六朝明月唯诗在，三楚空山有雁回。",
            "达理始应尽惆怅，僧闲应得话天台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 148. 题友人草堂 ----------
    {
        "id": "zhang-qiao-148",
        "title": "题友人草堂",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "空山卜隐初，生计亦无馀。三亩水边竹，一床琴畔书。",
            "深林收晚果，绝顶拾秋蔬。坚话长如此，何年献子虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 149. 七松亭 ----------
    {
        "id": "zhang-qiao-149",
        "title": "七松亭",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "七松亭上望秦川，高鸟闲云满目前。已比子真耕谷口，",
            "岂同陶令卧江边。临崖把卷惊回烧，扫石留僧听远泉。",
            "明月影中宫漏近，珮声应宿使朝天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 150. 题友人林斋 ----------
    {
        "id": "zhang-qiao-150",
        "title": "题友人林斋",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "乔木带凉蝉，来吟暑雨天。不离高枕上，似宿远山边。",
            "簟冷窗中月，茶香竹里泉。吾庐近溪岛，忆别动经年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 151. 经宣城元员外山居 ----------
    {
        "id": "zhang-qiao-151",
        "title": "经宣城元员外山居",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "无人袭仙隐，石室闭空山。避烧猿犹到，随云鹤不还。",
            "涧荒岩影在，桥断树阴闲。但有黄河赋，长留在世间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 152. 经九华山费征君故居 ----------
    {
        "id": "zhang-qiao-152",
        "title": "经九华山费征君故居",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "草堂芜没后，来往问樵翁。断石荒林外，孤坟晚照中。",
            "数溪分大野，九子立寒空。烟壁曾行处，青云路不通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 153. 题贾岛吟诗台 ----------
    {
        "id": "zhang-qiao-153",
        "title": "题贾岛吟诗台",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "吟魂不复游，台亦似荒丘。一径草中出，长江天外流。",
            "暝烟寒鸟集，残月夜虫愁。愿得生禾黍，锄平恨即休。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 154. 游南岳 ----------
    {
        "id": "zhang-qiao-154",
        "title": "游南岳",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "入岩仙境清，行尽复重行。若得闲无事，长来寄此生。",
            "涧松闲易老，笼烛晚生明。一宿泉声里，思乡梦不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 155. 寻桃源 ----------
    {
        "id": "zhang-qiao-155",
        "title": "寻桃源",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "武林春草齐，花影隔澄溪。路远无人去，山空有鸟啼。",
            "水垂青霭断，松偃绿萝低。世上迷途客，经兹尽不迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 156. 青鸟泉 ----------
    {
        "id": "zhang-qiao-156",
        "title": "青鸟泉",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "只此沉仙翼，瑶池似不遥。有声悬翠壁，无势下丹霄。",
            "净濑烟霞古，寒原草木凋。山河几更变，幽咽到唐朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 157. 望巫山 ----------
    {
        "id": "zhang-qiao-157",
        "title": "望巫山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "溪叠云深转谷迟，暝投孤店草虫悲。愁连远水波涛夜，",
            "梦断空山雨雹时。边海故园荒后卖，入关玄发夜来衰。",
            "东归未必胜羁旅，况是东归未有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 158. 省中偶作 ----------
    {
        "id": "zhang-qiao-158",
        "title": "省中偶作",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "二转郎曹自勉旃，莎阶吟步想前贤。不如何逊无佳句，",
            "若比冯唐是壮年。捧制名题黄纸尾，约僧心在白云边。",
            "乳毛松雪春来好，直夜清闲且学禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 159. 秋夕 ----------
    {
        "id": "zhang-qiao-159",
        "title": "秋夕",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "春恨复秋悲，秋悲难到时。每逢明月夜，长起故山思。",
            "巷僻行吟远，蛩多独卧迟。溪僧与樵客，动别十年期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 160. 山中冬夜 ----------
    {
        "id": "zhang-qiao-160",
        "title": "山中冬夜",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "寒叶风摇尽，空林鸟宿稀。涧冰妨鹿饮，山雪阻僧归。",
            "夜坐尘心定，长吟语力微。人间去多事，何处梦柴扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 161. 宿刘温书斋 ----------
    {
        "id": "zhang-qiao-161",
        "title": "宿刘温书斋",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "不掩盈窗月，天然格调高。凉风移蟋蟀，落叶在离骚。",
            "回笔挑灯烬，悬图见海涛。因论三国志，空载几英豪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 162. 归旧山 ----------
    {
        "id": "zhang-qiao-162",
        "title": "归旧山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "昔年山下结茅茨，村落重来野径移。樵客相逢悲往事，",
            "林僧闲坐问归期。异藤遍树无空处，幽草缘溪少歇时。",
            "此景一抛吟欲老，可能文字圣朝知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 163. 潭上作 ----------
    {
        "id": "zhang-qiao-163",
        "title": "潭上作",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "竹岛残阳映翠微，雪翎禽过碧潭飞。",
            "人间未有关身事，每到渔家不欲归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 164. 杨花落 ----------
    {
        "id": "zhang-qiao-164",
        "title": "杨花落",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "北斗南回春物老，红英落尽绿尚早。韶风澹荡无所依，",
            "偏惜垂杨作春好。此时可怜杨柳花，萦盈艳曳满人家。",
            "人家女儿出罗幕，净扫玉除看花落。宝环纤手捧更飞，",
            "翠羽轻裙承不著。历历瑶琴舞袖陈，飞红拂黛怜玉人。",
            "东园桃李芳已歇，犹有杨花娇暮春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 165. 九华楼晴望 ----------
    {
        "id": "zhang-qiao-165",
        "title": "九华楼晴望",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "一夜江潭风雨后，九华晴望倚天秋。",
            "重来此地知何日，欲别殷勤更上楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 166. 终南山 ----------
    {
        "id": "zhang-qiao-166",
        "title": "终南山",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "带雪复衔春，横天占半秦。势奇看不定，景变写难真。",
            "洞远皆通岳，川多更有神。白云幽绝处，自古属樵人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 167. 哭陈陶 ----------
    {
        "id": "zhang-qiao-167",
        "title": "哭陈陶",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "先生抱衰疾，不起茂陵间。夕临诸孤少，荒居吊客还。",
            "遗文禅东岳，留语葬乡山。多雨铭旌故，残灯素帐闲。",
            "乐章谁与集，陇树即堪攀。神理今难问，予将叫帝关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 168. 长门怨 ----------
    {
        "id": "zhang-qiao-168",
        "title": "长门怨",
        "author": "张乔",
        "poet_id": "zhang-qiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "御泉长绕凤凰楼，自是恩波别处流。",
            "闲揲舞衣归未得，夜来砧杵六宫秋。",
            "第六百四十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]