# -*- coding: utf-8 -*-
"""
法振卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 17 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 病愈寄友 ----------
    {
        "id": "fa-zhen-1",
        "title": "病愈寄友",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "哀乐暗成疾，卧中芳月移。西山有清士，孤啸不可追。",
            "捣药昼林静，汲泉阴涧迟。微踪与麋鹿，远谢求羊知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 程评事西园之作 ----------
    {
        "id": "fa-zhen-2",
        "title": "程评事西园之作",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "谁向春莺道，名园已共知。檐前回水影，城上出花枝。",
            "摇拂烟云动，登临翰墨随。相招能不厌，山舍为君移。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 陈九溪中草堂 ----------
    {
        "id": "fa-zhen-3",
        "title": "陈九溪中草堂",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "溪草落溅溅，鱼飞入稻田。早寒临洞月，轻素卷帘烟。",
            "dU帻题新句，蓑衣象古贤。曙花闲秀色，三十六峰前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题天长阮少府湖上客归 ----------
    {
        "id": "fa-zhen-4",
        "title": "题天长阮少府湖上客归",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "孤棹移官舍，新农寄楚田。晴林渡海日，春草长湖烟。",
            "卧对闲鸥戏，谈经稚子贤。佳期更何许，应向啸台前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题万山许炼师 ----------
    {
        "id": "fa-zhen-5",
        "title": "题万山许炼师",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "道成人不识，流水响空山。花暗轩窗外，云随坐卧间。",
            "验图名已久，绝粒事长闲。更欲昆仑去，羞看绛节还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 河源破贼后赠袁将军 ----------
    {
        "id": "fa-zhen-6",
        "title": "河源破贼后赠袁将军",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "白羽三千驻，萧萧万里行。出关深汉垒，带月破蕃营。",
            "蔓草河原色，悲笳碎叶声。欲朝王母殿，前路驻高旌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 越中赠程先生 ----------
    {
        "id": "fa-zhen-7",
        "title": "越中赠程先生",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "纱帽度残春，虚舟寄一身。溪边逢越女，花里问秦人。",
            "古塞连山静，阴霞落海新。有时城郭去，暗与酒家亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送常大夫赴朔方 ----------
    {
        "id": "fa-zhen-8",
        "title": "送常大夫赴朔方",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "关山今不掩，军候鸟先知。大汉嫖姚入，乌孙部曲随。",
            "高旌天外驻，寒角月中吹。归到长安第，花应再满枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送人游闽越 ----------
    {
        "id": "fa-zhen-9",
        "title": "送人游闽越",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "不须行借问，为尔话闽中。海岛阴晴日，江帆来去风。",
            "道游玄度宅，身寄朗陵公。此别何伤远，如今关塞通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送褚先生海上寻封炼师 ----------
    {
        "id": "fa-zhen-10",
        "title": "送褚先生海上寻封炼师",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "潮落风初定，天吴避客舟。近承三殿旨，欲向五湖游。",
            "不厌乌皮几，新缝鹤氅裘。明珠漂断岸，阴火映中流。",
            "华盖芝童引，神丹桂女收。悬知居缥缈，因为识浮丘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送韩侍御自使幕巡海北 ----------
    {
        "id": "fa-zhen-11",
        "title": "送韩侍御自使幕巡海北",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "微雨空山夜洗兵，绣衣朝拂海云清。幕中运策心应苦，",
            "马上吟诗卷已成。离亭不惜花源醉，古道犹看蔓草生。",
            "因说元戎能破敌，高歌一曲陇关情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 张舍人南溪别业 ----------
    {
        "id": "fa-zhen-12",
        "title": "张舍人南溪别业",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "新田绕屋半春耕，藜杖闲门引客行。山翠自成微雨色，",
            "谿花不隐乱泉声。渔家远到堪留兴，公府悬知欲厌名。",
            "入夜更宜明月满，双童唤出解吹笙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 别卢使君归故栅村 ----------
    {
        "id": "fa-zhen-13",
        "title": "别卢使君归故栅村",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "归风白马引嘶声，落日犹看楚客情。塞口竹缘空戍没，",
            "潮头沙拥慢冈成。松田且欲亲耕种，郡守何偏问姓名。",
            "东道宿程投故栅，依依渔父解相迎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 丹阳浦送客之海上 ----------
    {
        "id": "fa-zhen-14",
        "title": "丹阳浦送客之海上",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "不到终南向几秋，移居更欲近沧洲。风吹雨色连村暗，",
            "潮拥菱花出岸浮。漠漠望中春自艳，寥寥泊处夜堪愁。",
            "如君岂得空高枕，只益天书遣远求。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 月夜泛舟 ----------
    {
        "id": "fa-zhen-15",
        "title": "月夜泛舟",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "西塞长云尽，南湖片月斜。漾舟人不见，卧入武陵花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送友人之上都 ----------
    {
        "id": "fa-zhen-16",
        "title": "送友人之上都",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "玉帛征贤楚客稀，猿啼相送武陵归。",
            "湖头望入桃花去，一片春帆带雨飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 句 ----------
    {
        "id": "fa-zhen-17",
        "title": "句",
        "author": "法振",
        "poet_id": "fa-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "画鼓催来锦臂襄，小娥双起整霓裳。（《柘枝》，",
            "见《韵语阳秋》）",
            "第八百一十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]