# -*- coding: utf-8 -*-
"""
崔涯卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 黄蜀葵 ----------
    {
        "id": "cui-ya-1",
        "title": "黄蜀葵",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "野栏秋景晚，疏散两三枝。嫩碧浅轻态，幽香闲澹姿。",
            "露倾金盏小，风引道冠欹。独立悄无语，清愁人讵知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 咏春风 ----------
    {
        "id": "cui-ya-2",
        "title": "咏春风",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "动地经天物不伤，高情逸韵住何方。扶持燕雀连天去，",
            "断送杨花尽日狂。绕桂月明过万户，弄帆晴晚渡三湘。",
            "孤云虽是无心物，借便吹教到帝乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 竹 ----------
    {
        "id": "cui-ya-3",
        "title": "竹",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "领得溪风不放回，傍窗缘砌遍庭栽。须招野客为邻住，",
            "看引山禽入郭来。幽院独惊秋气早，小门深向绿阴开。",
            "谁怜翠色兼寒影，静落茶瓯与酒杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 侠士诗 ----------
    {
        "id": "cui-ya-4",
        "title": "侠士诗",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "太行岭上二尺雪，崔涯袖中三尺铁。",
            "一朝若遇有心人，出门便与妻儿别。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 别妻 ----------
    {
        "id": "cui-ya-5",
        "title": "别妻",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "陇上泉流陇下分，断肠呜咽不堪闻。",
            "嫦娥一入月中去，巫峡千秋空白云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 杂嘲二首 ----------
    {
        "id": "cui-ya-6",
        "title": "杂嘲二首",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "二年不到宋家东，阿母深居僻巷中。",
            "含泪向人羞不语，琵琶弦断倚屏风。",
            "日暮迎来香閤中，百年心事一宵同。",
            "寒鸡鼓翼纱窗外，已觉恩情逐晓风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 悼妓 ----------
    {
        "id": "cui-ya-7",
        "title": "悼妓",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "赤板桥西小竹篱，槿花还似去年时。",
            "淡黄衫子浑无色，肠断丁香画雀儿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 嘲妓 ----------
    {
        "id": "cui-ya-8",
        "title": "嘲妓",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "虽得苏方木，犹贪玳瑁皮。怀胎十个月，生下昆仑儿。",
            "布袍披袄火烧毡，纸补箜篌麻接弦。",
            "更著一双皮屐子，纥梯纥榻出门前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 嘲李端端 ----------
    {
        "id": "cui-ya-9",
        "title": "嘲李端端",
        "author": "崔涯",
        "poet_id": "cui-ya",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "黄昏不语不知行，鼻似烟窗耳似铛。",
            "独把象牙梳插鬓，昆仑山上月初明。",
            "觅得黄骝鞁绣鞍，善和坊里取端端。",
            "扬州近日浑成差，一朵能行白牡丹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]