# -*- coding: utf-8 -*-
"""
徐凝卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 92 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 送马向入蜀 ----------
    {
        "id": "xu-ning-1",
        "title": "送马向入蜀",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "游子出咸京，巴山万里程。白云连鸟道，青壁遰猿声。",
            "雨雪经泥坂，烟花望锦城。工文人共许，应纪蜀中行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送李补阙归朝 ----------
    {
        "id": "xu-ning-2",
        "title": "送李补阙归朝",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "驷马归咸秦，双凫出海门。还从清切禁，再沐圣明恩。",
            "礼乐中朝贵，文章大雅存。江湖多放逸，献替欲谁论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送日本使还 ----------
    {
        "id": "xu-ning-3",
        "title": "送日本使还",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "绝国将无外，扶桑更有东。来朝逢圣日，归去及秋风。",
            "夜泛潮回际，晨征苍莽中。鲸波腾水府，蜃气壮仙宫。",
            "天眷何期远，王文久已同。相望杳不见，离恨托飞鸿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题开元寺牡丹 ----------
    {
        "id": "xu-ning-4",
        "title": "题开元寺牡丹",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "此花南地知难种，惭愧僧闲用意栽。海燕解怜频睥睨，",
            "胡蜂未识更徘徊。虚生芍药徒劳妒，羞杀玫瑰不敢开。",
            "惟有数苞红萼在，含芳只待舍人来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 香炉峰 ----------
    {
        "id": "xu-ning-5",
        "title": "香炉峰",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "香炉一峰绝，顶在寺门前。尽是玲珑石，时生旦暮烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 白铜鞮 ----------
    {
        "id": "xu-ning-6",
        "title": "白铜鞮",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "騕褭锦障泥，楼头日又西。留欢住不住，素齿白铜鞮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 杨叛儿 ----------
    {
        "id": "xu-ning-7",
        "title": "杨叛儿",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "哀怨杨叛儿，骀荡郎知否。香死博山炉，烟生白门柳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 春寒 ----------
    {
        "id": "xu-ning-8",
        "title": "春寒",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "乱雪从教舞，回风任听吹。春寒能作底，已被柳条欺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 庐山独夜 ----------
    {
        "id": "xu-ning-9",
        "title": "庐山独夜",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "寒空五老雪，斜月九江云。钟声知何处，苍苍树里闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 天台独夜 ----------
    {
        "id": "xu-ning-10",
        "title": "天台独夜",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "银地秋月色，石梁夜溪声。谁知屐齿尽，为破烟苔行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送寒岩归士 ----------
    {
        "id": "xu-ning-11",
        "title": "送寒岩归士",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "不挂丝纩衣，归向寒岩栖。寒岩风雪夜，又过岩前溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送陈司马 ----------
    {
        "id": "xu-ning-12",
        "title": "送陈司马",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "家寄茅洞中，身游越城下。宁知许长史，不忆陈司马。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 武夷山仙城 ----------
    {
        "id": "xu-ning-13",
        "title": "武夷山仙城",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "武夷无上路，毛径不通风。欲共麻姑住，仙城半在空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 避暑二首 ----------
    {
        "id": "xu-ning-14",
        "title": "避暑二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "一株金染密，数亩碧鲜疏。避暑临溪坐，何妨直钓鱼。",
            "斑多筒簟冷，发少角冠清。避暑长林下，寒蝉又有声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 浙西李尚书奏毁淫昏庙 ----------
    {
        "id": "xu-ning-15",
        "title": "浙西李尚书奏毁淫昏庙",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "传闻废淫祀，万里静山陂。欲慰灵均恨，先烧靳尚祠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 酬相公再游云门寺 ----------
    {
        "id": "xu-ning-16",
        "title": "酬相公再游云门寺",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "远羡五云路，逶迤千骑回。遗簪唯一去，贵赏不重来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 杭州祝涛头二首 ----------
    {
        "id": "xu-ning-17",
        "title": "杭州祝涛头二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "不道沙堤尽，犹欺石栈顽。寄言飞白雪，休去打青山。",
            "倒打钱塘郭，长驱白浪花。吞吴休得也，输却五千家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 问渔叟 ----------
    {
        "id": "xu-ning-18",
        "title": "问渔叟",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "生事同漂梗，机心在野船。如何临逝水，白发未忘筌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 云封庵 ----------
    {
        "id": "xu-ning-19",
        "title": "云封庵",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "登岩背山河，立石秋风里。隐见浙江涛，一尺东沟水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 汉宫曲 ----------
    {
        "id": "xu-ning-20",
        "title": "汉宫曲",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "水色帘前流玉霜，赵家飞燕侍昭阳。",
            "掌中舞罢箫声绝，三十六宫秋夜长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 和嵩阳客月夜忆上清人 ----------
    {
        "id": "xu-ning-21",
        "title": "和嵩阳客月夜忆上清人",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "独夜嵩阳忆上仙，月明三十六峰前。",
            "瑶池月胜嵩阳月，人在玉清眠不眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 八月望夕雨 ----------
    {
        "id": "xu-ning-22",
        "title": "八月望夕雨",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "今年八月十五夜，寒雨萧萧不可闻。",
            "如练如霜在何处，吴山越水万重云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 观浙江涛 ----------
    {
        "id": "xu-ning-23",
        "title": "观浙江涛",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "浙江悠悠海西绿，惊涛日夜两翻覆。",
            "钱塘郭里看潮人，直至白头看不足。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 庐山瀑布 ----------
    {
        "id": "xu-ning-24",
        "title": "庐山瀑布",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "虚空落泉千仞直，雷奔入江不暂息。",
            "今古长如白练飞，一条界破青山色。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 嘉兴寒食 ----------
    {
        "id": "xu-ning-25",
        "title": "嘉兴寒食",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "嘉兴郭里逢寒食，落日家家拜扫回。",
            "唯有县前苏小小，无人送与纸钱来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 忆扬州 ----------
    {
        "id": "xu-ning-26",
        "title": "忆扬州",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "萧娘脸下难胜泪，桃叶眉头易得愁。",
            "天下三分明月夜，二分无赖是扬州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 八月灯夕寄游越施秀才 ----------
    {
        "id": "xu-ning-27",
        "title": "八月灯夕寄游越施秀才",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "四天净色寒如水，八月清辉冷似霜。",
            "想得越人今夜见，孟家珠在镜中央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 八月十五夜 ----------
    {
        "id": "xu-ning-28",
        "title": "八月十五夜",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "皎皎秋空八月圆，常娥端正桂枝鲜。",
            "一年无似如今夜，十二峰前看不眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 题伍员庙 ----------
    {
        "id": "xu-ning-29",
        "title": "题伍员庙",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "千载空祠云海头，夫差亡国已千秋。",
            "浙波只有灵涛在，拜奠青山人不休。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 员峤先生 ----------
    {
        "id": "xu-ning-30",
        "title": "员峤先生",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "员峤先生无白发，海烟深处采青芝。",
            "逢人借问陶唐主，欲进冰蚕五色丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 莫愁曲 ----------
    {
        "id": "xu-ning-31",
        "title": "莫愁曲",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "玳瑁床头刺战袍，碧纱窗外叶骚骚。",
            "若为教作辽西梦，月冷如丁风似刀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 寄白司马 ----------
    {
        "id": "xu-ning-32",
        "title": "寄白司马",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "三条九陌花时节，万户千车看牡丹。",
            "争遣江州白司马，五年风景忆长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 相思林 ----------
    {
        "id": "xu-ning-33",
        "title": "相思林",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "游客远游新过岭，每逢芳树问芳名。",
            "长林遍是相思树，争遣愁人独自行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 寄海峤丈人 ----------
    {
        "id": "xu-ning-34",
        "title": "寄海峤丈人",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "万丈只愁沧海浅，一身谁测岁华遥。",
            "自言来此云边住，曾看秦王树石桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 寄潘先生 ----------
    {
        "id": "xu-ning-35",
        "title": "寄潘先生",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "至人知姓不知名，闻道黄金骨节轻。",
            "世上仙方无觅处，欲来西岳事先生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 宫中曲二首 ----------
    {
        "id": "xu-ning-36",
        "title": "宫中曲二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "披香侍宴插山花，厌著龙绡著越纱。",
            "恃赖倾城人不及，檀妆唯约数条霞。",
            "身轻入宠尽恩私，腰细偏能舞柘枝。",
            "一日新妆抛旧样，六宫争画黑烟眉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 七夕 ----------
    {
        "id": "xu-ning-37",
        "title": "七夕",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "一道鹊桥横渺渺，千声玉佩过玲玲。",
            "别离还有经年客，怅望不如河鼓星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 八月九月望夕雨 ----------
    {
        "id": "xu-ning-38",
        "title": "八月九月望夕雨",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "八月繁云连九月，两回三五晦漫漫。",
            "一年怅望秋将尽，不得常娥正面看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 喜雪 ----------
    {
        "id": "xu-ning-39",
        "title": "喜雪",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "长爱谢家能咏雪，今朝见雪亦狂歌。",
            "杨花道即偷人句，不那杨花似雪何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 春饮 ----------
    {
        "id": "xu-ning-40",
        "title": "春饮",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "乌家若下蚁还浮，白玉尊前倒即休。",
            "不是春来偏爱酒，应须得酒遣春愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 二月望日 ----------
    {
        "id": "xu-ning-41",
        "title": "二月望日",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "长短一年相似夜，中秋未必胜中春。",
            "不寒不暖看明月，况是从来少睡人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 读远书 ----------
    {
        "id": "xu-ning-42",
        "title": "读远书",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "两转三回读远书，画檐愁见燕归初。",
            "百花时节教人懒，云髻朝来不欲梳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 古树 ----------
    {
        "id": "xu-ning-43",
        "title": "古树",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "古树欹斜临古道，枝不生花腹生草。",
            "行人不见树少时，树见行人几番老。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 独住僧 ----------
    {
        "id": "xu-ning-44",
        "title": "独住僧",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "百补袈裟一比丘，数茎长睫覆青眸。",
            "多应独住山林惯，唯照寒泉自剃头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 伤画松道芬上人（因画钓台江山而逝） ----------
    {
        "id": "xu-ning-45",
        "title": "伤画松道芬上人（因画钓台江山而逝）",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "百法驱驰百年寿，五劳消瘦五株松。",
            "昨来闻道严陵死，画到青山第几重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 观钓台画图 ----------
    {
        "id": "xu-ning-46",
        "title": "观钓台画图",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "一水寂寥青霭合，两崖崔崒白云残。",
            "画人心到啼猿破，欲作三声出树难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 荆巫梦思 ----------
    {
        "id": "xu-ning-47",
        "title": "荆巫梦思",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "楚水白波风袅袅，荆门暮色雨萧萧。",
            "相思合眼梦何处，十二峰高巴字遥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 浙东故孟尚书种柳 ----------
    {
        "id": "xu-ning-48",
        "title": "浙东故孟尚书种柳",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "孟家种柳东城去，临水逶迤思故人。",
            "不似当时大司马，重来得见汉南春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 长洲览古 ----------
    {
        "id": "xu-ning-49",
        "title": "长洲览古",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "吴王上国长洲奢，翠黛寒江一道斜。",
            "伤见摧残旧宫树，美人曾插九枝花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 却归旧山望月有寄 ----------
    {
        "id": "xu-ning-50",
        "title": "却归旧山望月有寄",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "年年明月总相似，大抵人情自不同。",
            "今夜故山依旧见，班家扇样碧峰东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 再归松溪旧居宿西林 ----------
    {
        "id": "xu-ning-51",
        "title": "再归松溪旧居宿西林",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "五粒松深溪水清，众山摇落月偏明。",
            "西林静夜重来宿，暗记人家犬吠声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 玩花五首 ----------
    {
        "id": "xu-ning-52",
        "title": "玩花五首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "一树梨花春向暮，雪枝残处怨风来。",
            "明朝渐校无多去，看到黄昏不欲回。",
            "麹尘溪上素红枝，影在溪流半落时。",
            "时人自惜花肠断，春风却是等闲吹。",
            "朱霞焰焰山枝动，绿野声声杜宇来。",
            "谁为蜀王身作鸟，自啼还自有花开。",
            "谁家踯躅青林里，半见殷花焰焰枝。",
            "忆得倡楼人送客，深红衫子影门时。",
            "花到蔷薇明艳绝，燕支颗破麦风秋。",
            "一番弄色一番退，小妇轻妆大妇愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 长庆春 ----------
    {
        "id": "xu-ning-53",
        "title": "长庆春",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "山头水色薄笼烟，久客新愁长庆年。",
            "身上五劳仍病酒，夭桃窗下背花眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 山鹧鸪词 ----------
    {
        "id": "xu-ning-54",
        "title": "山鹧鸪词",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "南越岭头山鹧鸪，传是当时守贞女。",
            "化为飞鸟怨何人，犹有啼声带蛮语。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 郑女出参丈人词 ----------
    {
        "id": "xu-ning-55",
        "title": "郑女出参丈人词",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "凤钗翠翘双宛转，出见丈人梳洗晚。",
            "掣曳罗绡跪拜时，柳条无力花枝软。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 春雨 ----------
    {
        "id": "xu-ning-56",
        "title": "春雨",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "花时闷见联绵雨，云入人家水毁堤。",
            "昨日春风源上路，可怜红锦枉抛泥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 和白使君木兰花 ----------
    {
        "id": "xu-ning-57",
        "title": "和白使君木兰花",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "枝枝转势雕弓动，片片摇光玉剑斜。",
            "见说木兰征戍女，不知那作酒边花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 正月十五夜呈幕中诸公 ----------
    {
        "id": "xu-ning-58",
        "title": "正月十五夜呈幕中诸公",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "宵游二万七千人，独坐重城圈一身。",
            "步月游山俱不得，可怜辜负白头春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 乐府新诗 ----------
    {
        "id": "xu-ning-59",
        "title": "乐府新诗",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "一声卢女十三弦，早嫁城西好少年。",
            "不羡越溪歌者苦，采莲归去绿窗眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 春陪相公看花宴会二首 ----------
    {
        "id": "xu-ning-60",
        "title": "春陪相公看花宴会二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "丞相邀欢事事同，玉箫金管咽东风。",
            "百分春酒莫辞醉，明日的无今日红。",
            "木兰花谢可怜条，远道音书转寂寥。",
            "春去一年春又尽，几回空上望江桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 牡丹 ----------
    {
        "id": "xu-ning-61",
        "title": "牡丹",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "何人不爱牡丹花，占断城中好物华。",
            "疑是洛川神女作，千娇万态破朝霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 过马当 ----------
    {
        "id": "xu-ning-62",
        "title": "过马当",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "风波隐隐石苍苍，送客灵鸦拂去樯。",
            "三月尽头云叶秀，小姑新著好衣裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 金谷览古 ----------
    {
        "id": "xu-ning-63",
        "title": "金谷览古",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "金谷园中数尺土，问人知是绿珠台。",
            "绿珠歌舞天下绝，唯与石家生祸胎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 上阳红叶 ----------
    {
        "id": "xu-ning-64",
        "title": "上阳红叶",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "洛下三分红叶秋，二分翻作上阳愁。",
            "千声万片御沟上，一片出宫何处流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 洛城秋砧 ----------
    {
        "id": "xu-ning-65",
        "title": "洛城秋砧",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "三川水上秋砧发，五凤楼前明月新。",
            "谁为秋砧明月夜，洛阳城里更愁人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 和川守侍郎缑山题仙庙 ----------
    {
        "id": "xu-ning-66",
        "title": "和川守侍郎缑山题仙庙",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "王子缑山石殿明，白家诗句咏吹笙。",
            "安知散席人间曲，不是寥天鹤上声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 和夜题玉泉寺 ----------
    {
        "id": "xu-ning-67",
        "title": "和夜题玉泉寺",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "岁岁云山玉泉寺，年年车马洛阳尘。",
            "风清月冷水边宿，诗好官高能几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 和秋游洛阳 ----------
    {
        "id": "xu-ning-68",
        "title": "和秋游洛阳",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "洛阳自古多才子，唯爱春风烂漫游。",
            "今到白家诗句出，无人不咏洛阳秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 和嘲春风 ----------
    {
        "id": "xu-ning-69",
        "title": "和嘲春风",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "源上拂桃烧水发，江边吹杏暗园开。",
            "可怜半死龙门树，懊恼春风作底来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 侍郎宅泛池 ----------
    {
        "id": "xu-ning-70",
        "title": "侍郎宅泛池",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "莲子花边回竹岸，鸡头叶上荡兰舟。",
            "谁知洛北朱门里，便到江南绿水游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 和侍郎邀宿不至 ----------
    {
        "id": "xu-ning-71",
        "title": "和侍郎邀宿不至",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "蟾蜍有色门应锁，街鼓无声夜自深。",
            "料得白家诗思苦，一篇诗了一弹琴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 自鄂渚至河南将归江外留辞侍郎 ----------
    {
        "id": "xu-ning-72",
        "title": "自鄂渚至河南将归江外留辞侍郎",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "一生所遇唯元白，天下无人重布衣。",
            "欲别朱门泪先尽，白头游子白身归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 蛮入西川后 ----------
    {
        "id": "xu-ning-73",
        "title": "蛮入西川后",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "守隘一夫何处在，长桥万里只堪伤。",
            "纷纷塞外乌蛮贼，驱尽江头濯锦娘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 忆紫溪 ----------
    {
        "id": "xu-ning-74",
        "title": "忆紫溪",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "长忆紫溪春欲尽，千岩交映水回斜。",
            "岩空水满溪自紫，水态更笼南烛花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 夸红槿 ----------
    {
        "id": "xu-ning-75",
        "title": "夸红槿",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "谁道槿花生感促，可怜相计半年红。",
            "何如桃李无多少，并打千枝一夜风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 题缙云山鼎池二首 ----------
    {
        "id": "xu-ning-76",
        "title": "题缙云山鼎池二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "黄帝旌旗去不回，空馀片石碧崔嵬。",
            "有时风卷鼎湖浪，散作晴天雨点来。",
            "天地茫茫成古今，仙都凡有几人寻。",
            "到来唯见山高下，只是不知湖浅深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 宿冽上人房 ----------
    {
        "id": "xu-ning-77",
        "title": "宿冽上人房",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "浮生不定若蓬飘，林下真僧偶见招。",
            "觉后始知身是梦，更闻寒雨滴芭蕉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 汴河览古 ----------
    {
        "id": "xu-ning-78",
        "title": "汴河览古",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "炀帝龙舟向此行，三千宫女采桡轻。",
            "渡河不似如今唱，为是杨家怨思声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 柬白丈人 ----------
    {
        "id": "xu-ning-79",
        "title": "柬白丈人",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "昔时丈人鬓发白，千年松下锄茯苓。",
            "今来见此松树死，丈人斩新鬓发青。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 览镜词 ----------
    {
        "id": "xu-ning-80",
        "title": "览镜词",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "宝镜磨来寒水清，青衣把就绿窗明。",
            "潘郎懊恼新秋发，拔却一茎生两茎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 寄玄阳先生 ----------
    {
        "id": "xu-ning-81",
        "title": "寄玄阳先生",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "不能相见见人传，rv岸山中岱岸边。",
            "颜貌只如三二十，道年三百亦藏年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 白人 ----------
    {
        "id": "xu-ning-82",
        "title": "白人",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "暖风入烟花漠漠，白人梳洗寻常薄。",
            "泥郎为插珑璁钗，争教一朵牙云落。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 奉酬元相公上元 ----------
    {
        "id": "xu-ning-83",
        "title": "奉酬元相公上元",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "出拥楼船千万人，入为台辅九霄身。",
            "如何更羡看灯夜，曾见宫花拂面春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 奉和鹦鹉 ----------
    {
        "id": "xu-ning-84",
        "title": "奉和鹦鹉",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "毛羽曾经翦处残，学人言语道暄寒。",
            "任饶长被金笼阖，也免栖飞雨雪难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 将至妙喜寺 ----------
    {
        "id": "xu-ning-85",
        "title": "将至妙喜寺",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "清风袅袅越水陂，远树苍苍妙喜寺。",
            "自有车轮与马蹄，未曾到此波心地。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 红蕉 ----------
    {
        "id": "xu-ning-86",
        "title": "红蕉",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "红蕉曾到岭南看，校小芭蕉几一般。",
            "差是斜刀剪红绢，卷来开去叶中安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 见少室 ----------
    {
        "id": "xu-ning-87",
        "title": "见少室",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "适我一箪孤客性，问人三十六峰名。",
            "青云无忘白云在，便可嵩阳老此生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 语儿见新月 ----------
    {
        "id": "xu-ning-88",
        "title": "语儿见新月",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "几处天边见新月，经过草市忆西施。",
            "娟娟水宿初三夜，曾伴愁蛾到语儿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 回施先辈见寄新诗二首 ----------
    {
        "id": "xu-ning-89",
        "title": "回施先辈见寄新诗二首",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "九幽仙子西山卷，读了绦绳系又开。",
            "此卷玉清宫里少，曾寻真诰读诗来。",
            "紫河车里丹成也，皂荚枝头早晚飞。",
            "料得仙宫列仙籍，如君进士出身稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 送沈亚之赴郢掾 ----------
    {
        "id": "xu-ning-90",
        "title": "送沈亚之赴郢掾",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "千万乘骢沈司户，不须惆怅郢中游。",
            "几年白雪无人唱，今日唯君上雪楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 答白公 ----------
    {
        "id": "xu-ning-91",
        "title": "答白公",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "高景争来草木头，一生心事酒前休。",
            "山公自是仙人侣，携手醉登城上楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 句 ----------
    {
        "id": "xu-ning-92",
        "title": "句",
        "author": "徐凝",
        "poet_id": "xu-ning",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "青山旧路在，白首醉还乡。（《别白公》）",
            "试到第三桥，便入千顷花。（以上并见《纪事》）",
            "乱后见淮水，归心忽迢遥。（《京都还汴口作》）",
            "乍疑鲸喷浪，忽似鹢凌风。呀呷汀洲动，喧阗里巷空。",
            "（《竞渡》。见《诗式》）",
            "第四百七十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]