# -*- coding: utf-8 -*-
"""
费冠卿卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 10 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 不赴拾遗召 ----------
    {
        "id": "fei-guan-qing-1",
        "title": "不赴拾遗召",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "君亲同是先王道，何如骨肉一处老。",
            "也知臣子合佐时，自古荣华谁可保。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 闲居即事 ----------
    {
        "id": "fei-guan-qing-2",
        "title": "闲居即事",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "生计唯将三尺僮，学他贤者隐墙东。照眠夜后多因月，",
            "扫地春来只藉风。几处红旗驱战士，一园青草伴衰翁。",
            "子房仙去孔明死，更有何人解指踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 酬范中丞见 ----------
    {
        "id": "fei-guan-qing-3",
        "title": "酬范中丞见",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "花宫柳陌正从行，紫袂金鞍问姓名。战国方须礼干木，",
            "康时何必重侯嬴。捧将束帛山僮喜，传示银钩邑客惊。",
            "直为云泥相去远，一言知己杀身轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 秋日与冷然上人寺庄观稼 ----------
    {
        "id": "fei-guan-qing-4",
        "title": "秋日与冷然上人寺庄观稼",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "世人从扰扰，独自爱身闲。美景当新霁，随僧过远山。",
            "村桥出秋稼，空翠落澄湾。唯有中林犬，犹应望我还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题中峰 ----------
    {
        "id": "fei-guan-qing-5",
        "title": "题中峰",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "中峰高拄泬寥天，上有茅庵与石泉。",
            "晴景猎人曾望见，青蓝色里一僧禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 蒙召拜拾遗书情二首 ----------
    {
        "id": "fei-guan-qing-6",
        "title": "蒙召拜拾遗书情二首",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "拾遗帝侧知难得，官紧才微恐不胜。",
            "好是中朝绝亲友，九华山下诏来征。",
            "三千里外一微臣，二十年来任运身。",
            "今日忽蒙天子召，自惭惊动国中人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 挂树藤 ----------
    {
        "id": "fei-guan-qing-7",
        "title": "挂树藤",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "本为独立难，寄彼高树枝。蔓衍数条远，溟濛千朵垂。",
            "向日助成阴，当风藉持危。谁言柔可屈，坐见蟠蛟螭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 枕流石 ----------
    {
        "id": "fei-guan-qing-8",
        "title": "枕流石",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "不为幽岸隐，古色涵空出。愿以清泚流，鉴此坚贞质。",
            "傍临玉光润，时泻苔花密。往往惊游鳞，尚疑垂钓日。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 久居京师感怀诗 ----------
    {
        "id": "fei-guan-qing-9",
        "title": "久居京师感怀诗",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "茕独不为苦，求名始辛酸。上国无交亲，请谒多少难。",
            "九月风到面，羞汗成冰片。求名俟公道，名与公道远。",
            "力尽得一名，他喜我且轻。家书十年绝，归去知谁荣。",
            "马嘶渭桥柳，特地起秋声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 答萧建 ----------
    {
        "id": "fei-guan-qing-10",
        "title": "答萧建",
        "author": "费冠卿",
        "poet_id": "fei-guan-qing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "自地上青峰，悬崖一万重。践危频侧足，登堑半齐胸。",
            "飞狖啼攀桂，游人喘倚松。入林寒z9々，近瀑雨濛濛。",
            "径滑石棱上，寺开山掌中。幡花扑净地，台殿印晴空。",
            "胜境层层别，高僧院院逢。泉鱼候洗钵，老玃戏撞钟。",
            "外户凭云掩，中厨课水舂。搜泥时和面，拾橡半添穜。",
            "渡壑缘槎险，持灯入洞穷。夹天开壁峭，透石蹙波雄。",
            "润蔼清无土，潭深碧有龙。畬田一片净，谷树万株浓。",
            "野客登临惯，山房幽寂同。寒炉树根火，夏牖竹稍风。",
            "边鄙筹贤相，黔黎托圣躬。君能弃名利，岁晏一相从。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]