# -*- coding: utf-8 -*-
"""
李洞卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 168 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 赠唐山人 ----------
    {
        "id": "li-dong-1",
        "title": "赠唐山人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "垂须长似发，七十色如黳。醉眼青天小，吟情太华低。",
            "千年松绕屋，半夜雨连溪。邛蜀路无限，往来琴独携。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送云卿上人游安南（一作送僧游南海） ----------
    {
        "id": "li-dong-2",
        "title": "送云卿上人游安南（一作送僧游南海）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "春往海南边，秋闻半夜蝉。鲸吞洗钵水，犀触点灯船。",
            "岛屿分诸国，星河共一天。长安却回日，松偃旧房前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 郑补阙山居 ----------
    {
        "id": "li-dong-3",
        "title": "郑补阙山居",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "高节谏垣客，白云居静坊。马饥餐落叶，鹤病晒残阳。",
            "野雾昏朝烛，溪笺惹御香。相招倚蒲壁，论句夜何长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送曹郎中南归，时南中用军 ----------
    {
        "id": "li-dong-4",
        "title": "送曹郎中南归，时南中用军",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "桂水净和天，南归似谪仙。系绦轻象笏，买布接蛮船。",
            "海气蒸鼙软，江风激箭偏。罢郎吟乱里，帝远岂知贤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 锦江陪兵部郑侍郎话诗著棋 ----------
    {
        "id": "li-dong-5",
        "title": "锦江陪兵部郑侍郎话诗著棋",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "落叶溅吟身，会棋云外人。海枯搜不尽，天定著长新。",
            "月上分题遍，钟残布子匀。忘餐二绝境，取意铸陶钧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 中秋月 ----------
    {
        "id": "li-dong-6",
        "title": "中秋月",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "四十五秋宵，月分千里毫。冷沉中岳短，光溢太行高。",
            "不寐清人眼，移栖湿鹤毛。露华台上别，吟望十年劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送沈光赴福幕（一作送福州从事） ----------
    {
        "id": "li-dong-7",
        "title": "送沈光赴福幕（一作送福州从事）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "泉齐岭鸟飞，雨熟荔枝肥。南斗看应近，北人来恐稀。",
            "潮浮廉使宴，珠照岛僧归。幕下逢迁拜，何官着茜衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 鄠郊山舍题赵处士林亭 ----------
    {
        "id": "li-dong-8",
        "title": "鄠郊山舍题赵处士林亭",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "圭峰秋后叠，乱叶落寒墟。四五百竿竹，二三千卷书。",
            "云深猿拾栗，雨霁蚁缘蔬。只隔门前水，如同万里馀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 赋得送贾岛谪长江 ----------
    {
        "id": "li-dong-9",
        "title": "赋得送贾岛谪长江",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "敲驴吟雪月，谪出国西门。行傍长江影，愁深汨水魂。",
            "筇携过竹寺，琴典在花村。饥拾山松子，谁知贾傅孙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 河阳道中 ----------
    {
        "id": "li-dong-10",
        "title": "河阳道中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "冲风仍蹑冻，提辔手频呵。得事应须早，愁人不在多。",
            "雪田平入塞，烟郭曲随河。翻忆江涛里，船中睡盖蓑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送知己赴濮州 ----------
    {
        "id": "li-dong-11",
        "title": "送知己赴濮州",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "中路行僧谒，邮亭话海涛。剑摇林狖落，旗闪岳禽高。",
            "苔长空州狱，花开梦省曹。濮阳流政化，一半布风骚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送行脚僧 ----------
    {
        "id": "li-dong-12",
        "title": "送行脚僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "瓶枕绕腰垂，出门何所之。毳衣沾雨重，棕笠看山欹。",
            "夜观入枯树，野眠逢断碑。邻房母泪下，相课别离词。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 龙州送人赴举 ----------
    {
        "id": "li-dong-13",
        "title": "龙州送人赴举",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "献策赴招携，行宫积翠西。挈囊秋卷重，转栈晚峰齐。",
            "踏月趋金阙，拂云看御题。飞鸣岂回顾，独鹤困江泥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 送安抚从兄夷偶中丞 ----------
    {
        "id": "li-dong-14",
        "title": "送安抚从兄夷偶中丞",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "奉诏向军前，朱袍映雪鲜。河桥吹角冻，岳月卷旗圆。",
            "僧救焚经火，人修著钓船。六州安抚后，万户解衣眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送远上人 ----------
    {
        "id": "li-dong-15",
        "title": "送远上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "海岳两无边，去来都偶然。齿因吟后冷，心向静中圆。",
            "虫网花间井，鸿鸣雨后天。叶书归旧寺，应附载钟船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 宿凤翔天柱寺穷易玄上人房 ----------
    {
        "id": "li-dong-16",
        "title": "宿凤翔天柱寺穷易玄上人房",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "天柱暮相逢，吟思天柱峰。墨研青露月，茶吸白云钟。",
            "卧语身粘藓，行禅顶拂松。探玄为一决，明日去临邛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 下第送张霞归觐江南 ----------
    {
        "id": "li-dong-17",
        "title": "下第送张霞归觐江南",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "此道背于时，携归一轴诗。树沈孤鸟远，风逆蹇驴迟。",
            "草入吟房坏，潮冲钓石移。恐伤欢觐意，半路摘愁髭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送人之天台 ----------
    {
        "id": "li-dong-18",
        "title": "送人之天台",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "行李一枝藤，云边晓扣冰。丹经如不谬，白发亦何能。",
            "浅井仙人境，明珠海客灯。乃知真隐者，笑就汉廷征。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 维摩畅林居（一作题维摩畅上人房） ----------
    {
        "id": "li-dong-19",
        "title": "维摩畅林居（一作题维摩畅上人房）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "诸方游几腊，五夏五峰销。越讲迎骑象，蕃斋忏射雕。",
            "冷筇和雪倚，朽栎带云烧。从此西林老，瞥然三万朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送张乔下第归宣州 ----------
    {
        "id": "li-dong-20",
        "title": "送张乔下第归宣州",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "诗道世难通，归宁楚浪中。早程残岳月，夜泊隔淮钟。",
            "一镜随双鬓，全家老半峰。无成来往过，折尽谢亭松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送卢郎中赴金州 ----------
    {
        "id": "li-dong-21",
        "title": "送卢郎中赴金州",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "云明天岭高，刺郡辍仙曹。危栈窥猿顶，公庭扫鹤毛。",
            "出军青壁罅，话道白眉毫。远集歌谣客，州前泊几艘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 江干即事 ----------
    {
        "id": "li-dong-22",
        "title": "江干即事",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "病卧四更后，愁闻报早衙。隔关沈水鸟，侵郭噪园鸦。",
            "吏瘦餐溪柏，身羸凭海槎。满朝吟五字，应不老烟霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 寄贺郑常侍 ----------
    {
        "id": "li-dong-23",
        "title": "寄贺郑常侍",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "山亦怀恩地，高禽尽下飞。吏穿霞片望，僧扫月棱归。",
            "省拜墀烟近，林居玉漏微。曾令驻锡话，聊用慰攀依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 登楼 ----------
    {
        "id": "li-dong-24",
        "title": "登楼",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "川上值楼开，寒山四面来。竹吹人语远，峰碍鸟飞回。",
            "生死别离陌，朝昏云雨堆。谁知独立意，溅泪落莓苔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 赠禅友 ----------
    {
        "id": "li-dong-25",
        "title": "赠禅友",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "散花留内殿，宫女梦谈禅。树杪开楼锁，云中认岳莲。",
            "溪声过长耳，筇节出羸肩。飞句相招宿，多逢有月天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 早春友人访别南归 ----------
    {
        "id": "li-dong-26",
        "title": "早春友人访别南归",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "南归来取别，穷巷坐青苔。一盏薄醨酒，数枝零落梅。",
            "潮生楚驿闭，星在越楼开。明日望君处，前临风月台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 题云际寺 ----------
    {
        "id": "li-dong-27",
        "title": "题云际寺",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "开门风雪顶，上彻困飞禽。猿戏青冥里，人行紫阁阴。",
            "腊泉冰下出，夜磬月中寻。尽欲居岩室，如何不住心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 山寺老僧 ----------
    {
        "id": "li-dong-28",
        "title": "山寺老僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "云际众僧里，独攒眉似愁。护茶高夏腊，爱火老春秋。",
            "海浪南曾病，河冰北苦游。归来诸弟子，白遍后生头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 同僧宿道者院 ----------
    {
        "id": "li-dong-29",
        "title": "同僧宿道者院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "携文过水宿，拂席四廊尘。坠果敲楼瓦，高萤映鹤身。",
            "点灯吹叶火，谈佛悟山人。尽有栖霞志，好谋三教邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 古柏 ----------
    {
        "id": "li-dong-30",
        "title": "古柏",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "手植知何代，年齐偃盖松。结根生别树，吹子落邻峰。",
            "古干经龙嗅，高烟过雁冲。可佳繁叶尽，声不碍秋钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 赠王凤二山人 ----------
    {
        "id": "li-dong-31",
        "title": "赠王凤二山人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "山兄望鹤信，山弟听乌占。养药同开鼎，休棋各枕奁。",
            "相逢九江底，共到五峰尖。愿许为三友，羞将白发撏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 避地冬夜与二三禅侣吟集茅斋 ----------
    {
        "id": "li-dong-32",
        "title": "避地冬夜与二三禅侣吟集茅斋",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "四海通禅客，搜吟会草亭。撚髭孤烛白，闭目众山青。",
            "松挂敲冰杖，垆温注月瓶。独愁悬旧旆，笏冷立残星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 赠道微禅师 ----------
    {
        "id": "li-dong-33",
        "title": "赠道微禅师",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "铜瓶涩泻水，出碛蹑莲层。猛虎降低鼠，盘雕望小蝇。",
            "通禅五天日，照祖几朝灯。短发归林白，何妨剃未能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 吊草堂禅师 ----------
    {
        "id": "li-dong-34",
        "title": "吊草堂禅师",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "杖屦疑师在，房关四壁蛩。贮瓶经腊水，响塔隔山钟。",
            "乳鸽沿苔井，斋猿散雪峰。如何不见性，倚遍寺前松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 宿长安苏雍主簿厅 ----------
    {
        "id": "li-dong-35",
        "title": "宿长安苏雍主簿厅",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "县对数峰云，官清主簿贫。听更池上鹤，伴值岳阳人。",
            "井锁煎茶水，厅关捣药尘。往来多屣步，同舍即诸邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 秋宿润州刘处士江亭 ----------
    {
        "id": "li-dong-36",
        "title": "秋宿润州刘处士江亭",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "北梦风吹断，江边处士亭。吟生万井月，见尽一天星。",
            "浪静鱼冲锁，窗高鹤听经。东西渺无际，世界半沧溟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 秋日曲江书事 ----------
    {
        "id": "li-dong-37",
        "title": "秋日曲江书事",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "门摇枯苇影，落日共鸥归。园近鹿来熟，江寒人到稀。",
            "片云穿塔过，枯叶入城飞。翻怕宾鸿至，无才动礼闱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 秋宿经上人房 ----------
    {
        "id": "li-dong-38",
        "title": "秋宿经上人房",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "江房无叶落，松影带山高。满寺中秋月，孤窗入夜涛。",
            "旧真悬石壁，衰发落铜刀。卧听晓耕者，与师知苦劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 冬日题觉公牛头兰若 ----------
    {
        "id": "li-dong-39",
        "title": "冬日题觉公牛头兰若",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "天寒高木静，一磬隔川闻。鼎水看山汲，台香扫雪焚。",
            "鹤归惟认刹，僧步不离云。石室开禅后，轮珠谢圣君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 送皇甫校书自蜀下峡，归觐襄阳 ----------
    {
        "id": "li-dong-40",
        "title": "送皇甫校书自蜀下峡，归觐襄阳",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "蜀道波不竭，巢乌出浪痕。松阴盖巫峡，雨色彻荆门。",
            "宿寺青山尽，归林彩服翻。苦吟怀冻馁，为吊浩然魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 题西明寺攻文僧林复上人房 ----------
    {
        "id": "li-dong-41",
        "title": "题西明寺攻文僧林复上人房",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "谁寄湘南信，阴窗砚起津。烧痕碑入集，海角寺留真。",
            "楼憩长空鸟，钟惊半阙人。御沟圆月会，似在草堂身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 寄翠微无可上人（一作无学禅师） ----------
    {
        "id": "li-dong-42",
        "title": "寄翠微无可上人（一作无学禅师）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "远近众心归，居然占翠微。展经猿识字，听法虎知非。",
            "泉注城池梦，霞生侍卫衣。玄机不可学，何似总无机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 喜鸾公自蜀归 ----------
    {
        "id": "li-dong-43",
        "title": "喜鸾公自蜀归",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "禁院对生台，寻师到绿槐。寺高猿看讲，钟动鸟知斋。",
            "扫石月盈帚，滤泉花满筛。归来逢圣节，吟步上尧阶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 题新安国寺 ----------
    {
        "id": "li-dong-44",
        "title": "题新安国寺",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "佛亦遇艰难，重兴叠废坛。偃松枝旧折，画竹粉新干。",
            "开讲宫娃听，抛生禁鸟餐。钟声入帝梦，天竺化长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 蕃寇侵逼，南归道中 ----------
    {
        "id": "li-dong-45",
        "title": "蕃寇侵逼，南归道中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "云州三万骑，南走疾飞鹰。回碛星低雁，孤城月伴僧。",
            "敲关通汉节，倾府守河冰。无处论边事，归溪夜结罾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送东宫贾正字之蜀 ----------
    {
        "id": "li-dong-46",
        "title": "送东宫贾正字之蜀",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "南朝献晋史，东蜀瞰巴楼。长栈怀宫树，疏峰露剑州。",
            "半空飞雪化，一道白云流。若次江边邑，宗诗为遍搜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 吊侯圭常侍 ----------
    {
        "id": "li-dong-47",
        "title": "吊侯圭常侍",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "我重君能赋，君褒我解诗。三堂一拜遇，四海两心知。",
            "影挂僧挑烛，名传鹤拂碑。涪江吊孤冢，片月下峨嵋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 颜上人房（一作题西明自觉上人房） ----------
    {
        "id": "li-dong-48",
        "title": "颜上人房（一作题西明自觉上人房）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "御沟临岸行，远岫见云生。松下度三伏，磬中销五更。",
            "雨淋经阁白，日闪剃刀明。海畔终须去，烧灯老国清。",
            "第七百二十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 题薛少府庄 ----------
    {
        "id": "li-dong-49",
        "title": "题薛少府庄",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "何须凿井饮，门占古溪居。寂寞苔床卧，寒虚玉柄书。",
            "有期登白阁，又得赏红蕖。清浅蒲根水，时看鹭啄鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 寄太白隐者 ----------
    {
        "id": "li-dong-50",
        "title": "寄太白隐者",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "开辟已来雪，为山长欠春。高遮辞碛雁，寒噤入川人。",
            "栈阁交冰柱，耕樵隔日轮。此中栖息者，不识两京尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 秋宿青龙禅阁 ----------
    {
        "id": "li-dong-51",
        "title": "秋宿青龙禅阁",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "前山不可望，暮色渐沉规。日转须弥北，蟾来渤海西。",
            "风铃乱僧语，霜枿欠猿啼。阁外千家月，分明见里迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 登圭峰旧隐寄荐福栖白上人 ----------
    {
        "id": "li-dong-52",
        "title": "登圭峰旧隐寄荐福栖白上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "返照塔轮边，残霖滴几悬。夜寒吟病甚，秋健讲声圆。",
            "粟穗干灯焰，苔根浊水泉。西峰埋藓石，秋月即师禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 将之蜀别友人 ----------
    {
        "id": "li-dong-53",
        "title": "将之蜀别友人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "嘉陵雨色青，澹别酌参苓。到蜀高诸岳，窥天合四溟。",
            "书来应隔雪，梦觉已无星。若遇多吟友，何妨勘竺经。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 吊膳曹从叔郎中 ----------
    {
        "id": "li-dong-54",
        "title": "吊膳曹从叔郎中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "华省支残俸，寒蔬办祭稀。安坟对白阁，买石折朱衣。",
            "蜀客弹琴哭，江鸥入宅飞。帆吹佳句远，不独遍王畿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 乱后龙州送郑郎中兼寄郑侍御 ----------
    {
        "id": "li-dong-55",
        "title": "乱后龙州送郑郎中兼寄郑侍御",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "待车登叠嶂，经乱集鴒原。省坏兰终洁，台寒柏有根。",
            "县清江入峡，楼静雪连村。莫隐匡山社，机云受晋恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 段秀才溪居送从弟游泾陇 ----------
    {
        "id": "li-dong-56",
        "title": "段秀才溪居送从弟游泾陇",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "抱疾寒溪卧，因循草木青。相留开夏蜜，辞去见秋萤。",
            "朔雪痕侵雍，边烽焰照泾。烟沈陇山色，西望涕交零。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 题刘相公光德里新构茅亭 ----------
    {
        "id": "li-dong-57",
        "title": "题刘相公光德里新构茅亭",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "野色迷亭晓，龙墀待押班。带涎移海木，兼雪写湖山。",
            "月白吟床冷，河清直印闲。唐封三万里，人偃翠微间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 江峡寇乱寄怀吟僧 ----------
    {
        "id": "li-dong-58",
        "title": "江峡寇乱寄怀吟僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "半锡探寒流，别师猿鹤洲。二三更后雨，四十字边秋。",
            "立塞吟霞石，敲鼙看雪楼。扶亲何处隐，惊梦入嵩丘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 贺昭国从叔员外转本曹郎中 ----------
    {
        "id": "li-dong-59",
        "title": "贺昭国从叔员外转本曹郎中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "苔砌塔阴浓，朝回尚叫蛩。粟征山县欠，官转水曹重。",
            "灯照楼中雨，书求海上峰。诗家无骤显，一一古人踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 赠宋校书 ----------
    {
        "id": "li-dong-60",
        "title": "赠宋校书",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "曾伴元戎猎，寒来梦北军。闲身不计日，病鹤放归云。",
            "石上铺棋势，船中赌酒分。长言买天姥，高卧谢人群。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 越公上人洛中归寄南孟家兄弟 ----------
    {
        "id": "li-dong-61",
        "title": "越公上人洛中归寄南孟家兄弟",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "洛下因归去，关西忆二龙。笠漫河岸雪，衣着虢城钟。",
            "睡鸭浮寒水，樵人出远峰。何当化闾俗，护取草堂松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 龙州送裴秀才 ----------
    {
        "id": "li-dong-62",
        "title": "龙州送裴秀才",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "违拜旆旗前，松阴路半千。楼冲高雪会，驿闭乱云眠。",
            "榜挂临江省，名题赴宅筵。人求新蜀赋，应贵浣花笺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 题慈恩友人房 ----------
    {
        "id": "li-dong-63",
        "title": "题慈恩友人房",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "贾生耽此寺，胜事入诗多。鹤宿星千树，僧归烧一坡。",
            "塔棱垂雪水，江色映茶锅。长久堪栖息，休言忆镜波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 寄窦禅山薛秀才 ----------
    {
        "id": "li-dong-64",
        "title": "寄窦禅山薛秀才",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "窦岭吟招隐，新诗满集贤。白衫春絮暖，红纸夏云鲜。",
            "琴缠江丝细，棋分海石圆。因知醉公子，虚写世人传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 西蜀与崔先生话东洛旧游 ----------
    {
        "id": "li-dong-65",
        "title": "西蜀与崔先生话东洛旧游",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "王屋峭难名，三刀梦四更。日升当地缺，星尽未天明。",
            "度雪云林湿，穿松角韵清。崔家开锦浪，忆着水窗声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 上昭国水部从叔郎中 ----------
    {
        "id": "li-dong-66",
        "title": "上昭国水部从叔郎中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "极南极北游，东泛复西流。行匝中华地，魂销四海秋。",
            "题诗在琼府，附舶出青州。不遇一公子，弹琴吊古丘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 题玉芝赵尊师院 ----------
    {
        "id": "li-dong-67",
        "title": "题玉芝赵尊师院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "晓起磬房前，真经诵百篇。漱流星入齿，照镜石差肩。",
            "静闭街西观，存思海上仙。闲听说五岳，穷遍一根莲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 送卢少府之任巩洛 ----------
    {
        "id": "li-dong-68",
        "title": "送卢少府之任巩洛",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "从知东甸尉，铨注似恩除。带土移嵩术，和泉送尹鱼。",
            "印床寒鹭宿，壁记醉僧书。堂下诸昆在，无妨候起居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 送人归觐河中 ----------
    {
        "id": "li-dong-69",
        "title": "送人归觐河中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "青门冢前别，道路武关西。有寺云连石，无僧叶满溪。",
            "河长随鸟尽，山远与人齐。觐省波涛县，寒窗响曙鸡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 锦城秋寄怀弘播上人 ----------
    {
        "id": "li-dong-70",
        "title": "锦城秋寄怀弘播上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "极顶云兼冻，孤城露洗初。共辞嵩少雪，久绝贝多书。",
            "远照雁行细，寒条狖挂虚。分泉煎月色，忆就茗林居。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 圭峰溪居寄怀韦曲曹秀才 ----------
    {
        "id": "li-dong-71",
        "title": "圭峰溪居寄怀韦曲曹秀才",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "南北飞山雪，万片寄相思。东西曲流水，千声泻别离。",
            "巴猿学导引，陇鸟解吟诗。翻羡家林赏，世人那得知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 送舍弟之山南 ----------
    {
        "id": "li-dong-72",
        "title": "送舍弟之山南",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "南山入谷游，去彻山南州。下马云未尽，听猿星正稠。",
            "印茶泉绕石，封国角吹楼。远宦有何兴，贫兄无计留。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 题南鉴公山房 ----------
    {
        "id": "li-dong-73",
        "title": "题南鉴公山房",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "竹房开处峭，迥挂半山灯。石磬敲来穴，不知何代僧。",
            "讲归双袖雪，禅起一盂冰。唯说黄桑屐，当时着秣陵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 送知己 ----------
    {
        "id": "li-dong-74",
        "title": "送知己",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "郡清官舍冷，枕席溅山泉。药气来人外，灯光到鹤边。",
            "梦秦书印斗，思越画渔船。掷笏南归去，波涛路几千。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 送人赴职湘潭 ----------
    {
        "id": "li-dong-75",
        "title": "送人赴职湘潭",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "南征虽赴辟，其奈负高科。水合湘潭住，山分越国多。",
            "梅花雪共下，文□□相和。白发陪官宴，红旗影里歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 过野叟居 ----------
    {
        "id": "li-dong-76",
        "title": "过野叟居",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "野人居止处，竹色与山光。留客羞蔬饭，洒泉开草堂。",
            "雨馀松子落，风过朮苗香。尽日无炎暑，眠君青石床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 吊郑宾客 ----------
    {
        "id": "li-dong-77",
        "title": "吊郑宾客",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "朝行丧名节，岳色惨天风。待漏秋吟断，焚香夜直空。",
            "骨寒依垄草，家尽逐边鸿。一吊知音后，归来碎峄桐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 送从叔书记山阴隐居 ----------
    {
        "id": "li-dong-78",
        "title": "送从叔书记山阴隐居",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "山顶绝茅居，云泉绕枕虚。烧移僧影瘦，风展鹭行疏。",
            "卷箔清江月，敲松紫阁书。由来簪组贵，不信教猿锄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 避暑庄严禅院 ----------
    {
        "id": "li-dong-79",
        "title": "避暑庄严禅院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "定里无烦热，吟中达性情。入林逢客话，上塔接僧行。",
            "八水皆知味，诸翁尽得名。常论冰井近，莫便厌浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 寄清演 ----------
    {
        "id": "li-dong-80",
        "title": "寄清演",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "忽闻清演病，可料苦吟身。不见近诗久，徒言华发新。",
            "别来山已破，住处月为邻。几绕庭前树，于今四十春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 迁村居二首 ----------
    {
        "id": "li-dong-81",
        "title": "迁村居二首",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "移居入村宇，树阙见城隍。云水虽堪画，恩私不可忘。",
            "猿涎滴鹤氅，麈尾拂僧床。弃逐随樵牧，何由报稻粱。",
            "歌乐听常稀，茅亭静掩扉。槎来垂钓次，月落问安归。",
            "远客传烧研，幽禽看衲衣。眼前无俗事，松雨蜀山辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 出山睹春榜 ----------
    {
        "id": "li-dong-82",
        "title": "出山睹春榜",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "未老鬓毛焦，心归向石桥。指霞辞二纪，吟雪遇三朝。",
            "连席频登相，分廊尚祝尧。回眸旧行侣，免使负嵩樵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 贾岛墓 ----------
    {
        "id": "li-dong-83",
        "title": "贾岛墓",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "一第人皆得，先生岂不销。位卑终蜀士，诗绝占唐朝。",
            "旅葬新坟小，魂归故国遥。我来因奠洒，立石用为标。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 观水墨障子 ----------
    {
        "id": "li-dong-84",
        "title": "观水墨障子",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "若非神助笔，砚水恐藏龙。研尽一寸墨，扫成千仞峰。",
            "壁根堆乱石，床罅插枯松。岳麓穿因鼠，湘江绽为蛩。",
            "挂衣岚气湿，梦枕浪头舂。只为少颜色，时人著意慵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 对棋 ----------
    {
        "id": "li-dong-85",
        "title": "对棋",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "小槛明高雪，幽人斗智棋。日斜抛作劫，月午蹙成迟。",
            "倚杖湘僧算，翘松野鹤窥。侧楸敲醒睡，片石夹吟诗。",
            "雨点奁中渍，灯花局上吹。秋涛寒竹寺，此兴谢公知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 题竹溪禅院 ----------
    {
        "id": "li-dong-86",
        "title": "题竹溪禅院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "溪边山一色，水拥竹千竿。鸟触翠微湿，人居酷暑寒。",
            "风摇瓶影碎，沙陷履痕端。爽极青崖树，平流绿峡滩。",
            "闲来披衲数，涨后卷经看。三境通禅寂，嚣尘染著难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 投献吏部张侍郎十韵 ----------
    {
        "id": "li-dong-87",
        "title": "投献吏部张侍郎十韵",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "苔染马蹄青，何曾似在城。不于僧院宿，多傍御沟行。",
            "隐岫侵巴叠，租田带渭平。肩囊寻省寺，袖轴遍公卿。",
            "梦入连涛郡，书来积雪营。泪随边雁堕，魂逐夜蝉惊。",
            "发愤巡江塔，无眠数县更。玄都一病客，兴善几回莺。",
            "贡艺披沙细，酬恩戴岳轻。心期公子念，滴酒在雕楹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 终南山二十韵 ----------
    {
        "id": "li-dong-88",
        "title": "终南山二十韵",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "关内平田窄，东西截杳冥。雨侵诸县黑，云破九门青。",
            "暂看犹无暇，长栖信有灵。古苔秋渍斗，积雾夜昏萤。",
            "怒恐撞天漏，深疑隐地形。盘根连北岳，转影落南溟。",
            "穷穴何山出，遮蛮上国宁。残阳高照蜀，败叶远浮泾。",
            "劚竹烟岚冻，偷湫雨雹腥。闲房僧灌顶，浴涧鹤遗翎。",
            "梯滑危缘索，云深静唱经。放泉惊鹿睡，闻磬得人醒。",
            "踏著神仙宅，敲开洞府扃。棋残秦士局，字缺晋公铭。",
            "一谷势当午，孤峰耸起丁。远平丹凤阙，冷射五侯厅。",
            "万丈冰声折，千寻树影停。望中仙岛动，行处月轮馨。",
            "叠石移临砌，研胶泼上屏。明时献君寿，不假老人星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 秋日同觉公上人眺慈恩塔六韵 ----------
    {
        "id": "li-dong-89",
        "title": "秋日同觉公上人眺慈恩塔六韵",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "九级耸莲宫，晴登袖拂虹。房廊窥井底，世界出笼中。",
            "照牖三山火，吹铃八极风。细闻槎客语，遥辨海鱼冲。",
            "禁静声连北，江寒影在东。谒师开秘锁，尘日闭虚空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 感知上刑部郑侍郎 ----------
    {
        "id": "li-dong-90",
        "title": "感知上刑部郑侍郎",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "寄掩白云司，蜀都高卧时。邻僧照寒竹，宿鸟动秋池。",
            "帝诵嘉莲表，人吟宝剑诗。石渠流月断，画角截江吹。",
            "闲出黄金勒，前飞白鹭鹚。公心外国说，重望两朝推。",
            "静藓斜圭影，孤窗响锡枝。兴幽松雪见，心苦砚冰知。",
            "缘杖虫声切，过门马足迟。漏残终卷读，日下大名垂。",
            "平碛容雕上，仙山许狖窥。数联金口出，死免愧丘为。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 叙事寄荐福栖白（一作听白公话旧） ----------
    {
        "id": "li-dong-91",
        "title": "叙事寄荐福栖白（一作听白公话旧）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "险倚石屏风，秋涛梦越中。前朝吟会散，故国讲流终。",
            "北地闻巴狖，南山见碛鸿。楼高惊雨阔，木落觉城空。",
            "兔满期姚监，蝉稀别楚公。净瓶光照客，拄杖朽生虫。",
            "平地塔千尺，半空灯一笼。祝尧谈几句，旋泻海涛东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 送龙州田使君旧诗家 ----------
    {
        "id": "li-dong-92",
        "title": "送龙州田使君旧诗家",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "御札轸西陲，龙州出牧时。度关云作雪，挂栈水成澌。",
            "剑淬号猿岸，弓悬宿鹤枝。江灯混星斗，山木乱枪旗。",
            "锁库休秤药，开楼又见诗。无心陪宴集，吟苦忆京师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 和知己赴任华州 ----------
    {
        "id": "li-dong-93",
        "title": "和知己赴任华州",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "东门罢相郡，此拜动京华。落日开宵印，初灯见早麻。",
            "鹤身红旆拂，仙掌白云遮。塞色侵三县，河声聒两衙。",
            "松根醒客酒，莲座隐僧家。一道帆飞直，中筵岳影斜。",
            "书名寻雪石，澄鼎露金沙。锁合眠关吏，杯寒啄庙鸦。",
            "分台话嵩洛，赛雨恋烟霞。树谷期招隐，吟诗煮柏茶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 题咸阳楼 ----------
    {
        "id": "li-dong-94",
        "title": "题咸阳楼",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "晚亚古城门，凭高黯客魂。塞侵秦旧国，河浸汉荒村。",
            "客路飏书烬，人家带水痕。猎频虚冢穴，耕苦露松根。",
            "墙外峰粘汉，冰中日晃原。断碑移作砌，广第灌成园。",
            "北马疑眠碛，南人忆钓湓。桥闲野鹿过，街静禁鸦翻。",
            "滩鼓城隍动，云冲太白昏。标衣多吕裔，荷锸或刘孙。",
            "吊问难知主，登攀强滴樽。不能扶壮势，冠剑惜乾坤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 赠兴善彻公上人 ----------
    {
        "id": "li-dong-95",
        "title": "赠兴善彻公上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "师资怀剑外，徒步管街东。九里山横烧，三条木落风。",
            "古池曾看鹤，新塔未吟虫。夜久龙髯冷，年多麈尾空。",
            "心宗本无碍，问学岂难同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 龙池春草 ----------
    {
        "id": "li-dong-96",
        "title": "龙池春草",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "龙池清禁里，芳草傍池春。旋长方遮岸，全生不染尘。",
            "和风轻动色，湛露静流津。浅得承天步，深疑绕御轮。",
            "鱼寻倒影没，花带湿光新。肯学长河畔，绵绵思远人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 秋宿梓州牛头寺 ----------
    {
        "id": "li-dong-97",
        "title": "秋宿梓州牛头寺",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "月去檐三尺，川云入寺楼。灵山顿离众，列宿不多稠。",
            "篆字焚初缺，翻经诵若流。窗闲二江冷，帘卷半空秋。",
            "诏散松梢别，棋终竹节收。静增双阙念，高并五翁游。",
            "鹤梦生红日，云闲锁梓州。望空工部眼，搔乱广文头。",
            "石室僧调马，银河客问牛。晓楼归下界，大地一浮沤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 送韦太尉自坤维除广陵 ----------
    {
        "id": "li-dong-98",
        "title": "送韦太尉自坤维除广陵",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "全蜀拜扬州，征东辍武侯。直来万里月，旁到五峰秋。",
            "幢冷遮高雪，旗闲卓乱流。谢朝明主喜，登省旧寮愁。",
            "隔海城通舶，连河市响楼。千官倚元老，虚梦法云游。",
            "第七百二十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 赠曹郎中崇贤所居（一作上崇贤曹郎中） ----------
    {
        "id": "li-dong-99",
        "title": "赠曹郎中崇贤所居（一作上崇贤曹郎中）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "闲坊宅枕穿宫水，听水分衾盖蜀缯。药杵声中捣残梦，",
            "茶铛影里煮孤灯。刑曹树荫千年井，华岳楼开万仞冰。",
            "诗句变风官渐紧，夜涛舂断海边藤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 赠昭应沈少府 ----------
    {
        "id": "li-dong-100",
        "title": "赠昭应沈少府",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "行宫接县判云泉，袍色虽青骨且仙。鄠杜忆过梨栗墅，",
            "潇湘曾棹雪霜天。华山僧别留茶鼎，渭水人来锁钓船。",
            "东送西迎终几考，新诗觅得两三联。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 上司空员外 ----------
    {
        "id": "li-dong-101",
        "title": "上司空员外",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "禅心高卧似疏慵，诗客经过不厌重。藤杖几携量碛雪，",
            "玉鞭曾把数嵩峰。夜眠古巷当城月，秋直清曹入省钟。",
            "禹凿故山归未得，河声暗老两三松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 叙旧游寄栖白 ----------
    {
        "id": "li-dong-102",
        "title": "叙旧游寄栖白",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "老着重袍坐石房，竺经休讲白眉长。省冲鼍没投江岛，",
            "曾看鱼飞倚海樯。晓炙冻盂原日气，夜挑莲碗禁灯光。",
            "吟诗五岭寻无可，倏忽如今四十霜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 哭栖白供奉 ----------
    {
        "id": "li-dong-103",
        "title": "哭栖白供奉",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "闻说孤窗坐化时，白莎萝雨滴空池。吟诗堂里秋关影，",
            "礼佛灯前夜照碑。贺雪已成金殿梦，看涛终负石桥期。",
            "逢山对月还惆怅，争得无言似祖师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 赠入内供奉僧 ----------
    {
        "id": "li-dong-104",
        "title": "赠入内供奉僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "内殿谈经惬帝怀，沃州归隐计全乖。数条雀尾来南海，",
            "一道蝉声噪御街。石枕纹含山里叶，铜瓶口塞井中柴。",
            "因逢夏日西明讲，不觉宫人拔凤钗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 感恩书事寄上集义司徒相公 ----------
    {
        "id": "li-dong-105",
        "title": "感恩书事寄上集义司徒相公",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "积雪峰西遇奖称，半家寒骨起沟塍。镇时贤相回人镜，",
            "报德慈亲点佛灯。授钺已闻诸国静，坐筹重见大河澄。",
            "功居第一图烟阁，依旧终南满杜陵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 赠永崇李将军充襄阳制置使 ----------
    {
        "id": "li-dong-106",
        "title": "赠永崇李将军充襄阳制置使",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "拜官门外发辉光，宿卫阴符注几行。行处近天龙尾滑，",
            "猎时陪帝马鬃香。九城王气生旗队，万里寒风入箭疮。",
            "从此浩然声价歇，武中还有李襄阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 寄淮海惠泽上人 ----------
    {
        "id": "li-dong-107",
        "title": "寄淮海惠泽上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "海涛痕满旧征衣，长忆初程宿翠微。竹里桥鸣知马过，",
            "塔中灯露见鸿飞。眉毫别后应盈尺，岩木居来定几围。",
            "他日愿师容一榻，煎茶扫地学忘机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 春日隐居官舍感怀 ----------
    {
        "id": "li-dong-108",
        "title": "春日隐居官舍感怀",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "风吹烧烬杂汀沙，还似青溪旧寄家。入户竹生床下叶，",
            "隔窗莲谢镜中花。苔房毳客论三学，雪岭巢禽看两衙。",
            "销得人间无限事，江亭月白诵南华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 春日即事寄一二知己 ----------
    {
        "id": "li-dong-109",
        "title": "春日即事寄一二知己",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "浴马池西一带泉，开门景物似樊川。朱衣映水人归县，",
            "白羽遗泥鹤上天。索米夜烧风折木，无车春养雪藏鞭。",
            "缙绅处士知章句，忍使孤窗枕泪眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 废寺闲居寄怀一二罢举知己（一作省归郎） ----------
    {
        "id": "li-dong-110",
        "title": "废寺闲居寄怀一二罢举知己（一作省归郎）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "病居废庙冷吟烟，无力争飞类病蝉。槐省老郎蒙主弃，",
            "月陂孤客望谁怜。税房兼得调猿石，租地仍分浴鹤泉。",
            "处世堪惊又堪愧，一坡山色不论钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 题尼大德院 ----------
    {
        "id": "li-dong-111",
        "title": "题尼大德院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "云鬟早岁断金刀，戒律曾持五百条。台上灯红莲叶密，",
            "眉间毫白黛痕销。绣成佛国银为地，画出王城雪覆桥。",
            "清净高楼松桧寺，世雄翻愧自低腰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 怀张乔张霞 ----------
    {
        "id": "li-dong-112",
        "title": "怀张乔张霞",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "西风吹雨叶还飘，忆我同袍隔海涛。江塔眺山青入佛，",
            "边城履雪白连雕。身离世界归天竺，影挂虚空度石桥。",
            "应念无成独流转，懒磨铜片鬓毛焦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 赠徐山人 ----------
    {
        "id": "li-dong-113",
        "title": "赠徐山人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "徐生何代降坤维，曾伴园公采紫芝。瓦砾变黄忧世换，",
            "髭须放白怕人疑。山房古竹粗于树，海岛灵童寿等龟。",
            "知叹有唐三百载，光阴未抵一先棋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 寄南岳僧 ----------
    {
        "id": "li-dong-114",
        "title": "寄南岳僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "新秋日后晒书天，白日当松影却圆。五字句求方寸佛，",
            "一条街擘两行蝉。不曾著事于机内，长合教山在眼前。",
            "花落俦公房外石，调猿弄虎叹无缘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 华山 ----------
    {
        "id": "li-dong-115",
        "title": "华山",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "碧山长冻地长秋，日夕泉源聒华州。万户烟侵关令宅，",
            "四时云在使君楼。风驱雷电临河震，鹤引神仙出月游。",
            "峰顶高眠灵药熟，自无霜雪上人头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 和曹监春晴见寄 ----------
    {
        "id": "li-dong-116",
        "title": "和曹监春晴见寄",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "竺庙邻钟震晓鸦，春阴盖石似仙家。兰台架列排书目，",
            "顾渚香浮瀹茗花。胶溜石松粘鹤氅，泉离冰井熨僧牙。",
            "功成名著扁舟去，愁睹前题罩碧纱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 赠三惠大师 ----------
    {
        "id": "li-dong-117",
        "title": "赠三惠大师",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "枫猿峤角别多时，二教兼修内学师。药树影中频缀偈，",
            "莲峰朵下几窥棋。游归笋长齐童子，病起巢成露鹤儿。",
            "诏落五天开夏讲，两街人竞礼长眉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 送醉画王处士 ----------
    {
        "id": "li-dong-118",
        "title": "送醉画王处士",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "几年乘兴住南吴，狂醉兰舟夜落湖。别后鹤毛描转细，",
            "近来牛角饮还粗。同餐夏果山何处，共钓秋涛石在无。",
            "关下相逢怪予老，篇章役思绕寰区。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 闻杜鹃 ----------
    {
        "id": "li-dong-119",
        "title": "闻杜鹃",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "万古潇湘波上云，化为流血杜鹃身。长疑啄破青山色，",
            "只恐啼穿白日轮。花落玄宗回蜀道，雨收工部宿江津。",
            "声声犹得到君耳，不见千秋一甑尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 赋得送轩辕先生归罗浮山 ----------
    {
        "id": "li-dong-120",
        "title": "赋得送轩辕先生归罗浮山",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "旧山归隐浪摇青，绿鬓山童一帙经。诗帖布帆猿鸟看，",
            "药煎金鼎鬼神听。洞深头上聆仙语，船静鼻中闻海腥。",
            "此处先生应不住，吾君南望漫劳形。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 送包处士 ----------
    {
        "id": "li-dong-121",
        "title": "送包处士",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "秋思枕月卧潇湘，寄宿慈恩竹里房。性急却于棋上慢，",
            "身闲未免药中忙。休抛手网惊龙睡，曾挂头巾拂鸟行。",
            "闻说石门君旧隐，寒峰溅瀑坏书堂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 赠庞炼师（女人） ----------
    {
        "id": "li-dong-122",
        "title": "赠庞炼师（女人）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "家住涪江汉语娇，一声歌戛玉楼箫。睡融春日柔金缕，",
            "妆发秋霞战翠翘。两脸酒醺红杏妒，半胸酥嫩白云饶。",
            "若能携手随仙令，皎皎银河渡鹊桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 送友罢举赴边职 ----------
    {
        "id": "li-dong-123",
        "title": "送友罢举赴边职",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "出剡篇章入洛文，无人细读叹俱焚。莫辞秉笏随红旆，",
            "便好携家住白云。过水象浮蛮境见，隔江猿叫汉州闻。",
            "高谈阔略陈从事，盟誓边庭壮我军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 病猿 ----------
    {
        "id": "li-dong-124",
        "title": "病猿",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "瘦缠金锁惹朱楼，一别巫山树几秋。寒想蜀门清露滴，",
            "暖怀湘岸白云流。罢抛檐果沉僧井，休拗崖冰溅客舟。",
            "啼过三声应有泪，画堂深不彻王侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 毙驴 ----------
    {
        "id": "li-dong-125",
        "title": "毙驴",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "蹇驴秋毙瘗荒田，忍把敲吟旧竹鞭。三尺焦桐背残月，",
            "一条藜杖卓寒烟。通吴白浪宽围国，倚蜀青山峭入天。",
            "如画海门支肘望，阿谁家卖钓鱼船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 宿叶公棋阁 ----------
    {
        "id": "li-dong-126",
        "title": "宿叶公棋阁",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "带风棋阁竹相敲，局莹无尘拂树梢。日到长天征未断，",
            "钟来岳顶劫须抛。挑灯雪客栖寒店，供茗溪僧爇废巢。",
            "因悟修身试贪教，不须焚火向三茅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 送郤先辈归觐华阴 ----------
    {
        "id": "li-dong-127",
        "title": "送郤先辈归觐华阴",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "桂枝博得凤栖枝，欢觐家僮舞翠微。僧向瀑泉声里贺，",
            "鸟穿仙掌指间飞。休停砚笔吟荒庙，永别灯笼赴锁闱。",
            "骚雅近来颓丧甚，送君傍觉有光辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 赠可上人 ----------
    {
        "id": "li-dong-128",
        "title": "赠可上人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "寺门和鹤倚香杉，月吐秋光到思嚵。将法传来穿泱漭，",
            "把诗吟去入嵌岩。模糊书卷烟岚滴，狼藉衣裳瀑布缄。",
            "不断清风牙底嚼，无因内殿得名衔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 东川高仆射 ----------
    {
        "id": "li-dong-129",
        "title": "东川高仆射",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "油幢影里拜清风，十里貔貅一片雄。三印锁开霜满地，",
            "四门关定月当空。泉浮山叶人家过，诏惹垆香鸟道通。",
            "新起画楼携客上，弦歌筵内海榴红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 宿成都松溪院 ----------
    {
        "id": "li-dong-130",
        "title": "宿成都松溪院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "松持节操溪澄性，一炷烟岚压寺隅。翡翠鸟飞人不见，",
            "琉璃瓶贮水疑无。夜闻子落真山雨，晓汲波圆入画图。",
            "尘拥蜀城抽锁后，此中犹梦在江湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 吊曹监 ----------
    {
        "id": "li-dong-131",
        "title": "吊曹监",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "宅上愁云吹不散，桂林诗骨葬云根。满楼山色供邻里，",
            "一洞松声付子孙。甘露施衣封泪点，秘书取集印苔痕。",
            "吟魂醉魄归何处，御水呜呜夜绕门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 赠长安毕郎中 ----------
    {
        "id": "li-dong-132",
        "title": "赠长安毕郎中",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "高门寒沼水连云，鹭识朱衣傍主人。地肺半边晴带雪，",
            "天街一面静无尘。朝回座客酬琴价，衙退留僧写鹤真。",
            "从此几迁为计相，蓬莱三刻奏东巡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 寄东蜀幕中友 ----------
    {
        "id": "li-dong-133",
        "title": "寄东蜀幕中友",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "官亭池碧海榴殷，遥想清才倚画栏。柳絮涨天笼地暖，",
            "角声经雨透云寒。晓侵台座香烟湿，夜草军书蜡炬干。",
            "为话门人吟太苦，风摧兰秀一枝残。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 曲江渔父 ----------
    {
        "id": "li-dong-134",
        "title": "曲江渔父",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "儿孙闲弄雪霜髯，浪飐南山影入檐。卧稳篷舟龟作枕，",
            "病来茅舍网为帘。值春游子怜莼滑，通蜀行人说鲙甜。",
            "数尺寒丝一竿竹，岂知浮世有猜嫌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 和刘驾博士赠庄严律禅师 ----------
    {
        "id": "li-dong-135",
        "title": "和刘驾博士赠庄严律禅师",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "人言紫绶有光辉，不二心观似草衣。尘劫自营还自坏，",
            "禅门无住亦无归。松根穴蚁通山远，塔顶巢禽见海微。",
            "每话南游偏起念，五峰波上入船扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 智新上人话旧 ----------
    {
        "id": "li-dong-136",
        "title": "智新上人话旧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "蟋蟀灯前话旧游，师经几夏我经秋。金陵市合月光里，",
            "甘露门开峰朵头。晴眺远帆飞入海，夜禅阴火吐当楼。",
            "相看未得东归去，满壁寒涛泻白鸥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 和淮南太尉留题凤州王氏别业 ----------
    {
        "id": "li-dong-137",
        "title": "和淮南太尉留题凤州王氏别业",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "清秋看长鹭雏成，说向湘僧亦动情。节屋折将松上影，",
            "印龛移锁月中声。野人陪赏增诗价，太尉因居著谷名。",
            "闲想此中遗胜事，宿斋吟绕凤池行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 乙酉岁自蜀随计趁试不及 ----------
    {
        "id": "li-dong-138",
        "title": "乙酉岁自蜀随计趁试不及",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "客卧涪江蘸月厅，知音唤起进趋生。寒梅折后方离蜀，",
            "腊月圆前未到京。风卷坏亭羸仆病，雪糊危栈蹇驴行。",
            "文昌一试应关分，岂校褒斜两日程。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 龙州韦郎中先梦六赤，后因打叶子以诗上 ----------
    {
        "id": "li-dong-139",
        "title": "龙州韦郎中先梦六赤，后因打叶子以诗上",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "红蜡香烟扑画楹，梅花落尽庾楼清。光辉圆魄衔山冷，",
            "彩镂方牙着腕轻。宝帖牵来狮子镇，金盆引出凤凰倾。",
            "微黄喜兆庄周梦，六赤重新掷印成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 140. 和寿中丞伤猿 ----------
    {
        "id": "li-dong-140",
        "title": "和寿中丞伤猿",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "遗挂朱栏锁半寻，清声难买恨黄金。悬崖接果今何在，",
            "浅井窥星影已沉。归宅叶铺曾睡石，入朝灯照旧啼林。",
            "小山罢绕随湘客，高树休升对岳禽。天竺省怜伤倍切，",
            "亲知宽和思难任。相门恩重无由报，竟托仙郎日夜吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 141. 上灵州令狐相公（一作赠高仆射自安西赴阙） ----------
    {
        "id": "li-dong-141",
        "title": "上灵州令狐相公（一作赠高仆射自安西赴阙）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "征蛮破虏汉功臣，提剑归来万里身。",
            "笑倚凌烟金柱看，形容憔悴老于真。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 142. 寓言 ----------
    {
        "id": "li-dong-142",
        "title": "寓言",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "三千宫女露蛾眉，笑煮黄金日月迟。",
            "麟凤隔云攀不及，空山惆怅夕阳时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 143. 客亭对月 ----------
    {
        "id": "li-dong-143",
        "title": "客亭对月",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "游子离魂陇上花，风飘浪卷绕天涯。",
            "一年十二度圆月，十一回圆不在家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 144. 宿鄠郊赠罗处士 ----------
    {
        "id": "li-dong-144",
        "title": "宿鄠郊赠罗处士",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "川静星高栎已枯，南山落石水声粗。",
            "白云钓客窗中宿，卧数嵩峰听五湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 145. 有寄 ----------
    {
        "id": "li-dong-145",
        "title": "有寄",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "爱酒耽棋田处士，弹琴咏史贾先生。",
            "御沟临岸有云石，不见鹤来何处行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 146. 送三藏归西天国 ----------
    {
        "id": "li-dong-146",
        "title": "送三藏归西天国",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "十万里程多少碛，沙中弹舌授降龙。",
            "五天到日应头白，月落长安半夜钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 147. 金陵怀古 ----------
    {
        "id": "li-dong-147",
        "title": "金陵怀古",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "古来无此战争功，日日戈船卷海风。",
            "一遇灵鳌开睡眼，六朝灰尽九江空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 148. 长安县厅 ----------
    {
        "id": "li-dong-148",
        "title": "长安县厅",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "主人寂寞客屯邅，愁绝终南满案前。",
            "乞取中庭藤五尺，为君高劚扣青天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 149. 题晰上人贾岛诗卷 ----------
    {
        "id": "li-dong-149",
        "title": "题晰上人贾岛诗卷",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "贾生诗卷惠休装，百叶莲花万里香。",
            "供得半年吟不足，长须字字顶司仓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 150. 送僧清演归山 ----------
    {
        "id": "li-dong-150",
        "title": "送僧清演归山",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "毛褐斜肩背负经，晓思吟入窦山青。",
            "峰前野水横官道，踏着秋天三四星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 151. 赠僧 ----------
    {
        "id": "li-dong-151",
        "title": "赠僧",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "不羡王公与贵人，唯将云鹤自相亲。",
            "闲来石上观流水，欲洗禅衣未有尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 152. 题学公院池莲 ----------
    {
        "id": "li-dong-152",
        "title": "题学公院池莲",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "竹引山泉玉甃池，栽莲莫怪藕生丝。",
            "如何不似麻衣客，坐对秋风待一枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 153. 山居喜友人见访 ----------
    {
        "id": "li-dong-153",
        "title": "山居喜友人见访",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "入云晴劚茯苓还，日暮逢迎木石间。",
            "看待诗人无别物，半潭秋水一房山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 154. 秋宿长安韦主簿厅 ----------
    {
        "id": "li-dong-154",
        "title": "秋宿长安韦主簿厅",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "水木清凉夜直厅，愁人楼上唱寒更。",
            "坐劳同步帘前月，鼠动床头印锁声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 155. 冬忆友人 ----------
    {
        "id": "li-dong-155",
        "title": "冬忆友人",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "吟上山前数竹枝，叶翻似雪落霏霏。",
            "枕前明月谁动影，睡里惊来不觉归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 156. 怀圭峰影林泉 ----------
    {
        "id": "li-dong-156",
        "title": "怀圭峰影林泉",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "吾家旧物贾生传，入内遥分锡杖泉。",
            "鹤去帝移宫女散，更堪呜咽过楼前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 157. 赠青龙印禅师 ----------
    {
        "id": "li-dong-157",
        "title": "赠青龙印禅师",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "雨涩秋刀剃雪时，庵前曾礼草堂师。",
            "居人昨日相过说，鹤已生孙竹满池。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 158. 戏赠侯常侍 ----------
    {
        "id": "li-dong-158",
        "title": "戏赠侯常侍",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "葛洪卷与江淹赋，名动天边傲石居。",
            "两蜀词人多载后，同君讳却马相如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 159. 绣岭宫词 ----------
    {
        "id": "li-dong-159",
        "title": "绣岭宫词",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "春日迟迟春草绿，野棠开尽飘香玉。",
            "绣岭宫前鹤发翁，犹唱开元太平曲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 160. 中秋月（一作廖凝诗） ----------
    {
        "id": "li-dong-160",
        "title": "中秋月（一作廖凝诗）",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "九十日秋色，今秋已半分。孤光吞列宿，四面绝微云。",
            "众木排疏影，寒流叠细纹。遥遥望丹桂，心绪更纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 161. 宿书僧院 ----------
    {
        "id": "li-dong-161",
        "title": "宿书僧院",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "夜水笔前澄，时推外学能。书成百个字，庭转几遭灯。",
            "寄墨大坛吏，分笺蜀国僧。为题江寺塔，牌挂入云层。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 162. 雪 ----------
    {
        "id": "li-dong-162",
        "title": "雪",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "迢迢来极塞，连阙谓风吹。禅客呵金锡，征人擘冻旗。",
            "细填虫穴满，重压鹤巢欹。有影晴飘野，无声夜落池。",
            "正繁秦甸暖，渐厚楚宫饥。冻挹分泉涩，光凝二阁痴。",
            "踏遗兰署迹，听起石门思。用表丰年瑞，无令扫玉墀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 163. 述怀二十韵献覃怀相公 ----------
    {
        "id": "li-dong-163",
        "title": "述怀二十韵献覃怀相公",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "帝梦求良弼，生申属圣明。青云县器业，白日贯忠贞。",
            "霭霭随春动，忻忻共物荣。静宜浮竞息，坐觉好风生。",
            "万国闻应跃，千门望尽倾。瑞含杨柳色，气变管弦声。",
            "百辟寻知度，三阶正有程。鲁儒规蕴藉，周诰美和平。",
            "碧水遗幽抱，朱丝寄远情。风流秦印绶，仪表汉公卿。",
            "忠谠期登用，回邪自震惊。云开长剑倚，路绝一峰横。",
            "九野方无事，沧溟本不争。国将身共计，心与众为城。",
            "早晚中条下，红尘一顾清。南潭容伴鹤，西笑忽迁莺。",
            "折树恩难报，怀仁命甚轻。二年犹困辱，百口望经营。",
            "未在英侯选，空劳短羽征。知音初相国，从此免长鸣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 164. 岁暮自广江至新兴往复中题峡山寺 ----------
    {
        "id": "li-dong-164",
        "title": "岁暮自广江至新兴往复中题峡山寺",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "薄暮缘西峡，停桡一访僧。鹭巢行卧柳，猿饮倒垂藤。",
            "水曲岩千叠，云深树百层。山风寒殿磬，溪雨夜船灯。",
            "滩涨危槎没，泉冲怪石崩。中台一襟泪，岁杪别良朋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 165. 冬日送凉州刺史 ----------
    {
        "id": "li-dong-165",
        "title": "冬日送凉州刺史",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "宠饯西门外，双旌出汉陵。未辞金殿日，已梦雪山灯。",
            "地远终峰尽，天寒朔气凝。新年行已到，旧典听难胜。",
            "吏扫盘雕影，人遮散马乘。移军驼驮角，下塞掾河冰。",
            "猎近昆仑兽，吟招碛石僧。重输右藏实，方见左车能。",
            "兵聚边风急，城宽夜月澄。连营烟火岭，望诏几回登。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 166. 过贾浪仙旧地 ----------
    {
        "id": "li-dong-166",
        "title": "过贾浪仙旧地",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "鹤外唐来有谪星，长江东注冷沧溟。境搜松雪仙人岛，",
            "吟歇林泉主簿厅。片月已能临榜黑，遥天何益抱坟青。",
            "年年谁不登高第，未胜骑驴入画屏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 167. 句 ----------
    {
        "id": "li-dong-167",
        "title": "句",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "公道此时如不得，昭陵恸哭一生休。（《北梦琐言》云：",
            "洞三榜，裴贽第二榜。策夜，帘前献诗云云。寻卒蜀中。",
            "贽无子，人谓屈洞所致）",
            "第七百二十四卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 168. 山泉 ----------
    {
        "id": "li-dong-168",
        "title": "山泉",
        "author": "李洞",
        "poet_id": "li-dong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "半空飞下水，势去响如雷。静彻啼猿寺，高凌坐客台。",
            "耳同经剑阁，身若到天台。溅树吹成冻，凌祠触作灰。",
            "深中试楖栗，浅处落莓苔。半夜重城闭，潺湲枕上来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]