# -*- coding: utf-8 -*-
"""
朱庆馀卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 161 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 泛溪 ----------
    {
        "id": "zhu-qing-yu-1",
        "title": "泛溪",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "曲渚回花舫，生衣卧向风。鸟飞溪色里，人语棹声中。",
            "馀卉才分影，新蒲自作丛。前湾更幽绝，虽浅去犹通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 宿陈处士书斋 ----------
    {
        "id": "zhu-qing-yu-2",
        "title": "宿陈处士书斋",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "结茅当此地，下马见高情。菰叶寒塘晚，杉阴白石明。",
            "向炉新茗色，隔雪远钟声。闲得相逢少，吟多寐不成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 上宣州沈大夫 ----------
    {
        "id": "zhu-qing-yu-3",
        "title": "上宣州沈大夫",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "科名继世古来稀，高步何年下紫微。帝命几曾移重镇，",
            "时清犹望领春闱。登朝旧友常思见，开幕贤人并望归。",
            "今日得游风化地，却回沧海有光辉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 杭州送萧宝校书 ----------
    {
        "id": "zhu-qing-yu-4",
        "title": "杭州送萧宝校书",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "马识青山路，人随白浪船。别君犹有泪，学道谩经年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送盛长史（盛随军） ----------
    {
        "id": "zhu-qing-yu-5",
        "title": "送盛长史（盛随军）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "莫辞东路远，此别岂闲行。职处中军要，官兼上佐荣。",
            "野亭枫叶暗，秋水藕花明。拜省期将近，孤舟促去程。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 宿道士观 ----------
    {
        "id": "zhu-qing-yu-6",
        "title": "宿道士观",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "堂闭仙人影，空坛月露初。闲听道家子，盥漱读灵书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 湖州韩使君置宴（一作陪韩中丞宴不饮酒） ----------
    {
        "id": "zhu-qing-yu-7",
        "title": "湖州韩使君置宴（一作陪韩中丞宴不饮酒）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "老大成名仍足病，纵听丝竹也无欢。",
            "高情太守容闲坐，借与青山尽日看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 题仙游寺 ----------
    {
        "id": "zhu-qing-yu-8",
        "title": "题仙游寺",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "石抱龙堂藓石干，山遮白日寺门寒。",
            "长松瀑布饶奇状，曾有仙人驻鹤看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 宫词 ----------
    {
        "id": "zhu-qing-yu-9",
        "title": "宫词",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "寂寂花时闭院门，美人相并立琼轩。",
            "含情欲说宫中事，鹦鹉前头不敢言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 公子行 ----------
    {
        "id": "zhu-qing-yu-10",
        "title": "公子行",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "闲从结客冶游时，忘却红楼薄暮期。",
            "醉上黄金堤上去，马鞭捎断绿杨丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送陈摽 ----------
    {
        "id": "zhu-qing-yu-11",
        "title": "送陈摽",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "满酌劝童仆，好随郎马蹄。春风慎行李，莫上白铜鞮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 寻古观 ----------
    {
        "id": "zhu-qing-yu-12",
        "title": "寻古观",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "仙观曾过知不远，花藏石室杳难寻。",
            "泉边白鹿闻人语，看过天坛渐入深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 南岭路 ----------
    {
        "id": "zhu-qing-yu-13",
        "title": "南岭路",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "越岭向南风景异，人人传说到京城。",
            "经冬来往不踏雪，尽在刺桐花下行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 陪江州李使君重阳宴百花亭 ----------
    {
        "id": "zhu-qing-yu-14",
        "title": "陪江州李使君重阳宴百花亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "闲携九日酒，共到百花亭。醉里求诗境，回看岛屿青。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 上张水部 ----------
    {
        "id": "zhu-qing-yu-15",
        "title": "上张水部",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "出入门阑久，儿童亦有情。不忘将姓字，常说向公卿。",
            "每许连床坐，仍容并马行。恩深转无语，怀抱甚分明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 凤翔西池与贾岛纳凉 ----------
    {
        "id": "zhu-qing-yu-16",
        "title": "凤翔西池与贾岛纳凉",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "四面无炎气，清池阔复深。蝶飞逢草住，鱼戏见人沈。",
            "拂石安茶器，移床选树阴。几回同到此，尽日得闲吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 上汴州令狐相公 ----------
    {
        "id": "zhu-qing-yu-17",
        "title": "上汴州令狐相公",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "罢相恩犹在，那容处静司。政严初领节，名重更因诗。",
            "公事巡营外，戎装拜敕时。恭闻长与善，应念出身迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送于中丞入蕃册立 ----------
    {
        "id": "zhu-qing-yu-18",
        "title": "送于中丞入蕃册立",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "上马生边思，戎装别众僚。双旌衔命重，空碛去程遥。",
            "迥没沙中树，孤飞雪外雕。蕃庭过册礼，几日却回朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送淮阴丁明府 ----------
    {
        "id": "zhu-qing-yu-19",
        "title": "送淮阴丁明府",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "之官未入境，已有爱人心。遣吏回中路，停舟对远林。",
            "岛声淮浪静，雨色稻苗深。暇日公门掩，唯应伴客吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送韦校书佐灵州幕 ----------
    {
        "id": "zhu-qing-yu-20",
        "title": "送韦校书佐灵州幕",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "共知行处乐，犹惜此时分。职已为书记，官曾校典坟。",
            "寒城初落叶，高戍远生云。边事何须问，深谋只在君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 上江州李史君 ----------
    {
        "id": "zhu-qing-yu-21",
        "title": "上江州李史君",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "起家声望重，自古更谁过。得在朝廷少，还因谏诤多。",
            "经年愁瘴疠，几处遇恩波。入境无馀事，唯闻父老歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 发凤翔后涂中怀田少府 ----------
    {
        "id": "zhu-qing-yu-22",
        "title": "发凤翔后涂中怀田少府",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "识君春未半，意欲住经秋。见酒连诗句，逢花跋马头。",
            "别来唯独宿，梦里尚同游。所在求飧过，无因离得愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 雪夜与真上人宿韩协律宅 ----------
    {
        "id": "zhu-qing-yu-23",
        "title": "雪夜与真上人宿韩协律宅",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "斜雪微沾砌，空堂夜语清。逆风听漏短，回烛向楼明。",
            "盥漱随禅伴，讴吟得野情。此欢那敢忘，世贵丈夫名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 与贾岛、顾非熊、无可上人宿万年姚少府宅 ----------
    {
        "id": "zhu-qing-yu-24",
        "title": "与贾岛、顾非熊、无可上人宿万年姚少府宅",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "莫厌通宵坐，贫中会聚难。堂虚雪气入，灯在漏声残。",
            "役思因生病，当禅岂觉寒。开门各有事，非不惜馀欢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 震为苍筤竹 ----------
    {
        "id": "zhu-qing-yu-25",
        "title": "震为苍筤竹",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "为擢东方秀，修然异众筠。青苍才映粉，蒙密正含春。",
            "嫩箨沾微雨，幽根绝细尘。乍怜分径小，偏觉带烟新。",
            "结实皆留凤，垂阴似庇人。顾唯竿在手，深水挂赪鳞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 题青龙寺 ----------
    {
        "id": "zhu-qing-yu-26",
        "title": "题青龙寺",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "寺好因岗势，登临值夕阳。青山当佛阁，红叶满僧廊。",
            "竹色连平地，虫声在上方。最怜东面静，为近楚城墙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 送滕庶子致仕归江南 ----------
    {
        "id": "zhu-qing-yu-27",
        "title": "送滕庶子致仕归江南",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "常怀独往意，此日去朝簪。丹诏荣归骑，清风满故林。",
            "诸侯新起敬，遗老重相寻。在处饶山水，堪行慰所心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 夏日题武功姚主簿 ----------
    {
        "id": "zhu-qing-yu-28",
        "title": "夏日题武功姚主簿",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "亭午无公事，垂帘树色间。僧来茶灶动，吏去印床闲。",
            "傍竹行寻巷，当门立看山。吟诗老不倦，未省话官班。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 送张景宣下第东归（归扬州觐省） ----------
    {
        "id": "zhu-qing-yu-29",
        "title": "送张景宣下第东归（归扬州觐省）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "归省值花时，闲吟落第诗。高情怜道在，公论觉才遗。",
            "春雨连淮暗，私船过马迟。离心可惆怅，为有入城期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 送顾非熊下第归 ----------
    {
        "id": "zhu-qing-yu-30",
        "title": "送顾非熊下第归",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "但取诗名远，宁论下第频。惜为今日别，共受几年贫。",
            "听雨宿吴寺，过江逢越人。知从本府荐，秋晚又辞亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 送韦繇校书赴浙东幕 ----------
    {
        "id": "zhu-qing-yu-31",
        "title": "送韦繇校书赴浙东幕",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "丞相辟书新，秋关独去人。官离芸阁早，名占甲科频。",
            "水驿迎船火，山城候骑尘。湖边寄家久，到日喜荣亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 寻贾岛所居 ----------
    {
        "id": "zhu-qing-yu-32",
        "title": "寻贾岛所居",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "求闲身未得，此日到京东。独在钟声外，相逢树色中。",
            "谁言人渐老，所向意皆同。月上因留宿，移床对药丛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 题毗陵上人院 ----------
    {
        "id": "zhu-qing-yu-33",
        "title": "题毗陵上人院",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "院深终日静，落叶覆秋虫。盥漱新斋后，修行未老中。",
            "映松山色远，隔水磬声通。此处宜清夜，高吟永与同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 送李侍御入蕃 ----------
    {
        "id": "zhu-qing-yu-34",
        "title": "送李侍御入蕃",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "远使随双节，新官属外台。戎装非好武，书记本多才。",
            "移帐依泉宿，迎人带雪来。心知玉关道，稀见一花开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 望萧关 ----------
    {
        "id": "zhu-qing-yu-35",
        "title": "望萧关",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "渐见风沙暗，萧关欲到时。儿童能探火，妇女解缝旗。",
            "川绝衔鱼鹭，林多带箭麋。暂来戎马地，不敢苦吟诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 送韩校书赴江西幕 ----------
    {
        "id": "zhu-qing-yu-36",
        "title": "送韩校书赴江西幕",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "从军五湖外，终是称诗人。酒后愁将别，涂中过却春。",
            "山桥槲叶暗，水馆燕巢新。驿舫迎应远，京书寄自频。",
            "野情随到处，公务日关身。久共趋名利，龙钟独滞秦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 题寄王秘书 ----------
    {
        "id": "zhu-qing-yu-37",
        "title": "题寄王秘书",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "唯求买药价，此外更无机。扶病看红叶，辞官著白衣。",
            "断篱通野径，高树荫邻扉。时馥留僧宿，馀人得见稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 山居 ----------
    {
        "id": "zhu-qing-yu-38",
        "title": "山居",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "归来青壁下，又见满篱霜。转觉琴斋静，闲从菊地荒。",
            "山泉共鹿饮，林果让僧尝。时复收新药，随云过石梁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 重过惟贞上人院 ----------
    {
        "id": "zhu-qing-yu-39",
        "title": "重过惟贞上人院",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "老去唯求静，都忘外学名。扫床秋叶满，对客远云生。",
            "香閤闲留宿，晴阶暖共行。窗西暮山色，依旧入诗情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 与石昼秀才过普照寺 ----------
    {
        "id": "zhu-qing-yu-40",
        "title": "与石昼秀才过普照寺",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "问人知寺路，松竹暗春山。潭黑龙应在，巢空鹤未还。",
            "经年为客倦，半日与僧闲。更共尝新茗，闻钟笑语间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 题任处士幽居 ----------
    {
        "id": "zhu-qing-yu-41",
        "title": "题任处士幽居",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "惜与幽人别，停舟对草堂。湖云侵卧位，杉露滴茶床。",
            "山月吟时在，池花觉后香。生涯无一物，谁与读书粮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送僧往太原谒李司空 ----------
    {
        "id": "zhu-qing-yu-42",
        "title": "送僧往太原谒李司空",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "已共邻房别，应无更住心。中时过野店，后夜宿寒林。",
            "寺去人烟远，城连塞雪深。禅馀得新句，堪对上公吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 将之上京别淮南书记李侍御 ----------
    {
        "id": "zhu-qing-yu-43",
        "title": "将之上京别淮南书记李侍御",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "心地偶相见，语多为别难。诗成公府晚，路入翠微寒。",
            "逢石自应坐，有花谁共看。身为当去雁，云尽到长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 韩协律相送精舍读书四韵奉寄呈陆补阙 ----------
    {
        "id": "zhu-qing-yu-44",
        "title": "韩协律相送精舍读书四韵奉寄呈陆补阙",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "白鹤西山别，更看上去船。遥知寻寺路，应念宿江烟。",
            "到处无闲日，回期已隔年。何因陪夜坐，清论谏臣边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 过苏州晓上人院 ----------
    {
        "id": "zhu-qing-yu-45",
        "title": "过苏州晓上人院",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "夏满律当清，无中景自生。移松不避远，取石亦亲行。",
            "经案离时少，绳床著处平。若将林下比，应只欠泉声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送僧游缙云 ----------
    {
        "id": "zhu-qing-yu-46",
        "title": "送僧游缙云",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "但望青山去，何山不是缘。寺幽堪讲律，月冷称当禅。",
            "水落无风夜，猿吟欲雨天。寻师若有路，终作缓归年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 赠道者 ----------
    {
        "id": "zhu-qing-yu-47",
        "title": "赠道者",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "自识来清瘦，寻常语论真。药成休伏火，符验不传人。",
            "独有年过鹤，曾无病到身。潜教问弟子，居处与谁邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 杭州卢录事山亭 ----------
    {
        "id": "zhu-qing-yu-48",
        "title": "杭州卢录事山亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "山色满公署，到来诗景饶。解衣临曲榭，隔竹见红蕉。",
            "清漏焚香夕，轻岚视事朝。静中看锁印，高处见迎潮。",
            "曳履庭芜近，当身树叶飘。傍城馀菊在，步入一仙瓢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 送品上人入秦 ----------
    {
        "id": "zhu-qing-yu-49",
        "title": "送品上人入秦",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "独去何人见，林塘共寂寥。生缘闻磬早，觉路出尘遥。",
            "江雪沾新草，秦园发故条。心知禅定处，石室对芭蕉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 题蔷薇花 ----------
    {
        "id": "zhu-qing-yu-50",
        "title": "题蔷薇花",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "四面垂条密，浮阴入夏清。绿攒伤手刺，红堕断肠英。",
            "粉著蜂须腻，光凝蝶翅明。雨中看亦好，况复值初晴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 题胡氏溪亭 ----------
    {
        "id": "zhu-qing-yu-51",
        "title": "题胡氏溪亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "亭与溪相近，无时不有风。涧松生便黑，野藓看多红。",
            "雨足秋声后，山沈夜色中。主人能守静，略与客心同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 看涛 ----------
    {
        "id": "zhu-qing-yu-52",
        "title": "看涛",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "不知来远近，但见白峨峨。风雨驱寒玉，鱼龙迸上波。",
            "声长势未尽，晓去夕还过。要路横天堑，其如造化何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 和刘补阙秋园寓兴之什十首 ----------
    {
        "id": "zhu-qing-yu-53",
        "title": "和刘补阙秋园寓兴之什十首",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "闲园清气满，新兴日堪追。隔水蝉鸣后，当檐雁过时。",
            "雨馀槐穟重，霜近药苗衰。不以朝簪贵，多将野客期。",
            "谁言高静意，不异在衡茅。竹冷人离洞，天晴鹤出巢。",
            "深篱藏白菌，荒蔓露青匏。几见中宵月，清光坠树梢。",
            "逍遥人事外，杖屦入杉萝。草色寒犹在，虫声晚渐多。",
            "静逢山鸟下，幽称野僧过。几许新开菊，闲从落叶和。",
            "留情清景宴，朝罢有馀闲。蝶散红兰外，萤飞白露间。",
            "墙高微见寺，林静远分山。吟足期相访，残阳自掩关。",
            "深斋尝独处，讵肯厌秋声。翠筱寒愈静，孤花晚更明。",
            "每因逢石坐，多见抱书行。入夜听疏杵，遥知耿此情。",
            "苍翠经宵在，园庐景自深。风凄欲去燕，月思向来砧。",
            "碧石当莎径，寒烟冒竹林。杯瓢闲寄咏，清绝是知音。",
            "门巷唯苔藓，谁言不称贫。台闲人下晚，果熟鸟来频。",
            "石脉潜通井，松枝静离尘。残蔬得晴后，又见一番新。",
            "卷帘天色静，近濑觉衣单。蕉叶犹停翠，桐阴已爽寒。",
            "云从高处望，琴爱静时弹。正去重阳近，吟秋意未阑。",
            "竹径通邻圃，清深称独游。虫丝交影细，藤子坠声幽。",
            "积润苔纹厚，迎寒荠叶稠。闲来寻古画，未废执茶瓯。",
            "风物已萧飒，晚烟生霁容。斜分紫陌树，远隔翠微钟。",
            "宿客论文静，闲灯落烬重。无穷林下意，真得古人风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 上翰林蒋防舍人 ----------
    {
        "id": "zhu-qing-yu-54",
        "title": "上翰林蒋防舍人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "清重可过知内制，从前礼绝外庭人。看花在处多随驾，",
            "召宴无时不及旬。马自赐来骑觉稳，诗缘得后意长新。",
            "应怜独在文场久，十有馀年浪过春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 上翰林李舍人 ----------
    {
        "id": "zhu-qing-yu-55",
        "title": "上翰林李舍人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "记得早年曾拜识，便怜孤进赏文章。免令汩没惭时辈，",
            "与作声名彻举场。一自凤池承密旨，今因世路接馀光。",
            "云泥虽隔思长在，纵使无成也不忘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 题章正字道正新居（孝标） ----------
    {
        "id": "zhu-qing-yu-56",
        "title": "题章正字道正新居（孝标）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "独在御楼南畔住，生涯还似旧时贫。全无竹可侵行径，",
            "一半花犹属别人。吟处不妨嫌鼓闹，眼前唯称与僧邻。",
            "近来渐觉青莎巷，车马过从已有尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 送李馀及第归蜀 ----------
    {
        "id": "zhu-qing-yu-57",
        "title": "送李馀及第归蜀",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "从得高科名转盛，亦言归去满城知。发时谁不开筵送，",
            "到处人争与马骑。剑路红蕉明栈阁，巴村绿树荫神祠。",
            "乡中后辈游门馆，半是来求近日诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 送唐中丞开淘西湖夏日游泛因书示郡人 ----------
    {
        "id": "zhu-qing-yu-58",
        "title": "送唐中丞开淘西湖夏日游泛因书示郡人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "萍岸新淘见碧霄，中流相去忽成遥。空馀孤屿来诗景，",
            "无复横槎碍柳条。红旆路幽山翠湿，锦帆风起浪花飘。",
            "共知浸润同雷泽，何虑川源有旱苗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 过旧宅（一作题王侯废宅） ----------
    {
        "id": "zhu-qing-yu-59",
        "title": "过旧宅（一作题王侯废宅）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "古巷戟门谁旧宅，早曾闻说属官家。更无新燕来巢屋，",
            "唯有闲人去看花。空厩欲摧尘满枥，小池初涸草侵沙。",
            "荣华事歇皆如此，立马踟蹰到日斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 鄂渚送白舍人赴杭州 ----------
    {
        "id": "zhu-qing-yu-60",
        "title": "鄂渚送白舍人赴杭州",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "岂知鹦鹉洲边路，得见凤凰池上人。",
            "从此不同诸客礼，故乡西与郡城邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 题崔驸马林亭 ----------
    {
        "id": "zhu-qing-yu-61",
        "title": "题崔驸马林亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "选居幽近御街东，易得诗人聚会同。白练鸟飞深竹里，",
            "朱弦琴在乱书中。亭开山色当高枕，楼静箫声落远风。",
            "何事宦涂犹寂寞，都缘清苦道难通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 赠韩协律 ----------
    {
        "id": "zhu-qing-yu-62",
        "title": "赠韩协律",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "永日微吟在竹前，骨清唯爱漱寒泉。门闲多有投文客，",
            "身病长无买药钱。岭寺听猿频独宿，湖亭避宴动经年。",
            "亲知尽怪疏荣禄，的是将心暗学禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 自萧关望临洮 ----------
    {
        "id": "zhu-qing-yu-63",
        "title": "自萧关望临洮",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "玉关西路出临洮，风卷边沙入马毛。寺寺院中无竹树，",
            "家家壁上有弓刀。惟怜战士垂金甲，不尚游人著白袍。",
            "日暮独吟秋色里，平原一望戍楼高。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 送崔约下第归淮南觐省 ----------
    {
        "id": "zhu-qing-yu-64",
        "title": "送崔约下第归淮南觐省",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "远忆拜亲留不住，出门行计与谁同。程涂半是依船上，",
            "请谒多愁值雨中。堰水静连堤树绿，村桥时映野花红。",
            "回期须及来春事，莫便江边逐钓翁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 羽林郎 ----------
    {
        "id": "zhu-qing-yu-65",
        "title": "羽林郎",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "紫髯年少奉恩初，直阁将军尽不如。酒后引兵围百草，",
            "风前驻旆领边书。宅将公主同时赐，官与中郎共日除。",
            "大笑鲁儒年四十，腰间犹未识金鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 归故园 ----------
    {
        "id": "zhu-qing-yu-66",
        "title": "归故园",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "桑柘骈阗数亩间，门前五柳正堪攀。尊中美酒长须满，",
            "身外浮名总是闲。竹径有时风为扫，柴门无事日常关。",
            "于焉已是忘机地，何用将金别买山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 同友人看花 ----------
    {
        "id": "zhu-qing-yu-67",
        "title": "同友人看花",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "寻花不问春深浅，纵是残红也入诗。",
            "每个树边行一匝，谁家园里最多时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 种花 ----------
    {
        "id": "zhu-qing-yu-68",
        "title": "种花",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "忆昔两京官道上，可怜桃李昼阴垂。",
            "不知谁作巡花使，空记玄宗遣种时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 早发庐江涂中遇雪寄李侍御 ----------
    {
        "id": "zhu-qing-yu-69",
        "title": "早发庐江涂中遇雪寄李侍御",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "芦苇声多雁满陂，湿云连野见山稀。",
            "遥知将吏相逢处，半是春城贺雪归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 登望云亭招友 ----------
    {
        "id": "zhu-qing-yu-70",
        "title": "登望云亭招友",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "日日恐无云可望，不辞逐静望来频。",
            "共知亭下眠云远，解到上头能几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 刘补阙西亭晚宴 ----------
    {
        "id": "zhu-qing-yu-71",
        "title": "刘补阙西亭晚宴",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "虫声已尽菊花干，共立松阴向晚寒。",
            "对酒看山俱惜去，不知斜月下栏干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 送长安罗少府 ----------
    {
        "id": "zhu-qing-yu-72",
        "title": "送长安罗少府",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "科名再得年犹少，今日休官更觉贤。去国已辞趋府伴，",
            "向家还入渡江船。雪晴新雁斜行出，潮落残云远色鲜。",
            "在处若逢山水住，到时应不及秋前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 林下招胡长官（一作寄招胡明府） ----------
    {
        "id": "zhu-qing-yu-73",
        "title": "林下招胡长官（一作寄招胡明府）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "语低清貌似休粮，称著朱衣入草堂。",
            "销暑近来无别物，桂阴当午满绳床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 与真上人一二禅师题玢寺主院 ----------
    {
        "id": "zhu-qing-yu-74",
        "title": "与真上人一二禅师题玢寺主院",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "杖屦相随任处便，不唯空寄上方眠。",
            "归时亦取湖边路，晚映枫林共上船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 寻僧 ----------
    {
        "id": "zhu-qing-yu-75",
        "title": "寻僧",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "吟背春城出草迟，天晴紫阁赴僧期。",
            "山边树下行人少，一派新泉日午时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 题王丘长史宅 ----------
    {
        "id": "zhu-qing-yu-76",
        "title": "题王丘长史宅",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "更无人吏在门前，不似居官似学仙。药气暗侵朝服上，",
            "花阴晚到簿书边。玉琴闲把看山坐，筒簟长铺与客眠。",
            "时见街中骑瘦马，低头只是为诗篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 寄刘少府 ----------
    {
        "id": "zhu-qing-yu-77",
        "title": "寄刘少府",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "唯爱图书兼古器，在官犹自未离贫。",
            "更闻县去青山近，称与诗人作主人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 哭胡遇 ----------
    {
        "id": "zhu-qing-yu-78",
        "title": "哭胡遇",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "寻僧昨日尚相随，忽见绯幡意可知。题处旧诗休更读，",
            "买来新马忆曾骑。不应随分空营奠，终拟求人与立碑。",
            "每向宣阳里中过，遥闻哭临泪先垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 自述 ----------
    {
        "id": "zhu-qing-yu-79",
        "title": "自述",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "诗人甘寂寞，居处遍苍苔。后夜蟾光满，邻家树影来。",
            "岂知莲帐好，自爱草堂开。愿答相思意，援毫愧不才。",
            "第五百一十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 省试晦日与同志昆明池泛舟 ----------
    {
        "id": "zhu-qing-yu-80",
        "title": "省试晦日与同志昆明池泛舟",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "故人同泛处，远色望中明。静见沙痕露，微思月魄生。",
            "周回馀雪在，浩渺暮云平。戏鸟随兰棹，空波荡石鲸。",
            "劫灰难问理，岛树偶知名。自省曾追赏，无如此日情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 送崔拾遗赴阙 ----------
    {
        "id": "zhu-qing-yu-81",
        "title": "送崔拾遗赴阙",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "清貌凌寒玉，朝来拜拾遗。行承天子诏，去感主人知。",
            "剑佩分班日，风霜独立时。名高住不得，非与九霄期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 酬李处士见赠 ----------
    {
        "id": "zhu-qing-yu-82",
        "title": "酬李处士见赠",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "干上非无援，才多却累身。云霄未得路，江海作闲人。",
            "久别唯谋道，相逢不话贫。行藏一如此，可便老风尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 送僧游温州 ----------
    {
        "id": "zhu-qing-yu-83",
        "title": "送僧游温州",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "夏满随所适，江湖非系缘。卷经离峤寺，隔苇上秋船。",
            "水落无风夜，猿啼欲雨天。石门期独往，谢守有遗篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 梦谢亭 ----------
    {
        "id": "zhu-qing-yu-84",
        "title": "梦谢亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "梦后何人见，孤亭似旧时。褰开诚得地，冥感竟因诗。",
            "不往过应少，悲来下独迟。顾惭非谢客，灵贶杳难追。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 河亭 ----------
    {
        "id": "zhu-qing-yu-85",
        "title": "河亭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "孤亭临绝岸，猿鸟识幽蹊。花落曾谁到，诗成独未题。",
            "潮痕经雨在，石笋与杉齐。谢守便登陟，秋来屐齿低。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 送吴秀才之山西 ----------
    {
        "id": "zhu-qing-yu-86",
        "title": "送吴秀才之山西",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "泽潞西边路，兰桡北去人。出门谁恨别，投分不缘贫。",
            "杯酒从年少，知音在日新。东湖发诗意，夏卉竟如春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 和处州严郎中游南溪 ----------
    {
        "id": "zhu-qing-yu-87",
        "title": "和处州严郎中游南溪",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "四望非人境，从前洞穴深。潭清蒲远岸，岚积树无阴。",
            "看草初移屐，扪萝忽并簪。世嫌山水僻，谁伴谢公吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 秋宵宴别卢侍御 ----------
    {
        "id": "zhu-qing-yu-88",
        "title": "秋宵宴别卢侍御",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "风亭弦管绝，玉漏一声新。绿茗香醒酒，寒灯静照人。",
            "清班无意恋，素业本来贫。明发青山道，谁逢去马尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 酬于訢校书见贻 ----------
    {
        "id": "zhu-qing-yu-89",
        "title": "酬于訢校书见贻",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "能□得从军，清嬴□□□。绮罗徒满目，山水不离心。",
            "暂别愁花老，相思倚竹阴。家贫无以养，未可话抽簪。【将之上京留别淮南书记李侍御】朱庆馀",
            "半似无名位，门当静处开。人心皆向德，物色不供才。",
            "酒兴春边过，军谋意外来。取名荣相府，却虑诏书催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 送祝秀才归衢州 ----------
    {
        "id": "zhu-qing-yu-90",
        "title": "送祝秀才归衢州",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "旧隐縠溪上，忆归年已深。学徒花下别，乡路雪边寻。",
            "骑吏陪春赏，江僧伴晚吟。高科如在意，当自惜光阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 过孟浩然旧居 ----------
    {
        "id": "zhu-qing-yu-91",
        "title": "过孟浩然旧居",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "命合终山水，才非不称时。冢边空有树，身后独无儿。",
            "散尽诗篇本，长存道德碑。平生谁见重，应只是王维。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 送虚上人游天台 ----------
    {
        "id": "zhu-qing-yu-92",
        "title": "送虚上人游天台",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "青冥通去路，谁见独随缘。此地春前别，何山夜后禅。",
            "石桥隐深树，朱阙见晴天。好是修行处，师当住几年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 孔尚书致仕因而有寄赠 ----------
    {
        "id": "zhu-qing-yu-93",
        "title": "孔尚书致仕因而有寄赠",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "高人心易足，三表乞身闲。与世长疏索，唯僧得往还。",
            "直声留阙下，生事在林间。时复逢清景，乘车看远山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 和处州韦使君新开南溪 ----------
    {
        "id": "zhu-qing-yu-94",
        "title": "和处州韦使君新开南溪",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "地里光图谶，樵人共说深。悠然想高躅，坐使变荒岑。",
            "疏凿因殊旧，亭台亦自今。静容猿暂下，闲与鹤同寻。",
            "转旆驯禽起，褰帷瀑溜侵。石稀潭见底，岚暗树无阴。",
            "跻险难通屐，攀栖称抱琴。云风开物意，潭水识人心。",
            "携榼巡花遍，移舟惜景沈。世嫌山水僻，谁伴谢公吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 送罗先辈书记归后却还闽中留别 ----------
    {
        "id": "zhu-qing-yu-95",
        "title": "送罗先辈书记归后却还闽中留别",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "同是越人从小别，忽归乡里见皆惊。湖边访旧知谁在，",
            "幕下留欢但觉荣。望岭又生红槿思，登车岂倦白云程。",
            "况当季父承恩日，廉问南州政已成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 送浙东陆中丞 ----------
    {
        "id": "zhu-qing-yu-96",
        "title": "送浙东陆中丞",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "坐将文教镇藩维，花满东南圣主知。公务肯容私暂入，",
            "丰年长与德相随。无贤不是朱门客，有子皆如玉树枝。",
            "自爱此身居乐土，咏歌林下日忘疲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 送元处士游天台 ----------
    {
        "id": "zhu-qing-yu-97",
        "title": "送元处士游天台",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "青冥路口绝人行，独与僧期上赤城。树列烟岚春更好，",
            "溪藏冰雪夜偏明。空山雉雊禾苗短，野馆风来竹气清。",
            "若过石桥看瀑布，不妨高处便题名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 吴兴新堤 ----------
    {
        "id": "zhu-qing-yu-98",
        "title": "吴兴新堤",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "春堤一望思无涯，树势还同水势斜。深映菰蒲三十里，",
            "晴分功利几千家。谋成既不劳人力，境远偏宜隔浪花。",
            "若与青山长作固，汀洲肯恨柳丝遮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 酬萧员外见寄 ----------
    {
        "id": "zhu-qing-yu-99",
        "title": "酬萧员外见寄",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "麦风吹雨正徘徊，忽报书从郡阁来。道薄谬应宗伯选，",
            "诗成徒费谢公才。九霄示路空知感，十上惊魂尚未回。",
            "胜寄幸容溪馆宿，龙钟惭见妓筵开。倘期霁后陪新兴，",
            "一滴还须当一杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 台州郑员外郡斋双鹤 ----------
    {
        "id": "zhu-qing-yu-100",
        "title": "台州郑员外郡斋双鹤",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "丹顶分明音响别，况闻来处隔云涛。情悬碧落飞何晚，",
            "立近清池意自高。向夜双栖惊玉漏，临轩对舞拂朱袍。",
            "仙郎为尔开笼早，莫虑回翔损羽毛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 送窦秀才 ----------
    {
        "id": "zhu-qing-yu-101",
        "title": "送窦秀才",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "江南才子日纷纷，少有篇章得似君。清话未同山寺宿，",
            "离歌已向客亭闻。梅天马上愁黄鸟，泽国帆前见白云。",
            "通籍名高年又少，回头应笑晚从军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 送邵州林使君 ----------
    {
        "id": "zhu-qing-yu-102",
        "title": "送邵州林使君",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "轩车此去也逢时，地近湘南颇入诗。一月计程那是远，",
            "中年出守未为迟。水边花气熏章服，岭上岚光照画旗。",
            "想得化行风土变，州人应为立生祠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 送饶州张使君 ----------
    {
        "id": "zhu-qing-yu-103",
        "title": "送饶州张使君",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "白头为郡清秋别，山水南行岂觉赊。楚老只应思入境，",
            "吴儿从此去移家。馆依高岭分樟叶，路出重江见苇花。",
            "务退唯当吟咏苦，留心曾不在生涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 题开元寺 ----------
    {
        "id": "zhu-qing-yu-104",
        "title": "题开元寺",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "西入山门十里程，粉墙书字甚分明。萧帝坏陵深虎迹，",
            "广师遗院闭松声。长廊画剥僧形影，石壁尘昏客姓名。",
            "何必更将空色遣，眼前人事是浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 与庞复言携酒望洞庭 ----------
    {
        "id": "zhu-qing-yu-105",
        "title": "与庞复言携酒望洞庭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "南湖春色通平远，贪记诗情忘酒杯。帆自巴陵山下过，",
            "雨从神女峡边来。青蒲映水疏还密，白鸟翻空去复回。",
            "尽日与君同看望，了然胜见画屏开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 送浙东周判官 ----------
    {
        "id": "zhu-qing-yu-106",
        "title": "送浙东周判官",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "久闻从事沧江外，谁谓无官已白头。来备戎装嘶数骑，",
            "去持丹诏入孤舟。蝉鸣远驿残阳树，鹭起湖田片雨秋。",
            "到日重陪丞相宴，镜湖新月在城楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 塞下曲 ----------
    {
        "id": "zhu-qing-yu-107",
        "title": "塞下曲",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "万里去长征，连年惯野营。入群来择马，抛伴去擒生。",
            "箭撚雕翎阔，弓盘鹊角轻。问看行近远，西过受降城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 送僧 ----------
    {
        "id": "zhu-qing-yu-108",
        "title": "送僧",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "客行皆有为，师去是闲游。野望携金策，禅栖寄石楼。",
            "山深松翠冷，潭静菊花秋。几处题青壁，袈裟溅瀑流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 望早日 ----------
    {
        "id": "zhu-qing-yu-109",
        "title": "望早日",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "窗下闻鸡后，苍茫映远林。才分天地色，便禁虎狼心。",
            "是处程涂远，何山洞府深。此时堪伫望，万象豁尘襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 旅中秋月有怀 ----------
    {
        "id": "zhu-qing-yu-110",
        "title": "旅中秋月有怀",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "久客未还乡，中秋倍可伤。暮天飞旅雁，故国在衡阳。",
            "岛外归云迥，林间坠叶黄。数宵千里梦，时见旧书堂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 十六夜月 ----------
    {
        "id": "zhu-qing-yu-111",
        "title": "十六夜月",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "昨夜忽已过，冰轮始觉亏。孤光犹不定，浮世更堪疑。",
            "影落澄江海，寒生静路岐。皎然银汉外，长有众星随。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 行路难 ----------
    {
        "id": "zhu-qing-yu-112",
        "title": "行路难",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "世事浇浮后，艰难向此生。人心不自足，公道为谁平。",
            "德丧淳风尽，年荒蔓草盈。堪悲山下路，非只客中行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 闲居冬末寄友人 ----------
    {
        "id": "zhu-qing-yu-113",
        "title": "闲居冬末寄友人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "短亭分袂后，倚槛思偏孤。雨雪落残腊，轮蹄在远涂。",
            "人情难故旧，草色易凋枯。共有男儿事，何年入帝都。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 望九疑 ----------
    {
        "id": "zhu-qing-yu-114",
        "title": "望九疑",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "浮生犹役役，未得便寻真。白日如无路，青山岂有人。",
            "烟收遥岫小，雨过晚川新。倚杖何凝望，中宵梦往频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 赠陈逸人 ----------
    {
        "id": "zhu-qing-yu-115",
        "title": "赠陈逸人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "乐道辞荣禄，安居桂水东。得闲多事外，知足少年中。",
            "药圃无凡草，松庭有素风。朝昏吟步处，琴酒与谁同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 湖中闲夜遣兴 ----------
    {
        "id": "zhu-qing-yu-116",
        "title": "湖中闲夜遣兴",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "钓艇同琴酒，良宵背水滨。风波不起处，星月尽随身。",
            "浦迥湘烟卷，林香岳气春。谁知此中兴，宁羡五湖人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 题娥皇庙 ----------
    {
        "id": "zhu-qing-yu-117",
        "title": "题娥皇庙",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "娥皇挥涕处，东望九疑天。往事难重问，孤峰尚惨然。",
            "夜深寒峒响，秋近碧萝鲜。未省明君意，遗踪万古传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 送友人赴举 ----------
    {
        "id": "zhu-qing-yu-118",
        "title": "送友人赴举",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "世路□□久，嗟君进取身。十年虽苦志，万里托何人。",
            "处困非乖道，求名本为亲。惟应□□意，先与化龙鳞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 中秋月 ----------
    {
        "id": "zhu-qing-yu-119",
        "title": "中秋月",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "自古分功定，唯应缺又盈。一宵当皎洁，四海尽澄清。",
            "静觉风微起，寒过雪乍倾。孤高稀此遇，吟赏倍牵情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 宿山居 ----------
    {
        "id": "zhu-qing-yu-120",
        "title": "宿山居",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "山店灯前客，酬身未有媒。乡关贫后别，风雨夜深来。",
            "上国求丹桂，衡门长绿苔。堪惊双鬓雪，不待岁寒催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 夏末留别洞庭知己 ----------
    {
        "id": "zhu-qing-yu-121",
        "title": "夏末留别洞庭知己",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "清秋时节近，分袂独凄然。此地折高柳，何门听暮蝉。",
            "浪摇湖外日，山背楚南天。空感迢迢事，荣归在几年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 过洞庭 ----------
    {
        "id": "zhu-qing-yu-122",
        "title": "过洞庭",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "帆挂狂风起，茫茫既往时。波涛如未息，舟楫亦堪疑。",
            "旅雁投孤岛，长天下四维。前程有平处，谁敢与心期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 旅中过重阳 ----------
    {
        "id": "zhu-qing-yu-123",
        "title": "旅中过重阳",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "一岁重阳至，羁游在异乡。登高思旧友，满目是穷荒。",
            "草际飞云片，天涯落雁行。故山篱畔菊，今日为谁黄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 送人下第归 ----------
    {
        "id": "zhu-qing-yu-124",
        "title": "送人下第归",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "独立身难达，新春与志违。异乡青草长，故国白头归。",
            "岸阔湖波溢，程遥楚岫微。高秋期再会，此去莫忘机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 叙吟 ----------
    {
        "id": "zhu-qing-yu-125",
        "title": "叙吟",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "雅道辛勤久，潜疑鬓雪侵。未能酬片善，难更免孤吟。",
            "有景皆牵思，无愁不到心。遥天一轮月，几夜见西沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 塞下感怀 ----------
    {
        "id": "zhu-qing-yu-126",
        "title": "塞下感怀",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "塞下闲为客，乡心岂易安。程涂过万里，身事尚孤寒。",
            "竟日风沙急，临秋草木残。何年方致主，时拂剑尘看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 宿江馆 ----------
    {
        "id": "zhu-qing-yu-127",
        "title": "宿江馆",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "江馆迢遥处，知音信渐赊。夜深乡梦觉，窗下月明斜。",
            "起雁看荒草，惊波尚白沙。那堪动乡思，故国在天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 早梅 ----------
    {
        "id": "zhu-qing-yu-128",
        "title": "早梅",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "天然根性异，万物尽难陪。自古承春早，严冬斗雪开。",
            "艳寒宜雨露，香冷隔尘埃。堪把依松竹，良涂一处栽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 夏日访贞上人院 ----------
    {
        "id": "zhu-qing-yu-129",
        "title": "夏日访贞上人院",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "炎夏寻灵境，高僧澹荡中。命棋隈绿竹，尽日有清风。",
            "流水离经阁，闲云入梵宫。此时袪万虑，直似出尘笼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 春日旅次 ----------
    {
        "id": "zhu-qing-yu-130",
        "title": "春日旅次",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "林中莺又啭，为客恨因循。故里遥千里，青春过数春。",
            "弟兄来渐少，岁月去何频。早晚荣归计，中堂会所亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 赠至寂禅师 ----------
    {
        "id": "zhu-qing-yu-131",
        "title": "赠至寂禅师",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "处世唯据衲，禅门几岁寒。法空无所染，性悟不多看。",
            "竟日门长掩，相逢草自残。有时寻道侣，飞锡度峰峦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 闲居即事 ----------
    {
        "id": "zhu-qing-yu-132",
        "title": "闲居即事",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "深嶂多幽景，闲居野兴清。满庭秋雨过，连夜绿苔生。",
            "石面横琴坐，松阴采药行。超然尘事外，不似绊浮名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 废宅花 ----------
    {
        "id": "zhu-qing-yu-133",
        "title": "废宅花",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "数树荒庭上，芬芳映绿苔。自缘逢暖发，不是为人开。",
            "色艳莺犹在，香消蝶已回。相从无胜事，谁向此倾杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 寄友人 ----------
    {
        "id": "zhu-qing-yu-134",
        "title": "寄友人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "当代知音少，相思在此身。一分南北路，长问往来人。",
            "是处应为客，何门许扫尘。凭书正惆怅，蜀魄数声新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 途中感怀 ----------
    {
        "id": "zhu-qing-yu-135",
        "title": "途中感怀",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "世上名利牵，途中意惨然。到家能几日，为客便经年。",
            "迹似萍随水，情同鹤在田。何当功业遂，归路下遥天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 赠道者 ----------
    {
        "id": "zhu-qing-yu-136",
        "title": "赠道者",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "独住神仙境，门当瀑布开。地多临水石，行不惹尘埃。",
            "风起松花散，琴鸣鹤翅回。还归九天上，时有故人来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 长安春日野中 ----------
    {
        "id": "zhu-qing-yu-137",
        "title": "长安春日野中",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "青春思楚地，闲步出秦城。满眼是岐路，何年见弟兄。",
            "烟霞装媚景，霄汉指前程。尽日徘徊处，归鸿过玉京。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 长城 ----------
    {
        "id": "zhu-qing-yu-138",
        "title": "长城",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "秦帝防胡虏，关心倍可嗟。一人如有德，四海尽为家。",
            "往事乾坤在，荒基草木遮。至今徒者骨，犹自哭风沙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 酬李躔侍御 ----------
    {
        "id": "zhu-qing-yu-139",
        "title": "酬李躔侍御",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "此去非关兴，君行不当游。无因两处马，共饮一溪流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 140. 别李侍御后亭夜坐却寄 ----------
    {
        "id": "zhu-qing-yu-140",
        "title": "别李侍御后亭夜坐却寄",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "已作亭下别，未忘灯下情。吟多欲就枕，更漏转分明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 141. 题钱宇别墅 ----------
    {
        "id": "zhu-qing-yu-141",
        "title": "题钱宇别墅",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "林居向晚饶清景，惜去非关恋酒杯。石净每因杉露滴，",
            "地幽渐觉水禽来。药蔬秋后供僧尽，竹杖吟中望月回。",
            "红叶闲飘篱落迥，行人远见草堂开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 142. 近试上张籍水部（一作闺意献张水部） ----------
    {
        "id": "zhu-qing-yu-142",
        "title": "近试上张籍水部（一作闺意献张水部）",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "洞房昨夜停红烛，待晓堂前拜舅姑。",
            "妆罢低声问夫婿，画眉深浅入时无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 143. 留别卢玄休归荆门 ----------
    {
        "id": "zhu-qing-yu-143",
        "title": "留别卢玄休归荆门",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "江边离别心，言罢各沾襟。以我去帆远，知君离恨深。",
            "云开孤鸟出，浪起白鸥沈。更作来年约，阳台许伴寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 144. 采莲 ----------
    {
        "id": "zhu-qing-yu-144",
        "title": "采莲",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "隔烟花草远濛濛，恨个来时路不同。",
            "正是停桡相遇处，鸳鸯飞去急流中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 145. 都门晚望 ----------
    {
        "id": "zhu-qing-yu-145",
        "title": "都门晚望",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "绿槐花堕御沟边，步出都门雨后天。",
            "日暮野人耕种罢，烽楼原上一条烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 146. 舜井 ----------
    {
        "id": "zhu-qing-yu-146",
        "title": "舜井",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "碧甃磷磷不记年，青萝锁在小山颠。",
            "向来下视千山水，疑是苍梧万里天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 147. 商州王中丞留吃枳壳 ----------
    {
        "id": "zhu-qing-yu-147",
        "title": "商州王中丞留吃枳壳",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "方物就中名最远，只应愈疾味偏佳。",
            "若交尽乞人人与，采尽商山枳壳花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 148. 登玄都阁 ----------
    {
        "id": "zhu-qing-yu-148",
        "title": "登玄都阁",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "野色晴宜上阁看，树阴遥映御沟寒。",
            "豪家旧宅无人住，空见朱门锁牡丹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 149. 赠凤翔柳司录 ----------
    {
        "id": "zhu-qing-yu-149",
        "title": "赠凤翔柳司录",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "杏园北寺题名日，数到如今四十年。",
            "点检生涯与官职，一茎野竹在身边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 150. 啄木儿 ----------
    {
        "id": "zhu-qing-yu-150",
        "title": "啄木儿",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "丁丁向晚急还稀，啄遍庭槐未肯归。",
            "终日与君除蠹害，莫嫌无事不频飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 151. 榜曲 ----------
    {
        "id": "zhu-qing-yu-151",
        "title": "榜曲",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "荷花明灭水烟空，惆怅来时径不同。",
            "欲到前洲堪入处，鸳鸯飞出碧流中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 152. 逢山人 ----------
    {
        "id": "zhu-qing-yu-152",
        "title": "逢山人",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "星月相逢现此身，自然无迹又无尘。",
            "秋来若向金天会，便是青莲叶上人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 153. 过耶溪 ----------
    {
        "id": "zhu-qing-yu-153",
        "title": "过耶溪",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "春溪缭绕出无穷，两岸桃花正好风。",
            "恰是扁舟堪入处，鸳鸯飞起碧流中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 154. 贺张水部员外拜命 ----------
    {
        "id": "zhu-qing-yu-154",
        "title": "贺张水部员外拜命",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "省中官最美，无似水曹郎。前代佳名逊，当时重姓张。",
            "白须吟丽句，红叶吐朝阳。徒有归山意，君恩未可忘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 155. 送璧州刘使君 ----------
    {
        "id": "zhu-qing-yu-155",
        "title": "送璧州刘使君",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "王府登朝后，巴乡典郡新。江分入峡路，山见采鞭人。",
            "旧业孤城梦，生祠几处身。知君素清俭，料得却来贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 156. 赠江夏卢使君 ----------
    {
        "id": "zhu-qing-yu-156",
        "title": "赠江夏卢使君",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "诗人中最屈，无与使君俦。白发虽求退，明时合见收。",
            "登山犹自健，纵酒可多愁。好是能骑马，相逢见鄂州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 157. 送崔秀才游江陵 ----------
    {
        "id": "zhu-qing-yu-157",
        "title": "送崔秀才游江陵",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "樽前荆楚客，云外思萦回。秦野春已尽，商山花正开。",
            "鸥惊帆乍起，虹见雨初来。自有归期在，蝉声处处催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 158. 观涛 ----------
    {
        "id": "zhu-qing-yu-158",
        "title": "观涛",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "木落霜飞天地清，空江百里见潮生。鲜飙出海鱼龙气，",
            "晴雪喷山雷鼓声。云日半阴川渐满，客帆皆过浪难平。",
            "高楼晓望无穷意，丹叶黄花绕郡城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 159. 南湖 ----------
    {
        "id": "zhu-qing-yu-159",
        "title": "南湖",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "湖上微风小槛凉，翻翻菱荇满回塘。野船著岸入春草，",
            "水鸟带波飞夕阳。芦叶有声疑露雨，浪花无际似潇湘。",
            "飘然蓬艇东归客，尽日相看忆楚乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 160. 镜湖西岛言事 ----------
    {
        "id": "zhu-qing-yu-160",
        "title": "镜湖西岛言事",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "慵拙幸便荒僻地，纵闻猿鸟亦何愁。偶因药酒欺梅雨，",
            "却著寒衣过麦秋。岁计有馀添橡实，生涯一半在渔舟。",
            "世人若便无知己，应向此溪成白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 161. 送刘思复南河从军 ----------
    {
        "id": "zhu-qing-yu-161",
        "title": "送刘思复南河从军",
        "author": "朱庆馀",
        "poet_id": "zhu-qing-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "七千里别宁无恨，且贵从军乐事多。不驻节旄先候发，",
            "偶逢山寺亦难过。蛮人独放畬田火，海兽群游落日波。",
            "远作受恩身不易，莫抛书剑近笙歌。",
            "第五百一十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]