# -*- coding: utf-8 -*-
"""
栖白卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 16 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 边思 ----------
    {
        "id": "qi-bai-1",
        "title": "边思",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "西北黄云暮，声声画角愁。阴山一夜雨，白草四郊秋。",
            "乱雁鸣寒渡，飞沙入废楼。何时番色尽，此地见芳洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 八月十五夜玩月 ----------
    {
        "id": "qi-bai-2",
        "title": "八月十五夜玩月",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "寻常三五夜，不是不婵娟。及至中秋满，还胜别夜圆。",
            "清光凝有露，皓魄爽无烟。自古人皆望，年来又一年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寻山僧真胜上人不遇 ----------
    {
        "id": "qi-bai-3",
        "title": "寻山僧真胜上人不遇",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "松下禅栖所，苔滋径莫分。青山春暮见，流水夜深闻。",
            "不坐看心石，应随出定云。猿猱非可问，岩谷自空曛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠李溟秀才 ----------
    {
        "id": "qi-bai-4",
        "title": "赠李溟秀才",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "南居古庙深，高树宿山禽。明月上清汉，骚人动楚吟。",
            "数篇正始韵，一片补亡心。孤悄欺何谢，云波不可寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送石秀才 ----------
    {
        "id": "qi-bai-5",
        "title": "送石秀才",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "正是叹羁游，知音拜楚侯。何须辞远道，自可乐扁舟。",
            "倚棹江洲雨，闻猿岛岫秋。谢家山水兴，终日待诗流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送造微上人游五台及礼本师 ----------
    {
        "id": "qi-bai-6",
        "title": "送造微上人游五台及礼本师",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "寒空金锡响，欲过渭阳津。极目多来雁，孤城少故人。",
            "与师虽别久，于法本相亲。又对清凉月，中宵语宿因。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送禅师宗极归玉峰 ----------
    {
        "id": "qi-bai-7",
        "title": "送禅师宗极归玉峰",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "背郭去归宿，头陀意颇浓。鹤争栖远树，猿斗上孤峰。",
            "夜戍经霜月，秋城过雨钟。由来无定止，何处访高踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送僧归旧山 ----------
    {
        "id": "qi-bai-8",
        "title": "送僧归旧山",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "谈空与破邪，献寿复荣家。白日得何偈，青天落几花。",
            "传灯皆有分，化俗独无涯。却入中峰寺，还知有聚沙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送圆仁三藏归本国 ----------
    {
        "id": "qi-bai-9",
        "title": "送圆仁三藏归本国",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "家山临晚日，海路信归桡。树灭浑无岸，风生只有潮。",
            "岁穷程未尽，天末国仍遥。已入闽王梦，香花境外邀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送王炼师归嵩岳 ----------
    {
        "id": "qi-bai-10",
        "title": "送王炼师归嵩岳",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "飘然绿毛节，杳去洛城端。隔水见秋岳，兼霜扫石坛。",
            "一溪松色古，半夜鹤声寒。迥与人寰别，劳生不可观。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 寿昌节赋得红云表夏日 ----------
    {
        "id": "qi-bai-11",
        "title": "寿昌节赋得红云表夏日",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "景候融融阴气潜，如峰云共火相兼。霞光捧日登天上，",
            "丹彩乘风入殿檐。行逐赤龙千岁出，明当朱夏万方瞻。",
            "微臣多幸逢佳节，得赋殊祥近御帘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 经废宫 ----------
    {
        "id": "qi-bai-12",
        "title": "经废宫",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "终日河声咽暮空，烟愁此地昼濛濛。锦帆东去沙侵苑，",
            "玉辇西来树满宫。鲁客望津天欲雪，朔鸿离岸苇生风。",
            "那堪独立思前事，回首残阳雉堞红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 赠识古法师 ----------
    {
        "id": "qi-bai-13",
        "title": "赠识古法师",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "重城深寺讲初休，却忆家山访旧游。对月与君相送夜，",
            "闻蛩教我独惊秋。云心杳杳难为别，鹤性萧萧不可留。",
            "遥想孤舟清渭上，飘然帆影起离愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 月夜怀刘秀才（一作元孚诗） ----------
    {
        "id": "qi-bai-14",
        "title": "月夜怀刘秀才（一作元孚诗）",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "独夜相思但自劳，阮生吟罢梦云涛。",
            "此时小定未禅寂，古塔月中松磬高。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 寄南山景禅师 ----------
    {
        "id": "qi-bai-15",
        "title": "寄南山景禅师",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "一度林前见远公，静闻真语世情空。",
            "至今寂寞禅心在，任起桃花柳絮风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 哭刘得仁 ----------
    {
        "id": "qi-bai-16",
        "title": "哭刘得仁",
        "author": "栖白",
        "poet_id": "qi-bai",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "为爱诗名吟至死，风魂雪魄去难招。",
            "直须桂子落坟上，生得一枝冤始消。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]