# -*- coding: utf-8 -*-
"""
畅当卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 15 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 南充谢郡客游澧州留赠宇文中丞 ----------
    {
        "id": "chang-dang-1",
        "title": "南充谢郡客游澧州留赠宇文中丞",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "仆本濩落人，辱当州郡使。量力颇及早，谢归今即己。",
            "萧萧若凌虚，襟带顿销靡。车服率然来，涔阳作游子。",
            "郁郁寡开颜，默默独行李。忽逢平生友，一笑方在此。",
            "秋情宁风日，楚思浩云水。为语弋林者，冥冥鸿远矣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 宿报恩寺精舍 ----------
    {
        "id": "chang-dang-2",
        "title": "宿报恩寺精舍",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "钟梵送沈景，星多露渐光。风中兰靡靡，月下树苍苍。",
            "夜殿若山横，深松如涧凉。羸然虎溪子，迟我一虚床。",
            "杳杳空寂舍，濛濛莲桂香。拥褐依西壁，纱灯霭中央。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 自平阳馆赴郡 ----------
    {
        "id": "chang-dang-3",
        "title": "自平阳馆赴郡",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "晨兴平阳馆，见月沈江水。溶溶山雾披，肃肃沙鹭起。",
            "奉恩谬符竹，伏轼省顽鄙。何当施教化，愧迎小郡吏。",
            "寥落火耕俗，征途青冥里。德绥及吾民，不德将鹿矣。",
            "擒奸非性能，多愍会衰齿。恭承共理诏，恒惧坠诸地。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 天柱隐所重答江州应物 ----------
    {
        "id": "chang-dang-4",
        "title": "天柱隐所重答江州应物",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "寂寞一怅望，秋风山景清。此中惟草色，翻意见人行。",
            "荒径饶松子，深萝绝鸟声。阳崖全带日，宽嶂偶通耕。",
            "拙昧难容世，贫寒别有情。烦君琼玖赠，幽懒百无成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 山居酬韦苏州见寄 ----------
    {
        "id": "chang-dang-5",
        "title": "山居酬韦苏州见寄",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "孤柴泄烟处，此中山叟居。观云宁有事，耽酒讵知馀。",
            "水定鹤翻去，松歌峰俨如。犹烦使君问，更欲结深庐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 春日过奉诚园（一作曲江，一作玉林园） ----------
    {
        "id": "chang-dang-6",
        "title": "春日过奉诚园（一作曲江，一作玉林园）",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "帝里阳和日，游人到御园。暖催新景气，春认旧兰荪。",
            "咏德先臣没，成蹊大树存。见桐犹近井，看柳尚依门。",
            "献地非更宅，遗忠永奉恩。又期攀桂后，来赏百花繁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 军中醉饮寄沈八刘叟（一作杜甫诗） ----------
    {
        "id": "chang-dang-7",
        "title": "军中醉饮寄沈八刘叟（一作杜甫诗）",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "酒渴爱江清，馀酣漱晚汀。软莎欹坐稳，冷石醉眠醒。",
            "野膳随行帐，华音发从伶。数杯君不见，都已遣沈冥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 偶宴西蜀摩诃池 ----------
    {
        "id": "chang-dang-8",
        "title": "偶宴西蜀摩诃池",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "珍木郁清池，风荷左右披。浅觞宁及醉，慢舸不知移。",
            "荫簟流光冷，凝簪照影欹。胡为独羁者，雪涕向涟漪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 奉送杜中丞赴洪州 ----------
    {
        "id": "chang-dang-9",
        "title": "奉送杜中丞赴洪州",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "诏出凤凰宫，新恩连帅雄。江湖经战阵，草木待仁风。",
            "豪右贪威爱，纡繁德简通。多惭君子顾，攀饯路尘中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 九日陪皇甫使君泛江宴赤岸亭 ----------
    {
        "id": "chang-dang-10",
        "title": "九日陪皇甫使君泛江宴赤岸亭",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "羁旅逢佳节，逍遥忽见招。同倾菊花酒，缓棹木兰桡。",
            "平楚堪愁思，长江去寂寥。猿啼不离峡，滩沸镇如潮。",
            "举目关山异，伤心乡国遥。徒言欢满座，谁觉客魂消。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 蒲中道中二首 ----------
    {
        "id": "chang-dang-11",
        "title": "蒲中道中二首",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "苍苍中条山，厥形极奇磈。我欲涉其崖，濯足黄河水。",
            "古刹栖柿林，绿阴覆苍瓦。岁晏来品题，拾叶总堪写。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 登鹳雀楼 ----------
    {
        "id": "chang-dang-12",
        "title": "登鹳雀楼",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "迥临飞鸟上，高出世尘间。天势围平野，河流入断山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 宿潭上二首 ----------
    {
        "id": "chang-dang-13",
        "title": "宿潭上二首",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "夜潭有仙舸，与月当水中。嘉宾爱明月，游子惊秋风。",
            "青蒲野陂水，白露明月天。中夜秋风起，心事坐潸然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 别卢纶 ----------
    {
        "id": "chang-dang-14",
        "title": "别卢纶",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "故交君独在，又欲与君离。我有新秋泪，非关宋玉悲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 题沈八斋 ----------
    {
        "id": "chang-dang-15",
        "title": "题沈八斋",
        "author": "畅当",
        "poet_id": "chang-dang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "江斋一入何亭亭，因寄沦涟心杳冥。",
            "绿绮琴弹白雪引，乌丝绢勒黄庭经。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]