# -*- coding: utf-8 -*-
"""
郑畋卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 15 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 中秋月直禁苑 ----------
    {
        "id": "zheng-tian-1",
        "title": "中秋月直禁苑",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "禁署方怀忝，纶闱已再加。暂来西掖路，还整上清槎。",
            "恍惚归丹地，深严宿绛霞。幽襟聊自适，闲弄紫薇花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 麦穗两岐 ----------
    {
        "id": "zheng-tian-2",
        "title": "麦穗两岐",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "圣虑忧千亩，嘉苗荐两岐。如云方表盛，成穗忽标奇。",
            "瑞露纵横滴，祥风左右吹。讴歌连上苑，化日遍平陂。",
            "史册书堪重，丹青画更宜。愿依连理树，俱作万年枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 五月一日紫宸候对时属禁直穿内而行因书六韵 ----------
    {
        "id": "zheng-tian-3",
        "title": "五月一日紫宸候对时属禁直穿内而行因书六韵",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "朱夏五更后，步廊三里馀。有人从翰苑，穿入内中书。",
            "漏响飘银箭，灯光照玉除。禁扉犹锁钥，宫妓已妆梳。",
            "紫府游应似，钧天梦不如。尘埃九重外，谁信在清虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题缑山王子晋庙 ----------
    {
        "id": "zheng-tian-4",
        "title": "题缑山王子晋庙",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "有昔灵王子，吹笙溯泬。六宫攀不住，三岛去相招。",
            "亡国原陵古，宾天岁月遥。无蹊窥海曲，有庙访山椒。",
            "石帐龙蛇拱，云栊彩翠销。露坛装琬琰，真像写松乔。",
            "珠馆青童宴，琳宫阿母朝。气舆仙女侍，天马吏兵调。",
            "湘妓红丝瑟，秦郎白管箫。西城要绰约，南岳命娇娆。",
            "句曲觞金洞，天台啸石桥。晚花珠弄蕊，春茹玉生苗。",
            "二景神光秘，三元宝箓饶。雾垂鸦翅发，冰束虎章腰。",
            "鹤驭争衔箭，龙妃合献绡。衣从星渚浣，丹就日宫烧。",
            "物外花尝满，人间叶自凋。望台悲汉戾，阅水笑梁昭。",
            "古殿香残灺，荒阶柳长条。几曾期七日，无复降重霄。",
            "嵩岭连天汉，伊澜入海潮。何由得真诀，使我佩环飘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 初秋寓直三首 ----------
    {
        "id": "zheng-tian-5",
        "title": "初秋寓直三首",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "晓星独挂结麟楼，三殿风高药树秋。",
            "玉笛数声飘不住，问人依约在东头。",
            "宿鸟翩翩落照微，石台楼阁锁重扉。",
            "步廊无限金羁响，应是诸司扈从归。",
            "幽阁焚香万虑凝，下帘胎息过禅僧。",
            "玉堂分照无人后，消尽金盆一碗冰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 夜景又作 ----------
    {
        "id": "zheng-tian-6",
        "title": "夜景又作",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "铃绦无响闭珠宫，小阁凉添玉蕊风。",
            "枕簟满床明月到，自疑身在五云中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 杪秋夜直 ----------
    {
        "id": "zheng-tian-7",
        "title": "杪秋夜直",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "蕊宫裁诏与宵分，虽在青云忆白云。",
            "待报君恩了归去，山翁何急草移文。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 禁直寄崔员外 ----------
    {
        "id": "zheng-tian-8",
        "title": "禁直寄崔员外",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "银台楼北蕊珠宫，夐与人间路不同。",
            "在省五更春睡侣，早来分梦玉堂中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 闻号 ----------
    {
        "id": "zheng-tian-9",
        "title": "闻号",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "陛兵偏近羽林营，夜静仍传禁号声。",
            "应笑执金双阙下，近南犹隔两重城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 禁直和人饮酒 ----------
    {
        "id": "zheng-tian-10",
        "title": "禁直和人饮酒",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "卉醴陀花物外香，清浓标格胜椒浆。",
            "我来尚有钧天会，犹得金尊半日尝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 下直早出 ----------
    {
        "id": "zheng-tian-11",
        "title": "下直早出",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "诸司人尽马蹄稀，紫帕云竿九钉归。",
            "偏觉石台清贵处，榜悬金字射晴晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 金銮坡上南望 ----------
    {
        "id": "zheng-tian-12",
        "title": "金銮坡上南望",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "玉晨钟韵上清虚，画戟祥烟拱帝居。",
            "极眼向南无限地，绿烟深处认中书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 酬隐珪舍人寄红烛 ----------
    {
        "id": "zheng-tian-13",
        "title": "酬隐珪舍人寄红烛",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "蜜炬殷红画不如，且将归去照吾庐。",
            "今来并得三般事，灵运诗篇逸少书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 马嵬坡 ----------
    {
        "id": "zheng-tian-14",
        "title": "马嵬坡",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "玄宗回马杨妃死，云雨虽亡日月新。",
            "终是圣明天子事，景阳宫井又何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 句 ----------
    {
        "id": "zheng-tian-15",
        "title": "句",
        "author": "郑畋",
        "poet_id": "zheng-tian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "圆明青z3饭，光润碧霞浆。（见《古今诗话》）。",
            "浴殿晴秋倘中谢，残英犹可醉琼杯。（《紫薇花》。",
            "见《海录碎事》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]