# -*- coding: utf-8 -*-
"""
潘咸卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 登明戍堡 ----------
    {
        "id": "pan-xian-1",
        "title": "登明戍堡",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "来经古城上，极目思无穷。寇尽烟萝外，人归蔓草中。",
            "峰峦当阙古，堞垒对云空。不见昔名将，徒称有战功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送陈明府之任 ----------
    {
        "id": "pan-xian-2",
        "title": "送陈明府之任",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "客见天台县，闾阎树色间。骖回几临水，带缓独开山。",
            "吏散落花尽，人居远岛闲。过于老莱子，端简独承颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 长安春暮 ----------
    {
        "id": "pan-xian-3",
        "title": "长安春暮",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "客在关西春暮夜，还同江外已清明。",
            "三更独立看花月，惟欠子规啼一声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 舟行 ----------
    {
        "id": "pan-xian-4",
        "title": "舟行",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "平沙极浦无人度，犹系孤舟寒草西。",
            "半夜起看潮上月，万山中有一猿啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送僧 ----------
    {
        "id": "pan-xian-5",
        "title": "送僧",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "阙下僧归山顶寺，却看朝日下方明。",
            "莫道野人寻不见，半天云里有钟声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 句 ----------
    {
        "id": "pan-xian-6",
        "title": "句",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "栈踏猿声暮，江看剑影秋。（送人游蜀）",
            "僧老白云上，磬寒高鸟边。",
            "心已同猿狖，不闻人是非。",
            "行人渡流水，白马入前山。",
            "秋深雪满黄金塞，夜夜鸿声入汉阳。（上并见《主客图》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 芍药 ----------
    {
        "id": "pan-xian-7",
        "title": "芍药",
        "author": "潘咸",
        "poet_id": "pan-xian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "闲来竹亭赏，赏极蕊珠宫。叶已尽馀翠，花才半展红。",
            "媚欺桃李色，香夺绮罗风。每到春残日，芳华处处同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]