# -*- coding: utf-8 -*-
"""
吴仁璧卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 投谢钱武肃 ----------
    {
        "id": "wu-ren-bi-1",
        "title": "投谢钱武肃",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "东门上相好知音，数尽台前郭隗金。累重虽然容食椹，",
            "力微无计报焚林。弊貂不称芙蓉幕，衰朽仍惭玳瑁簪。",
            "十里溪光一山月，可堪从此负归心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 客路 ----------
    {
        "id": "wu-ren-bi-2",
        "title": "客路",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "人寰急景如波委，客路浮云似盖轻。",
            "回首故山天外碧，十年无计却归耕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 南徐题友人郊居 ----------
    {
        "id": "wu-ren-bi-3",
        "title": "南徐题友人郊居",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "门前樵径连江寺，岸下渔矶系海槎。",
            "待到秋深好时节，与君长醉隐侯家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 读度人经寄郑仁表 ----------
    {
        "id": "wu-ren-bi-4",
        "title": "读度人经寄郑仁表",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "身虽一旦尘中老，名拟三清会里题。",
            "二午九斋馀日在，请君相伴醉如泥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 秋日听僧弹琴 ----------
    {
        "id": "wu-ren-bi-5",
        "title": "秋日听僧弹琴",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "金徽玉轸韵泠然，言下浮生指下泉。",
            "恰称秋风西北起，一时吹入碧湘烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 贾谊 ----------
    {
        "id": "wu-ren-bi-6",
        "title": "贾谊",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "扶持一疏满遗编，汉陛前头正少年。",
            "谁道恃才轻绛灌，却将惆怅吊湘川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 春雪 ----------
    {
        "id": "wu-ren-bi-7",
        "title": "春雪",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "雪霁凝光入坐寒，天明犹自卧袁安。",
            "貂裘穿后鹤氅敝，自此风流不足看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 衰柳 ----------
    {
        "id": "wu-ren-bi-8",
        "title": "衰柳",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "金风渐利露珠团，广陌长堤黛色残。",
            "水殿狂游隋炀帝，一千馀里可堪看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 凤仙花 ----------
    {
        "id": "wu-ren-bi-9",
        "title": "凤仙花",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "香红嫩绿正开时，冷蝶饥蜂两不知。",
            "此际最宜何处看，朝阳初上碧梧枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 金钱花 ----------
    {
        "id": "wu-ren-bi-10",
        "title": "金钱花",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "浅绛浓香几朵匀，日熔金铸万家新。",
            "堪疑刘宠遗芳在，不许山阴父老贫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 钱塘鹤 ----------
    {
        "id": "wu-ren-bi-11",
        "title": "钱塘鹤",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "人间路霭青天半，鳌岫云生碧海涯。",
            "虽抱雕笼密扃钥，可能长在叔伦家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 句 ----------
    {
        "id": "wu-ren-bi-12",
        "title": "句",
        "author": "吴仁璧",
        "poet_id": "wu-ren-bi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "为惜苔钱妨换砌，因怜山色旋开尊。（闲居）",
            "高阁烟霞禅客睡，满城尘土世人忙。（游法华寺）",
            "五龙金角向星斗，三洞玉音愁鬼神。（赠道士）",
            "蒲草薄裁连蒂白，胭脂浓染半葩红。（题莺粟花，",
            "以上并《雅言杂载》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]