# -*- coding: utf-8 -*-
"""
储嗣宗卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 39 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 登芜城 ----------
    {
        "id": "chu-si-zong-1",
        "title": "登芜城",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "昔人登此地，丘垄已前悲。今日又非昔，春风能几时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 沧浪峡（一作储光羲诗） ----------
    {
        "id": "chu-si-zong-2",
        "title": "沧浪峡（一作储光羲诗）",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "沧浪临古道，道上石成尘。自有沧浪峡，谁为无事人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 垓城 ----------
    {
        "id": "chu-si-zong-3",
        "title": "垓城",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "百战未言非，孤军惊夜围。山河意气尽，泪湿美人衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 南陂远望 ----------
    {
        "id": "chu-si-zong-4",
        "title": "南陂远望",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "闲门横古塘，红树已惊霜。独立望秋草，野人耕夕阳。",
            "孤烟起蜗舍，飞鹭下渔梁。唯有田家事，依依似故乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 宿玉箫宫 ----------
    {
        "id": "chu-si-zong-5",
        "title": "宿玉箫宫",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "尘飞不到空，露湿翠微宫。鹤影石桥月，箫声松殿风。",
            "绿毛辞世女，白发入壶翁。借问烧丹处，桃花几遍红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 晚眺徐州延福寺 ----------
    {
        "id": "chu-si-zong-6",
        "title": "晚眺徐州延福寺",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "杉风振旅尘，晚景藉芳茵。片水明在野，万花深见人。",
            "静依归鹤思，远惜旧山春。今日惜携手，寄怀吟白蘋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 宿甘棠馆 ----------
    {
        "id": "chu-si-zong-7",
        "title": "宿甘棠馆",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "尘迹入门尽，悄然江海心。水声巫峡远，山色洞庭深。",
            "风桂落寒子，岚烟凝夕阴。前轩鹤归处，萝月思沈沈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 和茅山高拾遗忆山中杂题五首·山泉 ----------
    {
        "id": "chu-si-zong-8",
        "title": "和茅山高拾遗忆山中杂题五首·山泉",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "香味清机仙府回，萦纡乱石便流杯。",
            "春风莫泛桃花去，恐引凡人入洞来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 和茅山高拾遗忆山中杂题五首·巢鹤 ----------
    {
        "id": "chu-si-zong-9",
        "title": "和茅山高拾遗忆山中杂题五首·巢鹤",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "千万云间丁令威，殷勤仙骨莫先飞。",
            "若逢茅氏传消息，贞白先生不久归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 和茅山高拾遗忆山中杂题五首·胡山 ----------
    {
        "id": "chu-si-zong-10",
        "title": "和茅山高拾遗忆山中杂题五首·胡山",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "犬入五云音信绝，凤楼凝碧悄无声。",
            "焚香古洞步虚夜，露湿松花空月明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 和茅山高拾遗忆山中杂题五首·小楼 ----------
    {
        "id": "chu-si-zong-11",
        "title": "和茅山高拾遗忆山中杂题五首·小楼",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "松杉风外乱山青，曲几焚香对石屏。",
            "空忆去年春雨后，燕泥时污太玄经。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 和茅山高拾遗忆山中杂题五首·山邻 ----------
    {
        "id": "chu-si-zong-12",
        "title": "和茅山高拾遗忆山中杂题五首·山邻",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "石桥春涧已归迟，梦入仙山山不知。",
            "柱史从来非俗吏，青牛道士莫相疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送道士 ----------
    {
        "id": "chu-si-zong-13",
        "title": "送道士",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "泠然御风客，与道自浮沉。黄鹤有归语，白云无忌心。",
            "药炉经月净，天路入壶深。从此分杯后，相思何处寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 宿山馆 ----------
    {
        "id": "chu-si-zong-14",
        "title": "宿山馆",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "寂寞对衰草，地凉凝露华。蝉鸣月中树，风落客前花。",
            "山馆无宿伴，秋琴初别家。自怜千万里，笔砚寄生涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 入浮石山 ----------
    {
        "id": "chu-si-zong-15",
        "title": "入浮石山",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "斜日出门去，残花已过春。鸟声穿叶远，虎迹渡溪新。",
            "入洞几时路，耕田何代人。自惭非避俗，不敢问迷津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送人归故园 ----------
    {
        "id": "chu-si-zong-16",
        "title": "送人归故园",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "远节惨言别，况予心久违。从来忆家泪，今日送君归。",
            "野路正风雪，还乡犹布衣。里中耕稼者，应笑读书非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 得越中书 ----------
    {
        "id": "chu-si-zong-17",
        "title": "得越中书",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "芳草离离思，悠悠春梦馀。池亭千里月，烟水一封书。",
            "诗想怀康乐，文应吊子胥。扁舟恋南越，岂独为鲈鱼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 秋墅 ----------
    {
        "id": "chu-si-zong-18",
        "title": "秋墅",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "欲暮候樵者，望山空翠微。虹随馀雨散，鸦带夕阳归。",
            "穷巷长秋草，孤村时捣衣。谁知多病客，寂寞掩柴扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 哭彭先生 ----------
    {
        "id": "chu-si-zong-19",
        "title": "哭彭先生",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "谷口溪声客自伤，那堪呜咽吊残阳。空阶鹤恋丹青影，",
            "秋雨苔封白石床。主祭孤儿初学语，无媒旅榇未还乡。",
            "门人远赴心丧夜，月满千山旧草堂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 和顾非熊先生题茅山处士闲居 ----------
    {
        "id": "chu-si-zong-20",
        "title": "和顾非熊先生题茅山处士闲居",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "归耕地肺绝尘喧，匣里青萍未报恩。浊酒自怜终日醉，",
            "古风时得野人言。鸟啼碧树闲临水，花满青山静掩门。",
            "唯有阶前芳草色，年年惆怅忆王孙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 长安怀古 ----------
    {
        "id": "chu-si-zong-21",
        "title": "长安怀古",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "祸稔萧墙终不知，生人力屈尽边陲。赤龙已赴东方暗，",
            "黄犬徒怀上蔡悲。面缺崩城山寂寂，土埋冤骨草离离。",
            "秋风解怨扶苏死，露泣烟愁红树枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 过王右丞书堂二首 ----------
    {
        "id": "chu-si-zong-22",
        "title": "过王右丞书堂二首",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "澄潭昔卧龙，章句世为宗。独步声名在，千岩水石空。",
            "野禽悲灌木，落日吊清风。后学攀遗址，秋山闻草虫。",
            "万树影参差，石床藤半垂。萤光虽散草，鸟迹尚临池。",
            "风雅传今日，云山想昔时。感深苏属国，千载五言诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 孤雁 ----------
    {
        "id": "chu-si-zong-23",
        "title": "孤雁",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "孤雁暮飞急，萧萧天地秋。关河正黄叶，消息断青楼。",
            "湘渚烟波远，骊山风雨愁。此时万里道，魂梦绕沧洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 赠隐者 ----------
    {
        "id": "chu-si-zong-24",
        "title": "赠隐者",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "尽室居幽谷，乱山为四邻。雾深知有术，窗静似无人。",
            "鹤语松上月，花明云里春。生涯更何许，尊酒与垂纶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 早春怀薛公裕 ----------
    {
        "id": "chu-si-zong-25",
        "title": "早春怀薛公裕",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "幽独自成愚，柴门日渐芜。陆机初入洛，孙楚又游吴。",
            "失意怨杨柳，异乡闻鹧鸪。相思复相望，春草满南湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 村月 ----------
    {
        "id": "chu-si-zong-26",
        "title": "村月",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "月午篱南道，前村半隐林。田翁独归处，荞麦露花深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 早春 ----------
    {
        "id": "chu-si-zong-27",
        "title": "早春",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "野树花初发，空山独见时。踟蹰历阳道，乡思满南枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 送友人游吴 ----------
    {
        "id": "chu-si-zong-28",
        "title": "送友人游吴",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "吴山青楚吟，草色异乡心。一酌水边酒，数声花下琴。",
            "登楼旧国远，探穴九疑深。更想逢秋节，那堪闻夜砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 赠别 ----------
    {
        "id": "chu-si-zong-29",
        "title": "赠别",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "兰泽伤秋色，临风远别期。东城草虽绿，南浦柳无枝。",
            "直道岂易枉，暗投谁不疑。因君问行役，有泪湿江蓠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 经故人旧居 ----------
    {
        "id": "chu-si-zong-30",
        "title": "经故人旧居",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "万里访遗尘，莺声泪湿巾。古书无主散，废宅与山邻。",
            "宿草风悲夜，荒村月吊人。凄凉问残柳，今日为谁春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 随边使过五原 ----------
    {
        "id": "chu-si-zong-31",
        "title": "随边使过五原",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "偶逐星车犯虏尘，故乡常恐到无因。",
            "五原西去阳关废，日漫平沙不见人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 春怀寄秣陵知友 ----------
    {
        "id": "chu-si-zong-32",
        "title": "春怀寄秣陵知友",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "庐江城外柳堪攀，万里行人尚未还。",
            "借问景阳台下客，谢家谁更卧东山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 宋州月夜感怀 ----------
    {
        "id": "chu-si-zong-33",
        "title": "宋州月夜感怀",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "雁池衰草露沾衣，河水东流万事微。",
            "寂寞青陵台上月，秋风满树鹊南飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 吴宫 ----------
    {
        "id": "chu-si-zong-34",
        "title": "吴宫",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "荒台荆棘多，忠谏竟如何。细草迷宫巷，闲花误绮罗。",
            "前溪徒自绿，子夜不闻歌。怅望清江暮，悠悠东去波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 春游望仙谷 ----------
    {
        "id": "chu-si-zong-35",
        "title": "春游望仙谷",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "清无车马尘，深洞百花春。鸡犬疑沾药，耕桑似避秦。",
            "登山采樵路，临水浣纱人。若得心无事，移家便卜邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 圣女祠 ----------
    {
        "id": "chu-si-zong-36",
        "title": "圣女祠",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "石屏苔色凉，流水绕祠堂。巢鹊疑天汉，潭花似镜妆。",
            "神来云雨合，神去蕙兰香。不复闻双佩，山门空夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 宿范水 ----------
    {
        "id": "chu-si-zong-37",
        "title": "宿范水",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "行人倦游宦，秋草宿湖边。露湿芙蓉渡，月明渔网船。",
            "寒机深竹里，远浪到门前。何处思乡甚，歌声闻采莲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 送顾陶校书归钱塘 ----------
    {
        "id": "chu-si-zong-38",
        "title": "送顾陶校书归钱塘",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "清苦月偏知，南归瘦马迟。橐轻缘换酒，发白为吟诗。",
            "水色西陵渡，松声伍相祠。圣朝思直谏，不是挂冠时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 题云阳高少府衙斋 ----------
    {
        "id": "chu-si-zong-39",
        "title": "题云阳高少府衙斋",
        "author": "储嗣宗",
        "poet_id": "chu-si-zong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "大隐能兼济，轩窗逐胜开。远含云水思，深得栋梁材。",
            "吏散山逾静，庭闲鸟自来。更怜幽砌色，秋雨长莓苔。",
            "第五百九十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]