# -*- coding: utf-8 -*-
"""
裴说卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 52 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 游洞庭湖 ----------
    {
        "id": "pei-shuo-1",
        "title": "游洞庭湖",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "楚云团翠八百里，澧兰吹香堕春水。白头渔子摇苍烟，",
            "鸂鶒眠沙晓惊起。沙头龙叟夜叹忧，铁笛未响春风羞。",
            "露寒紫藟结新愁，城角泣断关河秋。谪仙欲识雷斧手，",
            "刬却古今愁共丑。鲸游碧落杳无踪，作诗三叹君知否。",
            "瀛洲一棹何时还，满江宫锦看湖山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 怀素台歌（一作题怀素台） ----------
    {
        "id": "pei-shuo-2",
        "title": "怀素台歌（一作题怀素台）",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "我呼古人名，鬼神侧耳听：杜甫李白与怀素，",
            "文星酒星草书星。永州东郭有奇怪，笔冢墨池遗迹在。",
            "笔冢低低高如山，墨池浅浅深如海。我来恨不已，",
            "争得青天化为一张纸，高声唤起怀素书，",
            "搦管研朱点湘水。欲归家，重叹嗟。眼前有，三个字：",
            "枯树槎。乌梢蛇，墨老鸦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 闻砧（一作寄边衣） ----------
    {
        "id": "pei-shuo-3",
        "title": "闻砧（一作寄边衣）",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "深闺乍冷鉴开箧，玉箸微微湿红颊。一阵霜风杀柳条，",
            "浓烟半夜成黄叶。垂垂白练明如雪，独下闲阶转凄切。",
            "只知抱杵捣秋砧，不觉高楼已无月。时闻寒雁声相唤，",
            "纱窗只有灯相伴。几展齐纨又懒裁，离肠恐逐金刀断。",
            "细想仪形执牙尺，回刀剪破澄江色。愁捻银针信手缝，",
            "惆怅无人试宽窄。时时举袖匀红泪，红笺谩有千行字。",
            "书中不尽心中事，一片殷勤寄边使。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春早寄华下同人 ----------
    {
        "id": "pei-shuo-4",
        "title": "春早寄华下同人",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "正是花时节，思君寝复兴。市沽终不醉，春梦亦无凭。",
            "岳面悬青雨，河心走浊冰。东门一条路，离恨镇相仍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 赠衡山令 ----------
    {
        "id": "pei-shuo-5",
        "title": "赠衡山令",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "君吟十二载，辛苦必能官。造化犹难隐，生灵岂易谩。",
            "猿跳高岳静，鱼摆大江宽。与我为同道，相留夜话阑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 南中县令 ----------
    {
        "id": "pei-shuo-6",
        "title": "南中县令",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "寂寥虽下邑，良宰有清威。苦节长如病，为官岂肯肥。",
            "山多村地狭，水浅客舟稀。上国搜贤急，陶公早晚归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 寄曹松（一作洛中作） ----------
    {
        "id": "pei-shuo-7",
        "title": "寄曹松（一作洛中作）",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "莫怪苦吟迟，诗成鬓亦丝。鬓丝犹可染，诗病却难医。",
            "山暝云横处，星沈月侧时。冥搜不可得，一句至公知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 赠宾贡 ----------
    {
        "id": "pei-shuo-8",
        "title": "赠宾贡",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "惟君怀至业，万里信悠悠。路向东溟出，枝来北阙求。",
            "家无一夜梦，帆挂隔年秋。鬓发争禁得，孤舟往复愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 汉南邮亭 ----------
    {
        "id": "pei-shuo-9",
        "title": "汉南邮亭",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "高阁水风清，开门日送迎。帆张独鸟起，乐奏大鱼惊。",
            "骤雨拖山过，微风拂面生。闲吟虽得句，留此谢多情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 棋 ----------
    {
        "id": "pei-shuo-10",
        "title": "棋",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "十九条平路，言平又嶮巇。人心无算处，国手有输时。",
            "势迥流星远，声干下雹迟。临轩才一局，寒日又西垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 夏日即事 ----------
    {
        "id": "pei-shuo-11",
        "title": "夏日即事",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "僻居门巷静，竟日坐阶墀。鹊喜虽传信，蛩吟不见诗。",
            "笋抽通旧竹，梅落立闲枝。此际无尘挠，僧来称所宜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送人宰邑 ----------
    {
        "id": "pei-shuo-12",
        "title": "送人宰邑",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "官小任还重，命官难偶然。皇恩轻一邑，赤子病三年。",
            "瘦马稀餐粟，羸童不识钱。如君清苦节，到处有人传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 春暖送人下第 ----------
    {
        "id": "pei-shuo-13",
        "title": "春暖送人下第",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "相送短亭前，知君愚复贤。事多凭夜梦，老为待明年。",
            "春树添山脊，晴云学晓烟。雄文有公道，此别莫潸然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 湖外送何崇入阁 ----------
    {
        "id": "pei-shuo-14",
        "title": "湖外送何崇入阁",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "因诗相识久，忽此告临途。便是有船发，也须容市沽。",
            "精吟五个字，稳泛两重湖。长短逢公道，清名振帝都。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 送进士苏瞻乱后出家 ----------
    {
        "id": "pei-shuo-15",
        "title": "送进士苏瞻乱后出家",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "因乱事空王，孤心亦不伤。梵僧为骨肉，柏寺作家乡。",
            "眼闭千行泪，头梳一把霜。诗书不得力，谁与问苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 秋日送河北从事 ----------
    {
        "id": "pei-shuo-16",
        "title": "秋日送河北从事",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "北风沙漠地，吾子远从军。官路虽非远，诗名要且闻。",
            "蝉悲欲落日，雕下拟阴云。此去难相恋，前山掺袂分。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 喜友人再面 ----------
    {
        "id": "pei-shuo-17",
        "title": "喜友人再面",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "一别几寒暄，迢迢隔塞垣。相思长有事，及见却无言。",
            "静坐将茶试，闲书把叶翻。依依又留宿，圆月上东轩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 对雪 ----------
    {
        "id": "pei-shuo-18",
        "title": "对雪",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "大片向空舞，出门肌骨寒。路岐平即易，沟壑满应难。",
            "兔穴归时失，禽枝宿处干。豪家宁肯厌，五月画图看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 冬日后作 ----------
    {
        "id": "pei-shuo-19",
        "title": "冬日后作",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "寂寞掩荆扉，昏昏坐欲痴。事无前定处，愁有并来时。",
            "日影才添线，鬓根已半丝。明庭正公道，应许苦心诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 冬日作 ----------
    {
        "id": "pei-shuo-20",
        "title": "冬日作",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "粝食拥败絮，苦吟吟过冬。稍寒人却健，太饱事多慵。",
            "树老生烟薄，墙阴贮雪重。安能只如此，公道会相容。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 中秋月 ----------
    {
        "id": "pei-shuo-21",
        "title": "中秋月",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "一岁几盈亏，当轩重此期。幸无偏照处，刚有不明时。",
            "色静云归早，光寒鹤睡迟。相看吟未足，皎皎下疏篱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 塞上曲 ----------
    {
        "id": "pei-shuo-22",
        "title": "塞上曲",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "极目望空阔，马羸程又赊。月生方见树，风定始无沙。",
            "楚水辞鱼窟，燕山到雁家。如斯名利役，争不老天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 终南山 ----------
    {
        "id": "pei-shuo-23",
        "title": "终南山",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "九衢南面色，苍翠绝纤尘。寸步有闲处，百年无到人。",
            "禁林寒对望，太华净相邻。谁与群峰并，祥云瑞露频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 访道士 ----------
    {
        "id": "pei-shuo-24",
        "title": "访道士",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "高冈微雨后，木脱草堂新。惟有疏慵者，来看淡薄人。",
            "竹牙生碍路，松子落敲巾。粗得玄中趣，当期宿话频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 道林寺 ----------
    {
        "id": "pei-shuo-25",
        "title": "道林寺",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "独立凭危阑，高低落照间。寺分一派水，僧锁半房山。",
            "对面浮世隔，垂帘到老闲。烟云与尘土，寸步不相关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 般若寺 ----------
    {
        "id": "pei-shuo-26",
        "title": "般若寺",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "南岳古般若，自来天下知。翠笼无价寺，光射有名诗。",
            "一水涌兽迹，五峰排凤仪。高僧引闲步，昼出夕阳归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 兜率寺 ----------
    {
        "id": "pei-shuo-27",
        "title": "兜率寺",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "一片无尘地，高连梦泽南。僧居跨鸟道，佛影照鱼潭。",
            "朽枿云斜映，平芜日半涵。行行不得住，回首望烟岚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 鹿门寺 ----------
    {
        "id": "pei-shuo-28",
        "title": "鹿门寺",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "鹿门山上寺，突兀尽无尘。到此修行者，应非取次人。",
            "鸟过惊石磬，日出碍金身。何计生烦恼，虚空是四邻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 题岳州僧舍 ----------
    {
        "id": "pei-shuo-29",
        "title": "题岳州僧舍",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "喜到重湖北，孤州横晚烟。鹭衔鱼入寺，鸦接饭随船。",
            "松桧君山迥，菰蒲梦泽连。与师吟论处，秋水浸遥天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 过洞庭湖 ----------
    {
        "id": "pei-shuo-30",
        "title": "过洞庭湖",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "浪高风力大，挂席亦言迟。及到堪忧处，争如未济时。",
            "鱼龙侵莫测，雷雨动须疑。此际情无赖，何门寄所思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 旅行闻寇 ----------
    {
        "id": "pei-shuo-31",
        "title": "旅行闻寇",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "动步忧多事，将行问四邻。深山不畏虎，当路却防人。",
            "豪富田园废，疲羸屋舍新。自惭为旅客，无计避烟尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 旅中作 ----------
    {
        "id": "pei-shuo-32",
        "title": "旅中作",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "妄动远抛山，其如馁与寒。投人言去易，开口说贫难。",
            "泽国云千片，湘江竹一竿。时明未忍别，犹待计穷看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 旅次衡阳 ----------
    {
        "id": "pei-shuo-33",
        "title": "旅次衡阳",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "欲往几经年，今来意豁然。江风长借客，岳雨不因天。",
            "戏鹭飞轻雪，惊鸿叫乱烟。晚秋红藕里，十宿寄渔船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 不出院僧 ----------
    {
        "id": "pei-shuo-34",
        "title": "不出院僧",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "四远参寻遍，修行却不行。耳边无俗语，门外是前生。",
            "塔见移来影，钟闻过去声。一斋唯默坐，应笑我营营。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 湖外寄处宾上人 ----------
    {
        "id": "pei-shuo-35",
        "title": "湖外寄处宾上人",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "怪得意相亲，高携一轴新。能搜大雅句，不似小乘人。",
            "岳麓擎枯桧，潇湘吐白蘋。他年遇同道，为我话风尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 寄贯休 ----------
    {
        "id": "pei-shuo-36",
        "title": "寄贯休",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "忆昔与吾师，山中静论时。总无方是法，难得始为诗。",
            "冻犬眠干叶，饥禽啄病梨。他年白莲社，犹许重相期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 寄僧尚颜 ----------
    {
        "id": "pei-shuo-37",
        "title": "寄僧尚颜",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "曾居五老峰，所得共谁同。才大天全与，吟精楚欲空。",
            "客来庭减日，鸟过竹生风。早晚摇轻拂，重归瀑布中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 哭处默上人 ----------
    {
        "id": "pei-shuo-38",
        "title": "哭处默上人",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "凄凉繐幕下，香吐一灯分。斗老输寒桧，留闲与白云。",
            "挈盂曾几度，传衲不教焚。泣罢重回首，暮山钟半闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 庐山瀑布 ----------
    {
        "id": "pei-shuo-39",
        "title": "庐山瀑布",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "静景凭高望，光分翠嶂开。嶮飞千尺雪，寒扑一声雷。",
            "过去云冲断，旁来烧隔回。何当住峰下，终岁绝尘埃。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 华山上方 ----------
    {
        "id": "pei-shuo-40",
        "title": "华山上方",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "独上上方上，立高聊称心。气冲云易黑，影落县多阴。",
            "有云草不死，无风松自吟。会当求大药，他日复追寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 咏鹦鹉 ----------
    {
        "id": "pei-shuo-41",
        "title": "咏鹦鹉",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "常贵西山鸟，衔恩在玉堂。语传明主意，衣拂美人香。",
            "缓步寻珠网，高飞上画梁。长安频道乐，何日从君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 鹭鸶 ----------
    {
        "id": "pei-shuo-42",
        "title": "鹭鸶",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "秋江清浅时，鱼过亦频窥。却为分明极，翻成所得迟。",
            "浴偎红日色，栖压碧芦枝。会共鹓同侣，翱翔应可期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 牡丹 ----------
    {
        "id": "pei-shuo-43",
        "title": "牡丹",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "数朵欲倾城，安同桃李荣。未尝贫处见，不似地中生。",
            "此物疑无价，当春独有名。游蜂与蝴蝶，来往自多情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 见王贞白 ----------
    {
        "id": "pei-shuo-44",
        "title": "见王贞白",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "共贺登科后，明宣入紫宸。又看重试榜，还见苦吟人。",
            "此得名浑别，归来话亦新。分明一枝桂，堪动楚江滨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 经杜工部坟 ----------
    {
        "id": "pei-shuo-45",
        "title": "经杜工部坟",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "骚人久不出，安得国风清。拟掘孤坟破，重教大雅生。",
            "皇天高莫问，白酒恨难平。悒怏寒江上，谁人知此情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 寄僧知乾 ----------
    {
        "id": "pei-shuo-46",
        "title": "寄僧知乾",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "貌高清入骨，帝里旧临坛。出语经相似，行心佛证安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 乱中偷路入故乡 ----------
    {
        "id": "pei-shuo-47",
        "title": "乱中偷路入故乡",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "愁看贼火起诸烽，偷得馀程怅望中。",
            "一国半为亡国烬，数城俱作古城空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 蔷薇 ----------
    {
        "id": "pei-shuo-48",
        "title": "蔷薇",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "一架长条万朵春，嫩红深绿小窠匀。",
            "只应根下千年土，曾葬西川织锦人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 春日山中竹 ----------
    {
        "id": "pei-shuo-49",
        "title": "春日山中竹",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "数竿苍翠拟龙形，峭拔须教此地生。",
            "无限野花开不得，半山寒色与春争。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 柳 ----------
    {
        "id": "pei-shuo-50",
        "title": "柳",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "高拂危楼低拂尘，灞桥攀折一何频。",
            "思量却是无情树，不解迎人只送人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 岳阳兵火后题僧舍 ----------
    {
        "id": "pei-shuo-51",
        "title": "岳阳兵火后题僧舍",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "十年兵火真多事，再到禅扉却破颜。",
            "唯有两般烧不得，洞庭湖水老僧闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 句 ----------
    {
        "id": "pei-shuo-52",
        "title": "句",
        "author": "裴说",
        "poet_id": "pei-shuo",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "读书贫里乐，搜句静中忙。（《苕溪渔隐》）",
            "苦吟僧入定，得句将成功。（以下《诗话》）",
            "是事精皆易，唯诗会却难。（《赠贯休》）",
            "因携一家住，赢得半年吟。（《石首县》）",
            "吟馀潮入浦，坐久烧移山。（《湘江》）",
            "三年清似水，六月冷如冰。（《赠县令》）",
            "一通红锦重，三事紫罗轻。（以下《绣石书堂》）",
            "瘦肌寒带粟，病眼馁生花。",
            "避乱一生多。",
            "雪留寒竹寺舍冷，风撼早梅城郭香。（《锦绣万花谷》）",
            "画球轻蹴壶中地，彩索高飞掌上身。（清明，事文类聚）",
            "第七百二十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]