# -*- coding: utf-8 -*-
"""
陈子良卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 13 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 上之回 ----------
    {
        "id": "chen-zi-liang-1",
        "title": "上之回",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "承平重游乐，诏跸上之回。属车响流水，清笳转落梅。",
            "岭云盖道转，岩花映绶开。下辇便高宴，何如在瑶台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 新成安乐宫（一作新宫词） ----------
    {
        "id": "chen-zi-liang-2",
        "title": "新成安乐宫（一作新宫词）",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "春色照兰宫，秦女坐窗中。柳叶来眉上，桃花落脸红。",
            "拂尘开扇匣，卷帐却薰笼。衫薄偏憎日，裙轻更畏风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 夏晚寻于政世置酒赋韵 ----------
    {
        "id": "chen-zi-liang-3",
        "title": "夏晚寻于政世置酒赋韵",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "聊从嘉遁所，酌醴共抽簪。以兹山水地，留连风月心。",
            "长榆落照尽，高柳暮蝉吟。一返桃源路，别后难追寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 入蜀秋夜宿江渚 ----------
    {
        "id": "chen-zi-liang-4",
        "title": "入蜀秋夜宿江渚",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "我行逢日暮，弭棹独维舟。水雾一边起，风林两岸秋。",
            "山阴黑断碛，月影素寒流。故乡千里外，何以慰羁愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 赋得妓 ----------
    {
        "id": "chen-zi-liang-5",
        "title": "赋得妓",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "金谷多欢宴，佳丽正芳菲。流霞席上满，回雪掌中飞。",
            "明月临歌扇，行云接舞衣。何必桃将李，别有待春晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 酬萧侍中春园听妓（一作李元操诗） ----------
    {
        "id": "chen-zi-liang-6",
        "title": "酬萧侍中春园听妓（一作李元操诗）",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "微雨散芳菲，中园照落晖。红树摇歌扇，绿珠飘舞衣。",
            "繁弦调对酒，杂引动思归。愁人当此夕，羞见落花飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 游侠篇（一作侠客行） ----------
    {
        "id": "chen-zi-liang-7",
        "title": "游侠篇（一作侠客行）",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "洛阳丽春色，游侠骋轻肥。水逐车轮转，尘随马足飞。",
            "云影遥临盖，花气近薰衣。东郊斗鸡罢，南皮射雉归。",
            "日暮河桥上，扬鞭惜晚晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 春晚看群公朝还人为八韵 ----------
    {
        "id": "chen-zi-liang-8",
        "title": "春晚看群公朝还人为八韵",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "游子惜春暮，策杖出蒿莱。正直康庄晚，群公谒帝回。",
            "履度南宫至，车从北阙来。珂影傍明月，笳声动落梅。",
            "迎风采旄转，照日绶花开。红尘掩鹤盖，翠柳拂龙媒。",
            "绮云临舞阁，丹霞薄吹台。轻肥宁所羡，未若反山隈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 赞德上越国公杨素 ----------
    {
        "id": "chen-zi-liang-9",
        "title": "赞德上越国公杨素",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "君侯称上宰，命世挺才英。本超骐骥足，复蕴风云情。",
            "摅藻掞锦绮，育德润瑶琼。已踵四知举，非无三杰名。",
            "济世同舟楫，匡政本阿衡。雍容入青琐，肃穆侍丹楹。",
            "桂宫擅鸣珮，槐路独飞缨。高门罗虎戟，绮阁丽雕甍。",
            "金樽酌湛湛，歌扇掩盈盈。匈奴轶燕蓟，烽火照幽并。",
            "天子命薄伐，受脤事专征。七德播雄略，十万骋行兵。",
            "雁行蔽虏甸，鱼贯出长城。交河方饮马，瀚海盛扬旌。",
            "拔剑倚天外，蒙犀辉日精。弯弧穿伏石，挥戈斩大鲸。",
            "鼓鼙朝作气，刁斗夜偏鸣。六郡多壮士，三边岂足平。",
            "岭云朝合阵，山月夜临营。胡尘暗马色，芳树动笳声。",
            "关云未尽散，塞雾常自生。川长蔓草绿，峰迥杂花明。",
            "小人愧王氏，雕文惭马卿。滥此叨书记，何以谢过荣。",
            "高山徒仰止，终是恨才轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 于塞北春日思归 ----------
    {
        "id": "chen-zi-liang-10",
        "title": "于塞北春日思归",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "我家吴会青山远，他乡关塞白云深。为许羁愁长下泪，",
            "那堪春色更伤心。惊鸟屡飞恒失侣，落花一去不归林。",
            "如何此日嗟迟暮，悲来还作白头吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送别 ----------
    {
        "id": "chen-zi-liang-11",
        "title": "送别",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "落叶聚还散，征禽去不归。以我穷途泣，沾君出塞衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 七夕看新妇隔巷停车（一作陈伯材诗） ----------
    {
        "id": "chen-zi-liang-12",
        "title": "七夕看新妇隔巷停车（一作陈伯材诗）",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "隔巷遥停幰，非复为来迟。只言更尚浅，未是渡河时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 咏春雪（一作陈伯材诗） ----------
    {
        "id": "chen-zi-liang-13",
        "title": "咏春雪（一作陈伯材诗）",
        "author": "陈子良",
        "poet_id": "chen-zi-liang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "光映妆楼月，花承歌扇风。欲妒梅将柳，故落早春中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]