# -*- coding: utf-8 -*-
"""
可止卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 10 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 山居 ----------
    {
        "id": "ke-zhi-1",
        "title": "山居",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "雪消春力展，花漫洞门垂。果长纤枝曲，岩崩直道移。",
            "重猿围浅井，斗鼠下疏篱。寒食微灯在，高风势彻陂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠樊川长老（一作清尚诗） ----------
    {
        "id": "ke-zhi-2",
        "title": "赠樊川长老（一作清尚诗）",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "瘦颜颧骨见，满面雪毫垂。坐石鸟疑死，出门人谓痴。",
            "照身潭入楚，浸影桧生隋。太白曾经夏，清风凉四肢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寄积麦山会如长老 ----------
    {
        "id": "ke-zhi-3",
        "title": "寄积麦山会如长老",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "默然如大道，尘世不相关。青桧行时静，白云禅处闲。",
            "贫高一生行，病长十年颜。夏满期游寺，寻山又下山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送僧 ----------
    {
        "id": "ke-zhi-4",
        "title": "送僧",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "四海无拘系，行心兴自浓。百年三事衲，万里一枝筇。",
            "夜减当晴影，春消过雪踪。白云深处去，知宿在何峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 哭贾岛 ----------
    {
        "id": "ke-zhi-5",
        "title": "哭贾岛",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "燕生松雪地，蜀死葬山根。诗僻降今古，官卑误子孙。",
            "冢栏寒月色，人哭苦吟魂。墓雨滴碑字，年年添藓痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 雪十二韵 ----------
    {
        "id": "ke-zhi-6",
        "title": "雪十二韵",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "落处咸过尺，翛然物象凄。瑞凝金殿上，寒甚玉关西。",
            "润比江河普，明将日月齐。凌云花顶腻，锁径竹梢低。",
            "出谷樵童怯，归林野鸟迷。煮茶融破练，磨墨染成黳。",
            "陷兔埋平泽，和鱼冻合溪。入楼消酒力，当槛写诗题。",
            "道路依凭马，朝昏委托鸡。洞深猿作族，松亚鹤移栖。",
            "及夏清岩穴，经春溜石梯。丰年兼泰国，天道育黔黎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 精舍遇雨 ----------
    {
        "id": "ke-zhi-7",
        "title": "精舍遇雨",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "空门寂寂淡吾身，溪雨微微洗客尘。",
            "卧向白云情未尽，任他黄鸟醉芳春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 小雪 ----------
    {
        "id": "ke-zhi-8",
        "title": "小雪",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "落雪临风不厌看，更多还恐蔽林峦。",
            "愁人正在书窗下，一片飞来一片寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送婆罗门僧 ----------
    {
        "id": "ke-zhi-9",
        "title": "送婆罗门僧",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "雪岭金河独向东，吴山楚泽意无穷。",
            "如今白首乡心尽，万里归程在梦中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 句 ----------
    {
        "id": "ke-zhi-10",
        "title": "句",
        "author": "可止",
        "poet_id": "ke-zhi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "不知谁会喃喃语，必向王前报太平。（中山节度王处直座",
            "咏白鹊，时诸侯兼并，王欲继好息民，故云。《高僧传》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]