# -*- coding: utf-8 -*-
"""
汪遵卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 60 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 彭泽 ----------
    {
        "id": "wang-zun-1",
        "title": "彭泽",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "鹤爱孤松云爱山，宦情微禄免相关。",
            "栽成五柳吟归去，漉酒巾边伴菊闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 杜邮馆 ----------
    {
        "id": "wang-zun-2",
        "title": "杜邮馆",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "杀尽降兵热血流，一心犹自逞戈矛。",
            "功成若解求身退，岂得将军死杜邮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 细腰宫 ----------
    {
        "id": "wang-zun-3",
        "title": "细腰宫",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "鼓声连日烛连宵，贪向春风舞细腰。",
            "争奈君王正沈醉，秦兵江上促征桡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 瑶台 ----------
    {
        "id": "wang-zun-4",
        "title": "瑶台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "仙梦香魂不久留，满川云雨满宫愁。",
            "直须待得荆王死，始向瑶台一处游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 吴坂 ----------
    {
        "id": "wang-zun-5",
        "title": "吴坂",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "踡跼盐车万里蹄，忽逢良鉴始能嘶。",
            "不缘伯乐称奇骨，几与驽骀价一齐。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 箕山 ----------
    {
        "id": "wang-zun-6",
        "title": "箕山",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "薄世临流洗耳尘，便归云洞任天真。",
            "一瓢风入犹嫌闹，何况人间万种人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 息国 ----------
    {
        "id": "wang-zun-7",
        "title": "息国",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "家国兴亡身独存，玉容还受楚王恩。",
            "衔冤只合甘先死，何待花间不肯言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 梁寺 ----------
    {
        "id": "wang-zun-8",
        "title": "梁寺",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "立国从来为战功，一朝何事却谈空。",
            "台城兵匝无人敌，闲卧高僧满梵宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 南阳 ----------
    {
        "id": "wang-zun-9",
        "title": "南阳",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "陆困泥蟠未适从，岂妨耕稼隐高踪。",
            "若非先主垂三顾，谁识茅庐一卧龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 杞梁墓 ----------
    {
        "id": "wang-zun-10",
        "title": "杞梁墓",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "一叫长城万仞摧，杞梁遗骨逐妻回。",
            "南邻北里皆孀妇，谁解坚心继此来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 夷门 ----------
    {
        "id": "wang-zun-11",
        "title": "夷门",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "晋鄙兵回为重难，秦师收旆亦西还。",
            "今来不是无朱亥，谁降轩车问抱关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 汴河 ----------
    {
        "id": "wang-zun-12",
        "title": "汴河",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "隋皇意欲泛龙舟，千里昆仑水别流。",
            "还待春风锦帆暖，柳阴相送到迷楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 燕台 ----------
    {
        "id": "wang-zun-13",
        "title": "燕台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "礼士招贤万古名，高台依旧对燕城。",
            "如今寂寞无人上，春去秋来草自生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 聊城 ----------
    {
        "id": "wang-zun-14",
        "title": "聊城",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "刃血攻聊已越年，竟凭儒术罢戈鋋。",
            "田单漫逞烧牛计，一箭终输鲁仲连。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 西河 ----------
    {
        "id": "wang-zun-15",
        "title": "西河",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "花貌年年溺水滨，俗传河伯娶生人。",
            "自从明宰投巫后，直至如今鬼不神。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 密县 ----------
    {
        "id": "wang-zun-16",
        "title": "密县",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "百里能将济猛宽，飞蝗不到邑人安。",
            "至今闾里逢灾沴，犹祝当时卓长官。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 升仙桥 ----------
    {
        "id": "wang-zun-17",
        "title": "升仙桥",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "题桥贵欲露先诚，此日人皆笑率情。",
            "应讶临邛沽酒客，逢时还作汉公卿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 破陈 ----------
    {
        "id": "wang-zun-18",
        "title": "破陈",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "猎猎朱旗映彩霞，纷纷白刃入陈家。",
            "看看打破东平苑，犹舞庭前玉树花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 白头吟 ----------
    {
        "id": "wang-zun-19",
        "title": "白头吟",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "失却青丝素发生，合欢罗带意全轻。",
            "古今人事皆如此，不独文君与马卿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 短歌吟 ----------
    {
        "id": "wang-zun-20",
        "title": "短歌吟",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "箭飞乌兔竞东西，贵贱贤愚不梦齐。",
            "匣里有琴樽有酒，人间便是武陵溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 晋河 ----------
    {
        "id": "wang-zun-21",
        "title": "晋河",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "风引征帆管吹高，晋君张宴俟雄豪。",
            "舟人笑指千馀客，谁是烟霄六翮毛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 干将墓 ----------
    {
        "id": "wang-zun-22",
        "title": "干将墓",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "橐籥冰霜万古闻，拍灰松地见馀坟。",
            "应缘神剑飞扬久，水水山山尽是云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 金谷 ----------
    {
        "id": "wang-zun-23",
        "title": "金谷",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "晋臣荣盛更谁过，常向阶前舞翠娥。",
            "香散艳消如一梦，但留风月伴烟萝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 三闾庙 ----------
    {
        "id": "wang-zun-24",
        "title": "三闾庙",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "为嫌朝野尽陶陶，不觉官高怨亦高。",
            "憔悴莫酬渔父笑，浪交千载咏离骚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 易水 ----------
    {
        "id": "wang-zun-25",
        "title": "易水",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "匕首空磨事不成，误留龙袂待琴声。",
            "斯须却作秦中鬼，青史徒标烈士名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 严陵台 ----------
    {
        "id": "wang-zun-26",
        "title": "严陵台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "一钓凄凉在杳冥，故人飞诏入山扃。",
            "终将宠辱轻轩冕，高卧五云为客星。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 淮阴 ----------
    {
        "id": "wang-zun-27",
        "title": "淮阴",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "秦季贤愚混不分，只应漂母识王孙。",
            "归荣便累千金赠，为报当时一饭恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 鸡鸣曲 ----------
    {
        "id": "wang-zun-28",
        "title": "鸡鸣曲",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "金距花冠傍舍栖，清晨相叫一声齐。",
            "开关自有冯生计，不必天明待汝啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 采桑妇 ----------
    {
        "id": "wang-zun-29",
        "title": "采桑妇",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "为报踌躇陌上郎，蚕饥日晚妾心忙。",
            "本来若爱黄金好，不肯携笼更采桑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 渔父 ----------
    {
        "id": "wang-zun-30",
        "title": "渔父",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "棹月眠流处处通，绿蓑苇带混元风。",
            "灵均说尽孤高事，全与逍遥意不同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 越女 ----------
    {
        "id": "wang-zun-31",
        "title": "越女",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "玉貌何曾为浣沙，只图勾践献夫差。",
            "苏台日夜唯歌舞，不觉干戈犯翠华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 望思台 ----------
    {
        "id": "wang-zun-32",
        "title": "望思台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "不忧家国任奸臣，骨肉翻为蓦路人。",
            "巫蛊事行冤莫雪，九层徒筑见无因。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 比干墓 ----------
    {
        "id": "wang-zun-33",
        "title": "比干墓",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "国乱时危道不行，忠贤谏死胜谋生。",
            "一沉冤骨千年后，垄水虽平恨未平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 郢中 ----------
    {
        "id": "wang-zun-34",
        "title": "郢中",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "莫言白雪少人听，高调都难称俗情。",
            "不是楚词询宋玉，巴歌犹掩绕梁声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 北海 ----------
    {
        "id": "wang-zun-35",
        "title": "北海",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "汉臣曾此作缧囚，茹血衣毛十九秋。",
            "鹤发半垂龙节在，不闻青史说封侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 招屈亭 ----------
    {
        "id": "wang-zun-36",
        "title": "招屈亭",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "三闾溺处杀怀王，感得荆人尽缟裳。",
            "招屈亭边两重恨，远天秋色暮苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 屈祠 ----------
    {
        "id": "wang-zun-37",
        "title": "屈祠",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "不肯迂回入醉乡，乍吞忠梗没沧浪。",
            "至今祠畔猿啼月，了了犹疑恨楚王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 铜雀台 ----------
    {
        "id": "wang-zun-38",
        "title": "铜雀台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "铜雀台成玉座空，短歌长袖尽悲风。",
            "不知仙驾归何处，徒遣颦眉望汉宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 斑竹祠 ----------
    {
        "id": "wang-zun-39",
        "title": "斑竹祠",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "九处烟霞九处昏，一回延首一销魂。",
            "因凭直节流红泪，图得千秋见血痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 题李太尉平泉庄 ----------
    {
        "id": "wang-zun-40",
        "title": "题李太尉平泉庄",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "水泉花木好高眠，嵩少纵横满目前。",
            "惆怅人间不平事，今朝身在海南边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 战城南 ----------
    {
        "id": "wang-zun-41",
        "title": "战城南",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "风沙刮地塞云愁，平旦交锋晚未休。",
            "白骨又沾新战血，青天犹列旧旄头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 延平津 ----------
    {
        "id": "wang-zun-42",
        "title": "延平津",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "三尺晶荧射斗牛，岂随凡手报冤雠。",
            "延平一旦为龙处，看取风云布九州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 项亭 ----------
    {
        "id": "wang-zun-43",
        "title": "项亭",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "不修仁德合文明，天道如何拟力争。",
            "隔岸故乡归不得，十年空负拔山名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 乌江 ----------
    {
        "id": "wang-zun-44",
        "title": "乌江",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "兵散弓残挫虎威，单枪匹马突重围。",
            "英雄去尽羞容在，看却江东不得归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 绿珠 ----------
    {
        "id": "wang-zun-45",
        "title": "绿珠",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "大抵花颜最怕秋，南家歌歇北家愁。",
            "从来几许如君貌，不肯如君坠玉楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 升仙桥 ----------
    {
        "id": "wang-zun-46",
        "title": "升仙桥",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "汉朝卿相尽风云，司马题桥众又闻。",
            "何事不如杨得意，解搜贤哲荐明君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 隋柳 ----------
    {
        "id": "wang-zun-47",
        "title": "隋柳",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "夹浪分堤万树馀，为迎龙舸到江都。",
            "君看靖节高眠处，只向衡门种五株。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 杨柳 ----------
    {
        "id": "wang-zun-48",
        "title": "杨柳",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "亚夫营畔柳濛濛，隋主堤边四路通。",
            "攀折赠君还有意，翠眉轻嫩怕春风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 桐江 ----------
    {
        "id": "wang-zun-49",
        "title": "桐江",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "光武重兴四海宁，汉臣无不受浮荣。",
            "严陵何事轻轩冕，独向桐江钓月明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 招隐 ----------
    {
        "id": "wang-zun-50",
        "title": "招隐",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "罢听泉声看鹿群，丈夫才策合匡君。",
            "早携书剑离岩谷，莫待蒲轮辗白云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 陈宫 ----------
    {
        "id": "wang-zun-51",
        "title": "陈宫",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "椒宫荒宴竟无疑，倏忽山河尽入隋。",
            "留得后庭亡国曲，至今犹与酒家吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 樊将军庙 ----------
    {
        "id": "wang-zun-52",
        "title": "樊将军庙",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "玉辇曾经陷楚营，汉皇心怯拟休兵。",
            "当时不得将军力，日月须分一半明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 东海 ----------
    {
        "id": "wang-zun-53",
        "title": "东海",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "漾舟雪浪映花颜，徐福携将竟不还。",
            "同作危时避秦客，此行何似武陵滩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 昭君 ----------
    {
        "id": "wang-zun-54",
        "title": "昭君",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "汉家天子镇寰瀛，塞北羌胡未罢兵。",
            "猛将谋臣徒自贵，蛾眉一笑塞尘清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 五湖 ----------
    {
        "id": "wang-zun-55",
        "title": "五湖",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "已立平吴霸越功，片帆高扬五湖风。",
            "不知战国官荣者，谁似陶朱得始终。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 渑池 ----------
    {
        "id": "wang-zun-56",
        "title": "渑池",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "西秦北赵各称高，池上张筵列我曹。",
            "何事君王亲击缶，相如有剑可吹毛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 函谷关 ----------
    {
        "id": "wang-zun-57",
        "title": "函谷关",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "脱祸东奔壮气摧，马如飞电毂如雷。",
            "当时若不听弹铗，那得关门半夜开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 咏酒二首 ----------
    {
        "id": "wang-zun-58",
        "title": "咏酒二首",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "九酝松醪一曲歌，本图闲放养天和。",
            "后人不识前贤意，破国亡家事甚多。",
            "万事销沈向一杯，竹门哑轧为风开。",
            "秋宵睡足芭蕉雨，又是江湖入梦来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 苍颉台 ----------
    {
        "id": "wang-zun-59",
        "title": "苍颉台",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "观迹成文代结绳，皇风儒教浩然兴。",
            "几人从此休耕钓，吟对长安雪夜灯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 长城 ----------
    {
        "id": "wang-zun-60",
        "title": "长城",
        "author": "汪遵",
        "poet_id": "wang-zun",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "秦筑长城比铁牢，蕃戎不敢过临洮。",
            "虽然万里连云际，争及尧阶三尺高。",
            "第六百零三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]