# -*- coding: utf-8 -*-
"""
孙元晏卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 75 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 吴·黄金车 ----------
    {
        "id": "sun-yuan-yan-1",
        "title": "吴·黄金车",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "分擘山河即渐开，许昌基业已倾颓。",
            "黄金车与斑斓耳，早个须知入谶来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 吴·赤壁 ----------
    {
        "id": "sun-yuan-yan-2",
        "title": "吴·赤壁",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "会猎书来举国惊，只应周鲁不教迎。",
            "曹公一战奔波后，赤壁功传万古名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 吴·鲁肃指囷 ----------
    {
        "id": "sun-yuan-yan-3",
        "title": "吴·鲁肃指囷",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "破产移家事亦难，佐吴从此霸江山。",
            "争教不立功勋得，指出千囷如等闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 吴·甘宁斫营 ----------
    {
        "id": "sun-yuan-yan-4",
        "title": "吴·甘宁斫营",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "夜深偷入魏军营，满寨惊忙火似星。",
            "百口宝刀千匹绢，也应消得与甘宁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 吴·徐盛 ----------
    {
        "id": "sun-yuan-yan-5",
        "title": "吴·徐盛",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "欲把江山鼎足分，邢真衔册到江南。",
            "当时将相谁堪重，徐盛将军最不甘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 吴·鲁肃 ----------
    {
        "id": "sun-yuan-yan-6",
        "title": "吴·鲁肃",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "斫案兴言断众疑，鼎分从此定雄雌。",
            "若无子敬心相似，争得乌林破魏师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 吴·武昌 ----------
    {
        "id": "sun-yuan-yan-7",
        "title": "吴·武昌",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "西塞山高截九垓，谶谣终日自相催。",
            "武昌鱼美应难恋，历数须归建业来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 吴·顾雍 ----------
    {
        "id": "sun-yuan-yan-8",
        "title": "吴·顾雍",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "赞国经纶更有谁，蔡公相叹亦相师。",
            "贵为丞相封侯了，归后家人总不知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 吴·吕蒙 ----------
    {
        "id": "sun-yuan-yan-9",
        "title": "吴·吕蒙",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "幼小家贫实可哀，愿征行去志难回。",
            "不探虎穴求身达，争得人间富贵来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 吴·介象 ----------
    {
        "id": "sun-yuan-yan-10",
        "title": "吴·介象",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "好道君王遇亦难，变通灵异几多般。",
            "介先生有神仙术，钓得鲈鱼在玉盘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 吴·濡须坞 ----------
    {
        "id": "sun-yuan-yan-11",
        "title": "吴·濡须坞",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "风揭洪涛响若雷，枕波为垒险相隈。",
            "莫言有个濡须坞，几度曹公失志回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 吴·周泰 ----------
    {
        "id": "sun-yuan-yan-12",
        "title": "吴·周泰",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "名与诸公又不同，金疮痕在满身中。",
            "不将御盖宣恩泽，谁信将军别有功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 吴·张纮 ----------
    {
        "id": "sun-yuan-yan-13",
        "title": "吴·张纮",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "东部张公与众殊，共施经略赞全吴。",
            "陈琳漫自称雄伯，神气应须怯大巫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 吴·太史慈 ----------
    {
        "id": "sun-yuan-yan-14",
        "title": "吴·太史慈",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "圣德招贤远近知，曹公心计却成欺。",
            "陈韩昔日尝投楚，岂是当归召得伊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 吴·孙坚后 ----------
    {
        "id": "sun-yuan-yan-15",
        "title": "吴·孙坚后",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "委存张公翊圣材，几将贤德赞文台。",
            "争教不霸江山得，日月征曾入梦来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 吴·陆统 ----------
    {
        "id": "sun-yuan-yan-16",
        "title": "吴·陆统",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "将军身殁有儿孤，虎子为名教读书。",
            "更向宫中教骑马，感君恩重合何如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 吴·青盖 ----------
    {
        "id": "sun-yuan-yan-17",
        "title": "吴·青盖",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "历数将终势已摧，不修君德更堪哀。",
            "被他青盖言相误，元是须教入晋来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 晋·七宝鞭 ----------
    {
        "id": "sun-yuan-yan-18",
        "title": "晋·七宝鞭",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "天命须知岂偶然，乱臣徒欲用兵权。",
            "圣谟庙略还应别，浑不消他七宝鞭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 晋·庾悦鹅炙 ----------
    {
        "id": "sun-yuan-yan-19",
        "title": "晋·庾悦鹅炙",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "春暖江南景气新，子鹅炙美就中珍。",
            "庾家厨盛刘公困，浑弗相贻也恼人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 晋·谢玄 ----------
    {
        "id": "sun-yuan-yan-20",
        "title": "晋·谢玄",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "百万兵来逼合肥，谢玄为将统雄师。",
            "旌旗首尾千馀里，浑不消他一局棋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 晋·谢混 ----------
    {
        "id": "sun-yuan-yan-21",
        "title": "晋·谢混",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "尚主当初偶未成，此时谁合更关情。",
            "可怜谢混风华在，千古翻传禁脔名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 晋·陆玩 ----------
    {
        "id": "sun-yuan-yan-22",
        "title": "晋·陆玩",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "陆公高论亦由衷，谦让还惭未有功。",
            "天下忠良人欲尽，始应交我作三公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 晋·王坦之 ----------
    {
        "id": "sun-yuan-yan-23",
        "title": "晋·王坦之",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "晋祚安危只此行，坦之何必苦忧惊。",
            "谢公合定寰区在，争遣当时事得成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 晋·蒲葵扇 ----------
    {
        "id": "sun-yuan-yan-24",
        "title": "晋·蒲葵扇",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "抛舍东山岁月遥，几施经略挫雄豪。",
            "若非名德喧寰宇，争得蒲葵价数高。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 晋·王郎 ----------
    {
        "id": "sun-yuan-yan-25",
        "title": "晋·王郎",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "太尉门庭亦甚高，王郎名重礼相饶。",
            "自家妻父犹如此，谁更逢君得折腰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 晋·刘毅 ----------
    {
        "id": "sun-yuan-yan-26",
        "title": "晋·刘毅",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "绕床堪壮喝卢声，似铁容仪众尽惊。",
            "二十七人同举义，几人全得旧功名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 晋·王恭 ----------
    {
        "id": "sun-yuan-yan-27",
        "title": "晋·王恭",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "春风濯濯柳容仪，鹤氅神情举世推。",
            "可惜教君仗旄钺，枉将心地托牢之。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 晋·谢公赌墅 ----------
    {
        "id": "sun-yuan-yan-28",
        "title": "晋·谢公赌墅",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "发遣将军欲去时，略无情挠只贪棋。",
            "自从乞与羊昙后，赌墅功成更有谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 晋·苻坚投箠 ----------
    {
        "id": "sun-yuan-yan-29",
        "title": "晋·苻坚投箠",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "投箠填江语未终，谢安乘此立殊功。",
            "三台星烂乾坤在，且与张华死不同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 晋·卫玠 ----------
    {
        "id": "sun-yuan-yan-30",
        "title": "晋·卫玠",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "叔宝羊车海内稀，山家女婿好风姿。",
            "江东士女无端甚，看杀玉人浑不知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 晋·郭璞脱襦 ----------
    {
        "id": "sun-yuan-yan-31",
        "title": "晋·郭璞脱襦",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "吟坐因思郭景纯，每言穷达似通神。",
            "到头分命难移改，解脱青襦与别人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 晋·庾楼 ----------
    {
        "id": "sun-yuan-yan-32",
        "title": "晋·庾楼",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "江州楼上月明中，从事同登眺远空。",
            "玉树忽薶千载后，有谁重此继清风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 晋·新亭 ----------
    {
        "id": "sun-yuan-yan-33",
        "title": "晋·新亭",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "容易乘虚逼帝畿，满江艛橹与旌旗。",
            "卢循若解新亭上，胜负还应未可知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 宋·大岘 ----------
    {
        "id": "sun-yuan-yan-34",
        "title": "宋·大岘",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "大岘才过喜可知，指空言已副心期。",
            "公孙计策嗟无用，天与南朝作霸基。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 宋·放宫人 ----------
    {
        "id": "sun-yuan-yan-35",
        "title": "宋·放宫人",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "纳谏廷臣免犯颜，自然恩可霸江山。",
            "姚兴侍女方承宠，放出宫闱若等闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 宋·借南苑 ----------
    {
        "id": "sun-yuan-yan-36",
        "title": "宋·借南苑",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "人主词应不偶然，几人曾说笑掀天。",
            "不知南苑今何在，借与张公三百年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 宋·谢澹云霞友 ----------
    {
        "id": "sun-yuan-yan-37",
        "title": "宋·谢澹云霞友",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "仗气凌人岂可亲，只将范泰是知闻。",
            "缘何唤作云霞友，却恐云霞未似君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 宋·乌衣巷 ----------
    {
        "id": "sun-yuan-yan-38",
        "title": "宋·乌衣巷",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "古迹荒基好叹嗟，满川吟景只烟霞。",
            "乌衣巷在何人住，回首令人忆谢家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 宋·袁粲 ----------
    {
        "id": "sun-yuan-yan-39",
        "title": "宋·袁粲",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "负才尚气满朝知，高卧闲吟见客稀。",
            "独步何人识袁尹，白杨郊外醉方归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 宋·刘伯龙 ----------
    {
        "id": "sun-yuan-yan-40",
        "title": "宋·刘伯龙",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "位重何如不厌贫，伯龙孤子只修身。",
            "固知生计还须有，穷鬼临时也笑人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 宋·王方平 ----------
    {
        "id": "sun-yuan-yan-41",
        "title": "宋·王方平",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "拂衣耕钓已多时，江上山前乐可知。",
            "著却貂裘将采药，任他人唤作渔师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 宋·黄罗襦 ----------
    {
        "id": "sun-yuan-yan-42",
        "title": "宋·黄罗襦",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "戚属群臣尽见猜，预忧身后又堪哀。",
            "到头委付何曾是，虚把罗襦与彦回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 宋·谢朏 ----------
    {
        "id": "sun-yuan-yan-43",
        "title": "宋·谢朏",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "谢家诸子尽兰香，各震芳名满帝乡。",
            "惟有千金更堪重，只将高卧向齐王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 宋·羊玄保 ----------
    {
        "id": "sun-yuan-yan-44",
        "title": "宋·羊玄保",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "运命将来各有期，好官才阙即思之。",
            "就中堪爱羊玄保，偏受君王分外知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 齐·谢朏 ----------
    {
        "id": "sun-yuan-yan-45",
        "title": "齐·谢朏",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "解玺传呼诏侍中，却来高卧岂疏慵。",
            "此时忠节还希有，堪羡君王特地容。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 齐·小儿执烛 ----------
    {
        "id": "sun-yuan-yan-46",
        "title": "齐·小儿执烛",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "谢公情量已难量，忠宋心诚岂暂忘。",
            "执烛小儿浑放去，略无言语与君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 齐·王僧祐 ----------
    {
        "id": "sun-yuan-yan-47",
        "title": "齐·王僧祐",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "肯与公卿作等伦，澹然名德只推君。",
            "任他车骑来相访，箫鼓盈庭似不闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 齐·王僧虔 ----------
    {
        "id": "sun-yuan-yan-48",
        "title": "齐·王僧虔",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "位高名重不堪疑，恳让仪同帝亦知。",
            "不学常流争进取，却忧门有二台司。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 齐·明帝裹蒸 ----------
    {
        "id": "sun-yuan-yan-49",
        "title": "齐·明帝裹蒸",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "至尊尊贵异人间，御膳天厨岂等闲。",
            "惜得裹蒸无用处，不如安霸取江山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 齐·郁林王 ----------
    {
        "id": "sun-yuan-yan-50",
        "title": "齐·郁林王",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "强哀强惨亦从伊，归到私庭喜可知。",
            "喜字漫书三十六，到头能得几多时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 齐·何氏小山 ----------
    {
        "id": "sun-yuan-yan-51",
        "title": "齐·何氏小山",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "显达何曾肯系心，筑居郊外好园林。",
            "赚他谢朏出山去，赢得高名直至今。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 齐·王伦之 ----------
    {
        "id": "sun-yuan-yan-52",
        "title": "齐·王伦之",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "豫章太守重词林，图画陈蕃与华歆。",
            "更奠子将并孺子，为君千载作知音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 齐·潘妃 ----------
    {
        "id": "sun-yuan-yan-53",
        "title": "齐·潘妃",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "曾步金莲宠绝伦，岂甘今日委埃尘。",
            "玉儿还有怀恩处，不肯将身嫁小臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 齐·王亮 ----------
    {
        "id": "sun-yuan-yan-54",
        "title": "齐·王亮",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "后见梁王未免哀，奈何无计拯倾颓。",
            "若教彼相颠扶得，争遣明公到此来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 梁·分宫女 ----------
    {
        "id": "sun-yuan-yan-55",
        "title": "梁·分宫女",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "涤荡齐宫法令新，分张宫女二千人。",
            "可怜无限如花貌，重见世间桃李春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 梁·马仙埤 ----------
    {
        "id": "sun-yuan-yan-56",
        "title": "梁·马仙埤",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "齐朝太守不甘降，忠节当时动四方。",
            "义士要教天下见，且留君住待袁昂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 梁·勍敌 ----------
    {
        "id": "sun-yuan-yan-57",
        "title": "梁·勍敌",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "传闻天子重儒才，特为皇华绮宴开。",
            "今日方惊遇勍敌，此人元自北朝来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 梁·蔡撙 ----------
    {
        "id": "sun-yuan-yan-58",
        "title": "梁·蔡撙",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "紫茄白苋以为珍，守任清真转更贫。",
            "不饮吴兴郡中水，古今能有几多人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 梁·楚祠 ----------
    {
        "id": "sun-yuan-yan-59",
        "title": "梁·楚祠",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "曾与萧侯醉玉杯，此时神影尽倾颓。",
            "莫云千古无灵圣，也向西川助敌来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 梁·谢朏小舆 ----------
    {
        "id": "sun-yuan-yan-60",
        "title": "梁·谢朏小舆",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "小舆升殿掌钧台，不免无憀却忆回。",
            "应恨被他何胤误，悔先容易出山来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 梁·八关斋 ----------
    {
        "id": "sun-yuan-yan-61",
        "title": "梁·八关斋",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "依凭金地甚虔诚，忍溺空王为圣明。",
            "内殿设斋申祷祝，岂无功德及台城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 梁·庾信 ----------
    {
        "id": "sun-yuan-yan-62",
        "title": "梁·庾信",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "苦心词赋向谁谈，沦落周朝志岂甘。",
            "可惜多才庾开府，一生惆怅忆江南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 陈·王僧辨 ----------
    {
        "id": "sun-yuan-yan-63",
        "title": "陈·王僧辨",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "彼此英雄各有名，石头高卧拟争衡。",
            "当时堪笑王僧辨，待欲将心托圣明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 陈·武帝蚌盘 ----------
    {
        "id": "sun-yuan-yan-64",
        "title": "陈·武帝蚌盘",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "金翠丝黄略不舒，蚌盘清宴意何如。",
            "岂知三阁繁华日，解为君王妙破除。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 陈·虞居士 ----------
    {
        "id": "sun-yuan-yan-65",
        "title": "陈·虞居士",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "苦谏将军总不知，几随烟焰作尘飞。",
            "东山居士何人识，惟有君王却许归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 陈·姚察 ----------
    {
        "id": "sun-yuan-yan-66",
        "title": "陈·姚察",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "曾佐徐陵向北游，剖陈疑事动名流。",
            "却归掌选清何甚，一匹花綀不肯收。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 陈·宣帝伤将卒 ----------
    {
        "id": "sun-yuan-yan-67",
        "title": "陈·宣帝伤将卒",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "前后兵师战胜回，百馀城垒尽归来。",
            "当时将卒应知感，况得君王为举哀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 陈·临春阁 ----------
    {
        "id": "sun-yuan-yan-68",
        "title": "陈·临春阁",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "临春高阁上侵云，风起香飘数里闻。",
            "自是君王正沈醉，岂知消息报隋军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 陈·结绮阁 ----------
    {
        "id": "sun-yuan-yan-69",
        "title": "陈·结绮阁",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "结绮高宜眺海涯，上凌丹汉拂云霞。",
            "一千朱翠同居此，争奈恩多属丽华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 陈·望仙阁 ----------
    {
        "id": "sun-yuan-yan-70",
        "title": "陈·望仙阁",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "多少沈檀结筑成，望仙为号倚青冥。",
            "不知孔氏何形状，醉得君王不解醒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 陈·三阁 ----------
    {
        "id": "sun-yuan-yan-71",
        "title": "陈·三阁",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "三阁相通绮宴开，数千朱翠绕周回。",
            "只知断送君王醉，不道韩擒已到来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 陈·狎客 ----------
    {
        "id": "sun-yuan-yan-72",
        "title": "陈·狎客",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "八宫妃尽赋篇章，风揭歌声锦绣香。",
            "选得十人为狎客，有谁能解谏君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 陈·淮水 ----------
    {
        "id": "sun-yuan-yan-73",
        "title": "陈·淮水",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "文物衣冠尽入秦，六朝繁盛忽埃尘。",
            "自从淮水干枯后，不见王家更有人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 陈·江令宅 ----------
    {
        "id": "sun-yuan-yan-74",
        "title": "陈·江令宅",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "不向南朝立谏名，旧居基在事分明。",
            "令人惆怅江中令，只作篇章过一生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 陈·后庭舞 ----------
    {
        "id": "sun-yuan-yan-75",
        "title": "陈·后庭舞",
        "author": "孙元晏",
        "poet_id": "sun-yuan-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "嬿婉回风态若飞，丽华翘袖玉为姿。",
            "后庭一曲从教舞，舞破江山君未知。",
            "第七百六十八卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]