# -*- coding: utf-8 -*-
"""
冷朝阳卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 11 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 同张深秀才游华严寺 ----------
    {
        "id": "leng-zhao-yang-1",
        "title": "同张深秀才游华严寺",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "同游云外寺，渡水入禅关。立扫窗前石，坐看池上山。",
            "有僧飞锡到，留客话松间。不是缘名利，好来长伴闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 中秋与空上人同宿华严寺 ----------
    {
        "id": "leng-zhao-yang-2",
        "title": "中秋与空上人同宿华严寺",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "扫榻相逢宿，论诗旧梵宫。磬声迎鼓尽，月色过山穷。",
            "庭簇安禅草，窗飞带火虫。一宵何惜别，回首隔秋风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 宿柏岩寺 ----------
    {
        "id": "leng-zhao-yang-3",
        "title": "宿柏岩寺",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "幽寺在岩中，行唯一径通。客吟孤峤月，蝉噪数枝风。",
            "秋色生苔砌，泉声入梵宫。吾师修道处，不与世间同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 登灵善寺塔 ----------
    {
        "id": "leng-zhao-yang-4",
        "title": "登灵善寺塔",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "飞阁青霞里，先秋独早凉。天花映窗近，月桂拂檐香。",
            "华岳三峰小，黄河一带长。空闻指归路，烟处有垂杨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 瀑布泉 ----------
    {
        "id": "leng-zhao-yang-5",
        "title": "瀑布泉",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "潺湲半空里，霖落石房边。风激珠光碎，山欹练影偏。",
            "急流难起浪，迸沫只如烟。自古惟今日，凄凉一片泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 冬日逢冯法曹话怀 ----------
    {
        "id": "leng-zhao-yang-6",
        "title": "冬日逢冯法曹话怀",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "分襟二年内，多少事相干。礼乐风全变，尘埃路渐难。",
            "秋林新叶落，霜月满庭寒。虽喜逢知己，他乡岁又阑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送唐六赴举 ----------
    {
        "id": "leng-zhao-yang-7",
        "title": "送唐六赴举",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "秋色生边思，送君西入关。草衰空大野，叶落露青山。",
            "故国烟霞外，新安道路间。碧霄知己在，香桂月中攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送远上人归京 ----------
    {
        "id": "leng-zhao-yang-8",
        "title": "送远上人归京",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "夏腊岁方深，思归彻曙吟。未离销雪院，已有过云心。",
            "寒磬清函谷，孤钟宿华阴。别京游旧寺，月色似双林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 别郎上人 ----------
    {
        "id": "leng-zhao-yang-9",
        "title": "别郎上人",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "过云寻释子，话别更依依。静室开来久，游人到自稀。",
            "触风香气尽，隔水磬声微。独傍孤松立，尘中多是非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 立春 ----------
    {
        "id": "leng-zhao-yang-10",
        "title": "立春",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "玉律传佳节，青阳应此辰。土牛呈岁稔，彩燕表年春。",
            "腊尽星回次，寒馀月建寅。风光行处好，云物望中新。",
            "流水初销冻，潜鱼欲振鳞。梅花将柳色，偏思越乡人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送红线 ----------
    {
        "id": "leng-zhao-yang-11",
        "title": "送红线",
        "author": "冷朝阳",
        "poet_id": "leng-zhao-yang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "采菱歌怨木兰舟，送客魂销百尺楼。",
            "还似洛妃乘雾去，碧天无际水空流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]