# -*- coding: utf-8 -*-
"""
韦处厚卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 12 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 盛山十二诗·隐月岫 ----------
    {
        "id": "wei-chu-hou-1",
        "title": "盛山十二诗·隐月岫",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "初映钩如线，终衔镜似钩。远澄秋水色，高倚晓河流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 盛山十二诗·流杯渠 ----------
    {
        "id": "wei-chu-hou-2",
        "title": "盛山十二诗·流杯渠",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "激曲萦飞箭，浮沟泛满卮。将来山太守，早向习家池。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 盛山十二诗·竹岩 ----------
    {
        "id": "wei-chu-hou-3",
        "title": "盛山十二诗·竹岩",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "不资冬日秀，为作暑天寒。先植诚非凤，来翔定是鸾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 盛山十二诗·绣衣石榻（为温侍御置） ----------
    {
        "id": "wei-chu-hou-4",
        "title": "盛山十二诗·绣衣石榻（为温侍御置）",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "巉巉雪中峤，磊磊标方峭。勿为枕苍山，还当础清庙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 盛山十二诗·宿云亭 ----------
    {
        "id": "wei-chu-hou-5",
        "title": "盛山十二诗·宿云亭",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "雨合飞危砌，天开卷晓窗。齐平联郭柳，带绕抱城江。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 盛山十二诗·梅谿 ----------
    {
        "id": "wei-chu-hou-6",
        "title": "盛山十二诗·梅谿",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "夹岸凝清素，交枝漾浅沦。味调方荐实，腊近又先春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 盛山十二诗·桃坞 ----------
    {
        "id": "wei-chu-hou-7",
        "title": "盛山十二诗·桃坞",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "喷日舒红景，通蹊茂绿阴。终期王母摘，不羡武陵深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 盛山十二诗·胡卢沼 ----------
    {
        "id": "wei-chu-hou-8",
        "title": "盛山十二诗·胡卢沼",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "疏凿徒为巧，圆洼自可澄。倒花纷错秀，鉴月静涵冰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 盛山十二诗·茶岭 ----------
    {
        "id": "wei-chu-hou-9",
        "title": "盛山十二诗·茶岭",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "顾渚吴商绝，蒙山蜀信稀。千丛因此始，含露紫英肥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 盛山十二诗·盘石磴 ----------
    {
        "id": "wei-chu-hou-10",
        "title": "盛山十二诗·盘石磴",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "缭绕缘云上，璘玢甃玉联。高高曾几折，极目瞰秋鸢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 盛山十二诗·琵琶台 ----------
    {
        "id": "wei-chu-hou-11",
        "title": "盛山十二诗·琵琶台",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "褊地难层土，因厓遂削成。浅深岚嶂色，尽向此中呈。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 盛山十二诗·上士瓶泉（为柳律师置） ----------
    {
        "id": "wei-chu-hou-12",
        "title": "盛山十二诗·上士瓶泉（为柳律师置）",
        "author": "韦处厚",
        "poet_id": "wei-chu-hou",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "绠汲岂无井，颠崖贵非浚。愿洒尘垢馀，一雨根茎润。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]