# -*- coding: utf-8 -*-
"""
杨汝士卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 和段相公登武担寺西台 ----------
    {
        "id": "yang-ru-shi-1",
        "title": "和段相公登武担寺西台",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "清净此道宫，层台复倚空。偶时三伏外，列席九霄中。",
            "平视云端路，高临树杪风。自怜荣末座，前日别池笼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 和段相公夏登张仪楼 ----------
    {
        "id": "yang-ru-shi-2",
        "title": "和段相公夏登张仪楼",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "从公城上来，秋近绝纤埃。楼古秦规在，江分蜀望开。",
            "远山标宿雪，末席本寒灰。陪赏今为忝，临欢敢诉杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 和宗人尚书嗣复祠祭武侯毕，题临淮公旧碑 ----------
    {
        "id": "yang-ru-shi-3",
        "title": "和宗人尚书嗣复祠祭武侯毕，题临淮公旧碑",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "古柏森然地，修严蜀相祠。一过荣异代，三顾盛当时。",
            "功德流何远，馨香荐未衰。敬名探国志，饰像慰甿思。",
            "昔谒从征盖，今闻拥信旗。固宜光宠下，有泪刻前碑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 宴杨仆射新昌里第 ----------
    {
        "id": "yang-ru-shi-4",
        "title": "宴杨仆射新昌里第",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "隔坐应须赐御屏，尽将仙翰入高冥。文章旧价留鸾掖，",
            "桃李新阴在鲤庭。再岁生徒陈贺宴，一时良史尽传馨。",
            "当时疏广虽云盛，讵有兹筵醉绿醽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 建节后偶作 ----------
    {
        "id": "yang-ru-shi-5",
        "title": "建节后偶作",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "抛却弓刀上砌台，上方台榭与云开。",
            "山僧见我衣裳窄，知道新从战地来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 题画山水 ----------
    {
        "id": "yang-ru-shi-6",
        "title": "题画山水",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "太华峰前是故乡，路人遥指读书堂。",
            "如今老大骑官马，羞向关西道姓杨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 贺筵占赠营妓 ----------
    {
        "id": "yang-ru-shi-7",
        "title": "贺筵占赠营妓",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "郎君得意及青春，蜀国将军又不贫。",
            "一曲高歌红一匹，两头娘子谢夫人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 句 ----------
    {
        "id": "yang-ru-shi-8",
        "title": "句",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "昔日兰亭无艳质，此时金谷有高人。（裴令公居守东洛，",
            "夜宴半酣，公索句，元白有得色，时公为破题，次至汝",
            "士云云。白知不能加，遽裂之，曰：“笙歌鼎沸，勿作",
            "冷淡生活。”元顾白曰：“乐天所谓能全其名者也。”）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 戏柳棠 ----------
    {
        "id": "yang-ru-shi-9",
        "title": "戏柳棠",
        "author": "杨汝士",
        "poet_id": "yang-ru-shi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "文章漫道能吞凤，杯酒何曾解吃鱼。",
            "今日梓州张社会，应须遭这老尚书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]