# -*- coding: utf-8 -*-
"""
张登卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 8 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 上巳泛舟得迟字 ----------
    {
        "id": "zhang-deng-1",
        "title": "上巳泛舟得迟字",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "令节推元巳，天涯喜有期。初筵临泛地，旧俗祓禳时。",
            "枉渚潮新上，残春日正迟。竹枝游女曲，桃叶渡江词。",
            "风鹢今方退，沙鸥亦未疑。且同山简醉，倒载莫褰帷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送王主簿游南海 ----------
    {
        "id": "zhang-deng-2",
        "title": "送王主簿游南海",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "平生推久要，留滞共三年。明日东南路，穷荒雾露天。",
            "旷怀常寄酒，素业不言钱。道在贫非病，时来丑亦妍。",
            "过山乘蜡屐，涉海附楼船。行矣无为恨，宗门有大贤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 重阳宴集同用寒字 ----------
    {
        "id": "zhang-deng-3",
        "title": "重阳宴集同用寒字",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "锡宴逢佳节，穷荒亦共欢。恩深百日泽，雨借九秋寒。",
            "望气人谣洽，临风客以难。座移山色在，杯尽菊香残。",
            "欲识投醪遍，应从落帽看。还宵须命烛，举首谢三官。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 仲秋夜郡内西亭对月 ----------
    {
        "id": "zhang-deng-4",
        "title": "仲秋夜郡内西亭对月",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "天高月满影悠悠，一夜炎荒并觉秋。气与露清凝众草，",
            "色如霜白怯轻裘。高临华宇还知隙，静映长江不共流。",
            "□直西倾河汉曙，遗风犹想武昌楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 冬至夜郡斋宴别前华阴卢主簿 ----------
    {
        "id": "zhang-deng-5",
        "title": "冬至夜郡斋宴别前华阴卢主簿",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "虎宿方冬至，鸡人积夜筹。相逢一尊酒，共结两乡愁。",
            "王俭花为府，卢谌幄内璆。明朝更临水，怅望岭南流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 小雪日戏题绝句 ----------
    {
        "id": "zhang-deng-6",
        "title": "小雪日戏题绝句",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "甲子徒推小雪天，刺梧犹绿槿花然。",
            "融和长养无时歇，却是炎洲雨露偏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 招客游寺 ----------
    {
        "id": "zhang-deng-7",
        "title": "招客游寺",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "江城吏散卷春阴，山寺鸣钟隔雨深。",
            "招取遗民赴僧社，竹堂分坐静看心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 句 ----------
    {
        "id": "zhang-deng-8",
        "title": "句",
        "author": "张登",
        "poet_id": "zhang-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "孤高齐帝石，萧洒晋亭峰。（见《漳州名胜志》）。",
            "境旷穷山外，城标涨海头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]