# -*- coding: utf-8 -*-
"""
李远卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 36 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 立春日 ----------
    {
        "id": "li-yuan-1",
        "title": "立春日",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "暖日傍帘晓，浓春开箧红。钗斜穿彩燕，罗薄剪春虫。",
            "巧著金刀力，寒侵玉指风。娉婷何处戴，山鬓绿成丛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 翦彩 ----------
    {
        "id": "li-yuan-2",
        "title": "翦彩",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "翦彩赠相亲，银钗缀凤真。双双衔绶鸟，两两度桥人。",
            "叶逐金刀出，花随玉指新。愿君千万岁，无岁不逢春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 题僧院 ----------
    {
        "id": "li-yuan-3",
        "title": "题僧院",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "不用问汤休，何人免白头。百年如过鸟，万事尽浮沤。",
            "别绪长牵梦，情由乱种愁。却嫌风景丽，窗外碧云秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 观廉女真葬（女真善隶书，常为内中学士） ----------
    {
        "id": "li-yuan-4",
        "title": "观廉女真葬（女真善隶书，常为内中学士）",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "玉窗抛翠管，轻袖掩银鸾。错落云车断，丁泠金磬寒。",
            "鹤寻深院宿，人借旧书看。寂寞焚香处，红花满石坛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 闲居 ----------
    {
        "id": "li-yuan-5",
        "title": "闲居",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "尘事久相弃，沈浮皆不知。牛羊归古巷，燕雀绕疏篱。",
            "买药经年晒，留僧尽日棋。唯忧钓鱼伴，秋水隔波时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 及第后送家兄游蜀 ----------
    {
        "id": "li-yuan-6",
        "title": "及第后送家兄游蜀",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "人谁无远别，此别意多违。正鹄虽言中，冥鸿不共飞。",
            "玉京烟雨断，巴国梦魂归。若过严家濑，殷勤看钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送人入蜀 ----------
    {
        "id": "li-yuan-7",
        "title": "送人入蜀",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "蜀客本多愁，君今是胜游。碧藏云外树，红露驿边楼。",
            "杜魄呼名语，巴江作字流。不知烟雨夜，何处梦刀州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 游故王驸马池亭 ----------
    {
        "id": "li-yuan-8",
        "title": "游故王驸马池亭",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "花树杳玲珑，渔舟处处通。醉销罗绮艳，香暖芰荷风。",
            "野鸟翻萍绿，斜桥印水红。子猷箫管绝，谁爱碧鲜浓。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 悲铜雀台 ----------
    {
        "id": "li-yuan-9",
        "title": "悲铜雀台",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "西陵树已尽，铜雀思偏多。雪密疑楼阁，花开想绮罗。",
            "影销堂上舞，声断帐前歌。唯有漳河水，年年旧绿波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 陪新及第赴同年会 ----------
    {
        "id": "li-yuan-10",
        "title": "陪新及第赴同年会",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "曾攀芳桂英，处处共君行。今日杏园宴，当时天乐声。",
            "柳浓堪系马，花上未藏莺。满座皆仙侣，同年别有情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 咏雁 ----------
    {
        "id": "li-yuan-11",
        "title": "咏雁",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "早晚辞沙漠，南来处处飞。关山多雨雪，风水损毛衣。",
            "碧海魂应断，红楼信自稀。不知矰缴外，留得几行归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 与碧溪上人别 ----------
    {
        "id": "li-yuan-12",
        "title": "与碧溪上人别",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "欲入凤城游，西溪别惠休。色随花旋落，年共水争流。",
            "客思偏来夜，蝉声觉送秋。明朝逢旧侣，唯拟上歌楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 赠殷山人 ----------
    {
        "id": "li-yuan-13",
        "title": "赠殷山人",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "有客抱琴宿，值予多怨怀。啼乌弦易断，啸鹤调难谐。",
            "曲罢月移幌，韵清风满斋。谁能将此妙，一为奏金阶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 咏壁鱼 ----------
    {
        "id": "li-yuan-14",
        "title": "咏壁鱼",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "鳞细粉光鲜，开书乱眼前。透窗疑漏网，落砚似流泉。",
            "潜穴河图内，吞钩乙字边。莫言鬐鬣小，食尽白蘋篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 听话丛台 ----------
    {
        "id": "li-yuan-15",
        "title": "听话丛台",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "有客新从赵地回，自言曾上古丛台。云遮襄国天边去，",
            "树绕漳河地里来。弦管变成山鸟哢，绮罗留作野花开。",
            "金舆玉辇无行迹，风雨惟知长绿苔。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 失鹤 ----------
    {
        "id": "li-yuan-16",
        "title": "失鹤",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "秋风吹却九皋禽，一片闲云万里心。碧落有情应怅望，",
            "青天无路可追寻。来时白云翎犹短，去日丹砂顶渐深。",
            "华表柱头留语后，更无消息到如今。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 赠写御容李长史 ----------
    {
        "id": "li-yuan-17",
        "title": "赠写御容李长史",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "玉座尘消砚水清，龙髯不动彩毫轻。初分隆准山河秀，",
            "乍点重瞳日月明。宫女卷帘皆暗认，侍臣开殿尽遥惊。",
            "三朝供奉无人敌，始觉僧繇浪得名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 赠潼关不下山僧 ----------
    {
        "id": "li-yuan-18",
        "title": "赠潼关不下山僧",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "与君同在苦空间，君得空门我爱闲。禁足已教修雁塔，",
            "终身不拟下鸡山。窗中遥指三千界，枕上斜看百二关。",
            "香茗一瓯从此别，转蓬流水几时还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 过旧游见双鹤怆然有怀 ----------
    {
        "id": "li-yuan-19",
        "title": "过旧游见双鹤怆然有怀",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "谢公何岁掩松楸，双鹤依然傍玉楼。朱顶巑岏荒草上，",
            "雪毛零落小池头。蓬瀛路断君何在，云水情深我尚留。",
            "他日若来华表上，更添多少令威愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 赠友人 ----------
    {
        "id": "li-yuan-20",
        "title": "赠友人",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "凤城烟霭思偏多，曾向刘郎住处过。银烛焰前贪劝酒，",
            "玉箫声里已闻歌。佳人惜别看嘶马，公子含情向翠蛾。",
            "今日重来门巷改，出墙桐树绿婆娑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 赠南岳僧 ----------
    {
        "id": "li-yuan-21",
        "title": "赠南岳僧",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "曾住衡阳岳寺边，门开江水与云连。数州城郭藏寒树，",
            "一片风帆著远天。猿啸不离行道处，客来皆到卧床前。",
            "今朝惆怅红尘里，惟忆闲陪尽日眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 赠弘文杜校书 ----------
    {
        "id": "li-yuan-22",
        "title": "赠弘文杜校书",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "高倚霞梯万丈馀，共看移步入宸居。晓随鹓鹭排金锁，",
            "静对铅黄校玉书。漠漠禁烟笼远树，泠泠宫漏响前除。",
            "还闻汉帝亲词赋，好为从容奏子虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 听王氏话归州昭君庙 ----------
    {
        "id": "li-yuan-23",
        "title": "听王氏话归州昭君庙",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "献之闲坐说归州，曾到昭君庙里游。自古行人多怨恨，",
            "至今乡土尽风流。泉如珠泪侵阶滴，花似红妆满岸愁。",
            "河畔犹残翠眉样，有时新月傍帘钩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 过马嵬山（一作李益诗） ----------
    {
        "id": "li-yuan-24",
        "title": "过马嵬山（一作李益诗）",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "金甲云旗尽日回，仓皇罗袖满尘埃。浓香犹自飘銮辂，",
            "恨魄无因离马嵬。南内宫人悲帐殿，东溟方士问蓬莱。",
            "唯馀坡上弯环月，时送残蛾入帝台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 吴越怀古 ----------
    {
        "id": "li-yuan-25",
        "title": "吴越怀古",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "吴越千年奈怨何，两宫清吹作樵歌。姑苏一败云无色，",
            "范蠡长游水自波。霞拂故城疑转旆，月依荒树想嚬蛾。",
            "行人欲问西施馆，江鸟寒飞碧草多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 长安即事寄友人 ----------
    {
        "id": "li-yuan-26",
        "title": "长安即事寄友人",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "绮陌千年思断蓬，今来还宿凤城东。瑶台钟鼓长依旧，",
            "巫陕烟花自不同。千结故心为怨网，万条新景作愁笼。",
            "何时更伴刘郎去，却见夭桃满树红。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 闻明上人逝寄友人 ----------
    {
        "id": "li-yuan-27",
        "title": "闻明上人逝寄友人",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "萧寺曾过最上方，碧桐浓叶覆西廊。游人缥缈红衣乱，",
            "座客从容白日长。别后旋成庄叟梦，书来忽报惠休亡。",
            "他时若更相随去，只是含酸对影堂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 赠咸阳李少府 ----------
    {
        "id": "li-yuan-28",
        "title": "赠咸阳李少府",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "美貌雄才已少齐，宝书仙简两看题。金刀片片裁新锦，",
            "玉步重重上旧梯。鹏到碧天排雾去，凤游琼树拣枝栖。",
            "蓬瀛宴罢试回首，一望尘中路正迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 邻人自金仙观移竹 ----------
    {
        "id": "li-yuan-29",
        "title": "邻人自金仙观移竹",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "移居新竹已堪看，劚破莓苔得几竿。圆节不教伤粉箨，",
            "低枝犹拟拂霜坛。墙头枝动如烟绿，枕上风来送夜寒。",
            "第一莫教渔父见，且从萧飒满朱栏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 慈恩寺避暑 ----------
    {
        "id": "li-yuan-30",
        "title": "慈恩寺避暑",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "香荷疑散麝，风铎似调琴。不觉清凉晚，归人满柳阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 读田光传 ----------
    {
        "id": "li-yuan-31",
        "title": "读田光传",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "秦灭燕丹怨正深，古来豪客尽沾襟。",
            "荆卿不了真闲事，辜负田光一片心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 友人下第因以赠之 ----------
    {
        "id": "li-yuan-32",
        "title": "友人下第因以赠之",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "刘毅虽然不掷卢，谁人不道解樗蒲。",
            "黄金百万终须得，只有挼莎更一呼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 咏鸳鸯 ----------
    {
        "id": "li-yuan-33",
        "title": "咏鸳鸯",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "鸳鸯离别伤，人意似鸳鸯。试取鸳鸯看，多应断寸肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 赠筝妓伍卿 ----------
    {
        "id": "li-yuan-34",
        "title": "赠筝妓伍卿",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "轻轻没后更无筝，玉腕红纱到伍卿。",
            "座客满筵都不语，一行哀雁十三声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 黄陵庙词（一作李群玉诗） ----------
    {
        "id": "li-yuan-35",
        "title": "黄陵庙词（一作李群玉诗）",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "黄陵庙前莎草春，黄陵女儿蒨裙新。",
            "轻舟小楫唱歌去，水远山长愁杀人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 句 ----------
    {
        "id": "li-yuan-36",
        "title": "句",
        "author": "李远",
        "poet_id": "li-yuan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "人事三杯酒，流年一局棋。（《北梦琐言》）。",
            "青山不厌三杯酒，长日惟消一局棋。（《唐语林》）。",
            "第五百二十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]