# -*- coding: utf-8 -*-
"""
綦毋潜卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 26 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 冬夜寓居寄储太祝（一作薛据诗） ----------
    {
        "id": "qi-wu-qian-1",
        "title": "冬夜寓居寄储太祝（一作薛据诗）",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "自为洛阳客，夫子吾知音。尽义能下士，时人无此心。",
            "奈何离居夜，巢鸟悲空林。愁坐至月上，复闻南邻砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 春泛若耶溪 ----------
    {
        "id": "qi-wu-qian-2",
        "title": "春泛若耶溪",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "幽意无断绝，此去随所偶。晚风吹行舟，花路入溪口。",
            "际夜转西壑，隔山望南斗。潭烟飞溶溶，林月低向后。",
            "生事且弥漫，愿为持竿叟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 题鹤林寺 ----------
    {
        "id": "qi-wu-qian-3",
        "title": "题鹤林寺",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "道林隐形胜，向背临层霄。松覆山殿冷，花藏谿路遥。",
            "珊珊宝幡挂，焰焰明灯烧。迟日半空谷，春风连上潮。",
            "少凭水木兴，暂令身心调。愿谢携手客，兹山禅诵饶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题栖霞寺 ----------
    {
        "id": "qi-wu-qian-4",
        "title": "题栖霞寺",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "南山势回合，灵境依此住。殿转云崖阴，僧探石泉度。",
            "龙蛇争翕习，神鬼皆密护。万壑奔道场，群峰向双树。",
            "天花飞不著，水月白成路。今日观身我，归心复何处。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送储十二还庄城 ----------
    {
        "id": "qi-wu-qian-5",
        "title": "送储十二还庄城",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "西坂何缭绕，青林问子家。天寒噪野雀，日晚度城鸦。",
            "寂历道傍树，曈曨原上霞。兹情不可说，长恨隐沦赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送章彝下第 ----------
    {
        "id": "qi-wu-qian-6",
        "title": "送章彝下第",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "长安渭桥路，行客别时心。献赋温泉毕，无媒魏阙深。",
            "黄莺啼就马，白日暗归林。三十名未立，君还惜寸阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送崔员外黔中监选 ----------
    {
        "id": "qi-wu-qian-7",
        "title": "送崔员外黔中监选",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "持衡出帝畿，星指夜郎飞。神女云迎马，荆门雨湿衣。",
            "听猿收泪罢，系雁待书稀。蛮貊虽殊俗，知君肝胆微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送贾恒明府兼寄温张二司户 ----------
    {
        "id": "qi-wu-qian-8",
        "title": "送贾恒明府兼寄温张二司户",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "越客新安别，秦人旧国情。舟乘晚风便，月带上潮平。",
            "花路西施石，云峰句践城。明州报两掾，相忆二毛生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送宋秀才 ----------
    {
        "id": "qi-wu-qian-9",
        "title": "送宋秀才",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "冠古积荣盛，当时数戟门。旧交丞相子，继世五侯孙。",
            "长剑倚天外，短书盈万言。秋风一送别，江上黯消魂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送平判官入秦（一作卢象诗） ----------
    {
        "id": "qi-wu-qian-10",
        "title": "送平判官入秦（一作卢象诗）",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "谪远自安命，三年已忘归。同声愿执手，驿骑到门扉。",
            "云是帝乡去，军书谒紫微。曾为金马客，向日泪沾衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送郑务拜伯父 ----------
    {
        "id": "qi-wu-qian-11",
        "title": "送郑务拜伯父",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "名公作逐臣，驱马拂行尘。旧国问郧子，劳歌过郢人。",
            "一川花送客，二月柳宜春。奉料竹林兴，宽怀此别晨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 题招隐寺绚公房 ----------
    {
        "id": "qi-wu-qian-12",
        "title": "题招隐寺绚公房",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "开士度人久，空岩花雾深。徒知燕坐处，不见有为心。",
            "兰若门对壑，田家路隔林。还言证法性，归去比黄金。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 宿太平观 ----------
    {
        "id": "qi-wu-qian-13",
        "title": "宿太平观",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "夕到玉京寝，窅冥云汉低。魂交仙室蝶，曙听羽人鸡。",
            "滴沥花上露，清泠松下谿。明当访真隐，挥手入无倪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 题灵隐寺山顶禅院 ----------
    {
        "id": "qi-wu-qian-14",
        "title": "题灵隐寺山顶禅院",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "招提此山顶，下界不相闻。塔影挂清汉，钟声和白云。",
            "观空静室掩，行道众香焚。且驻西来驾，人天日未曛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 若耶溪逢孔九 ----------
    {
        "id": "qi-wu-qian-15",
        "title": "若耶溪逢孔九",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "相逢此溪曲，胜托在烟霞。潭影竹间动，岩阴檐外斜。",
            "人言上皇代，犬吠武陵家。借问淹留日，春风满若耶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 宿龙兴寺 ----------
    {
        "id": "qi-wu-qian-16",
        "title": "宿龙兴寺",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "香刹夜忘归，松青古殿扉。灯明方丈室，珠系比丘衣。",
            "白日传心静，青莲喻法微。天花落不尽，处处鸟衔飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 题沈东美员外山池 ----------
    {
        "id": "qi-wu-qian-17",
        "title": "题沈东美员外山池",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "仙郎偏好道，凿沼象瀛洲。鱼乐随情性，船行任去留。",
            "秦人辨鸡犬，尧日识巢由。归客衡门外，仍怜返景幽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 茅山洞口 ----------
    {
        "id": "qi-wu-qian-18",
        "title": "茅山洞口",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "华阳仙洞口，半岭拂云看。窈窕穿苔壁，差池对石坛。",
            "方随地脉转，稍觉水晶寒。未果变金骨，归来兹路难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 过方尊师院 ----------
    {
        "id": "qi-wu-qian-19",
        "title": "过方尊师院",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "羽客北山寻，草堂松径深。养神宗示法，得道不知心。",
            "洞户逢双履，寥天有一琴。更登玄圃上，仍种杏成林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 经陆补阙隐居 ----------
    {
        "id": "qi-wu-qian-20",
        "title": "经陆补阙隐居",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "不敢要君征亦起，致君全得似唐虞。谠言昨叹离天听，",
            "新象今闻入县图。琴锁坏窗风自响，鹤归乔木隐难呼。",
            "学书弟子何人在，点检犹存谏草无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 登天竺寺 ----------
    {
        "id": "qi-wu-qian-21",
        "title": "登天竺寺",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "郡有化城最，西穷叠嶂深。松门当涧口，石路在峰心。",
            "幽见夕阳霁，高逢暮雨阴。佛身瞻绀发，宝地践黄金。",
            "云向竹谿尽，月从花洞临。因物成真悟，遗世在兹岑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 满公房 ----------
    {
        "id": "qi-wu-qian-22",
        "title": "满公房",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "世界莲花藏，行人香火缘。灯王照不尽，中夜寂相传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 过融上人兰若（一作孟浩然诗） ----------
    {
        "id": "qi-wu-qian-23",
        "title": "过融上人兰若（一作孟浩然诗）",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "山头禅室挂僧衣，窗外无人溪鸟飞。",
            "黄昏半在下山路，却听钟声连翠微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 早发上东门 ----------
    {
        "id": "qi-wu-qian-24",
        "title": "早发上东门",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "十五能行西入秦，三十无家作路人。",
            "时命不将明主合，布衣空染洛阳尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 祇园寺 ----------
    {
        "id": "qi-wu-qian-25",
        "title": "祇园寺",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "宝坊求往迹，神理驻沿洄。雁塔酬前愿，王身更后来。",
            "加持将暝合，朗悟豁然开。两世分明见，馀生复几哉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送集贤学士伊阙史少府放归江东觐省（一作陶翰诗） ----------
    {
        "id": "qi-wu-qian-26",
        "title": "送集贤学士伊阙史少府放归江东觐省（一作陶翰诗）",
        "author": "綦毋潜",
        "poet_id": "qi-wu-qian",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "墨客钟张侣，材高吴越珍。千门来谒帝，驷马去荣亲。",
            "吏邑沿清洛，乡山指白蘋。归期应不远，当及未央春。",
            "第一百三十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]