# -*- coding: utf-8 -*-
"""
于邺卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 34 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 书怀 ----------
    {
        "id": "yu-ye-1",
        "title": "书怀",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "长安多路岐，西去欲何依。浮世只如此，旧山长忆归。",
            "自离京国久，应已故人稀。好与孤云住，孤云无是非。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 书情 ----------
    {
        "id": "yu-ye-2",
        "title": "书情",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "负郭有田在，年年长废耕。欲磨秋镜净，恐见白头生。",
            "未作一旬别，已过千里程。不知书与剑，十载两无成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 涂中作 ----------
    {
        "id": "yu-ye-3",
        "title": "涂中作",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "西南千里程，处处有车声。若使地无利，始应人不营。",
            "天涯犹马到，石迹尚尘生。如此未曾息，蜀山终冀平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春过函谷关 ----------
    {
        "id": "yu-ye-4",
        "title": "春过函谷关",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "几度作游客，客行长苦辛。愁看函谷路，老尽布衣人。",
            "岁远关犹固，时移草亦春。何当名利息，遣此绝征轮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 褒中即事 ----------
    {
        "id": "yu-ye-5",
        "title": "褒中即事",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "风吹残雨歇，云去有烟霞。南浦足游女，绿蘋应发花。",
            "远钟当半夜，明月入千家。不作故乡梦，始知京洛赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 岁暮还家 ----------
    {
        "id": "yu-ye-6",
        "title": "岁暮还家",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "东西流不驻，白日与车轮。残雪半成水，微风应欲春。",
            "几经他国岁，已减故乡人。回首长安道，十年空苦辛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 还家 ----------
    {
        "id": "yu-ye-7",
        "title": "还家",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "为客忆归舍，归来还寂寥。壮时看欲过，白首固非遥。",
            "独酌几回醉，此愁终不销。犹残鸡与犬，驱去住山椒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 题华山麻处士所居 ----------
    {
        "id": "yu-ye-8",
        "title": "题华山麻处士所居",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "贵贱各扰扰，皆逢朝市间。到此马无迹，始知君独闲。",
            "冰破听敷水，雪晴看华山。西风寂寥地，唯我坐忘还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 天南怀故人 ----------
    {
        "id": "yu-ye-9",
        "title": "天南怀故人",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "独行千里尘，轧轧转征轮。一别已多日，总看成老人。",
            "洞庭雪不下，故国草应春。三月烟波暖，南风生绿蘋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 路傍草 ----------
    {
        "id": "yu-ye-10",
        "title": "路傍草",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "春至始青青，香车碾已平。不知山下处，来向路傍生。",
            "每岁有人在，何时无马行。应随尘与土，吹满洛阳城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 秋夕闻雁 ----------
    {
        "id": "yu-ye-11",
        "title": "秋夕闻雁",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "星汉欲沈尽，谁家砧未休。忽闻凉雁至，如报杜陵秋。",
            "千树又黄叶，几人新白头。洞庭今夜客，一半却登舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 洛中有怀 ----------
    {
        "id": "yu-ye-12",
        "title": "洛中有怀",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "潺潺伊洛河，寂寞少恩波。銮驾久不幸，洛阳春草多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送魏山韦处士（一作送田处士西游） ----------
    {
        "id": "yu-ye-13",
        "title": "送魏山韦处士（一作送田处士西游）",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "阴阴亭际间，相顾惨离颜。一片云飞去，嵯峨空魏山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 白樱桃 ----------
    {
        "id": "yu-ye-14",
        "title": "白樱桃",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "王母阶前种几株，水晶帘内看如无。",
            "只应汉武金盘上，泻得珊珊白露珠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 白樱树 ----------
    {
        "id": "yu-ye-15",
        "title": "白樱树",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "记得花开雪满枝，和蜂和蝶带花移。",
            "如今花落游蜂去，空作主人惆怅诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 下第不胜其忿题路左佛庙 ----------
    {
        "id": "yu-ye-16",
        "title": "下第不胜其忿题路左佛庙",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "雀儿未逐飏风高，下视鹰鹯意气豪。",
            "自谓能生千里足，黄昏依旧委蓬蒿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 感怀（一作感情） ----------
    {
        "id": "yu-ye-17",
        "title": "感怀（一作感情）",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "东风吹草色，空使客蹉跎。不设太平险，更应游子多。",
            "几伤行处泪，一曲醉中歌。尽向青门外，东随渭水波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 游中梁山 ----------
    {
        "id": "yu-ye-18",
        "title": "游中梁山",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "僻地好泉石，何人曾陆沈。不知青嶂外，更有白云深。",
            "因此见乔木，几回思旧林。殷勤猿与鸟，唯我独何心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 寻山 ----------
    {
        "id": "yu-ye-19",
        "title": "寻山",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "到此绝车轮，萋萋草树春。青山如有利，白石亦成尘。",
            "水阔应无路，松深不见人。如知巢与许，千载迹犹新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 宿江口 ----------
    {
        "id": "yu-ye-20",
        "title": "宿江口",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "南渡人来绝，喧喧雁满沙。自生江上月，长有客思家。",
            "半夜下霜岸，北风吹荻花。自惊归梦断，不得到天涯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 秋夜达萧关 ----------
    {
        "id": "yu-ye-21",
        "title": "秋夜达萧关",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "扰扰浮梁路，人忙月自闲。去年为塞客，今夜宿萧关。",
            "辞国几经岁，望乡空见山。不知江叶下，又作布衣还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 斜谷道 ----------
    {
        "id": "yu-ye-22",
        "title": "斜谷道",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "乱峰连叠嶂，千里绿峨峨。蜀国路如此，游人车亦过。",
            "远烟当驿敛，骤雨逐风多。独忆紫芝叟，临风歌旧歌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 过百牢关贻舟中者 ----------
    {
        "id": "yu-ye-23",
        "title": "过百牢关贻舟中者",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "蜀国少平地，方思京洛间。远为千里客，来度百牢关。",
            "帆影清江水，铃声碧草山。不因名与利，尔我各应闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 客中览镜 ----------
    {
        "id": "yu-ye-24",
        "title": "客中览镜",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "何当开此镜，即见发如丝。白日急于水，少年能几时。",
            "每逢芳草处，长返故园迟。所以多为客，蹉跎欲怨谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 长安逢隐者 ----------
    {
        "id": "yu-ye-25",
        "title": "长安逢隐者",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "征车千里至，碾遍六街尘。向此有营地，忽逢无事人。",
            "昔时颜未改，浮世路多新。且脱衣沽酒，终南山欲春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 与僧话旧 ----------
    {
        "id": "yu-ye-26",
        "title": "与僧话旧",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "草堂前有山，一见一相宽。处世贵僧静，青松因岁寒。",
            "他山逢旧侣，尽日话长安。所以闲行迹，千回绕药栏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 赠王道士 ----------
    {
        "id": "yu-ye-27",
        "title": "赠王道士",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "日日市朝路，何时无苦辛。不随丹灶客，终作白头人。",
            "浮世度千载，桃源方一春。归来华表上，应笑北邙尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 匣中琴 ----------
    {
        "id": "yu-ye-28",
        "title": "匣中琴",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "世人无正心，虫网匣中琴。何以经时废，非为娱耳音。",
            "独令高韵在，谁感隙尘深。应是南风曲，声声不合今。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 友人亭松 ----------
    {
        "id": "yu-ye-29",
        "title": "友人亭松",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "俯仰不能去，如逢旧友同。曾因春雪散，见在华山中。",
            "何处有明月，访君听远风。相将归未得，各占石岩东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 过洛阳城 ----------
    {
        "id": "yu-ye-30",
        "title": "过洛阳城",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "古来利与名，俱在洛阳城。九陌鼓初起，万车轮已行。",
            "周秦时几变，伊洛水犹清。二月中桥路，鸟啼春草生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 客中月（一作望月） ----------
    {
        "id": "yu-ye-31",
        "title": "客中月（一作望月）",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "离家凡几宵，一望一寥寥。新魄又将满，故乡应渐遥。",
            "独临彭蠡水，远忆洛阳桥。更有乘舟客，凄然亦驻桡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 王将军宅夜听歌 ----------
    {
        "id": "yu-ye-32",
        "title": "王将军宅夜听歌",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "朱槛满明月，美人歌落梅。忽惊尘起处，疑有凤飞来。",
            "一曲听初彻，几年愁暂开。东南正云雨，不得见阳台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 长信宫 ----------
    {
        "id": "yu-ye-33",
        "title": "长信宫",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "莫问古宫名，古宫空有城。惟应东去水，不改旧时声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 高楼 ----------
    {
        "id": "yu-ye-34",
        "title": "高楼",
        "author": "于邺",
        "poet_id": "yu-ye",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "远天明月出，照此谁家楼。上有罗衣裳，凉风吹不休。",
            "第七百二十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]