# -*- coding: utf-8 -*-
"""
王睿卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 11 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·公无渡河 ----------
    {
        "id": "wang-rui-1",
        "title": "相和歌辞·公无渡河",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "浊波洋洋兮凝晓雾，公无渡河兮公苦渡。",
            "风号水激兮呼不闻，提壶看入兮中流去。",
            "浪摆衣裳兮随步没，沉尸深入兮蛟螭窟。",
            "蛟螭尽醉兮君血干，推出黄沙兮泛君骨。",
            "当时君死妾何适，遂就波澜合魂魄。",
            "愿持精卫衔石心，穷取河源塞泉脉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·祠神歌·迎神 ----------
    {
        "id": "wang-rui-2",
        "title": "相和歌辞·祠神歌·迎神",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "蓪草头花椰叶裙，蒲葵树下舞蛮云。",
            "引领望江遥滴酒，白蘋风起水生文。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 相和歌辞·祠神歌·送神 ----------
    {
        "id": "wang-rui-3",
        "title": "相和歌辞·祠神歌·送神",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "枨枨山响答琵琶，酒湿青莎肉饲鸦。",
            "树叶无声神去后，纸钱灰出木绵花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 公无渡河 ----------
    {
        "id": "wang-rui-4",
        "title": "公无渡河",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "浊波洋洋兮凝晓雾，公无渡河兮公竟渡。",
            "风号水激兮呼不闻，提壶看入兮中流去。",
            "浪摆衣裳兮随步没，沉尸深入兮蛟螭窟。",
            "蛟螭尽醉兮君血干，推出黄沙兮泛君骨。",
            "当时君死妾何适，遂就波涛合魂魄。愿持精卫衔石心，",
            "穷取河源塞泉脉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 松 ----------
    {
        "id": "wang-rui-5",
        "title": "松",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "寒松耸拔倚苍岑，绿叶扶疏自结阴。丁固梦时还有意，",
            "秦王封日岂无心。常将正节栖孤鹤，不遣高枝宿众禽。",
            "好是特凋群木后，护霜凌雪翠逾深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 竹 ----------
    {
        "id": "wang-rui-6",
        "title": "竹",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "庭竹森疏玉质寒，色包葱碧尽琅玕。翠筠不乐湘娥泪，",
            "斑箨堪裁汉主冠。成韵含风已萧瑟，媚涟凝渌更檀栾。",
            "此君引凤为龙日，耸节稍云直上看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 解昭君怨 ----------
    {
        "id": "wang-rui-7",
        "title": "解昭君怨",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "莫怨工人丑画身，莫嫌明主遣和亲。",
            "当时若不嫁胡虏，只是宫中一舞人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 祠渔山神女歌二首 ----------
    {
        "id": "wang-rui-8",
        "title": "祠渔山神女歌二首",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "蓪草头花椰叶裙，蒲葵树下舞蛮云。",
            "引领望江遥滴酒，白蘋风起水生文。",
            "枨枨山响答琵琶，酒湿青莎肉饲鸦。",
            "树叶无声神去后，纸钱灰出木绵花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 牡丹（一作王毂诗） ----------
    {
        "id": "wang-rui-9",
        "title": "牡丹（一作王毂诗）",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "牡丹妖艳乱人心，一国如狂不惜金。",
            "曷若东园桃与李，果成无语自成阴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 秋（一作王毂诗） ----------
    {
        "id": "wang-rui-10",
        "title": "秋（一作王毂诗）",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "蝉噪古槐疏叶下，树衔斜日映孤城。",
            "欲知潘鬓愁多少，一夜新添白数茎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 燕（一作王毂诗） ----------
    {
        "id": "wang-rui-11",
        "title": "燕（一作王毂诗）",
        "author": "王睿",
        "poet_id": "wang-rui",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "海燕双飞意若何，曲梁呕嘎语声多。",
            "茅檐不必嫌卑陋，犹胜吴宫爇尔窠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]