# -*- coding: utf-8 -*-
"""
周繇卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 22 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 送边上从事 ----------
    {
        "id": "zhou-yao-1",
        "title": "送边上从事",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "戎装佩镆铘，走马逐轻车。衰草城边路，残阳垄上笳。",
            "黄河穿汉界，青冢出胡沙。提笔男儿事，功名立可夸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 送洛阳崔员外 ----------
    {
        "id": "zhou-yao-2",
        "title": "送洛阳崔员外",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "塞诏除嵩洛，观图见废兴。城迁周古鼎，地列汉诸陵。",
            "日送归朝客，时招住岳僧。郡斋台阁满，公退即吟登。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送人尉黔中 ----------
    {
        "id": "zhou-yao-3",
        "title": "送人尉黔中",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "盘山行几驿，水路复通巴。峡涨三川雪，园开四季花。",
            "公庭飞白鸟，官俸请丹砂。知尉黔中后，高吟采物华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送宇文虞 ----------
    {
        "id": "zhou-yao-4",
        "title": "送宇文虞",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "此别欲何往，未言归故林。行车新岁近，落日乱山深。",
            "野店寒无客，风巢动有禽。潜知经目事，大半是愁吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题东林寺虎掊泉 ----------
    {
        "id": "zhou-yao-5",
        "title": "题东林寺虎掊泉",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "胜致通幽感，灵泉有虎掊。爪抬山脉断，掌托石心拗。",
            "竹蔼疑相近，松阴盖亦交。转令栖遁者，真境逾难抛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 登甘露寺 ----------
    {
        "id": "zhou-yao-6",
        "title": "登甘露寺",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "盘江上几层，峭壁半垂藤。殿锁南朝像，龛禅外国僧。",
            "海涛摏砌槛，山雨洒窗灯。日暮疏钟起，声声彻广陵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 甘露寺东轩 ----------
    {
        "id": "zhou-yao-7",
        "title": "甘露寺东轩",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "每日怜晴眺，闲吟只自娱。山从平地有，水到远天无。",
            "老树多封楚，轻烟暗染吴。虽居此廊下，入户亦踌蹰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 甘露寺北轩 ----------
    {
        "id": "zhou-yao-8",
        "title": "甘露寺北轩",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "晓色宜闲望，山风远益清。白云连晋阁，碧树尽芜城。",
            "少静沙痕出，烟消野火平。最堪佳此境，为我长诗情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 咏萤 ----------
    {
        "id": "zhou-yao-9",
        "title": "咏萤",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "熠熠与娟娟，池塘竹树边。乱飞同曳火，成聚却无烟。",
            "微雨洒不灭，轻风吹欲燃。旧曾书案上，频把作囊悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 望海 ----------
    {
        "id": "zhou-yao-10",
        "title": "望海",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "苍茫空泛日，四顾绝人烟。半浸中华岸，旁通异域船。",
            "岛间应有国，波外恐无天。欲作乘槎客，翻愁去隔年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送杨环校书归广南 ----------
    {
        "id": "zhou-yao-11",
        "title": "送杨环校书归广南",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "天南行李半波涛，滩树枝枝拂戏猱。初著蓝衫从远峤，",
            "乍辞云署泊轻艘。山村象踏桄榔叶，海外人收翡翠毛。",
            "名宦两成归旧隐，遍寻亲友兴何饶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 经故宅有感 ----------
    {
        "id": "zhou-yao-12",
        "title": "经故宅有感",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "身没南荒雨露赊，朱门空锁旧繁华。池塘凿就方通水，",
            "桃杏栽成未见花。异代图书藏几箧，倾城罗绮散谁家。",
            "昔年埏埴生灵地，今日生人为叹嗟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 送入蕃使 ----------
    {
        "id": "zhou-yao-13",
        "title": "送入蕃使",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "猎猎旗幡过大荒，敕书犹带御烟香。滹沱河冻军回探，",
            "逻逤孤城雁著行。远寨风狂移帐幕，平沙日晚卧牛羊。",
            "早终册礼朝天阙，莫遣虬髭染塞霜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 白石潭秋霁作 ----------
    {
        "id": "zhou-yao-14",
        "title": "白石潭秋霁作",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "潭心烟雾破斜晖，殷殷雷声隔翠微。崖蹙盘涡翻蜃窟，",
            "滩吹白石上渔矶。陵风舴艋讴哑去，出水鸬鹚薄泊飞。",
            "秋霁更谁同此望，远钟时见一僧归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 题金陵栖霞寺赠月公 ----------
    {
        "id": "zhou-yao-15",
        "title": "题金陵栖霞寺赠月公",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "明家不要买山钱，施作清池种白莲。松桧老依云外地，",
            "楼台深锁洞中天。风经绝顶回疏雨，石倚危屏挂落泉。",
            "欲结茅庵伴师住，肯饶多少薜萝烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 嘲段成式（一作广阳公宴） ----------
    {
        "id": "zhou-yao-16",
        "title": "嘲段成式（一作广阳公宴）",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "蹙鞠且徒为，宁如目送时。报仇惭选耎，存想恨逶迟。",
            "促坐疑辟咡，衔杯强朵颐。恣情窥窈窕，曾恃好风姿。",
            "色授应难夺，神交愿莫辞。请君看曲谱，不负少年期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送江州薛尚书 ----------
    {
        "id": "zhou-yao-17",
        "title": "送江州薛尚书",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "匡庐千万峰，影匝郡城中。忽佩虎符去，遥疑鸟道通。",
            "烟霞时满郭，波浪暮连空。树翳楼台月，帆飞鼓角风。",
            "郡斋多岳客，乡户半渔翁。王事行春外，题诗寄远公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 津头望白水 ----------
    {
        "id": "zhou-yao-18",
        "title": "津头望白水",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "晴江暗涨岸吹沙，山畔船冲树杪斜。",
            "城郭半淹桥市闹，鹭鸶缭绕入人家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 公子行 ----------
    {
        "id": "zhou-yao-19",
        "title": "公子行",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "青山薄薄漏春风，日暮鸣鞭柳影中。",
            "回望玉楼人不见，酒旗深处勒花骢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 看牡丹赠段成式（柯古前看吝酒） ----------
    {
        "id": "zhou-yao-20",
        "title": "看牡丹赠段成式（柯古前看吝酒）",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "金蕊霞英叠彩香，初疑少女出兰房。",
            "逡巡又是一年别，寄语集仙呼索郎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 以人参遗段成式 ----------
    {
        "id": "zhou-yao-21",
        "title": "以人参遗段成式",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "人形上品传方志，我得真英自紫团。",
            "惭非叔子空持药，更请伯言审细看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 和段成式 ----------
    {
        "id": "zhou-yao-22",
        "title": "和段成式",
        "author": "周繇",
        "poet_id": "zhou-yao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "回簪转黛喜猜防，粉署裁诗助酒狂。",
            "若遇仙丹偕羽化，但随萧史亦何伤。",
            "玉树琼筵映彩霞，澄虚楼阁似仙家。",
            "只缘存想归兰室，不向春风看夜花。",
            "第六百三十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]