# -*- coding: utf-8 -*-
"""
卢士衡卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 灵溪老松歌 ----------
    {
        "id": "lu-shi-heng-1",
        "title": "灵溪老松歌",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "灵溪古观坛西角，千尺鳞皴栋梁朴。横出一枝戛楼阁，",
            "直上一枝扫寥廓。白石苍苔拥根脚，月明风撼寒光落。",
            "有时风雨晦暝，摆撼若黑龙之腾跃。合生于象外峰峦，",
            "枉滞乎人间山岳。安得巨灵受请托，拔向青桂白榆边安著。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 游灵溪观 ----------
    {
        "id": "lu-shi-heng-2",
        "title": "游灵溪观",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "云藏宝殿风尘外，粉壁松轩入看初。话久仙童颜色老，",
            "病来玄鹤羽毛疏。樵翁接引寻红术，道士留连说紫书。",
            "不为壮心降未得，便堪从此玩清虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寄天台道友 ----------
    {
        "id": "lu-shi-heng-3",
        "title": "寄天台道友",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "相思遥指玉霄峰，怅望江山阻万重。会隔晓窗闻法鼓，",
            "几同寒榻听疏钟。别来知子长餐柏，吟处将谁对倚松。",
            "且住人间行圣教，莫思天路便登龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 花落 ----------
    {
        "id": "lu-shi-heng-4",
        "title": "花落",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "迎风啸未已，和雨落穀穀。千枝与万枝，不如一竿竹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 钟陵铁柱 ----------
    {
        "id": "lu-shi-heng-5",
        "title": "钟陵铁柱",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "千年埋没竟何为，变化宜将万物齐。",
            "安得风胡借方便，铸成神剑斩鲸鲵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 僧房听雨 ----------
    {
        "id": "lu-shi-heng-6",
        "title": "僧房听雨",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "古寺松轩雨声别，寒窗听久诗魔发。",
            "记得年前在赤城，石楼梦觉三更雪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 题牡丹 ----------
    {
        "id": "lu-shi-heng-7",
        "title": "题牡丹",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "万叶红绡剪尽春，丹青任写不如真。",
            "风光九十无多日，难惜尊前折赠人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 松 ----------
    {
        "id": "lu-shi-heng-8",
        "title": "松",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "云外千寻好性灵，伴杉陪柏事孤贞。招呼暑气终无分，",
            "应和凉风别有声。细雨洒时花旋落，道人食处叶重生。",
            "如逢郢匠垂搜采，为栋为梁力不轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 再游紫阳洞重题小松 ----------
    {
        "id": "lu-shi-heng-9",
        "title": "再游紫阳洞重题小松",
        "author": "卢士衡",
        "poet_id": "lu-shi-heng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "仙家种此充朝食，叶叶枝枝造化力。去年见时似鹤高，",
            "今年萧骚八九尺。不同矮桧终委地，定向晴空倚天碧。",
            "好期逸士统贞根，昂枝点破秋苔色。寻思凡眼重花开，",
            "宁知此木超尘埃。只是十年五年间，堪作大厦之宏材。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]