# -*- coding: utf-8 -*-
"""
熊孺登卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 30 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 至日荷李常侍过郊居 ----------
    {
        "id": "xiong-ru-deng-1",
        "title": "至日荷李常侍过郊居",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "贱子守柴荆，谁人记姓名。风云千骑降，草木一阳生。",
            "礼异江河动，欢殊里巷惊。称觞容侍坐，看竹许同行。",
            "遇觉沧溟浅，恩疑太岳轻。尽搜天地物，无谕此时情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 日暮天无云 ----------
    {
        "id": "xiong-ru-deng-2",
        "title": "日暮天无云",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "杳杳复苍然，无云日暮天。象分青气外，景尽赤霄前。",
            "渐吐星河色，遥生水木烟。从容难附丽，顾步欲澄鲜。",
            "但见收三素，何能测上玄。应非暂呈瑞，不许出山川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 新成小亭月夜 ----------
    {
        "id": "xiong-ru-deng-3",
        "title": "新成小亭月夜",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "已被月知处，斩新风到来。无人伴幽境，多取木兰栽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 和窦中丞岁酒喜见小男两岁 ----------
    {
        "id": "xiong-ru-deng-4",
        "title": "和窦中丞岁酒喜见小男两岁",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "更添十岁应为相，岁酒从今把未休。",
            "闻得一毛添五色，眼看相逐凤池头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 寒食 ----------
    {
        "id": "xiong-ru-deng-5",
        "title": "寒食",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "东风泼火雨新休，舁尽春泥扫雪沟。",
            "走马犊车当御路，汉阳公主谢鸡球。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送僧游山 ----------
    {
        "id": "xiong-ru-deng-6",
        "title": "送僧游山",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "云身自在山山去，何处灵山不是归。",
            "日暮寒林投古寺，雪花飞满水田衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 雪中答僧书 ----------
    {
        "id": "xiong-ru-deng-7",
        "title": "雪中答僧书",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "八行银字非常草，六出天花尽是梅。",
            "无所与陈童子别，雪中辛苦远山来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 题逍遥楼伤故韦大夫 ----------
    {
        "id": "xiong-ru-deng-8",
        "title": "题逍遥楼伤故韦大夫",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "利及生人无更为，落花流水旧城池。",
            "逍遥楼上雕龙字，便是羊公堕泪碑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 戏赠费冠卿 ----------
    {
        "id": "xiong-ru-deng-9",
        "title": "戏赠费冠卿",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "但恐红尘虚白首，宁论蹇逸分先后。",
            "莫占莺花笑寂寥，长安春色年年有。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 与左兴宗湓城别 ----------
    {
        "id": "xiong-ru-deng-10",
        "title": "与左兴宗湓城别",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "江逢九派人将别，猿到三声月为秋。",
            "不知相见更何日，此夜少年堪白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 八月十五夜卧疾 ----------
    {
        "id": "xiong-ru-deng-11",
        "title": "八月十五夜卧疾",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "一年只有今宵月，尽上江楼独病眠。",
            "寂寞竹窗闲不闭，夜深斜影到床前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 正月十五日 ----------
    {
        "id": "xiong-ru-deng-12",
        "title": "正月十五日",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "汉家遗事今宵见，楚郭明灯几处张。",
            "深夜行歌声绝后，紫姑神下月苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 曲池陪宴即事上窦中丞 ----------
    {
        "id": "xiong-ru-deng-13",
        "title": "曲池陪宴即事上窦中丞",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "水自山阿绕坐来，珊瑚台上木绵开。",
            "欲知举目无情罚，一片花流酒一杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 董监庙 ----------
    {
        "id": "xiong-ru-deng-14",
        "title": "董监庙",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "仁杰淫祠废欲无，枯枫老栎两三株。",
            "神乌惯得商人食，飞趁征帆过蠡湖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 赠侯山人 ----------
    {
        "id": "xiong-ru-deng-15",
        "title": "赠侯山人",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "一见清容惬素闻，有人传是紫阳君。",
            "来时玉女裁春服，剪破湘山几片云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送马判官赴安南 ----------
    {
        "id": "xiong-ru-deng-16",
        "title": "送马判官赴安南",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "故人交趾去从军，应笑狂生挥阵云。",
            "省得蔡州今日事，旧曾都护帐前闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 送准上人归石经院 ----------
    {
        "id": "xiong-ru-deng-17",
        "title": "送准上人归石经院",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "旃檀刻像今犹少，白石镌经古未曾。",
            "归去更寻翻译寺，前山应遇雁门僧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 寒食野望 ----------
    {
        "id": "xiong-ru-deng-18",
        "title": "寒食野望",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "拜扫无过骨肉亲，一年唯此两三辰。",
            "冢头莫种有花树，春色不关泉下人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 祗役遇风谢湘中春色 ----------
    {
        "id": "xiong-ru-deng-19",
        "title": "祗役遇风谢湘中春色",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "水生风熟布帆新，只见公程不见春。",
            "应被百花撩乱笑，比来天地一闲人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 湘江夜泛 ----------
    {
        "id": "xiong-ru-deng-20",
        "title": "湘江夜泛",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "江流如箭月如弓，行尽三湘数夜中。",
            "无那子规知向蜀，一声声似怨春风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 蜀江水（来自蕃界） ----------
    {
        "id": "xiong-ru-deng-21",
        "title": "蜀江水（来自蕃界）",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "日夜朝宗来万里，共怜江水引蕃心。",
            "若论巴峡愁人处，猿比滩声是好音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 寄安南马中丞 ----------
    {
        "id": "xiong-ru-deng-22",
        "title": "寄安南马中丞",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "龙韬能致虎符分，万里霜台压瘴云。",
            "蕃客不须愁海路，波神今伏马将军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 甘子堂陪宴上韦大夫 ----------
    {
        "id": "xiong-ru-deng-23",
        "title": "甘子堂陪宴上韦大夫",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "武陵楼上春长早，甘子堂前花落迟。",
            "楚乐怪来声竞起，新歌尽是大夫词。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 青溪村居二首 ----------
    {
        "id": "xiong-ru-deng-24",
        "title": "青溪村居二首",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "家占溪南千个竹，地临湖上一群山。",
            "渔船多在马长放，出处自由闲不闲。",
            "深树黄鹂晓一声，林西江上月犹明。",
            "野人早起无他事，贪绕沙泉看笋生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 奉和兴元郑相公早春送杨侍郎 ----------
    {
        "id": "xiong-ru-deng-25",
        "title": "奉和兴元郑相公早春送杨侍郎",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "征鞍欲上醉还留，南浦春生百草头。",
            "丞相新裁别离曲，声声飞出旧梁州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送舍弟孺复往庐山 ----------
    {
        "id": "xiong-ru-deng-26",
        "title": "送舍弟孺复往庐山",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "能骑竹马辨西东，未省烟花暂不同。",
            "第一早归春欲尽，庐山好看过湖风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 野别留少微上人 ----------
    {
        "id": "xiong-ru-deng-27",
        "title": "野别留少微上人",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "若为相见还分散，翻觉浮云亦不闲。",
            "何处留师暂且住，家贫唯有坐中山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 经古墓 ----------
    {
        "id": "xiong-ru-deng-28",
        "title": "经古墓",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "碑折松枯山火烧，夜台从闭不曾朝。",
            "那将逝者比流水，流水东流逢上潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 赠灵彻上人 ----------
    {
        "id": "xiong-ru-deng-29",
        "title": "赠灵彻上人",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "诗句能生世界春，僧家更有姓汤人。",
            "况闻暗忆前朝事，知是修行第几身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 春郊醉中赠章八元 ----------
    {
        "id": "xiong-ru-deng-30",
        "title": "春郊醉中赠章八元",
        "author": "熊孺登",
        "poet_id": "xiong-ru-deng",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "三月踏青能几日，百回添酒莫辞频。",
            "看君倒卧杨花里，始觉春光为醉人。",
            "第四百七十七卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]