# -*- coding: utf-8 -*-
"""
鱼玄机卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 49 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 赋得江边柳（一作临江树） ----------
    {
        "id": "yu-xuan-ji-1",
        "title": "赋得江边柳（一作临江树）",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "翠色连荒岸，烟姿入远楼。影铺秋水面，花落钓人头。",
            "根老藏鱼窟，枝低系客舟。萧萧风雨夜，惊梦复添愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠邻女（一作寄李亿员外） ----------
    {
        "id": "yu-xuan-ji-2",
        "title": "赠邻女（一作寄李亿员外）",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "羞日遮罗袖，愁春懒起妆。易求无价宝，难得有心郎。",
            "枕上潜垂泪，花间暗断肠。自能窥宋玉，何必恨王昌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寄国香 ----------
    {
        "id": "yu-xuan-ji-3",
        "title": "寄国香",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "旦夕醉吟身，相思又此春。雨中寄书使，窗下断肠人。",
            "山卷珠帘看，愁随芳草新。别来清宴上，几度落梁尘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 寄题炼师 ----------
    {
        "id": "yu-xuan-ji-4",
        "title": "寄题炼师",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "霞彩剪为衣，添香出绣帏。芙蓉花叶□，山水帔□稀。",
            "驻履闻莺语，开笼放鹤飞。高堂春睡觉，暮雨正霏霏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 寄刘尚书 ----------
    {
        "id": "yu-xuan-ji-5",
        "title": "寄刘尚书",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "八座镇雄军，歌谣满路新。汾川三月雨，晋水百花春。",
            "囹圄长空锁，干戈久覆尘。儒僧观子夜，羁客醉红茵。",
            "笔砚行随手，诗书坐绕身。小材多顾盼，得作食鱼人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 浣纱庙 ----------
    {
        "id": "yu-xuan-ji-6",
        "title": "浣纱庙",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "吴越相谋计策多，浣纱神女已相和。一双笑靥才回面，",
            "十万精兵尽倒戈。范蠡功成身隐遁，伍胥谏死国消磨。",
            "只今诸暨长江畔，空有青山号苎萝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 卖残牡丹 ----------
    {
        "id": "yu-xuan-ji-7",
        "title": "卖残牡丹",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "临风兴叹落花频，芳意潜消又一春。应为价高人不问，",
            "却缘香甚蝶难亲。红英只称生宫里，翠叶那堪染路尘。",
            "及至移根上林苑，王孙方恨买无因。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 酬李学士寄簟 ----------
    {
        "id": "yu-xuan-ji-8",
        "title": "酬李学士寄簟",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "珍簟新铺翡翠楼，泓澄玉水记方流。",
            "唯应云扇情相似，同向银床恨早秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 情书（一作书情寄李子安） ----------
    {
        "id": "yu-xuan-ji-9",
        "title": "情书（一作书情寄李子安）",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "饮冰食檗志无功，晋水壶关在梦中。秦镜欲分愁堕鹊，",
            "舜琴将弄怨飞鸿。井边桐叶鸣秋雨，窗下银灯暗晓风。",
            "书信茫茫何处问，持竿尽日碧江空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 闺怨 ----------
    {
        "id": "yu-xuan-ji-10",
        "title": "闺怨",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "蘼芜盈手泣斜晖，闻道邻家夫婿归。别日南鸿才北去，",
            "今朝北雁又南飞。春来秋去相思在，秋去春来信息稀。",
            "扃闭朱门人不到，砧声何事透罗帏。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 春情寄子安 ----------
    {
        "id": "yu-xuan-ji-11",
        "title": "春情寄子安",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "山路欹斜石磴危，不愁行苦苦相思。冰销远涧怜清韵，",
            "雪远寒峰想玉姿。莫听凡歌春病酒，休招闲客夜贪棋。",
            "如松匪石盟长在，比翼连襟会肯迟。虽恨独行冬尽日，",
            "终期相见月圆时。别君何物堪持赠，泪落晴光一首诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 打球作 ----------
    {
        "id": "yu-xuan-ji-12",
        "title": "打球作",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "坚圆净滑一星流，月杖争敲未拟休。无滞碍时从拨弄，",
            "有遮栏处任钩留。不辞宛转长随手，却恐相将不到头。",
            "毕竟入门应始了，愿君争取最前筹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 暮春有感寄友人 ----------
    {
        "id": "yu-xuan-ji-13",
        "title": "暮春有感寄友人",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "莺语惊残梦，轻妆改泪容。竹阴初月薄，江静晚烟浓。",
            "湿觜衔泥燕，香须采蕊蜂。独怜无限思，吟罢亚枝松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 冬夜寄温飞卿 ----------
    {
        "id": "yu-xuan-ji-14",
        "title": "冬夜寄温飞卿",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "苦思搜诗灯下吟，不眠长夜怕寒衾。满庭木叶愁风起，",
            "透幌纱窗惜月沈。疏散未闲终遂愿，盛衰空见本来心。",
            "幽栖莫定梧桐处，暮雀啾啾空绕林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 酬李郢夏日钓鱼回见示 ----------
    {
        "id": "yu-xuan-ji-15",
        "title": "酬李郢夏日钓鱼回见示",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "住处虽同巷，经年不一过。清词劝旧女，香桂折新柯。",
            "道性欺冰雪，禅心笑绮罗。迹登霄汉上，无路接烟波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 次韵西邻新居兼乞酒 ----------
    {
        "id": "yu-xuan-ji-16",
        "title": "次韵西邻新居兼乞酒",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "一首诗来百度吟，新情字字又声金。西看已有登垣意，",
            "远望能无化石心。河汉期赊空极目，潇湘梦断罢调琴。",
            "况逢寒节添乡思，叔夜佳醪莫独斟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 和友人次韵 ----------
    {
        "id": "yu-xuan-ji-17",
        "title": "和友人次韵",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "何事能销旅馆愁，红笺开处见银钩。蓬山雨洒千峰小，",
            "嶰谷风吹万叶秋。字字朝看轻碧玉，篇篇夜诵在衾裯。",
            "欲将香匣收藏却，且惜时吟在手头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 和新及第悼亡诗二首 ----------
    {
        "id": "yu-xuan-ji-18",
        "title": "和新及第悼亡诗二首",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "仙籍人间不久留，片时已过十经秋。鸳鸯帐下香犹暖，",
            "鹦鹉笼中语未休。朝露缀花如脸恨，晚风欹柳似眉愁。",
            "彩云一去无消息，潘岳多情欲白头。",
            "一枝月桂和烟秀，万树江桃带雨红。",
            "且醉尊前休怅望，古来悲乐与今同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 游崇真观南楼，睹新及第题名处 ----------
    {
        "id": "yu-xuan-ji-19",
        "title": "游崇真观南楼，睹新及第题名处",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "云峰满目放春晴，历历银钩指下生。",
            "自恨罗衣掩诗句，举头空羡榜中名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 愁思 ----------
    {
        "id": "yu-xuan-ji-20",
        "title": "愁思",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "落叶纷纷暮雨和，朱丝独抚自清歌。放情休恨无心友，",
            "养性空抛苦海波。长者车音门外有，道家书卷枕前多。",
            "布衣终作云霄客，绿水青山时一过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 秋怨 ----------
    {
        "id": "yu-xuan-ji-21",
        "title": "秋怨",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "自叹多情是足愁，况当风月满庭秋。",
            "洞房偏与更声近，夜夜灯前欲白头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 江行 ----------
    {
        "id": "yu-xuan-ji-22",
        "title": "江行",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "大江横抱武昌斜，鹦鹉洲前户万家。",
            "画舸春眠朝未足，梦为蝴蝶也寻花。",
            "烟花已入鸬鹚港，画舸犹沿鹦鹉洲。",
            "醉卧醒吟都不觉，今朝惊在汉江头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 闻李端公垂钓回寄赠 ----------
    {
        "id": "yu-xuan-ji-23",
        "title": "闻李端公垂钓回寄赠",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "无限荷香染暑衣，阮郎何处弄船归。",
            "自惭不及鸳鸯侣，犹得双双近钓矶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 题任处士创资福寺 ----------
    {
        "id": "yu-xuan-ji-24",
        "title": "题任处士创资福寺",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "幽人创奇境，游客驻行程。粉壁空留字，莲宫未有名。",
            "凿池泉自出，开径草重生。百尺金轮阁，当川豁眼明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 题隐雾亭 ----------
    {
        "id": "yu-xuan-ji-25",
        "title": "题隐雾亭",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "春花秋月入诗篇，白日清宵是散仙。",
            "空卷珠帘不曾下，长移一榻对山眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 重阳阻雨 ----------
    {
        "id": "yu-xuan-ji-26",
        "title": "重阳阻雨",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "满庭黄菊篱边拆，两朵芙蓉镜里开。",
            "落帽台前风雨阻，不知何处醉金杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 早秋 ----------
    {
        "id": "yu-xuan-ji-27",
        "title": "早秋",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "嫩菊含新彩，远山闲夕烟。凉风惊绿树，清韵入朱弦。",
            "思妇机中锦，征人塞外天。雁飞鱼在水，书信若为传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 感怀寄人 ----------
    {
        "id": "yu-xuan-ji-28",
        "title": "感怀寄人",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "恨寄朱弦上，含情意不任。早知云雨会，未起蕙兰心。",
            "灼灼桃兼李，无妨国士寻。苍苍松与桂，仍羡世人钦。",
            "月色苔阶净，歌声竹院深。门前红叶地，不扫待知音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 期友人阻雨不至 ----------
    {
        "id": "yu-xuan-ji-29",
        "title": "期友人阻雨不至",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "雁鱼空有信，鸡黍恨无期。闭户方笼月，褰帘已散丝。",
            "近泉鸣砌畔，远浪涨江湄。乡思悲秋客，愁吟五字诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 访赵炼师不遇 ----------
    {
        "id": "yu-xuan-ji-30",
        "title": "访赵炼师不遇",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "何处同仙侣，青衣独在家。暖炉留煮药，邻院为煎茶。",
            "画壁灯光暗，幡竿日影斜。殷勤重回首，墙外数枝花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 遣怀 ----------
    {
        "id": "yu-xuan-ji-31",
        "title": "遣怀",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "闲散身无事，风光独自游。断云江上月，解缆海中舟。",
            "琴弄萧梁寺，诗吟庾亮楼。丛篁堪作伴，片石好为俦。",
            "燕雀徒为贵，金银志不求。满杯春酒绿，对月夜窗幽。",
            "绕砌澄清沼，抽簪映细流。卧床书册遍，半醉起梳头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 寄飞卿 ----------
    {
        "id": "yu-xuan-ji-32",
        "title": "寄飞卿",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "阶砌乱蛩鸣，庭柯烟露清。月中邻乐响，楼上远山明。",
            "珍簟凉风著，瑶琴寄恨生。嵇君懒书札，底物慰秋情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 过鄂州 ----------
    {
        "id": "yu-xuan-ji-33",
        "title": "过鄂州",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "柳拂兰桡花满枝，石城城下暮帆迟。折牌峰上三闾墓，",
            "远火山头五马旗。白雪调高题旧寺，阳春歌在换新词。",
            "莫愁魂逐清江去，空使行人万首诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 夏日山居 ----------
    {
        "id": "yu-xuan-ji-34",
        "title": "夏日山居",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "移得仙居此地来，花丛自遍不曾栽。庭前亚树张衣桁，",
            "坐上新泉泛酒杯。轩槛暗传深竹径，绮罗长拥乱书堆。",
            "闲乘画舫吟明月，信任轻风吹却回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 暮春即事 ----------
    {
        "id": "yu-xuan-ji-35",
        "title": "暮春即事",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "深巷穷门少侣俦，阮郎唯有梦中留。香飘罗绮谁家席，",
            "风送歌声何处楼。街近鼓鼙喧晓睡，庭闲鹊语乱春愁。",
            "安能追逐人间事，万里身同不系舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 代人悼亡 ----------
    {
        "id": "yu-xuan-ji-36",
        "title": "代人悼亡",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "曾睹夭桃想玉姿，带风杨柳认蛾眉。珠归龙窟知谁见，",
            "镜在鸾台话向谁。从此梦悲烟雨夜，不堪吟苦寂寥时。",
            "西山日落东山月，恨想无因有了期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 和人 ----------
    {
        "id": "yu-xuan-ji-37",
        "title": "和人",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "茫茫九陌无知己，暮去朝来典绣衣。宝匣镜昏蝉鬓乱，",
            "博山炉暖麝烟微。多情公子春留句，少思文君昼掩扉。",
            "莫惜羊车频列载，柳丝梅绽正芳菲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 隔汉江寄子安 ----------
    {
        "id": "yu-xuan-ji-38",
        "title": "隔汉江寄子安",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "江南江北愁望，相思相忆空吟。鸳鸯暖卧沙浦，",
            "鸂鶒闲飞橘林。烟里歌声隐隐，渡头月色沈沈。",
            "含情咫尺千里，况听家家远砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 寓言 ----------
    {
        "id": "yu-xuan-ji-39",
        "title": "寓言",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "红桃处处春色，碧柳家家月明。楼上新妆待夜，",
            "闺中独坐含情。芙蓉月下鱼戏，螮蝀天边雀声。",
            "人世悲欢一梦，如何得作双成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 江陵愁望寄子安 ----------
    {
        "id": "yu-xuan-ji-40",
        "title": "江陵愁望寄子安",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "枫叶千枝复万枝，江桥掩映暮帆迟。",
            "忆君心似西江水，日夜东流无歇时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 寄子安 ----------
    {
        "id": "yu-xuan-ji-41",
        "title": "寄子安",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "醉别千卮不浣愁，离肠百结解无由。蕙兰销歇归春圃，",
            "杨柳东西绊客舟。聚散已悲云不定，恩情须学水长流。",
            "有花时节知难遇，未肯厌厌醉玉楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送别 ----------
    {
        "id": "yu-xuan-ji-42",
        "title": "送别",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "秦楼几夜惬心期，不料仙郎有别离。",
            "睡觉莫言云去处，残灯一盏野蛾飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 迎李近仁员外 ----------
    {
        "id": "yu-xuan-ji-43",
        "title": "迎李近仁员外",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "今日喜时闻喜鹊，昨宵灯下拜灯花。",
            "焚香出户迎潘岳，不羡牵牛织女家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送别 ----------
    {
        "id": "yu-xuan-ji-44",
        "title": "送别",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "水柔逐器知难定，云出无心肯再归。",
            "惆怅春风楚江暮，鸳鸯一只失群飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 左名场自泽州至京，使人传语 ----------
    {
        "id": "yu-xuan-ji-45",
        "title": "左名场自泽州至京，使人传语",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "闲居作赋几年愁，王屋山前是旧游。诗咏东西千嶂乱，",
            "马随南北一泉流。曾陪雨夜同欢席，别后花时独上楼。",
            "忽喜扣门传语至，为怜邻巷小房幽。相如琴罢朱弦断，",
            "双燕巢分白露秋。莫倦蓬门时一访，每春忙在曲江头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 和人次韵 ----------
    {
        "id": "yu-xuan-ji-46",
        "title": "和人次韵",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "喧喧朱紫杂人寰，独自清吟日色间。何事玉郎搜藻思，",
            "忽将琼韵扣柴关。白花发咏惭称谢，僻巷深居谬学颜。",
            "不用多情欲相见，松萝高处是前山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 光、威、裒姊妹三人少孤而始妍乃有是作…因次其韵 ----------
    {
        "id": "yu-xuan-ji-47",
        "title": "光、威、裒姊妹三人少孤而始妍乃有是作…因次其韵",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "昔闻南国容华少，今日东邻姊妹三。妆阁相看鹦鹉赋，",
            "碧窗应绣凤凰衫。红芳满院参差折，绿醑盈杯次第衔。",
            "恐向瑶池曾作女，谪来尘世未为男。文姬有貌终堪比，",
            "西子无言我更惭。一曲艳歌琴杳杳，四弦轻拨语喃喃。",
            "当台竞斗青丝发，对月争夸白玉簪。小有洞中松露滴，",
            "大罗天上柳烟含。但能为雨心长在，不怕吹箫事未谙。",
            "阿母几嗔花下语，潘郎曾向梦中参。暂持清句魂犹断，",
            "若睹红颜死亦甘。怅望佳人何处在，行云归北又归南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 折杨柳 ----------
    {
        "id": "yu-xuan-ji-48",
        "title": "折杨柳",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "朝朝送别泣花钿，折尽春风杨柳烟。",
            "愿得西山无树木，免教人作泪悬悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 句 ----------
    {
        "id": "yu-xuan-ji-49",
        "title": "句",
        "author": "鱼玄机",
        "poet_id": "yu-xuan-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "焚香登玉坛，端简礼金阙。",
            "明月照幽隙，清风开短襟。（《狱中作》）",
            "绮陌春望远，瑶徽春兴多。",
            "殷勤不得语，红泪一双流。",
            "云情自郁争同梦，仙貌长芳又胜花。（以上俱见《纪事》）",
            "第八百零五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]