# -*- coding: utf-8 -*-
"""
祖咏卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 37 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 古意二首 ----------
    {
        "id": "zu-yong-1",
        "title": "古意二首",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "夫差日淫放，举国求妃嫔。自谓得王宠，代间无美人。",
            "碧罗象天阁，坐辇乘芳春。宫女数千骑，常游江水滨。",
            "年深玉颜老，时薄花妆新。拭泪下金殿，娇多不顾身。",
            "生前妒歌舞，死后同灰尘。冢墓令人哀，哀于铜雀台。",
            "楚王竟何去，独自留巫山。偏使世人见，迢迢江汉间。",
            "驻舟春谿里，誓愿拜灵颜。梦寐睹神女，金沙鸣珮环。",
            "闲艳绝世姿，令人气力微。含笑默不语，化作朝云飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 渡淮河寄平一 ----------
    {
        "id": "zu-yong-2",
        "title": "渡淮河寄平一",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "天色混波涛，岸阴匝村墅。微微汉祖庙，隐隐江陵渚。",
            "云树森已重，时明郁相拒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 归汝坟山庄留别卢象 ----------
    {
        "id": "zu-yong-3",
        "title": "归汝坟山庄留别卢象",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "淹留岁将晏，久废南山期。旧业不见弃，还山从此辞。",
            "沤麻入南涧，刈麦向东菑。对酒鸡黍熟，闭门风雪时。",
            "非君一延首，谁慰遥相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 夕次圃田店 ----------
    {
        "id": "zu-yong-4",
        "title": "夕次圃田店",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "前路入郑郊，尚经百馀里。马烦时欲歇，客归程未已。",
            "落日桑柘阴，遥村烟火起。西还不遑宿，中夜渡泾水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 田家即事 ----------
    {
        "id": "zu-yong-5",
        "title": "田家即事",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "旧居东皋上，左右俯荒村。樵路前傍岭，田家遥对门。",
            "欢娱始披拂，惬意在郊原。馀霁荡川雾，新秋仍昼昏。",
            "攀条憩林麓，引水开泉源。稼穑岂云倦，桑麻今正繁。",
            "方求静者赏，偶与潜夫论。鸡黍何必具，吾心知道尊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 扈从御宿池 ----------
    {
        "id": "zu-yong-6",
        "title": "扈从御宿池",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "君王既巡狩，辇道入秦京。远树低枪垒，孤峰入幔城。",
            "寒疏清禁漏，夜警羽林兵。谁念迷方客，长怀魏阙情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 赠苗发员外（一作李端诗） ----------
    {
        "id": "zu-yong-7",
        "title": "赠苗发员外（一作李端诗）",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "宿雨朝来歇，空山天气清。盘云双鹤下，隔水一蝉鸣。",
            "古道黄花落，平芜赤烧生。茂陵虽有病，犹得伴君行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 答王维留宿 ----------
    {
        "id": "zu-yong-8",
        "title": "答王维留宿",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "四年不相见，相见复何为。握手言未毕，却令伤别离。",
            "升堂还驻马，酌醴便呼儿。语嘿自相对，安用傍人知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 长乐驿留别卢象裴总 ----------
    {
        "id": "zu-yong-9",
        "title": "长乐驿留别卢象裴总",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "朝来已握手，宿别更伤心。灞水行人渡，商山驿路深。",
            "故情君且足，谪宦我难任。直道皆如此，谁能泪满襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送刘高邮棁使入都 ----------
    {
        "id": "zu-yong-10",
        "title": "送刘高邮棁使入都",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "常闻积归思，昨夜又兼秋。乡路京华远，王程江水流。",
            "吴歌喧两岸，楚客醉孤舟。渐觉潮初上，凄然多暮愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 宴吴王宅 ----------
    {
        "id": "zu-yong-11",
        "title": "宴吴王宅",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "吴王承国宠，列第禁城东。连夜征词客，当春试舞童。",
            "砌分池水岸，窗度竹林风。更待西园月，金尊乐未终。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 观华岳 ----------
    {
        "id": "zu-yong-12",
        "title": "观华岳",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "西入秦关口，南瞻驿路连。彩云生阙下，松树到祠边。",
            "作镇当官道，雄都俯大川。莲峰径上处，仿佛有神仙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 泗上冯使君南楼作 ----------
    {
        "id": "zu-yong-13",
        "title": "泗上冯使君南楼作",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "井邑连淮泗，南楼向晚过。望滩沙鹭起，寻岸浴童歌。",
            "近海云偏出，兼秋雨更多。明晨拟回棹，乡思恨风波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 苏氏别业 ----------
    {
        "id": "zu-yong-14",
        "title": "苏氏别业",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "别业居幽处，到来生隐心。南山当户牖，沣水映园林。",
            "屋覆经冬雪，庭昏未夕阴。寥寥人境外，闲坐听春禽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 汝坟别业 ----------
    {
        "id": "zu-yong-15",
        "title": "汝坟别业",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "失路农为业，移家到汝坟。独愁常废卷，多病久离群。",
            "鸟雀垂窗柳，虹霓出涧云。山中无外事，樵唱有时闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 陆浑水亭 ----------
    {
        "id": "zu-yong-16",
        "title": "陆浑水亭",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "昼眺伊川曲，岩间霁色明。浅沙平有路，流水漫无声。",
            "浴鸟沿波聚，潜鱼触钓惊。更怜春岸绿，幽意满前楹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 过郑曲 ----------
    {
        "id": "zu-yong-17",
        "title": "过郑曲",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "路向荣川谷，晴来望尽通。细烟生水上，圆月在舟中。",
            "岸势迷行客，秋声乱草虫。旅怀劳自慰，淅淅有凉风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 宿陈留李少府揆厅 ----------
    {
        "id": "zu-yong-18",
        "title": "宿陈留李少府揆厅",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "相知有叔卿，讼简夜弥清。旅泊倦愁卧，堂空闻曙更。",
            "风帘摇烛影，秋雨带虫声。归思那堪说，悠悠限洛城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 题韩少府水亭 ----------
    {
        "id": "zu-yong-19",
        "title": "题韩少府水亭",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "梅福幽栖处，佳期不忘还。鸟吟当户竹，花绕傍池山。",
            "水气侵阶冷，松阴覆座闲。宁知武陵趣，宛在市朝间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 题远公经台 ----------
    {
        "id": "zu-yong-20",
        "title": "题远公经台",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "兰若无人到，真僧出复稀。苔侵行道席，云湿坐禅衣。",
            "涧鼠缘香案，山蝉噪竹扉。世间长不见，宁止暂忘归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 中峰居喜见苗发（一作李端诗） ----------
    {
        "id": "zu-yong-21",
        "title": "中峰居喜见苗发（一作李端诗）",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "自得中峰住，深林亦闭关。经秋无客到，入夜有僧还。",
            "暗涧泉声小，荒冈树影闲。高窗不可望，星月满空山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 江南旅情 ----------
    {
        "id": "zu-yong-22",
        "title": "江南旅情",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "楚山不可极，归路但萧条。海色晴看雨，江声夜听潮。",
            "剑留南斗近，书寄北风遥。为报空潭橘，无媒寄洛桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 泊扬子津 ----------
    {
        "id": "zu-yong-23",
        "title": "泊扬子津",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "才入维扬郡，乡关此路遥。林藏初过雨，风退欲归潮。",
            "江火明沙岸，云帆碍浦桥。客衣今日薄，寒气近来饶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 晚泊金陵水亭 ----------
    {
        "id": "zu-yong-24",
        "title": "晚泊金陵水亭",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "江亭当废国，秋景倍萧骚。夕照明残垒，寒潮涨古濠。",
            "就田看鹤大，隔水见僧高。无限前朝事，醒吟易觉劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 七夕 ----------
    {
        "id": "zu-yong-25",
        "title": "七夕",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "闺女求天女，更阑意未阑。玉庭开粉席，罗袖捧金盘。",
            "向月穿针易，临风整线难。不知谁得巧，明旦试相看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 望蓟门 ----------
    {
        "id": "zu-yong-26",
        "title": "望蓟门",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "燕台一望客心惊，箫鼓喧喧汉将营。万里寒光生积雪，",
            "三边曙色动危旌。沙场烽火连胡月，海畔云山拥蓟城。",
            "少小虽非投笔吏，论功还欲请长缨。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 家园夜坐寄郭微 ----------
    {
        "id": "zu-yong-27",
        "title": "家园夜坐寄郭微",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "前阶微雨歇，开户散窥林。月出夜方浅，水凉池更深。",
            "馀风生竹树，清露薄衣襟。遇物遂遥叹，怀人滋远心。",
            "依稀成梦想，影响绝徽音。谁念穷居者，明时嗟陆沉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 酬汴州李别驾赠 ----------
    {
        "id": "zu-yong-28",
        "title": "酬汴州李别驾赠",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "秋风多客思，行旅厌艰辛。自洛非才子，游梁得主人。",
            "文章参末议，荣贱岂同伦。叹逝逢三演，怀贤忆四真。",
            "情因恩旧好，契托死生亲。所愧能投赠，清言益润身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 清明宴司勋刘郎中别业 ----------
    {
        "id": "zu-yong-29",
        "title": "清明宴司勋刘郎中别业",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "田家复近臣，行乐不违亲。霁日园林好，清明烟火新。",
            "以文长会友，唯德自成邻。池照窗阴晚，杯香药味春。",
            "檐前花覆地，竹外鸟窥人。何必桃源里，深居作隐沦。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 汝坟秋同仙州王长史翰闻百舌鸟 ----------
    {
        "id": "zu-yong-30",
        "title": "汝坟秋同仙州王长史翰闻百舌鸟",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "秋天闻好鸟，惊起出帘帷。却念殊方月，能鸣巳后时。",
            "迁乔诚可早，出谷此何迟。顾影惭无对，怀群空所思。",
            "凄凉岁欲晚，萧索燕将辞。留听未终曲，弥令心独悲。",
            "高飞凭力致，巧啭任天姿。返覆知而静，间关断若遗。",
            "花繁上林路，霜落汝川湄。且长凌风翮，乘春自有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 送丘为下第 ----------
    {
        "id": "zu-yong-31",
        "title": "送丘为下第",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "沧江一身客，献赋空十年。明主岂能好，今人谁举贤。",
            "国门税征驾，旅食谋归旋。皦日媚春水，绿蘋香客船。",
            "无媒既不达，予亦思归田。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 赠苗发员外 ----------
    {
        "id": "zu-yong-32",
        "title": "赠苗发员外",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "朱户敞高扉，青槐碍落晖。八龙乘庆重，三虎递朝归。",
            "坐竹人声绝，横琴鸟语稀。花惭潘岳貌，年称老莱衣。",
            "叶暗朱樱熟，丝长粉蝶飞。应怜鲁儒贱，空与故山违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 寄王长史 ----------
    {
        "id": "zu-yong-33",
        "title": "寄王长史",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "汝颍俱宿好，往来托层峦。终日何寂寞，绕篱生蕙兰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 别怨 ----------
    {
        "id": "zu-yong-34",
        "title": "别怨",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "送别到中流，秋船倚渡头。相看尚不远，未可即回舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 终南望馀雪 ----------
    {
        "id": "zu-yong-35",
        "title": "终南望馀雪",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "终南阴岭秀，积雪浮云端。林表明霁色，城中增暮寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 句 ----------
    {
        "id": "zu-yong-36",
        "title": "句",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "不知叠嶂夜来雨，清晓石楠花乱流。",
            "第一百三十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 尚书省门吟 ----------
    {
        "id": "zu-yong-37",
        "title": "尚书省门吟",
        "author": "祖咏",
        "poet_id": "zu-yong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "落去他，两两三三戴帽子。",
            "日暮祖侯吟一声，长安竹柏皆枯死。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]