# -*- coding: utf-8 -*-
"""
朱放卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 27 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·铜雀妓 ----------
    {
        "id": "zhu-fang-1",
        "title": "相和歌辞·铜雀妓",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷95》",
        "verse": [
            "恨唱歌声咽，愁翻舞袖迟。西陵日欲暮，是妾断肠时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 剡溪行却寄新别者 ----------
    {
        "id": "zhu-fang-2",
        "title": "剡溪行却寄新别者",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "潺湲寒溪上，自此成离别。回首望归人，移舟逢暮雪。",
            "频行识草树，渐老伤年发。唯有白云心，为向东山月。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 九日陪刘中丞宴昌乐寺送梁廷评 ----------
    {
        "id": "zhu-fang-3",
        "title": "九日陪刘中丞宴昌乐寺送梁廷评",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "独坐三台妙，重阳百越间。水心观远俗，霜气入秋山。",
            "不弃遗簪旧，宁辞落帽还。仍闻西上客，咫尺谒天颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 经故贺宾客镜湖道士观 ----------
    {
        "id": "zhu-fang-4",
        "title": "经故贺宾客镜湖道士观",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "已得归乡里，逍遥一外臣。那随流水去，不待镜湖春。",
            "雪里登山屐，林间漉酒巾。空馀道士观，谁是学仙人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 送著公归越（一作皇甫曾诗） ----------
    {
        "id": "zhu-fang-5",
        "title": "送著公归越（一作皇甫曾诗）",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "谁能愁此别，到越会相逢。长忆云门寺，门前千万峰。",
            "石床埋积雪，山路倒枯松。莫学白道士，无人知去踪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 秣陵送客入京 ----------
    {
        "id": "zhu-fang-6",
        "title": "秣陵送客入京",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "秣陵春已至，君去学归鸿。绿水琴声切，青袍草色同。",
            "鸟喧金谷树，花满洛阳宫。日日相思处，江边杨柳风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 灵门寺赠灵一上人 ----------
    {
        "id": "zhu-fang-7",
        "title": "灵门寺赠灵一上人",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "所思劳旦夕，惆怅去湘东。禅客知何在，春山几处同。",
            "独行残雪里，相见暮云中。请住东林寺，弥年事远公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 江上送别 ----------
    {
        "id": "zhu-fang-8",
        "title": "江上送别",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "浦边新见柳摇时，北客相逢只自悲。惆怅空知思后会，",
            "艰难不敢料前期。行看汉月愁征战，共折江花怨别离。",
            "向夕孤城分首处，寂寥横笛为君吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 归桐庐旧居寄严长史（一作章八元诗） ----------
    {
        "id": "zhu-fang-9",
        "title": "归桐庐旧居寄严长史（一作章八元诗）",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "昨辞天子棹归舟，家在桐庐忆旧丘。三月暖时花竞发，",
            "两溪分处水争流。近闻江老传乡语，遥见家山减旅愁。",
            "或在醉中逢夜雪，怀贤应向剡川游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 竹 ----------
    {
        "id": "zhu-fang-10",
        "title": "竹",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "青林何森然，沈沈独曙前。出墙同淅沥，开户满婵娟。",
            "箨卷初呈粉，苔侵乱上钱。疏中思水过，深处若山连。",
            "叠夜常栖露，清朝乍有蝉。砌阴迎缓策，檐翠对欹眠。",
            "迸笋双分箭，繁梢一向偏。月过惊散雪，风动极闻泉。",
            "幽谷添诗谱，高人欲制篇。萧萧意何恨，不独往湘川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 铜雀妓 ----------
    {
        "id": "zhu-fang-11",
        "title": "铜雀妓",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "恨唱歌声咽，愁翻舞袖迟。西陵日欲暮，是妾断肠时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 毗陵留别 ----------
    {
        "id": "zhu-fang-12",
        "title": "毗陵留别",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "别离非一处，此处最伤情。白发将春草，相随日日生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 题竹林寺 ----------
    {
        "id": "zhu-fang-13",
        "title": "题竹林寺",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "岁月人间促，烟霞此地多。殷勤竹林寺，能得几回过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 答陆澧 ----------
    {
        "id": "zhu-fang-14",
        "title": "答陆澧",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "松叶堪为酒，春来酿几多。不辞山路远，踏雪也相过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 杨子津送人 ----------
    {
        "id": "zhu-fang-15",
        "title": "杨子津送人",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "今朝杨子津，忽见五溪人。老病无馀事，丹砂乞五斤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 山中谒皇甫曾 ----------
    {
        "id": "zhu-fang-16",
        "title": "山中谒皇甫曾",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "寻源路已尽，笑入白云间。不解乘轺客，那知有此山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 剡山夜月（一题剡溪舟行） ----------
    {
        "id": "zhu-fang-17",
        "title": "剡山夜月（一题剡溪舟行）",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "月在沃洲山上，人归剡县溪边。",
            "漠漠黄花覆水，时时白鹭惊船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 九日与杨凝、崔淑期登江上山会有故不得往因赠之 ----------
    {
        "id": "zhu-fang-18",
        "title": "九日与杨凝、崔淑期登江上山会有故不得往因赠之",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "欲从携手登高去，一到门前意已无。",
            "那得更将头上发，学他年少插茱萸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 山中听子规（一作顾况诗） ----------
    {
        "id": "zhu-fang-19",
        "title": "山中听子规（一作顾况诗）",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "幽人自爱山中宿，又近葛洪丹井西。",
            "窗中有个长松树，半夜子规来上啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 乱后经淮阴岸 ----------
    {
        "id": "zhu-fang-20",
        "title": "乱后经淮阴岸",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "荒村古岸谁家在，野水浮云处处愁。",
            "唯有河边衰柳树，蝉声相送到扬州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送张山人 ----------
    {
        "id": "zhu-fang-21",
        "title": "送张山人",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "知君住处足风烟，古寺荒村在眼前。",
            "便欲移家逐君去，唯愁未有买山钱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 别李季兰 ----------
    {
        "id": "zhu-fang-22",
        "title": "别李季兰",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "古岸新花开一枝，岸傍花下有分离。",
            "莫将罗袖拂花落，便是行人肠断时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 游石涧寺 ----------
    {
        "id": "zhu-fang-23",
        "title": "游石涧寺",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "闻道幽深石涧寺，不逢流水亦难知。",
            "莫道山僧无伴侣，猕猴长在古松枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 新安所居答相访人所居萧使君为制 ----------
    {
        "id": "zhu-fang-24",
        "title": "新安所居答相访人所居萧使君为制",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "谢公见我多愁疾，为我开门对碧山。",
            "君若欲来看猿鸟，不须争把桂枝攀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 送魏校书 ----------
    {
        "id": "zhu-fang-25",
        "title": "送魏校书",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "长恨江南足别离，几回相送复相随。",
            "杨花撩乱扑流水，愁杀人行知不知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送温台 ----------
    {
        "id": "zhu-fang-26",
        "title": "送温台",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "眇眇天涯君去时，浮云流水自相随。",
            "人生一世长如客，何必今朝是别离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 句 ----------
    {
        "id": "zhu-fang-27",
        "title": "句",
        "author": "朱放",
        "poet_id": "zhu-fang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "爱彼云外人，求取涧底泉。",
            "风吹芭蕉拆，鸟啄梧桐落。（并《诗式》）。",
            "第三百一十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]