# -*- coding: utf-8 -*-
"""
孟迟卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 18 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 发蕙风馆遇阴不见九华山有作 ----------
    {
        "id": "meng-chi-1",
        "title": "发蕙风馆遇阴不见九华山有作",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "我来淮阴城，千江万山无不经。山青水碧千万丈，",
            "奇峰急派何纵横！又闻九华山，山顶连青冥。太白有逸韵，",
            "使我西南行。一步一攀策，前行正鸡鸣。阴云冉冉忽飞起，",
            "千里万里危峥嵘。譬如天之有日蚀，使我昏沈犹不明。",
            "人家敲镜救不得，光阴却属贪狼星。恨亦不能通，",
            "言亦不足听。长鞭挥马出门去，是以九华为不平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 寄浙右旧幕僚 ----------
    {
        "id": "meng-chi-2",
        "title": "寄浙右旧幕僚",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "由来恶舌驷难追，自古无媒谤所归。勾践岂能容范蠡，",
            "李斯何暇救韩非。巨拳岂为鸡挥肋，强弩那因鼠发机。",
            "惭愧故人同鲍叔，此心江柳尚依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 壮士吟 ----------
    {
        "id": "meng-chi-3",
        "title": "壮士吟",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "壮士何曾悲，悲即无回期。如何易水上，未歌泪先垂。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 徐波渡 ----------
    {
        "id": "meng-chi-4",
        "title": "徐波渡",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "晓月千重树，春烟十里溪。过来还过去，此路不知迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题嘉祥驿 ----------
    {
        "id": "meng-chi-5",
        "title": "题嘉祥驿",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "树顶烟微绿，山根菊暗香。何人独鞭马，落日上嘉祥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 怀郑洎 ----------
    {
        "id": "meng-chi-6",
        "title": "怀郑洎",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "风兰舞幽香，雨叶堕寒滴。美人来不来，前山看向夕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 长信宫（一作赵嘏诗） ----------
    {
        "id": "meng-chi-7",
        "title": "长信宫（一作赵嘏诗）",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "君恩已尽欲何归，犹有残香在舞衣。",
            "自恨身轻不如燕，春来还绕御帘飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 闺情 ----------
    {
        "id": "meng-chi-8",
        "title": "闺情",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "山上有山归不得，湘江暮雨鹧鸪飞。",
            "蘼芜亦是王孙草，莫送春香入客衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 莲塘 ----------
    {
        "id": "meng-chi-9",
        "title": "莲塘",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "脉脉低回殷袖遮，脸横秋水髻盘鸦。",
            "莲茎有刺不成折，尽日岸傍空看花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 还淮却寄睢阳 ----------
    {
        "id": "meng-chi-10",
        "title": "还淮却寄睢阳",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "梁王池苑已苍然，满树斜阳极浦烟。",
            "尽日回头看不见，两行愁泪上南船。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 乌江 ----------
    {
        "id": "meng-chi-11",
        "title": "乌江",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "中分岂是无遗策，百战空劳不逝骓。",
            "大业固非人事及，乌江亭长又何知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 新安故关 ----------
    {
        "id": "meng-chi-12",
        "title": "新安故关",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "汉帝英雄重武材，崇山险处凿门开。",
            "如今更有将军否，移取潼关向北来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 广陵城（一作赵嘏诗） ----------
    {
        "id": "meng-chi-13",
        "title": "广陵城（一作赵嘏诗）",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "红绕高台绿绕城，城边春草傍墙生。",
            "隋家不向此中尽，汴水应无东去声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 过骊山（一作赵嘏诗） ----------
    {
        "id": "meng-chi-14",
        "title": "过骊山（一作赵嘏诗）",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "冷日微烟渭水愁，华清宫树不胜秋。",
            "霓裳一曲千门锁，白尽梨园弟子头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 吴故宫 ----------
    {
        "id": "meng-chi-15",
        "title": "吴故宫",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "越女歌长君且听，芙蓉香满水边城。",
            "岂知一日终非主，犹自如今有怨声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 兰昌宫 ----------
    {
        "id": "meng-chi-16",
        "title": "兰昌宫",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "宫门两片掩埃尘，墙上无花草不春。",
            "谁见当时禁中事，阿娇解佩与何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 宫人斜 ----------
    {
        "id": "meng-chi-17",
        "title": "宫人斜",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "云惨烟愁苑路斜，路傍丘冢尽宫娃。",
            "茂陵不是同归处，空寄香魂著野花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 句 ----------
    {
        "id": "meng-chi-18",
        "title": "句",
        "author": "孟迟",
        "poet_id": "meng-chi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "天地有时饶一掷。江山无主任平分。（过垓下，《纪事》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]