# -*- coding: utf-8 -*-
"""
郭震卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 18 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 古剑篇（一作宝剑篇） ----------
    {
        "id": "guo-zhen-1",
        "title": "古剑篇（一作宝剑篇）",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "君不见昆吾铁冶飞炎烟，红光紫气俱赫然。",
            "良工锻炼凡几年，铸得宝剑名龙泉。龙泉颜色如霜雪，",
            "良工咨嗟叹奇绝。琉璃玉匣吐莲花，错镂金环映明月。",
            "正逢天下无风尘，幸得周防君子身。精光黯黯青蛇色，",
            "文章片片绿龟鳞。非直结交游侠子，亦曾亲近英雄人。",
            "何言中路遭弃捐，零落漂沦古狱边。虽复尘埋无所用，",
            "犹能夜夜气冲天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 塞上 ----------
    {
        "id": "guo-zhen-2",
        "title": "塞上",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "塞外虏尘飞，频年出武威。死生随玉剑，辛苦向金微。",
            "久戍人将老，长征马不肥。仍闻酒泉郡，已合数重围。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 寄刘校书 ----------
    {
        "id": "guo-zhen-3",
        "title": "寄刘校书",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "俗吏三年何足论，每将荣辱在朝昏。才微易向风尘老，",
            "身贱难酬知己恩。御苑残莺啼落日，黄山细雨湿归轩。",
            "回首汉家丞相府，昨来谁得扫重门。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 同徐员外除太子舍人寓直之作 ----------
    {
        "id": "guo-zhen-4",
        "title": "同徐员外除太子舍人寓直之作",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "太子擅元良，宫臣命伟长。除荣辞会府，直宿总书坊。",
            "露湿幽岩桂，风吹便坐桑。阁连云一色，池带月重光。",
            "叶死兰无气，荷枯水不香。遥闻秋兴作，言是晋中郎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 春江曲 ----------
    {
        "id": "guo-zhen-5",
        "title": "春江曲",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "江水春沉沉，上有双竹林。竹叶坏水色，郎亦坏人心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 王昭君三首 ----------
    {
        "id": "guo-zhen-6",
        "title": "王昭君三首",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "自嫁单于国，长衔汉掖悲。容颜日憔悴，有甚画图时。",
            "厌践冰霜域，嗟为边塞人。思从漠南猎，一见汉家尘。",
            "闻有南河信，传言杀画师。始知君念重，更肯惜蛾眉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 子夜四时歌六首·春歌 ----------
    {
        "id": "guo-zhen-7",
        "title": "子夜四时歌六首·春歌",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "陌头杨柳枝，已被春风吹。妾心正断绝，君怀那得知。",
            "青楼含日光，绿池起风色。赠子同心花，殷勤此何极。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 子夜四时歌六首·秋歌 ----------
    {
        "id": "guo-zhen-8",
        "title": "子夜四时歌六首·秋歌",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "邀欢空伫立，望美频回顾。何时复采菱，江中密相遇。",
            "辟恶茱萸囊，延年菊花酒。与子结绸缪，丹心此何有。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 子夜四时歌六首·冬歌 ----------
    {
        "id": "guo-zhen-9",
        "title": "子夜四时歌六首·冬歌",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "北极严气升，南至温风谢。调丝竞短歌，拂枕怜长夜。",
            "帷横双翡翠，被卷两鸳鸯。婉态不自得，宛转君王床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 二月乐游诗 ----------
    {
        "id": "guo-zhen-10",
        "title": "二月乐游诗",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "二月芳游始，开轩望晓池。绿兰日吐叶，红蕊向盈枝。",
            "柳色行将改，君心幸莫移。阳春遽多意，唯愿两人知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 十月乐游诗 ----------
    {
        "id": "guo-zhen-11",
        "title": "十月乐游诗",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "十月严阴盛，霜气下玉台。罗衣羞自解，绮帐待君开。",
            "银箭更筹缓，金炉香气来。愁仍夜未几，已使炭成灰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 萤 ----------
    {
        "id": "guo-zhen-12",
        "title": "萤",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "秋风凛凛月依依，飞过高梧影里时。",
            "暗处若教同众类，世间争得有人知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 蛩 ----------
    {
        "id": "guo-zhen-13",
        "title": "蛩",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "愁杀离家未达人，一声声到枕前闻。",
            "苦吟莫向朱门里，满耳笙歌不听君。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 云 ----------
    {
        "id": "guo-zhen-14",
        "title": "云",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "聚散虚空去复还，野人闲处倚筇看。",
            "不知身是无根物，蔽月遮星作万端。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 野井 ----------
    {
        "id": "guo-zhen-15",
        "title": "野井",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "纵无汲引味清澄，冷浸寒空月一轮。",
            "凿处若教当要路，为君常济往来人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 米囊花 ----------
    {
        "id": "guo-zhen-16",
        "title": "米囊花",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "开花空道胜于草，结实何曾济得民。",
            "却笑野田禾与黍，不闻弦管过青春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 惜花 ----------
    {
        "id": "guo-zhen-17",
        "title": "惜花",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "艳拂衣襟蕊拂杯，绕枝闲共蝶徘徊。",
            "春风满目还惆怅，半欲离披半未开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 莲花 ----------
    {
        "id": "guo-zhen-18",
        "title": "莲花",
        "author": "郭震",
        "poet_id": "guo-zhen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "脸腻香薰似有情，世间何物比轻盈。",
            "湘妃雨后来池看，碧玉盘中弄水晶。",
            "第六十七卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]