# -*- coding: utf-8 -*-
"""
韦元旦卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 10 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 奉和九日幸临渭亭登高应制得月字 ----------
    {
        "id": "wei-yuan-dan-1",
        "title": "奉和九日幸临渭亭登高应制得月字",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "云物开千里，天行乘九月。丝言丹凤池，旆转苍龙阙。",
            "灞水欢娱地，秦京游侠窟。欣承解愠词，圣酒黄花发。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉和送金城公主适西蕃应制 ----------
    {
        "id": "wei-yuan-dan-2",
        "title": "奉和送金城公主适西蕃应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "柔远安夷俗，和亲重汉年。军容旌节送，国命锦车传。",
            "琴曲悲千里，箫声恋九天。唯应西海月，来就掌珠圆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 饯唐州高使君赴任 ----------
    {
        "id": "wei-yuan-dan-3",
        "title": "饯唐州高使君赴任",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "桐柏膺新命，芝兰惜旧游。鸣皋夜鹤在，迁木早莺求。",
            "传拥淮源路，尊空灞水流。落花纷送远，春色引离忧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 早朝 ----------
    {
        "id": "wei-yuan-dan-4",
        "title": "早朝",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "震维芳月季，宸极众星尊。珮玉朝三陛，鸣珂度九门。",
            "挈壶分早漏，伏槛耀初暾。北倚苍龙阙，西临紫凤垣。",
            "词庭草欲奏，温室树无言。鳞翰空为忝，长怀圣主恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 奉和立春游苑迎春应制 ----------
    {
        "id": "wei-yuan-dan-5",
        "title": "奉和立春游苑迎春应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "灞涘长安恒近日，殷正腊月早迎新。池鱼戏叶仍含冻，",
            "宫女裁花已作春。向苑云疑承翠幄，入林风若起青蘋。",
            "年年斗柄东无限，愿挹琼觞寿北辰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 奉和圣制春日幸望春宫应制 ----------
    {
        "id": "wei-yuan-dan-6",
        "title": "奉和圣制春日幸望春宫应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "九重楼阁半山霞，四望韶阳春未赊。侍跸妍歌临灞涘，",
            "留觞艳舞出京华。危竿竞捧中街日，戏马争衔上苑花。",
            "景色欢娱长若此，承恩不醉不还家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 奉和人日宴大明宫恩赐彩缕人胜应制 ----------
    {
        "id": "wei-yuan-dan-7",
        "title": "奉和人日宴大明宫恩赐彩缕人胜应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "鸾凤旌旗拂晓陈，鱼龙角牴大明辰。青韶既肇人为日，",
            "绮胜初成日作人。圣藻凌云裁柏赋，仙歌促宴摘梅春。",
            "垂旒一庆宜年酒，朝野俱欢荐寿新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 奉和幸安乐公主山庄应制 ----------
    {
        "id": "wei-yuan-dan-8",
        "title": "奉和幸安乐公主山庄应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "银河南渚帝城隅，帝辇平明出九衢。刻凤蟠螭凌桂邸，",
            "穿池叠石写蓬壶。琼箫暂下钧天乐，绮缀长悬明月珠。",
            "仙榜承恩争既醉，方知朝野更欢娱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 兴庆池侍宴应制 ----------
    {
        "id": "wei-yuan-dan-9",
        "title": "兴庆池侍宴应制",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "沧池漭沆帝城边，殊胜昆明凿汉年。夹岸旌旗疏辇道，",
            "中流箫鼓振楼船。云峰四起迎宸幄，水树千重入御筵。",
            "宴乐已深鱼藻咏，承恩更欲奏甘泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 夜宴安乐公主宅 ----------
    {
        "id": "wei-yuan-dan-10",
        "title": "夜宴安乐公主宅",
        "author": "韦元旦",
        "poet_id": "wei-yuan-dan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "主第新成银作榜，宾筵广宴玉为楼。",
            "壶觞既卜仙人夜，歌舞宜停织女秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]