# -*- coding: utf-8 -*-
"""
熊皎卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 11 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 冬日原居酬光上人见访 ----------
    {
        "id": "xiong-jiao-1",
        "title": "冬日原居酬光上人见访",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "吾道丧已久，吾师何此来。门无尘事闭，卷有国风开。",
            "野迥霜先白，庭荒叶自堆。寒暄吟罢后，犹喜话天台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 早梅 ----------
    {
        "id": "xiong-jiao-2",
        "title": "早梅",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "江南近腊时，已亚雪中枝。一夜欲开尽，百花犹未知。",
            "人情皆共惜，天意欲教迟。莫讶无浓艳，芳筵正好吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 怀三茅道友 ----------
    {
        "id": "xiong-jiao-3",
        "title": "怀三茅道友",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "尘事何年解客嘲，十年容易到三茅。长思碧洞云窗下，",
            "曾借黄庭雪夜抄。丹桂有心凭至论，五峰无信问深交。",
            "杏坛仙侣应相笑，只为浮名未肯抛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠胥尊师 ----------
    {
        "id": "xiong-jiao-4",
        "title": "赠胥尊师",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "绿发童颜羽服轻，天台王屋几经行。云程去速因风起，",
            "酒债还迟待药成。房闭十洲烟浪阔，箓开三洞鬼神惊。",
            "他年华表重归日，却恐桑田已变更。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 句 ----------
    {
        "id": "xiong-jiao-5",
        "title": "句",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "山前犹见月，陌上未逢人。（早行，以下见《雅言杂载》）",
            "果熟秋先落，禽寒夜未栖。（《山居》）",
            "深逢野草皆为药，静见樵人恐是仙。",
            "厌听啼鸟梦醒后，慵扫落花春尽时。",
            "废土有人耕不畏，古厅无讼醉何妨。（见《事文类聚》）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 湘江晓望 ----------
    {
        "id": "xiong-jiao-6",
        "title": "湘江晓望",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "笙歌欢罢散离筵，水色朦胧蘸宿烟。山响疏钟何处寺，",
            "火光收钓下滩船。微云过岛侵微月，古岸平江浸远天。",
            "归梦已阑风色动，孤帆仍要住无缘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 早行 ----------
    {
        "id": "xiong-jiao-7",
        "title": "早行",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "结束何妨早，将行四顾频。山前犹见月，陌上未逢人。",
            "远树动宿鸟，危桥怯病身。渐明恒自慰，应免复迷津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 游嵩山 ----------
    {
        "id": "xiong-jiao-8",
        "title": "游嵩山",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "独背焦桐访洞天，暂攀灵迹弃尘缘。深逢野草皆疑药，",
            "静见樵人恐是仙。翠木入云空自老，古碑横水莫知年。",
            "可怜幽景堪长往，一任人间岁月迁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 九华望庐山 ----------
    {
        "id": "xiong-jiao-9",
        "title": "九华望庐山",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "九江山势尽峥嵘，惟有匡庐最得名。万叠影遮残雪在，",
            "数峰岚带夕阳明。冷侵醉榻铺秋色，高亚吟龙送水声。",
            "只待丹霄酬志了，白云深处是归程。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 道傍松 ----------
    {
        "id": "xiong-jiao-10",
        "title": "道傍松",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "偃盖当衢莫记年，独含苍翠鹤应怜。垂阴独向笙歌地，",
            "有韵自成风雨天。尘□路岐分夜月，烧侵根脚起残烟。",
            "论功只合行人赏，销得烦蒸古道边。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 月中桂 ----------
    {
        "id": "xiong-jiao-11",
        "title": "月中桂",
        "author": "熊皎",
        "poet_id": "xiong-jiao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "断破重轮种者谁，银蟾何事便相随。莫言望夜无攀处，",
            "却是吟人有得时。孤影不凋清露滴，异香常在好风吹。",
            "几回目断云霄外，未必姮娥惜一枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]