# -*- coding: utf-8 -*-
"""
灵一卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 43 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 酬皇甫冉西陵见寄（一作西陵渡） ----------
    {
        "id": "ling-yi-1",
        "title": "酬皇甫冉西陵见寄（一作西陵渡）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "西陵潮信满，岛屿没中流。越客依风水，相思南渡头。",
            "寒光生极浦，落日映沧洲。何事扬帆去，空惊海上鸥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 溪行即事 ----------
    {
        "id": "ling-yi-2",
        "title": "溪行即事",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "近夜山更碧，入林溪转清。不知伏牛事，潭洞何从横。",
            "野岸烟初合，平湖月未生。孤舟屡失道，但听秋泉声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 栖霞山夜坐 ----------
    {
        "id": "ling-yi-3",
        "title": "栖霞山夜坐",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "山头戒坛路，幽映雪岩侧。四面青石床，一峰苔藓色。",
            "松风静复起，月影开还黑。何独乘夜来，殊非昼所得。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 宿天柱观（一作宿灵洞观） ----------
    {
        "id": "ling-yi-4",
        "title": "宿天柱观（一作宿灵洞观）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "石室初投宿，仙翁喜暂容。花源隔水见，洞府过山逢。",
            "泉涌阶前地，云生户外峰。中宵自入定，非是欲降龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 酬皇甫冉将赴无锡，于云门寺赠别 ----------
    {
        "id": "ling-yi-5",
        "title": "酬皇甫冉将赴无锡，于云门寺赠别",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "湖南通古寺，来往意无涯。欲识云门路，千峰到若耶。",
            "春山子敬宅，古木谢敷家。自可长偕隐，那言相去赊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 宜丰新泉 ----------
    {
        "id": "ling-yi-6",
        "title": "宜丰新泉",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "泉源新涌出，洞澈映纤云。稍落芙蓉沼，初淹苔藓文。",
            "素将空意合，净与众流分。每到清宵月，泠泠梦里闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 静林精舍 ----------
    {
        "id": "ling-yi-7",
        "title": "静林精舍",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "静林溪路远，萧帝有遗踪。水击罗浮磬，山鸣于阗钟。",
            "灯传三世火，树老万株松。无数烟霞色，空闻昔卧龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 江行寄张舍人 ----------
    {
        "id": "ling-yi-8",
        "title": "江行寄张舍人",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "客程终日风尘苦，蓬转还家未有期。林色晓分残雪后，",
            "角声寒奏落帆时。月高星使东看远，云破霜鸿北度迟。",
            "流荡此心难共说，千峰澄霁隔琼枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送王颖悟归左绵 ----------
    {
        "id": "ling-yi-9",
        "title": "送王颖悟归左绵",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "客意天南兴已阑，不堪言别向仙官。梦摇玉珮随旄节，",
            "心到金华忆杏坛。荒郊极望归云尽，瘦马空嘶落日残。",
            "想得故山青霭里，泉声入夜独潺潺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 安公 ----------
    {
        "id": "ling-yi-10",
        "title": "安公",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "弥天称圣哲，象法初繄赖。弘道识行藏，匡时知进退。",
            "秦王轻与举，习生重酬对。学文古篆中，义显心经内。",
            "法服应华夏，金言流海岱。西方浮云间，更陪龙华会。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 林公 ----------
    {
        "id": "ling-yi-11",
        "title": "林公",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "支公信高逸，久向山林住。时将孙许游，岂以形骸遇。",
            "幸辞天子诏，复览名臣疏。西晋尚虚无，南朝久沦误。",
            "因谈老庄意，乃尽逍遥趣。谁为竹林贤，风流相比附。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 远公 ----------
    {
        "id": "ling-yi-12",
        "title": "远公",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "远公逢道安，一朝弃儒服。真机久消歇，世教空拘束。",
            "誓入罗浮中，遂栖庐山曲。禅经初纂定，佛语新名目。",
            "钵帽绝朝宗，簪裾翻拜伏。东林多隐士，为我辞荣禄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 雨后欲寻天目山，问元、骆二公溪路 ----------
    {
        "id": "ling-yi-13",
        "title": "雨后欲寻天目山，问元、骆二公溪路",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "昨夜云生天井东，春山一雨一回风。",
            "林花并逐溪流下，欲上龙池通不通。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 题僧院 ----------
    {
        "id": "ling-yi-14",
        "title": "题僧院",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "虎溪闲月引相过，带雪松枝挂薜萝。",
            "无限青山行欲尽，白云深处老僧多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 宿静林寺 ----------
    {
        "id": "ling-yi-15",
        "title": "宿静林寺",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "山寺门前多古松，溪行欲到已闻钟。",
            "中宵引领寻高顶，月照云峰凡几重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 再还宜丰寺 ----------
    {
        "id": "ling-yi-16",
        "title": "再还宜丰寺",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "再寻招隐地，重会息心期。樵客问归日，山僧记别时。",
            "野云阴远甸，秋雨涨前陂。勿谓探形胜，吾今不好奇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 春日山斋 ----------
    {
        "id": "ling-yi-17",
        "title": "春日山斋",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "野径东风起，山扉度日开。晴光拆红萼，流水长青苔。",
            "逋客殊未去，芳时已再来。非关恋春草，自是欲裴回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 留别忠州故人（一作惟审诗） ----------
    {
        "id": "ling-yi-18",
        "title": "留别忠州故人（一作惟审诗）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "一身无定处，万里独销魂。芳草迷归路，春流滴泪痕。",
            "几时休旅食，何夜宿江村。欲识相思苦，空山啼暮猿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 送别 ----------
    {
        "id": "ling-yi-19",
        "title": "送别",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "凭高莫送远，看欲断归心。别恨啼猿苦，相思流水深。",
            "翠云南涧影，丹桂晚山阴。若未来双鹄，辽城何更寻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送冽寺主之京迎禅和尚 ----------
    {
        "id": "ling-yi-20",
        "title": "送冽寺主之京迎禅和尚",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "禅门居此地，瞻望在虚空。水国月未上，苍生如梦中。",
            "上人知机士，瓶锡慰樊笼。彼土诸梵众，嗟君扬道风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 送王法师之西川 ----------
    {
        "id": "ling-yi-21",
        "title": "送王法师之西川",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "旅游无近远，要自别魂销。官柳乡愁乱，春山客路遥。",
            "伴行芳草远，缘兴野花飘。计日功成后，还将辅圣朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送范律师往果州 ----------
    {
        "id": "ling-yi-22",
        "title": "送范律师往果州",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "终南千古后，独尔继卿名。离障非今日，修因是几生。",
            "乱峰寒影暮，深涧野流清。远客归心苦，难为此别情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 送明素上人归楚觐省 ----------
    {
        "id": "ling-yi-23",
        "title": "送明素上人归楚觐省",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "能将疏懒背时人，不厌孤萍任此身。江上昔年同出处，",
            "天涯今日共风尘。平湖旧隐应残雪，芳草归心未隔春。",
            "前路倍怜多胜事，到家知庆彩衣新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 项王庙（一作栖一诗） ----------
    {
        "id": "ling-yi-24",
        "title": "项王庙（一作栖一诗）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "缅想咸阳事可嗟，楚歌哀怨思无涯。八千子弟归何处，",
            "万里鸿沟属汉家。弓断阵前争日月，血流垓下定龙蛇。",
            "拔山力尽乌江水，今日悠悠空浪花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 酬陈明府舟中见赠 ----------
    {
        "id": "ling-yi-25",
        "title": "酬陈明府舟中见赠",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "长溪通夜静，素舸与人闲。月影沈秋水，风声落暮山。",
            "稻花千顷外，莲叶两河间。陶令多真意，相思一解颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 题东兰若 ----------
    {
        "id": "ling-yi-26",
        "title": "题东兰若",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "上人禅室路裴回，万木清阴向日开。寒竹影侵行径石，",
            "秋风声入诵经台。闲云不系从舒卷，狎鸟无机任往来。",
            "更惜片阳谈妙理，归时莫待暝钟催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 送朱放 ----------
    {
        "id": "ling-yi-27",
        "title": "送朱放",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "苦见人间世，思归洞里天。纵令山鸟语，不废野人眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 归岑山过惟审上人别业（一作归岑山留别） ----------
    {
        "id": "ling-yi-28",
        "title": "归岑山过惟审上人别业（一作归岑山留别）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "禅客无心忆薜萝，自然行径向山多。",
            "知君欲问人间事，始与浮云共一过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 于潜道中呈元八处士 ----------
    {
        "id": "ling-yi-29",
        "title": "于潜道中呈元八处士",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "苕水滩行浅，潜州路渐深。参差远岫色，迢递野人心。",
            "冻涧冰难释，秋山日易阴。不知天目下，何处是云林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 送殷判官归上都 ----------
    {
        "id": "ling-yi-30",
        "title": "送殷判官归上都",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "漾舟云路客，来过夕阳时。向背堪遗恨，逢迎宿未期。",
            "水容愁暮急，花影动春迟。别后王孙草，青青入梦思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 赠别皇甫曾 ----------
    {
        "id": "ling-yi-31",
        "title": "赠别皇甫曾",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "幽人从远岳，过客爱春山。高驾能相送，孤游且未还。",
            "紫苔封井石，绿竹掩柴关。若到云峰外，齐心去住间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 送陈允初卜居麻园 ----------
    {
        "id": "ling-yi-32",
        "title": "送陈允初卜居麻园",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "欲向麻源隐，能寻谢客踪。空山几千里，幽谷第三重。",
            "茅宇宁须葺，荷衣不待缝。因君见往事，为我谢乔松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 秋题刘逸人林泉 ----------
    {
        "id": "ling-yi-33",
        "title": "秋题刘逸人林泉",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "凉飙乱黄叶，迟客橘阴清。萝径封行迹，云门闭野情。",
            "零林秋露响，穿竹暮烟轻。莫恋幽栖地，怀安却败名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 自大林与韩明府归郭中精舍 ----------
    {
        "id": "ling-yi-34",
        "title": "自大林与韩明府归郭中精舍",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "野客同舟楫，相携复一归。孤烟生暮景，远岫带春晖。",
            "不道还山是，谁云向郭非。禅门有通隐，喧寂共忘机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 同使君宿大梁驿 ----------
    {
        "id": "ling-yi-35",
        "title": "同使君宿大梁驿",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "旌旗江上出，花外卷帘空。夜色临城月，春寒度水风。",
            "虽然行李别，且喜语音同。若问匡庐事，终身愧远公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 题黄公陶翰别业（一作处一诗，一作苏广文诗） ----------
    {
        "id": "ling-yi-36",
        "title": "题黄公陶翰别业（一作处一诗，一作苏广文诗）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "闻说花源堪避秦，幽寻数月不逢人。烟霞洞里无鸡犬，",
            "风雨林间有鬼神。黄公石上三芝秀，陶令门前五柳春。",
            "醉卧白云闲入梦，不知何物是吾身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 哭卫尚书 ----------
    {
        "id": "ling-yi-37",
        "title": "哭卫尚书",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "画戟重门楚水阴，天涯欲暮共伤心。南荆双戟痕犹在，",
            "北斗孤魂望已深。莲花幕下悲风起，细柳营边晓月临。",
            "有路茫茫向谁问，感君空有泪沾襟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 赠灵澈禅师 ----------
    {
        "id": "ling-yi-38",
        "title": "赠灵澈禅师",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "禅师来往翠微间，万里千峰到剡山。",
            "何时共到天台里，身与浮云处处闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 将出宜丰寺留题山房 ----------
    {
        "id": "ling-yi-39",
        "title": "将出宜丰寺留题山房",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "池上莲荷不自开，山中流水偶然来。",
            "若言聚散定由我，未是回时那得回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 妙乐观（一作题王乔观传傅道士所居） ----------
    {
        "id": "ling-yi-40",
        "title": "妙乐观（一作题王乔观传傅道士所居）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "王乔所居空山观，白云至今凝不散。坛场月路几千年，",
            "往往吹笙下天半。瀑布西行过石桥，黄精采根还采苗。",
            "忽见一人檠茶碗，篸花昨夜风吹满。自言家处在东坡，",
            "白犬相随邀我过。松间石上有棋局，能使樵人烂斧柯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 与元居士青山潭饮茶 ----------
    {
        "id": "ling-yi-41",
        "title": "与元居士青山潭饮茶",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "野泉烟火白云间，坐饮香茶爱此山。",
            "岩下维舟不忍去，青溪流水暮潺潺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送人得荡子归倡妇（一作行不归） ----------
    {
        "id": "ling-yi-42",
        "title": "送人得荡子归倡妇（一作行不归）",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "垂涕凭回信，为语柳园人。情知独难守，又是一阳春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 句 ----------
    {
        "id": "ling-yi-43",
        "title": "句",
        "author": "灵一",
        "poet_id": "ling-yi",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "滤泉侵月起，扫径避虫行。（《丹铅录》）",
            "第八百一十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]