# -*- coding: utf-8 -*-
"""
刘得仁卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 139 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 听歌 ----------
    {
        "id": "liu-de-ren-1",
        "title": "听歌",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "朱槛满明月，美人歌落梅。忽惊尘起处，疑是有风来。",
            "一曲听初彻，几年愁暂开。东南正云雨，不得见阳台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 青龙寺僧院 ----------
    {
        "id": "liu-de-ren-2",
        "title": "青龙寺僧院",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "常多簪组客，非独看高松。此地堪终日，开门见数峰。",
            "苔新禽迹少，泉冷树阴重。师意如山里，空房晓暮钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 夏夜会同人 ----------
    {
        "id": "liu-de-ren-3",
        "title": "夏夜会同人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "沈沈清暑夕，星斗俨虚空。岸帻栖禽下，烹茶玉漏中。",
            "形骸忘已久，偃仰趣无穷。日汲泉来漱，微开密筱风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 游崔监丞城南别业 ----------
    {
        "id": "liu-de-ren-4",
        "title": "游崔监丞城南别业",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "门与青山近，青山复几重。雪融皇子岸，春浥翠微峰。",
            "地有经冬草，林无未老松。竹寒溪隔寺，晴日直闻钟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 答韦先辈春雨后见寄 ----------
    {
        "id": "liu-de-ren-5",
        "title": "答韦先辈春雨后见寄",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "风散五更雨，鸟啼三月春。轩窗透初日，砚席绝纤尘。",
            "帝里峰头出，邻家树色新。怜君高且静，有句寄闲人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 题吴先生山居 ----------
    {
        "id": "liu-de-ren-6",
        "title": "题吴先生山居",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "先生此幽隐，便可谢人群。潭底见秋石，树间飞霁云。",
            "山居心已惯，俗事耳憎闻。念我要多疾，开炉药许分。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 晚游慈恩寺 ----------
    {
        "id": "liu-de-ren-7",
        "title": "晚游慈恩寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "寺去幽居近，每来因采薇。伴僧行不困，临水语忘归。",
            "磬动青林晚，人惊白鹭飞。堪嗟浮俗事，皆与道相违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 题王处士山居 ----------
    {
        "id": "liu-de-ren-8",
        "title": "题王处士山居",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "茅堂入谷远，林暗绝其邻。终日有流水，经年无到人。",
            "溪云常欲雨，山洞别开春。自得仙家术，栽松独养真。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 宿僧院 ----------
    {
        "id": "liu-de-ren-9",
        "title": "宿僧院",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "禅地无尘夜，焚香话所归。树摇幽鸟梦，萤入定僧衣。",
            "破月斜天半，高河下露微。翻令嫌白日，动即与心违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 晓别吕山人 ----------
    {
        "id": "liu-de-ren-10",
        "title": "晓别吕山人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "疏钟兼漏尽，曙色照青氛。栖鹤出高树，山人归白云。",
            "月盈期重宿，丹熟约相分。羡入秋风洞，幽泉仔细闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 送知全禅师南游 ----------
    {
        "id": "liu-de-ren-11",
        "title": "送知全禅师南游",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "师誉振京城，谈空万乘听。北行山已雪，南去木犹青。",
            "夜岳禅销月，秋潭汲动星。回期不可定，孤鹤在高冥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 上张水部 ----------
    {
        "id": "liu-de-ren-12",
        "title": "上张水部",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "出入门阑久，儿童亦有情。不须将姓字，长说向公卿。",
            "每许连床坐，时容并马行。恩深转无语，怀抱自分明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 塞上行作 ----------
    {
        "id": "liu-de-ren-13",
        "title": "塞上行作",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "乡井从离别，穷边触目愁。生人居外地，塞雪下中秋。",
            "雁举之衡翅，河穿入虏流。将军心莫苦，向此取封侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 赠江夏卢使君 ----------
    {
        "id": "liu-de-ren-14",
        "title": "赠江夏卢使君",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "诗人中最屈，无与使君俦。白发虽求退，明时合见收。",
            "登山犹自健，纵酒可多愁。好是能骑马，相逢见鄂州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 冬夜寄白阁僧 ----------
    {
        "id": "liu-de-ren-15",
        "title": "冬夜寄白阁僧",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "营营不自息，暌阔数年情。林下期难遂，人间事旋生。",
            "鸟栖寒水迥，月映积冰清。石室焚香坐，悬知不为名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 送姚合郎中任杭州 ----------
    {
        "id": "liu-de-ren-16",
        "title": "送姚合郎中任杭州",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "水陆中分程，看花一月行。会稽山隔浪，天竺树连城。",
            "候吏赍鱼印，迎船载旆旌。渡江春始半，列屿草初生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 西园 ----------
    {
        "id": "liu-de-ren-17",
        "title": "西园",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "夏圃秋凉入，树低逢帻欹。水声翻败堰，山翠湿疏篱。",
            "绿滑莎藏径，红连果压枝。幽人更何事，旦夕与僧期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 昊天观新栽竹 ----------
    {
        "id": "liu-de-ren-18",
        "title": "昊天观新栽竹",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "清风枝叶上，山鸟已栖来。根别古沟岸，影生秋观苔。",
            "遍思诸草木，惟此出尘埃。恨为移君晚，空庭更拟栽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 晚步曲江因谒慈恩寺恭上人 ----------
    {
        "id": "liu-de-ren-19",
        "title": "晚步曲江因谒慈恩寺恭上人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "岂曰趣名者，年年待命通。坐令青嶂上，兴起白云中。",
            "岸浸如天水，林含似雨风。南宗犹有碍，西寺问恭公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 送姚处士归亳州 ----------
    {
        "id": "liu-de-ren-20",
        "title": "送姚处士归亳州",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "白发麻衣破，还谯别弟回。首垂听乐泪，花落待歌杯。",
            "石路寻芝熟，柴门有鹿来。明王下征诏，应就碧峰开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 寄楼子山云栖上人 ----------
    {
        "id": "liu-de-ren-21",
        "title": "寄楼子山云栖上人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "一室凿崔嵬，危梯叠藓苔。永无尘事到，时有至人来。",
            "涧谷冬深静，烟岚日午开。修身知得地，京寺未言回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 秋夜喜友人宿 ----------
    {
        "id": "liu-de-ren-22",
        "title": "秋夜喜友人宿",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "莫说春闱事，清宵且共吟。频年遗我辈，何日遇知音。",
            "逼曙天倾斗，将寒叶坠林。无将簪绂意，只损壮夫心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 秋日同僧宿西池 ----------
    {
        "id": "liu-de-ren-23",
        "title": "秋日同僧宿西池",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "菡萏遍秋水，隔林香似焚。僧同池上宿，霞向月边分。",
            "渚鸟栖蒲立，城砧接曙闻。来宵莫他约，重此话孤云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 宿韦津山居 ----------
    {
        "id": "liu-de-ren-24",
        "title": "宿韦津山居",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "永夕见招宿，诗书盈草堂。静吟倾美酒，高论出名场。",
            "窗飒松篁韵，庭兼雪月光。心期身未老，一去泛潇湘。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 夜携酒访崔正字 ----------
    {
        "id": "liu-de-ren-25",
        "title": "夜携酒访崔正字",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "只应芸阁吏，知我僻兼愚。吟兴忘饥冻，生涯任有无。",
            "惨云埋远岫，阴吹吼寒株。忽起围炉思，招携酒满壶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 送蔡京东归迎侍 ----------
    {
        "id": "liu-de-ren-26",
        "title": "送蔡京东归迎侍",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "高堂惟两别，此别是荣归。薄俸迎亲远，平时知己稀。",
            "郓郊秋木见，鲁寺夜钟微。近腊西来日，多逢霰雪飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 中秋 ----------
    {
        "id": "liu-de-ren-27",
        "title": "中秋",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "尘里兼尘外，咸期此夕明。一年惟一度，长恐有云生。",
            "露洗微埃尽，光濡是物清。朗吟看正好，惆怅又西倾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 池上宿 ----------
    {
        "id": "liu-de-ren-28",
        "title": "池上宿",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "事事不求奢，长吟省叹嗟。无才堪世弃，有句向谁夸。",
            "老树呈秋色，空池浸月华。凉风白露夕，此境属诗家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 秋夕即事 ----------
    {
        "id": "liu-de-ren-29",
        "title": "秋夕即事",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "永夕坐暝久，萧萧猿狖啼。漏微砧韵隔，月落斗杓低。",
            "危叶无风坠，幽禽并树栖。自怜在岐路，不醉亦沉迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 晚夏 ----------
    {
        "id": "liu-de-ren-30",
        "title": "晚夏",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "日夕是西风，流光半已空。山光渐凝碧，树叶即翻红。",
            "学浅惭多士，秋成羡老农。谁怜信公道，不泣路岐中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 夏日即事 ----------
    {
        "id": "liu-de-ren-31",
        "title": "夏日即事",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "到晓改诗句，四邻嫌苦吟。中宵横北斗，夏木隐栖禽。",
            "天地先秋肃，轩窗映月深。幽庭多此景，惟恐曙光侵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 夏日通济里居酬诸先辈见访 ----------
    {
        "id": "liu-de-ren-32",
        "title": "夏日通济里居酬诸先辈见访",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "君子远相寻，联镳到敝林。有诗谁索和，无酒可赊斟。",
            "门列晴峰色，堂开古木阴。何因驻清听，惟恐日西沉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 寄姚谏议 ----------
    {
        "id": "liu-de-ren-33",
        "title": "寄姚谏议",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "鸣鞭静路尘，籍籍谏垣臣。函疏封还密，炉香侍立亲。",
            "箧多临水作，窗宿卧云人。危坐开寒纸，灯前起草频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 和厉玄侍御题户部相公庐山草堂 ----------
    {
        "id": "liu-de-ren-34",
        "title": "和厉玄侍御题户部相公庐山草堂",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "白云居创毕，诏入凤池年。林长双峰树，潭分并寺泉。",
            "石溪盘鹤外，岳室闭猿前。柱史题诗后，松前更肃然。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 题山中故静禅师 ----------
    {
        "id": "liu-de-ren-35",
        "title": "题山中故静禅师",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "寂灭身何在，门人隔此生。影悬尘已厚，塔种柏初成。",
            "溪院秋先雪，山堂古有精。当时挂锡处，树老几枝倾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 夏日游慈恩寺 ----------
    {
        "id": "liu-de-ren-36",
        "title": "夏日游慈恩寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "何处消长日，慈恩精舍频。僧高容野客，树密绝嚣尘。",
            "闲上凌虚塔，相逢避暑人。却愁归去路，马迹并车轮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 题终南麻先生寂禅师石室 ----------
    {
        "id": "liu-de-ren-37",
        "title": "题终南麻先生寂禅师石室",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "因居石室贫，五十二回春。拥褐冥心客，穷经暮齿人。",
            "翠沉空水定，雨绝片云新。危细秋峰径，相随到顶频。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 送灵武朱书记 ----------
    {
        "id": "liu-de-ren-38",
        "title": "送灵武朱书记",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "灵帅与谁善，得君宾幕中。从容应尽礼，赞画致元功。",
            "连塞云长惨，才秋树半空。相如偏自惬，掌记复乘骢。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 吊草堂禅师 ----------
    {
        "id": "liu-de-ren-39",
        "title": "吊草堂禅师",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "杖履疑师在，房关四壁蛩。贮瓶经腊水，响塔隔山钟。",
            "乳鸽沿苔井，斋猿散雪峰。如何不相见，倚遍寺前松。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 早春送湘潭李少府之任 ----------
    {
        "id": "liu-de-ren-40",
        "title": "早春送湘潭李少府之任",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "柳新春水湄，春岸草离离。祖席觞云尽，离人泪各垂。",
            "业文传不朽，作尉岂多时。公退琴堂上，风吹斑竹枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 送越客归 ----------
    {
        "id": "liu-de-ren-41",
        "title": "送越客归",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "霜薄东南地，江枫落未齐。众山离楚上，孤棹宿吴西。",
            "渚客留僧语，笼猿失子啼。到家冬即是，荷尽若耶溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 送周钺往江夏 ----------
    {
        "id": "liu-de-ren-42",
        "title": "送周钺往江夏",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "东西南北郡，自说遍曾游。人世终多故，皇都不少留。",
            "郢城帆过夜，汉水月方秋。此谒亲知去，闻猿岂解愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 送河池李明府之任 ----------
    {
        "id": "liu-de-ren-43",
        "title": "送河池李明府之任",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "河池安所理，种柳与弹琴。自合清时化，仍资白首吟。",
            "程馀行片月，公退入遥林。想得询民瘼，方称单父心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送蔡京侍御赴大梁幕 ----------
    {
        "id": "liu-de-ren-44",
        "title": "送蔡京侍御赴大梁幕",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "同城各多故，会面亦稀疏。及道须相别，临岐恨有馀。",
            "梁园飞楚鸟，汴水走淮鱼。众说裁军檄，陈琳远不如。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 哭鲍溶有感 ----------
    {
        "id": "liu-de-ren-45",
        "title": "哭鲍溶有感",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "寥落故人宅，今来身已亡。古苔封墨沼，深竹映书堂。",
            "秋色池馆静，雨声云水凉。无因展交道，日暮剖心肠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 送僧归玉泉寺 ----------
    {
        "id": "liu-de-ren-46",
        "title": "送僧归玉泉寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "玉泉归故刹，便老是僧期。乱木孤蝉后，寒山绝鸟时。",
            "若寻流水去，转出白云迟。见说千峰路，溪深复顶危。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 宣义池上 ----------
    {
        "id": "liu-de-ren-47",
        "title": "宣义池上",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "修篁夹绿池，幽絮此中飞。何必青山远，仍将白发归。",
            "鸟啼亦有恨，鸥习总无机。树起秋风细，西林磬入微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 回中夜访独孤从事 ----------
    {
        "id": "liu-de-ren-48",
        "title": "回中夜访独孤从事",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "满庭霜月魄，风静绝纤闻。边境时无事，州城夜访君。",
            "拥裘听塞角，酌醴话湘云。赞佐元戎美，恩齐十万军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 宿宣义池亭 ----------
    {
        "id": "liu-de-ren-49",
        "title": "宿宣义池亭",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "暮色绕柯亭，南山幽竹青。夜深斜舫月，风定一池星。",
            "岛屿无人迹，菰蒲有鹤翎。此中足吟眺，何用泛沧溟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 送智玄首座归蜀中旧山 ----------
    {
        "id": "liu-de-ren-50",
        "title": "送智玄首座归蜀中旧山",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "像教得重兴，因师说大乘。从来悟明主，今去证高僧。",
            "蜀国烟霞异，灵山水月澄。乡闾诸善友，喜似见南能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 贺顾非熊及第其年内索文章 ----------
    {
        "id": "liu-de-ren-51",
        "title": "贺顾非熊及第其年内索文章",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "愚为童稚时，已解念君诗。及得高科晚，须逢圣主知。",
            "花前翻有泪，鬓上却无丝。从此东归去，休为坠叶期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 冬日骆家亭子 ----------
    {
        "id": "liu-de-ren-52",
        "title": "冬日骆家亭子",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "亭台腊月时，松竹见贞姿。林积烟藏日，风吹水合池。",
            "恨无人此住，静有鹤相窥。是景吟诗遍，真于野客宜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 题邵公禅院（一作冬日题邵公院） ----------
    {
        "id": "liu-de-ren-53",
        "title": "题邵公禅院（一作冬日题邵公院）",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "无事门多掩，阴阶竹扫苔。劲风吹雪聚，渴鸟啄冰开。",
            "树向寒山得，人从瀑布来。终期天目老，擎锡逐云回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 忆鹤 ----------
    {
        "id": "liu-de-ren-54",
        "title": "忆鹤",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "自尔归仙后，经秋又过春。白云寻不得，紫府去无因。",
            "此地空明月，何山伴羽人。终期华表上，重见令威身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 听夜泉 ----------
    {
        "id": "liu-de-ren-55",
        "title": "听夜泉",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "静里层层石，潺湲到鹤林。流回出几洞，源远历千岑。",
            "寒助空山月，清兼此夜心。幽人听达曙，相和藓床吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 乐游原春望 ----------
    {
        "id": "liu-de-ren-56",
        "title": "乐游原春望",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "乐游原上望，望尽帝都春。始觉繁华地，应无不醉人。",
            "云开双阙丽，柳映九衢新。爱此频来往，多闲逐此身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 赠雍陶博士 ----------
    {
        "id": "liu-de-ren-57",
        "title": "赠雍陶博士",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "腹是群书笥，官为六义师。情高少尘事，朝下足闲时。",
            "有句同人伏，无私胄子知。汉庭公议在，正与触邪宜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 夏日感怀寄所知 ----------
    {
        "id": "liu-de-ren-58",
        "title": "夏日感怀寄所知",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "了了见岐路，欲行难负心。趋时不圆转，自古易湮沉。",
            "日正林方合，蜩鸣夏已深。中郎今远在，谁识爨桐音。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 陈情上知己 ----------
    {
        "id": "liu-de-ren-59",
        "title": "陈情上知己",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "性与才俱拙，名场迹甚微。久居颜亦厚，独立事多非。",
            "刻骨搜新句，无人悯白衣。明时自堪恋，不是不知机。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 秋夜寄友人二首 ----------
    {
        "id": "liu-de-ren-60",
        "title": "秋夜寄友人二首",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "永夜无他虑，长吟毕二更。暗灯摇碧影，滞雨滴阶声。",
            "道进愁还浅，年加睡自轻。如何得深术，相与舍浮名。",
            "所思同海岱，所梦亦烟波。默坐看山久，闲行值寺过。",
            "独吟黄叶乱，相去碧峰多。我有归心在，君行竟若何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 寄春坊顾校书 ----------
    {
        "id": "liu-de-ren-61",
        "title": "寄春坊顾校书",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "宁因不得志，寂寞本相宜。冥目冥心坐，花开花落时。",
            "数畦蔬甲出，半梦鸟声移。只恐龙楼吏，归山又见违。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 寄雍陶先辈 ----------
    {
        "id": "liu-de-ren-62",
        "title": "寄雍陶先辈",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "久别青云士，幽人分固然。愁心不易去，蹇步卒难前。",
            "尽落经霜叶，频阴欲雪天。归山自有限，岂待白头年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 对月寄雍陶 ----------
    {
        "id": "liu-de-ren-63",
        "title": "对月寄雍陶",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "圆明寒魄上，天地一光中。临水通宵坐，知君此兴同。",
            "华凝衣有露，静极树无风。若向湘江见，湘江彻底空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 寄谢观 ----------
    {
        "id": "liu-de-ren-64",
        "title": "寄谢观",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "十五年馀苦，今朝始遇君。无惭于白日，不枉别孤云。",
            "得失天难问，称扬鬼亦闻。此恩销镂骨，吟坐叶纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 送鄂州崔大夫赴镇 ----------
    {
        "id": "liu-de-ren-65",
        "title": "送鄂州崔大夫赴镇",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "廉问帝难人，朝廷辍重臣。入山初有雪，登路正无尘。",
            "去国鸣驺缓，经云住旆频。千峰与万木，清听雨情新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 送钱给事赴虢州 ----------
    {
        "id": "liu-de-ren-66",
        "title": "送钱给事赴虢州",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "帝心忧虢俗，暂辍掖垣臣。疲瘵初承制，乡闾似得春。",
            "化成应有瑞，位重转闻贫。用作盐梅日，争回卧辙人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 送雍陶侍御赴兖州裴尚书命 ----------
    {
        "id": "liu-de-ren-67",
        "title": "送雍陶侍御赴兖州裴尚书命",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "纶阁知孤直，翻论北巷贤。且縻莲幕里，会致玉阶前。",
            "洙泗秋微动，龟蒙月正圆。元戎军务息，清句待君联。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 送新罗人归本国 ----------
    {
        "id": "liu-de-ren-68",
        "title": "送新罗人归本国",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "鸡林隔巨浸，一住一年行。日近国先曙，风吹海不平。",
            "眼穿乡井树，头白渺瀰程。到彼星霜换，唐家语却生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 送车涛罢举归山 ----------
    {
        "id": "liu-de-ren-69",
        "title": "送车涛罢举归山",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "朝是暮还非，人情冷暖移。浮生只如此，强进欲何为。",
            "要路知无援，深山必遇师。怜君明此理，休去不迟疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 送王书记归邠州 ----------
    {
        "id": "liu-de-ren-70",
        "title": "送王书记归邠州",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "陈琳轻一别，马上意超然。来日行烦暑，归时听早蝉。",
            "阴云翳城郭，细雨紊山川。从事公刘地，元戎旧礼贤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 送谢观之剑南从事 ----------
    {
        "id": "liu-de-ren-71",
        "title": "送谢观之剑南从事",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "迢递从知己，他人敢更言。离京虽未腊，到府已应暄。",
            "飞急奔行雁，啼酸忆子猿。江山无限思，君拟共谁论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 送顾非熊作尉盱眙 ----------
    {
        "id": "liu-de-ren-72",
        "title": "送顾非熊作尉盱眙",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "一名兼一尉，未足是君伸。历数为诗者，多来作谏臣。",
            "路翻平楚阔，草带古淮新。天下虽云大，同声有几人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 送高湘及第后东归觐叔 ----------
    {
        "id": "liu-de-ren-73",
        "title": "送高湘及第后东归觐叔",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "此去几般荣，登科鼎足名。无惭入南巷，高价耸东京。",
            "窗对嵩山碧，庭来洛水声。门前桃李树，一径已阴成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 送友人下第归觐 ----------
    {
        "id": "liu-de-ren-74",
        "title": "送友人下第归觐",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "君此卜行日，高堂应梦归。莫将和氏泪，滴著老莱衣。",
            "岳雨连河细，田禽出麦飞。到家调膳后，吟苦落蝉晖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 送友人下第归扬州觐省 ----------
    {
        "id": "liu-de-ren-75",
        "title": "送友人下第归扬州觐省",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "新柳间花垂，东西京路岐。园林知自到，寝食计相思。",
            "雨断淮山出，帆扬楚树移。晨昏心已泰，蝉发是回时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 早行 ----------
    {
        "id": "liu-de-ren-76",
        "title": "早行",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "万类半已动，此心宁自安。月沉平野尽，星隐曙空残。",
            "马渡横流广，人行湛露寒。还思犹梦者，不信早行难。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 通济里居酬卢肇见寻不遇 ----------
    {
        "id": "liu-de-ren-77",
        "title": "通济里居酬卢肇见寻不遇",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "衡门掩绿苔，树下绝尘埃。偶赴高僧约，旋知长者来。",
            "云山堪眺望，车马必裴回。问以何为待，惭无酒一杯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 赠王尊师 ----------
    {
        "id": "liu-de-ren-78",
        "title": "赠王尊师",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "为道常日损，尊师修此心。挂肩黄布被，穿发白蒿簪。",
            "符札灵砂字，弦弹古素琴。囊中曾有药，点土亦成金。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 冬夜与蔡校书宿无可上人院 ----------
    {
        "id": "liu-de-ren-79",
        "title": "冬夜与蔡校书宿无可上人院",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "儒释偶同宿，夜窗寒更清。忘机于世久，晤语到天明。",
            "月倒高松影，风旋一磬声。真门犹是幻，不用觉浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 冬日喜同志宿 ----------
    {
        "id": "liu-de-ren-80",
        "title": "冬日喜同志宿",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "相逢话清夜，言实转相知。共道名虽切，唯论命不疑。",
            "吟身坐霜石，眠鸟握风枝。别忆天台客，烟霞昔有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 逢吕上山人 ----------
    {
        "id": "liu-de-ren-81",
        "title": "逢吕上山人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "尘里正愁老，相逢眼益明。从前枉多病，此后鲜疏名。",
            "古柏今收子，深山许事兄。长生如有分，愿逐到蓬瀛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 春暮对雨 ----------
    {
        "id": "liu-de-ren-82",
        "title": "春暮对雨",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "春暮雨微微，翻疑坠叶时。气蒙杨柳重，寒勒牡丹迟。",
            "未夕鸟先宿，望晴人有期。何当廓阴闭，新暑竹风吹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 长信宫 ----------
    {
        "id": "liu-de-ren-83",
        "title": "长信宫",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "簟凉秋气初，长信恨何如。拂黛月生指，解鬟云满梳。",
            "一从悲画扇，几度泣前鱼。坐听南宫乐，清风摇翠裾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 初夏题段郎中修竹里南园 ----------
    {
        "id": "liu-de-ren-84",
        "title": "初夏题段郎中修竹里南园",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "高人游息处，与此曲池连。密树才春后，深山在目前。",
            "远峰初绝雨，片石欲生烟。数有僧来宿，应缘静好禅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 题景玄禅师院 ----------
    {
        "id": "liu-de-ren-85",
        "title": "题景玄禅师院",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "古僧精进者，师复是谁流。道贵行无我，禅难说到头。",
            "汲泉羸鹤立，拥褐老猿愁。曾住深山院，何如此院幽。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 夏日樊川别业即事 ----------
    {
        "id": "liu-de-ren-86",
        "title": "夏日樊川别业即事",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "无事称无才，柴门亦罕开。脱巾吟永日，著屐步荒台。",
            "风卷微尘上，霆将暴雨来。终南云渐合，咫尺失崔嵬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 寄无可上人 ----------
    {
        "id": "liu-de-ren-87",
        "title": "寄无可上人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "省学为诗日，宵吟每达晨。十年期是梦，一事未成身。",
            "枉别山中客，殊非世上人。今来已如此，须得桂荣新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 和范校书赠造微上人 ----------
    {
        "id": "liu-de-ren-88",
        "title": "和范校书赠造微上人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "得性见微公，何曾执著空。修心将佛并，吐论与儒通。",
            "晓漱松杉下，宵禅雪月中。他生有缘会，君子亦应同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 访曲江胡处士 ----------
    {
        "id": "liu-de-ren-89",
        "title": "访曲江胡处士",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "何况归山后，而今已似仙。卜居天苑畔，闲步禁楼前。",
            "落日明沙岸，微风上纸鸢。静还林石下，坐读养生篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 慈恩寺塔下避暑 ----------
    {
        "id": "liu-de-ren-90",
        "title": "慈恩寺塔下避暑",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "古松凌巨塔，修竹映空廊。竟日闻虚籁，深山只此凉。",
            "僧真生我静，水淡发茶香。坐久东楼望，钟声振夕阳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 秋晚与友人游青龙寺 ----------
    {
        "id": "liu-de-ren-91",
        "title": "秋晚与友人游青龙寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "高视终南秀，西风度阁凉。一生同隙影，几处好山光。",
            "暮鸟投嬴木，寒钟送夕阳。因居话心地，川冥宿僧房。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 春日雨后作 ----------
    {
        "id": "liu-de-ren-92",
        "title": "春日雨后作",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "朝来微有雨，天地爽无尘。北阙明如画，南山碧动人。",
            "车舆终日别，草树一城新。枉是吾君戚，何门谒紫宸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 别王山人 ----------
    {
        "id": "liu-de-ren-93",
        "title": "别王山人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷93》",
        "verse": [
            "旨甘虽自足，未是禄荣亲。尚逐趋时伴，多离有道人。",
            "山居衣以草，生寄药随身。不食长无疾，年知出十旬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 赠陶山人 ----------
    {
        "id": "liu-de-ren-94",
        "title": "赠陶山人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "处士例营营，惟君纵此生。闲能资寿考，健不换公卿。",
            "药圃妻同耨，山田子共耕。定知丹熟后，无姓亦无名。",
            "第五百四十五卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 禁署早春晴望 ----------
    {
        "id": "liu-de-ren-95",
        "title": "禁署早春晴望",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "御林闻有早莺声，玉槛春香九陌晴。寒著霁云归紫阁，",
            "暖浮佳气动芳城。宫池日到冰初解，辇路风吹草欲生。",
            "鸳侣此时皆赋咏，商山雪在思尤清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 山中寻道人不遇 ----------
    {
        "id": "liu-de-ren-96",
        "title": "山中寻道人不遇",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "年过弱冠风尘里，常拟随师学炼形。石路特来寻道者，",
            "云房空见有仙经。棋于松底留残局，鹤向潭边退数翎。",
            "便欲此居闲到老，先生何日下青冥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 赠敬晊助教二首（一作无可诗） ----------
    {
        "id": "liu-de-ren-97",
        "title": "赠敬晊助教二首（一作无可诗）",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "到来常听说清虚，手把玄元七字书。仙籍不知名姓有，",
            "道情惟见往来疏。已能绝粒无饥色，早晚休官买隐居。",
            "便欲去随为弟子，片云孤鹤可相于。",
            "街西静观求居处，不到权门到寺频。禁掖人知连状荐，",
            "国庠官满一家贫。清仪称是蓬瀛客，直气堪为谏诤臣。",
            "自顾无成年渐长，报恩惟愿杀微身。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 送祖山人归山 ----------
    {
        "id": "liu-de-ren-98",
        "title": "送祖山人归山",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "独来朝市笑浮云，却忆烟霞出帝城。不说金丹能点化，",
            "空教弟子学长生。壶中泻酒看云影，洞里逢师下鹤迎。",
            "料得仙家玉牌上，已镌白日上升名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 监试莲花峰 ----------
    {
        "id": "liu-de-ren-99",
        "title": "监试莲花峰",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "太华万馀重，岧峣只此峰。当秋倚寥泬，入望似芙蓉。",
            "翠拔千寻直，青危一朵秾。气分毛女秀，灵有羽人踪。",
            "倒影侵官路，流香激庙松。尘埃终不及，车马自憧憧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 京兆府试目极千里 ----------
    {
        "id": "liu-de-ren-100",
        "title": "京兆府试目极千里",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "献赋多年客，低眉恨不前。此心常郁矣，纵目忽超然。",
            "送骥登长路，看鸿入远天。古墟烟幂幂，穷野草绵绵。",
            "树与金城接，山疑桂水连。何当开霁日，无物翳平川。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 寻陈处士山堂 ----------
    {
        "id": "liu-de-ren-101",
        "title": "寻陈处士山堂",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "步溪凡几转，始得见幽踪。路隐千根树，门开万仞峰。",
            "片云生石窦，浅水卧枯松。穷谷风光冷，深山翠碧浓。",
            "鹤看空里过，仙向坐中逢。底露秋潭水，声微暮观钟。",
            "他年来此定，异日愿相容。且喜今归去，人间事更慵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 题从伯舍人道正里南园 ----------
    {
        "id": "liu-de-ren-102",
        "title": "题从伯舍人道正里南园",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "帝里馀新第，朱门面碧岑。曙堂增爽气，乔木动清阴。",
            "直去亲瑶陛，朝回在竹林。风流才子调，好尚古人心。",
            "薜荔遮窗暗，莓苔近井深。礼无青草隔，诗共白衣吟。",
            "轩静留孤鹤，庭虚到远砧。掩关裁凤诏，开镜理琼簪。",
            "种植今如此，尘埃永不侵。云奔投刺者，日日待为霖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 赋得听松声 ----------
    {
        "id": "liu-de-ren-103",
        "title": "赋得听松声",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "庭际微风动，高松韵自生。听时无物乱，尽日觉神清。",
            "强与幽泉并，翻嫌细雨并。拂空增鹤唳，过牖合琴声。",
            "况复当秋暮，偏宜在月明。不知深涧底，萧瑟有谁听。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 宿普济寺 ----------
    {
        "id": "liu-de-ren-104",
        "title": "宿普济寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "京寺数何穷，清幽此不同。曲江临阁北，御苑自墙东。",
            "广陌车音急，危楼夕景通。乱峰沉暝野，毒暑过秋空。",
            "幡飏虚无里，星生杳霭中。月光笼月殿，莲气入莲宫。",
            "缀草凉天露，吹人古木风。饮茶除假寐，闻磬释尘蒙。",
            "童子眠苔净，高僧话漏终。待鸣晓钟后，万井复朣胧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 和郑校书夏日游郑泉 ----------
    {
        "id": "liu-de-ren-105",
        "title": "和郑校书夏日游郑泉",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "太虚悬畏景，古木蔽清阴。爰有泉堪挹，闲思日可寻。",
            "来闻鸣滴滴，照竦碧沈沈。几脉成溪壑，何人测浅深。",
            "澄时无一物，分处历千林。净溉灵根药，凉浮玉翅禽。",
            "饮疑蠲宿疾，见自失烦襟。僧共云前濑，龙和月下吟。",
            "叠光轻吹动，彻底晓霞侵。不用频游去，令君少进心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 和段校书冬夕寄题庐山 ----------
    {
        "id": "liu-de-ren-106",
        "title": "和段校书冬夕寄题庐山",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "名高身未到，此恨蓄多时。是夕吟因话，他年必去随。",
            "尝闻庐岳顶，半入楚江湄。几处悬崖上，千寻瀑布垂。",
            "炉峰松淅沥，湓浦柳参差。日色连湖白，钟声拂浪迟。",
            "烟梯缘薜荔，岳寺步欹危。地本饶灵草，林曾出祖师。",
            "石楼霞耀壁，猿树鹤分枝。细径萦岩末，高窗见海涯。",
            "嵌空寒更极，寂寞夜尤思。阴谷冰埋术，仙田雪覆芝。",
            "乱泉禅客濑，异迹逸人知。藓室新开灶，柽潭未了棋。",
            "如何遂闲放，长得在希夷。空务渔樵事，方无道路悲。",
            "谢公台尚在，陶令柳潜衰。尘外难相许，人间贵迹遗。",
            "虽怀丹桂影，不忘白云期。仁者终携手，今朝预赋诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 书事寄万年厉员外 ----------
    {
        "id": "liu-de-ren-107",
        "title": "书事寄万年厉员外",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "帝城皆剧县，令尹美居东。遂拜赵张下，暂离星象中。",
            "拥归从北阙，送上动南宫。紫禁黄山绕，沧溟素浐通。",
            "封疆亲日月，邑里出王公。赋税充天府，歌谣入圣聪。",
            "土膏寒麦覆，人海昼尘蒙。廨宇松连翠，朝街火散红。",
            "文场新桂茂，粉署旧兰崇。留客挥盈爵，抽毫咏早鸿。",
            "前驺潘岳贵，故里邵平穷。劝隐莲峰久，期耕树谷同。",
            "凫飞将去叶，剑气尚埋丰。何必华阴土，方垂拂拭功。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 上姚谏议 ----------
    {
        "id": "liu-de-ren-108",
        "title": "上姚谏议",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "高文与盛德，皆谓古无伦。圣代生才子，明庭有谏臣。",
            "已瞻龙衮近，渐向凤池新。却忆波涛郡，来时岛屿春。",
            "名因诗句大，家似布衣贫。曾暗投新轴，频闻奖滞身。",
            "照吟清夕月，送药紫霞人。终计依门馆，何疑不化鳞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 上翰林丁学士 ----------
    {
        "id": "liu-de-ren-109",
        "title": "上翰林丁学士",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "今代如尧代，征贤察众情。久聆推行实，然后佐聪明。",
            "官自文华重，恩因顾问生。词人求作称，天子许和羹。",
            "御柳凋霜晚，宫泉滴月清。直庐寒漏近，秋烛白麻成。",
            "玉殿移时对，金舆数侍行。赐衣香未散，借马色难名。",
            "时辈何偏羡，儒流此最荣。终当闻燮理，寰宇永升平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 二（一本将后四句作下第吟绝句） ----------
    {
        "id": "liu-de-ren-110",
        "title": "二（一本将后四句作下第吟绝句）",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "何处访岐路，青云但忆归。风尘数年限，门馆一生依。",
            "外族帝王是，中朝亲旧稀。翻令浮议者，不许九霄飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 山中舒怀寄上丁学士 ----------
    {
        "id": "liu-de-ren-111",
        "title": "山中舒怀寄上丁学士",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "五字投精鉴，惭非大雅词。本求闲赐览，岂料便蒙知。",
            "幽拙欣殊幸，提携更不疑。弱苗须雨长，懒翼在风吹。",
            "砺镞端杨叶，光门待桂枝。计闻尘里誉，因和禁中诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 莺出谷 ----------
    {
        "id": "liu-de-ren-112",
        "title": "莺出谷",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "东风潜启物，动息意皆新。此鸟从幽谷，依林报早春。",
            "出寒虽未及，振羽渐能频。稍类冲天鹤，多随折桂人。",
            "尊前喧有语，花里昼藏身。若向秾华处，馀禽不见亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 哭翰林丁侍郎 ----------
    {
        "id": "liu-de-ren-113",
        "title": "哭翰林丁侍郎",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "相知出肺腑，非旧亦非亲。每见云霄侣，多扬鄙拙身。",
            "即期扶泰运，岂料哭贤人。应是随先帝，依前作近臣。",
            "平生任公直，爱弟尚风尘。宅闭青松古，坟临赤水新。",
            "官清仍齿壮，儿小复家贫。惆怅天难问，空流泪满巾。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 陈情上李景让大夫 ----------
    {
        "id": "liu-de-ren-114",
        "title": "陈情上李景让大夫",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "一被浮名误，旋遭白发侵。裴回恋明主，梦寐在秋岑。",
            "遇物唯多感，居常只是吟。待时钳定口，经事压低心。",
            "辛苦文场久，因缘戚里深。老迷新道路，贫卖旧园林。",
            "晴赏行闻水，宵棋坐见参。龟留闲去问，僧约偶来寻。",
            "望喜潜凭鹊，娱情愿有琴。此生如遂意，誓死报知音。",
            "上德怜孤直，唯公拔陆沉。丘山恩忽被，蝼蚁力难任。",
            "作鉴明同日，听言重若金。从兹更无限，翘足俟为霖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 和郑先辈谢秩闲居寓书所怀 ----------
    {
        "id": "liu-de-ren-115",
        "title": "和郑先辈谢秩闲居寓书所怀",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "西风日夜吹，万木共离披。近甸新晴后，高人得意时。",
            "暂闲心亦泰，论道面难欺。把笔还诗债，将琴当酒资。",
            "蓝衫悬竹桁，乌帽挂松枝。名占文章重，官归谏宪迟。",
            "生涯贫帝里，公议到台司。室冷沾苔藓，门清绝路岐。",
            "莫言邻白屋，即贺立丹墀。岂虑尘埃久，云霄故有期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 病中晨起即事寄场中往还 ----------
    {
        "id": "liu-de-ren-116",
        "title": "病中晨起即事寄场中往还",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "昨日离尘里，今朝懒已成。岂能为久隐，更欲泥浮名。",
            "虚牖晨光白，幽园晓气清。戴沙寻水去，披雾入林行。",
            "叠叶孤禽在，初阳半树明。桑麻新雨润，芦荻古波声。",
            "易向田家熟，元于世路生。病多三径塞，吟苦四邻惊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 悲老宫人 ----------
    {
        "id": "liu-de-ren-117",
        "title": "悲老宫人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "白发宫娃不解悲，满头犹自插花枝。",
            "曾缘玉貌君王宠，准拟人看似旧时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 村中闲步 ----------
    {
        "id": "liu-de-ren-118",
        "title": "村中闲步",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "闲共野人临野水，新秋高树挂清晖。",
            "不知尘里无穷事，白鸟双飞入翠微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 上巳日 ----------
    {
        "id": "liu-de-ren-119",
        "title": "上巳日",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "未敢分明赏物华，十年如见梦中花。",
            "游人过尽衡门掩，独自凭栏到日斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 省试日上崔侍郎四首 ----------
    {
        "id": "liu-de-ren-120",
        "title": "省试日上崔侍郎四首",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "衣上年年泪血痕，只将怀抱诉乾坤。",
            "如今主圣臣贤日，岂致人间一物冤。",
            "如病如痴二十秋，求名难得又难休。",
            "回看骨肉须堪耻，一著麻衣便白头。",
            "戚里称儒愧小才，礼闱公道此时开。",
            "他人何事虚相指，明主无私不是媒。",
            "方寸终朝似火然，为求白日上青天。",
            "自嗟辜负平生眼，不识春光二十年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 秋夜 ----------
    {
        "id": "liu-de-ren-121",
        "title": "秋夜",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "秋气满堂孤烛冷，清宵无寐忆山归。",
            "窗前月过三更后，细竹吟风似雨微。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 长门怨 ----------
    {
        "id": "liu-de-ren-122",
        "title": "长门怨",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "争得一人闻此怨，长门深夜有妍姝。",
            "早知雨露翻相误，只插荆钗嫁匹夫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 贾妇怨 ----------
    {
        "id": "liu-de-ren-123",
        "title": "贾妇怨",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "嫁与商人头欲白，未曾一日得双行。",
            "任君逐利轻江海，莫把风涛似妾轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 寄友人 ----------
    {
        "id": "liu-de-ren-124",
        "title": "寄友人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "风飒沉思眼忽开，尘埃污得是庸才。",
            "那堪更见巢松鹤，飞入青云不下来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 125. 晏起 ----------
    {
        "id": "liu-de-ren-125",
        "title": "晏起",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "日过辰时犹在梦，客来应笑也求名。",
            "浮生自得长高枕，不向人间与命争。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 126. 马上别单于刘评事（时太和公主还京，评事罢举起职） ----------
    {
        "id": "liu-de-ren-126",
        "title": "马上别单于刘评事（时太和公主还京，评事罢举起职）",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "庙谋宏远人难测，公主生还帝感深。",
            "天下底平须共喜，一时闲事莫惊心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 127. 赠从弟谷 ----------
    {
        "id": "liu-de-ren-127",
        "title": "赠从弟谷",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "此世荣枯岂足惊，相逢惟要眼长青。",
            "从来不爱三闾死，今日凭君莫独醒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 128. 别山居 ----------
    {
        "id": "liu-de-ren-128",
        "title": "别山居",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "万壑千岩景象开，登临未足又须回。",
            "凭师莫断松间路，秋月圆时弟子来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 129. 赠道人 ----------
    {
        "id": "liu-de-ren-129",
        "title": "赠道人",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "长在城中无定业，卖丹磨镜两途贫。",
            "三山来往寻常事，不省曾惊市井人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 130. 对月寄同志 ----------
    {
        "id": "liu-de-ren-130",
        "title": "对月寄同志",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "霜满中庭月在林，塞鸿频过又更深。",
            "支颐不语相思坐，料得君心似我心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 131. 忆鹤 ----------
    {
        "id": "liu-de-ren-131",
        "title": "忆鹤",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "白丝翎羽丹砂顶，晓度秋烟出翠微。",
            "来向孤松枝上立，见人吟苦却高飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 132. 云门寺 ----------
    {
        "id": "liu-de-ren-132",
        "title": "云门寺",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "上方僧又起，清磬出林初。吟苦晓灯暗，露零秋草疏。",
            "旧山多梦到，流水送愁馀。寄寺欲经岁，惭无亲故书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 133. 中秋宿邓逸人居 ----------
    {
        "id": "liu-de-ren-133",
        "title": "中秋宿邓逸人居",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "偶与山僧宿，吟诗坐到明。夜凉耽月色，秋渴漱泉声。",
            "涧木如竿耸，窗云作片生。白衣闲自贵，不揖汉公卿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 134. 句 ----------
    {
        "id": "liu-de-ren-134",
        "title": "句",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "外家虽是帝，当路且无亲。（《读书志》）",
            "白日只如哭，黄泉免恨无。（哭贾岛，以下《吟窗杂录》）",
            "身闲甘旨下，白发太平人。",
            "同游芳草寺，见示白云诗。（以下《海录碎事》）",
            "犹祈启金口，一为动文权。",
            "深山寺路千层石，竹杖棕鞋便可登。",
            "第五百四十六卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 135. 晚步 ----------
    {
        "id": "liu-de-ren-135",
        "title": "晚步",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "野步晚悠悠，山光澹早秋。远空沦日脚，多稼没人头。",
            "古木蝉齐噪，深塍水慢流。幽居回不近，秋策却堪愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 136. 村晚闲步 ----------
    {
        "id": "liu-de-ren-136",
        "title": "村晚闲步",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "缓步出居处，过原边雁行。夕阳投草木，远水映苍茫。",
            "野寺同蟾宿，云溪劚药尝。萧条霜景暮，极目尽堪伤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 137. 冬日题兴善寺崔律师院孤松 ----------
    {
        "id": "liu-de-ren-137",
        "title": "冬日题兴善寺崔律师院孤松",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "为此疏名路，频来访远公。孤标宜雪后，每见忆山中。",
            "静影生幽藓，寒声入迥空。何年植兹地，晓夕动清风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 138. 题新栽小松 ----------
    {
        "id": "liu-de-ren-138",
        "title": "题新栽小松",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "满庭萧飒皆凡木，岂得飕飗似石溪。雪夜枝柯疑画出，",
            "月中长短共人齐。未知何日干天及，恐到秋来被鹤栖。",
            "却向旧山寻得处，白云根蕟觅应迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 139. 栽松 ----------
    {
        "id": "liu-de-ren-139",
        "title": "栽松",
        "author": "刘得仁",
        "poet_id": "liu-de-ren",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "翠色凛空庭，披衣独绕行。取从山顶嶮，栽得道心生。",
            "未弱幽泉韵，焉论别木声。霜天残月在，转影入池清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]