# -*- coding: utf-8 -*-
"""
李昭象卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 喜杜荀鹤及第 ----------
    {
        "id": "li-zhao-xiang-1",
        "title": "喜杜荀鹤及第",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "深岩贫复病，榜到见君名。贫病浑如失，山川顿觉清。",
            "一春新酒兴，四海旧诗声。日使能吟者，西来步步轻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赴举出山留寄山居郑参军 ----------
    {
        "id": "li-zhao-xiang-2",
        "title": "赴举出山留寄山居郑参军",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "还如费冠卿，向此振高名。肯羡鱼须美，长夸鹤氅轻。",
            "理琴寒指倦，试药黑髭生。时泰难云卧，随看急诏行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 题顾正字谿居 ----------
    {
        "id": "li-zhao-xiang-3",
        "title": "题顾正字谿居",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "高敞吟轩近钓湾，尘中来似出人间。若教明月休生桂，",
            "应得危时共掩关。春酒夜棋难放客，短篱疏竹不遮山。",
            "莫夸恬淡胜荣禄，雁引行高未许闲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 寄献山中顾公员外 ----------
    {
        "id": "li-zhao-xiang-4",
        "title": "寄献山中顾公员外",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "抽却朝簪著钓蓑，近来声迹转巍峨。祥麟避网虽山野，",
            "丹凤衔书即薜萝。乍隐文章情更逸，久闲经济术翻多。",
            "深惭未副吹嘘力，竟困风埃争奈何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 山中寄崔谏议 ----------
    {
        "id": "li-zhao-xiang-5",
        "title": "山中寄崔谏议",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "半生猿鸟共山居，吟月吟风两鬓疏。新句未尝忘教化，",
            "上才争忍不吹嘘。全家欲去干戈后，大国中兴礼乐初。",
            "从此升腾休说命，只希公道数封书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 学仙词寄顾云 ----------
    {
        "id": "li-zhao-xiang-6",
        "title": "学仙词寄顾云",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "记得初传九转方，碧云峰下祝虚皇。丹砂未熟心徒切，",
            "白日难留鬓欲苍。无路洞天寻穆满，有时人世美刘郎。",
            "仙人恩重何由报，焚尽星坛午夜香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 寄尉迟侍御 ----------
    {
        "id": "li-zhao-xiang-7",
        "title": "寄尉迟侍御",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "我眠青嶂弄澄潭，君戴貂蝉白玉篸。",
            "应向谢公楼上望，九华山色在西南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 招西洞道者 ----------
    {
        "id": "li-zhao-xiang-8",
        "title": "招西洞道者",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "危峰抹黛夹晴川，树簇红英草碧烟。",
            "樵客云僧两无事，此中堪去觅灵仙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 句 ----------
    {
        "id": "li-zhao-xiang-9",
        "title": "句",
        "author": "李昭象",
        "poet_id": "li-zhao-xiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "投文得仕而今少，佩印还家古所荣。（送周繇之建德。",
            "《唐诗纪事》）",
            "第六百九十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]