# -*- coding: utf-8 -*-
"""
朱长文卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 宿新安江深渡馆寄郑州王使君 ----------
    {
        "id": "zhu-zhang-wen-1",
        "title": "宿新安江深渡馆寄郑州王使君",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "霜飞十月中，摇落众山空。孤馆闭寒木，大江生夜风。",
            "赋诗忙有意，沈约在关东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 春眺扬州西上岗寄徐员外 ----------
    {
        "id": "zhu-zhang-wen-2",
        "title": "春眺扬州西上岗寄徐员外",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "芜城西眺极苍流，漠漠春烟间曙楼。瓜步早潮吞建业，",
            "蒜山晴雪照扬州。隋家故事不能问，鹤在仙池期我游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 送李司直归浙东幕兼寄鲍将军（一作朱湾诗） ----------
    {
        "id": "zhu-zhang-wen-3",
        "title": "送李司直归浙东幕兼寄鲍将军（一作朱湾诗）",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "翩翩书记早曾闻，二十年来愿见君。今日相逢悲白发，",
            "同时几许在青云。人从北固山边去，水到西陵渡口分。",
            "会作王门曳裾客，为余前谢鲍将军。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 望中有怀 ----------
    {
        "id": "zhu-zhang-wen-4",
        "title": "望中有怀",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "龙向洞中衔雨出，鸟从花里带香飞。",
            "白云断处见明月，黄叶落时闻捣衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 题虎丘山西寺 ----------
    {
        "id": "zhu-zhang-wen-5",
        "title": "题虎丘山西寺",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "王氏家山昔在兹，陆机为赋陆云诗。",
            "青莲香匝东西宇，日月与僧无尽时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 吴兴送梁补阙归朝赋得荻花 ----------
    {
        "id": "zhu-zhang-wen-6",
        "title": "吴兴送梁补阙归朝赋得荻花",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "柳家汀洲孟冬月，云寒水清荻花发。",
            "一枝持赠朝天人，愿比蓬莱殿前雪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 句 ----------
    {
        "id": "zhu-zhang-wen-7",
        "title": "句",
        "author": "朱长文",
        "poet_id": "zhu-zhang-wen",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "夜静忽疑身是梦，更闻寒雨滴芭蕉。",
            "（《宿僧房》，见《诗式》）。",
            "第二百七十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]