# -*- coding: utf-8 -*-
"""
杨凌卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 21 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 琴曲歌辞·明妃怨 ----------
    {
        "id": "yang-ling-1",
        "title": "琴曲歌辞·明妃怨",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "汉国明妃去不还，马驼弦管向阴山。",
            "匣中纵有菱花镜，羞对单于照旧颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉酬韦滁州寄示 ----------
    {
        "id": "yang-ling-2",
        "title": "奉酬韦滁州寄示",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "淮扬为郡暇，坐惜流芳歇。散怀累榭风，清暑澄潭月。",
            "陪燕辞三楚，戒途绵百越。非当远别离，雅奏何由发。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 梅里旅夕 ----------
    {
        "id": "yang-ling-3",
        "title": "梅里旅夕",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "沧洲东望路，旅棹怆羁游。枫浦蝉随岸，沙汀鸥转流。",
            "露天星上月，水国夜生秋。谁忍持相忆，南归一叶舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 钟陵雪夜酬友人 ----------
    {
        "id": "yang-ling-4",
        "title": "钟陵雪夜酬友人",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "穷腊催年急，阳春怯和歌。残灯闪壁尽，夜雪透窗多。",
            "归路山川险，游人梦寐过。龙洲不可泊，岁晚足惊波。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 润州水楼 ----------
    {
        "id": "yang-ling-5",
        "title": "润州水楼",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "归心不可留，雪桂一丛秋。叶雨空江月，萤飞白露洲。",
            "野蝉依独树，水郭带孤楼。遥望山川路，相思万里游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 江上秋月 ----------
    {
        "id": "yang-ling-6",
        "title": "江上秋月",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "陇雁送乡心，羁情属岁阴。惊秋黄叶遍，愁暮碧云深。",
            "月色吴江上，风声楚木林。交亲几重别，归梦并愁侵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 阁前双槿 ----------
    {
        "id": "yang-ling-7",
        "title": "阁前双槿",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "群玉开双槿，丹荣对绛纱。含烟疑出火，隔雨怪舒霞。",
            "向晚争辞蕊，迎朝斗发花。非关后桃李，为欲继年华。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 小苑春望宫池柳色 ----------
    {
        "id": "yang-ling-8",
        "title": "小苑春望宫池柳色",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "上苑闲游早，东风柳色轻。储胥遥掩映，池水隔微明。",
            "春至条偏弱，寒馀叶未成。和烟变浓淡，转日异阴晴。",
            "不独芳菲好，还因雨露荣。行人望攀折，远翠暮愁生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送客往睦州 ----------
    {
        "id": "yang-ling-9",
        "title": "送客往睦州",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "水阔尽南天，孤舟去渺然。惊秋路傍客，日暮数声蝉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送客之蜀 ----------
    {
        "id": "yang-ling-10",
        "title": "送客之蜀",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "西蜀三千里，巴南水一方。晓云天际断，夜月峡中长。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 剡溪看花 ----------
    {
        "id": "yang-ling-11",
        "title": "剡溪看花",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "花落千回舞，莺声百啭歌。还同异方乐，不奈客愁多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 江中风 ----------
    {
        "id": "yang-ling-12",
        "title": "江中风",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "白浪暗江中，南泠路不通。高樯帆自满，出浦莫呼风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 咏破扇 ----------
    {
        "id": "yang-ling-13",
        "title": "咏破扇",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "粉落空床弃，尘生故箧留。先来无一半，情断不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 贾客愁 ----------
    {
        "id": "yang-ling-14",
        "title": "贾客愁",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "山水路悠悠，逢滩即殢留。西江风未便，何日到荆州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 即事寄人 ----------
    {
        "id": "yang-ling-15",
        "title": "即事寄人",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "中禁鸣钟日欲高，北窗欹枕望频搔。",
            "相思寂寞青苔合，唯有春风啼伯劳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 早春雪中 ----------
    {
        "id": "yang-ling-16",
        "title": "早春雪中",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "新年雨雪少晴时，屡失寻梅看柳期。",
            "乡信忆随回雁早，江春寒带故阴迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 北行留别 ----------
    {
        "id": "yang-ling-17",
        "title": "北行留别",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "日日山川烽火频，山河重起旧烟尘。",
            "一生孤负龙泉剑，羞把诗书问故人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 秋原野望 ----------
    {
        "id": "yang-ling-18",
        "title": "秋原野望",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "客雁秋来次第逢，家书频寄两三封。",
            "夕阳天外云归尽，乱见青山无数峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 春霁花萼楼南闻宫莺 ----------
    {
        "id": "yang-ling-19",
        "title": "春霁花萼楼南闻宫莺",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "祥烟瑞气晓来轻，柳变花开共作晴。",
            "黄鸟远啼鳷鹊观，春风流出凤凰城。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 明妃怨 ----------
    {
        "id": "yang-ling-20",
        "title": "明妃怨",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "汉国明妃去不还，马驮弦管向阴山。",
            "匣中纵有菱花镜，羞对单于照旧颜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 句 ----------
    {
        "id": "yang-ling-21",
        "title": "句",
        "author": "杨凌",
        "poet_id": "yang-ling",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "南园桃李花落尽，春风寂寞摇空枝。（《诗式》）",
            "第二百九十二卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]