# -*- coding: utf-8 -*-
"""
王无竞卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·铜雀台 ----------
    {
        "id": "wang-wu-jing-1",
        "title": "相和歌辞·铜雀台",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "北登铜雀上，西望青松郭。繐帐空苍苍，陵田纷漠漠。",
            "平生事已变，歌吹宛犹昨。长袖拂玉尘，遗情结罗幕。",
            "妾怨在朝露，君恩岂中薄。高台奏曲终，曲终泪横落。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·凤台曲 ----------
    {
        "id": "wang-wu-jing-2",
        "title": "相和歌辞·凤台曲",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷96》",
        "verse": [
            "凤台何逶迤，嬴女管参差。一旦彩云至，身去无还期。",
            "遗曲此台上，世人多学吹。一吹一落泪，至今怜玉姿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 和宋之问下山歌 ----------
    {
        "id": "wang-wu-jing-3",
        "title": "和宋之问下山歌",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "日云暮兮下嵩山，路连绵兮树石间。",
            "出谷口兮见明月，心裴回兮不能还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 北使长城 ----------
    {
        "id": "wang-wu-jing-4",
        "title": "北使长城",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "秦世筑长城，长城无极已。暴兵四十万，兴工九千里。",
            "死人如乱麻，白骨相撑委。殚弊未云悟，穷毒岂知止。",
            "胡尘未北灭，楚兵遽东起。六国复嚣嚣，两龙斗觺觺。",
            "卯金竟握谶，反璧俄沦祀。仁义寝邦国，狙暴行终始。",
            "一旦咸阳宫，翻为汉朝市。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 凤台曲 ----------
    {
        "id": "wang-wu-jing-5",
        "title": "凤台曲",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "凤台何逶迤，嬴女管参差。一旦彩云至，身去无还期。",
            "遗曲此台上，世人多学吹。一吹一落泪，至今怜玉姿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 铜雀台 ----------
    {
        "id": "wang-wu-jing-6",
        "title": "铜雀台",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "北登铜雀上，西望青松郭。繐帐空苍苍，陵田纷漠漠。",
            "平生事已变，歌吹宛犹昨。长袖拂玉尘，遗情结罗幕。",
            "妾怨在朝露，君恩岂中薄。高台奏曲终，曲终泪横落。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 巫山（一作宋之问诗） ----------
    {
        "id": "wang-wu-jing-7",
        "title": "巫山（一作宋之问诗）",
        "author": "王无竞",
        "poet_id": "wang-wu-jing",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "神女向高唐，巫山下夕阳。裴回行作雨，婉娈逐荆王。",
            "电影江前落，雷声峡外长。朝云无处所，台馆晓苍苍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]