# -*- coding: utf-8 -*-
"""
姚崇卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 8 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 郊庙歌辞·享龙池乐章·第一章 ----------
    {
        "id": "yao-chong-1",
        "title": "郊庙歌辞·享龙池乐章·第一章",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "恭闻帝里生灵沼，应报明君鼎业新。既协翠泉光宝命，",
            "还符白水出真人。此时舜海潜龙跃，此地尧河带马巡。",
            "独有前池一小雁，叨承旧惠入天津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 奉和圣制夏日游石淙山 ----------
    {
        "id": "yao-chong-2",
        "title": "奉和圣制夏日游石淙山",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "二室三涂光地险，均霜揆日处天中。石泉石镜恒留月，",
            "山鸟山花竞逐风。周王久谢瑶池赏，汉主悬惭玉树宫。",
            "别有祥烟伴佳气，能随轻辇共葱葱。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 故洛阳城侍宴应制 ----------
    {
        "id": "yao-chong-3",
        "title": "故洛阳城侍宴应制",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "游豫停仙跸，登临对晚晴。川凫连倒影，岩鸟应虚声。",
            "野奏风成曲，山居云作缨。今朝丘壑上，高兴小蓬瀛。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 春日洛阳城侍宴 ----------
    {
        "id": "yao-chong-4",
        "title": "春日洛阳城侍宴",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "南山开宝历，北渚对芳蹊。的历风梅度，参差露草低。",
            "尧樽临上席，舜乐下前溪。任重由来醉，乘酣志转迷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 秋夜望月 ----------
    {
        "id": "yao-chong-5",
        "title": "秋夜望月",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "明月有馀鉴，羁人殊未安。桂含秋树晚，波入夜池寒。",
            "灼灼云枝净，光光草露团。所思迷所在，长望独长叹。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 夜渡江（一作柳中庸诗） ----------
    {
        "id": "yao-chong-6",
        "title": "夜渡江（一作柳中庸诗）",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "夜渚带浮烟，苍茫晦远天。舟轻不觉动，缆急始知牵。",
            "听草遥寻岸，闻香暗识莲。唯看孤帆影，常似客心悬。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 奉和圣制龙池篇 ----------
    {
        "id": "yao-chong-7",
        "title": "奉和圣制龙池篇",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "恭闻帝里生灵沼，应报明君鼎业新。既协翠泉光宝命，",
            "还符白水出真人。此时舜海潜龙跃，此地尧河带马巡。",
            "独有前池一小雁，叨承旧惠入天津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 句 ----------
    {
        "id": "yao-chong-8",
        "title": "句",
        "author": "姚崇",
        "poet_id": "yao-chong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "扇掩将雏曲，钗承堕马鬟。（见《海录碎事》，",
            "又见后张昌宗太平公主山亭侍宴诗）",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]