# -*- coding: utf-8 -*-
"""
陈叔达卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 9 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 早春桂林殿应诏 ----------
    {
        "id": "chen-shu-da-1",
        "title": "早春桂林殿应诏",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "金铺照春色，玉律动年华。朱楼云似盖，丹桂雪如花。",
            "水岸衔阶转，风条出柳斜。轻舆临太液，湛露酌流霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 后渚置酒 ----------
    {
        "id": "chen-shu-da-2",
        "title": "后渚置酒",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "大渚初惊夜，中流沸鼓鼙。寒沙满曲浦，夕雾上邪溪。",
            "岸广凫飞急，云深雁度低。严关犹未遂，此夕待晨鸡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 听邻人琵琶 ----------
    {
        "id": "chen-shu-da-3",
        "title": "听邻人琵琶",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "本是龙门桐，因妍入汉宫。香缘罗袖里，声逐朱弦中。",
            "虽有相思韵，翻将入塞同。关山临却月，花蕊散回风。",
            "为将金谷引，添令曲未终。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 州城西园入斋祠社 ----------
    {
        "id": "chen-shu-da-4",
        "title": "州城西园入斋祠社",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "升坛预洁祀，诘早肃分司。达气风霜积，登光日色迟。",
            "农教先八政，阳和秩四时。祈年服垂冕，告币动褰帷。",
            "瘗地尊馀奠，人天庶有资。椒兰卒清酌，簠簋彻香萁。",
            "折俎分归胙，充庭降受釐。方凭知礼节，况奉化雍熙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 春首 ----------
    {
        "id": "chen-shu-da-5",
        "title": "春首",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "雪花联玉树，冰彩散瑶池。翔禽遥出没，积翠远参差。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 初年 ----------
    {
        "id": "chen-shu-da-6",
        "title": "初年",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "和风起天路，严气消冰井。索索枝未柔，厌厌漏犹永。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 咏菊 ----------
    {
        "id": "chen-shu-da-7",
        "title": "咏菊",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "霜间开紫蒂，露下发金英。但令逢采摘，宁辞独晚荣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 自君之出矣（一作贾冯吉诗） ----------
    {
        "id": "chen-shu-da-8",
        "title": "自君之出矣（一作贾冯吉诗）",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "自君之出矣，红颜转憔悴。思君如明烛，煎心且衔泪。",
            "自君之出矣，明镜罢红妆。思君如夜烛，煎泪几千行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 太庙祼地歌辞 ----------
    {
        "id": "chen-shu-da-9",
        "title": "太庙祼地歌辞",
        "author": "陈叔达",
        "poet_id": "chen-shu-da",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "清庙既祼，郁鬯推礼。大哉孝思，严恭祖祢。",
            "龙衮以祭，鸾刀思启。发德朱弦，升歌丹陛。",
            "遥享粢盛，堂斟况齐。降福穰穰，来仪济济。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]