# -*- coding: utf-8 -*-
"""
崔国辅卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 52 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·对酒 ----------
    {
        "id": "cui-guo-fu-1",
        "title": "相和歌辞·对酒",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "行行日将夕，荒村古冢无人迹。朦胧荆棘一鸟飞，",
            "屡唱提壶酤酒吃。古人不达酒不足，遗恨精灵传此曲。",
            "寄言当代诸少年，平生且尽杯中渌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 相和歌辞·王昭君 ----------
    {
        "id": "cui-guo-fu-2",
        "title": "相和歌辞·王昭君",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "汉使南还尽，胡中妾独存。紫台绵望绝，秋草不堪论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 相和歌辞·王昭君 ----------
    {
        "id": "cui-guo-fu-3",
        "title": "相和歌辞·王昭君",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "一回望月一回悲，望月月移人不移。",
            "何时得见汉朝使，为妾传书斩画师。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 相和歌辞·怨诗二首 ----------
    {
        "id": "cui-guo-fu-4",
        "title": "相和歌辞·怨诗二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "楼前桃李疏，池上芙蓉落。织锦犹未成，虫声入罗幕。",
            "妾有罗衣裳，秦王在时作。为舞春风多，秋来不堪著。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 相和歌辞·婕妤怨 ----------
    {
        "id": "cui-guo-fu-5",
        "title": "相和歌辞·婕妤怨",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "长信宫中草，年年愁处生。故侵珠履迹，不使玉阶行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 相和歌辞·子夜冬歌 ----------
    {
        "id": "cui-guo-fu-6",
        "title": "相和歌辞·子夜冬歌",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "寂寥抱冬心，裁罗又褧褧。夜久频挑灯，霜寒剪刀冷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 相和歌辞·襄阳曲二首 ----------
    {
        "id": "cui-guo-fu-7",
        "title": "相和歌辞·襄阳曲二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "蕙草娇红萼，时光舞碧鸡。城中美年少，相见白铜鞮。",
            "少年襄阳地，来往襄阳城。城中轻薄子，知妾解秦筝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 相和歌辞·采莲曲 ----------
    {
        "id": "cui-guo-fu-8",
        "title": "相和歌辞·采莲曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "玉溆花红发，金塘水碧流。相逢畏相失，并著采莲舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 舞曲歌辞·白纻辞二首 ----------
    {
        "id": "cui-guo-fu-9",
        "title": "舞曲歌辞·白纻辞二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "洛阳梨花落如霰，河阳桃叶生复齐。",
            "坐恐玉楼春欲尽，红绵粉絮裛妆啼。",
            "董贤女弟在椒风，窈窕繁华贵后宫。",
            "璧带金釭皆翡翠，一朝零落变成空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 杂曲歌辞·妾薄命 ----------
    {
        "id": "cui-guo-fu-10",
        "title": "杂曲歌辞·妾薄命",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "虽入秦帝宫，不上秦帝床。夜夜玉窗里，与他卷罗裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 杂曲歌辞·长乐少年行 ----------
    {
        "id": "cui-guo-fu-11",
        "title": "杂曲歌辞·长乐少年行",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "遗却珊瑚鞭，白马骄不行。章台折杨柳，春草路旁情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 杂曲歌辞·丽人曲 ----------
    {
        "id": "cui-guo-fu-12",
        "title": "杂曲歌辞·丽人曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "红颜称绝代，欲并真无侣。独有镜中人，由来自相许。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 杂曲歌辞·今别离 ----------
    {
        "id": "cui-guo-fu-13",
        "title": "杂曲歌辞·今别离",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "送别未能旋，相望连水口。船行欲映洲，几度急摇手。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 杂曲歌辞·小长干曲 ----------
    {
        "id": "cui-guo-fu-14",
        "title": "杂曲歌辞·小长干曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "月暗送湖风，相寻路不通。菱歌唱不辍，知在此塘中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 杂曲歌辞·王孙游 ----------
    {
        "id": "cui-guo-fu-15",
        "title": "杂曲歌辞·王孙游",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "自与王孙别，频看黄鸟飞。应由春草误，著处不成归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 从军行 ----------
    {
        "id": "cui-guo-fu-16",
        "title": "从军行",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "塞北胡霜下，营州索兵救。夜里偷道行，将军马亦瘦。",
            "刀光照塞月，阵色明如昼。传闻贼满山，已共前锋斗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 杂诗 ----------
    {
        "id": "cui-guo-fu-17",
        "title": "杂诗",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "逢著平乐儿，论交鞍马前。与酤一斗酒，恰用十千钱。",
            "后余在关内，作事多迍邅。何肯相救援，徒闻宝剑篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 古意 ----------
    {
        "id": "cui-guo-fu-18",
        "title": "古意",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "红荷楚水曲，彪炳烁晨霞。未得两回摘，秋风吹却花。",
            "时芳不待妾，玉珮无处夸。悔不盛年时，嫁与青楼家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 宿法华寺 ----------
    {
        "id": "cui-guo-fu-19",
        "title": "宿法华寺",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "松雨时复滴，寺门清且凉。此心竟谁证，回憩支公床。",
            "壁画感灵迹，龛经传异香。独游寄象外，忽忽归南昌。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 题预章馆 ----------
    {
        "id": "cui-guo-fu-20",
        "title": "题预章馆",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "杨柳映春江，江南转佳丽。吴门绿波里，越国青山际。",
            "游宦常往来，津亭暂临憩。驿前苍石没，浦外湖沙细。",
            "向晚宴且久，孤舟冏然逝。云留西北客，气歇东南帝。",
            "独有萋萋心，谁知怨芳岁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 石头滩作 ----------
    {
        "id": "cui-guo-fu-21",
        "title": "石头滩作",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "怅矣秋风时，余临石头濑。因高见远境，尽此数州内。",
            "羽山数点青，海岸杂光碎。离离树木少，漭漭湖波大。",
            "日暮千里帆，南飞落天外。须臾遂入夜，楚色有微霭。",
            "寻远迹已穷，遗荣事多昧。一身犹未理，安得济时代。",
            "且泛朝夕潮，荷衣蕙为带。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 漂母岸 ----------
    {
        "id": "cui-guo-fu-22",
        "title": "漂母岸",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "泗水入淮处，南边古岸存。秦时有漂母，于此饭王孙。",
            "王孙初未遇，寄食何足论。后为楚王来，黄金答母恩。",
            "事迹遗在此，空伤千载魂。茫茫水中渚，上有一孤墩。",
            "遥望不可到，苍苍烟树昏。几年崩冢色，每日落潮痕。",
            "古地多堙圮，时哉不敢言。向夕泪沾裳，遂宿芦洲村。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 对酒吟 ----------
    {
        "id": "cui-guo-fu-23",
        "title": "对酒吟",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "行行日将夕，荒村古冢无人迹。蒙笼荆棘一鸟吟，",
            "屡唱提壶沽酒吃。古人不达酒不足，遗恨精灵传此曲。",
            "寄言世上诸少年，平生且尽杯中醁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 奉和华清宫观行香应制 ----------
    {
        "id": "cui-guo-fu-24",
        "title": "奉和华清宫观行香应制",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "天子蕊珠宫，楼台碧落通。豫游皆汗漫，斋处即崆峒。",
            "云物三光里，君臣一气中。道言何所说，宝历自无穷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 七夕 ----------
    {
        "id": "cui-guo-fu-25",
        "title": "七夕",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "太守仙潢族，含情七夕多。扇风生玉漏，置水写银河。",
            "阁下陈书籍，闺中曝绮罗。遥思汉武帝，青鸟几时过。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 宿范浦 ----------
    {
        "id": "cui-guo-fu-26",
        "title": "宿范浦",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "月暗潮又落，西陵渡暂停。村烟和海雾，舟火乱江星。",
            "路转定山绕，塘连范浦横。鸱夷近何去，空山临沧溟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 奉和圣制上巳祓禊应制 ----------
    {
        "id": "cui-guo-fu-27",
        "title": "奉和圣制上巳祓禊应制",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "元巳秦中节，吾君灞上游。鸣銮通禁苑，别馆绕芳洲。",
            "鹓鹭千官列，鱼龙百戏浮。桃花春欲尽，谷雨夜来收。",
            "庆向尧樽祝，欢从楚棹讴。逸诗何足对，窅作掩东周。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 九日侍宴应制 ----------
    {
        "id": "cui-guo-fu-28",
        "title": "九日侍宴应制",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "运偶千年圣，时传九日神。尧樽列钟鼓，汉阙辟钩陈。",
            "金箓三清降，琼筵五老巡。始惊兰佩出，复咏柏梁新。",
            "云雁楼前晚，霜花酒里春。欢娱无限极，书剑太平人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 杭州北郭戴氏荷池送侯愉 ----------
    {
        "id": "cui-guo-fu-29",
        "title": "杭州北郭戴氏荷池送侯愉",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "秋近万物肃，况当临水时。折花赠归客，离绪断荷丝。",
            "谁谓江国永，故人感在兹。道存过北郭，情极望东菑。",
            "乔木故园意，鸣蝉穷巷悲。扁舟竟何待，中路每迟迟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 怨词二首 ----------
    {
        "id": "cui-guo-fu-30",
        "title": "怨词二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "妾有罗衣裳，秦王在时作。为舞春风多，秋来不堪著。",
            "楼头桃李疏，池上芙蓉落。织锦犹未成，蛩声入罗幕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 古意二首 ----------
    {
        "id": "cui-guo-fu-31",
        "title": "古意二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "玉笼薰绣裳，著罢眠洞房。不能春风里，吹却兰麝香。",
            "种棘遮蘼芜，畏人来采杀。比至狂夫还，看看几花发。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 襄阳曲二首 ----------
    {
        "id": "cui-guo-fu-32",
        "title": "襄阳曲二首",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "蕙草娇红萼，时光舞碧鸡。城中美年少，相见白铜鞮。",
            "少年襄阳地，来往襄阳城。城中轻薄子，知妾解秦筝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 魏宫词 ----------
    {
        "id": "cui-guo-fu-33",
        "title": "魏宫词",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "朝日照红妆，拟上铜雀台。画眉犹未了，魏帝使人催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 长信草（一作长信宫，一作婕妤怨） ----------
    {
        "id": "cui-guo-fu-34",
        "title": "长信草（一作长信宫，一作婕妤怨）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "长信宫中草，年年愁处生。故侵珠履迹，不使玉阶行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 长乐少年行（一作古意） ----------
    {
        "id": "cui-guo-fu-35",
        "title": "长乐少年行（一作古意）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "遗却珊瑚鞭，白马骄不行。章台折杨柳，春日路傍情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 湖南曲（一作古意） ----------
    {
        "id": "cui-guo-fu-36",
        "title": "湖南曲（一作古意）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "湖南送君去，湖北送君归。湖里鸳鸯鸟，双双他自飞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 中流曲（一作古意） ----------
    {
        "id": "cui-guo-fu-37",
        "title": "中流曲（一作古意）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "归时日尚早，更欲向芳洲。渡口水流急，回船不自由。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 王孙游 ----------
    {
        "id": "cui-guo-fu-38",
        "title": "王孙游",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "自与王孙别，频看黄鸟飞。应由春草误，著处不成归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 采莲曲 ----------
    {
        "id": "cui-guo-fu-39",
        "title": "采莲曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "玉溆花争发，金塘水乱流。相逢畏相失，并著采莲舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 子夜冬歌 ----------
    {
        "id": "cui-guo-fu-40",
        "title": "子夜冬歌",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "寂寥抱冬心，裁罗又褧褧。夜久频挑灯，霜寒剪刀冷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 丽人曲 ----------
    {
        "id": "cui-guo-fu-41",
        "title": "丽人曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "红颜称绝代，欲并真无侣。独有镜中人，由来自相许。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 小长干曲 ----------
    {
        "id": "cui-guo-fu-42",
        "title": "小长干曲",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "月暗送潮风，相寻路不通。菱歌唱不彻，知在此塘中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 王昭君（一作吟叹曲） ----------
    {
        "id": "cui-guo-fu-43",
        "title": "王昭君（一作吟叹曲）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "汉使南还尽，胡中妾独存。紫台绵望绝，秋草不堪论。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 秦女卷衣（一作妾薄命） ----------
    {
        "id": "cui-guo-fu-44",
        "title": "秦女卷衣（一作妾薄命）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "虽入秦帝宫，不上秦帝床。夜夜玉窗里，与他卷衣裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 今别离 ----------
    {
        "id": "cui-guo-fu-45",
        "title": "今别离",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "送别未能旋，相望连水口。船行欲映洲，几度急摇手。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 卫艳词 ----------
    {
        "id": "cui-guo-fu-46",
        "title": "卫艳词",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "淇上桑叶青，青楼含白日。比时遥望君，车马城中出。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 渭水西别李仑 ----------
    {
        "id": "cui-guo-fu-47",
        "title": "渭水西别李仑",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "陇右长亭堠，山阴古塞秋。不知呜咽水，何事向西流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 古意 ----------
    {
        "id": "cui-guo-fu-48",
        "title": "古意",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "净扫黄金阶，飞霜皎如雪。下帘弹箜篌，不忍见秋月。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 送韩十四被鲁王推递往济南府 ----------
    {
        "id": "cui-guo-fu-49",
        "title": "送韩十四被鲁王推递往济南府",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "西候情何极，南冠怨有馀。梁王虽好事，不察狱中书。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 白纻辞二首（前首一作《香风词》） ----------
    {
        "id": "cui-guo-fu-50",
        "title": "白纻辞二首（前首一作《香风词》）",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "洛阳梨花落如霰，河阳桃叶生复齐。",
            "坐惜玉楼春欲尽，红绵粉絮裛妆啼。",
            "董贤女弟在椒风，窈窕繁华贵后宫。",
            "璧带金釭皆翡翠，一朝零落变成空。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 九日 ----------
    {
        "id": "cui-guo-fu-51",
        "title": "九日",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "江边枫落菊花黄，少长登高一望乡。",
            "九日陶家虽载酒，三年楚客已沾裳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 王昭君 ----------
    {
        "id": "cui-guo-fu-52",
        "title": "王昭君",
        "author": "崔国辅",
        "poet_id": "cui-guo-fu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "一回望月一回悲，望月月移人不移。",
            "何时得见汉朝使，为妾传书斩画师。",
            "第一百二十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]