# -*- coding: utf-8 -*-
"""
廖融卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 7 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 谢翁宏以诗百篇见示 ----------
    {
        "id": "liao-rong-1",
        "title": "谢翁宏以诗百篇见示",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "高奇一百篇，造化见工全。积思游沧海，冥搜入洞天。",
            "神珠迷罔象，端玉匪雕镌。休叹不得力，离骚千古传。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 赠天台逸人 ----------
    {
        "id": "liao-rong-2",
        "title": "赠天台逸人",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "移桧托禅子，携家上赤城。拂琴天籁寂，欹枕海涛生。",
            "云白寒峰晚，鸟歌春谷晴。又闻求桂楫，载月十洲行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 古桧 ----------
    {
        "id": "liao-rong-3",
        "title": "古桧",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "何人见植初，老树梵王居。山鬼暗栖托，樵夫难破除。",
            "声高秋汉迥，影倒月潭虚。尽日无僧倚，清风长有馀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 题伍彬屋壁 ----------
    {
        "id": "liao-rong-4",
        "title": "题伍彬屋壁",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "圆塘绿水平，鱼跃紫莼生。要路贫无力，深村老退耕。",
            "犊随原草远，蛙傍堑篱鸣。拨棹茶川去，初逢谷雨晴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 梦仙谣 ----------
    {
        "id": "liao-rong-5",
        "title": "梦仙谣",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "琪木扶疏系辟邪，麻姑夜宴紫皇家。银河旌节摇波影，",
            "珠阁笙箫吸月华。翠凤引游三岛路，赤龙齐驾五云车。",
            "星稀犹倚虹桥立，拟就张骞搭汉槎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 退宫妓 ----------
    {
        "id": "liao-rong-6",
        "title": "退宫妓",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "神仙风格本难俦，曾从前皇翠辇游。红踯躅繁金殿暖，",
            "碧芙蓉笑水宫秋。宝筝钿剥阴尘覆，锦帐香消画烛幽。",
            "一旦色衰归故里，月明犹梦按梁州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 句 ----------
    {
        "id": "liao-rong-7",
        "title": "句",
        "author": "廖融",
        "poet_id": "liao-rong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "圭灶先知晓，盆池别见天，",
            "古寺寻僧饭，寒岩衣鹿裘。",
            "云穿捣药屋，雪压钓鱼舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]