# -*- coding: utf-8 -*-
"""
蒋吉卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 15 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 石城 ----------
    {
        "id": "jiang-ji-1",
        "title": "石城",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "系缆石城下，恣吟怀暂开。江人桡艇子，将谓莫愁来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 汉东道中 ----------
    {
        "id": "jiang-ji-2",
        "title": "汉东道中",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "九十九冈遥，天寒雪未消。羸童牵瘦马，不敢过危桥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 高溪有怀 ----------
    {
        "id": "jiang-ji-3",
        "title": "高溪有怀",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "驻马高溪侧，旅人千里情。雁山山下水，还作此泉声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 寄进士贾希 ----------
    {
        "id": "jiang-ji-4",
        "title": "寄进士贾希",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "恨苦泪不落，耿然东北心。空囊与瘦马，羁绁意应深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 出塞 ----------
    {
        "id": "jiang-ji-5",
        "title": "出塞",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "瘦马羸童行背秦，暮鸦撩乱入残云。",
            "北风吹起寒营角，直至榆关人尽闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 旅泊 ----------
    {
        "id": "jiang-ji-6",
        "title": "旅泊",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "霜月正高鹦鹉洲，美人清唱发红楼。",
            "乡心暗逐秋江水，直到吴山脚下流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 次青云驿 ----------
    {
        "id": "jiang-ji-7",
        "title": "次青云驿",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "马转栎林山鸟飞，商溪流水背残晖。",
            "行人几在青云路，底事风尘犹满衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 大庾驿有怀 ----------
    {
        "id": "jiang-ji-8",
        "title": "大庾驿有怀",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "一囊书重百馀斤，邮吏宁知去计贫。",
            "莫讶偏吟望乡句，明朝便见岭南人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 题商山修路僧院 ----------
    {
        "id": "jiang-ji-9",
        "title": "题商山修路僧院",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "此地修行山几枯，草堂生计只瓶盂。",
            "支郎既解除艰险，试看人心平得无。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 题长安僧院 ----------
    {
        "id": "jiang-ji-10",
        "title": "题长安僧院",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "出门争走九衢尘，总是浮生不了身。",
            "惟有水田衣下客，大家忙处作闲人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 次商於感旧寄卢中丞 ----------
    {
        "id": "jiang-ji-11",
        "title": "次商於感旧寄卢中丞",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "昔年簪组隘丘门，今日旌幢一院存。",
            "何事商於泪如雨，小儒偏受陆家恩。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 樵翁 ----------
    {
        "id": "jiang-ji-12",
        "title": "樵翁",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "独入深山信脚行，惯当貙虎不曾惊。",
            "路傍花发无心看，惟见枯枝刮眼明。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 四老庙 ----------
    {
        "id": "jiang-ji-13",
        "title": "四老庙",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "无端舍钓学干名，不得溪山养性情。",
            "自省此身非达者，今朝羞拜四先生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 昭君冢 ----------
    {
        "id": "jiang-ji-14",
        "title": "昭君冢",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "曾为汉帝眼中人，今作狂胡陌上尘。",
            "身死不知多少载，冢花犹带洛阳春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 闻歌竹枝 ----------
    {
        "id": "jiang-ji-15",
        "title": "闻歌竹枝",
        "author": "蒋吉",
        "poet_id": "jiang-ji",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "巡堤听唱竹枝词，正是月高风静时。",
            "独向东南人不会，弟兄俱在楚江湄。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]