# -*- coding: utf-8 -*-
"""
张又新卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 17 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 郡斋三月下旬作（以下三首一作崔护诗） ----------
    {
        "id": "zhang-you-xin-1",
        "title": "郡斋三月下旬作（以下三首一作崔护诗）",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "春事日已歇，池塘旷幽寻。残红披独坠，初绿间浅深。",
            "偃仰倦芳褥，顾步爱新阴。谋春未及竟，夏初遽见侵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 五月水边柳 ----------
    {
        "id": "zhang-you-xin-2",
        "title": "五月水边柳",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "结根挺涯涘，垂影覆清浅。睡脸寒未开，懒腰晴更软。",
            "摇空条已重，拂水带方展。似醉烟景凝，如愁月露泫。",
            "丝长鱼误恐，枝弱禽惊践。怅别几多情，含春任攀搴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 三月五日陪大夫泛长沙东湖（一作李群玉诗） ----------
    {
        "id": "zhang-you-xin-3",
        "title": "三月五日陪大夫泛长沙东湖（一作李群玉诗）",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "上巳馀风景，芳辰集远坰。彩舟浮泛荡，绣毂下娉婷。",
            "栖树回葱蒨，笙歌转杳冥。湖光迷翡翠，草色醉蜻蜓。",
            "鸟弄桐花日，鱼翻谷雨萍。从今留胜会，谁看画兰亭。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 赠广陵妓 ----------
    {
        "id": "zhang-you-xin-4",
        "title": "赠广陵妓",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "云雨分飞二十年，当时求梦不曾眠。",
            "今来头白重相见，还上襄王玳瑁筵。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 牡丹 ----------
    {
        "id": "zhang-you-xin-5",
        "title": "牡丹",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "牡丹一朵值千金，将谓从来色最深。",
            "今日满栏开似雪，一生辜负看花心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 游白鹤山 ----------
    {
        "id": "zhang-you-xin-6",
        "title": "游白鹤山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "白鹤山边秋复春，张文宅畔少风尘。",
            "欲驱五马寻真隐，谁是当初□竹人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 行田诗（一作白石岩） ----------
    {
        "id": "zhang-you-xin-7",
        "title": "行田诗（一作白石岩）",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "白石岩前湖水春，湖边旧境有清尘。",
            "欲追谢守行田意，今古同忧是长人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 罗浮山 ----------
    {
        "id": "zhang-you-xin-8",
        "title": "罗浮山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "江北重峦积翠浓，绮霞遥映碧芙蓉。",
            "不知末后沧溟上，减却瀛洲第几峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 青障山（一作慈湖山） ----------
    {
        "id": "zhang-you-xin-9",
        "title": "青障山（一作慈湖山）",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "一派远光澄碧月，万株耸翠猎金飙。",
            "陶仙谩学长生术，暑往寒来更寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 中界山 ----------
    {
        "id": "zhang-you-xin-10",
        "title": "中界山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "瑟瑟峰头玉水流，晋时遗迹更堪愁。",
            "愁人到此劳长望，何处烟波是祖州。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 帆游山 ----------
    {
        "id": "zhang-you-xin-11",
        "title": "帆游山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "涨海尝从此地流，千帆飞过碧山头。",
            "君看深谷为陵后，翻覆人间未肯休。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 谢池 ----------
    {
        "id": "zhang-you-xin-12",
        "title": "谢池",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "郡郭东南积谷山，谢公曾是此跻攀。",
            "今来惟有灵池月，犹是婵娟一水间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 华盖山 ----------
    {
        "id": "zhang-you-xin-13",
        "title": "华盖山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "一岫坡陀凝绿草，千重虚翠透红霞。",
            "愁来始上消归思，见尽江城数百家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 吹台山 ----------
    {
        "id": "zhang-you-xin-14",
        "title": "吹台山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "吹台山上彩烟凝，日落云收叠翠屏。",
            "应谓焦桐堪采斫，不知谁是柳吴兴。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 青岙山 ----------
    {
        "id": "zhang-you-xin-15",
        "title": "青岙山",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "灵海泓澄匝翠峰，昔贤心赏已成空。",
            "今朝亭馆无遗制，积水沧浪一望中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 孤屿 ----------
    {
        "id": "zhang-you-xin-16",
        "title": "孤屿",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "碧水逶迤浮翠巘，绿萝蒙密媚晴江。",
            "不知谁与名孤屿，其实中川是一双。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 春草池 ----------
    {
        "id": "zhang-you-xin-17",
        "title": "春草池",
        "author": "张又新",
        "poet_id": "zhang-you-xin",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "谢公梦草一差微，谪宦当时道不机。",
            "且谓飞霞游赏地，池塘烟柳亦依依。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]