# -*- coding: utf-8 -*-
"""
雍陶卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 124 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 相和歌辞·明月照高楼 ----------
    {
        "id": "yong-tao-1",
        "title": "相和歌辞·明月照高楼",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "朗月何高高，楼中帘影寒。一妇独含叹，四坐谁成欢。",
            "时节屡已移，游旅杳不还。沧溟倘未涸，妾泪终不干。",
            "君若无定云，妾若不动山。云行出山易，山逐云去难。",
            "愿为边塞尘，因风委君颜。君颜良洗多，荡妾浊水间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 明月照高楼 ----------
    {
        "id": "yong-tao-2",
        "title": "明月照高楼",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "朗月何高高，楼中帘影寒。一妇独含叹，四坐谁成欢。",
            "时节屡已移，游旅杳不还。沧溟倘未涸，妾泪终不干。",
            "君若无定云，妾若不动山。云行出山易，山逐云去难。",
            "愿为边塞尘，因风委君颜。君颜良洗多，荡妾浊水间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 酬秘书王丞见寄 ----------
    {
        "id": "yong-tao-3",
        "title": "酬秘书王丞见寄",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "朝下有闲思，南沟边水行。因来见寥落，转自叹平生。",
            "白首丈夫气，赤心知己情。留诗本相慰，却忆苦吟声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 僧金河戍客 ----------
    {
        "id": "yong-tao-4",
        "title": "僧金河戍客",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "惯猎金河路，曾逢雪不迷。射雕青冢北，走马黑山西。",
            "戍远旌幡少，年深帐幕低。酬恩须尽敌，休说梦中闺。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 孤桐 ----------
    {
        "id": "yong-tao-5",
        "title": "孤桐",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "疏桐馀一干，风雨日萧条。岁晚琴材老，天寒桂叶凋。",
            "已悲根半死，复恐尾全焦。幸在龙门下，知音肯寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 秋露 ----------
    {
        "id": "yong-tao-6",
        "title": "秋露",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "白露暧秋色，月明清漏中。痕沾珠箔重，点落玉盘空。",
            "竹动时惊鸟，莎寒暗滴虫。满园生永夜，渐欲与霜同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送徐使君赴岳州 ----------
    {
        "id": "yong-tao-7",
        "title": "送徐使君赴岳州",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "渺渺楚江上，风旗摇去舟。马归云梦晚，猿叫洞庭秋。",
            "别思满南渡，乡心生北楼。巴陵山水郡，应称谢公游。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送裴璋还蜀因亦怀归 ----------
    {
        "id": "yong-tao-8",
        "title": "送裴璋还蜀因亦怀归",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "客在剑门外，新年音信稀。自为千里别，已送几人归。",
            "陌上月初落，马前花正飞。离言殊未尽，春雨满行衣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 送前鄠县李少府 ----------
    {
        "id": "yong-tao-9",
        "title": "送前鄠县李少府",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "近出圭峰下，还期又不赊。身闲多宿寺，官满未移家。",
            "罢钓临秋水，开尊对月华。自当蓬阁选，岂得卧烟霞。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送宜春裴明府之任 ----------
    {
        "id": "yong-tao-10",
        "title": "送宜春裴明府之任",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "南行春已满，路半水茫然。楚望花当渡，湘阴橘满川。",
            "山横湖色上，帆出鸟行前。此任无辞远，亲人贵用还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 赠宗静上人 ----------
    {
        "id": "yong-tao-11",
        "title": "赠宗静上人",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "世上方传教，山中未得归。闲花飘讲席，驯鸽污禅衣。",
            "积雨谁过寺，残钟自掩扉。寒来垂顶帽，白发剃应稀。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 同贾岛宿无可上人院 ----------
    {
        "id": "yong-tao-12",
        "title": "同贾岛宿无可上人院",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "何处销愁宿，携囊就远僧。中宵吟有雪，空屋语无灯。",
            "静境唯闻铎，寒床但枕肱。还因爱闲客，始得见南能。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 和刘补阙秋园寓兴六首 ----------
    {
        "id": "yong-tao-13",
        "title": "和刘补阙秋园寓兴六首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "水木夕阴冷，池塘秋意多。庭风吹故叶，阶露净寒莎。",
            "愁燕窥灯语，情人见月过。砧声听已别，虫响复相和。",
            "闭门无事后，此地即山中。但觉鸟声异，不知人境同。",
            "晚花开为雨，残果落因风。独坐还吟酌，诗成酒已空。",
            "自得家林趣，常时在外稀。对僧餐野食，迎客著山衣。",
            "雀斗翻檐散，蝉惊出树飞。功成他日后，何必五湖归。",
            "秋色庭芜上，清朝见露华。疏篁抽晚笋，幽药吐寒芽。",
            "引水新渠净，登台小径斜。人来多爱此，萧爽似仙家。",
            "禁掖朝回后，林园胜赏时。野人来辨药，庭鹤往看棋。",
            "晚日明丹枣，朝霜润紫梨。还因重风景，犹自有秋诗。",
            "圣代少封事，闲居方屏喧。漏寒云外阙，木落月中园。",
            "山鸟宿檐树，水萤流洞门。无人见清景，林下自开尊。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 岳阳晚景 ----------
    {
        "id": "yong-tao-14",
        "title": "岳阳晚景",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "汉阳无远寺，见说过汾城。云雨经春客，江山几日程。",
            "终随鸥鸟去，只在海潮生。前路逢渔父，多愁问姓名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 塞上宿野寺 ----------
    {
        "id": "yong-tao-15",
        "title": "塞上宿野寺",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "塞上蕃僧老，天寒疾上关。远烟平似水，高树暗如山。",
            "去马朝常急，行人夜始闲。更深听刁斗，时到磬声间。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 寒食夜池上对月怀友 ----------
    {
        "id": "yong-tao-16",
        "title": "寒食夜池上对月怀友",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "人间多别离，处处是相思。海内无烟夜，天涯有月时。",
            "跳鱼翻荇叶，惊鹊出花枝。亲友皆千里，三更独绕池。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 自述 ----------
    {
        "id": "yong-tao-17",
        "title": "自述",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "万事谁能问，一名犹未知。贫当多累日，闲过少年时。",
            "灯下和愁睡，花前带酒悲。无谋常委命，转觉命堪疑。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送契玄上人南游 ----------
    {
        "id": "yong-tao-18",
        "title": "送契玄上人南游",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "红叶落湘川，枫明映水天。寻钟过楚寺，拥锡上泷船。",
            "病客思留药，迷人待说禅。南中多古迹，应访虎溪泉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 少年行（一作汉宫少年行） ----------
    {
        "id": "yong-tao-19",
        "title": "少年行（一作汉宫少年行）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "不倚军功有侠名，可怜球猎少年情。戴铃健鹘随声下，",
            "撼珮骄骢弄影行。觅匠重装燕客剑，对人新按越姬筝。",
            "岂知儒者心偏苦，吟向秋风白发生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 咏双白鹭（一作崔少府池鹭） ----------
    {
        "id": "yong-tao-20",
        "title": "咏双白鹭（一作崔少府池鹭）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "双鹭应怜水满池，风飘不动顶丝垂。立当青草人先见，",
            "行榜白莲鱼未知。一足独拳寒雨里，数声相叫早秋时。",
            "林塘得尔须增价，况与诗家物色宜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 晴诗（一作塞路初晴） ----------
    {
        "id": "yong-tao-21",
        "title": "晴诗（一作塞路初晴）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "晚虹斜日塞天昏，一半山川带雨痕。新水乱侵青草路，",
            "残烟犹傍绿杨村。胡人羊马休南牧，汉将旌旗在北门。",
            "行子喜闻无战伐，闲看游骑猎秋原。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送徐山人归睦州旧隐 ----------
    {
        "id": "yong-tao-22",
        "title": "送徐山人归睦州旧隐",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "君在桐庐何处住，草堂应与戴家邻。初归山犬翻惊主，",
            "久别江鸥却避人。终日欲为相逐计，临岐空羡独行身。",
            "秋风钓艇遥相忆，七里滩西片月新。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 到蜀后记途中经历 ----------
    {
        "id": "yong-tao-23",
        "title": "到蜀后记途中经历",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "剑峰重叠雪云漫，忆昨来时处处难。大散岭头春足雨，",
            "褒斜谷里夏犹寒。蜀门去国三千里，巴路登山八十盘。",
            "自到成都烧酒熟，不思身更入长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 忆山寄僧 ----------
    {
        "id": "yong-tao-24",
        "title": "忆山寄僧",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "尘路谁知蹋雪踪，到来空认出云峰。天晴远见月中树，",
            "风便细听烟际钟。阅世数思僧并院，忆山长羡鹤归松。",
            "新愁旧恨多难说，半在眉间半在胸。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 赠玉芝观王尊师 ----------
    {
        "id": "yong-tao-25",
        "title": "赠玉芝观王尊师",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "处处烟霞寻总遍，却来城市喜逢师。时流见说无人在，",
            "年纪唯应有鹤知。大药已成宁畏晚，小松初种不嫌迟。",
            "长忧一日归天去，未授灵方遣问谁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 哭饶州吴谏议使君 ----------
    {
        "id": "yong-tao-26",
        "title": "哭饶州吴谏议使君",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "忽闻身谢满朝惊，俄感鄱阳罢市情。遗爱永存今似古，",
            "高名不朽死如生。神仙难见青骡事，谏议空留白马名。",
            "授馆曾为门下客，几回垂泪过宣平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 经杜甫旧宅 ----------
    {
        "id": "yong-tao-27",
        "title": "经杜甫旧宅",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "浣花溪里花多处，为忆先生在蜀时。万古只应留旧宅，",
            "千金无复换新诗。沙崩水槛鸥飞尽，树压村桥马过迟。",
            "山月不知人事变，夜来江上与谁期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 河阴新城 ----------
    {
        "id": "yong-tao-28",
        "title": "河阴新城",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "高城新筑压长川，虎踞龙盘气色全。五里似云根不动，",
            "一重如月晕长圆。河流暗与沟池合，山色遥将睥睨连。",
            "自有此来当汴口，武牢何用锁风烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 秋居病中 ----------
    {
        "id": "yong-tao-29",
        "title": "秋居病中",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "幽居悄悄何人到，落日清凉满树梢。新句有时愁里得，",
            "古方无效病来抛。荒檐数蝶悬蛛网，空屋孤萤入燕巢。",
            "独卧南窗秋色晚，一庭红叶掩衡茅。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 罢还边将 ----------
    {
        "id": "yong-tao-30",
        "title": "罢还边将",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "白须虏将话边事，自失公权怨语多。汉主岂劳思李牧，",
            "赵王犹是用廉颇。新鹰饱肉唯闲猎，旧剑生衣懒更磨。",
            "百战无功身老去，羡他年少渡黄河。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 永乐殷尧藩明府县池嘉莲咏 ----------
    {
        "id": "yong-tao-31",
        "title": "永乐殷尧藩明府县池嘉莲咏",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "青蘋白石匝莲塘，水里莲开带瑞光。露湿红芳双朵重，",
            "风飘绿蒂一枝长。同心栀子徒夸艳，合穗嘉禾岂解香。",
            "不独丰祥先有应，更宜花县对潘郎。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 酬李绀岁除送酒 ----------
    {
        "id": "yong-tao-32",
        "title": "酬李绀岁除送酒",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "岁尽贫生事事须，就中深恨酒钱无。故人充寿能分送，",
            "远客消愁免自沽。一夜四乘倾凿落，五更三点把屠苏。",
            "已供时节深珍重，况许今朝更挈壶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 蜀路倦行因有所感 ----------
    {
        "id": "yong-tao-33",
        "title": "蜀路倦行因有所感",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "乱峰碎石金牛路，过客应骑铁马行。白日欲斜催后乘，",
            "青云何处问前程。飞蝇一一皆先去，度鸟双双亦远鸣。",
            "蹇步不唯伤旅思，此中兼见宦途情。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 寄永乐殷尧藩明府 ----------
    {
        "id": "yong-tao-34",
        "title": "寄永乐殷尧藩明府",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "古县萧条秋景晚，昔年陶令亦如君。头巾漉酒临黄菊，",
            "手板支颐向白云。百里岂能容骥足，九霄终自别鸡群。",
            "相思不恨书来少，佳句多从阙下闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 蜀中战后感事 ----------
    {
        "id": "yong-tao-35",
        "title": "蜀中战后感事",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "蜀道英灵地，山重水又回。文章四子盛，道路五丁开。",
            "词客题桥去，忠臣叱驭来。卧龙同骇浪，跃马比浮埃。",
            "已谓无妖土，那知有祸胎。蕃兵依濮柳，蛮旆指江梅。",
            "战后悲逢血，烧馀恨见灰。空留犀厌怪，无复酒除灾。",
            "岁积苌弘怨，春深杜宇哀。家贫移未得，愁上望乡台。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 答蜀中经蛮后友人马艾见寄 ----------
    {
        "id": "yong-tao-36",
        "title": "答蜀中经蛮后友人马艾见寄",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "茜马渡泸水，北来如鸟轻。几年朝凤阙，一日破龟城。",
            "此地有征战，谁家无死生。人悲还旧里，鸟喜下空营。",
            "弟侄意初定，交朋心尚惊。自从经难后，吟苦似猿声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 卢岳闲居十韵 ----------
    {
        "id": "yong-tao-37",
        "title": "卢岳闲居十韵",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "扰扰走人寰，争如占得闲。防愁心付酒，求静力登山。",
            "见药芳时采，逢花好处攀。望云开病眼，临涧洗愁颜。",
            "春色流岩下，秋声碎竹间。锦文苔点点，钱样菊斑斑。",
            "路远朝无客，门深夜不关。鹤飞高缥缈，莺语巧绵蛮。",
            "养拙甘沈默，忘怀绝险艰。更怜云外路，空去又空还。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 送于中丞使北蕃 ----------
    {
        "id": "yong-tao-38",
        "title": "送于中丞使北蕃",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "朔将引双旌，山遥碛雪平。经年通国信，计日得蕃情。",
            "野次依泉宿，沙中望火行。远雕秋有力，寒马夜无声。",
            "看猎临胡帐，思乡见汉城。来春拥边骑，新草满归程。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 和河南白尹西池北新葺水斋招赏十二韵 ----------
    {
        "id": "yong-tao-39",
        "title": "和河南白尹西池北新葺水斋招赏十二韵",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "二室峰前水，三川府右亭。乱流深竹径，分绕小花汀。",
            "池角通泉脉，堂心豁地形。坐中寒瑟瑟，床下细泠泠。",
            "雨夜思巫峡，秋朝想洞庭。千年孤镜碧，一片远天青。",
            "鱼戏摇红尾，鸥闲退白翎。荷倾泻珠露，沙乱动金星。",
            "藤架如纱帐，苔墙似锦屏。龙门人少到，仙棹自多停。",
            "游忆高僧伴，吟招野客听。馀波不能惜，便欲养浮萍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 感兴 ----------
    {
        "id": "yong-tao-40",
        "title": "感兴",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "贫女貌非丑，要须缘嫁迟。还似求名客，无媒不及时。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 长安客感 ----------
    {
        "id": "yong-tao-41",
        "title": "长安客感",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "日过千万家，一家非所依。不及行尘影，犹随马蹄归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 春怀旧游 ----------
    {
        "id": "yong-tao-42",
        "title": "春怀旧游",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "吟想旧经过，花时奈远何。别来长似见，春梦入关多。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 离京城宿商山作 ----------
    {
        "id": "yong-tao-43",
        "title": "离京城宿商山作",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "山月吟声苦，春风引思长。无由及尘土，犹带杏花香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 秋馆雨夜 ----------
    {
        "id": "yong-tao-44",
        "title": "秋馆雨夜",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "夜雨空馆静，幽人起裴回。长安醉眠客，岂知新雁来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 闻子规 ----------
    {
        "id": "yong-tao-45",
        "title": "闻子规",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "百鸟有啼时，子规声不歇。春寒四邻静，独叫三更月。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 怀无可上人 ----------
    {
        "id": "yong-tao-46",
        "title": "怀无可上人",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "山寺秋时后，僧家夏满时。清凉多古迹，几处有新诗。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 长安客感 ----------
    {
        "id": "yong-tao-47",
        "title": "长安客感",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "客泪如危叶，长悬零落心。况是悲秋日，临风制不禁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 送客遥望 ----------
    {
        "id": "yong-tao-48",
        "title": "送客遥望",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "别远心更苦，遥将目送君。光华不可见，孤鹤没秋云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 伤靡草 ----------
    {
        "id": "yong-tao-49",
        "title": "伤靡草",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "靡草似客心，年年亦先死。无由伴花落，暂得因风起。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 放鹤 ----------
    {
        "id": "yong-tao-50",
        "title": "放鹤",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "从今一去不须低，见说辽东好去栖。",
            "努力莫辞仙路远，白云飞处免群鸡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 早秋月夜 ----------
    {
        "id": "yong-tao-51",
        "title": "早秋月夜",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "身闲伴月夜深行，风触衣裳四体轻。",
            "为见近来天气好，几篇诗兴入秋成。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 蝉 ----------
    {
        "id": "yong-tao-52",
        "title": "蝉",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "高树蝉声入晚云，不唯愁我亦愁君。",
            "何时各得身无事，每到闻时似不闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 公子行 ----------
    {
        "id": "yong-tao-53",
        "title": "公子行",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "公子风流嫌锦绣，新裁白纻作春衣。",
            "金鞭留当谁家酒，拂柳穿花信马归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 题情尽桥 ----------
    {
        "id": "yong-tao-54",
        "title": "题情尽桥",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "从来只有情难尽，何事名为情尽桥。",
            "自此改名为折柳，任他离恨一条条。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 峡中行 ----------
    {
        "id": "yong-tao-55",
        "title": "峡中行",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "两崖开尽水回环，一叶才通石罅间。",
            "楚客莫言山势险，世人心更险于山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 韦处士郊居 ----------
    {
        "id": "yong-tao-56",
        "title": "韦处士郊居",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "满庭诗境飘红叶，绕砌琴声滴暗泉。",
            "门外晚晴秋色老，万条寒玉一溪烟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 秋怀 ----------
    {
        "id": "yong-tao-57",
        "title": "秋怀",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "古槐烟薄晚鸦愁，独向黄昏立御沟。",
            "南国望中生远思，一行新雁去汀洲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 再下第将归荆楚上白舍人 ----------
    {
        "id": "yong-tao-58",
        "title": "再下第将归荆楚上白舍人",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "穷通应计一时间，今日甘从刖足还。",
            "长倚玉人心自醉，不辞归去哭荆山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 春行武关作 ----------
    {
        "id": "yong-tao-59",
        "title": "春行武关作",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "风香春暖展归程，全胜游仙入洞情。",
            "一路缘溪花覆水，不妨闲看不妨行。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 恨别二首 ----------
    {
        "id": "yong-tao-60",
        "title": "恨别二首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "知君饯酒深深意，图使行人涕不流。",
            "如今却恨酒中别，不得一言千里愁。",
            "人言日远还疏索，别后都非未别心。",
            "唯我忆君千里意，一年不见一重深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 送人归吴 ----------
    {
        "id": "yong-tao-61",
        "title": "送人归吴",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "远爱春波正满湖，羡君东去是归途。",
            "吟诗好向月中宿，一叫水天沙鹤孤。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 喜梦归 ----------
    {
        "id": "yong-tao-62",
        "title": "喜梦归",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷61》",
        "verse": [
            "旅馆岁阑频有梦，分明最似此宵希。",
            "觉来莫道还无益，未得归时且当归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 63. 路中问程知欲达青云驿 ----------
    {
        "id": "yong-tao-63",
        "title": "路中问程知欲达青云驿",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷62》",
        "verse": [
            "行愁驿路问来人，西去经过愿一闻。",
            "落日回鞭相指点，前程从此是青云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 64. 题君山（一作洞庭诗） ----------
    {
        "id": "yong-tao-64",
        "title": "题君山（一作洞庭诗）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷63》",
        "verse": [
            "风波不动影沈沈，翠色全微碧色深。",
            "应是水仙梳洗处，一螺青黛镜中心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 65. 离家后作 ----------
    {
        "id": "yong-tao-65",
        "title": "离家后作",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷64》",
        "verse": [
            "世上无媒似我希，一身惟有影相随。",
            "出门便作焚舟计，生不成名死不归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 66. 寄题岘亭 ----------
    {
        "id": "yong-tao-66",
        "title": "寄题岘亭",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷65》",
        "verse": [
            "岘亭留恨为伤杯，未得醒醒看便回。",
            "却想醉游如梦见，直疑元本不曾来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 67. 病鹤 ----------
    {
        "id": "yong-tao-67",
        "title": "病鹤",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷66》",
        "verse": [
            "忆得当时病未遭，身为仙驭雪为毛。",
            "今来沙上飞无力，羞见樯乌立处高。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 68. 状春 ----------
    {
        "id": "yong-tao-68",
        "title": "状春",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷67》",
        "verse": [
            "含春笑日花心艳，带雨牵风柳态妖。",
            "珍重两般堪比处，醉时红脸舞时腰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 69. 春咏 ----------
    {
        "id": "yong-tao-69",
        "title": "春咏",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷68》",
        "verse": [
            "风恼花枝不耐频，等闲飞落易愁人。",
            "殷勤最是章台柳，一树千条管带春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 70. 非酒 ----------
    {
        "id": "yong-tao-70",
        "title": "非酒",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷69》",
        "verse": [
            "人人慢说酒消忧，我道翻为引恨由。",
            "一夜醒来灯火暗，不应愁事亦成愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 71. 苦寒 ----------
    {
        "id": "yong-tao-71",
        "title": "苦寒",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷70》",
        "verse": [
            "今年无异去年寒，何事朝来独忍难。",
            "应是渐为贫客久，锦衣著尽布衣单。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 72. 送客 ----------
    {
        "id": "yong-tao-72",
        "title": "送客",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷71》",
        "verse": [
            "若论秋思人人苦，最觉愁多客又深。",
            "何况病来惆怅尽，不知争作送君心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 73. 人问应举 ----------
    {
        "id": "yong-tao-73",
        "title": "人问应举",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷72》",
        "verse": [
            "莫惊西上独迟回，只为衡门未有媒。",
            "惆怅赋成身不去，一名闲事逐秋回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 74. 送客不及 ----------
    {
        "id": "yong-tao-74",
        "title": "送客不及",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷73》",
        "verse": [
            "水阔江天两不分，行人两处更相闻。",
            "遥遥已失风帆影，半日虚销指点云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 75. 闻杜鹃二首 ----------
    {
        "id": "yong-tao-75",
        "title": "闻杜鹃二首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷74》",
        "verse": [
            "碧竿微露月玲珑，谢豹伤心独叫风。",
            "高处已应闻滴血，山榴一夜几枝红。",
            "蜀客春城闻蜀鸟，思归声引未归心。",
            "却知夜夜愁相似，尔正啼时我正吟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 76. 西归出斜谷 ----------
    {
        "id": "yong-tao-76",
        "title": "西归出斜谷",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷75》",
        "verse": [
            "行过险栈出褒斜，出尽平川似到家。",
            "万里客愁今日散，马前初见米囊花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 77. 宿嘉陵驿（一作嘉陵馆楼） ----------
    {
        "id": "yong-tao-77",
        "title": "宿嘉陵驿（一作嘉陵馆楼）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷76》",
        "verse": [
            "离思茫茫正值秋，每因风景却生愁。",
            "今宵难作刀州梦，月色江声共一楼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 78. 旅怀 ----------
    {
        "id": "yong-tao-78",
        "title": "旅怀",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷77》",
        "verse": [
            "旧里已悲无产业，故山犹恋有烟霞。",
            "自从为客归时少，旅馆僧房却是家。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 79. 贫居春怨 ----------
    {
        "id": "yong-tao-79",
        "title": "贫居春怨",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷78》",
        "verse": [
            "贫居尽日冷风烟，独向檐床看雨眠。",
            "寂寞春风花落尽，满庭榆荚似秋天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 80. 忆江南旧居 ----------
    {
        "id": "yong-tao-80",
        "title": "忆江南旧居",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷79》",
        "verse": [
            "闲思往事在湖亭，亭上秋灯照月明。",
            "宿客尽眠眠不得，半窗残月带潮声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 81. 夷陵城 ----------
    {
        "id": "yong-tao-81",
        "title": "夷陵城",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷80》",
        "verse": [
            "世家曾览楚英雄，国破城荒万事空。",
            "唯有邮亭阶下柳，春来犹似细腰宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 82. 访友人幽居二首 ----------
    {
        "id": "yong-tao-82",
        "title": "访友人幽居二首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷81》",
        "verse": [
            "落花门外春将尽，飞絮庭前日欲高。",
            "深院客来人未起，黄鹂枝上啄樱桃。",
            "莎深苔滑地无尘，竹冷花迟剩驻春。",
            "尽日弄琴谁共听，与君兼鹤是三人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 83. 宿大彻禅师故院 ----------
    {
        "id": "yong-tao-83",
        "title": "宿大彻禅师故院",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷82》",
        "verse": [
            "竹房谁继生前事，松月空悬过去心。",
            "秋磬数声天欲晓，影堂斜掩一灯深。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 84. 送蜀客 ----------
    {
        "id": "yong-tao-84",
        "title": "送蜀客",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷83》",
        "verse": [
            "剑南风景腊前春，山鸟江风得雨新。",
            "莫怪送君行较远，自缘身是忆归人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 85. 题宝应县 ----------
    {
        "id": "yong-tao-85",
        "title": "题宝应县",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷84》",
        "verse": [
            "雪楼当日动晴寒，渭水梁山鸟外看。",
            "闻说德宗曾到此，吟诗不敢倚阑干。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 86. 和孙明府怀旧山 ----------
    {
        "id": "yong-tao-86",
        "title": "和孙明府怀旧山",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷85》",
        "verse": [
            "五柳先生本在山，偶然为客落人间。",
            "秋来见月多归思，自起开笼放白鹇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 87. 城西访友人别墅 ----------
    {
        "id": "yong-tao-87",
        "title": "城西访友人别墅",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷86》",
        "verse": [
            "澧水桥西小路斜，日高犹未到君家。",
            "村园门巷多相似，处处春风枳壳花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 88. 题大安池亭 ----------
    {
        "id": "yong-tao-88",
        "title": "题大安池亭",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷87》",
        "verse": [
            "幽岛曲池相隐映，小桥虚阁半高低。",
            "好风好月无人宿，夜夜水禽船上栖。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 89. 送春 ----------
    {
        "id": "yong-tao-89",
        "title": "送春",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷88》",
        "verse": [
            "勿言春尽春还至，少壮看花复几回。",
            "今日已从愁里去，明年更莫共愁来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 90. 武侯庙古柏 ----------
    {
        "id": "yong-tao-90",
        "title": "武侯庙古柏",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷89》",
        "verse": [
            "密叶四时同一色，高枝千岁对孤峰。",
            "此中疑有精灵在，为见盘根似卧龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 91. 哀蜀人为南蛮俘虏五章·初出成都闻哭声 ----------
    {
        "id": "yong-tao-91",
        "title": "哀蜀人为南蛮俘虏五章·初出成都闻哭声",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷90》",
        "verse": [
            "但见城池还汉将，岂知佳丽属蛮兵。",
            "锦江南度遥闻哭，尽是离家别国声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 92. 哀蜀人为南蛮俘虏五章·过大渡河蛮使许之泣望乡国 ----------
    {
        "id": "yong-tao-92",
        "title": "哀蜀人为南蛮俘虏五章·过大渡河蛮使许之泣望乡国",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷91》",
        "verse": [
            "大渡河边蛮亦愁，汉人将渡尽回头。",
            "此中剩寄思乡泪，南去应无水北流。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 93. 哀蜀人为南蛮俘虏五章·出青溪关有迟留之意 ----------
    {
        "id": "yong-tao-93",
        "title": "哀蜀人为南蛮俘虏五章·出青溪关有迟留之意",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷92》",
        "verse": [
            "欲出乡关行步迟，此生无复却回时。",
            "千冤万恨何人见，唯有空山鸟兽知。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 94. 哀蜀人为南蛮俘虏五章·别巂州一时恸哭云日为之变色 ----------
    {
        "id": "yong-tao-94",
        "title": "哀蜀人为南蛮俘虏五章·别巂州一时恸哭云日为之变色",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷93》",
        "verse": [
            "越巂城南无汉地，伤心从此便为蛮。",
            "冤声一恸悲风起，云暗青天日下山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 95. 哀蜀人为南蛮俘虏五章·入蛮界不许有悲泣之声 ----------
    {
        "id": "yong-tao-95",
        "title": "哀蜀人为南蛮俘虏五章·入蛮界不许有悲泣之声",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷94》",
        "verse": [
            "云南路出陷河西，毒草长青瘴色低。",
            "渐近蛮城谁敢哭，一时收泪羡猿啼。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 96. 宿石门山居 ----------
    {
        "id": "yong-tao-96",
        "title": "宿石门山居",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷95》",
        "verse": [
            "窗灯欲灭夜愁生，萤火飞来促织鸣。",
            "宿客几回眠又起，一溪秋水枕边声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 97. 过旧宅看花 ----------
    {
        "id": "yong-tao-97",
        "title": "过旧宅看花",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷96》",
        "verse": [
            "山桃野杏两三栽，树树繁花去复开。",
            "今日主人相引看，谁知曾是客移来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 98. 寄襄阳章孝标 ----------
    {
        "id": "yong-tao-98",
        "title": "寄襄阳章孝标",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷97》",
        "verse": [
            "青油幕下白云边，日日空山夜夜泉。",
            "闻说小斋多野意，枳花阴里麝香眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 99. 洛中感事 ----------
    {
        "id": "yong-tao-99",
        "title": "洛中感事",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷98》",
        "verse": [
            "洛城今古足繁华，最恨乔家似石家。",
            "行到窈娘身没处，水边愁见亚枝花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 100. 阴地关见入蕃公主石上手迹 ----------
    {
        "id": "yong-tao-100",
        "title": "阴地关见入蕃公主石上手迹",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷99》",
        "verse": [
            "汉家公主昔和蕃，石上今馀手迹存。",
            "风雨几年侵不灭，分明纤指印苔痕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 101. 美人春风怨 ----------
    {
        "id": "yong-tao-101",
        "title": "美人春风怨",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷100》",
        "verse": [
            "澹荡春风满眼来，落花飞蝶共裴回。",
            "偏能飘散同心蒂，无那愁眉吹不开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 102. 过南邻花园 ----------
    {
        "id": "yong-tao-102",
        "title": "过南邻花园",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷101》",
        "verse": [
            "莫怪频过有酒家，多情长是惜年华。",
            "春风堪赏还堪恨，才见开花又落花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 103. 劝行乐 ----------
    {
        "id": "yong-tao-103",
        "title": "劝行乐",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷102》",
        "verse": [
            "老去风光不属身，黄金莫惜买青春。",
            "白头纵作花园主，醉折花枝是别人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 104. 渡桑干河 ----------
    {
        "id": "yong-tao-104",
        "title": "渡桑干河",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷103》",
        "verse": [
            "南客岂曾谙塞北，年年唯见雁飞回。",
            "今朝忽渡桑干水，不似身来似梦来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 105. 月下喜吕郎中除兵部 ----------
    {
        "id": "yong-tao-105",
        "title": "月下喜吕郎中除兵部",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷104》",
        "verse": [
            "北阙云间见碧天，南宫月似旧时圆。",
            "喜看列宿今朝正，休叹参差十四年。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 106. 天津桥望春 ----------
    {
        "id": "yong-tao-106",
        "title": "天津桥望春",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷105》",
        "verse": [
            "津桥春水浸红霞，烟柳风丝拂岸斜。",
            "翠辇不来金殿闭，宫莺衔出上阳花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 107. 自蔚州南入真谷有似剑门，因有归思 ----------
    {
        "id": "yong-tao-107",
        "title": "自蔚州南入真谷有似剑门，因有归思",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷106》",
        "verse": [
            "我家蜀地身离久，忽见胡山似剑门。",
            "马上欲垂千里泪，耳边唯欠一声猿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 108. 再经天涯地角山 ----------
    {
        "id": "yong-tao-108",
        "title": "再经天涯地角山",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷107》",
        "verse": [
            "每忆云山养短才，悔缘名利入尘埃。",
            "十年马足行多少，两度天涯地角来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 109. 题等界寺二首 ----------
    {
        "id": "yong-tao-109",
        "title": "题等界寺二首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷108》",
        "verse": [
            "吴蜀千年等界村，英雄无主岂长存。",
            "思量往事今何在，万里山中一寺门。",
            "两国道涂都万里，来从此地等平分。",
            "行人竞说东西利，事不关心耳不闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 110. 洛源驿戏题 ----------
    {
        "id": "yong-tao-110",
        "title": "洛源驿戏题",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷109》",
        "verse": [
            "柳阴春岭鸟新啼，暖色浓烟深处迷。",
            "如恨往来人不见，水声呦咽出花溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 111. 遣愁 ----------
    {
        "id": "yong-tao-111",
        "title": "遣愁",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷110》",
        "verse": [
            "抛掷泥中一听沈，不能三叹引愁深。",
            "莫言客子无愁易，须识愁多暗损心。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 112. 送友人弃官归山居 ----------
    {
        "id": "yong-tao-112",
        "title": "送友人弃官归山居",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷111》",
        "verse": [
            "不爱人间紫与绯，却思松下著山衣。",
            "春郊雨尽多新草，一路青青蹋雨归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 113. 山行 ----------
    {
        "id": "yong-tao-113",
        "title": "山行",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷112》",
        "verse": [
            "野花幽鸟几千般，头白山僧遍识难。",
            "世上游人无复见，一生唯向画图看。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 114. 送客二首 ----------
    {
        "id": "yong-tao-114",
        "title": "送客二首",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷113》",
        "verse": [
            "与君同在少年场，知己萧条壮士伤。",
            "可惜报恩无处所，却提孤剑过咸阳。",
            "行人立马强盘回，别字犹含未忍开。",
            "好去出门休落泪，不如前路早归来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 115. 安国寺赠广宣上人 ----------
    {
        "id": "yong-tao-115",
        "title": "安国寺赠广宣上人",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷114》",
        "verse": [
            "马急人忙尘路喧，几从朝出到黄昏。",
            "今来合掌听师语，一似敲冰清耳根。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 116. 初醒 ----------
    {
        "id": "yong-tao-116",
        "title": "初醒",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷115》",
        "verse": [
            "心中得胜暂抛愁，醉卧京风拂簟秋。",
            "半夜觉来新酒醒，一条斜月到床头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 117. 送客归襄阳旧居 ----------
    {
        "id": "yong-tao-117",
        "title": "送客归襄阳旧居",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷116》",
        "verse": [
            "襄阳耆旧别来稀，此去何人共掩扉。",
            "唯有白铜鞮上月，水楼闲处待君归。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 118. 夜闻方响 ----------
    {
        "id": "yong-tao-118",
        "title": "夜闻方响",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷117》",
        "verse": [
            "方响闻时夜已深，声声敲著客愁心。",
            "不知正在谁家乐，月下犹疑是远砧。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 119. 路逢有似亡友者，恻然赋此 ----------
    {
        "id": "yong-tao-119",
        "title": "路逢有似亡友者，恻然赋此",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷118》",
        "verse": [
            "吾友今生不可逢，风流空想旧仪容。",
            "朝来马上频回首，惆怅他人似蔡邕。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 120. 望月怀江上旧游 ----------
    {
        "id": "yong-tao-120",
        "title": "望月怀江上旧游",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷119》",
        "verse": [
            "往岁曾随江客船，秋风明月洞庭边。",
            "为看今夜天如水，忆得当时水似天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 121. 途中西望 ----------
    {
        "id": "yong-tao-121",
        "title": "途中西望",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷120》",
        "verse": [
            "行行何处散离愁，长路无因暂上楼。",
            "唯到高原即西望，马知人意亦回头。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 122. 题友人所居（即故元少尹宅） ----------
    {
        "id": "yong-tao-122",
        "title": "题友人所居（即故元少尹宅）",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷121》",
        "verse": [
            "亚尹故居经几主，只因君住有诗情。",
            "夜吟邻叟闻惆怅，七八年来无此声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 123. 蔚州晏内遇新雪 ----------
    {
        "id": "yong-tao-123",
        "title": "蔚州晏内遇新雪",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷122》",
        "verse": [
            "胡卢河畔逢秋雪，疑是风飘白鹤毛。",
            "坐客停杯看未定，将军已湿褐花袍。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 124. 句 ----------
    {
        "id": "yong-tao-124",
        "title": "句",
        "author": "雍陶",
        "poet_id": "yong-tao",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷123》",
        "verse": [
            "古木闽州道，驱羸落照间。投村碍野水，问店隔荒山。",
            "（见《泉州志》）",
            "第五百一十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]