# -*- coding: utf-8 -*-
"""
左偃卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 11 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 寄庐山白上人 ----------
    {
        "id": "zuo-yan-1",
        "title": "寄庐山白上人",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "潦倒门前客，闲眠岁又残。连天数峰雪，终日与谁看。",
            "万丈高松古，千寻落水寒。仍闻有新作，懒寄入长安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 寄韩侍郎 ----------
    {
        "id": "zuo-yan-2",
        "title": "寄韩侍郎",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "谋身谋隐两无成，拙计深惭负耦耕。渐老可堪怀故国，",
            "多愁翻觉厌浮生。言诗幸遇明公许，守朴甘遭俗者轻。",
            "今日况闻搜草泽，独悲憔悴卧升平。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 汉宫词 ----------
    {
        "id": "zuo-yan-3",
        "title": "汉宫词",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "寒烛照清夜，笙歌隔藓墙。一从飞燕入，便不见君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 送君去 ----------
    {
        "id": "zuo-yan-4",
        "title": "送君去",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "关河月未晓，行子心已急。佳人无一言，独背残灯泣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 秋晚野望 ----------
    {
        "id": "zuo-yan-5",
        "title": "秋晚野望",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "倚筇聊一望，何处是秦川。草色初晴路，鸿声欲暮天。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 郊原晚望怀李秘书 ----------
    {
        "id": "zuo-yan-6",
        "title": "郊原晚望怀李秘书",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "归鸟入平野，寒云在远村。徒令睇望久，不复见王孙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 言怀别同志 ----------
    {
        "id": "zuo-yan-7",
        "title": "言怀别同志",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "渐老将谁托，劳生每自惭。何当重携手，风雨满江南。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 江上晚泊 ----------
    {
        "id": "zuo-yan-8",
        "title": "江上晚泊",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "寒云淡淡天无际，片帆落处沙鸥起。",
            "水阔风高日复斜，扁舟独宿芦花里。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 寄鉴上人 ----------
    {
        "id": "zuo-yan-9",
        "title": "寄鉴上人",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "一从携手阻戈鋋，屈指如今已十年。",
            "长记二林同宿夜，竹斋听雨共忘眠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 送人 ----------
    {
        "id": "zuo-yan-10",
        "title": "送人",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "一茎两茎华发生，千枝万枝梨花白。",
            "春色江南独未归，今朝又送还乡客。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 句 ----------
    {
        "id": "zuo-yan-11",
        "title": "句",
        "author": "左偃",
        "poet_id": "zuo-yan",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "胡笳闻欲死，汉月望还生。（《昭君怨》）",
            "日华离碧海，云影散青霄。（《早日》）",
            "第七百四十一卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]