# -*- coding: utf-8 -*-
"""
成彦雄卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 20 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 杜鹃花 ----------
    {
        "id": "cheng-yan-xiong-1",
        "title": "杜鹃花",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "杜鹃花与鸟，怨艳两何赊。疑是口中血，滴成枝上花。",
            "一声寒食夜，数朵野僧家。谢豹出不出，日迟迟又斜。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 江上枫 ----------
    {
        "id": "cheng-yan-xiong-2",
        "title": "江上枫",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "江枫自蓊郁，不竞松筠力。一叶落渔家，残阳带秋色。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 夜夜曲 ----------
    {
        "id": "cheng-yan-xiong-3",
        "title": "夜夜曲",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "自从君去夜，锦幌孤兰麝。欹枕对银缸，秦筝绿窗下。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 村行 ----------
    {
        "id": "cheng-yan-xiong-4",
        "title": "村行",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "暧暧村烟暮，牧童出深坞。骑牛不顾人，吹笛寻山去。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 煎茶 ----------
    {
        "id": "cheng-yan-xiong-5",
        "title": "煎茶",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "岳寺春深睡起时，虎跑泉畔思迟迟。",
            "蜀茶倩个云僧碾，自拾枯松三四枝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 松 ----------
    {
        "id": "cheng-yan-xiong-6",
        "title": "松",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "大夫名价古今闻，盘屈孤贞更出群。",
            "将谓岭头闲得了，夕阳犹挂数枝云。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 新燕 ----------
    {
        "id": "cheng-yan-xiong-7",
        "title": "新燕",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "才离海岛宿江滨，应梦笙歌作近邻。",
            "减省雕梁并头语，画堂中有未归人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 会友不至 ----------
    {
        "id": "cheng-yan-xiong-8",
        "title": "会友不至",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "王孙还是负佳期，玉马追游日渐西。",
            "独上郊原人不见，鹧鸪飞过落花溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 惜花 ----------
    {
        "id": "cheng-yan-xiong-9",
        "title": "惜花",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "忘餐为恋满枝红，锦障频移护晚风。",
            "客散酒酣归未得，栏边独立月明中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 中秋月 ----------
    {
        "id": "cheng-yan-xiong-10",
        "title": "中秋月",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "王母妆成镜未收，倚栏人在水精楼。",
            "笙歌莫占清光尽，留与溪翁一钓舟。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 暮春日宴溪亭 ----------
    {
        "id": "cheng-yan-xiong-11",
        "title": "暮春日宴溪亭",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "寒食寻芳游不足，溪亭还醉绿杨烟。",
            "谁家花落临流树，数片残红到槛前。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 晓 ----------
    {
        "id": "cheng-yan-xiong-12",
        "title": "晓",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "列宿回元朝北极，爽神晞露滴楼台。",
            "佳人卷箔临阶砌，笑指庭花昨夜开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 夕 ----------
    {
        "id": "cheng-yan-xiong-13",
        "title": "夕",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "台榭沈沈禁漏初，麝烟红蜡透虾须。",
            "雕笼鹦鹉将栖宿，不许鸦鬟转辘轳。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 露 ----------
    {
        "id": "cheng-yan-xiong-14",
        "title": "露",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "银河昨夜降醍醐，洒遍坤维万象苏。",
            "疑是鲛人曾泣处，满池荷叶捧真珠。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 游紫阳宫 ----------
    {
        "id": "cheng-yan-xiong-15",
        "title": "游紫阳宫",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "古殿烟霞簇画屏，直疑踪迹到蓬瀛。",
            "碧桃满地眠花鹿，深院松窗捣药声。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 除夜 ----------
    {
        "id": "cheng-yan-xiong-16",
        "title": "除夜",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "铜龙看却送春来，莫惜颠狂酒百杯。",
            "吟鬓就中专拟白，那堪更被二更催。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 元日 ----------
    {
        "id": "cheng-yan-xiong-17",
        "title": "元日",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "戴星先捧祝尧觞，镜里堪惊两鬓霜。",
            "好是灯前偷失笑，屠苏应不得先尝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 寒夜吟 ----------
    {
        "id": "cheng-yan-xiong-18",
        "title": "寒夜吟",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "洞房脉脉寒宵永，烛影香消金凤冷。",
            "猧儿睡魇唤不醒，满窗扑落银蟾影。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 柳枝辞九首 ----------
    {
        "id": "cheng-yan-xiong-19",
        "title": "柳枝辞九首",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "轻笼小径近谁家，玉马追风翠影斜。",
            "爱把长条恼公子，惹他头上海棠花。",
            "鹅黄剪出小花钿，缀上芳枝色转鲜。",
            "饮散无人收拾得，月明阶下伴秋千。",
            "东君爱惜与先春，草泽无人处也新。",
            "委嘱露华并细雨，莫教迟日惹风尘。",
            "句践初迎西子年，琉璃为帚扫溪烟。",
            "至今不改当时色，留与王孙系酒船。",
            "绿杨移傍小亭栽，便拥秾烟拨不开。",
            "谁把金刀为删掠，放教明月入窗来。",
            "远接关河高接云，雨馀洗出半天津。",
            "牡丹不用相轻薄，自有清阴覆得人。",
            "掩映莺花媚有馀，风流才调比应无。",
            "朝朝奉御临池上，不羡青松拜大夫。",
            "王孙宴罢曲江池，折取春光伴醉归。",
            "怪得美人争斗乞，要他秾翠染罗衣。",
            "残照林梢袅数枝，能招醉客上金堤。",
            "马娇如练缨如火，瑟瑟阴中步步嘶。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 句 ----------
    {
        "id": "cheng-yan-xiong-20",
        "title": "句",
        "author": "成彦雄",
        "poet_id": "cheng-yan-xiong",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "莎草放茵深护砌，海榴喷火巧横墙。",
            "纹鳞引子跳银海，紫燕呼雏语画梁。（见《吟窗杂录》）",
            "第七百六十卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]