# -*- coding: utf-8 -*-
"""
陈羽卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 62 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 琴曲歌辞·湘妃怨 ----------
    {
        "id": "chen-yu-1",
        "title": "琴曲歌辞·湘妃怨",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "二妃怨处云沉沉，二妃哭处湘水深。",
            "商人酒滴庙前草，萧飒风生斑竹林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 杂歌谣辞·步虚词 ----------
    {
        "id": "chen-yu-2",
        "title": "杂歌谣辞·步虚词",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "汉武清斋读鼎书，内官扶上画云车。",
            "坛上月明宫殿闭，仰看星斗礼空虚。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 公子行 ----------
    {
        "id": "chen-yu-3",
        "title": "公子行",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "金羁白面郎，何处蹋青来。马娇郎半醉，躞蹀望楼台。",
            "似见楼上人，玲珑窗户开。隔花闻一笑，落日不知回。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 古意 ----------
    {
        "id": "chen-yu-4",
        "title": "古意",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "十三学绣罗衣裳，自怜红袖闻馨香。人言此是嫁时服，",
            "含笑不刺双鸳鸯。郎年十九髭未生，拜官天下闻郎名。",
            "车马骈阗贺门馆，自然不失为公卿。是时妾家犹未贫，",
            "兄弟出入双车轮。繁华全盛两相敌，与郎年少为婚姻。",
            "郎家居近御沟水，豪门客尽蹑珠履。雕盘酒器常不干，",
            "晓入中厨妾先起。姑嫜严肃有规矩，小姑娇憨意难取。",
            "朝参暮拜白玉堂，绣衣著尽黄金缕。妾貌渐衰郎渐薄，",
            "时时强笑意索寞。知郎本来无岁寒，几回掩泪看花落。",
            "妾年四十丝满头，郎年五十封公侯。男儿全盛日忘旧，",
            "银床羽帐空飕飗。庭花红遍蝴蝶飞，看郎佩玉下朝时。",
            "归来略略不相顾，却令侍婢生光辉。郎恨妇人易衰老，",
            "妾亦恨深不忍道。看郎强健能几时，年过六十还枯槁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 长相思 ----------
    {
        "id": "chen-yu-5",
        "title": "长相思",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "相思长相思，相思无限极。相思苦相思，相思损容色。",
            "容色真可惜，相思不可彻。日日长相思，相思肠断绝。",
            "肠断绝，泪还续，闲人莫作相思曲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 送戴端公赴容州 ----------
    {
        "id": "chen-yu-6",
        "title": "送戴端公赴容州",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "分命诸侯重，葳蕤绣服香。八蛮治险阻，千骑蹋繁霜。",
            "山断旌旗出，天晴剑珮光。还将小戴礼，远出化南方。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送殷华之洪州 ----------
    {
        "id": "chen-yu-7",
        "title": "送殷华之洪州",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "离堂悲楚调，君奏豫章行。愁处雪花白，梦中江水清。",
            "扣船歌月色，避浪宿猿声。还作经年别，相思湖草生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 春日晴原野望 ----------
    {
        "id": "chen-yu-8",
        "title": "春日晴原野望",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "东风吹暖气，消散入晴天。渐变池塘色，欲生杨柳烟。",
            "蒙茸花向月，潦倒客经年。乡思应愁望，江湖春水连。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 湘妃怨 ----------
    {
        "id": "chen-yu-9",
        "title": "湘妃怨",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "舜欲省蛮陬，南巡非逸游。九山沉白日，二女泣沧洲。",
            "目极楚云断，恨连湘水流。至今闻鼓瑟，咽绝不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 冬晚送友人使西蕃 ----------
    {
        "id": "chen-yu-10",
        "title": "冬晚送友人使西蕃",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "驿使向天西，巡羌复入氐。玉关晴有雪，砂碛雨无泥。",
            "落泪军中笛，惊眠塞上鸡。逢春乡思苦，万里草萋萋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 春园即事 ----------
    {
        "id": "chen-yu-11",
        "title": "春园即事",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "水隔群物远，夜深风起频。霜中千树橘，月下五湖人。",
            "听鹤忽忘寝，见山如得邻。明年还到此，共看洞庭春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 送友人及第归江东 ----------
    {
        "id": "chen-yu-12",
        "title": "送友人及第归江东",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "五陵春色泛花枝，心醉花前远别离。落羽耻为关右客，",
            "成名空羡里中儿。都门雨歇愁分处，山店灯残梦到时。",
            "家住洞庭多钓伴，因来相贺话相思。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 梓州与温商夜别（一作夜别温商梓州） ----------
    {
        "id": "chen-yu-13",
        "title": "梓州与温商夜别（一作夜别温商梓州）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "凤凰城里花时别，玄武江边月下逢。客舍莫辞先买酒，",
            "相门曾忝共登龙。迎风骚屑千家竹，隔水悠扬午夜钟。",
            "明日又行西蜀路，不堪天际远山重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 长安卧病秋夜言怀 ----------
    {
        "id": "chen-yu-14",
        "title": "长安卧病秋夜言怀",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "九重门锁禁城秋，月过南宫渐映楼。紫陌夜深槐露滴，",
            "碧空云尽火星流。风清刻漏传三殿，甲第歌钟乐五侯。",
            "楚客病来乡思苦，寂寥灯下不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 喜雪上窦相公（一作朱湾诗） ----------
    {
        "id": "chen-yu-15",
        "title": "喜雪上窦相公（一作朱湾诗）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "千门万户雪花浮，点点无声落瓦沟。全似玉尘销更积，",
            "半成冰水结还流。光添曙色连天远，轻逐春风绕玉楼。",
            "平地已沾盈尺润，年丰须荷富人侯。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 宴杨驸马山亭（一作朱湾诗） ----------
    {
        "id": "chen-yu-16",
        "title": "宴杨驸马山亭（一作朱湾诗）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "垂杨拂岸草茸茸，绣户窗前花影重。鲙下玉盘红缕细，",
            "酒开金瓮绿醅醲。中朝驸马何平叔，南国词人陆士龙。",
            "落日泛舟同醉处，回潭百丈映千峰。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 西蜀送许中庸归秦赴举 ----------
    {
        "id": "chen-yu-17",
        "title": "西蜀送许中庸归秦赴举",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "春色华阳国，秦人此别离。驿楼横水影，乡路入花枝。",
            "日暖莺飞好，山晴马去迟。剑门当石隘，栈阁入云危。",
            "独鹤心千里，贫交酒一卮。桂条攀偃蹇，兰叶藉参差。",
            "旅梦惊蝴蝶，残芳怨子规。碧霄今夜月，惆怅上峨嵋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 小苑春望宫池柳色（一作御沟新柳） ----------
    {
        "id": "chen-yu-18",
        "title": "小苑春望宫池柳色（一作御沟新柳）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "宛宛如丝柳，含黄一望新。未成沟上暗，且向日边春。",
            "袅娜方遮水，低迷欲醉人。托空芳郁郁，逐溜影鳞鳞。",
            "弄水滋宵露，垂枝染夕尘。夹堤连太液，还似映天津。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 中秋夜临镜湖望月 ----------
    {
        "id": "chen-yu-19",
        "title": "中秋夜临镜湖望月",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "镜里秋宵望，湖平月彩深。圆光珠入浦，浮照鹊惊林。",
            "澹动光还碎，婵娟影不沉。远时生岸曲，空处落波心。",
            "迥彻轮初满，孤明魄未侵。桂枝如可折，何惜夜登临。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 江上愁思二首 ----------
    {
        "id": "chen-yu-20",
        "title": "江上愁思二首",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "江上翁开门，开门向衰草。只知愁子孙，不觉生涯老。",
            "江上草茎枯，茎枯叶复焦。那堪芳意尽，夜夜没寒潮。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 梁城老人怨（一作司空曙诗） ----------
    {
        "id": "chen-yu-21",
        "title": "梁城老人怨（一作司空曙诗）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "朝为耕种人，暮作刀枪鬼。相看父子血，共染城濠水。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 送灵一上人 ----------
    {
        "id": "chen-yu-22",
        "title": "送灵一上人",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "十年劳远别，一笑喜相逢。又上青山去，青山千万重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 23. 经夫差庙 ----------
    {
        "id": "chen-yu-23",
        "title": "经夫差庙",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "姑苏城畔千年木，刻作夫差庙里神。",
            "冠盖寂寥尘满室，不知箫鼓乐何人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 24. 九月十日即事 ----------
    {
        "id": "chen-yu-24",
        "title": "九月十日即事",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "汉江天外东流去，巴塞连山万里秋。",
            "节过重阳人病起，一枝残菊不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 25. 夏日宴九华池赠主人 ----------
    {
        "id": "chen-yu-25",
        "title": "夏日宴九华池赠主人",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷23》",
        "verse": [
            "池上凉台五月凉，百花开尽水芝香。",
            "黄金买酒邀诗客，醉倒檐前青玉床。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 26. 长安早春言志 ----------
    {
        "id": "chen-yu-26",
        "title": "长安早春言志",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷24》",
        "verse": [
            "九衢日暖树苍苍，万里吴人忆水乡。",
            "汉主未曾亲羽猎，不知将底谏君王。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 27. 读苏属国传 ----------
    {
        "id": "chen-yu-27",
        "title": "读苏属国传",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷25》",
        "verse": [
            "天山西北居延海，沙塞重重不见春。",
            "肠断帝乡遥望日，节旄零落汉家臣。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 28. 吴城览古 ----------
    {
        "id": "chen-yu-28",
        "title": "吴城览古",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷26》",
        "verse": [
            "吴王旧国水烟空，香径无人兰叶红。",
            "春色似怜歌舞地，年年先发馆娃宫。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 29. 犍为城下夜泊闻夷歌 ----------
    {
        "id": "chen-yu-29",
        "title": "犍为城下夜泊闻夷歌",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷27》",
        "verse": [
            "犍为城下牂牁路，空冢滩西贾客舟。",
            "此夜可怜江上月，夷歌铜鼓不胜愁。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 30. 和王中丞使君春日过高评事幽居 ----------
    {
        "id": "chen-yu-30",
        "title": "和王中丞使君春日过高评事幽居",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷28》",
        "verse": [
            "风光满路旗幡出，林下高人待使君。",
            "笑藉紫兰相向醉，野花千树落纷纷。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 31. 和王中丞中和日 ----------
    {
        "id": "chen-yu-31",
        "title": "和王中丞中和日",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷29》",
        "verse": [
            "节应中和天地晴，繁弦叠鼓动高城。",
            "汉家分刺诸侯贵，一曲阳春江水清。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 32. 同韦中丞花下夜饮赠歌人 ----------
    {
        "id": "chen-yu-32",
        "title": "同韦中丞花下夜饮赠歌人",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷30》",
        "verse": [
            "银烛煌煌半醉人，娇歌宛转动朱唇。",
            "繁花落尽春风里，绣被郎官不负春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 33. 若耶溪逢陆澧 ----------
    {
        "id": "chen-yu-33",
        "title": "若耶溪逢陆澧",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷31》",
        "verse": [
            "溪上春晴聊看竹，谁言驿使此相逢。",
            "担簦蹑屐仍多病，笑杀云间陆士龙。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 34. 夜泊荆溪 ----------
    {
        "id": "chen-yu-34",
        "title": "夜泊荆溪",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷32》",
        "verse": [
            "小雪已晴芦叶暗，长波乍急鹤声嘶。",
            "孤舟一夜宿流水，眼看山头月落溪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 35. 南山别僧 ----------
    {
        "id": "chen-yu-35",
        "title": "南山别僧",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷33》",
        "verse": [
            "惆怅人间多别离，梅花满眼独行时。",
            "无家度日多为客，欲共山僧何处期。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 36. 戏题山居二首 ----------
    {
        "id": "chen-yu-36",
        "title": "戏题山居二首",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷34》",
        "verse": [
            "云盖秋松幽洞近，水穿危石乱山深。",
            "门前自有千竿竹，免向人家看竹林。",
            "虽有柴门长不关，片云高木共身闲。",
            "犹嫌住久人知处，见欲移居更上山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 37. 山中秋夜喜周士闲见过 ----------
    {
        "id": "chen-yu-37",
        "title": "山中秋夜喜周士闲见过",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷35》",
        "verse": [
            "青山高处上不易，白云深处行亦难。",
            "留君不宿对秋月，莫厌山空泉石寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 38. 过栎阳山谿 ----------
    {
        "id": "chen-yu-38",
        "title": "过栎阳山谿",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷36》",
        "verse": [
            "众草穿沙芳色齐，蹋莎行草过春溪。",
            "闲云相引上山去，人到山头云却低。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 39. 姑苏台怀古 ----------
    {
        "id": "chen-yu-39",
        "title": "姑苏台怀古",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷37》",
        "verse": [
            "忆昔吴王争霸日，歌钟满地上高台。",
            "三千宫女看花处，人尽台崩花自开。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 40. 将归旧山留别 ----------
    {
        "id": "chen-yu-40",
        "title": "将归旧山留别",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷38》",
        "verse": [
            "相共游梁今独还，异乡摇落忆空山。",
            "信陵死后无公子，徒向夷门学抱关。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 41. 游洞灵观 ----------
    {
        "id": "chen-yu-41",
        "title": "游洞灵观",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷39》",
        "verse": [
            "初访西城礼少君，独行深入洞天云。",
            "风吹青桂寒花落，香绕仙坛处处闻。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 42. 旅次沔阳，闻克复，而用师者穷兵黩武，因书简之 ----------
    {
        "id": "chen-yu-42",
        "title": "旅次沔阳，闻克复，而用师者穷兵黩武，因书简之",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷40》",
        "verse": [
            "江上烟消汉水清，王师大破绿林兵。",
            "干戈用尽人成血，韩信空传壮士名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 43. 湘君祠（一作湘妃怨） ----------
    {
        "id": "chen-yu-43",
        "title": "湘君祠（一作湘妃怨）",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷41》",
        "verse": [
            "二妃怨处云沉沉，二妃哭处湘水深。",
            "商人酒滴庙前草，萧索风生斑竹林。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 44. 送辛吉甫常州觐省 ----------
    {
        "id": "chen-yu-44",
        "title": "送辛吉甫常州觐省",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷42》",
        "verse": [
            "西去兰陵家不远，到家还及采兰时。",
            "新年送客我为客，惆怅门前黄柳丝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 45. 题舞花山大师遗居 ----------
    {
        "id": "chen-yu-45",
        "title": "题舞花山大师遗居",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷43》",
        "verse": [
            "西过流沙归路长，一生遗迹在东方。",
            "空堂寂寞闭灯影，风动四山松柏香。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 46. 广陵秋夜对月即事 ----------
    {
        "id": "chen-yu-46",
        "title": "广陵秋夜对月即事",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷44》",
        "verse": [
            "霜落寒空月上楼，月中歌吹满扬州。",
            "相看醉舞倡楼月，不觉隋家陵树秋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 47. 早秋浐水送人归越 ----------
    {
        "id": "chen-yu-47",
        "title": "早秋浐水送人归越",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷45》",
        "verse": [
            "凉叶萧萧生远风，晓鸦飞度望春宫。",
            "越人归去一摇首，肠断马嘶秋水东。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 48. 小江驿送陆侍御归湖上山 ----------
    {
        "id": "chen-yu-48",
        "title": "小江驿送陆侍御归湖上山",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷46》",
        "verse": [
            "鹤唳天边秋水空，荻花芦叶起西风。",
            "今夜渡江何处宿，会稽山在月明中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 49. 送李德舆归穿石洞山居 ----------
    {
        "id": "chen-yu-49",
        "title": "送李德舆归穿石洞山居",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷47》",
        "verse": [
            "乌巾年少归何处，一片彩霞仙洞中。",
            "惆怅别时花似雪，行人不肯醉春风。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 50. 酬幽居闲上人喜及第后见赠 ----------
    {
        "id": "chen-yu-50",
        "title": "酬幽居闲上人喜及第后见赠",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷48》",
        "verse": [
            "九霄心在劳相问，四十年间岂足惊。",
            "风动自然云出岫，高僧不用笑浮生。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 51. 洛下赠彻公 ----------
    {
        "id": "chen-yu-51",
        "title": "洛下赠彻公",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷49》",
        "verse": [
            "天竺沙门洛下逢，请为同社笑相容。",
            "支颐忽望碧云里，心爱嵩山第几重。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 52. 观朱舍人归葬吴中 ----------
    {
        "id": "chen-yu-52",
        "title": "观朱舍人归葬吴中",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷50》",
        "verse": [
            "翩翩绛旐寒流上，行引东归万里魂。",
            "几处州人临水哭，共看遗草有王言。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 53. 题清镜寺留别 ----------
    {
        "id": "chen-yu-53",
        "title": "题清镜寺留别",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷51》",
        "verse": [
            "路入千山愁自知，雪花撩乱压松枝。",
            "世人并道离别苦，谁信山僧轻别离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 54. 从军行 ----------
    {
        "id": "chen-yu-54",
        "title": "从军行",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷52》",
        "verse": [
            "海畔风吹冻泥裂，枯桐叶落枝梢折。",
            "横笛闻声不见人，红旗直上天山雪。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 55. 宿淮阴作 ----------
    {
        "id": "chen-yu-55",
        "title": "宿淮阴作",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷53》",
        "verse": [
            "秋灯点点淮阴市，楚客联樯宿淮水。",
            "夜深风起鱼鳖腥，韩信祠堂明月里。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 56. 春日南山行 ----------
    {
        "id": "chen-yu-56",
        "title": "春日南山行",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷54》",
        "verse": [
            "处处看山不可行，野花相向笑无成。",
            "长嫌为客过州县，渐被时人识姓名。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 57. 步虚词二首 ----------
    {
        "id": "chen-yu-57",
        "title": "步虚词二首",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷55》",
        "verse": [
            "汉武清斋读鼎书，太官扶上画云车。",
            "坛上月明宫殿闭，仰看星斗礼空虚。",
            "楼殿层层阿母家，昆仑山顶驻红霞。",
            "笙歌出见穆天子，相引笑看琪树花。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 58. 襄阳过孟浩然旧居 ----------
    {
        "id": "chen-yu-58",
        "title": "襄阳过孟浩然旧居",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷56》",
        "verse": [
            "襄阳城郭春风起，汉水东流去不还。",
            "孟子死来江树老，烟霞犹在鹿门山。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 59. 送友人游嵩山 ----------
    {
        "id": "chen-yu-59",
        "title": "送友人游嵩山",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷57》",
        "verse": [
            "嵩山归路绕天坛，雪影松声满谷寒。",
            "君见九龙潭上月，莫辞清夜访袁安。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 60. 伏翼西洞送夏方庆 ----------
    {
        "id": "chen-yu-60",
        "title": "伏翼西洞送夏方庆",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷58》",
        "verse": [
            "洞里春晴花正开，看花出洞几时回。",
            "殷勤好去武陵客，莫引世人相逐来。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 61. 赠人 ----------
    {
        "id": "chen-yu-61",
        "title": "赠人",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷59》",
        "verse": [
            "或棹孤舟或杖藜，寻常适意钓长溪。",
            "草堂竹径在何处，落日孤烟寒渚西。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 62. 句 ----------
    {
        "id": "chen-yu-62",
        "title": "句",
        "author": "陈羽",
        "poet_id": "chen-yu",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷60》",
        "verse": [
            "稚子新能编笋笠，山妻旧解补荷衣。秋山隔岸清猿叫，",
            "湖水当门白鸟飞。（见《锦绣万花谷》）",
            "第三百四十九卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]