# -*- coding: utf-8 -*-
"""
清江卷 · 全唐诗诗作（自动解析自《全唐诗》曹寅本）
共 22 首。原文据《全唐诗》，重点名篇注释赏析据《唐诗鉴赏辞典》等权威典籍。
"""

POEMS_LOCAL = [
    # ---------- 1. 早发陕州途中赠严秘书 ----------
    {
        "id": "qing-jiang-1",
        "title": "早发陕州途中赠严秘书",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷1》",
        "verse": [
            "此身虽不系，忧道亦劳生。万里江湖梦，千山雨雪行。",
            "人家依旧垒，关路闭层城。未尽交河虏，犹屯细柳兵。",
            "艰难嗟远客，栖托赖深情。贫病吾将有，精修许少卿。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 2. 早春书情寄河南崔少府 ----------
    {
        "id": "qing-jiang-2",
        "title": "早春书情寄河南崔少府",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷2》",
        "verse": [
            "春日春风至，阳和似不均。病身空益老，愁鬓不知春。",
            "宇宙成遗物，光阴促幻身。客游伤末路，心事向行人。",
            "道薄犹怀土，时难欲厌贫。微才如可寄，赤县有乡亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 3. 春游司直城西鸬鹚谿别业 ----------
    {
        "id": "qing-jiang-3",
        "title": "春游司直城西鸬鹚谿别业",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷3》",
        "verse": [
            "别墅军城下，闲喧未可齐。春深花蝶梦，晓隔柳烟鞞。",
            "韶景浮寒水，疏杨映绿堤。沿洄看竹色，来往听莺啼。",
            "久慢持生术，多亲种药畦。家贫知素行，心苦见清溪。",
            "越客初投分，南枝得寄栖。禅机空寂寞，雅趣赖招携。",
            "本寺重江外，游方二室西。裴回恋知己，日夕草萋萋。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 4. 夕次襄邑 ----------
    {
        "id": "qing-jiang-4",
        "title": "夕次襄邑",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷4》",
        "verse": [
            "何处戒吾道，经年远路中。客心犹向北，河水自归东。",
            "古戍鸣寒角，疏林振夕风。轻舟惟载月，那与故人同。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 5. 宿严维宅简章八元（一作宿严秘书宅） ----------
    {
        "id": "qing-jiang-5",
        "title": "宿严维宅简章八元（一作宿严秘书宅）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷5》",
        "verse": [
            "佳期曾不远，甲第即南邻。惠爱偏相及，经过岂厌频。",
            "秋寒林叶动，夕霁月华新。莫话羁栖事，平原是主人。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 6. 赠淮西贾兵马使 ----------
    {
        "id": "qing-jiang-6",
        "title": "赠淮西贾兵马使",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷6》",
        "verse": [
            "破虏功成百战场，天书新拜汉中郎。映门旌旆春风起，",
            "对客弦歌白日长。阶下斗鸡花乍发，营南试马柳初黄。",
            "由来吴楚多同调，感激逢君共异乡。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 7. 送坚上人归杭州天竺寺 ----------
    {
        "id": "qing-jiang-7",
        "title": "送坚上人归杭州天竺寺",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷7》",
        "verse": [
            "十年劳负笈，经论化中朝。流水知乡近，和风惜别遥。",
            "云山零夜雨，花岸上春潮。归卧南天竺，禅心更寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 8. 送赞律师归嵩山（一作无可诗） ----------
    {
        "id": "qing-jiang-8",
        "title": "送赞律师归嵩山（一作无可诗）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷8》",
        "verse": [
            "禅意归心急，山深定易安。清贫修道苦，孝友别家难。",
            "雪路侵溪转，花宫映岳看。到时瞻塔暮，松月向人寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 9. 上都酬章十八兄 ----------
    {
        "id": "qing-jiang-9",
        "title": "上都酬章十八兄",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷9》",
        "verse": [
            "每叹经年别，人生有几年。关河长问道，风雨独随缘。",
            "寓蝶成庄梦，怀人识祢贤。徽猷不及此，空愧白华篇。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 10. 登楼望月寄凤翔李少尹 ----------
    {
        "id": "qing-jiang-10",
        "title": "登楼望月寄凤翔李少尹",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷10》",
        "verse": [
            "陌上凉风槐叶凋，夕阳秋露湿寒条。登楼望月楚山上，",
            "月到楼南山独遥。心送秦人趋凤阙，月随阳雁极烟霄。",
            "轩车不重无名客，此地谁能访寂寥。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 11. 湘川怀古 ----------
    {
        "id": "qing-jiang-11",
        "title": "湘川怀古",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷11》",
        "verse": [
            "潇湘连汨罗，复对九嶷河。浪势屈原冢，竹声渔父歌。",
            "地荒征骑少，天暖浴禽多。脉脉东流水，古今同奈何。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 12. 七夕 ----------
    {
        "id": "qing-jiang-12",
        "title": "七夕",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷12》",
        "verse": [
            "七夕景迢迢，相逢只一宵。月为开帐烛，云作渡河桥。",
            "映水金冠动，当风玉珮摇。惟愁更漏促，离别在明朝。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 13. 长安卧病 ----------
    {
        "id": "qing-jiang-13",
        "title": "长安卧病",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷13》",
        "verse": [
            "身世足堪悲，空房卧病时。卷帘花雨滴，扫石竹阴移。",
            "已觉生如梦，堪嗟寿不知。未能通法性，讵可免支离。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 14. 送婆罗门（一作可止诗） ----------
    {
        "id": "qing-jiang-14",
        "title": "送婆罗门（一作可止诗）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷14》",
        "verse": [
            "雪岭金河独向东，吴山楚泽意无穷。",
            "如今白首乡心尽，万里归程在梦中。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 15. 喜皇甫大夫同宿大梁驿 ----------
    {
        "id": "qing-jiang-15",
        "title": "喜皇甫大夫同宿大梁驿",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷15》",
        "verse": [
            "江头旌旆去，花外卷帘空。夜色临城月，春声渡水风。",
            "也知行李别，暂喜话言同。若问庐山事，终身愧远公。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 16. 酬姚补阙南仲云溪馆中戏题随书见寄 ----------
    {
        "id": "qing-jiang-16",
        "title": "酬姚补阙南仲云溪馆中戏题随书见寄",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷16》",
        "verse": [
            "寺溪临使府，风景借仁祠。补衮周官贵，能名汉主慈。",
            "卧云知独处，望月忆同时。忽枉缄中赠，琼瑶满手持。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 17. 喜严侍御蜀还赠严秘书 ----------
    {
        "id": "qing-jiang-17",
        "title": "喜严侍御蜀还赠严秘书",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷17》",
        "verse": [
            "往年分首出咸秦，木落花开秋又春。江客不曾知蜀路，",
            "旅魂何处访情人。当时望月思文友，今日迎骢见近臣。",
            "多羡二龙同汉代，绣衣芸阁共荣亲。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 18. 送韦参军江陵（一作戴叔伦诗） ----------
    {
        "id": "qing-jiang-18",
        "title": "送韦参军江陵（一作戴叔伦诗）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷18》",
        "verse": [
            "槐花落尽柳阴清，萧索凉天楚客情。海上旧山无的信，",
            "东门归路不堪行。身随幻境劳多事，迹学禅心厌有名。",
            "公子道存知不弃，欲依刘表住南荆。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 19. 月夜有怀黄端公兼简朱孙二判官 ----------
    {
        "id": "qing-jiang-19",
        "title": "月夜有怀黄端公兼简朱孙二判官",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷19》",
        "verse": [
            "月照疏林惊鹊飞，羁人此夜共无依。青门旅寓身空老，",
            "白首头陀力渐微。屡向曲池陪逸少，几回戎幕接玄晖。",
            "四科弟子称文学，五马诸侯是绣衣。江雁往来曾不定，",
            "野云摇曳本无机。修行未尽身将尽，欲向东山掩旧扉。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 20. 精舍遇雨（一作可止诗） ----------
    {
        "id": "qing-jiang-20",
        "title": "精舍遇雨（一作可止诗）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷20》",
        "verse": [
            "空门寂寂淡吾身，溪雨微微洗客尘。",
            "卧向白云情未尽，任他黄鸟醉芳春。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 21. 小雪（一作可止诗） ----------
    {
        "id": "qing-jiang-21",
        "title": "小雪（一作可止诗）",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷21》",
        "verse": [
            "落雪临风不厌看，更多还恐蔽林峦。",
            "愁人正在书窗下，一片飞来一片寒。",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
    # ---------- 22. 句 ----------
    {
        "id": "qing-jiang-22",
        "title": "句",
        "author": "清江",
        "poet_id": "qing-jiang",
        "dynasty": "唐",
        "genre": "古诗",
        "year": "",
        "source": "《全唐诗·卷22》",
        "verse": [
            "万木无一叶，客心悲此时。（秋日晚泊，见《吟窗杂录》）",
            "第八百一十三卷",
        ],
        "tijie": "",
        "notes": [],
        "appreciation": "",
        "famous": [],
        "sources": ["《全唐诗》曹寅本"],
    },
]